### ISSUE TITLE
Windows image clarification

### ISSUE THREAD

**Issue by raluca256** [MicrosoftDocs/azure-stack-docs#10]
Hello, Would it be possible to add a clarification on the need to download new version of Windows Server images? It is not clear to me if the images downloaded are automatically updated with the new OS fixes and new versions of guest OS, or if the admin must manually replace the images periodically to have the latest updates available. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2945c53e-1796-2a51-7de8-55b6289f319c
* Version Independent ID: a879ecd5-7baa-c3d1-4197-863124c6978c
* Content: [Azure Marketplace items available for Azure Stack](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-marketplace-azure-items)
* Content Source: [articles/azure-stack/azure-stack-marketplace-azure-items.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-marketplace-azure-items.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
Hi @raluca256 -- thanks for reaching out. We have added this section to the release notes: https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-release-notes-1904#security-updates. In addition, we added this topic to help clarify: https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-release-notes-security-updates-1904. Please let us know if that is sufficient.

**Comment by raluca256** [comment]
Hello Seth! Thanks for the info. It's great that this note and the article were added but I was asking about the guest OSs running on the stamp, not the infra ones. I got my answer earlier this year, but it would be nice if the information would be publicly available. Please let me know if something was published on this topic (updating Windows guest VMs on Azure Stack) or will be published. Thank you!

**Comment by sethmanheim** [comment]
@raluca256 Hi Raluca, sorry for the slow response. We have added this to our doc backlog and will publish an update as soon as possible. Thanks again for the feedback. #please-close
