### ISSUE TITLE
CloudID

### ISSUE THREAD

**Issue by david-dell** [MicrosoftDocs/azure-stack-docs#1002]
In the current version of this document, you require the user to obtain the CloudID, however you never actually mention what you need it for? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19119cef-de12-31e5-d0b6-b95f2985f57e
* Version Independent ID: 5a7921c1-ac2e-6de8-0e8d-de9f04e457a6
* Content: [Register Azure Stack Hub with Azure - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-registration?view=azs-2005&pivots=state-connected)
* Content Source: [azure-stack/operator/azure-stack-registration.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-registration.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by TravisCragg-MSFT** [comment]
@david-dell Thanks for the feedback! I do not see the Cloud ID being used anymore, it is likely a remnant from a past registration method. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by Justinha** [comment]
@TravisCragg-MSFT We will add an explanation here: https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-find-cloud-id?view=azs-2005 and link to it from the registration topic. 

The Cloud ID is the unique ID for tracking support data uploaded from a specific scale unit. When diagnostic logs get uploaded for support analysis, the Cloud ID is how they are associated to that scale unit. 

@david-dell Thanks for the question!
