### ISSUE TITLE
Changes for new AKS engine 0.55.0 version

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1003]
1. In section "Steps to upgrade to a newer Kubernetes version", step 1. Replace "The versions of Kubernetes supported in the latest update are 1.14.7 and 1.15.10. Follow this table for the upgrades available:" and the table right below that. for the following:
"To see the latest updat supported see the release notes here link:https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2005#aks-engine-and-azure-stack-version-mapping"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f23e9819-30aa-02a8-08af-49b92c61316b
* Version Independent ID: a0b1770c-1ddc-17b6-2461-b4d77f474ca4
* Content: [Upgrade a Kubernetes cluster on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-upgrade?view=azs-2005)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-upgrade.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-upgrade.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks! 

#in-progress

**Comment by mattbriggs** [comment]
@walterov https://review.docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-upgrade?view=azs-1802&branch=pr-en-us-4879

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by mattbriggs** [comment]
#please-close
