### ISSUE TITLE
New version of AKS engine v0.55.0

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1004]
1. In section "Prerequisites for the AKS engine" fine the image version in the table "AKS Base Ubuntu 16.04-LTS Image Distro, May 2020 (2020.05.13)" and replace it for "AKS Base Ubuntu 16.04-LTS Image, August 2020 (2020.08.24)"

2. Find all the refernces to "v0.51.0" and replace them for ""v0.55.0"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a537721-93a2-202f-abf5-6d0fe560fef0
* Version Independent ID: 676263bc-6c11-4fd4-0318-5d2504c1b014
* Content: [Set up the prerequisites for the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-set-up?view=azs-2005)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-set-up.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-set-up.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks! 

#in-progress

**Comment by mattbriggs** [comment]
@walterov https://review.docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-set-up?view=azs-1802&branch=pr-en-us-4879
