### ISSUE TITLE
New version of AKS Engine v0.55.0

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1005]
Find all refernces to "v0.51.0" and replace them to "v0.55.0"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d8c6cbd-54d8-9746-a1f8-a618b98e011e
* Version Independent ID: 479c631e-b7a4-c5cf-160d-141d336ad50a
* Content: [Install the AKS engine on Linux in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux?view=azs-2005)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks! 

#in-progress

**Comment by mattbriggs** [comment]
@Walterov https://review.docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux?view=azs-1802&branch=pr-en-us-4879

**Comment by mattbriggs** [comment]
#please-close
