### ISSUE TITLE
New version of AKS Engine v0.55.0

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1006]
replace all references o 0.51.0 to 0.55.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 374a2d3f-fc08-7479-678e-cc1b28fa09c3
* Version Independent ID: 56139164-d119-c4e5-de98-3bf7cb0702bc
* Content: [Deploy the AKS engine on Windows in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-windows?view=azs-2005)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-windows.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-windows.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks! 

#in-progress

**Comment by mattbriggs** [comment]
@walterov https://review.docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-windows?view=azs-1802&branch=pr-en-us-4879

**Comment by mattbriggs** [comment]
#please-close
