### ISSUE TITLE
Collect AKS engine logs - confusing

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-stack-docs#1018]
was going through this part and seems confusing at least for me. 
Seems that command is not correct **aks-engine --output-directory <path to the directory>**
as **aks-engine get-logs** has this switch "--output-directory"
also, it is not clear if this process do the same as next section for **Collect Kubernetes logs**, since its required parameters are below and they seem collecting logs using script from K8S nodes.
Flags:
  -m, --api-model string               path to the generated apimodel.json file (required)
      --control-plane-only             get logs from control plane VMs only
  -h, --help                           help for get-logs
      --linux-script string            path to the log collection script to execute on the cluster's Linux nodes (required)
      --linux-ssh-private-key string   path to a valid private SSH key to access the cluster's Linux nodes (required)
  -l, --location string                Azure location where the cluster is deployed (required)
  -o, --output-directory string        collected logs destination directory, derived from --api-model if missing
      --ssh-host string                FQDN, or IP address, of an SSH listener that can reach all nodes in the cluster (required)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143ccfc6-64a1-f7d9-e9ec-7e0b313f1f15
* Version Independent ID: e59d1050-1d82-0792-dd64-7f0fa9816605
* Content: [Troubleshoot the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot?view=azs-2005)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@HassanAlmanasrah Thanks for the feedback! The Get-Logs part of aks-engine was added recently, and likely needs to be updated here as well. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@@HassanAlmanasrah I'll check this. Thanks! #in-progress

**Comment by mattbriggs** [comment]
@HassanAlmanasrah Thanks for calling out the missing command. I've double checked the aks-engine and we are missing the command get-logs in the instructions. I've updated. The logs with the command aks-engine get-logs, 'Collect logs and current cluster nodes configuration.' This is seperate process from the full range of info collected by the getkuberneteslogs.sh. Without this script, you would need to connect to each node in the cluster locate and download the logs manually.

**Comment by mattbriggs** [comment]
Here is the PR with the fix: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/4957

**Comment by mattbriggs** [comment]
#please-close
