### ISSUE TITLE
Missed version for image in example phrase

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1020]
Section "Matching engine to base image version", need to replace "2020.05.13" for "2020.08.24"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a537721-93a2-202f-abf5-6d0fe560fef0
* Version Independent ID: 676263bc-6c11-4fd4-0318-5d2504c1b014
* Content: [Set up the prerequisites for the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-set-up?view=azs-2005#prerequisites-for-the-aks-engine)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-set-up.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-set-up.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks! fixed. #in-progress

**Comment by mattbriggs** [comment]
https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/4955/commits/fc7cebf1f0354e6cb28089c8fbfdc0f496a4f7d0

**Comment by mattbriggs** [comment]
#please-close
