### ISSUE TITLE
We need to add a section on "Version support"

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1025]
Add a new section to this article title: "Version support". With this paragraph:

The AKS engine version support follows the same pattern established by the rest of the Azure Stack Hub support policy, that is support of a version of AKS engine on Azure Stack Hub is based on the n-2 formula. For example, if the latest version of AKS engine is v0.55.0, the set of supported versions are: 0.48.0, 0.51.0, 0.55.0. Also important it to follow the Azure Stack Hub update version and corresponding mapping to AKS engine supported version, this is maintain in the AKS engine release notes (https://review.docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2008&branch=pr-en-us-4879#aks-engine-and-azure-stack-version-mapping)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95fd6a25-af7a-737d-24e4-f2c7947f0aba
* Version Independent ID: d1ef3fa8-733d-1802-59c9-5b54f7069d43
* Content: [Support policies for AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-support?view=azs-2005)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-support.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-support.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks! #in-progress

**Comment by mattbriggs** [comment]
@walterov For your review: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5006

**Comment by mattbriggs** [comment]
updated

#please-close
