### ISSUE TITLE
Outbound URLs for Diagnostic Log Collection do not include prod SAS URI DNs name azsdiagprdlocalwestus

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1027]
Outbound URLs for **Diagnostic Log Collection** do not include prod SAS Uri DNS name azsdiagprdlocalwestus

Current doc, outbound endpoints:
**Diagnostic Log Collection**
https://azsdiagppelocalwestus02.blob.core.windows.net
https://azsdiagppewestusfrontend.westus.cloudapp.azure.com
https://azsdiagprdwestusfrontend.westus.cloudapp.azure.com

Example prod SASUri starts with- https://azsdiagprdlocalwestus.blob.core.windows.net
(From https://azsdiagprdwestusportal.westus.cloudapp.azure.com/)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d02f93-1ae9-eb2d-9c0f-0af012653885
* Version Independent ID: 18f15ad2-ef9b-f883-c49b-09289a2e6fb8
* Content: [Publish Azure Stack Hub services in your datacenter - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-endpoints?view=azs-2005#ports-and-urls-outbound)
* Content Source: [azure-stack/operator/azure-stack-integrate-endpoints.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-endpoints.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by Justinha** [comment]
@alexsmithMSFT thanks for the feedback! We have some follow up questions for you and will update the topic after.

**Comment by alexsmithMSFT** [comment]
Pending input from PG. Based on conversation so far this...
https://azsdiagppelocalwestus02.blob.core.windows.net
...will become one of these (not both):
https://azsdiag*.blob.core.windows.net
https://*.blob.core.windows.net

For the others, not sure if we remove the PPE endpoint-
https://azsdiagppewestusfrontend.westus.cloudapp.azure.com **(REMOVE?)**
https://azsdiagprdwestusfrontend.westus.cloudapp.azure.com
https://azsdiagprdlocalwestus.blob.core.windows.net **(ADD)**

**Comment by myoungerman** [comment]
@alexsmithMSFT Fixed this, thanks! 

https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5223
