### ISSUE TITLE
Initial feedback.

### ISSUE THREAD

**Issue by slinehan** [MicrosoftDocs/azure-stack-docs#1029]
I would consider changing this paragraph a bit to lead not only with the feature but that it is with the customers consent.  I would also rephrase the benefit to ensure we are not setting a false expectation.  So from this:

"The Azure Stack Hub remote support feature enables Microsoft Support to perform support operations remotely on your Azure Stack Hub device. Remote support lets Microsoft Support diagnose and fix your problem faster than other support methods."

to something like this:

_The Azure Stack Hub remote support feature enables Microsoft Support to perform support operations on your behalf remotely against your Azure Stack Hub.  This capability is only enabled once you have granted consent and enables you to fully control the level and duration of your consent. Remote support lets Microsoft Support diagnose and remediate your problem in a more efficient manner than traditional support channels._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e24692e9-d36f-4bea-a2b7-cb56787f04e5
* Version Independent ID: dea4734a-76e4-d0bf-5b93-db93477287cb
* Content: [Azure Stack Hub remote support - Azure Stack Hub](https://review.docs.microsoft.com/en-us/azure-stack/operator/remote-support?view=azs-1802&branch=pr-en-us-4624)
* Content Source: [azure-stack/operator/remote-support.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/remote-support.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TravisCragg-MSFT** [comment]
@slinehan Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by myoungerman** [comment]
@TravisCragg-MSFT I've updated the article text since this issue was opened, so the text is clearer now. Thanks!

**Comment by PatAltimore** [comment]
#please-close
