### ISSUE TITLE
The link for Azure Active Directory Module for Windows PowerShell (64-bit version) does not work

### ISSUE THREAD

**Issue by rohernan** [MicrosoftDocs/azure-stack-docs#103]
This program is no longer hosted on that link (MS Connect).  For more info go here:
https://docs.microsoft.com/en-us/office365/enterprise/powershell/connect-to-office-365-powershell

Therefore do these from that article:

Step 1: Install required software
These steps are required once on your computer, not every time you connect. However, you'll likely need to install newer versions of the software periodically.

Install the 64-bit version of the Microsoft Online Services Sign-in Assistant: Microsoft Online Services Sign-in Assistant for IT Professionals RTW.

Install the Microsoft Azure Active Directory Module for Windows PowerShell with these steps:

Open an elevated Windows PowerShell command prompt (run Windows PowerShell as an administrator).
Run the Install-Module MSOnline command.
If prompted to install the NuGet provider, type Y and press ENTER.
If prompted to install the module from PSGallery, type Y and press ENTER.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2adbad-6f3d-02af-c936-694f98597cb9
* Version Independent ID: fdc8c0cb-eb86-0b3a-595c-162e18f67d54
* Content: [Add a new Azure Stack tenant account in Azure Active Directory](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-add-new-user-aad#feedback)
* Content Source: [azure-stack/operator/azure-stack-add-new-user-aad.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-add-new-user-aad.md)
* Service: **azure-stack**
* GitHub Login: @PatrickA
* Microsoft Alias: **patricka**

**Comment by TravisCragg-MSFT** [comment]
@rohernan Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by PatAltimore** [comment]
@rohernan, Thanks for the feedback. I'm getting the change reviewed.

Thanks,
Pat

#in-progress

**Comment by PatAltimore** [comment]
@rohernan, Thanks for the suggested fix. I've pushed a change to fix it. It should be published soon.

Thanks,
Pat

#please-close

**Comment by TravisCragg-MSFT** [comment]
@rohernan We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
