### ISSUE TITLE
Need new Issue section for 0.55.0

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1031]
We need to add a new section title: "Disk detach operation fails in AKS Engine 0.55.0" and the following as content.

When the Kubernetes user tries to delete a deployment that contains Persistence Volumes, the user will notice a series of attach/detach errors associate to the delete operation. This is due to a bug in AKS Engine v0.55.0 Cloud Provider whereas the Cloud Provider calls ARM using a newer version of the API than ARM currently supports in Azure Stack Hub update 2005.  Please find the details and mitigation steps in the following link:   https://github.com/Azure/aks-engine/issues/3817#issuecomment-691329443. We encourage our users to upgrade as soon as a new build of AKS Engine and corresponding image are available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bddc138b-1b2e-4be5-d38b-91818ccf1922
* Version Independent ID: fb4f2341-8ca1-f849-05f5-5b4ce22b9462
* Content: [Known issues with the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues?view=azs-2005)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov #in-progress

**Comment by mattbriggs** [comment]
@walterov https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5027

**Comment by mattbriggs** [comment]
#please-close
