### ISSUE TITLE
Infrastructure Backup size requirements do not add up correctly

### ISSUE THREAD

**Issue by jgallucci32** [MicrosoftDocs/azure-stack-docs#1032]
The math is incorrect for the recommended size of the backup directory. Seven backups @10GB per backup would be 70GB, not 140GB. Given the default setting for Infrastructure Backup is 2 backups per day, I think this means to say "Fourteen or 14" backups which would add up to 140GB total.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8873f195-3d34-8940-8019-90d4d99b16bf
* Version Independent ID: 09b13864-5ef5-d148-9a6e-004661970735
* Content: [Recover data in Azure Stack Hub with the Infrastructure Backup Service - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-backup-infrastructure-backup?view=azs-2005)
* Content Source: [azure-stack/operator/azure-stack-backup-infrastructure-backup.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-backup-infrastructure-backup.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by RohitMungi-MSFT** [comment]
@jgallucci32 Thanks for the feedback. We are investigating the issue and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@jgallucci32 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by myoungerman** [comment]
@RohitMungi-MSFT @TravisCragg-MSFT I've updated the article as appropriate. Thanks! 

https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5212

**Comment by PatAltimore** [comment]
@TravisCragg-MSFT Please assign to me @PatAltimore

**Comment by PatAltimore** [comment]
Checked update was published. 

#please-close
