### ISSUE TITLE
New patch release for AKS Engine v0.55.4

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1036]
In this page we need to:

1. Change references to AKS engine version "0.55.0" for "v0.55.4" (let's make sure we use the "v")
2. Change references to image "2020.08.24" for "2020.09.14 and "August 2020" for "September 2020"
3. Add a new bullet point to "What's new"
   Update Azure Stack's Linux VHD to 2020.09.14 (#3828 <link: https://github.com/Azure/aks-engine/pull/3828>). Fix to issue #3817 (disk detachment errors)
4. Add a new version to the table in "AKS engine and Azure Stack version mapping"
2005 | 0.48.0, 0.51.0, 0.55.0, 0.55.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2005)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks! https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5078

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
#please-close
