### ISSUE TITLE
replace v0.55.0 for v0.55.4 and 2020.08.24 for 2020.09.14

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1037]
In this page we need to:

replace v0.55.0 for v0.55.4 and 2020.08.24 for 2020.09.14

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2005)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks! https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5078

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
#please-close
