### ISSUE TITLE
Release notes is missing the latest fix bullet item

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1039]
In the "what's new" section add this fix:

Update Azure Stack's Linux VHD to 2020.09.14 #3828 <TODO:#3828 should point to https://github.com/Azure/aks-engine/pull/3828>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2005)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@walterov Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@walterov Sorry this slipped through the cracks. Updated:
https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5224

#in-progress

**Comment by mattbriggs** [comment]
Updated.

#please-close
