### ISSUE TITLE
Service principal steps use App registrations (Legacy) which will be depricated this month (May 2019)

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#104]
The steps under "Create a service principal" appear to be using Azure Portal blade now called "App registrations (Legacy)".
Per the public Azure portal- "App registrations (Legacy) will be replaced and no longer available starting May 2019. Go to the new and improved App registrations (now Generally Available)."

Please update this document to use the new-style App Registrations before the old one is unavailable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60c4726-881a-a32c-6a85-25ca65a31c00
* Version Independent ID: a40334b6-dca7-52f7-62c3-3b8ecba6d606
* Content: [Deploy Kubernetes to Azure Stack using Azure Active Directory (Azure AD)](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-template-kubernetes-azuread#create-a-service-principal)
* Content Source: [azure-stack/user/azure-stack-solution-template-kubernetes-azuread.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-solution-template-kubernetes-azuread.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@alexsmithMSFT Thanks Alex. I saw your email and got one of our SPN topics updated, but missed this one. Thanks for sending the note. I'll update. #in-progress

**Comment by mattbriggs** [comment]
Updated. #sign-off

**Comment by alexsmithMSFT** [comment]
Thanks @mattbriggs but I don't see the change yet in this repo or on the public site. Can I see it in another fork somewhere?

**Comment by TravisCragg-MSFT** [comment]
@alexsmithMSFT The updates can take up to 24 hours to show on the live doc. If for some reason it does not show up on Monday, please let me know!

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
