### ISSUE TITLE
Use Test-AzureStack SecretRotationReadiness group

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1052]
In Prerequisites section, under first step to run Test-AzureStack, this page should reference the new-ish validation group for secret rotation:
`Test-AzureStack -Group SecretRotationReadiness`

For reference- https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-diagnostic-test?view=azs-2005#groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4feaa2a-4850-478d-8122-7eb751ba0777
* Version Independent ID: f5cd7372-0443-3f2e-c403-ed7ba1a56146
* Content: [Rotate secrets - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-2005#update-the-bmc-credential)
* Content Source: [azure-stack/operator/azure-stack-rotate-secrets.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-rotate-secrets.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
@alexsmithMSFT - thanks much for the contribution. The changes are in staging and will publish in the next business day.

#please-close
