### ISSUE TITLE
BMC Credential step confuses interactive PEP session

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1053]
Step #3 under [Update the BMC credential](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-2005#update-the-bmc-credential) is worded in a confusing way.

> After your PowerShell prompt has changed to [IP address or ERCS VM name]: PS>, or to [azs-ercs01]: PS>, depending on the environment, run Set-BmcCredential by running **Invoke-Command**. 

If you are **inside** the locked PEP session, you will see the "PS>", but then you can't run the command using **Invoke-Command** as described. To set the BMC credential while in an interactive PEP session, you would have to run **Set-BmcCredential** and manually type out the parameter values, which isn't ideal.

The example script given in the doc is a better example, where a session object is created with New-PSSession, which won't change the powershell prompt, and then the BMC command is run using **Invoke-Command**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4feaa2a-4850-478d-8122-7eb751ba0777
* Version Independent ID: f5cd7372-0443-3f2e-c403-ed7ba1a56146
* Content: [Rotate secrets - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-2005#update-the-bmc-credential)
* Content Source: [azure-stack/operator/azure-stack-rotate-secrets.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-rotate-secrets.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
Resolved in azure-stack-docs-pr PR #5216.
#please-close
