### ISSUE TITLE
Doc how to create custom environment is incomplete, no information for Dogfood

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/azure-stack-docs#1059]
Currently the doc says how to create a custom environment for Azure Stack Hub. But no word about how to add fully custom Azure environment, such as Microsoft Azure Dogfood.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aa954f6-471e-fb07-ad81-d3c389b8d1ea
* Version Independent ID: c80b0c02-9292-c5e1-d7df-c37db7aa2c42
* Content: [Connect Storage Explorer to Azure Stack Hub subscription or storage account - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-storage-connect-se?view=azs-2005#connect-to-an-azure-stack-hub-subscription-with-ad-fs-account)
* Content Source: [azure-stack/user/azure-stack-storage-connect-se.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-storage-connect-se.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SwathiDhanwada-MSFT** [comment]
@abatishchev Thanks for your comment. We will review the issue and get back to you shortly.

**Comment by TravisCragg-MSFT** [comment]
@abatishchev This doc (and repository) is designed to be specific for [Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-overview?view=azs-2005). 

If you need assistance with Storage Explorer on an issue unrelated to Azure Stack, your best bet is to [ask that question on Azure Storage Explorer's doc page](https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=windows#connect-to-a-storage-account-or-service).

**Comment by abatishchev** [comment]
hi @TravisCragg-MSFT,
I got this link from ASE itself:

![image](https://user-images.githubusercontent.com/351644/94603101-a7253100-024a-11eb-946e-7ff4f13a3842.png)
and then

![image](https://user-images.githubusercontent.com/351644/94603158-ba380100-024a-11eb-9234-6517d11bb4d8.png)

If the dropdown item was called "New Azure Stack Hub Environment" I would not have questions.

Can you please work with ASE team to either rename it (to avoid further confusion) or make it truly generic (how it appears now)?

**Comment by mattbriggs** [comment]
@cawaMS @abatishchev I've added the github alias for the Get Started with Storage Explorer here. Thanks again for your feedback.

Thanks, Matt

#please-close
