### ISSUE TITLE
Need to add the "v" to 0.55.4

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1064]
Change this line ./get-akse.sh --version 0.55.4

for this one

./get-akse.sh --version v0.55.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d8c6cbd-54d8-9746-a1f8-a618b98e011e
* Version Independent ID: 479c631e-b7a4-c5cf-160d-141d336ad50a
* Content: [Install the AKS engine on Linux in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux?view=azs-2005)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov #in-progress

**Comment by mattbriggs** [comment]
@walterov preview: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5275/commits/204d52e587a6d1c9e622d1e48f61845bf58330ca

**Comment by mattbriggs** [comment]
Merging... #please-close
