### ISSUE TITLE
Need to upgrade script version to v0.1.5

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1068]
This link: https://github.com/msazurestackworkloads/azurestack-gallery/releases/tag/diagnosis-v0.1.3
should change to https://github.com/msazurestackworkloads/azurestack-gallery/releases/tag/diagnosis-v0.1.5

This command:

wget https://github.com/msazurestackworkloads/azurestack-gallery/releases/download/diagnosis-v0.1.1/diagnosis-v0.1.1.tar.gz
tar xvf diagnosis-v0.1.1.tar.gz -C ./

Should change to:

wget https://github.com/msazurestackworkloads/azurestack-gallery/releases/download/diagnosis-v0.1.5/diagnosis-v0.1.5.tar.gz
tar xvf diagnosis-v0.1.5.tar.gz -C ./

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143ccfc6-64a1-f7d9-e9ec-7e0b313f1f15
* Version Independent ID: e59d1050-1d82-0792-dd64-7f0fa9816605
* Content: [Troubleshoot the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot?view=azs-2005)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov #in-progress

**Comment by mattbriggs** [comment]
@walterov Here is the change: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5290/files

**Comment by mattbriggs** [comment]
Updated.

#please-close
