### ISSUE TITLE
Change the the Log list

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1072]
Replace the entire list of logs described under "This script automates the process of gathering the following logs:" with:

- Log files in directory /var/log/azure/
- Log files in directory /var/log/kubeaudit (kube audit logs)
- Log file /var/log/waagent.log (waagent)
- Log file /var/log/azure/deploy-script-dvm.log (if deployed using Azure Stack's Kubernetes Cluster marketplace item)
- Static manifests in directory /etc/kubernetes/manifests
- Static addons in directory /etc/kubernetes/addons
- kube-system containers metadata and logs
- kubelet status and journal
- etcd status and journal
- docker status and journal
- kube-system snapshot
- Azure CNI config files

Some additional logs are retrieved for Windows nodes:

- Log file c:\Azure\CustomDataSetupScript.log
- kube-proxy status and journal
- containerd status and journal
- azure-vnet log and azure-vnet-telemetry log
- ETW events for docker
- ETW events for Hyper-V

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143ccfc6-64a1-f7d9-e9ec-7e0b313f1f15
* Version Independent ID: e59d1050-1d82-0792-dd64-7f0fa9816605
* Content: [Troubleshoot the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot?view=azs-2005#collect-kubernetes-logs)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by AnuragSharma-MSFT** [comment]
@walterov Thank you for the feedback. We are actively investigating and will get back to you soon.

**Comment by GitaraniSharma-MSFT** [comment]
@TravisCragg-MSFT , could you please take a look into this feedback?

**Comment by walterov** [comment]
Hi Team, I'm the PM for this product, we need these changes to be applied. Could you review language and proceed? Thanks!

**Comment by walterov** [comment]
Please check with @mattbriggs, he normally manages this content. Thanks!

**Comment by mattbriggs** [comment]
@walterov in-progress

**Comment by mattbriggs** [comment]
@walterov updated: https://review.docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot?view=azs-1802&branch=pr-en-us-5335

**Comment by mattbriggs** [comment]
#please-close
