### ISSUE TITLE
Unable to managed user subscription resources

### ISSUE THREAD

**Issue by luqmanawawi86** [MicrosoftDocs/azure-stack-docs#109]
As an CSP Azure stack provider, I have folllowed above steps but unable to carry out task #3:
==
Your CSP should create a resource in your subscription to verify that they can manage your resources.
==

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11a1cde5-1b89-2868-4768-3e2c55cee5a1
* Version Independent ID: 670abaf8-6088-b5a8-e13b-36930c40d74e
* Content: [Enable a Cloud Service Provider to manage your Azure Stack subscription](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-csp-enable-billing-usage-tracking#feedback)
* Content Source: [azure-stack/user/azure-stack-csp-enable-billing-usage-tracking.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-csp-enable-billing-usage-tracking.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by msrini-MSFT** [comment]
@luqmanawawi86 , Thank you for your feedback. We will take a look and get back to you shortly.

**Comment by TravisCragg-MSFT** [comment]
@luqmanawawi86 You will need to look at why you are unable to create the resource. Does it give any error message when you try to create a virtual machine or other resource?

**Comment by TravisCragg-MSFT** [comment]
@luqmanawawi86 Since we have not heard back from you we wil now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
