### ISSUE TITLE
windowss typo

### ISSUE THREAD

**Issue by MatthiasMerk** [MicrosoftDocs/azure-stack-docs#1094]
There's a typo in the taint yaml. should be windows and not windowss with two s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15b010a6-b39c-0423-ae57-c1977c8f4a0a
* Version Independent ID: 081ecd08-bece-aa57-229d-06c5d46a8fa5
* Content: [Adapt applications for use in mixed-OS Kubernetes clusters - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/aks-hci/adapt-apps-mixed-os-clusters)
* Content Source: [azure-stack/aks-hci/adapt-apps-mixed-os-clusters.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/adapt-apps-mixed-os-clusters.md)
* Service: **azure-stack**
* GitHub Login: @abha
* Microsoft Alias: **abha**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@MatthiasMerk Thank you for catching that error in the docs! I have submitted a PR to fix the issue, the change is merged internally and will go-live in the public docs shortly.
