### ISSUE TITLE
Screen shots have changed

### ISSUE THREAD

**Issue by kprpg** [MicrosoftDocs/azure-stack-docs#11]
When I went to install version 1902, the screen shots have changed. Please update them to reflect the new screens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e46293a4-00e4-46d5-d052-09f49c99d3c9
* Version Independent ID: 5df13a3e-3b6e-a90f-968e-72a5b5dc4447
* Content: [Install the Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure/azure-stack/asdk/asdk-install#feedback)
* Content Source: [articles/azure-stack/asdk/asdk-install.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-install.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by mattbriggs** [comment]
@kprpg Thanks again for your feedback. We have updated our screenshots. Thanks! #please-close

**Comment by mattbriggs** [comment]
#please-close
