### ISSUE TITLE
Pics are missing in the docs

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/azure-stack-docs#1101]
[Enter feedback here]
Please fix this issue, images are gone across the sections.
Thanks, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b4e8aa-3637-897c-3db5-1be1a435b606
* Version Independent ID: 8f83513a-b461-5c6d-bd8d-ce13486f4691
* Content: [Deploy the Azure Stack HCI operating system - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/operating-system)
* Content Source: [azure-stack/hci/deploy/operating-system.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/deploy/operating-system.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JohnCobb1
* Microsoft Alias: **v-johcob**

**Comment by TravisCragg-MSFT** [comment]
@carlosmayol Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by JohnCobb1** [comment]
Hi @carlosmayol Thanks for this feedback. I've checked the images in the topic in both Edge and Chrome. All images are displaying as expected from my PC.

**Comment by carlosmayol** [comment]
Hello @JohnCobb1 since yesterdays seems OK, I though it might be related to where the images are stored. thanks for checking.

**Comment by JohnCobb1** [comment]
@carlosmayol  I've checked the images again in this topic in both Edge and Chrome. All images are displaying as expected from my PC. Do you want me to sign off on this PR? Thanks

**Comment by carlosmayol** [comment]
@JohnCobb1 Sure sorry I forgot. thanks
