### ISSUE TITLE
Add a known issue to this page

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1103]
Title: "Resizing cluster VMs through the Compute service does not work with AKS engine"

The reason is that AKS engine maintains the state of the cluster in the API json file. To ensure that the desired VM size is reflected in any create, update, or scale operation done with AKS engine the API model must be updated before executing any of those operations. For example, on an already deployed cluster, if you change a VM size in the cluster to a different size using the Compute service, such state will be lost when "aks-engine update" is executed. To make this work you need to locate the API model for the cluster and change it there, and then run "aks-engine update"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bddc138b-1b2e-4be5-d38b-91818ccf1922
* Version Independent ID: fb4f2341-8ca1-f849-05f5-5b4ce22b9462
* Content: [Known issues with the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues?view=azs-2005)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov #in-progress

**Comment by mattbriggs** [comment]
@https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5523

**Comment by mattbriggs** [comment]
#sign-off
