### ISSUE TITLE
Unable to find nupkg as instructed

### ISSUE THREAD

**Issue by joberholzer** [MicrosoftDocs/azure-stack-docs#1119]
The document talks about saving a nuget package to a local file share or some other location so you can import it into Windows Admin Center and begin setting up Azure Kubernetes service. Yet I can't seem to find this nuget package anywhere. It's not available on the downloads page, on the ISO for AKS-HCI, not in the MSI for admin center... where is this file? How do we get it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 966bc617-756d-b69a-0d30-c8bc20d6e40b
* Version Independent ID: c2086376-2a7d-bacd-7057-e902f282a419
* Content: [Quickstart to set up Azure Kubernetes Service on Azure Stack HCI using Windows Admin Center - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/aks-hci/setup)
* Content Source: [azure-stack/aks-hci/setup.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/setup.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @davannaw-msft
* Microsoft Alias: **dawhite**

**Comment by joberholzer** [comment]
Also, Tried to switch over to the Powershell instructions but the zip file referenced for all the powershell modules is also missing from the download page. Unable to continue with any setup what-so-ever for Kubernetes on HCI.

**Comment by joberholzer** [comment]
User error. Disregard

**Comment by TravisCragg-MSFT** [comment]
@joberholzer Thanks for following up!
