### ISSUE TITLE
Replace PFXpassword with the actual password:

### ISSUE THREAD

**Issue by AquanPJCA** [MicrosoftDocs/azure-stack-docs#1125]
Replace PFXpassword with the actual password <--------------- this line is incorrect.
The line creates a prompt where the user inputs a password. PFXpassword is the prompt text itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82d4c695-8176-5c19-9814-6dd9b7506138
* Version Independent ID: fc6ceb0a-5167-1251-2e75-b258e4a93669
* Content: [Fix common issues with PKI certificates - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-remediate-certs?view=azs-2005)
* Content Source: [azure-stack/operator/azure-stack-remediate-certs.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-remediate-certs.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by HarithaMaddi-MSFT** [comment]
@AquanPJCA - Thanks for your valuable feedback. We are looking into it and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@AquanPJCA Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by IngridAtMicrosoft** [comment]
This is being investigated.

**Comment by BryanLa** [comment]
@AquanPJCA - thanks for finding this and contributing feedback. The article has been fixed and will be updated during the next publishing cycle, about 5 hours from now.

#please-close
