### ISSUE TITLE
Missing dependency for App Service Update 5 offline install

### ISSUE THREAD

**Issue by dfencegit** [MicrosoftDocs/azure-stack-docs#113]
The App Services update 5 offline install appears to have a missing depency for offline installs.  The install requires the newtonsoft.json powershell library in order to parse the initial ARM endpoints.  This package is not included in the offline install package and is not mentioned in the "before you get started" documentation.

Without the newtonsoft.json package installed you get the following errors in the app server install log:

System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json', Version=8.0.0.0.......

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 603ac047-9a9e-1841-c3a4-bc037edf7f64
* Version Independent ID: 19bbf07b-c7e4-263d-7678-eaf8ad9e3fe3
* Content: [Update Azure App Service Offline](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-update-offline)
* Content Source: [azure-stack/operator/azure-stack-app-service-update-offline.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-update-offline.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **anwestg**

**Comment by TravisCragg-MSFT** [comment]
@dfencegit are you referring to the [App Service 1.5 update doc](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-update-offline)?

**Comment by dfencegit** [comment]
The comment is aimed at the App Services 1.5 install package when used for update or install, as the issue occurs right at the beginning of the install where you point it to the ARM endpoint.

**Comment by apwestgarth** [comment]
@dfencegit we will investigate this as this sounds more like a bug with the installer or a corruption of the download package as you should not need to install that package to complete an offline installation, if you could share the full installer log with me that would be helpful also.

**Comment by apwestgarth** [comment]
Update 5 is no longer a supported version and similar issues have not been reported in the current supported versions #please-close
