### ISSUE TITLE
Update steps to deploy DeepStream Module to accommodate all customer environments

### ISSUE THREAD

**Issue by toolboc** [MicrosoftDocs/azure-stack-docs#1130]
It appears that not all customer environments have access to deploy IoT Edge Modules from the Azure Marketplace, it may be advised to update documentation to reflect manual steps to accommodate this situation.  This would impact steps 14 & 15 [here](https://docs.microsoft.com/en-us/azure-stack/hci/manage/attach-gpu-to-linux-vm#configure-azure-iot-edge). 
 I will update this issue shortly with a proposed workaround / PR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6ed06ba-9f13-a2e5-59b3-645cdd2e2821
* Version Independent ID: de5caca5-1d3e-aaf0-3aa5-aadd2abff270
* Content: [Attach a GPU to a Linux VM in Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/attach-gpu-to-linux-vm)
* Content Source: [azure-stack/hci/manage/attach-gpu-to-linux-vm.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/attach-gpu-to-linux-vm.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by BharathNimmala-MSFT** [comment]
@toolboc Thanks a lot for bringing this to attention and also helping fixing the document with a PR. Thank you

**Comment by TravisCragg-MSFT** [comment]
@toolboc Thanks for the feedback! It looks like your PR request was merged, so I am going to close this issue. 

@khdownie FYI
