### ISSUE TITLE
Update documentation - 

### ISSUE THREAD

**Issue by VJayMeyer** [MicrosoftDocs/azure-stack-docs#1133]
Hi There,

ASR states to use Server 2016. But in 2016 you first need to mandate the correct TLS level.
For the next person. Add this line to the PowerShell commands to be run:-

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c7ec8b-634f-6b95-7ce1-c38d55b12c23
* Version Independent ID: 8cc3a38e-0bbc-71b4-2c37-fc6231bb540d
* Content: [Install PowerShell Az module for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2005)
* Content Source: [azure-stack/operator/powershell-install-az-module.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/powershell-install-az-module.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by HarithaMaddi-MSFT** [comment]
@VJayMeyer - Thanks for your valuable feedback. Our team is looking into it and will get back to you soon.

**Comment by mattbriggs** [comment]
@VJayMeyer Tanks for your feedback. I'll update the content. #in-progress

**Comment by mattbriggs** [comment]
Updated the doc. Will be merged in the next doc build. Thanks! Matt

#please-close
