### ISSUE TITLE
Link needed for Download the Azure Stack Hub tools.

### ISSUE THREAD

**Issue by bganapa** [MicrosoftDocs/azure-stack-docs#1137]
Download the Azure Stack Hub tools.

this should be a link the Azurestack hub registration page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19119cef-de12-31e5-d0b6-b95f2985f57e
* Version Independent ID: 5a7921c1-ac2e-6de8-0e8d-de9f04e457a6
* Content: [Register Azure Stack Hub with Azure - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-registration?view=azs-2008)
* Content Source: [azure-stack/operator/azure-stack-registration.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-registration.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by TravisCragg-MSFT** [comment]
@bgianfo the link for how to get the tools is given in the [Download the Azure Stack Hub tools section](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-registration?view=azs-2008&pivots=state-disconnected#download-the-azure-stack-hub-tools). It takes you to another page where installation instructions are given, as it is best to use PowerShell to download the tools. The Exact URL for the zip file is given there. 

Please let me know if you need any additional information.

**Comment by bganapa** [comment]
I see that now :). There is no further action needed . Thank you!
