### ISSUE TITLE
No custom vm folder in downloaded file

### ISSUE THREAD

**Issue by francoislegrange** [MicrosoftDocs/azure-stack-docs#1141]
. This download includes custom VM templates. Extract the .zip file, and under the folder Custom VMs, < The is no such folder in downloaded zip file.>
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e401ae26-588f-124f-09a8-f1f6dc75da4e
* Version Independent ID: 6a9509a1-f16c-f527-5df1-9dae2d8eeaed
* Content: [Create and publish a Marketplace item in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-create-and-publish-marketplace-item?view=azs-2008)
* Content Source: [azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by HarithaMaddi-MSFT** [comment]
@francoislegrange - Thanks for your valuable feedback. We will review and get back to you with more details.

**Comment by TravisCragg-MSFT** [comment]
@francoislegrange Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@francoislegrange Thank you for the feedback and sorry for the delayed response. This article has been updated in several places and has addressed the issue you reported. Thanks again for reaching out! #please-close
