### ISSUE TITLE
PowerShell Command for Domain Join has typos

### ISSUE THREAD

**Issue by eszych** [MicrosoftDocs/azure-stack-docs#1145]
To connect to the Windows Worker VM using SSH you first need the SSH Key.
**Please add a description on how to optain the key.**
Also, the optained key is in the wrong format for putty for Windows and needs to be converted into a .ppk file.

After connecting to the Windows Worker VM using SSH the user will be at a command prompt - not a powershell prompt. Hence the listed PowerShell command (add-computer) will not work - PowerShell has to be started first.
Then, the listed command has errors - and a credential object is needed to do the domain join...
The complete PowerShell Command should read:

$password = ConvertTo-SecureString 'MySecretPassword' -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ('Domainname\Administrator', $password)
Add-Computer -DomainName "Domainname" -Restart -Credential $credential

Then the System will ask if it is o.k. that the NetBios Name will be shortened to 15 characters - that has to be acknowledged with "y" - otherwise the VM will not be joined to the domain...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2112f5e3-803b-c44d-3410-a14b1ba1bc30
* Version Independent ID: 4fa4c8b2-426f-a37b-160d-955fd98e7a82
* Content: [Use Use persistent storage in a Windows container - Azure Kubernetes Service on Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/persistent-storage-windows-nodes)
* Content Source: [azure-stack/aks-hci/persistent-storage-windows-nodes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/persistent-storage-windows-nodes.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @abha
* Microsoft Alias: **abha**

**Comment by TravisCragg-MSFT** [comment]
@eszych Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by msjingli** [comment]
This issue is already fixed. See [Prepare Windows nodes for group Managed Service Account support - Azure Stack Hub | Microsoft Docs](url) Thanks for the feedback.

**Comment by TravisCragg-MSFT** [comment]
closing as this no longer seems appropriate for the doc.
