### ISSUE TITLE
Update content - Tiering volumes is not accurate

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/azure-stack-docs#1166]
The section on tiering does not provide accurate informaiton about the current tiers created for AZSHCI and therefore some of the examples will fail. 

NestedMirrorOnHDD          Mirror                                     
MirrorOnHDD                Mirror                                     
Capacity                   Mirror                                     
NestedParityOnHDD          Parity                                     
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73197027-3340-4b3a-ea69-87737dd7152a
* Version Independent ID: c28e92b8-46d5-31b1-44ce-abec49cfcf3a
* Content: [Create volumes in Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/create-volumes)
* Content Source: [azure-stack/hci/manage/create-volumes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/create-volumes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by khdownie** [comment]
@carlosmayol thanks for the catch! Are you able to provide the correct info? Should we remove some of the examples? Please let me know who I should contact to get the correct information to update this page. Thank you!

**Comment by carlosmayol** [comment]
Hello Sir, I could, but probably Jaromir have it already @jaromirk is his Github user (jaromirk@microsoft.com) but for some reason its not picking-up.

**Comment by khdownie** [comment]
@jaromirk are you able to advise on this?

**Comment by jaromirk** [comment]
Hi folks, yeah, here you go https://github.com/Microsoft/WSLab/tree/master/Scenarios/S2D%20and%20Volumes%20deep%20dive

**Comment by jaromirk** [comment]
+ here is code to add "missing" tiers. In 2016 are not "MirrorOnHDD/SSD" and it makes more sense to use this naming. Also this codes adds nested resiliency volumes tiers for 2 node configurations https://github.com/microsoft/WSLab/blob/master/Scenarios/S2D%20Hyperconverged/Scenario.ps1#L731-L770

**Comment by carlosmayol** [comment]
Jaromir, can you update on the nestedTiers also? They are populated in 2node AZSHCI.

Thanks

________________________________

**Comment by khdownie** [comment]
Thanks @jaromirk - this page was very closely based on an S2D topic in the Windows Server repo. @carlosmayol - does that page need to be updated as well?

**Comment by carlosmayol** [comment]
@khdownie Yes, the S2D topic should be updated with jaromir's content (probably not all) but at least updates on the updates names for the tiers in 2019. the AZSHCI page should be updated with the new tiers NestedMirrorOnHDD Mirror & NestedParityOnHDD Parity on 2 nodes, but probably there are more in 4 nodes setup. @jaromirk  can you come up with an update for both pages?? something not as deep as your page but enough to match content with product release?

**Comment by khdownie** [comment]
@carlosmayol I stepped away from this to focus on GA, but now that's done. I can address these issues with the content. Do we have everything we need here in this thread, or are we still waiting on update on the nestedTiers from @jaromirk ?

**Comment by carlosmayol** [comment]
Hello @khdownie afaik the information is incomplete because few current tiers are not exposed on AZSHCI notes i added, I would like to double check the current tier naming in Stack HCI for 4+ nodes, those might not be the same @jaromirk  added on his page and therefore not accurate, if we are doing this to provide accuracy to both S2D and AZSHCI docs, then that info must be provided, but you can work in something that I can help validate, in the meantime I can ask someone else if they have a AZSHCI 4 nodes to provide accurate namings.

**Comment by jaromirk** [comment]
Nested tiers are exposed in 2node deployments by default - no need to manually create. All other tiers are exposed if mediatype is present (if HDD, then mirroronhdd and parityonhdd are exposed). It's easy to validate with WSLab - you can spin multiple node clusters as in this scenario: https://github.com/microsoft/WSLab/tree/master/Scenarios/S2D%20and%20Metadata%20deep%20dive

**Comment by carlosmayol** [comment]
Yes and those are the ones I put in the issue. Hello don’t have 4 node cluster and I thought you had it already and will be easy for you to run one command and expose any new name in azshci. But if you are too busy that’s fine. Thanks

________________________________

**Comment by khdownie** [comment]
@carlosmayol @jaromirk do the Performance and Capacity tier templates still exist? Can you confirm that all that needs to change in this page is the last section (Example: Using Storage Tiers)? Can I just replace what's there now with Jaromir's documentation on tiering?

**Comment by jaromirk** [comment]
Hi,
I just started a lab - the same as this, just with azshci OS and 1GB RAM https://github.com/microsoft/WSLab/tree/master/Scenarios/S2D%20and%20Tiers%20deep%20dive .... I'll share screenshots from there. I think perf and capacity still exists. But it should not be used as it's confusing (2node and 4 node systems have different purpose for performance and capacity)

**Comment by jaromirk** [comment]
![image](https://user-images.githubusercontent.com/9829838/103312414-3f36e000-4a1d-11eb-94de-08b1cfdf64e9.png)

**Comment by khdownie** [comment]
@jaromirk so can I just incorporate your Introduction to tiers, etc. WSLab documentation into the HCI docs, with some small changes? https://github.com/Microsoft/WSLab/tree/master/Scenarios/S2D%20and%20Volumes%20deep%20dive#introduction-to-tiers

**Comment by jaromirk** [comment]
Of course! Let me know if I should rewrite scenario to Azure Stack HCI, so you could reference lab if needed.

**Comment by khdownie** [comment]
If you have time, that would be great. If not, I can use what you've provided as the basis for a revised doc. Thank you!

**Comment by carlosmayol** [comment]
Hello @khdownie how is the new article doing? are we ready for review? Thanks

**Comment by khdownie** [comment]
@carlosmayol I am just getting back to this after some higher priority tasks, plus I wanted to give Jaromir a bit more time. But I think I can put something together based on what he has sent so far. I will have something for your review later this week or early next week.

**Comment by jaromirk** [comment]
Sorry, bit busy lately (and still on parental leave :)

**Comment by khdownie** [comment]
Is everything on this page correct except for the last section (Example: Using storage tiers)? https://docs.microsoft.com/en-us/azure-stack/hci/manage/create-volumes

**Comment by carlosmayol** [comment]
Hello again, correct this section is the wrong one:
https://docs.microsoft.com/en-us/azure-stack/hci/manage/create-volumes#example-using-storage-tiers 
Why? because we dont have those tiers in AZSHCI, as is a mimic of WS2019 approach, we shoule mention instead MirrorOnMediaType for performance or ParityOnMediaType for capacity.
We should mention, we can combine a volume that expands across those tiers and those types of disks are called MAP (Mirror-Accelerated Parity) they require ReFS file system. The picture belong to a WS 2016, which is terrible wrong on a new OS
additionally in the AZSHCI doc we are totally missing the nested resiliency, so I will add that for 2 nodes scenario
I should include the reference of the table that Jaromir created in here: 
https://github.com/microsoft/WSLab/tree/master/Scenarios/S2D%20and%20Tiers%20deep%20dive#summary-table
careful the notes on the side that mentions 2019 and should be AZSHCI wording.

**Comment by khdownie** [comment]
Thanks @carlosmayol - I am starting to put the pieces together and work on this. Question: Does creating a mirror-accelerated parity volume always require ReFS? Or only in tiering situations?

**Comment by jaromirk** [comment]
yes, MAP is ReFS feature.

**Comment by khdownie** [comment]
There is already a MAP section in the doc so I will put this note there. Is there anything else that needs to change for the MAP section?
https://docs.microsoft.com/en-us/azure-stack/hci/manage/create-volumes#create-a-mirror-accelerated-parity-volume

**Comment by carlosmayol** [comment]
> When I run Get-StorageTier on an Azure Stack HCI cluster I get the following. Is it OK to replace the old 2016 screen shot with this?
> 
> FriendlyName ResiliencySettingName PhysicalDiskRedundancy
> 
> NestedParityOnHDD Parity 1
> Capacity Mirror 1
> NestedMirrorOnHDD Mirror 3
> MirrorOnHDD Mirror 1

Yes, that's how it look in a 2 node Cluster with no SSD drives. Is a better capture that the one we have today. Please remember to include a Nested example in the HCI docs there is none I could have seen.

**Comment by jaromirk** [comment]
BTW. You don't have Performance tier because you have 2 node system. Since you have 2 node, Capacity tier is Mirror. In 4+ node cluster is Performance Mirror and capacity is Parity... Well, This is some skeleton Claus Joergensen made :), That's why I would skip Capacity/Performance naming completely as it's confusing!

**Comment by khdownie** [comment]
@jaromirk and @carlosmayol here is a PR for your review. I put a couple questions in bold: https://review.docs.microsoft.com/en-us/azure-stack/hci/manage/create-volumes?branch=pr-en-us-6459

**Comment by carlosmayol** [comment]
@khdownie looks pretty good to me, I will personally add some more info about the nested tiers from here: https://docs.microsoft.com/en-us/windows-server/storage/storage-spaces/nested-resiliency or mentioned in this volumes section but add an additional section for nested resiliency knowledge...
About the bold sections, I dont see any...

**Comment by khdownie** [comment]
@carlosmayol so nested resiliency only applies to 2-node clusters? I'm having trouble figuring out how much of that page to port over, since WS2019 is a little different than Azure Stack HCI. Is there anything that doesn't apply?

**Comment by carlosmayol** [comment]
> @carlosmayol so nested resiliency only applies to 2-node clusters? I'm having trouble figuring out how much of that page to port over, since WS2019 is a little different than Azure Stack HCI. Is there anything that doesn't apply?

Correct, only 2 nodes, from the link above:

Prerequisites
Consider nested resiliency if:
**Your cluster runs Windows Server 2019; and
Your cluster has exactly 2 server nodes**
Red X icon. You can't use nested resiliency if:
**Your cluster runs Windows Server 2016; or
Your cluster has 3 or more server nodes**

**Comment by khdownie** [comment]
Right, I saw that, thanks -- wasn't sure if it applied to Az HCI. So should I port that whole page over, or just parts of it? It's a pretty long page.
