### ISSUE TITLE
Parameter "-intent" no longer available - Concerned part: Identify the best destination shares to hold the container you migrate

### ISSUE THREAD

**Issue by Lihailian** [MicrosoftDocs/azure-stack-docs#118]
Hi Team,

Parameter "-intent" no longer available - Concerned part: "Identify the best destination shares to hold the container you migrate" in https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-manage-storage-shares

Thank you!

Regards,

Hailian Li

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03c63388-ff19-a72e-959b-883a01b400e8
* Version Independent ID: bba686d4-1463-c9a1-bdb4-7d3edf095fee
* Content: [Manage storage capacity in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-manage-storage-shares#feedback)
* Content Source: [azure-stack/operator/azure-stack-manage-storage-shares.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-manage-storage-shares.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@Lihailian Thanks for the note. I'll update shortly. #in-progress

**Comment by mattbriggs** [comment]
@Lihailian Update in progress. Should appear in our next build. #please-close

**Comment by TravisCragg-MSFT** [comment]
@Lihailian We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
