### ISSUE TITLE
Should add Azure Stream Analytics Preview in the list

### ISSUE THREAD

**Issue by dacoppet** [MicrosoftDocs/azure-stack-docs#1182]
[Enter feedback here]
The list of services should be updated with preview services : Azure Stream Analytics is missing.
https://azure.microsoft.com/en-us/updates/asaonstack/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34b4d158-a0bd-47ce-4a29-60111ef9f515
* Version Independent ID: 4a8f336e-cbb4-f35a-429c-048ada1c6df6
* Content: [Azure Stack Hub services, plans, offers, subscriptions overview - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/service-plan-offer-subscription-overview?view=azs-2008)
* Content Source: [azure-stack/operator/service-plan-offer-subscription-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/service-plan-offer-subscription-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
Contacted contributor internally to suggest an alternate path.
#please-close
