### ISSUE TITLE
Docker in windows request hyper-V enabled but VM in AzureStack Hub do not support nested virtualization

### ISSUE THREAD

**Issue by jianfeng-jia** [MicrosoftDocs/azure-stack-docs#1187]
[Enter feedback here]
It seems we need give notes that this document is not applied to windows VM running in Azure Stack hub as it does not support nested virtualization, which hyper-v can not be enabled. Readers can be mislead as this document mentioned for azure stack hub so some readers try the steps in windows VMs running in Azure Stack Hub but get blocked.  Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55e2558f-e434-e5cc-acd4-0d3bd2dd979f
* Version Independent ID: be6bfe5f-bfdd-6550-588d-6d627c16c3f8
* Content: [Use Docker to run PowerShell in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-powershell-user-docker?view=azs-2008&tabs=az)
* Content Source: [azure-stack/user/azure-stack-powershell-user-docker.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-powershell-user-docker.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @jianfeng-jia , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by mattbriggs** [comment]
@jianfeng-jia This a good call out. I'll add to the docs. #In-progress

**Comment by mattbriggs** [comment]
https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/6111

**Comment by mattbriggs** [comment]
Thanks again! #please-close
