### ISSUE TITLE
Windows Server can run on-premises or in the cloud, but isn't itself a complete hyperconverged offering.

### ISSUE THREAD

**Issue by DarrylvanderPeijl** [MicrosoftDocs/azure-stack-docs#1196]
"Windows Server can run on-premises or in the cloud, but isn't itself a complete hyperconverged offering."

Windows Server (vNext) has Hyper-V, Storage Spaces Direct and SDN. How it this not a complete hyperconverged offering?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1b5681-bec1-c4d2-bb1a-9c1e2533d710
* Version Independent ID: 818c8ae2-b58a-ed92-799d-1bec94407187
* Content: [Compare Azure Stack HCI to Azure Stack Hub and Windows Server - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/compare-windows-server)
* Content Source: [azure-stack/hci/concepts/compare-windows-server.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/concepts/compare-windows-server.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by himanshusinha-msft** [comment]
@DarrylvanderPeijl   Thanks for the ask  . At this time we are reviewing the ask and we will reply back as soon as we can .

**Comment by khdownie** [comment]
@DarrylvanderPeijl makes a good point. I will open a separate PR to revise the language. Keep in mind that Microsoft no longer wants to position Windows Server as a future-ready HCI offering. But we should obviously still be factual.

**Comment by khdownie** [comment]
I revised the language to: "Windows Server can run on-premises or in the cloud, but will not offer the latest hyperconverged features moving forward." Which is true; the Windows Admin Center cluster creation wizard includes SDN and RDMA only for Azure Stack HCI.  Good to close this issue?

**Comment by khdownie** [comment]
Update: We are redoing this page and will be ready to publish soon, probably next week. I believe the new approach will alleviate the concerns that @DarrylvanderPeijl brings up here (which are totally valid).

**Comment by khdownie** [comment]
We published the new page: https://docs.microsoft.com/en-us/azure-stack/hci/concepts/compare-windows-server

@DarrylvanderPeijl has further suggestions which I will discuss with Cosmos, but I think the above is sufficient to close this issue now.
