### ISSUE TITLE
Image under add a node is a bit confusing

### ISSUE THREAD

**Issue by BasWassenaar** [MicrosoftDocs/azure-stack-docs#1210]
Hi!
I was reading to this page and the image under "add a node" is a bit confusing. To me it looks like it adds another scale unit instead of a node. I think it's because of the naming used: Azure Stack Hub Stack 1 and Azure Stack Hub Stack 2.

So maybe change the naming to Azure Hub Node 1 and Azure Stack Hub Node 2?

https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-capacity-planning-compute?view=azs-2008#azure-stack-hub-memory

Regards,
Bastiaan Wassenaar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b6179e-9c7b-4c9e-6c26-c5edfc4bedae
* Version Independent ID: ada578d3-3b7f-dffc-a0f3-3e6938a8f75f
* Content: [Azure Stack Hub compute capacity - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-capacity-planning-compute?view=azs-2008)
* Content Source: [azure-stack/operator/azure-stack-capacity-planning-compute.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-capacity-planning-compute.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **justinha**

**Comment by KranthiPakala-MSFT** [comment]
@BasWassenaar 
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will provide an update as appropriate.

**Comment by TravisCragg-MSFT** [comment]
@BasWassenaar Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by IngridAtMicrosoft** [comment]
Please reassign to one of the other authors on Azure Stack. I no longer maintain this content.

**Comment by PatAltimore** [comment]
@TravisCragg-MSFT Please assign to me @PatAltimore

**Comment by PatAltimore** [comment]
Hi @BasWassenaar,

Thanks for the feedback.  I updated the image to node 1 & node 2. 

Pat
#please-close
