### ISSUE TITLE
Add link to Microsoft Q&A, Questions in tag: azure-stack

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1219]
The second paragraph has a link to the MSDN forum, but that is deprecated and moved to the Azure Q&A site, per this post-
https://social.msdn.microsoft.com/Forums/en-US/17450e71-6eb4-43b7-be12-107a82631ae8/announcement-azure-stack-forum-migrated-to-microsoft-qa?forum=AzureStack 

Please update and add a link to new Q&A site- 
Microsoft Q&A, Questions in tag: azure-stack
https://docs.microsoft.com/en-us/answers/questions/topics/single/25482.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1af91df-2eff-9379-b3b1-e1ad2ab70c9e
* Version Independent ID: fb6f5447-ebde-8883-9f6f-5d36d4ed0cad
* Content: [Troubleshoot the ASDK - Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-troubleshooting?view=azs-2008)
* Content Source: [azure-stack/asdk/asdk-troubleshooting.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-troubleshooting.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub-asdk**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by KranthiPakala-MSFT** [comment]
@alexsmithMSFT  
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by GitaraniSharma-MSFT** [comment]
@alexsmithMSFT , thank you for your feedback. I see that the backend repo is already updated with the Q&A URL but for some reason, it is not being reflected in the actual doc. I am checking with the relevant team regarding same. I'll get back to you with an update soon.
![image](https://user-images.githubusercontent.com/67630903/103877411-0e306c80-50fb-11eb-8399-46c84631db73.png)

**Comment by PatAltimore** [comment]
Hi @alexsmithMSFT and @SumanthMarigowda-MSFT, 

I fixed this yesterday. I thought I had responded to this issue and closed it. Sorry for the confusion.

Pat
#please-close
