### ISSUE TITLE
Search and replace gone wrong

### ISSUE THREAD

**Issue by Hyldsgaard** [MicrosoftDocs/azure-stack-docs#1224]
In the second code block under "Register the ASDK" I think a search and replace might have gone wrong.

It seems that the word "Azure" has been replaced with the word "AzureRMure" multiple times which makes this code fail.

Best regards,
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ccb9b30-d08b-f263-c23e-abe9e399626a
* Version Independent ID: b25ce77b-1249-14d7-2634-e96f1c9fa0c4
* Content: [Register the ASDK with Azure - Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-register?view=azs-2008&tabs=az1%2Caz2%2Caz3%2Caz4%2Caz5%2Caz6%2Caz7)
* Content Source: [azure-stack/asdk/asdk-register.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-register.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub-asdk**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by KranthiPakala-MSFT** [comment]
@Hyldsgaard  
Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will update the document as appropriate.

**Comment by TravisCragg-MSFT** [comment]
@Hyldsgaard Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by PatAltimore** [comment]
Hi @Hyldsgaard,

Thanks for catching the issue. I've fixed the article and it should publish today. 

Thanks!
Pat
#please-close
