### ISSUE TITLE
review doc!

### ISSUE THREAD

**Issue by RZomermanMS** [MicrosoftDocs/azure-stack-docs#1230]
This document makes no sense at all - it's a mixture of Hyper_V commands (if HCI nodes are running on another Hyper-V hosts, mismatching commands, wrong values etc).. this needs a proper cleanup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df3012c4-22e5-004d-da6f-60744f2cfb4f
* Version Independent ID: 57e21edd-9a2b-f1ca-2ff7-48e3da5dc260
* Content: [Create an Azure Stack HCI cluster using Windows PowerShell - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell)
* Content Source: [azure-stack/hci/deploy/create-cluster-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/deploy/create-cluster-powershell.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @v-dasis
* Microsoft Alias: **v-dasis**

**Comment by Grace-MacJones-MSFT** [comment]
thanks for bringing this to our attention. Your feedback has been shared with the content owner for further review.

**Comment by v-dasis** [comment]
updating article with feedback - this is a work in progress . Thanks for your patience.
