### ISSUE TITLE
Install-Module PowerShellGet -MinimumVersion 2.2.3 -Force

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#1240]
On a newly installed host (Windows 10 or Windows Server 2019) when executing this command the following warning will be received:

WARNING: The version '1.4.7' of module 'PackageManagement' is currently in use. Retry the operation after closing the applications.

There are no known applications, PowerShell sessions, scripts, etc. running or known to be using this module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c7ec8b-634f-6b95-7ce1-c38d55b12c23
* Version Independent ID: 8cc3a38e-0bbc-71b4-2c37-fc6231bb540d
* Content: [Install PowerShell Az module for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2008)
* Content Source: [azure-stack/operator/powershell-install-az-module.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/powershell-install-az-module.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@aricbernard I suspect this is related to a known issue with the Az modules on Azure Stack Hub. 

1. Have you restarted your session? This sometimes works.
2. This is the mitigation to a similar known issue: 
3. 
Run the following cmdlet in the same session:
Install-Module PowershellGet -MinimumumVersion 2.3.0 -Force
Close your session and start a new elevated PowerShell session.

I'll send your feedback to the technical contact for the contact and follow up with their response.

#in-progress

**Comment by mattbriggs** [comment]
Az topic has been updated.

#please-close
