### ISSUE TITLE
Install-Module -Name Az.BootStrapper -Force

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#1241]
When executing this command, the following error message is received:

PackageManagement\Install-Package : No match was found for the specified search criteria and module name 
'Az.BootStrapper'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Pa 
   ckage], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.Install 
   Package

This is possible due to another issue that I filed:
https://github.com/MicrosoftDocs/azure-stack-docs/issues/1240

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c7ec8b-634f-6b95-7ce1-c38d55b12c23
* Version Independent ID: 8cc3a38e-0bbc-71b4-2c37-fc6231bb540d
* Content: [Install PowerShell Az module for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2008)
* Content Source: [azure-stack/operator/powershell-install-az-module.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/powershell-install-az-module.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@aricbernard: I think this may be related. If the mitigation doesn't work, can you let me know here? I am following up with the technical contact for Azure Stack Hub PowerShell, and will have an answer in a bit. Thanks for your comments. #in-progress

**Comment by mattbriggs** [comment]
Az topic has been updated.

#please-close
