### ISSUE TITLE
1910 Release Notes Missing

### ISSUE THREAD

**Issue by jamesorlando** [MicrosoftDocs/azure-stack-docs#1244]
1910 Release Notes do not appear in the Technet Gallery Archive or the Archive as this page mentioned. Latest Archive notes are from 1908.0

**Comment by sethmanheim** [comment]
@jamesorlando I will add these back tomorrow (PST). Please keep in mind that the 1910 Azure Stack build is no longer under support.

**Comment by sethmanheim** [comment]
Hi again @jamesorlando. Unfortunately TechNet has been made read-only, and will be retired soon. So we will need to find another place to host archived release notes. Thanks for bringing this to our attention! #please-close

**Comment by sethmanheim** [comment]
All archived release notes are now at https://docs.microsoft.com/en-us/azure-stack/operator/relnotearchive/release-notes

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim Thanks for sharing the details.
