### ISSUE TITLE
The link to the .NET Core Hosting package is obsolute

### ISSUE THREAD

**Issue by DRAirey1** [MicrosoftDocs/azure-stack-docs#1247]
Great page of documentation.  I use it often, but the link for the .NET Core hosting package points to the 2.1 version which is being end-of-lifed.  You want:

https://dotnet.microsoft.com/download/dotnet-core/current/runtime

As the link on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86a4e4e-a87b-376f-c2c8-dc208f65af24
* Version Independent ID: 3af8893e-2822-1859-de57-6c129ddfeebe
* Content: [Deploy C# ASP.NET web app to a VM in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-dev-start-howto-vm-dotnet?view=azs-2008)
* Content Source: [azure-stack/user/azure-stack-dev-start-howto-vm-dotnet.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-dev-start-howto-vm-dotnet.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SnehaAgrawal-MSFT** [comment]
@DRAirey1 Thanks for the feedback! We are taking a look into this and will get back to you soon.

**Comment by mattbriggs** [comment]
@DRAirey1 Thanks for the comment and update!

#in-progress

**Comment by DRAirey1** [comment]
Actually, you probably want to point to the .NET 5.0 Download site now.  FWIW.

**Comment by mattbriggs** [comment]
@DRAirey1 Thanks again.

Updated and will appear in the next build.

#please-close
