### ISSUE TITLE
Conflicting information

### ISSUE THREAD

**Issue by noellis-ms** [MicrosoftDocs/azure-stack-docs#1254]
Although the release notes states "Starting with the 2005 release, when you update to a new major version (for example, 1.2005.x to 1.2008.x), the latest hotfixes (if any) in the new major version are installed automatically. From that point forward, if a hotfix is released for your build, you should install it."   In this paragraph the word "**_should_**" is used.

Next, the release note states that hotfixes are cumulative and that " you only need to install the latest hotfix to get all fixes included in any previous hotfix releases for that version."   In this paragraph the phrase "**_only need to_**" is used.

Lastly, the release note states as a "Hotfix prerequisites" - "The 2008 release of Azure Stack Hub must be applied on the 2005 release with the following hotfixes:" then goes on to list the latest hotfix for the previous ASH release.   In this paragraph the work "**_must_**" is used.

There is an ocean of difference between the words "should" and "must" and the phrase "only need to". I have emphasized with my customer that the best practice and best experience is to always install the latest hotfix prior to installing the next major release. With that said, my customer has pointed out that the words used and how they instruct to perform maintenance are confusing, unclear, contradictory. They have requested that the release notes be updated as to provide the best practice only and not state something "must" be done when clearly it does not; even if it would produce a more positive experience.

For clarity, the request is to update the release notes to state the following:

"Starting with the 2005 release, when you update to a new major version (for example, 1.2005.x to 1.2008.x), the latest hotfixes (if any) in the new major version are installed automatically. _Further, Azure Stack Hub hotfixes are cumulative. As a best practice, all hotfix's released for your build should be installed to ensure the best update experience between major releases_."

"_Note*
If you operate a disconnected Azure Stack Hub, it is best practice that you monitor the RSS feed "Microsoft Support - Azure Stack Hub" (provide link) to ensure you have downloaded the most recent release of a major version. This will ensure you have the current inline hotfix for the new major version._"

I was also requested that since hotfixes are cumulative - the section "Hotfix prerequisites: before applying the 2008 update" should be removed because this is a best practice - not a requirement due to the cumulative nature of the hotfixes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e05517-6ffa-ad32-ec69-d3299492d880
* Version Independent ID: 2d6ffb4c-9134-a390-3f90-2322c9182e76
* Content: [Azure Stack Hub release notes - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/release-notes?view=azs-2008)
* Content Source: [azure-stack/operator/release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/release-notes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@noellis-ms Thank you for the feedback. We have a couple of issues here.

First, I agree the wording of this is confusing. The idea is that you don't need to install the latest hotfix before updating to a major release (which was previously a requirement); the major releases contain all the cumulative hotfixes up to that point. I like your suggestions for rewording, and will make that change you suggest.

For the RSS feed, I do not have a link or any access to that feed, so I won't include that change. We will continue to rely on the other channels customers have used to keep informed about new major releases. Thank you for the suggestion, however!

**Comment by noellis-ms** [comment]
Hi Seth,

Much appreciate the quick response.

The URL to the RSS feed for Azure Stack Hub hotfixes is listed below.

https://support.microsoft.com/app/content/api/content/feeds/sap/en-us/32d322a8-acae-202d-e9a9-7371dccf381b/rss

Additionally, a customer reading the release note could go to this URL and select Azure Stack Hub from the dropdown menu.
Feed Picker (microsoft.com)<https://support.microsoft.com/en-us/rss-feed-picker>

Kind Regards,

[Microsoft]
[cid:image007.jpg@01D6EFF8.08837890]
Norman Ellis
Customer Engineer
Microsoft Federal
U.S. Regulated Industries
Office: Reston, VA | +1 (202) 8316461 X6461
Mobile: +1 (703) 909-6103
Norman.Ellis@Microsoft.com<mailto:Norman.Ellis@Microsoft.com>
﻿
If you have any feedback about my work, please let either me or my manager Becky Wynne know at Becky.Wynne@microsoft.com
[cid:image005.gif@01D6EFF8.070C41E0]

**Comment by sethmanheim** [comment]
Thanks again for your feedback. I have changed this section in the 2008 release notes as follows. It should be live today after 10 AM PST:

**After successfully applying the 2008 update**
Because Azure Stack Hub hotfixes are cumulative, as a best practice you should install all hotfixes released for your build, to ensure the best update experience between major releases. When you update to a new major version (for example, 1.2005.x to 1.2008.x), the latest hotfixes (if any) in the new major version are installed automatically.

After the installation of 2008, if any 2008 hotfixes are subsequently released, you should install them:

Azure Stack Hub hotfix 1.2008.20.102

**Comment by sethmanheim** [comment]
#please-close
