### ISSUE TITLE
Disable multi-tenancy section title is misleading

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1262]
The section title "Disable multi-tenancy" is misleading. There is no setting to enable/disable multi-tenancy, just whether there is a single directory, or multiple directories (multi-tenancy). Removing a tenant directory does not disable multi-tenancy, if there are still 2 or more directories configured.

This leads to customer confusion, when they want steps to remove one or more guest directories, but leave other multi-tenant directories in place. 

Customer verbatim from SR 120031624002614 - "...he said I could remove both of those unhealthy tenants.  However, your link you supplied says disable multi-tenancy which is not want I want to do. I just want to remove those 2 that are unhealthy."

**Suggestion:** Rename the "Disable multi-tenancy" section title to something like "Remove a guest directory tenant"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea6b2d3-c2a7-a7f1-2473-34c76e32c835
* Version Independent ID: b3cd3369-fdab-225e-2cc9-d90f9b5bffff
* Content: [Configure multi-tenancy in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-enable-multitenancy?view=azs-2008#disable-multi-tenancy)
* Content Source: [azure-stack/operator/azure-stack-enable-multitenancy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-enable-multitenancy.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by BryanLa** [comment]
@SaiKishor-MSFT - please assign this one to me. This article needs multiple revisions, including the ones called out by @alexsmithMSFT.

**Comment by SaiKishor-MSFT** [comment]
> @SaiKishor-MSFT - please assign this one to me. This article needs multiple revisions, including the ones called out by @alexsmithMSFT.

Assigned. Thanks!

**Comment by alexsmithMSFT** [comment]
@SaiKishor-MSFT thanks for taking this one. One other issue I noticed, is with the comment in the second script under "Disable multi-tenancy", which mentions creation of a registration resource. I think it was copied verbatim from earlier sample to "Configure Azure Stack Hub directory". 

`## Replace the value below with the name of the resource group in which the directory tenant registration resource should be created (resource group must already exist).`

**Comment by BryanLa** [comment]
@alexsmithMSFT - done. I'm making several other revisions to make this more intuitive as well. I'll send you a link to the preview when it's ready..

**Comment by BryanLa** [comment]
Substantive changes made to Configure multi-tenancy in Azure Stack Hub to address this issue.
#please-close
