### ISSUE TITLE
Supported CentOS appear to be out of date for versions 7.6 - 8.0

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1264]
The list of supported Linux distros only includes CentOS up to version 7.5-
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-supported-os?view=azs-2008#linux

But the "Add from Azure" in Azure Stack Hub Marketplace Management also has CentOS images for versions 7.6, 7.7, 7.8 and 8.0-
![image](https://user-images.githubusercontent.com/26260056/105907540-10e3fa80-5ff3-11eb-8156-b76549ea9c87.png)

These are probably supported, and not listed in the doc (or if they are not supported, we should call that out too).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf72767c-5772-1398-dfbc-2f736aeb3e2a
* Version Independent ID: c8f3ce87-baa9-5a4f-6b2e-f0dd6614c6a3
* Content: [Guest operating systems supported on Azure Stack Hub - Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-supported-os?view=azs-2008#linux)
* Content Source: [azure-stack/operator/azure-stack-supported-os.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-supported-os.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by alexsmithMSFT** [comment]
See- https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-marketplace-changes?view=azs-2008#updated-marketplace-items

> 09/04/2020: CentOS-based 7.5 - version 7.5.201808150
09/04/2020: CentOS-based 7.6 - version 7.6.201909120
09/04/2020: CentOS-based 7.7 - version 7.7.2020062400
09/04/2020: CentOS-based 8.0 - version 8.0.201912060

> 12/22/2020: Rogue Wave Software Centos 7.8 – version 7.8.2020062400

**Comment by shashishailaj** [comment]
@alexsmithMSFT Thank you for your feedback . We will investigate and update the thread with our findings .

**Comment by alexsmithMSFT** [comment]
@sethmanheim we have at least one customer who upgraded an existing VM to CentOS 7.9, so it would be good to have clarification on that version, even if we don't have a marketplace image for it.

**Comment by sethmanheim** [comment]
@alexsmithMSFT I have no clue and I'll need to ask a PM somewhere anyway, so... if you have any helpful information, that'd be great.

**Comment by sethmanheim** [comment]
Updates to the article will be live after 3 PM PST today. Thank you for the feedback! #please-close
