### ISSUE TITLE
We need to update the api model json file references in this article

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1266]
please change all references to this url: 

https://github.com/Azure/aks-engine/blob/master/examples/azure-stack/kubernetes-azurestack.json

use this one instead 

https://aka.ms/aksengine-json-example

Thanks,
Walter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9652b7b-09b9-ace9-4ef7-abc413b9d52c
* Version Independent ID: 53c19bb0-3f77-d15c-87e2-33e1d442d73b
* Content: [Deploy Kubernetes cluster with AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster?view=azs-2005#define-a-cluster-specification)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
#in-progess

https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/6387

**Comment by mattbriggs** [comment]
Updated and merged

#please-close
