### ISSUE TITLE
Publishing a Windows Image using this guide does not work

### ISSUE THREAD

**Issue by jimchurches** [MicrosoftDocs/azure-stack-docs#1267]
Following these instructions does not work.  It seems to me that these instructions are out of date or are not tested (or I can't read).

This guide provides more information but there is inconsistencies between the two:

https://azurestack.blog/2016/10/adding-and-using-os-gallery-items-to-azure-stack-tp2/

Combining the information in the two articles I can get a custom Windows image published, but when attempting to use if via the Marketplace I get an error _'The selected image is not valid for the specified location. Select a different location.'_

The location drop down defaults to the region name for our AzSH and this is the only option.  This seems to be correct, but we get the error.

We can use the vmImage from an ARM template and PowerShell to create VMs, so we don't think we have an issue with the image, we think the issue is with one of the files in the _.azpkg_ file but we can't figure out the issue.  The examples provided my Microsoft in the article do not work and need to be updated, but we are obviously missing something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e401ae26-588f-124f-09a8-f1f6dc75da4e
* Version Independent ID: 6a9509a1-f16c-f527-5df1-9dae2d8eeaed
* Content: [Create and publish a Marketplace item in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-create-and-publish-marketplace-item?view=azs-2008&tabs=az)
* Content Source: [azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @jimchurches , thanks for the question! We are taking a look into this and will get back to you soon.

**Comment by sethmanheim** [comment]
@jimchurches Hello and thanks for the feedback. We have seen that error before when there’s insufficient quota. Can you please verify that you have enough compute quota?

**Comment by jimchurches** [comment]
Hi - that was one of the things I checked and it looks fine to me, but I will get with my colleague who set up quotas to make sure I'm reading things correctly.  Wouldn't quotas also stop ARM templates and PowerShell from provisioning a machine from the image?

**Comment by sethmanheim** [comment]
Hi again @jimchurches -- I asked the product team about this and they replied that "They would, but that’s the message that shows up before resource creation in the portal."

Hope that's helpful.

**Comment by jimchurches** [comment]
Hi Folks - we have checked quotas and offers and we are sure they are okay.  I can sanitise our .azpkg configuration files and share them if that helps at all.

**Comment by sethmanheim** [comment]
@jimchurches Thanks for the response -- at this point it's probably best to file a support ticket with CSS. Thank you for the feedback! #please-close
