### ISSUE TITLE
Missing Event Hub Quotas

### ISSUE THREAD

**Issue by kikofarad** [MicrosoftDocs/azure-stack-docs#1268]
please check this part missing event hub quotas : 

https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-quota-types?WT.mc_id=modinfra-12256-thmaure&view=azs-2008#event-hubs-quota-types

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41a2a997-ac32-8e7a-1085-12645f2b1d4d
* Version Independent ID: 5dd94010-147c-f5cd-3f22-27ff24184ff4
* Content: [Quotas and quota types in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-quota-types?WT.mc_id=modinfra-12256-thmaure&view=azs-2008#event-hubs-quota-types)
* Content Source: [azure-stack/operator/azure-stack-quota-types.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-quota-types.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SatishBoddu-MSFT** [comment]
Hello @kikofarad Thanks for your feedback.
I have assigned the issue to the content author @sethmanheim  for further review.

**Comment by sethmanheim** [comment]
@SatishBoddu-MSFT Please assign to @spelluru. Thank you!

**Comment by spelluru** [comment]
@kikofarad - do you mean this article is missing Event Hubs quotas mentioned in the following article?
https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quotas

@kasun04 for awareness
