### ISSUE TITLE
Code title. Az module is duplicated

### ISSUE THREAD

**Issue by kikofarad** [MicrosoftDocs/azure-stack-docs#1270]
The code snippet title tab are duplicated , should be Az module and AzRM module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a227a2f7-001d-edb2-31d2-6dc020fa666d
* Version Independent ID: cae8db95-8311-3ff3-8c63-30d9c751d8e6
* Content: [Change the billing owner for an Azure Stack Hub user subscription - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-change-subscription-owner?WT.mc_id=modinfra-12256-thmaure&view=azs-2008&tabs=az)
* Content Source: [azure-stack/operator/azure-stack-change-subscription-owner.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-change-subscription-owner.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by SaiKishor-MSFT** [comment]
@kikofarad Thanks for pointing this. I have made the changes and it should update soon. If you have any further concerns, please do let us know. Thank you!
