### ISSUE TITLE
add- vs. login-azaccount

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#1274]
In the Connect with Azure AD section, the command Add-AzAccount is used.
In the Connect with AD FS section, the command Login-AzAccount is used.

These cmdlets are **the same** and both are aliases for **Connect-AzAccount**.  The best practice for PowerShell coding, especially when publishing scripts and snippets, is to use proper cmdlet names instead of aliases.  As this is official documentation, shouldn't we adhere to those best practices instead of potentially confusing administrators?

`Get-Alias -Name "*-azaccount" | Select-Object DisplayName,Definition`

DisplayName         Definition
-----------               ----------
Add-AzAccount     **Connect-AzAccount**
Login-AzAccount   **Connect-AzAccount**
Logout-AzAccount Disconnect-AzAccount
Remove-AzAccount Disconnect-AzAccount

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12c58c5-d502-b45e-9cb8-699be1856deb
* Version Independent ID: aae468e2-40d7-007a-e47f-cf30a1238bae
* Content: [Connect to Azure Stack Hub with PowerShell - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-configure-admin?view=azs-2008&tabs=az1%2Caz2%2Caz3)
* Content Source: [azure-stack/operator/azure-stack-powershell-configure-admin.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-powershell-configure-admin.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SatishBoddu-MSFT** [comment]
@aricbernard 
Thanks for the feedback! 
I have assigned the issue to the content author for further review.

**Comment by mattbriggs** [comment]
@aricbernard in-progress

**Comment by mattbriggs** [comment]
Updated. #please-close
