### ISSUE TITLE
Missing '/'

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#1275]
There appears to be missing '/' characters in the example calls in the REST API section.  All references to "/providersMicrosoft.Commerce.Admin/" should be changed to "/providers/Microsoft.Commerce.Admin/"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35cd7f7c-54fa-f242-bee3-860e5378b135
* Version Independent ID: 1f878748-b633-f194-e27b-43c9f7f43924
* Content: [Azure Stack Hub provider resource usage API - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-provider-resource-api?view=azs-2008)
* Content Source: [azure-stack/operator/azure-stack-provider-resource-api.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-provider-resource-api.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SatishBoddu-MSFT** [comment]
@aricbernard Thanks for bringing this to our notice!
I have assigned the issue to the content author for further review.

**Comment by sethmanheim** [comment]
@SatishBoddu-MSFT Thank you for catching that -- I just submitted a PR to fix it. Appreciate the feedback! #please-close
