### ISSUE TITLE
Azure Stack Hub GPU support is currently in public preview. 

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#1278]
Isn't AZsH GPU support now GA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 682649a8-9b9c-1376-9e06-3ec3bbdaad8f
* Version Independent ID: 3f14a385-148c-8ad2-5526-9c5ef5f9ac07
* Content: [Graphics processing unit (GPU) VM on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/gpu-vms-about?WT.mc_id=modinfra-12256-thmaure&view=azs-2008)
* Content Source: [azure-stack/user/gpu-vms-about.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/gpu-vms-about.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@aricbernard following up. Thanks for the note.

#in-progress

**Comment by mattbriggs** [comment]
@aricbernard @shashishailaj  Thanks for your question. GPU is not yet GA yet for Azure Stack Hub. We will update the page as soon as it does. Thanks! Matt

#please-close
