### ISSUE TITLE
When Trying to Register ASDk Deployment I get a failure message

### ISSUE THREAD

**Issue by joseq-terawe** [MicrosoftDocs/azure-stack-docs#128]
VERBOSE: 2019-05-27.13-36-21: Connection to AzS-ERCS01 successful
VERBOSE: 2019-05-27.13-36-21: Verifying stamp version.
VERBOSE: 2019-05-27.13-36-31: Running registration actions on build 1.1904.0.36. Cloud Id: xxxxxxxx
-xxxx-xxxx-xxxx-xxxxxxxxxxxx, Deployment Id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
VERBOSE: 2019-05-27.13-36-31: Creating Azure Active Directory service principal in tenant 'xxxxxxxx
-xxxx-xxxx-xxxx-xxxxxxxxxxxx' Attempt 0 of 3
VERBOSE: Looking up shared vhd product drive letter.
WARNING: Unable to find volume with label Deployment
VERBOSE: Get-Package returned with Success:True
VERBOSE: Found package Microsoft.AzureStack.Solution.Deploy.Security with version 1.1904.0.36 at C:
\NugetStore\Microsoft.AzureStack.Solution.Deploy.Security.1.1904.0.36\Microsoft.AzureStack.Solution
.Deploy.Security.nuspec.
VERBOSE: type added
VERBOSE: 2019-05-27.13-41-52: *** WARNING ***
WARNING: 2019-05-27.13-41-52: Creation of service principal failed:
Action plan execution failed. Error: Execution timeout
VERBOSE: 2019-05-27.13-52-36: *** End WARNING ***
VERBOSE: 2019-05-27.13-52-36: Waiting 10 seconds and trying again...
VERBOSE: 2019-05-27.13-52-46: ************************ Error ************************
VERBOSE: 2019-05-27.13-52-46: Action plan execution failed. Error: Execution timeout
VERBOSE: 2019-05-27.13-52-47: at Start-ActionPlanInstance, C:\Program Files\WindowsPowerShell\Modul
es\Microsoft.Azurestack.Activation\Microsoft.Azurestack.Activation.psm1: line 426
at New-AzureBridgeServicePrincipal, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Azurestack
.Activation\Microsoft.Azurestack.Activation.psm1: line 179
VERBOSE: 2019-05-27.13-52-47: *********************** Ending registration action during New-Service
Principal ***********************
VERBOSE: 2019-05-27.13-52-47: Logs can be found at: C:\MASLogs\Registration\AzureStack.Activation.S
et-AzsRegistration-2019-05-27.log  and  \\AzS-ERCS01\c$\maslogs 
VERBOSE: 2019-05-27.13-52-47: Removing any existing PSSession...
Action plan execution failed. Error: Execution timeout
At C:\AzureStack-Tools-master\Registration\RegisterWithAzure.psm1:1249 char:13
+             $servicePrincipal = Invoke-Command -Session $PSSession -S ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Action plan exe...ecution timeout:String) [], Ru 
   ntimeException
    + FullyQualifiedErrorId : Action plan execution failed. Error: Execution timeout

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ccb9b30-d08b-f263-c23e-abe9e399626a
* Version Independent ID: b25ce77b-1249-14d7-2634-e96f1c9fa0c4
* Content: [Register the ASDK with Azure](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-register#feedback)
* Content Source: [azure-stack/asdk/asdk-register.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-register.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by Alberto-Vega-MSFT** [comment]
@joseq-terawe Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by mattbriggs** [comment]
@joseq-terawe Thanks for your feedback. I'll get back to shortly. #in-progress

**Comment by mattbriggs** [comment]
@joseq-terawe This is an issue engineering is aware of. We will update our docs as soon as we know what we should do. I'm going to keep this open so that I can resolve when we have the fix ready. #in-progress

**Comment by TravisCragg-MSFT** [comment]
@joseq-terawe The solution was posted to the [Azure Stack MSDN Forums](https://social.msdn.microsoft.com/Forums/en-US/9e319e05-f498-4f75-a466-bf8593524395/cant-register-asdk-adfs-to-azure?forum=AzureStack), which is the best place for these kinds of issues. Here is the mitigation: 

> This issue is being caused due to an improper timeout on the service principal creation, and all we need to do is increase the timeout. 
> To mitigate this issue, you will need to open up the file at "C:\AzureStack-Tools-master\Registration/RegisterWithAzure.psm1" in an editor with ADMINISTRATOR PERMISSIONS, I prefer PowerShell ISE as it gives line numbers. 
> Line#1249 needs -TimeoutInSeconds 600 added to the "New-AzureBridgeServicePrincipal" cmdlet, and should look like this:
> $servicePrincipal = Invoke-Command -Session $PSSession -ScriptBlock { New-AzureBridgeServicePrincipal -RefreshToken $using:RefreshToken -AzureEnvironment $using:AzureEnvironmentName -TenantId $using:TenantId -TimeoutInSeconds 1800}
> 
> We are fixing this in the Registration Script as well, but for now the manual workaround is the best.  

We will now proceed to close this thread. If there are further questions regarding this matter, or if this does not fix your issue, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
