### ISSUE TITLE
curl example does not work with the aka.ms url

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1289]
curl example does not work with the aka.ms url, we need to provide the actual target url instead:

https://raw.githubusercontent.com/Azure/aks-engine/v0.55.4/examples/azure-stack/kubernetes-azurestack.json

Please use this url in the curl example command. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9652b7b-09b9-ace9-4ef7-abc413b9d52c
* Version Independent ID: 53c19bb0-3f77-d15c-87e2-33e1d442d73b
* Content: [Deploy Kubernetes cluster with AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster?view=azs-2008)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by mattbriggs** [comment]
!!!!

@walterov will update the curl link! thanks, Matt

#in-progress

**Comment by mattbriggs** [comment]
updated.

#please-close
