### ISSUE TITLE
Incorrect URL

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#1295]
In the section "Quick start: install and run DISKSPD" the incorrect URL is provided for the diskspd download.

The following path is provided:
https://github.com/Microsoft/diskspd/releases/download/v2.0.21a/DiskSpd-2.0.21a.zip
The correct path is:
https://github.com/Microsoft/diskspd/releases/latest/download/DiskSpd.zip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dcbfe3b-52e3-7cc4-0727-3055383db649
* Version Independent ID: c894cd31-5738-8a11-78ec-5ecb4b8ad341
* Content: [Use DISKSPD to test workload storage performance - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/diskspd-overview)
* Content Source: [azure-stack/hci/manage/diskspd-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/diskspd-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @jasonnyi
* Microsoft Alias: **jasonyi**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@aricbernard  Thanks for your feedback! We will investigate and update as appropriate.

**Comment by GitaraniSharma-MSFT** [comment]
@aricbernard , thank you for bringing this to our notice.

I have updated the URL for DISKSPD download :
From - https://github.com/Microsoft/diskspd/releases/download/v2.0.21a/DiskSpd-2.0.21a.zip 
To - https://github.com/microsoft/diskspd/releases/download/v2.0.21a/DiskSpd.zip

It will reflect shortly on the doc.

We are closing this issue for now. If there are further questions regarding this matter, please reply and we will gladly continue the discussion.
