### ISSUE TITLE
No AzureRM commands 

### ISSUE THREAD

**Issue by basawaqe** [MicrosoftDocs/azure-stack-docs#1296]
the commands are not correct as AzureRM contain no commands:
Get-AzureRMsUserSubscription
Set-AzureRMsUserSubscription

And to find a replacement for the commands (bear in mind its not AzureRM Modules nor Az Modules) as this is a specific commands for Azure Stack(Built in function that worked along with AzureRM Modules or Az Modules):

CommandType     Name                                               Version    Source                                                                                                                                                                             
-----------     ----                                               -------    ------                                                                                                                                                                             
Function        Get-AzsUserSubscription                            0.3.3      Azs.Subscriptions.Admin                                                                                                                                                            
Function        New-AzsUserSubscription                            0.3.3      Azs.Subscriptions.Admin                                                                                                                                                            
Function        Remove-AzsUserSubscription                         0.3.3      Azs.Subscriptions.Admin                                                                                                                                                            
Function        Set-AzsUserSubscription                            0.3.3      Azs.Subscriptions.Admin 

so the replacement part should be:

# Change user subscription owner
$subscription = Get-AzsUserSubscription -SubscriptionId $SubscriptionId
$Subscription.Owner = $OwnerUpn
Set-AzsUserSubscription -InputObject $subscription

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a227a2f7-001d-edb2-31d2-6dc020fa666d
* Version Independent ID: cae8db95-8311-3ff3-8c63-30d9c751d8e6
* Content: [Change the billing owner for an Azure Stack Hub user subscription - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-change-subscription-owner?view=azs-2008&tabs=azurerm)
* Content Source: [azure-stack/operator/azure-stack-change-subscription-owner.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-change-subscription-owner.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by mattbriggs** [comment]
@basawaqe  Thanks for the feedback.

#in-progress

**Comment by mattbriggs** [comment]
Updated. Thanks again!

#please-close
