### ISSUE TITLE
Create-AADIdentityApp.ps1 relies on the AzureRM modules

### ISSUE THREAD

**Issue by bowlerma** [MicrosoftDocs/azure-stack-docs#1299]
It appears that you have to have the AzureRM module for Azure Stack Hub installed for this script to work.

Is there a version of the script that works with Az, as AzureRM is now deprecated?  If not, please can the documentation be updated to reflect this dependency.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Prerequisites to deploy Azure App Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started?view=azs-2008)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by AjayKumar-MSFT** [comment]
@bowlerma, Thanks for the feedback! We are taking a look into this and will get back to you soon.

**Comment by BryanLa** [comment]
@bowlerma - thanks very much for your feedback, and apologies for the delay.
I've checked and there does not appear to be a version of the scripts that will work with the Az module.
As such, I've added a NOTE block to the prerequisites section, indicating that AzureRM is required, for now.

#please-close
