### ISSUE TITLE
Missing Adding SQL DBs in the availability group

### ISSUE THREAD

**Issue by jbpaux** [MicrosoftDocs/azure-stack-docs#13]
According to the release notes of App Service 1.5, in case it's deployed in HA, the DB must be added to the AG.
https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-app-service-release-notes-update-five

That would be good to have it here otherwise it's not really an HA architecture and it will fail at some point...
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 191cc116-9bd7-171c-cdfc-f48c41aef252
* Version Independent ID: a9a47181-f4c6-51d0-caea-e06d67996e60
* Content: [Deploy Azure Stack App Service in a highly available configuration](https://docs.microsoft.com/en-us/azure/azure-stack/app-service-deploy-ha)
* Content Source: [articles/azure-stack/app-service-deploy-ha.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/app-service-deploy-ha.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by mattbriggs** [comment]
@jbpaux Thanks for your feedback. I've added to the text to the topic. #please-close

**Comment by mattbriggs** [comment]
#please-close
