### ISSUE TITLE
Please add the following version mapping table to this document after the "upgrade path section"

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1302]
Add the table found here:

https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#aks-engine-versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2008)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by mattbriggs** [comment]
@walterov Adding the table.

**Comment by mattbriggs** [comment]
updated.

#please-close
