### ISSUE TITLE
Az Modules Last Line will return an Error

### ISSUE THREAD

**Issue by basawaqe** [MicrosoftDocs/azure-stack-docs#1303]
Set-AzsUserSubscription -InputObject $subscription will not Work.

this due newer Version from Azure Stack module "2.0.2-preview"
replacement:

$Subscription | Set-AzsUserSubscription | fl *

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a227a2f7-001d-edb2-31d2-6dc020fa666d
* Version Independent ID: cae8db95-8311-3ff3-8c63-30d9c751d8e6
* Content: [Change the billing owner for an Azure Stack Hub user subscription - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-change-subscription-owner?view=azs-2008&tabs=az)
* Content Source: [azure-stack/operator/azure-stack-change-subscription-owner.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-change-subscription-owner.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@basawaqe Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by PatAltimore** [comment]
Hi @basawaqe,

Thanks for finding the issue. I've made the fix to the article. The change will publish today.

Thanks,
Pat
#please-close
