### ISSUE TITLE
Add a link on function runtime comparison instead of root page for functions

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/azure-stack-docs#1309]
Big Azure supports 3 versions Functions, while Stack Hub on v1. It's better to replace link on root of azure functions page with a link on runtime comparison. https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions
![image](https://user-images.githubusercontent.com/578954/108032196-2329e500-7043-11eb-8a9c-3b2eed3b3725.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee9022e-5af6-93f0-8910-2200485917d1
* Version Independent ID: 25cea13d-78f7-e51b-acb0-582e71c14684
* Content: [Azure App Service on Azure Stack overview - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-overview?view=azs-2008)
* Content Source: [azure-stack/operator/azure-stack-app-service-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **BryanLa**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by BryanLa** [comment]
@SychevIgor - thanks for your feedback and [PR contribution.](https://github.com/MicrosoftDocs/azure-stack-docs/pull/1310)
@SaiKishor-MSFT - this makes sense to me. Adding @apwestgarth for his thoughts as well.

**Comment by BryanLa** [comment]
Completed. #please-close
