### ISSUE TITLE
Broken link to download Deployment Checker for ASDK

### ISSUE THREAD

**Issue by tysonflint** [MicrosoftDocs/azure-stack-docs#1312]
The link with this name can't find the download for the ASDK pre-req checker script.

Deployment Checker for ASDK
https://go.microsoft.com/fwlink/?LinkId=828735&clcid=0x409

It now redirects to the TechNet Gallery script samples browser.
![2021-02-16 23_24_24-Download Pre-Req Script -- Broken Link to Download](https://user-images.githubusercontent.com/1578227/108170045-6f5e3f00-70ae-11eb-936c-155b448e2054.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289cb46f-b173-0ec0-ace1-6e038f82c553
* Version Independent ID: 8f72a4e5-fba9-6631-1924-3b649446bf18
* Content: [Download and extract the ASDK - Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-download?view=azs-2008)
* Content Source: [azure-stack/asdk/asdk-download.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-download.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub-asdk**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by HarshitaSingh-MSFT** [comment]
Hello @tysonflint , thanks for taking time to share your valuable feedback! We are taking a look into this and will get back to you soon.

**Comment by HarshitaSingh-MSFT** [comment]
@tysonflint, I verified that the script was hosted on the retired `gallery.technet.microsoft.com`. We are working on updating the new link on [this](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-download?view=azs-2008) page and will keep you posted. Thanks again for reporting this!

**Comment by PatAltimore** [comment]
Hi @tysonflint,

Thanks for finding and reporting the issue. We've reviewed, updated, tested, and hosted the script on GitHub. The link has been updated to point to https://github.com/Azure/AzureStack-Tools/blob/master/Deployment/asdk-prechecker.ps1.

I'm going to close the issue.

Thanks,
Pat
#please-close
