### ISSUE TITLE
Reference to Set-AzVMBootDiagnostics (Quickstart: Create a Linux server VM by using PowerShell in Azure Stack Hub)

### ISSUE THREAD

**Issue by matiasdahl** [MicrosoftDocs/azure-stack-docs#1313]
Possible minor typo: The page

https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-quick-create-vm-linux-powershell.md

references `Set-AzVMBootDiagnostics`. 

Should it be [Set-AzVMBootDiagnostic](https://docs.microsoft.com/en-us/powershell/module/az.compute/set-azvmbootdiagnostic?view=azps-5.5.0)  (without s)? 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 675c83b0-1d6e-ca23-5434-0618c49d07b8
* Version Independent ID: 8743626e-03a7-0fe8-c856-ecdf5bf66486
* Content: [Create Linux VM with PowerShell in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-quick-create-vm-linux-powershell?view=azs-2008&tabs=az1%2Caz2%2Caz3%2Caz4%2Caz5%2Caz6%2Caz7%2Caz8)
* Content Source: [azure-stack/user/azure-stack-quick-create-vm-linux-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-quick-create-vm-linux-powershell.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by JamesTran-MSFT** [comment]
@matiasdahl 
Thanks for your feedback! We will investigate and update as appropriate.

![image](https://user-images.githubusercontent.com/36619112/108247744-eb38a580-7107-11eb-90a8-011797aa7ac0.png)

**Comment by mattbriggs** [comment]
@matiasdahl Thanks for your feedback. I'll update shortly. Thanks! Matt

#in-progress

**Comment by mattbriggs** [comment]
@TravisCragg-MSFT just letting you know. Cheers!

**Comment by mattbriggs** [comment]
@matiasdahl Created a PR and caught another Set-AzVMBootDiagnostic with an S. Thanks again for your feedback. The update should be live with our next doc build.

#please-close
