### ISSUE TITLE
Missing code in "Connected: Install with internet connectivity"

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#1317]
Prior to installing the modules as specified in "Connected: Install with internet connectivity" you must first update PowerShellGet to a minimum of version 2.2.3. To update PowerShellGet execute the following:
`
Install-Module PowerShellGet -MinimumVersion 2.2.3 -Force 
`
However, before this update takes effect, you must first close the PowerShell window and open a new PowerShell window.  In the new window you can then successfully execute the code specified in "Connected: Install with internet connectivity"
`
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Install-Module -Name Az.BootStrapper -Force -AllowPrerelease
Install-AzProfile -Profile 2019-03-01-hybrid -Force
Install-Module -Name AzureStack -RequiredVersion 2.0.2-preview -AllowPrerelease
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c7ec8b-634f-6b95-7ce1-c38d55b12c23
* Version Independent ID: 8cc3a38e-0bbc-71b4-2c37-fc6231bb540d
* Content: [Install PowerShell Az module for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2008)
* Content Source: [azure-stack/operator/powershell-install-az-module.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/powershell-install-az-module.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@aricbernard  thanks for your comments.

#in-progress

**Comment by mattbriggs** [comment]
Updated

#please-close
