### ISSUE TITLE
Error on Get-AzToken in Set-AzsRegistration - Unable to find type

### ISSUE THREAD

**Issue by bobleith** [MicrosoftDocs/azure-stack-docs#1318]
Any ideas on the below? Everything looks fine with the Azure Stack SDK install, No errors on the Test-AzureStack on Azs-ERCS01.  Everything seems to work and then last thing that happens is
Get-AzToken : Unable to find type [Microsoft.Azure.Commands.Common.Authentication.Authentication.Clients.AuthenticationClientFactory].
At C:\AzureStack-Tools-az\Registration\RegisterWithAzure.psm1:404 char:26
+ ... eshToken = (Get-AzToken -Context $AzureContext -FromCache -Verbose).G ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Azure...onClientFactory:TypeName) [Get-AzToken], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound,Get-AzToken

Below is a snippet of the last portion of the output leading up to that after the AzureContext 
info is displayed.

Thank you very much for your help, I'm dead in the water on this one.

VERBOSE: 2021-02-18.23-00-18: Initializing session with privileged endpoint: AzS-ERCS01. Attempt 0 of 3
VERBOSE: Looking up shared vhd product drive letter.
VERBOSE: For ERCS Machines :(AZS-ERCS01) return Volume as null as ERCS Machine use c:\NugetStore as nugetstore
VERBOSE: Get-Package returned with Success:True
VERBOSE: Found package Microsoft.AzureStack.Solution.Deploy.EnterpriseCloudEngine.Client.Deployment with version 1.2008.0.59 at C:\NugetStore\Microsoft.AzureStack.Solution.D
eploy.EnterpriseCloudEngine.Client.Deployment.1.2008.0.59\Microsoft.AzureStack.Solution.Deploy.EnterpriseCloudEngine.Client.Deployment.nuspec.
WARNING: The names of some imported commands from the module 'ECEClient' include unapproved verbs that might make them less discoverable. To find the commands with unapprove
d verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
VERBOSE: 2021-02-18.23-00-28: Connection to AzS-ERCS01 successful
VERBOSE: 2021-02-18.23-00-28: Verifying stamp version.
VERBOSE: 2021-02-18.23-00-32: Running registration actions on build 1.2008.0.59. Cloud Id: 4b3c43ac-2047-4800-9537-65ea7a0423a2, Deployment Id: 5a9eb328-648a-45ea-b115-82f00
626d34e
VERBOSE: Attempting to retrieve a token for account 'xxxx@xxx.com' in tenant 'xxxx' for resource 'https://management.core.windows.net
/'...
WARNING: Attempting to find a refresh token and an access token from the existing token cache data...
VERBOSE: 2021-02-18.23-00-32: Removing any existing PSSession...
Get-AzToken : Unable to find type [Microsoft.Azure.Commands.Common.Authentication.Authentication.Clients.AuthenticationClientFactory].
At C:\AzureStack-Tools-az\Registration\RegisterWithAzure.psm1:404 char:26
+ ... eshToken = (Get-AzToken -Context $AzureContext -FromCache -Verbose).G ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Azure...onClientFactory:TypeName) [Get-AzToken], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound,Get-AzToken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ccb9b30-d08b-f263-c23e-abe9e399626a
* Version Independent ID: b25ce77b-1249-14d7-2634-e96f1c9fa0c4
* Content: [Register the ASDK with Azure - Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-register?view=azs-2008&tabs=az1%2Caz2%2Caz3%2Caz4%2Caz5%2Caz6%2Caz7)
* Content Source: [azure-stack/asdk/asdk-register.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-register.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub-asdk**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by JamesTran-MSFT** [comment]
@bobleith 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
@bobleith Very sorry for the slow response here. As the ASDK is no longer officially updated, we are closing this issue. Please reopen if you still need assistance. Thank you and sorry again. #please-close
