### ISSUE TITLE
Add certificate property requirements

### ISSUE THREAD

**Issue by brsteel** [MicrosoftDocs/azure-stack-docs#1321]
Would be nice to add the required properties of the certificates.
See:
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-validate-pki-certs?view=azs-2008
Just a mention that the cert needs "Server Authentication" and "Client Authentication", the PFX should be encrypted with 3Des Sha1, etc

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Prerequisites to deploy Azure App Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started?view=azs-2008&pivots=state-connected)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@brsteel I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by BryanLa** [comment]
@brsteel - thanks for the feedback. 

We point the reader to the [Validate Certificates](https://docs.microsoft.com/azure-stack/operator/azure-stack-validate-pki-certs) article later, in [validate certificates](https://docs.microsoft.com/azure-stack/operator/azure-stack-app-service-before-you-get-started#validate-certificates), which does list the requirements that the tool validates for. LMK if it would be suitable to reference that early on, in the [certificate requirements section](https://docs.microsoft.com/azure-stack/operator/azure-stack-app-service-before-you-get-started#certificate-requirements) section. I think TripleDES-SHA1 is assumed as the default for PFX files, but I can also mention that in list of validations.

**Comment by BryanLa** [comment]
#please-close
