### ISSUE TITLE
description of clusterSubnet is incorrect.

### ISSUE THREAD

**Issue by Donnie-Zhang** [MicrosoftDocs/azure-stack-docs#1323]
Field | Example | Description
-- | -- | --
clusterSubnet | 172.16.244.0/24 | IP range of the cluster subnet (POD network) must use an IP range within the space of the custom VNET IP range you defined.

1. POD network should not use the same IP space as that of the VNET.
2. We should use /16 instead /24 subnet. If we use /24, this subnet will be assigned to one node only. Other node will not get POD network assigned (as we have run out of the IP space), so they will be not ready in the cluster.

Below is an example that a node has no POD network assigned.
++
NetworkUnavailable True Thu, 18 Feb 2021 13:27:00 +0000 Thu, 18 Feb 2021 13:27:00 +0000 NoRouteCreated RouteController failed to create a route
MemoryPressure False Wed, 24 Feb 2021 05:41:53 +0000 Thu, 18 Feb 2021 13:26:17 +0000 KubeletHasSufficientMemory kubelet has sufficient memory available
DiskPressure False Wed, 24 Feb 2021 05:41:53 +0000 Thu, 18 Feb 2021 13:26:17 +0000 KubeletHasNoDiskPressure kubelet has no disk pressure
PIDPressure False Wed, 24 Feb 2021 05:41:53 +0000 Thu, 18 Feb 2021 13:26:17 +0000 KubeletHasSufficientPID kubelet has sufficient PID available
Ready False Wed, 24 Feb 2021 05:41:53 +0000 Thu, 18 Feb 2021 13:26:17 +0000 KubeletNotReady runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: kubenet does not have netConfig. This is most likely due to lack of PodCIDR
++

https://github.com/Azure/aks-engine/blob/master/docs/topics/clusterdefinitions.md
clusterSubnet | no | The IP subnet used for   allocating IP addresses for pod network interfaces. The subnet must be in the   VNET address space. With Azure CNI enabled, the default value is   10.240.0.0/12. Without Azure CNI, the default value is **10.244.0.0/16**.
-- | -- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc538db2-5b34-3668-1e8e-1914b4b18c43
* Version Independent ID: 4f4c7701-f73c-ca0b-f7e4-62652a7ae66b
* Content: [Deploy Kubernetes cluster to custom virtual network on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-custom-vnet?view=azs-2008)
* Content Source: [azure-stack/user/kubernetes-aks-engine-custom-vnet.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-custom-vnet.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by mattbriggs** [comment]
@Donnie-Zhang Thanks for your feedback. I have a question out, and will update when I get an answer.

#in-progress

**Comment by mattbriggs** [comment]
updated.

#please-close
