### ISSUE TITLE
Typo in instructions

### ISSUE THREAD

**Issue by realgregoryk** [MicrosoftDocs/azure-stack-docs#1324]
[Enter feedback here]
Step #6 says go to App Permissions in the portal it should be go to API Permissions in the portal for Admin Consent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0b133de-ea80-3860-b8d2-00f1b109fef9
* Version Independent ID: cea18011-66a6-521c-1517-312a1508f1ab
* Content: [Register Windows Admin Center with Azure - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/register-windows-admin-center)
* Content Source: [azure-stack/hci/manage/register-windows-admin-center.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/register-windows-admin-center.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate this and update the document as appropriate

**Comment by khdownie** [comment]
@realgregoryk thanks for the catch - this is fixed now. @SaiKishor-MSFT this issue can now be closed:
https://docs.microsoft.com/en-us/azure-stack/hci/manage/register-windows-admin-center

**Comment by SaiKishor-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
