### ISSUE TITLE
Remove section "Supported scenarios with the AKS engine"

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1325]
I don't think this section adds info anymore, all areas mentioned are documented and this one is out of date. We can do this as part of the v0.60.1 docs release

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4810154-9f19-3f67-8c54-c2bb08edc2b4
* Version Independent ID: e99088a6-f7b1-cefd-4cad-3554423d4900
* Content: [What is the AKS engine on Azure Stack Hub? - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-overview?view=azs-2008)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov in-progress
