### ISSUE TITLE
Link to set-akshciconfig is Broken

### ISSUE THREAD

**Issue by lanicolas** [MicrosoftDocs/azure-stack-docs#1332]
The link under set-akshciconfig throws a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca3647ab-54da-0c66-c4ee-cf14f4adc4e1
* Version Independent ID: 8ea9f725-84c1-aeea-68c3-fbfab909d73a
* Content: [AksHci PowerShell module - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/akshci)
* Content Source: [azure-stack/aks-hci/akshci.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/akshci.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @jessicaguan
* Microsoft Alias: **jeguan**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@lanicolas Thanks for bringing this to our attention. I have submitted a PR to fix the issue that's in review.
Meanwhile, please refer to: [Set-AksHciConfig](https://docs.microsoft.com/en-us/azure-stack/aks-hci/set-akshciconfig).

**Comment by BhargaviAnnadevara-MSFT** [comment]
@lanicolas We will now proceed to close this thread as resolved, but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
