### ISSUE TITLE
VNET Peering is supported since version 2008

### ISSUE THREAD

**Issue by mihiguch** [MicrosoftDocs/azure-stack-docs#1335]
This page says:
>VNET to VNET VPN Connection. As VNET Peering is not yet available on Azure Stack Hub, use VNET to VNET VPN connection in order to connect the two VNETs. Please see VNET to VNET in Azure Stack Hub for more information.

However, other doc says it's supported since version 2008.
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-differences?view=azs-2008
>Supported since version 2008 Virtual Network peering

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53626034-9b54-0438-23db-7e2539493d6f
* Version Independent ID: e4ce9a49-ac2f-9ba2-a8b1-0edd8253edb3
* Content: [Run N-tier application in multiple Azure Stack Hub regions for high availability - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/iaas-architecture-sql-n-tier-multi-region?view=azs-2008)
* Content Source: [azure-stack/user/iaas-architecture-sql-n-tier-multi-region.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/iaas-architecture-sql-n-tier-multi-region.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate this and update the document as appropriate
