### ISSUE TITLE
Next Hop address might be wrong

### ISSUE THREAD

**Issue by mihiguch** [MicrosoftDocs/azure-stack-docs#1350]
Next Hop address in the picture might be wrong.
I think it should be:

RoutesForVNet1-rt
Address Prefix 10.2.0.0/16
Next Hop 10.1.1.4

and

RoutesForVNet2-rt
Address Prefix 10.1.0.0/16
Next Hop 10.2.1.4

Same comment is applied to:
https://docs.microsoft.com/en-us/azure-stack/user/network-howto-vpn-tunnel-gre?view=azs-2008
https://docs.microsoft.com/en-us/azure-stack/user/network-howto-vpn-tunnel-ipsec?view=azs-2008

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45cb846a-5db5-94b3-3e49-5d86f5884640
* Version Independent ID: 7c8ef065-2909-4888-47f1-2c3a7150fd60
* Content: [Connect two Azure Stack Hub VNETs - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-howto-vnet-peering?view=azs-2008#feedback)
* Content Source: [azure-stack/user/azure-stack-network-howto-vnet-peering.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-network-howto-vnet-peering.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@mihiguch Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@mihiguch Thanks for your feedback.

#in-progress

**Comment by mattbriggs** [comment]
Updated.

#please-close
