### ISSUE TITLE
Sentence unclear

### ISSUE THREAD

**Issue by cenkersoy** [MicrosoftDocs/azure-stack-docs#1353]
[Enter feedback here]

Could someone explain this sentence ? "Shared workers are multi-tenant and host free and shared App Service plans and consumption-based Azure functions for many tenants. "
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a844634b-8ece-f737-7686-b6a2231db1ba
* Version Independent ID: 2f928f50-bbbc-aece-41fa-f697ac62630b
* Content: [Azure App Service on Azure Stack Hub billing overview and FAQ - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/app-service-billing-faq?view=azs-2008)
* Content Source: [azure-stack/operator/app-service-billing-faq.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/app-service-billing-faq.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @apwestgarth
* Microsoft Alias: **anwestg**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@cenkersoy Thanks for the feedback. We shall evaluate and update the document as appropriate.

**Comment by sethmanheim** [comment]
@cenkersoy Very sorry for the slow response here. Please reach out for assistance if this is still an issue. #please-close
