### ISSUE TITLE
App Services on stack hub | SQL permissions

### ISSUE THREAD

**Issue by TrentShoun** [MicrosoftDocs/azure-stack-docs#1362]
In the app services prerequisites under "Prepare the SQL Instance"
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started?view=azs-2008&pivots=state-connected#prepare-the-sql-server-instance

We should list out what SQL permissions are required for the SQL account being used for app services. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Prerequisites to deploy Azure App Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started?view=azs-2008&pivots=state-connected#prepare-the-sql-server-instance)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by BryanLa** [comment]
Adding @apwestgarth for his thoughts, as I'm not sure what the actual account/perms would be.
