### ISSUE TITLE
deploymentType parameter is not documented.

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/azure-stack-docs#1363]
deploymentType parameter is not documented. Also will be great to have the parameter sort by descending alphabetical order

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7063b994-0e35-6c7e-3be9-b29de6047509
* Version Independent ID: fddeb894-cb94-8e42-a6b1-0d9100e0428b
* Content: [Set-AksHciConfig - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/set-akshciconfig)
* Content Source: [azure-stack/aks-hci/set-akshciconfig.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/set-akshciconfig.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @jessicaguan
* Microsoft Alias: **jeguan**

**Comment by DerekHerman-MSFT** [comment]
Thanks for reporting this. I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by abhilashaagarwala** [comment]
We dont need to pass deployment type anymore because this is now automatically detected.

**Comment by mattbriggs** [comment]
#please-close
