### ISSUE TITLE
Question regarding the maximum supported hardware specification

### ISSUE THREAD

**Issue by rfsonders** [MicrosoftDocs/azure-stack-docs#1369]
[Enter feedback here]
For this matrix
https://docs.microsoft.com/en-us/azure-stack/aks-hci/system-requirements#review-maximum-supported-hardware-specifications

More clarity is needed. Should be..  ( in parentheses )
Resource
Physical servers per cluster ( Azure Stack HCI Cluster ) =  4
Kubernetes Clusters ( per Azure Stack HCI Cluster ) = 4
Total number of VMs ( per Kubernetes Cluster ) = 4

I am interested in thoughts from this team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425ddc25-2a4b-c529-9d8c-b9e6975cfd1c
* Version Independent ID: 818658d6-3f73-7a88-93af-81018f971676
* Content: [Azure Kubernetes Service on Azure Stack HCI requirements - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/system-requirements)
* Content Source: [azure-stack/aks-hci/system-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/system-requirements.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @abhilashaagarwala
* Microsoft Alias: **abha**

**Comment by SaiKishor-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate this and update the document as appropriate.

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
Updated:
https://docs.microsoft.com/en-us/azure-stack/aks-hci/system-requirements#review-maximum-supported-hardware-specifications

Additional information:
https://docs.microsoft.com/en-us/azure-stack/aks-hci/concepts-support

Thanks again for this feedback.

#please-close
