### ISSUE TITLE
Pricing and offers has changed location in the new Partener center portal

### ISSUE THREAD

**Issue by raluca256** [MicrosoftDocs/azure-stack-docs#137]
Hello,
Can you please update the article with the new location for "Pricing and offers"?
Old:  Dashboard menu &gt; Pricing and offers
New:  Dashboard menu &gt; Sell &gt; Pricing and offers
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e65d7d7-0cd6-d81d-e8a2-a3e5d0ab447e
* Version Independent ID: f5192f3b-a187-7b94-f287-d3b08fc1baaa
* Content: [Usage reporting infrastructure for Cloud Service Providers for Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-csp-ref-infrastructure)
* Content Source: [azure-stack/operator/azure-stack-csp-ref-infrastructure.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-csp-ref-infrastructure.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@raluca256 Will do, thank you for catching this! Submitting a PR right now to fix this.

**Comment by sethmanheim** [comment]
Closing as the PR has just been merged. #please-close

**Comment by TravisCragg-MSFT** [comment]
@raluca256 We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
