### ISSUE TITLE
Data dedup feature/role missing from instructions

### ISSUE THREAD

**Issue by jamesaepp** [MicrosoftDocs/azure-stack-docs#1375]
Step 1.3: Install roles and features

Step does not include the data deduplication but the WAC wizard includes this feature ... what gives?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df3012c4-22e5-004d-da6f-60744f2cfb4f
* Version Independent ID: 57e21edd-9a2b-f1ca-2ff7-48e3da5dc260
* Content: [Create an Azure Stack HCI cluster using Windows PowerShell - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell)
* Content Source: [azure-stack/hci/deploy/create-cluster-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/deploy/create-cluster-powershell.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @v-dasis
* Microsoft Alias: **v-dasis**

**Comment by ram-msft** [comment]
@jamesaepp Thanks for the feedback! We will review and update accordingly.

**Comment by v-dasis** [comment]
This has been updated and is live: https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell
