### ISSUE TITLE
Add note about differences between online and offline marketplace

### ISSUE THREAD

**Issue by jgallucci32** [MicrosoftDocs/azure-stack-docs#14]
A note should be added explaining there is a different in content between the connected and disconnected marketplaces. For example, a connected Azure Stack has over 20 variants of F5 BIG-IP load balancers, but the marketplace syndication tool shows only 3 of the 20 are available. Several other items from the marketplace are missing as well.

It would be useful to explain why there is a difference and if its a matter of timing or if some items are not authorized for disconnected Azure Stack versus connected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da2c689d-3537-c125-3f00-d769c9b5aa0c
* Version Independent ID: 81e5de2b-da67-e875-405d-65628be05adc
* Content: [Download marketplace items from Azure](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-download-azure-marketplace-item#feedback)
* Content Source: [articles/azure-stack/azure-stack-download-azure-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-download-azure-marketplace-item.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@jgallucci32 Sorry for leaving this open so long. We have made modifications to this article, so if you still feel the information is missing, can you please open a new issue and @ mention me? Many thanks for your feedback! #please-close
