### ISSUE TITLE
Typos in Azure Stack Hub hotfix 1.2005.33.108

### ISSUE THREAD

**Issue by aluty** [MicrosoftDocs/azure-stack-docs#1401]
Fixed an issue in which partner node certificates required by nchotagent might be deleted.
**nchostagent**
Disabled winrrm runner
**winrm**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7da25b-56e5-d04a-b025-0c765b997acc
* Version Independent ID: ee049f22-7026-2967-5e14-835454a5d822
* Content: [Azure Stack Hub hotfix 1.2005.33.108 - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/hotfix-1-2005-33-108?view=azs-2005)
* Content Source: [azure-stack/operator/hotfix-1-2005-33-108.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/hotfix-1-2005-33-108.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by BharathNimmala-MSFT** [comment]
@aluty Thanks a lot for bringing this to our notice and helping us improve our Azure documentation. I have raised a PR to correct the typos. Once the PR is reviewed and approved , changes would go live. 

At this point it appears that there's no further edits or updates needed to the documentation, other than what has been listed above. We will go ahead and close this issue for now, however if you have any further feedback on the document please tag us in your reply and will be happy to reopen the thread and continue the conversation. Thank you
