### ISSUE TITLE
Missing details on SQL account requirements during install of App Service RP

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1404]
Received feedback on this doc from customer case:
> the pre reqs for admin rp is missing external SQL permissions for the DB creation and maintence...  I need to know what level of permission the local account requires to create and manage the DB. Ideally, we want to avoid SA if possible.

This is related to the section **#prepare-the-sql-server-instance**. Per discussion with Andrew Westgarth and Max Yang, these are the requirements-

1. We only support SQL Auth, not Windows Auth
2. It does not need to be the default root/sa/sqlsa account, but does require certain permissions. From App Service release notes, we expect to perform installation, “by a user that has the system administrator privilege, for example the SQL SA Account”.
3. The permissions are basically create/modify databases, tables, indices, store procedures, functions, roles, users and logins (if the sql is not containable).
4. The installation connection string appears in the AppService installer, ARM template, and AppService controller (CN0 and CN1), but AppService does not store that connection string. 
5. ARM templates have a protection mechanism for the connection string. 
6. After installation, only the connection string rotation need that account again, as it need to create new users (and logins); other operations, including upgrade, uses the AppService created account with proper permission.

Our reference ARM template for App Service SQL/File-server deployment template uses the sqlsa user by default- https://github.com/Azure/AzureStack-QuickStart-Templates/blob/master/appservice-fileserver-sqlserver-ha/azuredeploy.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Prerequisites to deploy Azure App Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started?view=azs-2008&pivots=state-connected#prepare-the-sql-server-instance)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by GitaraniSharma-MSFT** [comment]
@alexsmithMSFT , thank you for your feedback. We have assigned this to the content owner/author for review.

@BryanLa , please review the feedback and update the doc accordingly as it has already been discussed with Andrew Westgarth (anwestg).

**Comment by alexsmithMSFT** [comment]
Looks to be a dupe of https://github.com/MicrosoftDocs/azure-stack-docs/issues/1362

**Comment by BryanLa** [comment]
#1362 is closed - I'll be using the steps from @apwestgarth to update the article instead.

**Comment by alexsmithMSFT** [comment]
@BryanLa **not saying the requirements are the same**, but this doc section has a nice format that could be adapted to App Service RP SQL account requirements-
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-hosting-servers?view=azs-2008#required-privileges

**Comment by BryanLa** [comment]
Thanks @alexsmithMSFT . I like the format, but any thoughts on how to adapt # 3 from your [requirements list above](https://github.com/MicrosoftDocs/azure-stack-docs/issues/1404#issue-857327287) to a similar "Object: permission(s)" format? Seems like it would be:

Databases: create, alter
Tables: create, alter  << I omitted your "indices" one, as I think this would include perms to create/alter an Index?
Stored Procedures: create, alter
Functions: create, alter 
Roles: create, alter 
Users: create, alter
Logins: create, alter

**Comment by BryanLa** [comment]
After discussing further with @apwestgarth, he's going to open an ADO work item to track this. He'll do some tests as part of his release work to verify the correct perms. After his work item is complete, we'll update the article.

#please-close
cc: @alexsmithMSFT @TrentShoun
