### ISSUE TITLE
Add statements officially supporting Azure CNI network plugin

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1411]
From the top of this page-
> The Kubernetes cluster in Azure Stack Hub using the AKS engine uses the **kubenet** network plugin.

@walterov recently confirmed that we also support Azure CNI networking plugin. 

We should probably also update-
https://docs.microsoft.com/azure-stack/user/azure-stack-kubernetes-aks-engine-support#aks-engine-supported-areas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc538db2-5b34-3668-1e8e-1914b4b18c43
* Version Independent ID: 4f4c7701-f73c-ca0b-f7e4-62652a7ae66b
* Content: [Deploy Kubernetes cluster to custom virtual network on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-custom-vnet?view=azs-2008)
* Content Source: [azure-stack/user/kubernetes-aks-engine-custom-vnet.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-custom-vnet.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by alexsmithMSFT** [comment]
Some background info available for public AKS-
https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni
https://docs.microsoft.com/en-us/azure/aks/configure-kubenet

**Comment by BryanTrach-MSFT** [comment]
@alexsmithMSFT Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by mattbriggs** [comment]
@alexsmithMSFT Thanks for passing this info on I'll update.

#in-progress

**Comment by mattbriggs** [comment]
@alexsmithMSFT Added the links and statement about Azure CNI. Thanks Alex! Will appear in the next update.

#please-close
