### ISSUE TITLE
Proposal for update

### ISSUE THREAD

**Issue by prjelesi** [MicrosoftDocs/azure-stack-docs#1412]
step 4 of https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster?view=azs-2008#update-the-api-model

provide the URL to the tenant portal. For example, https://portal.local.azurestack.external. 

is making confusion with 

step 6: Find portalURL and provide the URL to the tenant portal. For example, https://portal.local.azurestack.external.

i would delete step 4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9652b7b-09b9-ace9-4ef7-abc413b9d52c
* Version Independent ID: 53c19bb0-3f77-d15c-87e2-33e1d442d73b
* Content: [Deploy Kubernetes cluster with AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster?view=azs-2008#feedback)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by BryanTrach-MSFT** [comment]
@prjelesi Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by mattbriggs** [comment]
@prjelesi Thanks for catching the duplicate step. I removed the second one. Thanks! The update will be on the site shortly.

Thanks!

#please-close
