### ISSUE TITLE
Missing part regarding running from linux on ADSK

### ISSUE THREAD

**Issue by prjelesi** [MicrosoftDocs/azure-stack-docs#1413]
when deployment is executed on ASDK from linux error will happened - missing root certificate for ADSK.

i would add lines:

if you are using the ASDK  you need to explicitly add the root certificate to the trusted certificate store of the machine. 
You can find the root certificate in the VM at this directory: /var/lib/waagent/Certificates.pem.
Copy the certificate file with the following command:

sudo cp /var/lib/waagent/Certificates.pem /usr/local/share/ca-certificates/azurestacka.crt 
sudo update-ca-certificates

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9652b7b-09b9-ace9-4ef7-abc413b9d52c
* Version Independent ID: 53c19bb0-3f77-d15c-87e2-33e1d442d73b
* Content: [Deploy Kubernetes cluster with AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster?view=azs-2008#feedback)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@prjelesi Thanks for providing feedback to help improve our docs. I'll update.

#in-progress

**Comment by mattbriggs** [comment]
updated.

#please-close
