### ISSUE TITLE
[ICM fix] Fix json example in "Update the API model" section

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1424]
This is needed to mitigate an ICM... Currently the "clusterSubnet" value in the json example in section "Update the API model" (https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-custom-vnet?view=azs-2008#update-the-api-model) has the wrong value for "clusterSubnet", the table above says that the value for "clusterSubnet" should be "10.244.0.0/16". Please change the json example to show the "10.244.0.0/16" value for "clusterSubnet", here is how it would look like:

"kubernetesConfig": [
  {
    ...
    "clusterSubnet": "10.244.0.0/16",
    ...
  },

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc538db2-5b34-3668-1e8e-1914b4b18c43
* Version Independent ID: 4f4c7701-f73c-ca0b-f7e4-62652a7ae66b
* Content: [Deploy Kubernetes cluster to custom virtual network on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-custom-vnet?view=azs-2008)
* Content Source: [azure-stack/user/kubernetes-aks-engine-custom-vnet.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-custom-vnet.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks!

#in-progress

**Comment by KrishnaG-MSFT** [comment]
@mattbriggs Thanks for the quick response. 👍

**Comment by mattbriggs** [comment]
updated.

#please-close
