### ISSUE TITLE
Images Aren't Readable in Dark Mode.

### ISSUE THREAD

**Issue by bandwiches** [MicrosoftDocs/azure-stack-docs#1426]
![image](https://user-images.githubusercontent.com/16140382/116929712-6ea46600-ac24-11eb-8206-45bb64b07b10.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d6ea47-e076-e8ca-04b8-caf60a394879
* Version Independent ID: 55f706e5-2200-ec76-9703-f507f029a5bd
* Content: [Configure IPsec/IKE site-to-site VPN connections in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-s2s?view=azs-2008&tabs=az1%2Caz2%2Caz3%2Caz4%2Caz5%2Caz8%2Caz6%2Caz7)
* Content Source: [azure-stack/user/azure-stack-vpn-s2s.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-vpn-s2s.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by JayaChatterjee-MSFT** [comment]
Thank you for your feedback! We will review and update as appropriate.

**Comment by TravisCragg-MSFT** [comment]
@bandwiches Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@bandwiches Very sorry for the slow response. The image has been updated with a white background and should appear live today after 10 AM PT. #please-close
