### ISSUE TITLE
PKI Next Steps

### ISSUE THREAD

**Issue by icestorm104** [MicrosoftDocs/azure-stack-docs#1428]
Right at the end it under the Using validated certificates section it states:

_For deployment, securely transfer your certificates to your deployment engineer so that they can copy them onto the **deployment host** as specified in the **Azure Stack Hub PKI requirements documentation**._

However, the PKI requirements documentation do not include any information. After research this appears to be referring to the deployment VM on the Hardware Lifecycle Host. This isn't clear and should be linked either to a more appropriate page. In the absence of this I have been trying to create a Visio to detail the process to provide further clarity to my end customer. This should probably be under the next steps section too.

Thanks

Robin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ca84a2-7dba-dab4-b591-976eb360baed
* Version Independent ID: 198d7378-7246-7b4b-bd73-564a1a593140
* Content: [Validate Azure Stack Hub PKI certificates - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-validate-pki-certs?view=azs-2008)
* Content Source: [azure-stack/operator/azure-stack-validate-pki-certs.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-validate-pki-certs.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by BryanLa** [comment]
Resolved. 
#please-close
