### ISSUE TITLE
Update Storage Section: 3.1

### ISSUE THREAD

**Issue by LeeCoxMS** [MicrosoftDocs/azure-stack-docs#1430]
We should update this section: https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell#step-31-prepare-drives

It should also exclude Removable drives on the Host nodes. If a customer is building this with a script set locally on the Primary Node it will wipe the Removable Storage they are using to build the cluster. I understand it's a corner case, but still a valid one if you're using Powershell and Remote scripts can have issues with specific functions.

Best,

Lee Cox - FTE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df3012c4-22e5-004d-da6f-60744f2cfb4f
* Version Independent ID: 57e21edd-9a2b-f1ca-2ff7-48e3da5dc260
* Content: [Create an Azure Stack HCI cluster using Windows PowerShell - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell)
* Content Source: [azure-stack/hci/deploy/create-cluster-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/deploy/create-cluster-powershell.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @v-dasis
* Microsoft Alias: **v-dasis**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by v-dasis** [comment]
note has been added to doc and merged. Will notify when this is live, thx!

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for bringing this to our attention. We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
