### ISSUE TITLE
Azure Active Directory domain?

### ISSUE THREAD

**Issue by ChaiSwaddipong** [MicrosoftDocs/azure-stack-docs#1436]
"In order to register an Azure Stack HCI cluster using Windows Admin Center, you must first register Windows Admin Center with Azure and supply your Azure Active Directory (tenant) ID. Make sure that the computer on which you run Windows Admin Center is joined to the same **Azure Active Directory domain** in which you'll create the cluster, or a trusted domain."

1. Could you clarify this **Azure Active Directory domain** ?  I think you meant to say just  Active Directory domain.
2. Perhaps, consider rewriting 
"Make sure that the computer on which you run Windows Admin Center is joined to the same **Azure Active Directory domain** in which you'll create the cluster, or a trusted domain."" 

to

"HCI cluster nodes need to join an active directory domain. Windows Admin Center must run on a computer, joined to the same domain or one with a trusted relationship."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a37b92a-145e-92f0-a55f-471927a3a0d6
* Version Independent ID: fd19801e-fb46-7ef4-1e38-b27c749824b6
* Content: [Connect Azure Stack HCI to Azure - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/register-with-azure)
* Content Source: [azure-stack/hci/deploy/register-with-azure.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/deploy/register-with-azure.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by khdownie** [comment]
Thanks @ChaiSwaddipong - you are correct. I will fix this today.

**Comment by VikasPullagura-MSFT** [comment]
@ChaiSwaddipong 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by khdownie** [comment]
@VikasPullagura-MSFT @ChaiSwaddipong this is fixed now. You can close this issue.
