### ISSUE TITLE
missing NSG on RRAS to allow the traffic in between the local and remote vnet

### ISSUE THREAD

**Issue by Donnie-Zhang** [MicrosoftDocs/azure-stack-docs#1438]
[Enter feedback here]

One customer followed this doc to deploy the S2S VPN tunnel using RRAS on two of this azure stack stamps. The tunnel was setup successfully, but tenant VM cannot talk to its peer on another stamp.
We figured out the problem is that we were miss the NSG rule on the RRAS to allow the traffic in between the two vNets in both inbound and outbound. Without this NSG, the RRAS will drop the packets when its IP is not either the source or destination IP.

We should allow source "LocalVNetAddressSpace", destination "RemoteVNetAddressSpace", protocal Any, port Any in both inbound and outbound.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c745c925-5ab8-7b3d-0f1b-4a60a63bd831
* Version Independent ID: aeb3a9fa-fe38-ac0d-f166-49354010562d
* Content: [Set up multiple site-to-site VPN tunnel in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/network-howto-vpn-tunnel?view=azs-2008)
* Content Source: [azure-stack/user/network-howto-vpn-tunnel.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/network-howto-vpn-tunnel.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by psmanhas** [comment]
@Donnie-Zhang Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate. We will update you accordingly.

**Comment by psmanhas** [comment]
@mattbriggs Can you please check and add your comments on this doc update request as applicable

**Comment by mattbriggs** [comment]
@psmanhas @Donnie-Zhang Thanks for your notes.

#in-progress
