### ISSUE TITLE
DHCP example has an incorrect name as example. Should be lowercase

### ISSUE THREAD

**Issue by dmc-tech** [MicrosoftDocs/azure-stack-docs#1455]
https://docs.microsoft.com/en-us/azure-stack/aks-hci/new-akshcinetworksetting#deploy-with-a-dhcp-environment has an incorrect example.  DHCPVnet is not a valid name with April-2021 PowerShell modules as the name must lowercase 

![image](https://user-images.githubusercontent.com/8145761/118647227-05525480-b7d9-11eb-9092-e54898b75adf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 795c8a21-73e6-b16f-d525-3f3e9f66a4c2
* Version Independent ID: 6b89d194-a7ef-399f-2253-95d98b0ddb5d
* Content: [New-AksHciNetworkSetting - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/new-akshcinetworksetting)
* Content Source: [azure-stack/aks-hci/new-akshcinetworksetting.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/new-akshcinetworksetting.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mkostersitz
* Microsoft Alias: **mikek**

**Comment by psmanhas** [comment]
@dmc-tech Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate. We will update you accordingly.

**Comment by psmanhas** [comment]
@mkostersitz Can you please check and add your comments on this doc update request as applicable

**Comment by mkostersitz** [comment]
@dmc-tech thanks for the feedback. We will update the document accordingly. The input for the name parameter for New-AksHciNetworksetting must be lowercase. @psmanhas I will submit a PR for the document.

**Comment by mattbriggs** [comment]
@dmc-tech Thanks!

#in-progress
