### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by jianfeng-jia** [MicrosoftDocs/azure-stack-docs#1458]
[Enter feedback here]
To send diagnostic logs from VirtualMachines and BareMetal roles, with date filtering for log files for the time period between 8 hours ago and 2 hours ago:

$fromDate = (Get-Date).AddHours(-8) -ToDate (Get-Date).AddHours(-2)
Invoke-Command -Session $pepsession -ScriptBlock {Send-AzureStackDiagnosticLog -FilterByRole VirtualMachines,BareMetal -FromDate $using:fromDate}

should be: 
$fromDate = (Get-Date).AddHours(-8) 
$toDate =  (Get-Date).AddHours(-2)
Invoke-Command -Session $pepsession -ScriptBlock {Send-AzureStackDiagnosticLog -FilterByRole VirtualMachines,BareMetal -FromDate $using:fromDate -ToDate $using:toDate}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29690f5d-25bc-84d2-6b9c-8e5d83f0162b
* Version Independent ID: bcc274b8-41fa-66e4-8cb1-50a5aee662e4
* Content: [Diagnostic log collection - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/diagnostic-log-collection?view=azs-2102)
* Content Source: [azure-stack/operator/diagnostic-log-collection.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/diagnostic-log-collection.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by psmanhas** [comment]
@jianfeng-jia Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.We will update you accordingly.

**Comment by psmanhas** [comment]
@PatAltimore Can you please check and add your comments on this doc update request as applicable

**Comment by PatAltimore** [comment]
Hi @jianfeng-jia,

Thank you for finding the issue and providing the fix. Your help is appreciated. I've made the edit and the fix should be published soon.

Thanks,
Pat

#please-close
