### ISSUE TITLE
2020.Q3 Installer Link Broken

### ISSUE THREAD

**Issue by binaryjanitor** [MicrosoftDocs/azure-stack-docs#1464]
Azure Stack App Service RP 2020.Q3 Installer link results in 404 error. Also 2020.Q3 Installer fails to load feed from https://go.microsoft.com/fwlink/?linkid=2136732

This effectively breaks this installer.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f38266c0-568b-4c1b-b5f6-84b97eb641df
* Version Independent ID: 56d70df8-b306-ca1c-4c84-65c423175995
* Content: [App Service on Azure Stack Hub 2020 Q3 release notes - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/app-service-release-notes-2020-q3?view=azs-2102)
* Content Source: [azure-stack/operator/app-service-release-notes-2020-Q3.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/app-service-release-notes-2020-Q3.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @apwestgarth
* Microsoft Alias: **anwestg**

**Comment by apwestgarth** [comment]
We are investigating the issue with the download and are actively working to resolve it as soon as possible.

**Comment by binaryjanitor** [comment]
@apwestgarth Thank you for the help and generally being awesome!

**Comment by apwestgarth** [comment]
This issue has since been resolved and links restored #please-close
