### ISSUE TITLE
Better safeguard for Install-AksHci 

### ISSUE THREAD

**Issue by ChaiSwaddipong** [MicrosoftDocs/azure-stack-docs#1466]
_"Now, you are ready to install the Azure Kubernetes Service on Azure Stack HCI host.

Install-AksHCi_"

Questions/observations:

1. Please specify where to run this command. Is it on one node or all nodes?
2. I accidentally ran it after creating K8S cluster. Then, the get-akshcicluster stopped working. There should be some sort of warning that there is a K8S cluster running. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed866116-e130-d450-f4b7-6b3f6d25c9fd
* Version Independent ID: 2d037dd0-14ca-9644-a218-0fad2e76c0e0
* Content: [Tutorial - Deploy a cluster in Azure Kubernetes Service on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/tutorial-kubernetes-deploy-cluster)
* Content Source: [azure-stack/aks-hci/tutorial-kubernetes-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/tutorial-kubernetes-deploy-cluster.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @jeguan
* Microsoft Alias: **jeguan**

**Comment by NavtejSaini-MSFT** [comment]
@ChaiSwaddipong We are checking this and will get back to you.

**Comment by TravisCragg-MSFT** [comment]
@ChaiSwaddipong Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by abhilashaagarwala** [comment]
Closing this issue because we've released multiple product updates and this shouldnt be an issue any longer. Please open a fresh issue if this persists in the Jan 2022 AKS-HCI build.
Release notes for AKS-HCI Jan 2022 build: https://github.com/Azure/aks-hci/releases/tag/AKS-HCI-2201
