### ISSUE TITLE
Missing storage access type

### ISSUE THREAD

**Issue by danborik** [MicrosoftDocs/azure-stack-docs#1493]
[Enter feedback here]
There should be explicitly specified required access type to storage account container which contains new VM image VHD. With default access type (Private) it is not possible to add new VM image. Blob access type has to be used at least.
Second thing is that neither adminportal nor AzS PowerShell  do not return any meaningful error, but only Failed status at newly added image. But it isn't a docs issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6a61eee-2c60-1a86-3e06-fa7689705d18
* Version Independent ID: 28759edc-2b94-e42e-3353-6ebe13b2a90f
* Content: [Add a custom VM image to Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-add-vm-image?view=azs-2102&tabs=image-add-portal%2Cimage-rem-portal)
* Content Source: [azure-stack/operator/azure-stack-add-vm-image.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-add-vm-image.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by MonikaReddy-MSFT** [comment]
@danborik - 
Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@danborik - 
Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged. For the PS Issue, we have added this in our backlog for our PG to look into it. 

 We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
