### ISSUE TITLE
Update screenshot. AKS on Azure Stack Hub HCI no longer in a preview

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/azure-stack-docs#1499]
Update this screenshot https://docs.microsoft.com/en-us/azure-stack/aks-hci/media/create-kubernetes-cluster/add-connection.png it's no longer up-to-date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eab013e-9d8b-6a9a-a7cc-91254cea0e5f
* Version Independent ID: 1307b887-14cd-cf0d-ff02-715c55bb8db7
* Content: [Quickstart to create a Kubernetes cluster using Windows Admin Center - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/create-kubernetes-cluster)
* Content Source: [azure-stack/aks-hci/create-kubernetes-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/create-kubernetes-cluster.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @davannaw-msft
* Microsoft Alias: **dawhite**

**Comment by MonikaReddy-MSFT** [comment]
@SychevIgor - Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@SychevIgor - 
Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
