### ISSUE TITLE
Following the steps produces Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by jamescmaki** [MicrosoftDocs/azure-stack-docs#15]
Here is a powershell script that  I ran from Windows 10 which results in the Invalid URI error. This is using the unmodified example. I have also tried modifying the example extensively with no success. What changes need to be made in order for the packager to succeed?

wget http://www.aka.ms/azurestackmarketplaceitem -OutFile example.zip
Expand-Archive .\example.zip
cd '.\example\Azure Stack Marketplace Item Generator and Sample'
.\AzureGalleryPackageGenerator\AzureGalleryPackager.exe package -m .\SimpleVMTemplate\manifest.json -o .

Result:

Invalid URI: The format of the URI could not be determined.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83d0ba3d-9766-30da-70f0-5f4c3ec9a47e
* Version Independent ID: 6a9509a1-f16c-f527-5df1-9dae2d8eeaed
* Content: [Create and publish a Marketplace item in Azure Stack](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-create-and-publish-marketplace-item#feedback)
* Content Source: [articles/azure-stack/azure-stack-create-and-publish-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Solaflex** [comment]
This issue is still happening (verified today).
Can you give us an update on the expected date of delivery for the fix ?

We have this issue as showstopper for a customer solution on Azure Stack.

**Comment by GTMer** [comment]
@jamescmaki @Solaflex Change path of manifest and out to absolute path will fix this issue.

**Comment by Solaflex** [comment]
@GTMer I can confirm your fix. absolute path will fix the issue. Thank you!

**Comment by sethmanheim** [comment]
@GTMer @jamescmaki @Solaflex Very sorry for the slow response, but yes -- this issue has been reported and I have updated the topic in question to indicate the absolute path is required -- I added the note in a couple of places. Thank you again for the feedback!

**Comment by sethmanheim** [comment]
Please open another issue if you have any further questions. Thank you! #please-close
