### ISSUE TITLE
New release of AKS Engine v0.63.0

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1506]
We have a new version of AKS Engine v0.63.0. there are only new K8s version, not new features. We need to apply the following changes to the release notes:

1. In table "AKS engine and Azure Stack version mapping" add a new row mapping ASH version 2102 to AKSe versions 0.60.1 and 0.63.0

2. In table "Kubernetes version upgrade path in AKS engine v0.60.1" change:
   a. change the title to reference v0.63.0 instead of v0.63.0
   b. add new 3 rows to the table to map each of these (one per line): 1.18.15 to 1.18.18, 1.18.18 to 1.19.10, and 1.19.10 to 1.20.6

3. In table "AKS engine and corresponding image mapping" add a new row with the following information:

v0.63.0 | AKS Base Ubuntu 18.04-LTS Image Distro, 2021 Q2 (2021.05.24), AKS Base Windows Image (17763.1935.210520) | 1.18.18, 1.19.10, 1.20.6 | API Model Samples (Linux,&nbsp;Windows)

Each of the items in the table have links:

v0.63.0 = https://github.com/Azure/aks-engine/releases/tag/v0.63.0

AKS Base Ubuntu 18.04-LTS Image Distro, 2021 Q2 (2021.05.24) = https://github.com/Azure/aks-engine/blob/v0.63.0/vhd/release-notes/aks-engine-ubuntu-1804/aks-engine-ubuntu-1804-202007_2021.05.24.txt

AKS Base Windows Image (17763.1935.210520) = https://github.com/Azure/aks-engine/blob/v0.63.0/vhd/release-notes/aks-windows/2109-datacenter-core-smalldisk-17763.1935.210520.txt

Linux = https://github.com/Azure/aks-engine/blob/v0.63.0/examples/azure-stack/kubernetes-azurestack.json

Windows = https://github.com/Azure/aks-engine/blob/v0.63.0/examples/azure-stack/kubernetes-windows.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2102)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks Walter

#in-progress

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by mattbriggs** [comment]
Updated.

#please-close
