### ISSUE TITLE
New release of AKS Engine v0.63.0 Part 2

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1507]
For the "What's new" section change:

Remove the bullet list and add only one bullet item:

Support for Kubernetes 1.18.18, 1.19.10, 1.20.6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2102)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks Walter

#in-progress

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by mattbriggs** [comment]
Updated.

#please-close
