### ISSUE TITLE
Storage Tiers monitoring and reporting

### ISSUE THREAD

**Issue by i3laze** [MicrosoftDocs/azure-stack-docs#1510]
There's no documentation on monitoring and reporting of Storage Tiers performance and cache hit ratio.
One for Server 2012 and defrag.exe is currently obsolete:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn789160(v=ws.11)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73197027-3340-4b3a-ea69-87737dd7152a
* Version Independent ID: c28e92b8-46d5-31b1-44ce-abec49cfcf3a
* Content: [Create volumes on Azure Stack HCI and Windows Server clusters - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/create-volumes)
* Content Source: [azure-stack/hci/manage/create-volumes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/create-volumes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by psmanhas** [comment]
@i3laze Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate. We will update you accordingly.

**Comment by psmanhas** [comment]
@khdownie Can you please check and add your comments on this doc update request as applicable

**Comment by i3laze** [comment]
Thanks for rapid response.
I’m particularly interested in Storage Spaces Direct/Azure Stack HCI cluster running Tiered Storage.

**Comment by i3laze** [comment]
@khdownie no updates so far?

**Comment by khdownie** [comment]
@i3laze thanks for the reminder. I must have missed this the first time. I will look into it.

**Comment by i3laze** [comment]
Still looking into Win2016+ Tiered Spaces monitoring.
Particularly Mirror Accelerated Parity drives me crazy with its cold tier write performance - I need more data to make decisions.

**Comment by sethmanheim** [comment]
Please reopen a new GitHub issue if this is still an issue.
