### ISSUE TITLE
Need clarification in the Update fails section

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1512]
The section "Update to 2102 fails during pre-update checks for AKS/ACR" says 

"Applicable: This issue applies to Azure Kubernetes Service (AKS) and Azure Container Registry (ACR) private preview customers.
Remediation: You must uninstall AKS and ACR prior to updating to 2102. Please restart the update after uninstalling these services."

We need to change it to:

"Applicable: This issue applies to Azure Kubernetes Service (AKS) and Azure Container Registry (ACR) private preview customers who plan to upgrade to 2102 or apply any hotfixes.
Remediation: You must uninstall AKS and ACR prior to updating to 2102 or prior to applying any hotfixes after updating to 2102. Please restart the update after uninstalling these services."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0094b74f-e85b-6983-5f58-ce24f825b63c
* Version Independent ID: a90feafe-0401-3da0-bb95-4dbc8868ea0f
* Content: [Azure Stack Hub known issues - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-2102#update-to-2102-fails-during-pre-update-checks-for-aksacr)
* Content Source: [azure-stack/operator/known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/known-issues.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
Thanks @walterov, I have opened a PR in the private repo. Should be live by 3 PM today PT. #please-close

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim Thanks for fixing the document.
