### ISSUE TITLE
Change section "Download New Image"

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1513]
Need to change this section to say

The aks-engine binary (required)
AKS Base Ubuntu 16.04-LTS Image Distro (deprecated - no longer use, change in API Model to use 18.04 instead)
AKS Base Ubuntu 18.04-LTS Image Distro (required for Linux agents)
AKS Base Windows Server Image Distro (required for Windows agents)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2102)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov #in-progress

**Comment by mattbriggs** [comment]
Updated. #please-close

**Comment by VikasPullagura-MSFT** [comment]
@mattbriggs Thanks for updating the document.
