### ISSUE TITLE
AKS Base 16.04

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-stack-docs#1518]
the below table shows that 1604 AKS Base image is available for AKS-Engine 0.60.1
![image](https://user-images.githubusercontent.com/54538594/122742060-43d2a780-d28e-11eb-8062-b1bd23ef3503.png)
On the other hand, it is mentioned that 1604 is deprecated
![image](https://user-images.githubusercontent.com/54538594/122742214-649afd00-d28e-11eb-8344-09307c30768e.png)

do we have discrepancy in this documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2102#download-new-image-and-aks-engine)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by VikasPullagura-MSFT** [comment]
@HassanAlmanasrah 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@mattbriggs 
Can you please check and add your comments on this doc update request as applicable.

**Comment by mattbriggs** [comment]
@HassanAlmanasrah Thanks for catching this. updating...

#in-progress

**Comment by mattbriggs** [comment]
updated.

#please-close
