### ISSUE TITLE
Cisco contact links are missing

### ISSUE THREAD

**Issue by walkerlin-msft** [MicrosoftDocs/azure-stack-docs#1522]
[Enter feedback here]
The 2 Cisco links of OEM contact information
![Cisco OEM contact](https://user-images.githubusercontent.com/21300840/123069767-b0dc6d80-d445-11eb-87e0-1cab49d33058.PNG)
 are redirected to the Bing search, please update them as correct information.
https://aka.ms/aa708e2
https://aka.ms/aa700rq
![image](https://user-images.githubusercontent.com/21300840/123069616-84285600-d445-11eb-8d80-3fa2cdb85bc2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2be586d-1a43-6f3f-a4e7-47b37646d84e
* Version Independent ID: 89a53e5e-e055-397f-1288-cd6f7951ba4a
* Content: [Apply an OEM update to Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-update-oem?view=azs-2102)
* Content Source: [azure-stack/operator/azure-stack-update-oem.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-update-oem.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by VikasPullagura-MSFT** [comment]
@walkerlin-msft 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@PatAltimore 
Can you please check and add your comments on this doc update request as applicable.

**Comment by PatAltimore** [comment]
Hi @walkerlin-msft,

I've updated the links. The changes will publish tomorrow.

Thanks,
Pat

#please-close
