### ISSUE TITLE
Which OS should be used for SDN infrastructure VM ?

### ISSUE THREAD

**Issue by Li-Yanzhi** [MicrosoftDocs/azure-stack-docs#1523]
In section create **`Create the VHDX file`**,  it said **"SDN uses a VHDX file containing the Azure Stack HCI operating system (OS) as a source for creating the SDN virtual machines (VMs). The version of the OS in your VHDX must match the version used by the Azure Stack HCI Hyper-V hosts"**, but in the following examples, it uses **WindowsServerDatacenter** image for create VHDX file.

And if I use Azure Stack OS to create VHDX file and use it as SDN VMs (NC, Gateway or Mux), then in Events of each SDN VM, it will prompt an Warning **Azure Stack HCI needs to join a cluster within 30 days of installing the operating system. Create a new cluster or join an existing one.** every hour, but in general, this VM will not be add to cluster for hosting virtualization workload.

So the question is:
1)  Which OS should be used for SDN infrastructure VM  (if SDN is used for Azure Stack HCI cluster)?
2)  If used Azure Stack HCI OS for SDN VMs,  should we add SDN VMs to a Azure Stack HCI cluster? If we do not add to cluster, what will happen after 30 days?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01571ef6-1345-ed10-4033-6d031b769dac
* Version Independent ID: 7943811e-8822-7e0d-ba9a-172daf986312
* Content: [Deploy an SDN infrastructure using SDN Express - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/sdn-express)
* Content Source: [azure-stack/hci/manage/sdn-express.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/sdn-express.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @v-dasis
* Microsoft Alias: **v-dasis**

**Comment by v-dasis** [comment]
Thanks for the feedback , am investigating...

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by Li-Yanzhi** [comment]
@v-dasis I have an another question, if we use both Azure Stack HCI cluster and Windows Server 2019 (SDDC) cluster in same datacenter and managed by same SDN infrastructure,  what OS we should use for SDN infrastructure VMs?

**Comment by v-dasis** [comment]
SDN infrastructure VMs should be on same OS type as the underlying hosts. So, if you have a HCI cluster, the SDN VMs should be on the HCI OS. And if you have a Windows Server cluster, the SDN VMs should be on the Server Datacenter OS. One SDN cluster cannot manage a mix of HCI and Server hosts.

The SDN VMs use the Azure Stack HCI OS. Although the event comes up and can be annoying, it will not have an adverse effect. Customers will be able to use SDN VMs even after 30 days.

Hope this helps...

**Comment by Li-Yanzhi** [comment]
> SDN infrastructure VMs should be on same OS type as the underlying hosts. So, if you have a HCI cluster, the SDN VMs should be on the HCI OS. And if you have a Windows Server cluster, the SDN VMs should be on the Server Datacenter OS. One SDN cluster cannot manage a mix of HCI and Server hosts.
> 
> Hope this helps...

Can you officially confirm this?  It's a hardcoded technical constraints , or license limitation (but actually works), or just not the best practice?  We have customer using SDDC clusters currently and have plan to use Azure Stack HCI for part of workload only if the SDDC clusters and HCI clusters will co-exist in same SDN infrastructure.

**Comment by AnirbanPaul** [comment]
It may work, there is no hardcoded technical constraint right now. But, it is not officially supported.

Please reach out to sdn_feedback@microsoft.com. We can discuss available options for the customer.

**Comment by Li-Yanzhi** [comment]
@AnirbanPaul @v-dasis Thanks for you comments, and we will contact SDN team with customer scenario.

**Comment by shashishailaj** [comment]
We will close this now as this is being taken offline.

**Comment by aricbernard** [comment]
I would like to see this reopened.  Both WAC and the current SDNExpress automation appear to fail if an Azure Stack HCI OS 21H2 image are used.

**Comment by AnirbanPaul** [comment]
HI
Can you please tell us where you see the failure? And can you provide the failure details.

Thanks
Anirban

**Comment by xYorickx** [comment]
Hi Anirban,

Aric is my colleague and we have been working on this together.
We see the same failure in 3 different lab setups.
The screenshot you see is from the network controller VM after it has been created by WAC.

**Comment by AnirbanPaul** [comment]
Thanks for the feedback. I would like to take a look at logs for the deployment. If you are using Windows Admin Center for deploying Network Controller, the logs will be in the Documents folder of the first HCI host. You can send the logs to ***@***.******@***.***>.
NOTE: You should be using an Azure Stack HCI vhdx file for NC deployment on an Azure Stack HCI cluster.

Also, would you be willing to get on a call to discuss the issue if needed?

Thanks
Anirban

**Comment by aricbernard** [comment]
I think part of the issue may have been the lack of good instructions for creating an Azure Stack HCI VHDX.  We created one and ran sysprep within it.  However that seem to break the VHDX.  The process documented to create the VHDX in the docs was broken (we reported this bad link) . We connected with someone in support that provided additional guidance for the VHDX creation.  We are close to being able to test again.  I will report back more soon.

**Comment by aricbernard** [comment]
@AnirbanPaul creating the VHDX using Convert-WindowsImage (once I worked through the bad links links in the Docs etc.) did work and allowed me to deploy an NC using the image (with SDNExpress).  However, something is not shaking out properly with the SDN deployment even through SDNExpress says it completed successfully.  Where is the best place to start troubleshooting?  Are there logs?  EventLogs on the NC maybe?

**Comment by AnirbanPaul** [comment]
Can you provide more details on what is failing? That will given an idea on how to investigate further and what logs to collect. Alternatively, we could discuss over a call as well.

Thanks
Anirban

**Comment by aricbernard** [comment]
Happy to have a call next week.  I am in GMT-8 but can be somewhat flexible.

My latest attempt to deploy is using WAC (instead of SDNExpress) and it is 'hanging' in the "Network Controller creation" following successfully executing "Virtual machine creation".

**Comment by aricbernard** [comment]
BTW - GitHub is blocking the display of all email addresses, so I cannot email you the logs.

**Comment by AnirbanPaul** [comment]
Please send mail to sdn_feedback at microsoft.com with the logs. We can figure out a time slot for a call as required.
