### ISSUE TITLE
Need to remove explicit links to json files and point to the release notes for them instead

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1526]
Customers keep getting confused by having multiple links to json files. Instead could we tell them to use the json files referenced for the specific version of AKS Engine in the release notes? In the case of the bash command we can simply say that the command would look like that but the the link to use is in the release notes. Would that work? This allies to Linux ad Windows json files (API Models)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9652b7b-09b9-ace9-4ef7-abc413b9d52c
* Version Independent ID: 53c19bb0-3f77-d15c-87e2-33e1d442d73b
* Content: [Deploy Kubernetes cluster with AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster?view=azs-2102)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov This makes sense. I'll review and update and send you the review link. #in-progress

**Comment by mattbriggs** [comment]
Updated.

#please-close
