### ISSUE TITLE
Time Synchronization section needs updating

### ISSUE THREAD

**Issue by jwk55** [MicrosoftDocs/azure-stack-docs#1528]
[Hello,

With respect to an NTP server. In addition to a FQDN or IP address stack requires ",0x1" or ",0x8" (depending if NTP server is windows or non-windows) to be added to the end of each NTP server name or address.  We installed 2102 on our stack and when we attempted to apply a minor update we received the error that the PDC was not configured to use the NTP server, was instead synchronized to the CMOS clock of the virtual host. To resolve we had to run Set-AzSTimeSource -TimeServer "[IP],0x8"

The deployment worksheet needs to be modified also, when we add the ",0x8" to the end of our NTP server the worksheet throws an error that the IP is invalid. I will submit a separate bug for that.

Thank you,
Jason.Kelley@microsoft.com]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d144a188-4eb1-b940-89bd-ab23e7ba88f6
* Version Independent ID: fcac9f2a-5b1e-37ff-a768-fa6d8350ec6f
* Content: [Plan datacenter integration for Azure Stack Hub integrated systems - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-datacenter-integration?view=azs-2102&source=docs#time-synchronization)
* Content Source: [azure-stack/operator/azure-stack-datacenter-integration.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-datacenter-integration.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by VikasPullagura-MSFT** [comment]
@jwk55 
Thanks for the feedback! We are currently investigating and will get back on this.

**Comment by TravisCragg-MSFT** [comment]
@jwk55 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by PatAltimore** [comment]
Hi @jwk55,

Thanks for logging an issue. Are you saying the documentation needs to be clearer or the capacity planner worksheet needs to be fixed? (or both).

I own the article. I'm trying to understand what needs to be updated in the article. 

For the worksheet, I can pass the feedback along to the capacity planner worksheet owner.

Thanks,
Pat

**Comment by jwk55** [comment]
Hi Pat,

I am a CE. Working with a customer we ran into some issues with time.  2 things need to happen.


  1.  The Time Synchronization section needs to be clearer because most users are going to insert the IP address of an NTP server or a FQDN. In the docs article there is no mention of appending “,0x1” or “,0x8” at the end of your time source. Those characters are needed, otherwise when you run test-azure stack the infrastructure clock test will fail. When it comes to NTP there is distinction on why to use a 1 or 8…….Lee Haughton provided assistance on this issue and may shine some light on it.


  1.  The deployment worksheet needs to be modified also. If a user does try to enter an NTP server IP address properly formatted such as “10.1.1.123,0x8” the worksheet will give an error. Steve Linehan said he will file a bug on this as well.

Please feel free to hit me up on teams if you have any questions.

Jason Kelley

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PatAltimore** [comment]
#in-progress

**Comment by PatAltimore** [comment]
Hi @jwk55,

I published an update to the article. It will publish soon.

Thanks!
Pat

#please-close
