### ISSUE TITLE
Supported CentOS versions do not match Azure Stack marketplace image versions

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#153]
This doc says “CentOS-based 7.4”, but "Add from Azure" marketplace images only have 7.3 and 7.5 options. 

Per a support case, customer wants clarification on which specific CentOS versions are supported on Azure Stack. 

1. Confirm whether 7.3 and 7.5 marketplace images are supported
2. Confirm whether customer can still deploy 7.4 if they bring their own image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf72767c-5772-1398-dfbc-2f736aeb3e2a
* Version Independent ID: c8f3ce87-baa9-5a4f-6b2e-f0dd6614c6a3
* Content: [Supported guest operating systems for Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-supported-os)
* Content Source: [azure-stack/operator/azure-stack-supported-os.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-supported-os.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@alexsmithMSFT Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@alexsmithMSFT Checking with the product team.

**Comment by kivenkat** [comment]
Customer can stil bring their own image for 7.4 as long as they follow Azure guidelines

**Comment by sethmanheim** [comment]
#please-close
