### ISSUE TITLE
Should state not to use .local for the external DNS zone

### ISSUE THREAD

**Issue by mattcowen** [MicrosoftDocs/azure-stack-docs#1534]
When configuring an external DNS zone and forwarding from Stack Hub's DNS, it is best customers don't use a .local domain. This can cause issues for some workloads like the vanilla Ubuntu 18.04 vm image that, by default, uses systemd-resolved service to route DNS queries. Systemd-resolved does not respond to queries for .local domains so DNS settings for Ubuntu would have to be updated to resolve storage account and ARM endpoint URLs from within VMs running on the Stack Hub.

We should add a "NOTE" to this effect on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0403da-4784-000f-2c14-50257ae7c37f
* Version Independent ID: 2b4f5bc1-66f6-4c7f-c06e-bc32f2acd383
* Content: [Azure Stack Hub datacenter DNS integration - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-dns?view=azs-2102)
* Content Source: [azure-stack/operator/azure-stack-integrate-dns.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-dns.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by MonikaReddy-MSFT** [comment]
@mattcowen - 
Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
