### ISSUE TITLE
Some comments about this documentation which cause confusion and misunderstanding for customer as well as some typos:

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-stack-docs#1535]
**[Typos]**
- Step 2: **The tool includes sample packages that are in the .azpk format, and must be extracted first. You can rename the file extensions from ".azpk" to ".zip," or use an archiver tool of your choice:**
--> it should be ".azpkg"
- In step 7: **For all fields referring to ms-resource, you must change the appropriate values inside the strings/resources.json file:**
--> the file name in the package is: **resources.resjson**
- Step 14: **When you finish modifying your files, convert it to an .azpkg file. You perform the conversion using the AzureGallery.exe tool and the sample gallery package you downloaded previously. Run the following command:
.\AzureGalleryHubGallery.exe package -m c:\<path>\<gallery package name>\manifest.json -o c:\Temp**
--> the execution file name is incorrect in both of the above, correct name is: AzureStackHubGallery.exe

**[Confusion]**

- Step 6: **Replace the following highlighted values (those with numbers) in the Manifest.json template with the value that you provided when**
--> initial look at sample file, it was understood that we need to fill information for variables from 1 to 7, and to keep **ms-resource:** at the beginning of some parameters, since ms-resource: has to be removed from the json, maybe worth to mention that it has to be removed.
--> It is understood from step 7 that we need to add parameters in manifest.json which has **ms-resource:** 
- Step 9: **To ensure that the resource can be deployed successfully, test the template with the Azure Stack Hub APIs.**
--> the URL direct us to Azure Stack APIs, however there is no procedure to test the template
Step 10: **If your template relies on a virtual machine (VM) image, follow the instructions to add a VM image to Azure Stack Hub.**
--> since, this documentation is about adding marketplace item. there should be template, is the statement correct here?
Step 11:**Save your Azure Resource Manager template in the /Contoso.TodoList/DeploymentTemplates/ folder.**
--> is the above path correct?  does it mean, DeploymentTemplates folder in the package where manifest file is located

Sorry for the several points above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e401ae26-588f-124f-09a8-f1f6dc75da4e
* Version Independent ID: 6a9509a1-f16c-f527-5df1-9dae2d8eeaed
* Content: [Create and publish a Marketplace item in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-create-and-publish-marketplace-item?view=azs-2008&tabs=az)
* Content Source: [azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by MonikaReddy-MSFT** [comment]
@HassanAlmanasrah - 
Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@HassanAlmanasrah - Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged.  If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue. 

@mlearned - Can you take a look at the above couple of issues that the customer is asking for a templates. Please provide your insights.

**Comment by sethmanheim** [comment]
@HassanAlmanasrah Thank you for your feedback. The article describes creating your own Azure Resource Manager template to use to create a custom marketplace item and deploy it. If you are not familiar with ARM templates, see https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/quickstart-create-templates-use-the-portal. In Azure Stack, you will need to use API version profiles: https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles?view=azs-2008, and that is the link that's provided.

Sorry for the confusion on the last point: Contoso.TodoList is just an example. When you rename the .azpkg file to .zip and extract it, you will see the /DeploymentTemplates folder.

Please ask any followup questions you may have, and if necessary I will engage some product team assistance. Thanks again for reaching out.

**Comment by MonikaReddy-MSFT** [comment]
@sethmanheim  - Thank you for providing your insights.
@HassanAlmanasrah - I hope @sethmanheim  has answered your question. 
At this moment, Since there is no doc update required, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
