### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by fabianotex** [MicrosoftDocs/azure-stack-docs#1537]
Documentation states that I can use Built-in "Owner" **OR** "User Access Administrator"

"If your Azure subscription is through an EA or CSP, the easiest way is to ask your Azure subscription admin to assign a built-in "Owner" **or** "User Access Administrator" Azure role to your subscription."

Admin assigned "User Access Administrator", however that is not enough permission to register the Cluster via Windows Admin Center. Getting the following error:

Message
Failed to register with Azure for cluster: xyz.local. Error: RemoteException: The client 'user@domain.onmicrosoft.com' with object id 'xxxxxxxxx' does not have **authorization** to perform action 'Microsoft.AzureStackHCI/register/action' over scope '/subscriptions/xxxxxxxxxxxx' or the scope is invalid. If access was recently granted, please refresh your credentials. StatusCode: 403 ReasonPhrase: Forbidden OperationID : xxxxxxxxxxxxxxx

Unable to create Custom Roles as AAD Premium is required (don't have too many users to justify that). Need a better solution. Owner permission is too invasive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a37b92a-145e-92f0-a55f-471927a3a0d6
* Version Independent ID: fd19801e-fb46-7ef4-1e38-b27c749824b6
* Content: [Connect Azure Stack HCI to Azure - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/register-with-azure#azure-subscription-and-permissions)
* Content Source: [azure-stack/hci/deploy/register-with-azure.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/deploy/register-with-azure.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by himanshusinha-msft** [comment]
Thanks for reaching out to us , but at this time it does not look like you are referring to a document but to a specific scenario . If that's the case we request you to please post your question on Microsoft Q&A  and other forums , we have our engineers and others who are monitoring them and will be happy to help .
If you have a document which you are following and if you think it needs  an update , please let us know about that here .

**Comment by fabianotex** [comment]
The documentation doesn't seems to be correct. Documentation states that I can use Built-in "Owner" OR "User Access Administrator". User Access Administrator does not have the proper permissions required to register AsHCI Cluster.

**Comment by himanshusinha-msft** [comment]
Thank @fabianotex  . Can you share the document which you are fering so that we can go ahead and review the same .

**Comment by SatishBoddu-MSFT** [comment]
Adding the reference document link.
[Azure subscription and permissions](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/register-with-azure#azure-subscription-and-permissions)

![image](https://user-images.githubusercontent.com/62923178/124520418-4c080800-dda1-11eb-9ce8-61160bdcafa8.png)

Cc: @khdownie

**Comment by khdownie** [comment]
Contributor role is still required along with user access administrator. Adjusting the docs to make this clear. Thank you for bringing this to our attention.
