### ISSUE TITLE
Incorrect schema

### ISSUE THREAD

**Issue by jbpaux** [MicrosoftDocs/azure-stack-docs#1542]
Hello, the schema https://docs.microsoft.com/en-us/azure-stack/operator/media/azure-stack-integrate-dns/integrate-dns-01.svg?view=azs-2102 is incorrect :

* Name servers are azs-ns01/ns02 and not azs-Dns01/Dns02 (the D should be removed)
* forwarded zone should be the same as in the text (east.cloud.fabrikam.com and not sea.azurestack.external)
* another zone should be included in the ns01/ns02 servers : east.cloudapp.cloud.fabrikam.com)

Please update it to match the rest of the doc. (same as #20 but nothing was fixed...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0403da-4784-000f-2c14-50257ae7c37f
* Version Independent ID: 2b4f5bc1-66f6-4c7f-c06e-bc32f2acd383
* Content: [Azure Stack Hub datacenter DNS integration - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-dns?view=azs-2102)
* Content Source: [azure-stack/operator/azure-stack-integrate-dns.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-dns.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by PatAltimore** [comment]
Hi @jbpaux,

Sorry I didn't get all your feedback in the first time. I published a new update. Would you like to confirm the changes include all your feedback?

Thanks,
Pat

**Comment by PatAltimore** [comment]
#in-progress

**Comment by PatAltimore** [comment]
Hi @jbpaux,

You can review the change when you have time. I published an update to the article. I'm going to close this issue as resolved. Let us know if you have additional feedback.

Thanks,
Pat

#please-close

**Comment by jbpaux** [comment]
Thanks @PatAltimore sounds good now ! Well done.
In the center part under "conditional forwarding", I have doubts. It may be both zones, not just the cloudapp one.
