### ISSUE TITLE
"Connect with SSH by using PuTTY" - incorrect description

### ISSUE THREAD

**Issue by Langenbuch** [MicrosoftDocs/azure-stack-docs#1546]
[Enter feedback here]
The description for "Connect with SSH by using PuTTY" is somehow mixing public and private keys. Public SSH key is mentioned as prerequisite, but path to private key is requested. Following the description is leading to an error message, that publickey authentication is missing.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ae6dca-f225-c076-4b79-3ee5f76f530f
* Version Independent ID: 25d0c989-e093-d2bc-c152-6d73bb44dc13
* Content: [How to use an SSH public key with Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-dev-start-howto-ssh-public-key?view=azs-2102)
* Content Source: [azure-stack/user/azure-stack-dev-start-howto-ssh-public-key.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-dev-start-howto-ssh-public-key.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by mattbriggs** [comment]
@Langenbuch Thanks for your feedback. I'll update. Thanks! 

#in-progress

**Comment by mattbriggs** [comment]
@Langenbuch Sorry about the confusion in the titling and the intros in this topic. I updated those, so hopefully it won't be so confusing. Thank you for your feedback and taking the time to point this out.

#please-close

**Comment by TravisCragg-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
