### ISSUE TITLE
Add Upgrade VM version to this article.

### ISSUE THREAD

**Issue by Mihaly7** [MicrosoftDocs/azure-stack-docs#1550]
After migration, it would worth to note to upgrade the Virtual Machine's version. In case when customer moves from older Hyper-V servers, they could miss useful features. Also, if they migrate from different Hyper-V servers they could have different vm versions on a single environment.

Reference article.:
https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/deploy/upgrade-virtual-machine-version-in-hyper-v-on-windows-or-windows-server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cbd36e1-4f1c-c009-8f06-bd5ec979f07a
* Version Independent ID: eb14e0ca-c74b-b0bc-e00a-581c88535295
* Content: [Migrate to Azure Stack HCI on new hardware - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/migrate-cluster-new-hardware#run-the-migration-script)
* Content Source: [azure-stack/hci/deploy/migrate-cluster-new-hardware.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/deploy/migrate-cluster-new-hardware.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @v-dasis
* Microsoft Alias: **v-dasis**

**Comment by psmanhas** [comment]
@Mihaly7 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.We will update you accordingly.

**Comment by psmanhas** [comment]
@v-dasis Can you please check and add your comments on this doc update request as applicable

**Comment by v-dasis** [comment]
This is already stated (in both Azure Stack HCI migration articles):

Update your VMs to the latest version for Azure Stack HCI to take advantage of all the advancements:

Get-VM | Update-VMVersion -Force

**Comment by shashishailaj** [comment]
as per the details form the team , you can update
