### ISSUE TITLE
Install-AksHci

### ISSUE THREAD

**Issue by ChaiSwaddipong** [MicrosoftDocs/azure-stack-docs#1553]
Do I run this on all physical hosts? Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e3139e-399b-be0f-d80e-d78b094b214a
* Version Independent ID: f18262fc-0401-68d0-964a-ee4e19be10e0
* Content: [Quickstart to set up an Azure Kubernetes Service host and create AKS on Azure Stack HCI clusters using Windows PowerShell - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/kubernetes-walkthrough-powershell)
* Content Source: [azure-stack/aks-hci/kubernetes-walkthrough-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/kubernetes-walkthrough-powershell.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @jessicaguan
* Microsoft Alias: **jeguan**

**Comment by MonikaReddy-MSFT** [comment]
@ChaiSwaddipong  - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can update the document accordingly.

**Comment by mattbriggs** [comment]
Updated.

#please-close
