### ISSUE TITLE
PowerShell instructions are not clear

### ISSUE THREAD

**Issue by fabianotex** [MicrosoftDocs/azure-stack-docs#1555]
[Enter feedback here]

Instructions are not clear. In the cmdlets below, there is no reference from where the variable **$vm** is coming from. I would imagine that the first one is from "Get-ClusterResource -Name "Virtual Machine xyz"? The next cmdlet cannot be piped, so should I use "Add-VMAssignableDevice -ResourcePoolName GPU_Pool -VMName xyz?

$vm | Set-ClusterParameter -Name "OfflineAction" -Value 3
$vm | Add-VMAssignableDevice -ResourcePoolName "GpuChildPool"

I was able to assign the GPU from a Pool to a VM and install the GPU drivers, however VM wont move to remaining node if I Pause node it is running on.

Error:
Move of cluster role 'xyz' for drain could not be completed.  The operation failed with error code 0x32.

Please provide instructions so it can be retried.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08dae85-343a-8053-316f-fa321a0c46dc
* Version Independent ID: e91c7aa1-e79b-752b-f9ae-7f29d9629ae2
* Content: [Use GPUs with clustered VMs - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/use-gpu-with-clustered-vm)
* Content Source: [azure-stack/hci/manage/use-gpu-with-clustered-vm.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/use-gpu-with-clustered-vm.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @rick-man
* Microsoft Alias: **rickman**

**Comment by fabianotex** [comment]
I decided to manually stop the VM and then I performed a Quick Migration in order to move VM pointer to the other node, since Drain/Pause node failed. VM started just fine on the other node and GPU was present.

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by sethmanheim** [comment]
Sounds like the issue was resolved.
