### ISSUE TITLE
OS Disk Swap

### ISSUE THREAD

**Issue by jamesorlando** [MicrosoftDocs/azure-stack-docs#1562]
I learned through internal channels that OS Disk Swap is not supported in ASH. Can we get that noted on this page? 

Thanks. 

James

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa744c44-a2a6-725e-e29a-62e89d0b0529
* Version Independent ID: 4e31c4b6-1685-2248-13ac-9776720cf73b
* Content: [Azure Stack Hub VM features - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vm-considerations?view=azs-2102&tabs=az1%2Caz2)
* Content Source: [azure-stack/user/azure-stack-vm-considerations.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-vm-considerations.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@jamesorlando Thanks for this note. I'll follow up and get this noted.

#in-progress

**Comment by mattbriggs** [comment]
@jamesorlando I've updated as unsupported. Thanks again for your note. The update should appear in the next doc build.

#please-close
