### ISSUE TITLE
monitor link anchor missing/wrong

### ISSUE THREAD

**Issue by nimeader** [MicrosoftDocs/azure-stack-docs#1578]
"It's important to **(monitor)[https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-manage-storage-shares?view=azs-2002#monitor-shares]** the available storage..."

link should likely anchor to #monitor-volumes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03c63388-ff19-a72e-959b-883a01b400e8
* Version Independent ID: bba686d4-1463-c9a1-bdb4-7d3edf095fee
* Content: [Manage storage capacity in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-manage-storage-shares?view=azs-2002#migrate-a-managed-disk-between-volumes)
* Content Source: [azure-stack/operator/azure-stack-manage-storage-shares.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-manage-storage-shares.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by DerekHerman-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@nimeader Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by PatAltimore** [comment]
Hi @nimeader, 

Thanks for letting us know. The issue was due to a recent change supporting multiple versions. I standardized the header / bookmark to "Monitor storage". The fix will go live tomorrow.

Thanks,
Pat
#please-close
