### ISSUE TITLE
Errors installing AksHCI 

### ISSUE THREAD

**Issue by cenkersoy** [MicrosoftDocs/azure-stack-docs#1581]
Hi,

When installing AksHCI module, I get the following warnings:

WARNING: The specified module 'DownloadSdk' with PowerShellGetFormatVersion '2.0' is not supported by the current version of PowerShellGet. Get the latest versi
on of the PowerShellGet module to install this module, 'DownloadSdk'.
WARNING: The specified module 'Kva' with PowerShellGetFormatVersion '2.0' is not supported by the current version of PowerShellGet. Get the latest version of th
e PowerShellGet module to install this module, 'Kva'.
WARNING: The specified module 'Moc' with PowerShellGetFormatVersion '2.0' is not supported by the current version of PowerShellGet. Get the latest version of th
e PowerShellGet module to install this module, 'Moc'.
WARNING: The specified module 'AksHci' with PowerShellGetFormatVersion '2.0' is not supported by the current version of PowerShellGet. Get the latest version of
 the PowerShellGet module to install this module, 'AksHci'.

Then the import-module akshci fails.

Thanks
Cenk Ersoy 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37e3139e-399b-be0f-d80e-d78b094b214a
* Version Independent ID: f18262fc-0401-68d0-964a-ee4e19be10e0
* Content: [Quickstart to set up an Azure Kubernetes Service host and create AKS on Azure Stack HCI clusters using Windows PowerShell - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/kubernetes-walkthrough-powershell)
* Content Source: [azure-stack/aks-hci/kubernetes-walkthrough-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/kubernetes-walkthrough-powershell.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @jessicaguan
* Microsoft Alias: **jeguan**

**Comment by DerekHerman-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by abhilashaagarwala** [comment]
@cenkersoy  - Are you still facing this issue? If not, can we close it?

**Comment by abhilashaagarwala** [comment]
#please-close
