### ISSUE TITLE
Trial period is not 30 days for AZHCI but 60.

### ISSUE THREAD

**Issue by Mihaly7** [MicrosoftDocs/azure-stack-docs#1582]
30-day free trial once registered - Should be 60

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1b5681-bec1-c4d2-bb1a-9c1e2533d710
* Version Independent ID: 818c8ae2-b58a-ed92-799d-1bec94407187
* Content: [Compare Azure Stack HCI to Windows Server - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/compare-windows-server)
* Content Source: [azure-stack/hci/concepts/compare-windows-server.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/concepts/compare-windows-server.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by MonikaReddy-MSFT** [comment]
Thanks for brining this to our attention. We will investigate it further and update you shortly.

**Comment by MonikaReddy-MSFT** [comment]
@Mihaly7 - Thanks again for bringing this to our attention. We have updated the Doc and it will be live once its merged.  We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by Mihaly7** [comment]
Thank you for the quick response!
