### ISSUE TITLE
Hub operations on sql/mysql providers fail if newer Az modules are installed.

### ISSUE THREAD

**Issue by pameruoso** [MicrosoftDocs/azure-stack-docs#1588]
This page should mention that no other "Az" or Azs modules shoul be installed on the machine where running the SQL/Mysql provider scripts.

If these modules are present, most "operation" tasks will randomly fail like the simple authentication to the admin management portal. 

This is due to the module transition from AzureRM to Az.

Here is an example while trying to rotate the sqlrp certificate

**********************
Windows PowerShell transcript start
Start time: 20210730100447

Host Application: C:\Windows\system32\WindowsPowerShell\v1.0\PowerShell_ISE.exe
Process ID: 5940
PSVersion: 5.1.14393.4530
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14393.4530
BuildVersion: 10.0.14393.4530
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************

WARNING: The names of some imported commands from the module 'Common' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
VERBOSE: 10:04:47 AM :
VERBOSE: 10:04:47 AM : *********************************************************
VERBOSE: 10:04:47 AM : *Executing Script SecretRotationSQLProvider.ps1 1.1.93.1*
VERBOSE: 10:04:47 AM : *********************************************************
VERBOSE: PSBoundParameter are:
VERBOSE: {
    "PrivilegedEndpoint":  "",
    "CloudAdminCredential":  {
                                 "UserName":  "",
                                 "Password":  {
                                                  "Length":  
                                              }
                             }
}
VERBOSE: 10:04:47 AM :
VERBOSE: 10:04:47 AM : ************************************************
VERBOSE: 10:04:47 AM : *Checking for Azure Stack Powershell Module ...*
VERBOSE: 10:04:47 AM : ************************************************
Nuget Package provider found.
Loading azure powershell modules from location C:\Program Files\SqlMySqlPsh
Azure powershell version 2.5.0 found at C:\Program Files\SqlMySqlPsh
Loading azure powershell modules from location C:\Program Files\SqlMySqlPsh
VERBOSE: 10:04:47 AM :
VERBOSE: 10:04:47 AM : ***************************
VERBOSE: 10:04:47 AM : *Validating the parameters*
VERBOSE: 10:04:47 AM : ***************************
VERBOSE: Current trusted root: *
VERBOSE: Performing the operation "Remove" on target "".
VERBOSE: Current trusted root: *
VERBOSE: Performing the operation "Remove" on target "".
VERBOSE: AzureStack Stamp Version: 1.2102.28.89
VERBOSE: Endpoints: {
    "galleryEndpoint":  "https://adminproviders.azurestack",
    "graphEndpoint":  "https://graph.windows.net/",
    "portalEndpoint":  "https://adminportal.",
    "authentication":  {
                           "loginEndpoint":  "https://login.microsoftonline.com/",
                           "audiences":  [
                                             "https://adminmanagement
                                         ]
                       }
}
PS>TerminatingError(Get-AzureRmContext): "Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation."
VERBOSE: Initializing a new AzureRm context
PS>TerminatingError(Disconnect-AzureRmAccount): "Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation."
>> TerminatingError(Disconnect-AzureRmAccount): "Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation."
>> TerminatingError(Disconnect-AzureRmAccount): "Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation."
VERBOSE: Cannot login with account: XXXXXXXXXXXXXX. Using https://adminmanagement.XXXXXXX Admin URL and XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX DirectoryTenantID
VERBOSE: Errors are Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Failed to verify account, please enter correct Service Admin Account credential
VERBOSE: Endpoints: {
    "galleryEndpoint":  "https://adminproviders.
    "graphEndpoint":  "https://graph.windows.net/",
    "portalEndpoint":  "https://adminportal.
    "authentication":  {
                           "loginEndpoint":  "https://login.microsoftonline.com/",
                           "audiences":  [
                                             "https://adminmanagement
                                         ]
                       }
}
PS>TerminatingError(Get-AzureRmContext): "Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation."
VERBOSE: Initializing a new AzureRm context
PS>TerminatingError(Disconnect-AzureRmAccount): "Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation."
>> TerminatingError(Disconnect-AzureRmAccount): "Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation."
>> TerminatingError(Disconnect-AzureRmAccount): "Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation."
VERBOSE: Cannot login with account: XXXXXXXXXXXXXXXXXXXXXXXXX Using https://adminmanagement.XXXXXXXXXXXXXXXXXXXXXXXX Admin URL and XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX DirectoryTenantID
VERBOSE: Errors are Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Failed to verify account, please enter correct Service Admin Account credential
PS>TerminatingError(Test-AzurestackAdminCredential): "Cannot bind argument to parameter 'azCredential' because it is null."
Error: Cannot bind argument to parameter 'azCredential' because it is null.
VERBOSE: 10:11:38 AM :
VERBOSE: 10:11:38 AM : *********************************************************************************************************************************************************************
VERBOSE: 10:11:38 AM : *Microsoft.SQLAdapter provider Secret Rotation failed. Check log file C:\XXXXXXXXXXXXXXXXXXXXXXXXSecretRotationSQLProvider.ps1_20210730-100447.txt for details*
VERBOSE: 10:11:38 AM : *********************************************************************************************************************************************************************
**********************
Windows PowerShell transcript end
End time: 20210730101138
**********************

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 062392be-64fa-7151-9db9-f346aac5f491
* Version Independent ID: ae463fff-d809-ca27-8dd3-45904ef1aba5
* Content: [SQL resource provider maintenance operations - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-maintain?view=azs-2102#secrets-rotation)
* Content Source: [azure-stack/operator/azure-stack-sql-resource-provider-maintain.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-sql-resource-provider-maintain.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by psmanhas** [comment]
@BryanLa Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate. We will update you accordingly.

**Comment by psmanhas** [comment]
@BryanLa Can you please check and add your comments on this doc update request as applicable

**Comment by BryanLa** [comment]
@pameruoso - thanks very much for your feedback. The doc has been updated.

#please-close this issue

cc: @AKEMXP
