### ISSUE TITLE
Fix references to "update", change them to "upgrade" in the VM Re-sizing item from aks-engine 

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1592]
There is a typo in the item for how to re-size VMs in the cluster, it says to use aks-engine update, it should say, aks-engine upgrade. We do not support aks-engine update, we should not instruct customers to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bddc138b-1b2e-4be5-d38b-91818ccf1922
* Version Independent ID: fb4f2341-8ca1-f849-05f5-5b4ce22b9462
* Content: [Known issues with the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues?view=azs-2102#unable-to-resize-cluster-vms-with-the-compute-service)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by mattbriggs** [comment]
@walterov Thanks #in-progress

**Comment by mattbriggs** [comment]
Signed off on Javier's PR.

#please-close
