### ISSUE TITLE
Need to remove "aks-engine get-versions command limitations" item since it is no longer an issue

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1597]
Please remove this bullet item, it is no longer an issue

aks-engine get-versions command limitations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bddc138b-1b2e-4be5-d38b-91818ccf1922
* Version Independent ID: fb4f2341-8ca1-f849-05f5-5b4ce22b9462
* Content: [Known issues with the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues?view=azs-2102)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks!

#in-progress

**Comment by mattbriggs** [comment]
Change made.

#please-close
