### ISSUE TITLE
AKS on HCI with SDN ?

### ISSUE THREAD

**Issue by ariesow** [MicrosoftDocs/azure-stack-docs#1599]
[Enter feedback here]
Can AKS work in conjunction with the use of SDN on HCI ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6db0c266-9042-4171-77fe-666d43eeba15
* Version Independent ID: fbce33cb-7178-5933-e35d-1f5b40af00f5
* Content: [Software defined networking (SDN) in Azure Stack HCI and Windows Server - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/software-defined-networking)
* Content Source: [azure-stack/hci/concepts/software-defined-networking.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/concepts/software-defined-networking.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the question. We are currently investigating and will update you shortly.

**Comment by khdownie** [comment]
@Karishma-Tiwari-MSFT @ariesow I've confirmed that SDN is not currently supported in AKS HCI - so this issue can be closed.

**Comment by TravisCragg-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by ariesow** [comment]
Hi @TravisCragg-MSFT and @khdownie, Thanks for the prompt response, by an chance this is in roadmap for cloud provider scenario which require multi-tenancy ?

**Comment by khdownie** [comment]
We can't make any definitive comments about the future, @ariesow - but SDN will likely be supported at some point.
