### ISSUE TITLE
deployment of template fail if you add tags

### ISSUE THREAD

**Issue by prjelesi** [MicrosoftDocs/azure-stack-docs#1602]
Hi, 

It should be noted that deployment of HA filesharing and SQL fail if you add tags.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Prerequisites to deploy Azure App Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started?view=azs-2102)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by apwestgarth** [comment]
Hi @prjelesi if you are experiencing and issue with the Quickstart template(s), please raise an issue in the [Azure Stack Hub Quickstart Samples Repository](https://github.com/Azure/AzureStack-QuickStart-Templates/issues)

Adding tags to a deployment or resource should not cause the template to fail.  Please share details of Azure Stack Hub version and detail error messages when creating the issue in the template repository.
