### ISSUE TITLE
issue with 'Start-SecretRotation' script

### ISSUE THREAD

**Issue by Donnie-Zhang** [MicrosoftDocs/azure-stack-docs#1608]
[Enter feedback here]
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-2102#rotation
We have seen a few cases that the customers failed to pass the parameters to Start-SecretRotation, which can be mitigated by adding '-ArgumentList' by the end of the script as below.

Invoke-Command -Session $PEPsession -ScriptBlock {
    param($certSharePath, $certPassword, $certShareCreds )
     Start-SecretRotation -PfxFilesPath $certSharePath -PathAccessCredential $certShareCreds -CertificatePassword $certPassword
} -ArgumentList ($certSharePath, $certPassword, $certShareCreds)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4feaa2a-4850-478d-8122-7eb751ba0777
* Version Independent ID: f5cd7372-0443-3f2e-c403-ed7ba1a56146
* Content: [Rotate secrets - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-2102)
* Content Source: [azure-stack/operator/azure-stack-rotate-secrets.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-rotate-secrets.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by kobulloc-MSFT** [comment]
@Donnie-Zhang Thank you for bringing this to our attention!  I've assigned this to the document author for review.

**Comment by BryanLa** [comment]
Article changes have been completed.

#please-close
