### ISSUE TITLE
It is a bit unclear what "registering your ASDK installation with Azure" refers to

### ISSUE THREAD

**Issue by bjoernf73** [MicrosoftDocs/azure-stack-docs#1622]
The sentence "If you've previously registered your ASDK installation with Azure, you should remove the registration resource before redeploying the ASDK" is somewhat unclear. 

Have I? 

My ASDK re-installation just failed at step 60.190.197: 

"Invoke-EceAction : Type 'Configure' of Role 'Gallery' raised an exception: ERROR during Directory Tenant Registration: A task was canceled." 

I certainly didn't cancel anything, but that's a different story. And I never did a manual registration of my ASDK in Azure. If I didn't, is it registered? There certainly are references to Azure Stack in the portal when I log in - but that must be something the installer did - I didn't. 

So - have I registered my ASDK installation with Azure? How would I know if I have? 

The point is: The registration that this is referring to, is that something that the asdk-installer.ps1 (or any subscript that the script calls) will do? Or is it a registration that you will *have to perform manually after the ASDK is successfully installed*? 

The following simple sentence would clear it all up: *"If you have not performed the manual registration outlined in the next step, you have not registered your ASDK with Azure, and you may skip this step"* or similar. 

On the other hand, if that is a lie, it would really make a mess of things ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3bed670-b412-74b4-f2ea-48023250a718
* Version Independent ID: 109c728d-522d-71d1-04cf-146624e5e4e2
* Content: [Redeploy the ASDK - Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-redeploy?view=azs-2102&tabs=az)
* Content Source: [azure-stack/asdk/asdk-redeploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-redeploy.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub-asdk**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by shashishailaj** [comment]
@bjoernf73  Thank you for pointing this out . We will investigate and update the thread.

**Comment by PatAltimore** [comment]
#reassign @sethmanheim

**Comment by sethmanheim** [comment]
Please contact Microsoft Support for ASDK issues, as we cannot verify the information currently.
