### ISSUE TITLE
Documentation needs slight correction

### ISSUE THREAD

**Issue by maheoasic** [MicrosoftDocs/azure-stack-docs#1624]
[Enter feedback here]
2nd block is not azure cmd but output of prev cmd, that show LoadBalancer details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fff7a8c5-0a30-db37-e348-d7726d6428e7
* Version Independent ID: 6ed253a0-d251-565f-feb7-72a73c1afbe8
* Content: [Install existing applications with Helm on Azure Kubernetes Service on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/kubernetes-helm)
* Content Source: [azure-stack/aks-hci/kubernetes-helm.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/kubernetes-helm.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattmcspirit
* Microsoft Alias: **mmcspirt**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for bringing this to our attention. This has been updated in the document. 
We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
