### ISSUE TITLE
Replace "down" for "download"

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1629]
Replace "down" for "download" in the sentence starting with: "For other Linux machines, down "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28bc38be-d135-cf83-9b01-b6a050d71baf
* Version Independent ID: 6178cf90-b745-b187-9cc1-6439893857ec
* Content: [Using Azure Kubernetes Service on Azure Stack Hub with the CLI - Azure Stack Hub](https://review.docs.microsoft.com/en-us/azure-stack/user/aks-how-to-use-cli?view=azs-2107&branch=release-2108&tabs=windows%2Clinuxcon)
* Content Source: [azure-stack/user/aks-how-to-use-cli.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/aks-how-to-use-cli.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by kobulloc-MSFT** [comment]
@walterov Thank you for bringing this to our attention!  I'll get a PR out to fix this.

**Comment by mattbriggs** [comment]
updated. https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/8241

#please-close
