### ISSUE TITLE
tls settings required for PowerShellGet

### ISSUE THREAD

**Issue by nimeader** [MicrosoftDocs/azure-stack-docs#1634]
TLS settings:

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

are required for installing PowerShellGet (step 1.prerequisites.3, and step 4.1), but isn't mentioned until after the step (step 4.3). This should be in one of the prerequisites.

-Nick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c7ec8b-634f-6b95-7ce1-c38d55b12c23
* Version Independent ID: 8cc3a38e-0bbc-71b4-2c37-fc6231bb540d
* Content: [Install PowerShell Az module for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2102)
* Content Source: [azure-stack/operator/powershell-install-az-module.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/powershell-install-az-module.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@nimeader Thanks for your note. I'll update shortly. Thanks!

#in-progress

**Comment by mattbriggs** [comment]
updated.

#please-close
