### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by clementmoulin** [MicrosoftDocs/azure-stack-docs#1641]
"It's recommended that all servers be the same manufacturer and model"

But when trying to setup a cluster with 2 servers from different manufacturers, you get the following error:

"The provided servers are not the same manufacturer model, which is required to continue".

BTW, this requirement is really disappointing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eeb152f-1c40-2222-c2d4-199371710080
* Version Independent ID: 09741470-9f27-a683-d042-12b22f3e4105
* Content: [System requirements for Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/system-requirements)
* Content Source: [azure-stack/hci/concepts/system-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/concepts/system-requirements.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for bringing this to our attention. I have created a PR with the update, changes will be live shortly.
We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
