### ISSUE TITLE
service account not showing up in portal

### ISSUE THREAD

**Issue by drloring** [MicrosoftDocs/azure-stack-docs#1648]
I"m following the instructions to setup a service account with a secret.  But when I attempt to add the new account the Read role to my subscription, I can't find the user.  This is on an offline ASDK installation with ADFS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193ec77a-b7dc-7807-cb42-fb1c8ad4a3c7
* Version Independent ID: 389dc440-613b-88ad-c1e9-e4b6fe6db8c6
* Content: [Give an app access to Azure Stack Hub resources - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/give-app-access-to-resources?view=azs-2102&tabs=az1%2Caz2&pivots=state-disconnected#manage-an-azure-ad-app)
* Content Source: [azure-stack/operator/give-app-access-to-resources.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/give-app-access-to-resources.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
@drloring - I'm assuming where you said "user", you meant the name of the Application you registered (the service account)? If so, make sure you search for the application name using the syntax mentioned in the article (see step 6 under [assign a role](https://docs.microsoft.com/azure-stack/operator/give-app-access-to-resources?view=azs-2102&tabs=az1%2Caz2&pivots=state-disconnected#assign-a-role)). 

If this still doesn't work, I'm not sure what the problem would be. You might want to open a support request in the admin portal. See [Help and support](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-help-and-support-overview?view=azs-2102) for more details. 

Hope this helps.

**Comment by VikasPullagura-MSFT** [comment]
@BryanLa Thanks for sharing the details.

@drloring Hope the provided information is helpful.

**Comment by VikasPullagura-MSFT** [comment]
@drloring 
Hope the provided information is helpful.

We will now close this issue. If there are further questions regarding this, please tag me in a comment. I will reopen it and we will continue the discussion.
