### ISSUE TITLE
Fix this sentence: "Is the service principal is not automatically created?"

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1654]
Fix this sentence: "Is the service principal is not automatically created?". Change to "Is the service principal automatically created?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa2fa482-ee43-99ca-38bf-cdfc180efdb3
* Version Independent ID: 159e5062-cb29-8f90-6b2e-1240791b2f76
* Content: [Known issues for the Azure Kubernetes Service on Azure Stack Hub - Azure Stack Hub](https://review.docs.microsoft.com/en-us/azure-stack/user/aks-known-issues?view=azs-2107&branch=release-2108)
* Content Source: [azure-stack/user/aks-known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/aks-known-issues.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for bringing this to our attention. I have created a PR with the update, changes will be live shortly.

Thanks for improving our documentation! Just so you know, it's also possible to make these changes yourself, if you are interested. Doing so will improve our documentation, and it will add you as a contributor to the document.
In case you're interested, these are the steps to do so:
1.	Navigate to the page of interest
2.	Select the "Edit" button at the top right of the page
3.	Select the "Pencil" icon on the right
4.	Modify the text within the text box in markdown format - more info: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
5.	Name your file change and provide a description, if necessary
6.	Select "Propose file change"
7.	Select "Create pull request" on the 'Comparing changes' page
8.	Select "Create pull request" on the 'Open a pull request' page
You can find a GIF that demonstrates the end-to-end process for submitting changes here: https://aka.ms/editsqldocs.
