### ISSUE TITLE
Clarification on Azure Stackhub Marketplace

### ISSUE THREAD

**Issue by santhoshbomma9** [MicrosoftDocs/azure-stack-docs#1658]
Is Stackhub Marketplace like a private marketplace for that stackhub users? This is not like Azure Marketplace right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f55b7c67-95b1-2a78-7918-200a97c8899a
* Version Independent ID: 25fa28e8-8a70-a525-7640-8b615c2b99d7
* Content: [Azure Stack Hub Marketplace overview - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-marketplace?view=azs-2102)
* Content Source: [azure-stack/operator/azure-stack-marketplace.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-marketplace.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
Closing as was discussed offline. #please-close
