### ISSUE TITLE
Change Ubuntu CLI installation instruction

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1661]
Remove this part:

"For an Ubuntu machine, run the following commands to install the build of the Azure CLI with AKS support.

Bash

Copy
curl -o azure-cli_xenial_all.deb https://aka.ms/ash-aks-cli-linux

sudo apt install ./azure-cli_xenial_all.deb"

Replace it with:

"For an Ubuntu machine, follow the instructions here https://aka.ms/ash-aks-cli-linux" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28bc38be-d135-cf83-9b01-b6a050d71baf
* Version Independent ID: 6178cf90-b745-b187-9cc1-6439893857ec
* Content: [Using Azure Kubernetes Service on Azure Stack Hub with the CLI - Azure Stack Hub](https://review.docs.microsoft.com/en-us/azure-stack/user/aks-how-to-use-cli?view=azs-2107&branch=release-2108&tabs=linux%2Clinuxcon)
* Content Source: [azure-stack/user/aks-how-to-use-cli.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/aks-how-to-use-cli.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
Updated.

#please-close

**Comment by walterov** [comment]
The link in the article is not using the aka link I placed in the issue above.

**Comment by mattbriggs** [comment]
Yes ... the link doesn't work. I wish they would fix it. The link however will work when it is published. You check by removing the 'review' in the URL...
