### ISSUE TITLE
Change the "az --version" screenshots for the following...

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1662]
In section: https://review.docs.microsoft.com/en-us/azure-stack/user/aks-how-to-use-cli?view=azs-2107&branch=release-2108&tabs=ubuntu%2Clinuxcon#install-azure-cli

For Ubuntu:
Mention that Azure CLI version should be 2.28.0 or above
![image](https://user-images.githubusercontent.com/1017810/135186516-a182ebd2-7ca2-45cc-bbba-500cc055e461.png)

For Windows:
Mention that Azure CLI version should be 2.28.0 or above
![image](https://user-images.githubusercontent.com/1017810/135186556-56f23caf-101b-43e9-9c6a-a2121ee3a5d1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28bc38be-d135-cf83-9b01-b6a050d71baf
* Version Independent ID: 6178cf90-b745-b187-9cc1-6439893857ec
* Content: [Using Azure Kubernetes Service on Azure Stack Hub with the CLI - Azure Stack Hub](https://review.docs.microsoft.com/en-us/azure-stack/user/aks-how-to-use-cli?view=azs-2107&branch=release-2108&tabs=ubuntu%2Clinuxcon)
* Content Source: [azure-stack/user/aks-how-to-use-cli.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/aks-how-to-use-cli.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by VikasPullagura-MSFT** [comment]
@walterov 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@mattbriggs 
Can you please check and add your comments on this doc update request as applicable.

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
Updated. Will merge to the release branch for review.

#sign-off

**Comment by mattbriggs** [comment]
#please-close
