### ISSUE TITLE
Template validation tool doc references Az modules in AzureRM code stamples

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1664]
The AzureRM code samples reference the Az modules "Import-Module .\Az.BLAH" instead of the AzureRM modules, in these two sections:

https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-validate-templates?view=azs-2102&tabs=azurerm1%2Cazurerm2%2Caz3#build-the-cloud-capabilities-file

Should be:
> Import-Module ".\CloudCapabilities\AzureRM.CloudCapabilities.psm1"

https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-validate-templates?view=azs-2102&tabs=azurerm1%2Cazurerm2%2Caz3#validate-templates

Should be:
> Import-Module ".\TemplateValidator\AzureRM.TemplateValidator.psm1"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db0d3cb0-ca45-567a-3404-a88d86acfa02
* Version Independent ID: b4bc0117-bedd-6da1-d5be-32c04205d0d2
* Content: [Use the template validation tool in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-validate-templates?view=azs-2102&tabs=azurerm1%2Cazurerm2%2Caz3#validate-templates)
* Content Source: [azure-stack/user/azure-stack-validate-templates.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-validate-templates.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@alexsmithMSFT Thank you for catching that, I will fix. #please-close

**Comment by alexsmithMSFT** [comment]
@sethmanheim the code snippits look good, but the text of the steps still gives the Az module names:

> 2. Import the Az.CloudCapabilities PowerShell module:

> 1. Import the Az.TemplateValidator.psm1 PowerShell module:

And the second instance still mentions the Az subdirectory: AzureStack-Tools-az

**Comment by sethmanheim** [comment]
@alexsmithMSFT OK, I will fix. This issue initially only mentioned the code samples.

**Comment by alexsmithMSFT** [comment]
@sethmanheim you're right, I should have said steps and code-samples originally, but I didn't notice at first.

**Comment by sethmanheim** [comment]
@alexsmithMSFT No worries, thanks for catching it, really appreciated. The fix is merged, will be live at 3 PM PT.
