### ISSUE TITLE
Rotation PowerShell code snippet uses double-quotes instead of single quotes

### ISSUE THREAD

**Issue by JohnBMSFT** [MicrosoftDocs/azure-stack-docs#1666]
Characters preceded by a dollar sign ($) in the password string are treated as a variable when used within double quotes and thus entire password is not considered when the string is passed to the command for processing. With the use of single quotes the string is passed to the command exactly as you type it.
![image](https://user-images.githubusercontent.com/91756038/135675828-ada54237-2b51-49e6-a519-f259ae3ee02d.png)

Source:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.1#double-quoted-strings

Tagging @alexsmithMSFT for visibility.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4feaa2a-4850-478d-8122-7eb751ba0777
* Version Independent ID: f5cd7372-0443-3f2e-c403-ed7ba1a56146
* Content: [Rotate secrets - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-2102)
* Content Source: [azure-stack/operator/azure-stack-rotate-secrets.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-rotate-secrets.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
@JohnBMSFT - thanks for your feedback. I've gone ahead and converted all instances of the strings passed to ConvertTo-SecureString, from double to single quotes.

#please-close
