### ISSUE TITLE
Add new section above "Download AKS Base Images" titled "Download Required VM Extensions"

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1669]
Add new section above "Download AKS Base Images" titled "Download Required VM Extensions"

Here is the document with the content: https://microsoft-my.sharepoint-df.com/:w:/p/waltero/EUnUiBaGfExCmQZZ87b9BzcBLgeFl-ZqBST9Eh0l28MqEg?e=dn1RvD 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5161bfe9-b400-e18f-0119-5d1c5a50abb4
* Version Independent ID: a3ddc8f7-bdb6-e6a7-097d-b0e405ee3e82
* Content: [Install and offer the Azure Kubernetes Service on Azure Stack Hub - Azure Stack Hub](https://review.docs.microsoft.com/en-us/azure-stack/operator/aks-add-on?view=azs-2108&branch=release-2108)
* Content Source: [azure-stack/operator/aks-add-on.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/aks-add-on.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
#please-close
