### ISSUE TITLE
Guest OS support?

### ISSUE THREAD

**Issue by pemsft** [MicrosoftDocs/azure-stack-docs#1670]
Thank you for excellent documentation!

Could you add question and answer for question: **Which Guest OS are supported on Azure Stack HCI?**

Perhaps the answer would be reference to related Hyper-V documentation:
https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-windows-guest-operating-systems-for-hyper-v-on-windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bce9bf06-c279-4009-0fae-65315f490cd8
* Version Independent ID: 89c42ecf-095b-758f-0e3d-fc4114cf48d2
* Content: [Azure Stack HCI FAQ](https://docs.microsoft.com/en-us/azure-stack/hci/faq)
* Content Source: [azure-stack/hci/faq.yml](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/faq.yml)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JohnCobb1
* Microsoft Alias: **v-johcob**

**Comment by SrijitBose-MSFT** [comment]
@pemsft , thank you for your feedback. We have shared the same with the content author(s). This should now be visible in their backlog.

**Comment by JohnCobb1** [comment]
Thanks for your feedback. The FAQ has been updated with it: https://docs.microsoft.com/en-us/azure-stack/hci/faq#which-guest-operating-systems-are-supported-on-azure-stack-hci

#sign-off

**Comment by shashishailaj** [comment]
As this has been updated we will be closing this.
