### ISSUE TITLE
AKS HCI calendar to match Kubernetes Release Cadence Change

### ISSUE THREAD

**Issue by ezYakaEagle442** [MicrosoftDocs/azure-stack-docs#1678]
Please update calendar based on last summer K8S communication : 
[https://kubernetes.io/blog/2021/07/20/new-kubernetes-release-cadence/?s=03](https://kubernetes.io/blog/2021/07/20/new-kubernetes-release-cadence/?s=03)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88bbe4b7-99f3-6aa3-0bd1-0bdf82be2da2
* Version Independent ID: ded686cb-6331-7de2-69a8-3d0283c21279
* Content: [Supported Kubernetes versions in Azure Kubernetes Service on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/supported-kubernetes-versions)
* Content Source: [azure-stack/aks-hci/supported-kubernetes-versions.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/supported-kubernetes-versions.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mkostersitz
* Microsoft Alias: **mikek**

**Comment by mattbriggs** [comment]
@zYakaEagle442 Thanks!

#in-progress

**Comment by mattbriggs** [comment]
Updated.

#please-close
