### ISSUE TITLE
Azure Firewall

### ISSUE THREAD

**Issue by tiny-dancer** [MicrosoftDocs/azure-stack-docs#168]
Accounting for Azure Firewall

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd5972fd-29f4-2643-56d4-98f845a132e6
* Version Independent ID: 900d8d64-db85-6db9-3a38-22d84d0c55df
* Content: [Azure Stack networking Differences and considerations](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-differences)
* Content Source: [azure-stack/user/azure-stack-network-differences.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-network-differences.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@tiny-dancer Thanks for the feedback! Azure firewall is not currently a part of Azure Stack. If you would like us to add it in the future, [please leave your feedback Here](https://feedback.azure.com/forums/344565-azure-stack). 

I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@tiny-dancer I've added a row that Azure Firewall is net yet supported in Azure Stack.

**Comment by mattbriggs** [comment]
#please-close
