### ISSUE TITLE
AKS engine image mapping for V0.60.1 lists 18.04-LTS twice, and not 16.04-LTS

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1684]
The table for **#aks-engine-and-corresponding-image-mapping** for version V0.60.1 lists AKS Base Ubuntu 18.04-LTS twice, but the sample Linux API model sample shows "distro": "aks-ubuntu-16.04"...

V0.60.1
AKS Base Ubuntu 18.04-LTS Image Distro, 2021 Q1 (2021.01.28), 
AKS Base Ubuntu 18.04-LTS Image Distro, 2021 Q1 (2021.01.28), 
AKS Base Windows Image (17763.1697.210129)	1.16.14, 1.16.15, 1.17.17, 1.18.15	Linux, Windows

Related to this commit from @mattbriggs 
https://github.com/MicrosoftDocs/azure-stack-docs/commit/95bb37c5fe1bf31102891adca73fa14b197b3247

If aks-engine V0.60.1 is still compatible with "aks-ubuntu-16.04" base image, please update the table

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2102#aks-engine-and-corresponding-image-mapping)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@alexsmithMSFT Thanks for pointing this out. I updated in this pull request after touching bases with Walter. https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/8563

Here is the AKS engine topic this is based on: https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#aks-engine-versions

**Comment by mattbriggs** [comment]
#please-close

**Comment by alexsmithMSFT** [comment]
Cool, thanks @mattbriggs !
