### ISSUE TITLE
Need formatting of FAQ

### ISSUE THREAD

**Issue by vmaruthi** [MicrosoftDocs/azure-stack-docs#169]
First 4 questions have formatting issues

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b6179e-9c7b-4c9e-6c26-c5edfc4bedae
* Version Independent ID: ada578d3-3b7f-dffc-a0f3-3e6938a8f75f
* Content: [Azure Stack capacity planning compute](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-capacity-planning-compute)
* Content Source: [azure-stack/operator/azure-stack-capacity-planning-compute.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-capacity-planning-compute.md)
* Service: **azure-stack**
* GitHub Login: @prchint
* Microsoft Alias: **justinha**

**Comment by TravisCragg-MSFT** [comment]
@vmaruthi Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by Justinha** [comment]
@vmaruthi @TravisCragg-MSFT Thanks for reporting this! It's fixed now.

**Comment by TravisCragg-MSFT** [comment]
@vmaruthi We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
