### ISSUE TITLE
script provided is erroneous

### ISSUE THREAD

**Issue by MMannheim** [MicrosoftDocs/azure-stack-docs#1692]
just wondering if anybody has tested the robocopy script before publishing?

running the script code in following order:
$Logfile     = "c:\temp\Robocopy1-$date.txt"
$date        = Get-Date -UFormat "%Y%m%d"
will evaluate the log file name with  empty date.

Further, don't understand why those variables are declared twice in the script:
$Dest_Server     = "Node01"
$TARGETDIR   = \\$Dest_Server\C$\Clusterstorage\Volume01 --> same as $dest???

Furthermore for me it is not understandable why no choice for VM live migration from existing systems into Azure Stack HCI is provided. That is a big step into the wrong direction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cbd36e1-4f1c-c009-8f06-bd5ec979f07a
* Version Independent ID: eb14e0ca-c74b-b0bc-e00a-581c88535295
* Content: [Migrate to Azure Stack HCI on new hardware - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/migrate-cluster-new-hardware#vm-version-support-and-update)
* Content Source: [azure-stack/hci/deploy/migrate-cluster-new-hardware.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/deploy/migrate-cluster-new-hardware.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @v-dasis
* Microsoft Alias: **v-dasis**

**Comment by sethmanheim** [comment]
@MMannheim Very sorry for the slow response here. If you still require assistance, please reach out. #please-close
