### ISSUE TITLE
2102 Known issue: Promoted images for new VMs are displayed in dropdown, even if they are not available in the local marketplace

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1695]
Consider adding an item for this under-
https://docs.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-2102#portal

In current 2102 builds, customers reported seeing OS images that were not downloaded in the marketplace when trying to create a VM from **All services -> Virtual Machines -> Create a Virtual machine**. 

We are able to reproduce this issue in our lab environments, and have reported the issue to the IaaS portal engineering team earlier this week. They understand the issue is causing these "promoted images" to display in the updated IaaS portal UI, even if they have not been downloaded from the Azure marketplace, and are already implementing a fix that is expected in the next major update, as well as a hotfix for 2102.

In the meantime, the "selected image is not available" warning should at least prevent failed VM deployments for missing OS images, and as a UI workaround, users can be directed to use Create a Resource -> Compute, which should only display images that are locally available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0094b74f-e85b-6983-5f58-ce24f825b63c
* Version Independent ID: a90feafe-0401-3da0-bb95-4dbc8868ea0f
* Content: [Azure Stack Hub known issues - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-2102)
* Content Source: [azure-stack/operator/known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/known-issues.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@alexsmithMSFT Please submit known issue items in the following format. For examples, see https://docs.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-2102. Thank you!

Applicable: 
Cause: 
Remediation: 
Occurrence:

**Comment by sethmanheim** [comment]
#please-close
