### ISSUE TITLE
The 21H2 build number is 20348.288 not 20348.11.

### ISSUE THREAD

**Issue by katyhuang72727** [MicrosoftDocs/azure-stack-docs#1696]
[Enter feedback here]

Hi ASHCI team,
The 21H2 build released on 10/19/2021 is 20348.288, not 20348.11.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22ce0662-cc07-34bc-1d9c-de7fd075bdee
* Version Independent ID: fc01822a-5d78-b4e0-eb1a-ccd8d9c7bdf0
* Content: [Azure Stack HCI release information - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/release-information)
* Content Source: [azure-stack/hci/release-information.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/release-information.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by SwathiDhanwada-MSFT** [comment]
@katyhuang72727 Thanks for your feedback.

Assigning to content author @khdownie   for review.
