### ISSUE TITLE
Network example references an illegal IP address

### ISSUE THREAD

**Issue by jberkers42** [MicrosoftDocs/azure-stack-docs#1704]
Hi There,

In the section of the page that describes the allocation of addresses in the 172.100.0.0/24 network, the address space is divided into different classes, also listing reserved addresses.  The table just before the **Kubenet address blocks example**, the last entry references the following IP Address:

* 172.100.0.256

This is an illegal address, and should actually be **172.100.0.255**.  The previous entry also then needs correcting to indicate **.254** as the last address.  As this would make the block 15 addresses, you would likely also need to reduce the starting IP of that block.

Additionally, using **172.100.0.0** as an example is ill-advised as this is a public routed internet address, not an RFC1918 address.  Anyone following this example may subsequently have issues communicating with the legitimate owner/operator of these addresses.  Not all consumers of these samples would be as astute as to realise this, subsequently leaving them with technical debt within their environment.

Please let me know if you have any further questions or comments.

Regards,
JohnB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc538db2-5b34-3668-1e8e-1914b4b18c43
* Version Independent ID: 4f4c7701-f73c-ca0b-f7e4-62652a7ae66b
* Content: [Deploy Kubernetes cluster to custom virtual network on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-custom-vnet?view=azs-2102)
* Content Source: [azure-stack/user/kubernetes-aks-engine-custom-vnet.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-custom-vnet.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
Catching up on this. This was updated in Feb. Thanks again.

#please-close
