### ISSUE TITLE
Install-Module -Name AzureRm.BootStrapper ???

### ISSUE THREAD

**Issue by lucidqdreams** [MicrosoftDocs/azure-stack-docs#171]
hasn't AzureRM bootstrapper been retired?  With the update schedule of 3  versions behind I believe I followed a guide that told me to delete all my AzureRM cmdlets and this SQL RP is still to be installed with AzureRM?

**Comment by MicahMcKittrick-MSFT** [comment]
@lucidqdreams thanks for reaching out and closing out the issue. If we can assist further just let us know.
