### ISSUE TITLE
two issues hit by following the document

### ISSUE THREAD

**Issue by Donnie-Zhang** [MicrosoftDocs/azure-stack-docs#1711]
[Enter feedback here]
Customer may hit two issues while running 'Connect-AzureRMAccount'
1. invalid provider type specified
This is due to the self-signed certificate missing a provider. This can be fixed by making a little change in New-SelfSignedCertificate
Old:$NewCert = New-SelfSignedCertificate -CertStoreLocation "cert:\CurrentUser\My" -Subject "CN=<YourAppName>" -KeySpec KeyExchange
New:$NewCert = New-SelfSignedCertificate -CertStoreLocation "cert:\CurrentUser\My" -Subject "CN=<YourAppName>" -KeySpec KeyExchange -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider"
2. MSIS9622: Client authentication failed. Please verify the credential provided for client
authentication is valid.
This is because when we create the SPN with New-GraphApplication, the certificate failed to be passed into the powershell session. So the Thumbprint of the SPN is empty.
This can be fixed by making little change in New-GraphApplication
Old:$SpObject = Invoke-Command -Session $Session -ScriptBlock {New-GraphApplication -Name "<YourAppName>" -ClientCertificates $using:cert}
New:$SpObject = Invoke-Command -Session $Session -ScriptBlock {param($cert) New-GraphApplication -Name "<YourAppName>" -ClientCertificates $cert} -ArgumentList ($cert)
3. It's worthy to mention the customer need to have the permission to access the self-signed certificate he/she generates. 
If not, customer will hit 'Keyset does not exist'. This can be fixed by correcting the permission to the cert. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193ec77a-b7dc-7807-cb42-fb1c8ad4a3c7
* Version Independent ID: 389dc440-613b-88ad-c1e9-e4b6fe6db8c6
* Content: [Give an app access to Azure Stack Hub resources - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/give-app-access-to-resources?view=azs-2102&tabs=az1%2Caz2)
* Content Source: [azure-stack/operator/give-app-access-to-resources.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/give-app-access-to-resources.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by VikasPullagura-MSFT** [comment]
@Donnie-Zhang 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@BryanLa 
Can you please check and add your comments on this doc update request as applicable.

**Comment by BryanLa** [comment]
@Donnie-Zhang - thanks much for your feedback. I'll need to consult with the security team on this as we worked closely on this particular article. I'll report back once I get a response from them..

**Comment by BryanLa** [comment]
Discussed with engineering security team. 
Issue #1 has been resolved. 
No consensus from engineering on changing anything for issue #2, so closing this for now..

#please-close
