### ISSUE TITLE
Heading formatting broken

### ISSUE THREAD

**Issue by jacobpedd** [MicrosoftDocs/azure-stack-docs#1712]
Configure an override doesn't show up in the navigation, I believe because the headings are incorrect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1cea280-89dd-b421-0ca9-da8fc972610d
* Version Independent ID: 746905a4-0549-449c-6842-d365fb7da05d
* Content: [Manage host networking with Network ATC - Azure Stack HCI](https://review.docs.microsoft.com/en-us/azure-stack/hci/manage/manage-network-atc?branch=pr-en-us-8684)
* Content Source: [azure-stack/hci/manage/manage-network-atc.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/manage-network-atc.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @v-dasis
* Microsoft Alias: **v-dasis**

**Comment by kobulloc-MSFT** [comment]
@jacobpedd, thank you for your feedback!  I want to make sure I'm looking at the right thing.  I currently see "Manage Network ATC" in the navigation to the left which matches the title, "Manage host networking using Network ATC".  "Configure an override" appears below as a heading and can be linked to (note the url in the screenshot.  Did I miss anything?

![image](https://user-images.githubusercontent.com/37556655/140095908-5a7690d3-ef48-4939-99c2-46aea56fefa3.png)

**Comment by kobulloc-MSFT** [comment]
@jacobpedd, there was an update to the docs yesterday if I'm not mistaken.  Are you looking at the live version of this document?

![image](https://user-images.githubusercontent.com/37556655/140098400-af161a89-b3f4-40ff-999b-17dcbf00579c.png)

**Comment by kobulloc-MSFT** [comment]
@jacobpedd We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
