### ISSUE TITLE
Should use -cluster instead of -IPstPort

### ISSUE THREAD

**Issue by TolliLF** [MicrosoftDocs/azure-stack-docs#1714]
I was advised by Dan Cuomo that:
New-NetQosPolicy "Cluster" -IPDstPort 3343 -Priority 6

should be
New-NetQosPolicy "Cluster" -Cluster -Priority 6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dea141b6-da05-c6d2-3abd-fab02216da49
* Version Independent ID: f0b22348-f1af-fb52-ebac-688df3941009
* Content: [Troubleshoot cluster validation reporting - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/validate-qos)
* Content Source: [azure-stack/hci/manage/validate-qos.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/validate-qos.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by GiftA-MSFT** [comment]
@TolliLF we'll review your feedback and get back to you shortly. Thanks.

**Comment by khdownie** [comment]
@TolliLF @GiftA-MSFT thank you - I verified with Dan and made the change to the doc, so this issue can be closed.
