### ISSUE TITLE
Error on page

### ISSUE THREAD

**Issue by brcart** [MicrosoftDocs/azure-stack-docs#1717]
Please ignore
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 575279d6-40ba-bb35-9dd9-ca766d561039
* Version Independent ID: 7c0f91cc-e60c-30e8-4fcf-e5ad1dd3f5bf
* Content: [Get authentication information for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/authenticate-azure-stack-hub?view=azs-2102)
* Content Source: [azure-stack/user/authenticate-azure-stack-hub.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/authenticate-azure-stack-hub.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by kobulloc-MSFT** [comment]
@brcart Thank you for your feedback!  If there is anything else you would like us to address, please open another issue and we'd be happy to work on a resolution.
