### ISSUE TITLE
Doc issue

### ISSUE THREAD

**Issue by brcart** [MicrosoftDocs/azure-stack-docs#1718]
On this page you have
For multinode systems, the user portal URL is formatted as https://management.<region>.<FQDN>
I believe this should be 
For multinode systems, the user portal URL is formatted as https://portal.<region>.<FQDN>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d05155b-09e6-313e-de80-44de4eee68a3
* Version Independent ID: 4f8eacf4-5ecb-4e15-5535-e0ca289b0c77
* Content: [Configure multi-tenancy in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/enable-multitenancy?view=azs-2102)
* Content Source: [azure-stack/operator/enable-multitenancy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/enable-multitenancy.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by kobulloc-MSFT** [comment]
@brcart Thank you for bringing this to our attention!  It looks like we have different text for the portal versus PowerShell.  We'll get a PR out to address that.

**Portal**

![image](https://user-images.githubusercontent.com/37556655/140534736-111bda31-6720-4599-9830-23ab2d107413.png)

**PowerShell**

![image](https://user-images.githubusercontent.com/37556655/140534515-15830a39-ae64-49c6-8017-e0d84b4ecc2e.png)

**Comment by BryanLa** [comment]
Thanks for this feedback @brcart. I've gone ahead and fixed this - it should republish later today.

#please-close
