### ISSUE TITLE
Unclear steps for Trusting the Certificate on Windows

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1719]
In the section [**Trust the certificate -> Windows**](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-cli?view=azs-2102&tabs=win#trust-the-certificate), step 1, the python installed as part of the Az CLI is not automatically in the PATH environment variable, so a user needs to change directory where python.exe is located, e.g.

> PS C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2> .\python -c "import certifi; print(certifi.where())"

In the same section, step 1 output example given is the Linux default location-
> ~/lib/python3.5/site-packages/certifi/cacert.pem 

Instead the example should be Windows default location-
> C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\certifi\cacert.pem

Finally, the user is not told what to do with this output, and the default location is used on line 24 of the sample script in step 2-

> Write-Host "Adding the certificate content to Python Cert store"
> Add-Content "${env:ProgramFiles(x86)}\Microsoft SDKs\Azure\CLI2\Lib\site-packages\certifi\cacert.pem" $rootCertEntry

So the user should have a variable to set the Python Cert store path, or at least instruction to adjust the path based on the output from step 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42ff21d-4d03-75c8-7ac7-7b03119b1e55
* Version Independent ID: 74536d0e-29ae-ecee-b1b2-17dfd3576b80
* Content: [Setting up certificates for Azure CLI on the Azure Stack Development Kit (ASDK)? - Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-cli?view=azs-2102&tabs=win)
* Content Source: [azure-stack/asdk/asdk-cli.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-cli.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub-asdk**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by alexsmithMSFT** [comment]
Also a minor typo for ASDK in the description of this section-

> To use Azure CLI with the **aSDK**, you must trust the CA root certificate on your remote machine.

**Comment by mattbriggs** [comment]
@alexsmithMSFT Thanks for the feedback. #in-progress

**Comment by mattbriggs** [comment]
Merged

#please-close
