### ISSUE TITLE
Steps missing for exporting and trusting root certificates on multinode Stack Hub systems

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1721]
In the section [Connect with Azure CLI -> Connect to Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-azurecli2?view=azs-2102&tabs=ad-win#connect-to-azure-stack-hub
), there is a step specific to ASDK: **Step 1 - If you are using the ASDK, trust the Azure Stack Hub CA root certificate**. The ASDK will always have this problem because it generates self signed certs but it is also applicable to any cert not already in the cert bundle distributed with python SDK, as is the case for multi-node stamps in a disconnected environment, or if the certificates are not issue by a CA in the trusted roots program.

The steps would be the same and you would simply pull the chain from the customer's Azure Stack Hub cert and import them in as directed in the doc that is linked for ASDK- https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-cli?view=azs-2102&tabs=win#trust-the-certificate

This is similar to the steps for Azure Storage Explorer, where [the doc](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-storage-connect-se?view=azs-2102#export-and-then-import-the-azure-stack-hub-certificate) explicitly calls out non-ASDK environments and gives steps 1 thru 5 to export it- 

> Export and then import Azure Stack Hub certificate **for disconnected integrated systems** and for the ASDK. For connected integrated systems, the certificate is publicly signed and this step isn't necessary.

Suggest adding steps to export and trust this certificate for non-ASDK systems, or provide a link to a new document similar to https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-cli for multi-node environments. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583c4bab-c16a-a723-04ac-b3265d9e8269
* Version Independent ID: e6ecb0ee-2303-a7ed-9fca-767e3d3bfe86
* Content: [Manage Azure Stack Hub with Azure CLI - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-azurecli2?view=azs-2102&tabs=ad-win)
* Content Source: [azure-stack/user/azure-stack-version-profiles-azurecli2.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-version-profiles-azurecli2.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@alexsmithMSFT Thanks for the feedback. #in-progress

**Comment by AnuragSingh-MSFT** [comment]
@alexsmithMSFT, thank you for the feedback. This issue has been assigned to the author for further review and update.

**Comment by mattbriggs** [comment]
Merged.

#please-close
