### ISSUE TITLE
The default value of parameter controlPlaneVmSize is not correct

### ISSUE THREAD

**Issue by Li-Yanzhi** [MicrosoftDocs/azure-stack-docs#1725]
The default value of parameter controlPlaneVmSize is **Standard_A4_v2** (4CPU,8G RAM)  instead of **Standard_A2_v2** (2CPU,4GB RAM)

![image](https://user-images.githubusercontent.com/6248137/140637048-bcad6373-9485-4e47-b4ae-a6e16cb75b64.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7063b994-0e35-6c7e-3be9-b29de6047509
* Version Independent ID: fddeb894-cb94-8e42-a6b1-0d9100e0428b
* Content: [Set-AksHciConfig for AKS on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/reference/ps/set-akshciconfig)
* Content Source: [azure-stack/aks-hci/reference/ps/set-akshciconfig.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/aks-hci/reference/ps/set-akshciconfig.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @jessicaguan
* Microsoft Alias: **jeguan**

**Comment by GiftA-MSFT** [comment]
@Li-Yanzhi we'll review your feedback and get back to you shortly. Thanks.

**Comment by jessicaguan** [comment]
@GitaraniSharma-MSFT @Li-Yanzhi hi! yes the default control plane VM size is Standard_A4_V2. It is described [here](https://docs.microsoft.com/en-us/azure-stack/aks-hci/reference/ps/new-akshcicluster), you can scroll down to the parameter description of "-controlPlaneVmSize" and see the default. Can I get some more clarity on what the issue/ask is here? Thanks!

**Comment by GitaraniSharma-MSFT** [comment]
@jessicaguan , thank you for the confirmation. It is mentioned as **Standard_A2_v2** in the below link:
https://docs.microsoft.com/en-us/azure-stack/aks-hci/reference/ps/set-akshciconfig#-controlplanevmsize

![image](https://user-images.githubusercontent.com/67630903/144272798-dc203ce4-f4c6-48ba-a532-ffbf76b9f759.png)

I do not have access to update this doc as I'm getting a 404 error.
Would you be able to update it?

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
Updated.

#please-close
