### ISSUE TITLE
ASH-R/RCA UPS suggestions

### ISSUE THREAD

**Issue by aserfass-msft** [MicrosoftDocs/azure-stack-docs#1729]
Hello,

Please consider adding the recommendation for UPSs to support an ASH-R/RCA deployment. I understand it is dependent on the time and usage assumptions but I'm really wondering what are power related ASH-R specific risks to mitigate? Are the nodes redundant enough to recover from a sudden power outage? Is brown-out UPS capacity therefore enough? Otherwise, how much time is recommended for a safe shutdown?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70d0adb4-9c95-e00d-bf5d-40751896e1e2
* Version Independent ID: cfa2aa27-8355-2cdf-13fe-4f2aca93e13a
* Content: [Azure Stack Hub ruggedized site readiness for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/ruggedized/site-readiness)
* Content Source: [azure-stack/ruggedized/site-readiness.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/ruggedized/site-readiness.md)
* Service: **azure-stack**
* GitHub Login: @PatAltimore
* Microsoft Alias: **wamota**

**Comment by VikasPullagura-MSFT** [comment]
@aserfass-msft 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@PatAltimore 
Can you please check and add your comments on this doc update request as applicable.
