### ISSUE TITLE
sql rp install powershell profile

### ISSUE THREAD

**Issue by lucidqdreams** [MicrosoftDocs/azure-stack-docs#173]
in the install powershell for azure stack page  for 1904 states https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-install

For Azure Stack 1904 or later:
Install-Module -Name AzureRM.BootStrapper

# Install and import the API Version Profile required by Azure Stack into the current PowerShell session.
Use-AzureRmProfile -Profile 2019-03-01-hybrid -Force
Install-Module -Name AzureStack -RequiredVersion 1.7.2

SQL install script states

Install-Module -Name AzureRm.BootStrapper -Force
Use-AzureRmProfile -Profile 2018-03-01-hybrid -Force
Install-Module -Name AzureStack -RequiredVersion 1.6.0

the installation check for cmdlets

VERBOSE: 5:36:50 PM :
VERBOSE: 5:36:50 PM : ************************************************
VERBOSE: 5:36:50 PM : *Checking for Azure Stack Powershell Module ...*
VERBOSE: 5:36:50 PM : ************************************************
Nuget Package provider found.
Azure Powershell Module with 2.5.0 version found. Need Azure powershell compatible with stack. Use ArmProfile 2018-03-01
-hybrid. Please uninstall the current version and rerun the RP setup

and if I now try to run the import for the cmdlets I get 

PS C:\windows\system32> Use-AzureRmProfile -Profile 2018-03-01-hybrid -Force
Loading Profile 2018-03-01-hybrid
Import-Module : The following error occurred while loading the extended type data file: Error in TypeData
"Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The TypeConverter was ignored
because it already occurs.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The member
SerializationDepth is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member
PropertySerializationSet is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member
SerializationMethod is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member
PropertySerializationSet is already present.
Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member
SerializationMethod is already present.
Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureContext": The member SerializationDepth is already
present.
Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureProfile": The member SerializationDepth is already
present.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.5.0\AzureRM.Bootstrapper.psm1:1052 char:9
+         Import-Module -Name $Module -RequiredVersion $version -Global
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

Import-Module : The specified module 'AzureRM' with version '2.3.0' was not loaded because no valid module file was
found in any module directory.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.5.0\AzureRM.Bootstrapper.psm1:1052 char:9
+         Import-Module -Name $Module -RequiredVersion $version -Global
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (AzureRM:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleWithVersionNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

its seems like the installation for SQL needs to be updated to work for 1904?  or have I missed something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d14a302-9b02-8eb4-1b49-b52580a67472
* Version Independent ID: 10c55050-5b52-a48d-bfb2-eba0a4494900
* Content: [Install PowerShell for Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-install)
* Content Source: [azure-stack/operator/azure-stack-powershell-install.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-powershell-install.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by MicahMcKittrick-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@lucidqdreams Thanks for the feedback! This is a known issue with installing the SQL RP, and currently the workaround is to uninstall the newer PowerShell Modules, and install the older ones required for the SQL RP. This is also discussed in #18. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
