### ISSUE TITLE
az arcappliance create hci raises InvalidResourceType

### ISSUE THREAD

**Issue by kongou-ae** [MicrosoftDocs/azure-stack-docs#1739]
Hi,

I tried installing ResourceBridge to Nested Azure Stack HCI. But the following error raised.

```
PS C:\Users\AzureUser>  az arcappliance create hci --config-file $csv_path\workingDir\hci-appliance.yaml --kubeconfig $env:USERPROFILE\.kube\config
Command group 'arcappliance create' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Appliance create command failed with error:  (InvalidResourceType) The resource type could not be found in the namespace 'Microsoft.ResourceConnector' for api version '2020-09-15-privatepreview'.
```

I believe that our Azure CLI and extensions are latest version and requires prerequisite for this feature.

```
PS C:\Users\AzureUser> az version
{
  "azure-cli": "2.30.0",
  "azure-cli-core": "2.30.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "arcappliance": "0.1.42",
    "azurestackhci": "0.2.1",
    "connectedk8s": "1.2.0",
    "customlocation": "0.1.3",
    "k8s-configuration": "1.1.1",
    "k8s-extension": "1.0.0"
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b82e60f9-ebed-4011-41b7-3e11a60322ff
* Version Independent ID: 61535b85-bea3-f0b5-f562-fdd08293ed65
* Content: [VM provisioning through Azure portal on Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-enabled-virtual-machines?WT.mc_id=AZ-MVP-5003408)
* Content Source: [azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @kilolsurjan
* Microsoft Alias: **ksurjan**

**Comment by ksurjan** [comment]
@kongou-ae, thanks for trying this.
Please go use the sign-up link to have access to the Preview: https://aka.ms/joinEAP.

This requirement will be removed in the next few weeks.

**Comment by kongou-ae** [comment]
Hi @ksurjan,

Thanks. After having onboarding my subscription, this error was fixed.

Best
