### ISSUE TITLE
Need to change the version of the Custom Script extension to 2.0.6

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1742]
The extension we refer to should not be the "latest" but instead the 2.0.6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4871e496-b684-ea5f-b579-50774bb9ffb4
* Version Independent ID: b683dc6a-864d-9932-11da-3335d2597cb7
* Content: [Install and offer the Azure Kubernetes Service on Azure Stack Hub - Azure Stack Hub](https://review.docs.microsoft.com/en-us/azure-stack/operator/aks-add-on?view=azs-2108&branch=release-2108)
* Content Source: [azure-stack/operator/aks-add-on.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/aks-add-on.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by kobulloc-MSFT** [comment]
@walterov Thank you for bringing this to our attention!  We'll review the documentation and get back to you shortly.

**Comment by mattbriggs** [comment]
@walterov 

#in-inprogress

**Comment by mattbriggs** [comment]
Updated

#please-close
