### ISSUE TITLE
Error at Step 3 of "Install PowerShell modules and update extensions"

### ISSUE THREAD

**Issue by excelsi** [MicrosoftDocs/azure-stack-docs#1745]
I get this error at the Set-MocConfig Command:

ssh-keygen : The term 'ssh-keygen' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included,
verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\Moc\1.0.9\Moc.psm1:1812 char:9
+         ssh-keygen -q -f $($global:config[$modulename]["sshPrivateKey ...
+         ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ssh-keygen:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The OpenSSH Client is unfortunately not avaialable on Azure Stach HCI OS so what can i do here?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b82e60f9-ebed-4011-41b7-3e11a60322ff
* Version Independent ID: 61535b85-bea3-f0b5-f562-fdd08293ed65
* Content: [VM provisioning through Azure portal on Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-enabled-virtual-machines)
* Content Source: [azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ksurjan
* Microsoft Alias: **ksurjan**

**Comment by ksurjan** [comment]
Hello, 
Can you please share the version of the Host OS. ssh-keygen is standard with new versions of Windows OS.
Thanks.

**Comment by excelsi** [comment]
The Host OS is Azure Stack HCI because i need to execute the Command there as i understand the Docs correctly..

**Comment by excelsi** [comment]
If i do an Get-WindowsOptionalFeature -Online on Azure Stack HCI i don't see the OpenSSH Client Feature so that i could enable this here...

**Comment by excelsi** [comment]
I checked also the 21H2 Relase Build 20348, which also doesn't include the OpenSSH Client Feature..

**Comment by ksurjan** [comment]
Thanks for the details. I am checking on this.

**Comment by ksurjan** [comment]
Can you please check if running ssh-keygen on all nodes unblocks this step.

**Comment by excelsi** [comment]
I cannot run ssh-keygen because it's not available..

**Comment by excelsi** [comment]
This should be Part of the OpenSSH Client i assume..

**Comment by ksurjan** [comment]
Can you also share the output of the following:

Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH*'

# Install the OpenSSH Client
Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

**Comment by excelsi** [comment]
Thanks that was the right CMDlet here... i didn't remeber before :-)

**Comment by excelsi** [comment]
Unfortunately the installation stucks in running forever as it seems...
<img width="403" alt="image" src="https://user-images.githubusercontent.com/8747559/142990236-7b51cf69-d3e6-42db-a66d-443971ee0894.png">

**Comment by excelsi** [comment]
I managed to install this now through a workarround

**Comment by ksurjan** [comment]
For Portal access to create Virtual Machines, please use aka.ms/AzureArcVM.
Please feel free to reach out to me with any feedback. Thanks.

**Comment by excelsi** [comment]
Now im at point 4 "Update the required extensions:" and i got errors here (i think because az shell is not installed on the Azure Stack HCI Node)... what's the sugesstion here or how can i can quickly install AZ Shell?

**Comment by excelsi** [comment]
Or should this az extension commands be executed on Azure?

**Comment by excelsi** [comment]
Shou
