### ISSUE TITLE
Can't create a virtual machine on AzSHCI from portal due to no virtual machine kind

### ISSUE THREAD

**Issue by kongou-ae** [MicrosoftDocs/azure-stack-docs#1749]
I created custom location but I can't create a VM from Azure Portal. Because there is no virtual machine kind. Any idea?

![image](https://user-images.githubusercontent.com/3410186/143686532-c879834e-f516-4257-83f3-5b768d13f4a9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b82e60f9-ebed-4011-41b7-3e11a60322ff
* Version Independent ID: 61535b85-bea3-f0b5-f562-fdd08293ed65
* Content: [VM provisioning through Azure portal on Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-enabled-virtual-machines?WT.mc_id=AZ-MVP-5003408#prerequisites-for-deploying-azure-arc-resource-bridge)
* Content Source: [azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ksurjan
* Microsoft Alias: **ksurjan**

**Comment by excelsi** [comment]
I used the preview portal link but still cannot select the Virtual Machine Kind also if i have created my Location, Network and Gallery Image:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/8747559/143691519-e84e2988-5ae9-4113-8cab-6cefc9ad12f0.png">

<img width="627" alt="image" src="https://user-images.githubusercontent.com/8747559/143691555-14a0e246-d9f6-462e-9b70-80ee814c4f1d.png">

What could be the issue here?

**Comment by MayankBargali-MSFT** [comment]
@kongou-ae Thank you for your feedback! We will review and update as appropriate.

**Comment by excelsi** [comment]
Thanks i could start the Deployment now but after some time got this deployment error:

{
    "status": "Failed",
    "error": {
        "code": "InternalError",
        "message": "Cannot connect to the hybrid connection because no agent is connected in the target arc resource."
    }
}

Any help here?
Thanks!

**Comment by ksurjan** [comment]
Can you please provide get-archcilogs bundle?

**Comment by excelsi** [comment]
I need to enter the Password for this user of the local Linux VM:
<img width="208" alt="image" src="https://user-images.githubusercontent.com/8747559/143928571-94efe619-e63f-4995-9110-843d286437b6.png">
and then the cloudservice IP of something?
<img width="169" alt="image" src="https://user-images.githubusercontent.com/8747559/143928640-51703390-d42c-4457-8d35-3ae9397fe1ed.png">
Thanks!

**Comment by ksurjan** [comment]
You can do the following:
1. uninstall-module archci
2. Install-Module -Name ArcHci -RequiredVersion 0.2.6 -Force -Confirm:$false -SkipPublisherCheck -AcceptLicense
3. close all powershell windows
4. restart powershell
5. get-archcilogs
This will not prompt for VM passwords. It will still require cloudServiceIP and the token file generated under $csv_path/workingDir/

**Comment by excelsi** [comment]
How is the file called with the login information?

<img width="324" alt="image" src="https://user-images.githubusercontent.com/8747559/143931441-c4987c16-fcb0-41b0-8753-633a1f607fc5.png">

Thanks!

**Comment by ksurjan** [comment]
it should be a .tok file.

**Comment by excelsi** [comment]
Worked
https://1drv.ms/u/s!Aopp0r2sfNjEio9lvtoGpzeXDHdchQ?e=I0FLvh

**Comment by kongou-ae** [comment]
@ksurjan 

I created the new VM by https://aka.ms/AzureArcVM. Then the following error raised.

![image](https://user-images.githubusercontent.com/3410186/144072026-1f9afb9b-1d9a-4414-b57c-5d27e876b9c5.png)

After a few minutes later from this error, I found the new VM in Azure Stack HCI. I guess that timeout may be short.

Best.

**Comment by ksurjan** [comment]
Would you be able to get `get-ArcHCILogs` and share it with me. Thanks.

**Comment by excelsi** [comment]
Im now one step further but now it's failed on the gallery image:

{
    "status": "Failed",
    "error": {
        "code": "NotFound",
        "message": "Couldn't find gallery image with name 'WS22AzureCore': Couldn't find a Gallery image with name 'WS22AzureCore': Not Found"
    }
}

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/8747559/144126043-38bd82a3-43cd-4c75-9a8a-4834485894bb.png">

But the gallery image exists:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/8747559/144126097-21682a2d-0b0c-4fc6-872b-18df00192435.png">

**Comment by excelsi** [comment]
Deployment succeded after i recreated the galleryimage

**Comment by ksurjan** [comment]
> Worked https://1drv.ms/u/s!Aopp0r2sfNjEio9lvtoGpzeXDHdchQ?e=I0FLvh

@excelsi was this a transient error or are you seeing this for every VM creation ?

**Comment by excelsi** [comment]
No this was my first try yesterday, now it succeded after some retries..

**Comment by ksurjan** [comment]
Please let me know if you have any other issues.

**Comment by wagnerock** [comment]
I had the same issue as the original poster. I was able to initiate provisioning using the new link (https://aka.ms/AzureArcVM) but the the VM provisioning failed. 

The logs: https://nerdio1013-my.sharepoint.com/:u:/g/personal/nwagner_getnerdio_com/EccGDNU-f_hJjS1tHI0wGS8BgvbGePMleCr995RpuZMyRA?e=EwVpT6

**Comment by ksurjan** [comment]
@wagnerock  - What is the error message with VM provisioning?

**Comment by wagnerock** [comment]
The initial error message was that the operation timed out. In activity log the operation claims to have succeeded, and there's a VM resource in the portal, but it says "failed to provision"

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/59660952/150229650-bf0e6af8-2539-4862-b4af-5c79822caae1.png">

**Comment by ksurjan** [comment]
Thanks for the sharing the screenshot. Will follow up with an update here. Thanks.

**Comment by wagnerock** [comment]
Thanks. I'm creating a new image now, as I think the image file was vhd and not vhdx

**Comment by ksurjan** [comment]
Hello @wagnerock - Did using a vhdx work for you?

**Comment by wagnerock** [comment]
Hi @ksurjan. I created a vhdx file, but now I'm having trouble creating the image resource. The command 

`az azurestackhci galleryimage create`

Fails with this error: 

`Deployment failed. Correlation ID: 1bb66607-4e0e-4eab-bfc5-d66182e14701. rpc error: code = NotFound desc = Type[GalleryImage], Location[MocLocation], Name[win10-21h2-evd]: Not Found`

The Azure activity logs eventually indicated that this operation succeeded, but the image is not available when I attempt to create a VM in the custom location. Creating the custom location also reported an error initially, but eventually succeeded and is visible in the portal.

Log files are attached. Very much appreciate your help!
[archcilogs 2.zip](https://github.com/MicrosoftDocs/azure-stack-docs/files/7929481/archcilogs.2.zip)

**Comment by ksurjan** [comment]
Thank you. I will follow up shortly.
Can you also run the command that is failing with -v and provide the output.

**Comment by wagnerock** [comment]
@ksurjan Not much info there: 
<img width="974" alt="image" src="https://user-images.githubusercontent.com/59660952/150885360-9f2d44a1-bce8-4de6-8776-303fb9b68268.png">

**Comment by wagnerock** [comment]
@ksurjan I was eventually able to create an image. One issue was that I didn't realize the image-path value needed double \\ in the path. Another issue was that the disks were low on space. I now have an image, but creating the vm in the portal failed:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/59660952/151259457-b4d0fd9d-37e3-4d16-a3d3-07d97a719263.png">
<img width="492" alt="image" src="https://user-images.githubusercontent.com/59660952/151259473-d2737a9a-06d8-4f8a-a40c-26f58ed1e58b.png">

**Comment by wagnerock** [comment]
Looks like that one was because I hadn't specified a resource group. It let me submit the deployment without one, but then failed. New deployment is in progress now

**Comment by ksurjan** [comment]
@wagnerock  can you elaborate on the double \  problem.
We use single \ and that seems to work correctly. Can you provide the path so we can take a look? Thanks.
