### ISSUE TITLE
Please review Maximum supported specifications

### ISSUE THREAD

**Issue by IvanNaumeiko** [MicrosoftDocs/azure-stack-docs#1752]
Please review Maximum supported specifications here:
https://docs.microsoft.com/en-us/azure-stack/aks-hci/concepts-support 

Not sure if that is still valid, it looks confusing.

Azure Kubernetes Service on Azure Stack HCI deployments that exceed the following specifications are not supported:
MAXIMUM SUPPORTED SPECIFICATIONS
Resource	Maximum
Physical servers per cluster	4
Kubernetes Clusters	4
Total number of VMs	200

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d689781-cffe-081d-2e9b-73daeac18c45
* Version Independent ID: 6507d088-54d8-ccc9-c755-3545bd0d67a0
* Content: [Concepts - Supported resource limits, VM sizes, and regions in AKS on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/concepts-support)
* Content Source: [azure-stack/aks-hci/concepts-support.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/concepts-support.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mamezgeb
* Microsoft Alias: **mamezgeb**

**Comment by kobulloc-MSFT** [comment]
@IvanNaumeiko Thank you for your feedback!  We are investigating this and will get back to you shortly.

**Comment by mkostersitz** [comment]
Yes looks like this got missed in the latest update cycle we should update it to reflect what we say elsewhere that it is 8 physical nodes and 8 target clusters with 200 VMs. @abhilashaagarwala  is working on new wording I believe

**Comment by mattbriggs** [comment]
Thanks for your feedback.
Updated.

https://docs.microsoft.com/en-us/azure-stack/aks-hci/concepts-support

#please-close

**Comment by mkostersitz** [comment]
Thanks for pushing this out quickly.

Mike
________________________________
