### ISSUE TITLE
Does Microsoft provide backend support for MySQL services? If not whom shall we procure the support from?

### ISSUE THREAD

**Issue by habeebth7** [MicrosoftDocs/azure-stack-docs#1757]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9b14206-ecc7-c437-dfb7-283be7faf482
* Version Independent ID: d3559753-5579-a08b-bfcb-4202b2395a5f
* Content: [Create highly available MySQL databases - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-tutorial-mysql?view=azs-2102)
* Content Source: [azure-stack/operator/azure-stack-tutorial-mysql.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-tutorial-mysql.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @habeebth7 
Following are the options to host MySQL server on Azure:
1. **Azure Database for MySQL** - This option is a fully managed MySQL database engine based on the stable version of MySQL community edition. This relational database as a service (DBaaS), hosted on the Azure cloud platform, falls into the industry category of PaaS
2. **MySQL on Azure VMs** - This option falls into the industry category of IaaS. With this service, you can run MySQL Server inside a managed virtual machine on the Azure cloud platform.

You can go through [this documentation](https://docs.microsoft.com/en-in/azure/mysql/select-right-deployment-type) for additional details. Please let me know if you have any additional questions. Thank you!

**Comment by habeebth7** [comment]
@ChaitanyaNaykodi-MSFT ... Thanks for the quick response. Our query was related to Azure Stack.  We see MySQl from Bitnami on Azure Stack. What level of support microsoft provide for such third party images/solutions? OS Level? application Level or not at all?

MS DOC https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-tutorial-mysql?view=azs-2102 speaks about Bitnami image. Does this mean Microsoft is responsible for supporting entire solutions including VM OS & MYSQL applications.?

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Hello @habeebth7, thank you for clarifying the question. As per this [FAQ documentation](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-windows-server-faq?view=azs-2002&tabs=az1%2Caz2#who-should-i-contact-for-support-issues-with-azure-stack-hub-marketplace-items-)

> Publishers are responsible for providing technical support for their products on the Azure Stack Hub Marketplace.

Please go through [this FAQ documentation](https://docs.microsoft.com/en-us/azure/marketplace/marketplace-faq-publisher-guide#customer-support) as well for additional details on how you can get support for commercial marketplace products.

Hope this helps answer your question. Please let me know if you have any additional questions. Thank you!

**Comment by habeebth7** [comment]
Thanks, clear. I will contact Bitnami for the support. Appreciate your help.

**Comment by ChaitanyaNaykodi-MSFT** [comment]
Glad I could help. We will now proceed to close this issue out. Please tag me in your response if you have any additional questions. Thank you!
