### ISSUE TITLE
Enhancements to Secrets Store CSI Driver + AKS-HCI docs

### ISSUE THREAD

**Issue by aramase** [MicrosoftDocs/azure-stack-docs#1760]
1. Typo in the helm command [here](https://docs.microsoft.com/en-us/azure-stack/aks-hci/secrets-store-csi-driver#install-the-secrets-store-csi-driver)

```
helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/chartsy`(extra y at the end)
```

Should be 
```
helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
```

2. Update api version in this [section](https://docs.microsoft.com/en-us/azure-stack/aks-hci/secrets-store-csi-driver#create-and-apply-your-own-secretproviderclass-object)

The apiVersion should be `secrets-store.csi.x-k8s.io/v1` instead of `secrets-store.csi.x-k8s.io/v1alpha1`

3. The namespace isn't required in [here](https://docs.microsoft.com/en-us/azure-stack/aks-hci/secrets-store-csi-driver#validate-the-secrets-store-deployment).

The `busybox-secrets-store-inline` is being deployed in default namespace based on the yaml, so `--namespace kube-system` isn't required in the commands. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48500978-a4c7-4fd8-2c5a-3fca53607600
* Version Independent ID: d87865b6-266a-a2fb-631a-d7f66b62e304
* Content: [Kubernetes Secrets Store CSI Driver integration with AKS on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/secrets-store-csi-driver)
* Content Source: [azure-stack/aks-hci/secrets-store-csi-driver.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/secrets-store-csi-driver.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @jessicaguan
* Microsoft Alias: **jeguan**

**Comment by kobulloc-MSFT** [comment]
@aramase Thank you for the feedback!  We are reviewing this and will get back to you shortly.

**Comment by Karishma-Tiwari-MSFT** [comment]
I have created a PR for the 1.Typo  

I have assigned the issue to the content author to investigate further and update the document as appropriate for 2 & 3.
