### ISSUE TITLE
Change to the latest know issue and one more known issue

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1764]
For this Known Issue: https://docs.microsoft.com/en-us/azure-stack/user/aks-known-issues?view=azs-2108#applications-deployed-to-aks-clusters-fail-to-access-persistent-volumes

We need to change the beginning of this sentence "When you deploy to an AKS cluster using Kubernetes 1.19 ..." to "When you deploy an AKS cluster using:
- Kubernetes 1.19 or 
- Kubernetes 1.20 with Kubenet as the network plug-in

and deploy an application that uses persistent volumes, you will note an issue with the application's pod when it tries to deploy a persistent volume. If you look into the pod's log, you may find an error regarding permissions denied. The problem resides in Azure Stack Hub's Azure Disk CSI driver"

Also add a known issue to this list https://docs.microsoft.com/en-us/azure-stack/user/aks-known-issues?view=azs-2108#known-issues, saying that in Public Preview there is no support for AKS PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b99c7b6-e07b-e082-6069-35539612b5ac
* Version Independent ID: d0877253-8f15-7c64-a242-0f79303b396b
* Content: [Known issues for the Azure Kubernetes Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/aks-known-issues?view=azs-2108)
* Content Source: [azure-stack/user/aks-known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/aks-known-issues.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks! #in-progress

**Comment by mattbriggs** [comment]
Updated.

#please-close
