### ISSUE TITLE
Change the AKS known issue to also include ACR

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1765]
Change this known issue to also include ACR: https://docs.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-2108#update-to-2108-will-not-proceed-if-there-are-aks-clusters-created-and-the-private-preview-of-aks-service-is-installed

Title should change to "Update to 2108 will not proceed if there are AKS clusters or ACR Registries created and the private preview of AKS and ACR services is installed"

Here are the rest of the sentences:

Applicable: This issue applies to Azure Kubernetes Service (AKS) and Azure Container Registry (ACR) private preview customers who plan to upgrade to 2108.
Remediation: The operator must delete all AKS clusters and ACR Registries and uninstall the private preview of the AKS and ACR services.
Occurrence: Any stamp that has the AKS and ACR private preview installed will experience this message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0094b74f-e85b-6983-5f58-ce24f825b63c
* Version Independent ID: a90feafe-0401-3da0-bb95-4dbc8868ea0f
* Content: [Azure Stack Hub known issues - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-2108)
* Content Source: [azure-stack/operator/known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/known-issues.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@walterov Done, thank you for the update! Will be live at 10 AM PST tomorrow. Just FYI, if it's easier to send email for small changes like this rather than file a GitHub issue, we are OK with that. Whatever is easiest for you. #please-close
