### ISSUE TITLE
Azure Stack Hub - VPN Gateway - Clarify if P2S - Point to Site is supported

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/azure-stack-docs#1766]
To help avoid user confusion, please clarify in the article if the Gateway SKUs supports point to site VPN connections. Hyperscale Azure from the same SKUs supports P2S. 

Consider also adding the same clarification note to the following page: [https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-gateway-settings?view=azs-2108](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-gateway-settings?view=azs-2108)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f780e2ad-c126-43e9-2596-848115d09fa7
* Version Independent ID: 7e6afc9e-2803-5831-14b5-44d6fdbdb952
* Content: [Create VPN gateways for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-gateway-about-vpn-gateways?view=azs-2108)
* Content Source: [azure-stack/user/azure-stack-vpn-gateway-about-vpn-gateways.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-vpn-gateway-about-vpn-gateways.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by CristianEdwards** [comment]
Hi Chase, 
Thank you for your feedback.  the following network considerations article covers the differences between Azure and Azure Stack Hub Networking. https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-differences?view=azs-2108. The first row of the VPN section explains that P2S VPNs are not supported in Hub.

**Comment by Karishma-Tiwari-MSFT** [comment]
@CHDAFNI-MSFT We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
