### ISSUE TITLE
Clarify supportability of custom IPSec/IKE policy configurations

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/azure-stack-docs#1768]
Per note on page:

"In addition, Azure Stack Hub does not support using policy-based traffic selectors for route-based gateways at this time, because custom IPSec/IKE policy configurations are not supported."

However, per these 2 links:

- [https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-s2s?view=azs-2108&tabs=az1%2Caz2%2Caz3%2Caz4%2Caz5%2Caz8%2Caz6%2Caz7#part-2---supported-cryptographic-algorithms-and-key-strengths](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-s2s?view=azs-2108&tabs=az1%2Caz2%2Caz3%2Caz4%2Caz5%2Caz8%2Caz6%2Caz7#part-2---supported-cryptographic-algorithms-and-key-strengths)
- [https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-s2s?view=azs-2108&tabs=az1%2Caz2%2Caz3%2Caz4%2Caz5%2Caz8%2Caz6%2Caz7#1-create-an-ipsecike-policy](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-s2s?view=azs-2108&tabs=az1%2Caz2%2Caz3%2Caz4%2Caz5%2Caz8%2Caz6%2Caz7#1-create-an-ipsecike-policy) 
 
It gives the impression custom policy configurations are possible. If it is indeed possible, please assess if the policy-based routing statement is still true as well "Currently, Azure Stack Hub only supports the route-based VPN type. If your device only supports policy-based VPNs, then connections to those devices from Azure Stack Hub are not supported."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ea6e48-1e3a-6fc0-04a7-89e4300eecc8
* Version Independent ID: 2eff51e4-ed22-2420-7d5a-241f754b5a4e
* Content: [Configure VPN gateway settings for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-gateway-settings?view=azs-2108)
* Content Source: [azure-stack/user/azure-stack-vpn-gateway-settings.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-vpn-gateway-settings.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by kobulloc-MSFT** [comment]
@CHDAFNI-MSFT Thank you for your feedback!  This is being reviewed and we will get back to you shortly.

**Comment by Karishma-Tiwari-MSFT** [comment]
@@sethmanheim Can you please help confirm on this? Thanks.

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by CHDAFNI-MSFT** [comment]
Hello @Karishma-Tiwari-MSFT  and @sethmanheim  - just checking in on this.

**Comment by sethmanheim** [comment]
@CHDAFNI-MSFT I have escalated the question, hoping for a response later.

**Comment by sethmanheim** [comment]
@CHDAFNI-MSFT I got the following response from the development team:

The term “custom IPSec/IKE policy” is being overloaded. In other docs, we use the term to refer to the IKE Main Mode and Quick Mode negotiation parameters (encryption algorithm, Diffie-hellman group, etc…). We support custom IPSec negotiation parameters if the resources are created via Powershell.

The sentence you quoted includes policy-based traffic selectors in the definition of “custom IPSec/IKE policy”. We do not support any policy-based traffic selectors like in Azure. Here is the Azure documentation on policy-based VPNs: https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-connect-multiple-policybased-rm-ps#update

**Comment by sethmanheim** [comment]
I have added some clarifying text to the section in https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-gateway-settings?view=azs-2108#vpn-types. Thank you again for the feedback.

**Comment by sethmanheim** [comment]
#please-close
