### ISSUE TITLE
Switch requirements N-S vs E-W

### ISSUE THREAD

**Issue by gregnashnamoi** [MicrosoftDocs/azure-stack-docs#1776]
Hi,
It's a little ambiguous whether all these are required on North-South switches, or only on East-West. It appears East-West has stricter requirements, but those might be avoided if E-W is done switchless.
For branch-office / edge scenarios, it would be helpful to work with N-S switches that don't do .1Qbb and .1Qaz

Can this be clarified?

thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37289c9d-b579-912c-1bf0-95cd71034a4b
* Version Independent ID: 9b6a5ee4-4b17-657b-e1b4-5a8f4ccbfe49
* Content: [Physical network requirements for Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/physical-network-requirements)
* Content Source: [azure-stack/hci/concepts/physical-network-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/physical-network-requirements.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @jacobpedd
* Microsoft Alias: **jpeddicord**

**Comment by VikasPullagura-MSFT** [comment]
@gregnashnamoi 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@jacobpedd 
Can you please check and add your comments on this doc update request as applicable.
