### ISSUE TITLE
Dead links for Leader and consortium member templates from GitHub

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1777]
The first two template short-links used in step 1 of each section are dead now, redirecting to bing.com (aka.ms shows no link exists)-
https://aka.ms/aa6z619
https://aka.ms/aa6zkua

The third one is valid, ownership shows @mattbriggs 
https://aka.ms/aa6zdyt

Suggest updating the first two, with new short links, pointing to the correct templates under-
https://github.com/Azure/AzureStack-QuickStart-Templates/tree/master/ethereum-consortium-blockchain/marketplace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5463f12-085e-6215-28ce-0a623d315ddd
* Version Independent ID: a24ebeda-404f-19ab-1eb1-7d929e70ace0
* Content: [Deploy Ethereum blockchain network on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-ethereum?view=azs-2108#prerequisites)
* Content Source: [azure-stack/user/azure-stack-ethereum.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-ethereum.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by SatishBoddu-MSFT** [comment]
Hello [@alexsmithMSFT](https://github.com/alexsmithMSFT)
I have assigned the issue to the content author for further review.

**Comment by mattbriggs** [comment]
@alexsmithMSFT Thanks Alex!

#in-progress

**Comment by PatAltimore** [comment]
Updated links. Also removed a broken link.

#please-close
