### ISSUE TITLE
Red Hat Enterprise Linux Images private offering survey link no longer works

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1780]
The Red Hat Enterprise Linux Images private offering survey link on this page no longer works-

https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR_e32WQju3tMrgXNcUR94AVUNkJTWjdQRjc3TzFLREdGU0dIVFRUQ1JCSi4u

Resulting page says- **Sorry, something went wrong -> This form doesn't exist.**

Red Hat Enterprise Linux Images are a private offering on Azure Stack Hub. To make this offering available to your Marketplace Management tab, you will need to **complete a survey.** After you post the survey, it takes seven business days to see it in your Add from Azure tab within Marketplace Management.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc31e147-b01d-ab0d-f97a-14ace2d658a8
* Version Independent ID: 351862a1-a03f-61dd-e619-3af6562870ac
* Content: [Offer a Red Hat-based virtual machine for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-redhat-create-upload-vhd?view=azs-2108#offer-a-red-hat-based-vm)
* Content Source: [azure-stack/operator/azure-stack-redhat-create-upload-vhd.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-redhat-create-upload-vhd.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@alexsmithMSFT Sorry, I must be misunderstanding the issue here, as all links on this page seem to work just fine. Please contact me internally if you have more information rather than through external GitHub issues. Thank you! #please-close
