### ISSUE TITLE
KB5008210 is for Azure Stack HCI version 20H2

### ISSUE THREAD

**Issue by JimLin-Qcttw** [MicrosoftDocs/azure-stack-docs#1783]
KB5008210 is for Azure Stack HCI version 20H2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c98d186-ef81-48f0-7e70-301b3ad92f09
* Version Independent ID: 8552ac82-b862-f27d-e8df-5e4a8612d9ea
* Content: [Azure Benefits on Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-benefits)
* Content Source: [azure-stack/hci/manage/azure-benefits.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/azure-benefits.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
Hi @JimLin-Qcttw, thank you for catching that. The correct KB should be KB5008223 -- I will make the change immediately. Thanks again! #please-close
