### ISSUE TITLE
Install-AzProfile fails with Install-Module missing parameter 'AllowPrerelease'

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1785]
The currently published commands fail on a clean install, at this step-

**PS C:\WINDOWS\system32> Install-AzProfile -Profile 2020-09-01-hybrid -Force** 
_Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'._

This happened on my personal client machine, as well as a customer's today. It seems to be related to a change in PowerShellGet, I found more info and a workaround here- https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness/issues/3094#issuecomment-974689244

The workaround steps from that example were (as administrator)-
```
powershell -noprofile # Starts PSCore
$PSVersionTable
Uninstall-Module PowershellGet -AllVersions -Force -Confirm:$false
Get-module PowershellGet
Find-module PowershellGet
Install-Module PowershellGet -Force
```

After this, I was able to go back and successfully run the Install-AzProfile command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c7ec8b-634f-6b95-7ce1-c38d55b12c23
* Version Independent ID: 8cc3a38e-0bbc-71b4-2c37-fc6231bb540d
* Content: [Install PowerShell Az module for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2108#4-connected-install-with-internet-connectivity)
* Content Source: [azure-stack/operator/powershell-install-az-module.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/powershell-install-az-module.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SatishBoddu-MSFT** [comment]
[@alexsmithMSFT](https://github.com/alexsmithMSFT)
I have assigned the issue to the content author for further review.

**Comment by mattbriggs** [comment]
Thanks for this info! Updated topic.

@please-close

**Comment by alexsmithMSFT** [comment]
Just hit the same issue again on a fresh Windows Server 2019 VM. The same workaround unblocked the install again.
Most of the steps were in PowerShell ISE as Administrator, but workaround steps to re-install PowerShellGet only work in a cmd.exe window as Admin (not ISE) because it uses a subshell of powershell.exe, which can't run in ISE.

**Comment by mattbriggs** [comment]
@alexsmithMSFT I added this to the install Powershell Az topic. Should we add this as a known issue as well in case someone runs into the issue after installing Az? 

Current doc (with update based on your feedback):
https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2108#prerequisites-for-windows
