### ISSUE TITLE
One statement per code block

### ISSUE THREAD

**Issue by ChristianGottinger** [MicrosoftDocs/azure-stack-docs#1788]
Consider splitting the two statements in "Create the Kubernetes Secret with credentials" block and add description why to add the label in secret secrets-store-cred secret. 

e.g.

## Create the Kubernetes Secret with credentials

To create the Kubernetes secret with the Service Principal credentials, run the following command. Replace the following values with the appropriate Client ID and Client Secret from the previous step.

```powershell
kubectl create secret generic secrets-store-creds --from-literal clientid=<client-id> --from-literal clientsecret=<client-secret>
```

By default the Secret Store Provider has filtered watch enabled on secrets. Allow finding the secret in default configuration by adding the label secrets-store.csi.k8s.io/used=true to secret.

```powershell
kubectl label secret secrets-store-creds secrets-store.csi.k8s.io/used=true
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48500978-a4c7-4fd8-2c5a-3fca53607600
* Version Independent ID: d87865b6-266a-a2fb-631a-d7f66b62e304
* Content: [Kubernetes Secrets Store CSI Driver integration with AKS on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/secrets-store-csi-driver#feedback)
* Content Source: [azure-stack/aks-hci/secrets-store-csi-driver.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/secrets-store-csi-driver.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @jessicaguan
* Microsoft Alias: **jeguan**

**Comment by JamesTran-MSFT** [comment]
@ChristianGottinger 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@ChristianGottinger 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@jessicaguan 
Can you please check and add your comments on this doc update request as applicable.

**Comment by mattbriggs** [comment]
Updated

#please-close
