### ISSUE TITLE
Dead feedback link

### ISSUE THREAD

**Issue by jamesaepp** [MicrosoftDocs/azure-stack-docs#1789]
The paragraph below:

https://docs.microsoft.com/en-us/azure-stack/hci/faq#can-i-transfer-data-offline-between-an--air-gapped--azure-stack-hci-and-azure

Links to: https://feedback.azure.com/forums/929833-azure-stack-hci

Which is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bce9bf06-c279-4009-0fae-65315f490cd8
* Version Independent ID: 89c42ecf-095b-758f-0e3d-fc4114cf48d2
* Content: [Azure Stack HCI FAQ](https://docs.microsoft.com/en-us/azure-stack/hci/faq#can-i-transfer-data-offline-between-an--air-gapped--azure-stack-hci-and-azure)
* Content Source: [azure-stack/hci/faq.yml](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/faq.yml)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by JamesTran-MSFT** [comment]
@jamesaepp 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by JamesTran-MSFT** [comment]
@jamesaepp
Thank you for pointing this out! I've created a PR to update the documentation and it's currently waiting for the author to review and sign off.

New Link - https://feedback.azure.com/d365community/forum/74a4b1b9-0725-ec11-b6e6-000d3a4f07b8

I will now close out this issue. Please allow some time for the author to review and the changes to reflect.
Thank you for your time and patience!
