### ISSUE TITLE
How are the Azure Marketplace items made available for Azure Stack Hub?

### ISSUE THREAD

**Issue by TheOnlyWei** [MicrosoftDocs/azure-stack-docs#1791]
[Enter feedback here]
How are the Azure Marketplace items made available for Azure Stack Hub? What process determines this? How is it possible for an independent software vendor to update their Azure Stack Hub marketplace product if they are not consistent with their Azure Cloud marketplace counterpart product. I received an ICM from an independent software vendor customer with this question.

Customer Question Update (1/3/2022):
We need to understand how the marketplace item in public Azure can be tagged properly, so that the updated version appears under the Azure Stack Hub registration-

/subscriptions/[SubID]/resourceGroups/[RGName]/providers/Microsoft.AzureStack/registrations/<RegName>/products/[productName][tag]

so this item can then be downloaded to Azure Stack Hub via the "Add from Azure" in the portal, or  Select-AzsMarketplaceItem tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7c550a-722a-d50a-dd72-59bcb4de5292
* Version Independent ID: a879ecd5-7baa-c3d1-4197-863124c6978c
* Content: [Azure Marketplace items available for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-marketplace-azure-items?view=azs-2108#feedback)
* Content Source: [azure-stack/operator/azure-stack-marketplace-azure-items.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-marketplace-azure-items.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by PriyankaRudramaina** [comment]
Hi @TheOnlyWei, 

Thank you for the question, I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by sethmanheim** [comment]
@PriyankaRudramaina This seems more like a product query, not a documentation issue.

**Comment by TheOnlyWei** [comment]
@sethmanheim Yes, it is a product query, but this questions doesn't seem to be answered in any documentation I can find, so will be helpful to be documented as an independent software vendor created an ICM for this question.

**Comment by VikasPullagura-MSFT** [comment]
@TheOnlyWei Thanks for sharing more details. 
I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by TheOnlyWei** [comment]
There is an update from customer with a more refined question on how to update their product:

> We need to understand how the marketplace item in public Azure can be tagged properly, so that the updated version appears under the Azure Stack Hub registration-
> 
> /subscriptions/[SubID]/resourceGroups/[RGName]/providers/Microsoft.AzureStack/registrations/<RegName>/products/[productName][tag]
> 
> so this item can then be downloaded to Azure Stack Hub via the "Add from Azure" in the portal, or  Select-AzsMarketplaceItem tool.

**Comment by vrajasekaran1** [comment]
Hi @TheOnlyWei,

Azure marketplace items can be pushed to the Azure stack hub marketplace on request from the publisher of the product (assuming that type of product is supported on the Hub marketplace). 

The process of pushing the product to Hub is manual and requires a pm in the product group to publish the item themselves. Please note that any items pushed to Hub are first whitelisted to the owner of the item for testing, once everything has been tested the item is published publicly.

Please send me an [email](mailto:vrajasekaran@microsoft.com) if you have an ISV that would like their product pushed to Hub marketplace.

**Comment by sethmanheim** [comment]
Thank you @vrajasekaran1! Closing this issue for now. @TheOnlyWei Please follow up with any other questions. #please-close
