### ISSUE TITLE
Failed to open "complete a survey" form

### ISSUE THREAD

**Issue by Lihailian** [MicrosoftDocs/azure-stack-docs#1795]
HI Team,

Seems the form is in below statement is not exists anymore, could anyone help to check and fix the issue please? Thanks!
+++
Red Hat Enterprise Linux Images are a private offering on Azure Stack Hub. To make this offering available to your Marketplace Management tab, you will need to **complete a survey**. After you post the survey, it takes seven business days to see it in your Add from Azure tab within Marketplace Management.
+++
Regards,
Hailian Li

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc31e147-b01d-ab0d-f97a-14ace2d658a8
* Version Independent ID: 351862a1-a03f-61dd-e619-3af6562870ac
* Content: [Offer a Red Hat-based virtual machine for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-redhat-create-upload-vhd?view=azs-2108)
* Content Source: [azure-stack/operator/azure-stack-redhat-create-upload-vhd.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-redhat-create-upload-vhd.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@Lihailian 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
#please-close

**Comment by alexsmithMSFT** [comment]
The survey link is back online- https://forms.office.com/r/F10XvmPLVw
