### ISSUE TITLE
SQL RP compatibility with 1902 update

### ISSUE THREAD

**Issue by rfsonders** [MicrosoftDocs/azure-stack-docs#18]
[Enter feedback here]
Hello.
The current latest SQL RP requires:
Use-AzureRmProfile -Profile 2018-03-01-hybrid 
Install-Module  -Name AzureStack -RequiredVersion 1.5.0 

The core Azure Stack 1902 release requires:
Install-Module AzureRM -RequiredVersion 2.4.0
Install-Module -Name AzureStack -RequiredVersion 1.7.0

Please advise when a new SQL RP will be made available for the 1902 build.

Here is the error:
Azure Powershell Module with 2.4.0 version found. Need Azure powershell compatible with stack. Use ArmProfile 2018-03-01-hybrid. Please uninstall the current version and rerun the RP setup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31804a1d-4c4f-70e6-556c-66c533e9b3e3
* Version Independent ID: cbdb8c6f-ad4d-9e3d-a490-f1348b5ccdfa
* Content: [Using SQL databases on Azure Stack](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-sql-resource-provider-deploy#feedback)
* Content Source: [articles/azure-stack/azure-stack-sql-resource-provider-deploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-sql-resource-provider-deploy.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by mattbriggs** [comment]
@rfsonders I'm following up on some issues. I wanted to find out if this was still an issue? Thanks, Matt #in-progress

**Comment by xiaofmao** [comment]
Thanks for feedback! @rfsonders 
The online document is correct. SQL/MySQL RPs do version check at the beginning of installation. The later released version of PowerShell profile/module may include some breaking changes which could cause the deployment failure of database RPs.
In future release of SQL/MySQL RP, it would support the latest version of PowerShell profile then. But for the current released versions of RPs, user need to install the required versions of profile and module.
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-deploy#deploy-the-sql-resource-provider-using-a-custom-script

**Comment by mattbriggs** [comment]
@rfsonders Thanks again. Can you let me know if you have any additional questions. #please-close

**Comment by MatthewAt3Sharp** [comment]
Hey guys, this appears to still be an issue. whats the ETA here?
