### ISSUE TITLE
Should document how to remove app registration

### ISSUE THREAD

**Issue by TheOnlyWei** [MicrosoftDocs/azure-stack-docs#1802]
The page should document how to remove app registration for AAD, not just ADFS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 193ec77a-b7dc-7807-cb42-fb1c8ad4a3c7
* Version Independent ID: 389dc440-613b-88ad-c1e9-e4b6fe6db8c6
* Content: [Give an app access to Azure Stack Hub resources - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/give-app-access-to-resources?view=azs-2108&tabs=az1%2Caz2&pivots=state-connected#manage-an-azure-ad-app)
* Content Source: [azure-stack/operator/give-app-access-to-resources.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/give-app-access-to-resources.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by kobulloc-MSFT** [comment]
@TheOnlyWei Thank you for your feedback!  This has been assigned to the document author for further review.

**Comment by BryanLa** [comment]
Links have been added to the "Manage and Azure AD app" section for additional operations, including how to remove an app registration. These will go live around 3pm Pacific today.

#please-close
