### ISSUE TITLE
Broken link to Azure functions on Stack HCI

### ISSUE THREAD

**Issue by MrCNeale** [MicrosoftDocs/azure-stack-docs#1807]
Broken link

Tried to access
https://docs.microsoft.com/en-us/azure/app-service/overview-arc-integration.md
and got a "page not found".
Was looking for Function apps on stack-hci

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9a6344-b950-e72f-ec2e-bdbbe9ea1c07
* Version Independent ID: 9b22c6e4-0af5-9958-7e3a-429ce14f20ea
* Content: [What's new in Azure Stack HCI, version 21H2 - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/whats-new)
* Content Source: [azure-stack/hci/whats-new.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/whats-new.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by ManikaDhiman** [comment]
@MrCNeale Thanks for the feedback. Broken links are now fixed. Links should work fine after the next publishing pass. Thanks!

**Comment by ManikaDhiman** [comment]
#please-close

**Comment by ManikaDhiman** [comment]
Hi @AjayKumar-MSFT: This issue is already fixed and closed. Any reason why it's assigned to the author again? Thanks!

**Comment by AjayKumar-MSFT** [comment]
> Hi @AjayKumar-MSFT: This issue is already fixed and closed. Any reason why it's assigned to the author again? Thanks!

@ManikaDhiman, Just for the triage completion, the appropriate labels' are added. There is no action item for you. Thanks!
