### ISSUE TITLE
The import section is unclear. 

### ISSUE THREAD

**Issue by jamesorlando** [MicrosoftDocs/azure-stack-docs#1810]
When you download an offline package, it does not match the folder structure listed in the example. 

The example has the parent folder of microsoft.custom-script-linux-arm-2.0.3 and then an icons subfolder, plus a .json, .azpkg, .txt and .zip files. When I download something such as the DSC extension, I get the parent folder of microsoft.dsc-arm.2.77.0.0 and three subfolders (extension, gallerypackage, icons) plus one json file. 

Additionally, when you go to run the import, if you run import-azsmarketplaceitem -repositorydir "c:\temp\microsoft.dsc-arm-2.77.0" you will get an error that says the productdetails.json cannot be found in the extensions folder. If you copy the json into that folder, you get the same error for the gallerypackage folder, if you then copy the json into that folder, you get the same error for the icons folder. 

The fix is to create a subfolder of microsoft.dsc-arm.2.77.0.0 in the microsoft.dsc-arm.2.77.0.0 folder. 
So, in my example I end up with a folder of c:\temp\microsoft.dsc-arm-2.77.0\microsoft.dsc-arm-2.77.0 and then run the import-azsmarketplaceitem -repositorydir "c:\temp\microsoft.dsc-arm-2.77.0" command to get the import to complete successfully. 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5a0e40a-4042-9935-0f59-37eb87ec478e
* Version Independent ID: 81e5de2b-da67-e875-405d-65628be05adc
* Content: [Download marketplace items from Azure and publish to Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-download-azure-marketplace-item?view=azs-2108&tabs=az1%2Caz2&pivots=state-disconnected#import-the-download-and-publish-to-azure-stack-hub-marketplace-using-powershell)
* Content Source: [azure-stack/operator/azure-stack-download-azure-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-download-azure-marketplace-item.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@jamesorlando 
Thanks for your Question! We are currently investigating and will get back on this.

**Comment by VikasPullagura-MSFT** [comment]
@jamesorlando I shared this feedback to the Doc author and this is taken to the product team for further investigation.
The document will be updated accordingly post confirmation from the Product Team.

**Comment by jdrowne** [comment]
@VikasPullagura-MSFT we are running into this same exact issue and cannot move forward with the import. Can you please keep this ticket open? This is blocking us.

**Comment by sethmanheim** [comment]
@VikasPullagura-MSFT Please re-open this issue and I will escalate with the PM team. #please-open

**Comment by jdrowne** [comment]
@VikasPullagura-MSFT @sethmanheim confirmed the proposed solution by @jamesorlando works.

Here's the actual process:

1. Copy the name of the folder. Say, microsoft.dsc-arm-2.77.0
2. Create a folder named that way.
3. Move the downloaded folder to that folder. Now you have C:\microsoft.dsc-arm-2.77.0\microsoft.dsc-arm-2.77.0\original-sub-folders-are-here and C:\microsoft.dsc-arm-2.77.0\microsoft.dsc-arm-2.77.0\productDetails.json
4. import-azsmarketplaceitem -repositorydir "C:\microsoft.dsc-arm-2.77.0"

**Comment by sethmanheim** [comment]
OK thank you @jdrowne. Are you saying you're no longer blocked? Maybe we just need to update the documentation, no escalation necessary.

**Comment by jdrowne** [comment]
@sethmanheim correct, no longer blocked.

**Comment by VikasPullagura-MSFT** [comment]
@jdrowne Thanks for confirming that this is resolved.

**Comment by sethmanheim** [comment]
@jdrowne I incorporated your clarifying steps and the updates should be live today after 3 PM PST. Thank you again for the feedback! #please-close

@jamesorlando
