### ISSUE TITLE
Add-AzStackHCIAttestation doesn't exist.

### ISSUE THREAD

**Issue by kongou-ae** [MicrosoftDocs/azure-stack-docs#1821]
Hi,

This document uses "Add-AzStackHCIAttestation". But this command doesn't exist as follows.

```
PS C:\Program Files\AzureConnectedMachineAgent> Add-AzStackHCIAttestation
Add-AzStackHCIAttestation : The term 'Add-AzStackHCIAttestation' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ Add-AzStackHCIAttestation
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Add-AzStackHCIAttestation:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
---
```

And the document of this module doesn't explain this command.

https://docs.microsoft.com/en-us/powershell/module/az.stackhci/?view=azps-7.1.0

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c98d186-ef81-48f0-7e70-301b3ad92f09
* Version Independent ID: 8552ac82-b862-f27d-e8df-5e4a8612d9ea
* Content: [Azure Benefits on Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-benefits#feedback)
* Content Source: [azure-stack/hci/manage/azure-benefits.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/azure-benefits.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@kongou-ae 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@VikasPullagura-MSFT Thank you for catching that -- I am checking with the PM team about this.

**Comment by sethmanheim** [comment]
@kongou-ae Sorry for the delay -- I finally got confirmation that the correct command should be `Add-AzStackHCIVMAttestation -AddAll`. I will update the article, thank you again for the report. #please-close
