### ISSUE TITLE
Clarify if AKS supports ADFS & Disconnected ASH Deployments - single tenant environments

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/azure-stack-docs#1823]
Azure Doc states `To install, you will need to have the VM extensions, the AKS base image, a plan and offer to your users, and **enable multi-tenancy for your Azure Stack Hub**. AKS clusters can only be created in the user environment.`

Disconnected environments and ADFS enabled ASH deployments only support a single tenant.

Please consider clarifying if AKS supports environments that are disconnected or not multi-tenant. 

The Azure doc gives guidance in a few areas about disconnected environments as it relates to downloading marketplace items which gives an impression disconnected is supported.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4871e496-b684-ea5f-b579-50774bb9ffb4
* Version Independent ID: b683dc6a-864d-9932-11da-3335d2597cb7
* Content: [Install and offer the Azure Kubernetes Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/aks-add-on?view=azs-2108)
* Content Source: [azure-stack/operator/aks-add-on.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/aks-add-on.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by vipulsparsh** [comment]
@CHDAFNI-MSFT Thanks for reaching out. We will investigate and update the thread accordingly.

**Comment by mattbriggs** [comment]
@CHDAFNI-MSFT Thanks for your feedback. The following answer is in the FAQ for AKS on Azure Stack Hub:
https://docs.microsoft.com/en-us/azure-stack/user/aks-known-issues?view=azs-2108#can-i-use-azure-ad-or-ad-fs-integrated-with-my-aks-clusters

Thanks!
Matt

@please-close
