### ISSUE TITLE
Missprint in command

### ISSUE THREAD

**Issue by AmoorG** [MicrosoftDocs/azure-stack-docs#1829]
I think some commands needs to be modified as it was mentioned incorrectly
- in Section 5.1 , the 3rd PowerShell command it supposed to be Get-ClusterFaultDomain -CimSession "ClusterS1" not New-ClusterFaultDomain -CimSession "ClusterS1".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df3012c4-22e5-004d-da6f-60744f2cfb4f
* Version Independent ID: 57e21edd-9a2b-f1ca-2ff7-48e3da5dc260
* Content: [Create an Azure Stack HCI cluster using Windows PowerShell - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell)
* Content Source: [azure-stack/hci/deploy/create-cluster-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/create-cluster-powershell.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @v-dasis
* Microsoft Alias: **v-dasis**

**Comment by PriyankaRudramaina** [comment]
Hello @AmoorG,

Thank you for bringing this to our attention. Your feedback is being reviewed, we shall take an appropriate action towards the correction required in the document [https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell](url)

**Comment by PriyankaRudramaina** [comment]
Hello @AmoorG,

I have made the necessary changes in the document and the changes are being reflected now. Please check and get back in case of any further queries.

**Comment by AmoorG** [comment]
Thank you .. fixed 😊

Best Regards,
Omar Ghazal
