### ISSUE TITLE
Azure Functions features which not available in Azure Stack

### ISSUE THREAD

**Issue by abhijitkakade914** [MicrosoftDocs/azure-stack-docs#183]
Team ,  We are looking for details document related to Azure Functions in Azure Stack. as you mentioned above  "However, some features are disabled in Azure Stack. The Azure-specific expectations or services that those features require are not currently available in Azure Stack"

Can you please let us know details on which features of Azure Functions and App services not currently available in Azure stack. For now its very important for us to know and understand it in detail. Please provide related links and documents. Awaiting for your response. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee9022e-5af6-93f0-8910-2200485917d1
* Version Independent ID: 25cea13d-78f7-e51b-acb0-582e71c14684
* Content: [App Service on Azure Stack overview](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-overview#feedback)
* Content Source: [azure-stack/operator/azure-stack-app-service-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-overview.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@abhijitkakade914 I do not believe such a document exists. If you can outline your exact asks I would be happy to follow up and get the information for you.

**Comment by cenkersoy** [comment]
With other services on Azure Stack, we have documentation pages that mentions "considerations" or "limitations". Examples are below. We need a similar one for App Services. 
•	Networking: https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-network-differences 
•	Managed Disks: https://docs.microsoft.com/en-gb/azure/azure-stack/user/azure-stack-managed-disk-considerations 
•	Storage: https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-acs-differences
•	Virtual Machines: https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-vm-considerations 
•	Using Services or Building Apps: https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-considerations 
•	SQL Server VM: https://docs.microsoft.com/en-gb/azure-stack/user/azure-stack-sql-server-vm-considerations 
Thanks
Cenk Ersoy (cenker@microsoft.com)

**Comment by TravisCragg-MSFT** [comment]
@abhijitkakade914 We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by apwestgarth** [comment]
Hi, I'm the PM for Azure App Service and Azure Functions on Azure Stack, we do not publish a list of features which are/aren't enabled per region/cloud (i.e. Public, National or Hybrid).

From a high level we support Azure Functions runtime 1.x on Azure Stack, in terms of Azure App Service we do not offer App Service Linux or App Service Environments.  Below those top level items there is a high proportion of feature completeness with Azure however key features such as VNET Integration and Autoscaling are not supported today.  Hope this helps?

**Comment by ashrafelsheikh** [comment]
hi, i need to find a deployment guide to enable Azure functions in Azure Stack Hub

**Comment by BryanLa** [comment]
@ashrafelsheikh - you'll need to [install the App Service on Azure Stack Hub resource provider](https://docs.microsoft.com/azure-stack/operator/azure-stack-app-service-overview?view=azs-2002) first. This is an administrator function. Once installed, you can [create an offer](https://docs.microsoft.com/azure-stack/operator/tutorial-offer-services?view=azs-2002) that includes App Services, to which your users can subscribe. HTH.
