### ISSUE TITLE
Correction in the path mentioned under validation

### ISSUE THREAD

**Issue by nairsrijith** [MicrosoftDocs/azure-stack-docs#1832]
Under the section "Validate the ACR certificate" path mentioned in step 1 and 2 should not have leading \
`\$ENV:USERPROFILE\Documents\AzureStack` should instead be `$ENV:USERPROFILE\Documents\AzureStack`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d79b488c-7ac2-a18e-014f-cf57f1139f36
* Version Independent ID: 91409569-7446-0124-d838-8ea126092b80
* Content: [Install Azure Container Registry on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/container-registries-install?view=azs-2108)
* Content Source: [azure-stack/operator/container-registries-install.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/container-registries-install.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by kobulloc-MSFT** [comment]
@nairsrijith Thank you for bringing this to our attention!  We'll review the documentation and get back to you shortly.

**Comment by mattbriggs** [comment]
@kobulloc-MSFT Thanks! #in-progress

**Comment by mattbriggs** [comment]
PR committed.

#please-close
