### ISSUE TITLE
Wrong PS Command-Line

### ISSUE THREAD

**Issue by eszych** [MicrosoftDocs/azure-stack-docs#1836]
[Enter feedback here]
Line should read
((Get-NetIPConfiguration).DNSServer | ?{ $_.AddressFamily -ne 23}).ServerAddresses

Missing "(" and ")"!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2058b8-318d-da2b-6dc7-04d4b3dffc9e
* Version Independent ID: 0e997ca9-22fa-19c3-a5d3-71fe840843fc
* Content: [Troubleshoot known issues and errors when installing Azure Kubernetes Service on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues-installation)
* Content Source: [azure-stack/aks-hci/known-issues-installation.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/known-issues-installation.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by shashishailaj** [comment]
@eszych Thank you for your inputs . We will investigate and update the thread.

**Comment by mattbriggs** [comment]
@eszych Great! Thanks for your feedback.

Updated. Will be in the next build.

#please-close
