### ISSUE TITLE
Deploying the SQL Servers via https://adminportal.<region>.<FQDN> is NOT supported

### ISSUE THREAD

**Issue by dmc-tech** [MicrosoftDocs/azure-stack-docs#184]
In the tutorial, you infer that for integrated systems, the SQL HA template should be deployed to the Default Provider Subscription.  This is only allowed for ASDK.  The servers must be deployed to a user/tenant subscription:

https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-hosting-servers

Please clarify as it is confusing for customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dba4334-9944-ca79-a90b-caa1dfd51c5d
* Version Independent ID: 34371eae-05f5-9cd1-5339-50ff51445761
* Content: [Offer highly available SQL databases in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-tutorial-sql)
* Content Source: [azure-stack/operator/azure-stack-tutorial-sql.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-tutorial-sql.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TravisCragg-MSFT** [comment]
@dmc-tech Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@sethmanheim

**Comment by sethmanheim** [comment]
Hi @TravisCragg-MSFT, can you please assign this issue to me? Thanks!

**Comment by sethmanheim** [comment]
Please let us know if this is still an issue, and if so we will reopen the item. Thank you! #please-close
