### ISSUE TITLE
Update the section on creating an identity

### ISSUE THREAD

**Issue by cybersmithio** [MicrosoftDocs/azure-stack-docs#1840]
The command in the section Create an identity on Azure for retrieving the client ID will not work.

The example given is: az ad sp show --id http://secrets-store-test --query 'appId' -otsv

According to https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-show the value of --id would not work in this instance.   "az ad sp list" might be an option to get the client  ID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48500978-a4c7-4fd8-2c5a-3fca53607600
* Version Independent ID: d87865b6-266a-a2fb-631a-d7f66b62e304
* Content: [Kubernetes Secrets Store CSI Driver integration with AKS on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/secrets-store-csi-driver)
* Content Source: [azure-stack/aks-hci/secrets-store-csi-driver.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/secrets-store-csi-driver.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@cybersmithio Thanks for your feedback. We will update shortly.

#in-progress

**Comment by VikasPullagura-MSFT** [comment]
@cybersmithio 
Thanks for the feedback! 
As @mattbriggs the document update is in-progress.

**Comment by mattbriggs** [comment]
Updated.

#please-close
