### ISSUE TITLE
Incorrect command system for kubectl exec

### ISSUE THREAD

**Issue by cybersmithio** [MicrosoftDocs/azure-stack-docs#1842]
In the section "Validate the Secrets Store deployment" it shows the incorrect command:
kubectl exec busybox-secrets-store-inline -- ls /mnt/secrets-store/ --namespace kube-system

After the double hyphen everything must be part of the command to execute in the pod, so the "--namespace kube-system" needs to be before that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48500978-a4c7-4fd8-2c5a-3fca53607600
* Version Independent ID: d87865b6-266a-a2fb-631a-d7f66b62e304
* Content: [Kubernetes Secrets Store CSI Driver integration with AKS on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/secrets-store-csi-driver)
* Content Source: [azure-stack/aks-hci/secrets-store-csi-driver.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/secrets-store-csi-driver.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by VikasPullagura-MSFT** [comment]
@cybersmithio Thanks for the Feedback. We will check and update the document accordingly.

**Comment by VikasPullagura-MSFT** [comment]
@mattbriggs Can you please check and add your comments on this doc update request as applicable.

**Comment by mattbriggs** [comment]
@cybersmithio Thanks for your comment. Updated.

#please-close
