### ISSUE TITLE
Please update production limits as new max # nodes

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/azure-stack-docs#1843]
Please update production limits as new max # nodes, info here is outdated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425ddc25-2a4b-c529-9d8c-b9e6975cfd1c
* Version Independent ID: 818658d6-3f73-7a88-93af-81018f971676
* Content: [Azure Kubernetes Service on Azure Stack HCI requirements - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/system-requirements)
* Content Source: [azure-stack/aks-hci/system-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/system-requirements.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by VikasPullagura-MSFT** [comment]
@carlosmayol 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@mattbriggs 
Can you please check and add your comments on this doc update request as applicable.

**Comment by mattbriggs** [comment]
@carlosmayol Thanks! Content has been reviewed and updated.

https://docs.microsoft.com/en-us/azure-stack/aks-hci/system-requirements#review-maximum-supported-hardware-specifications
https://docs.microsoft.com/en-us/azure-stack/aks-hci/concepts-support

Thanks for your note!

#please-close
