### ISSUE TITLE
D-series missing even in pages for older stamp

### ISSUE THREAD

**Issue by ecaha** [MicrosoftDocs/azure-stack-docs#1848]
Some update of the page removed the table for older D-series VMs. It was there (D1-D6) and now it is missing even for older AzS Hub versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab1df1a4-dba7-3a66-dce4-88028f9b663d
* Version Independent ID: 3f33cd0e-cb7f-87e8-f201-872148031f4d
* Content: [VM sizes supported in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vm-sizes?view=azs-2108)
* Content Source: [azure-stack/user/azure-stack-vm-sizes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-vm-sizes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by ecaha** [comment]
Found commit mattbriggs@6cd86e61a6ceea6e7982ce1225160a30bae39b23, which removed a bunch of VM sizes even for old stacks versions. Is there a particular reason? We still reference these sizes at: [azure-stack/user/azure-stack-vm-considerations.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-vm-considerations.md)

**Comment by PriyankaRudramaina** [comment]
Hello @ecaha,

Thanks for the feedback. We will review the content and take appropriate action.

**Comment by PriyankaRudramaina** [comment]
@ecaha 

I am reviewing this internally, will update here once i have more details.

**Comment by mattbriggs** [comment]
@ecaha @BryanLa  I was working with Neil Bird and Thomas Reottinger. However, there was some confusion at the time in Neil's PR. It is possible they approved of the update not aware the content was removed. The source for which sizes are available should be a stamp of those older versions. Sorry for confusion, and thank you for raising this issue.

**Comment by PriyankaRudramaina** [comment]
Hi @ecaha @mattbriggs,

I am assiging this to content author @BryanLa, please help to get this document corrected

**Comment by sethmanheim** [comment]
Please see the comment from Matt Briggs.
