### ISSUE TITLE
Azure Container Registry missing networking info?

### ISSUE THREAD

**Issue by ryanewillis** [MicrosoftDocs/azure-stack-docs#1857]
ACR created on Azure Stack Hub per instructions, login server is FQDN, does not seem to fully bake all DNS needed? Is there additional doc to figure out what is missing?

azureuser@K8Test1:~$ docker login http://test01.azsacr.ourdomain/v2/
Username: test01
Password: xxxxxx
Error response from daemon: Get "http://test01.azsacr.ourdomain/v2/": dial tcp: lookup [test01.azsacr.engctc.ourdomain.com](http://test01.azsacr.ourdomain/v2/): no such host
azureuser@K8Test1:~$ Error response from daemon: Get "http://test01.azsacr.ourdomain/v2//v2/": dial tcp: lookup (http://test01.azsacr.ourdomain/v2/): no such host
Error: command not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cba7249-7020-c34d-b429-98d1953c5434
* Version Independent ID: 6fa9bff7-347a-176d-427c-a24b39406d97
* Content: [Azure Container Registries on Azure Stack Hub overview - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/container-registry-overview?view=azs-2108)
* Content Source: [azure-stack/user/container-registry-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/container-registry-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by MartinJaffer-MSFT** [comment]
Thank you for your detailed feedback.  We are looking into the issue, and we will respond when we have more information.

**Comment by VikasPullagura-MSFT** [comment]
@mattbriggs Can you please check and help on this query.

**Comment by mattbriggs** [comment]
@ryanewillis According to the team, there are no additional steps needed to set up DNS. ACR installation should take care of all DNS setup. 

You may want to double-check that you didn't mistype the login server. You can use the command below to get the exact name of the login server with Azure CLI. And make a GET request using curl:

```azurecli
loginServer=$(az acr show -n test01 --query loginServer -o tsv)
curl -v [https://${loginServer}/v2/](https://%24%7Bloginserver%7D/v2/)
```

If you get a 401 error then DNS is working fine, and you can try logging in with Docker. If you are still getting a “no such host” error, even with the exact login server as returned by the CLI, then contact Microsoft support (CSS) and start log collection. Support can work with you from there to resolve the issue. If you haven't worked with support before with your Azure Stack Hub, you may want to contact your cloud operator.

**Comment by chappleg** [comment]
I think the formatting got messed up on that curl command. It should be this:

``` bash
loginServer=$(az acr show -n test01 --query loginServer -o tsv)
curl -v "https://${loginServer}/v2/"
```

**Comment by mattbriggs** [comment]
@chappleg Thanks.

**Comment by ryanewillis** [comment]
ACR login server name is correct, I am operator of the stack as well, I will contact support. thanks!
