### ISSUE TITLE
User to request VM console access - Add 'Az' command section

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/azure-stack-docs#1862]
Section 'User to request VM console access' only reflects the AzureRM module. Please consider including the Az module which is already reflected earlier in the document under 'Operator enables a user subscription for EVA'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221ace5c-e2df-f784-d570-a39563c13a8d
* Version Independent ID: 38a14acb-21f5-5378-6ece-50e89e437025
* Content: [Emergency VM access in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/emergency-vm-access?view=azs-2108&tabs=azurerm1)
* Content Source: [azure-stack/user/emergency-vm-access.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/emergency-vm-access.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by PriyankaRudramaina** [comment]
Hello @CHDAFNI-MSFT,

Thank you for bringing this to our attention. Your feedback is under review, we shall update the document shortly.

**Comment by PriyankaRudramaina** [comment]
Hello @CHDAFNI-MSFT,

I have updated the document with az cmdlet "Invoke-AzResourceAction" at [https://review.docs.microsoft.com/en-us/azure-stack/user/emergency-vm-access?view=azs-1802&branch=pr-en-us-9370&tabs=azurerm1#user-to-request-vm-console-access](url)
![image](https://user-images.githubusercontent.com/95755055/153165252-e03d46d3-e655-41ad-89b5-6d2e47380a5f.png)
