### ISSUE TITLE
Proxy-Address should be a string

### ISSUE THREAD

**Issue by eszych** [MicrosoftDocs/azure-stack-docs#1864]
[Enter feedback here]

In the description of the command a <String> is expected for the parameters
New-AksHciProxySetting -name <String>
                       -http <String>
                       -https <String>
                       -noProxy <String>
But in the examples the parameters for "http", "https" and "noproxy" are not in a string format:
$proxySetting=New-AksHciProxySetting -name "corpProxy" -http http://contosoproxy:8080 -https https://contosoproxy:8443 -noProxy localhost,127.0.0.1,.svc,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16 

Running this example leads to an error "Cannot convert value to System.String"
When the above example is changed to 
$proxySetting=New-AksHciProxySetting -name "corpProxy" -http "http://contosoproxy:8080" -https "https://contosoproxy:8443" -noProxy "localhost,127.0.0.1,.svc,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
no error is thrown and the proxy setting is accepted.

This should be changed in all examples on the page...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f0ee2ee-3726-8de5-f362-4b2cb086cb16
* Version Independent ID: d94e1f9a-cb07-fef3-12e8-1d578c68fb70
* Content: [New-AksHciProxySetting for AKS on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/reference/ps/new-akshciproxysetting)
* Content Source: [azure-stack/aks-hci/reference/ps/new-akshciproxysetting.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/reference/ps/new-akshciproxysetting.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by VikasPullagura-MSFT** [comment]
@eszych 
Thanks for the feedback! We will check and update the document accordingly.

**Comment by VikasPullagura-MSFT** [comment]
@mattbriggs 
Can you please check and add your comments on this doc update request as applicable.

**Comment by mattbriggs** [comment]
@eszych Thanks for this detailed note. I will check and update.

#in-progress

**Comment by mattbriggs** [comment]
updated.

#please-close
