### ISSUE TITLE
Code block markdown typo under "To send diagnostic logs for Event Hubs:" section.

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1870]
There's a code block markdown syntax issue under "To send diagnostic logs for Event Hubs:" section, which looks like:

```
To send diagnostic logs for Event Hubs:

```powershell
Send-AzureStackDiagnosticLog -FilterByResourceProvider eventhub

```
Probably need to close the code block, and make sure the preceding text isn't included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29690f5d-25bc-84d2-6b9c-8e5d83f0162b
* Version Independent ID: bcc274b8-41fa-66e4-8cb1-50a5aee662e4
* Content: [Diagnostic log collection - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/diagnostic-log-collection?view=azs-2108)
* Content Source: [azure-stack/operator/diagnostic-log-collection.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/diagnostic-log-collection.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by kobulloc-MSFT** [comment]
@alexsmithMSFT Thank you for bringing this to our attention!  I'll get a PR out to address this.

**Comment by kobulloc-MSFT** [comment]
Code block in question:

![image](https://user-images.githubusercontent.com/37556655/153643906-aa59cab8-8401-431b-8170-7fc25c07a4dd.png)
