### ISSUE TITLE
Fast, offline update references SERVICES.MSC despite that not being a thing in Azure Stack HCI / Core

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/azure-stack-docs#1875]
This does not make sense for ASHCI management. Docs should be updated with references to Powershell (half the doc is already doing this; unsure why the flip-flop between GUI and Powershell)?

![image](https://user-images.githubusercontent.com/503974/154154545-c98f1b3a-d9b0-4ca9-81b0-845b9488e564.png)

URL:
https://docs.microsoft.com/en-us/azure-stack/hci/manage/update-cluster#perform-a-fast-offline-update-of-all-servers-in-a-cluster

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64880e71-5de3-4b72-bcbf-1eb6d9dbfced
* Version Independent ID: db618f0c-c803-7fc0-91e9-2b77a6543ebf
* Content: [Update Azure Stack HCI clusters - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/update-cluster#perform-a-fast-offline-update-of-all-servers-in-a-cluster)
* Content Source: [azure-stack/hci/manage/update-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/update-cluster.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by kobulloc-MSFT** [comment]
@eponerine Thank you for your feedback!  We've assigned this to the document author for further review.

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by eponerine** [comment]
Please keep this open. There is no reason to close the issue just because no one has reviewed the doc.

The problem is it's referring to `services.msc`, a GUI tool that does not exist on Windows Server Core or Azure Stack HCI.

Simply update the following: 

1. Line 4 to `Set-Service -Name ClusSvc -StartupType Disabled` 
2. Line 7 to `Set-Service -Name ClusSvc -StartupType Automatic` 

This would make more sense, especially since every other line is using PowerShell.
