### ISSUE TITLE
Instructions for creating parentdisk for AzureACI seems to be incorrect.

### ISSUE THREAD

**Issue by mhocso** [MicrosoftDocs/azure-stack-docs#1876]
The step for creating the ACI parent disk does not work or is described incorrectly.

Download the [Convert-WindowsImage.ps1 function](https://raw.githubusercontent.com/microsoft/MSLab/master/Tools/Convert-WindowsImage.ps1) to the C:\Lab\wslab_xxx\ParentDisks folder as CreateParentDisk.ps1. Then run CreateParentDisk.ps1 as administrator. Choose the Azure Stack HCI ISO from C:\Labs\Isos, and accept the default name and size.

When running that script it does not ask for an iso file it just does nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 997dd27c-a77c-76ca-fd9a-b411c7155b9e
* Version Independent ID: 304722a4-5966-0e19-53db-39555b07c8d2
* Content: [Tutorial on creating a private forest environment and virtual machines for an Azure Stack HCI cluster - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/tutorial-private-forest)
* Content Source: [azure-stack/hci/deploy/tutorial-private-forest.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/tutorial-private-forest.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by VikasPullagura-MSFT** [comment]
@mhocso 
Thanks for the feedback! We are currently investigating and will get back on this.

**Comment by VikasPullagura-MSFT** [comment]
@JasonGerend 
Can you please check and add your comments on this issue as applicable.

**Comment by PriyankaRudramaina** [comment]
Hello @JasonGerend,

Could you please review this thread and add your comments.

**Comment by VikasPullagura-MSFT** [comment]
@mhocso 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@JasonGerend 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sawneil** [comment]
Is there any  update on this. I tried deploying and same issue. the parentdisk creation doesnt do anything.

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by alkohli** [comment]
Closing this issue. #please-close
