### ISSUE TITLE
Minor adjustments

### ISSUE THREAD

**Issue by Jayes90** [MicrosoftDocs/azure-stack-docs#1879]
Swap line 120 and 136
AzureRM and Az commands wrongly placed.

Remove extra space at end of line 139 and 140, if not the chunk of commands will break during copy/paste.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221ace5c-e2df-f784-d570-a39563c13a8d
* Version Independent ID: 38a14acb-21f5-5378-6ece-50e89e437025
* Content: [Emergency VM access in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/emergency-vm-access?view=azs-2108&tabs=azurerm1)
* Content Source: [azure-stack/user/emergency-vm-access.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/emergency-vm-access.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@Jayes90 Thank you for catching that -- I've submitted a PR to fix this, should be live after 10 AM PST. #please-close
