### ISSUE TITLE
Azure Resource Manager Endpoint Metadata missing loginEndgraphEndpointpoint

### ISSUE THREAD

**Issue by SqlTechMike** [MicrosoftDocs/azure-stack-docs#188]
When retrieving the endpoint metadata for an Integrated System running 1905, there is no loginEndgraphEndpointpoint property in the JSON.  The only properties that are returned are
- galleryEndpoint
- graphEndpoint
- portalEndpoint
- authentication
    - loginEndpoint
    - audiences

When I use the graphEndpoint value for the activeDirectoryResourceId I can save the file and login, but the Extension shows the following message under App Service: 

Error: The access token has been obtained for the wrong audience or resource 'https://graph.windows/net/'.  It should exactly match with one of the allowed audiences '{Audience URI}'.

When I use the audiences value for the activeDirectoryResourceId I get the following message when trying to log in:

Visual Studio Code  
An error occurred while signing in: 
AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: aebc6443-996d-45c2-90f0-388ff96faa56(Visual Studio Code). Resource value from request: {Audience URI}. Resource app ID: 052c2b1c-afba-4985-a4f2-842432c36269. List of valid resources from app registration: . Trace ID: d04cd65e-41f9-484d-a48e-cdee819fe900 Correlation ID: 88ae3661-3b06-49e1-b917-6c94cec779b3 Timestamp: 2019-06-21 19:01:28Z

It seems like the audience URI is the correct value to use, but the must be an additional step missing from the instructions.

Environment Information:
4-Node Integrated System
Microsoft Build 1.1905.0.40
Identity Provider Azure Active Directory
AAD Tenant is different from Registration Tenant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d8803f5-7736-6a29-98df-69c121d43c95
* Version Independent ID: d88f693f-cade-48ee-df03-d2363298ef0d
* Content: [Connect to Azure Stack using Azure Account Extension in Visual Studio Code](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-dev-start-vscode-azure#feedback)
* Content Source: [azure-stack/user/azure-stack-dev-start-vscode-azure.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-dev-start-vscode-azure.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@SqlTechMike Thanks for the feedback. I am reaching out about this issue, and will get back to you as soon as I have more information.

**Comment by mattbriggs** [comment]
@SqlTechMike Thanks for your feedback! We will have an update for the topic posted shortly. #in-progress

**Comment by TravisCragg-MSFT** [comment]
@SqlTechMike you will need to register your VS code application ID by [updating the Azure Stack AAD Home Directory](https://github.com/Azure/AzureStack-Tools/tree/master/Identity#updating-the-azure-stack-aad-home-directory-after-installing-updates-or-new-resource-providers). 

Try running those 3 PowerShell lines and then see if this still does not give the proper output.

**Comment by mattbriggs** [comment]
@SqlTechMike We've updated the topic. Hopefully it will resolve your issue. It should be available later this afternoon. Travis has summarized the gist of the update to the article. Thanks again for leaving feedback. 

#please-close

**Comment by SqlTechMike** [comment]
Thank you, running the PowerShell created the missing application registrations and the connection from Visual Studio Code now works properly.
