### ISSUE TITLE
Update Windows server version in the page

### ISSUE THREAD

**Issue by carlosmayol** [MicrosoftDocs/azure-stack-docs#1880]
can we please update this page with the latest validated windows server version (2022)

thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425ddc25-2a4b-c529-9d8c-b9e6975cfd1c
* Version Independent ID: 818658d6-3f73-7a88-93af-81018f971676
* Content: [Azure Kubernetes Service on Azure Stack HCI requirements - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/system-requirements)
* Content Source: [azure-stack/aks-hci/system-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/system-requirements.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
Updated. Thanks!
https://docs.microsoft.com/en-us/azure-stack/aks-hci/system-requirements?tabs=allow-table

#please-close
