### ISSUE TITLE
Would it be possible to provide any update about this topic?

### ISSUE THREAD

**Issue by IvanNaumeiko** [MicrosoftDocs/azure-stack-docs#1884]
Hello,

Would it be possible to provide any update here?
This issue in service is a real blocker for my company.
Many thanks.

Ivan.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b51ac2d-86d8-1c65-3fb9-c2e00b465d23
* Version Independent ID: 0fa7135a-e7da-a9b4-d238-0e49a4c18a68
* Content: [Set up multiple administrators on Azure Kubernetes Service (AKS) on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/set-multiple-administrators)
* Content Source: [azure-stack/aks-hci/set-multiple-administrators.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/set-multiple-administrators.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by kobulloc-MSFT** [comment]
@IvanNaumeiko Thank you for your feedback!  We're assigning this to the document author for further review.

@mattbriggs I believe the introduction is what is being referenced:

> For various reasons, AKS on Azure Stack HCI is currently tightly coupled to the user who installed the service with no awareness of other local users or AD users with administrative rights. We are working on resolving this issue, but you can use the steps in this topic to register additional users with the Microsoft on Cloud (MOC) service under AKS on Azure Stack HCI. This will allow multiple people to perform administrative tasks.

**Comment by mattbriggs** [comment]
@IvanNaumeiko Thanks for your question. I have forward to your technical staff. In the meantime, you may find the the roadmap for the AKS on HCI here: [AKS on Azure Stack HCI roadmap](https://aka.ms/aks-hci-roadmap/).

#in-progress
