### ISSUE TITLE
SCVMM Supportability for Azure Stack HCI

### ISSUE THREAD

**Issue by AmoorG** [MicrosoftDocs/azure-stack-docs#1887]
[Enter feedback here]

its mentioned in this article as a note that :
You can't use Microsoft System Center VMM 2019 to manage clusters running Azure Stack HCI, version 21H2 or Windows Server 2022.
while on other articles supportability is there:
https://techcommunity.microsoft.com/t5/system-center-blog/get-started-with-azure-stack-hci-using-vmm/ba-p/2244302
https://docs.microsoft.com/en-us/system-center/vmm/deploy-manage-azure-stack-hci?view=sc-vmm-2019&branch=release-sc2019-ur3
so here we need to clarify this point to match with other announcements and supportability scenarios 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842bf434-fd3f-5a56-4dee-794858175bed
* Version Independent ID: 779df781-d6a7-0a43-1f1a-2fc66eb9e82f
* Content: [Deploy SDN using Windows Admin Center - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/sdn-wizard)
* Content Source: [azure-stack/hci/deploy/sdn-wizard.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/sdn-wizard.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by VikasPullagura-MSFT** [comment]
@AmoorG 
Thanks for the feedback! We will check and update the document as appropriate.

**Comment by ManikaDhiman** [comment]
Hi @AmoorG, thanks for your feedback. You can use VMM 2019 to manage clusters running Azure Stack HCI, version 20H2, but not version 21H2. So, the note is correct. However, you can use VMM 2022, which is currently in preview, to manage clusters running Azure Stack HCI, version 21H2. I updated the note to state that and added a link to the blog; updates will be live shortly. Thanks!

**Comment by ManikaDhiman** [comment]
#please-close
