### ISSUE TITLE
Error when running asdk-installer.ps1

### ISSUE THREAD

**Issue by mwdarab** [MicrosoftDocs/azure-stack-docs#1889]
Under this [section](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-prepare-host?view=azs-2108#prepare-the-development-kit-host-computer):

I do #1-3, and when I run the ps script for #4 (C:\AzureStack_Installer\asdk-installer.ps1) I get this error:

"**_Initialize environment. Please wait..The server is currently already booted from a virtual hard disk, to boot the server from the CloudBuilder.vhdx you will need to run this script on an Operating System that is installed on the 
physical disk of this server_**."

(I have an Azure VM I created, with 4 additional hard drives with 100GBs each. I RDP into the VM using my local admin account)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11763bdd-9ffc-4c47-d2a2-d9a594c82d88
* Version Independent ID: 9c65d4a1-30c3-2294-bfc5-5cf9f6bfec02
* Content: [Prepare the ASDK host computer - Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-prepare-host?view=azs-2108)
* Content Source: [azure-stack/asdk/asdk-prepare-host.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/asdk/asdk-prepare-host.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub-asdk**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by kobulloc-MSFT** [comment]
@mwdarab Thank you for your feedback!  We've assigned this to the document author for further review.

**Comment by sethmanheim** [comment]
@mwdarab @kobulloc-MSFT Not clear what the documentation issue is here -- can you please clarify?

**Comment by kobulloc-MSFT** [comment]
@mwdarab It looks like you are looking for some troubleshooting assistance.  For help with a deployment, please check out Microsoft Q&A: 
https://docs.microsoft.com/en-us/answers/topics/50514/azure-stack-hub.html

**Comment by kobulloc-MSFT** [comment]
@mwdarab Unless there's a change we can make to the documentation, we are going to close this thread as resolved.  If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
