### ISSUE TITLE
Command for Installing Hyper-V 

### ISSUE THREAD

**Issue by hfu949** [MicrosoftDocs/azure-stack-docs#1892]
Hi, suggestion. 

You should let people know to use the Enable-WindowsOptionalFeatures on the link below instead of the usual Install-WindowsFeature command as that seems to error out with "A prerequisite check for the Hyper-V feature failed." "Hyper-V cannot be installed because virtualization support is not enabled in the BIOS." It works with Enable-WindowsOptionalFeature.

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v#enable-hyper-v-using-powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58cb678-2c81-b3c2-cfce-9ff96c0e18cc
* Version Independent ID: b34bb724-ea12-7063-8d9c-0ff0ae6db190
* Content: [Nested virtualization in Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/nested-virtualization)
* Content Source: [azure-stack/hci/concepts/nested-virtualization.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/nested-virtualization.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by MonikaReddy-MSFT** [comment]
@hfu949  - Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can review and update the document accordingly.

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by alkohli** [comment]
Since there is no request to keep it opened, will be closing this issue. #please-close
