### ISSUE TITLE
Please update the page

### ISSUE THREAD

**Issue by IvanNaumeiko** [MicrosoftDocs/azure-stack-docs#1896]
Hello,

Would it be possible to review content of this page and update it?
AFAIK at least docker command should be replaced with crictl in all applicable sections.
Thanks,

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42fa409d-1f42-4f1e-840b-d281dd17f3ee
* Version Independent ID: c9682e4a-02e6-9910-1a44-076a9c6b2d06
* Content: [Troubleshoot Kubernetes workload cluster issues and errors in Azure Kubernetes Service on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues-workload-clusters)
* Content Source: [azure-stack/aks-hci/known-issues-workload-clusters.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/known-issues-workload-clusters.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by kobulloc-MSFT** [comment]
@IvanNaumeiko Thank you for your feedback!  We are reviewing the documentation and will get back to you shortly.

**Comment by mattbriggs** [comment]
@IvanNaumeiko Thanks for your feedback.

#in-progress

**Comment by mattbriggs** [comment]
@IvanNaumeiko We are evaluating the change and the plan to handle the shift from the Docker runtime. We will update the docs when the change has been checked. Thanks again!

#please-close
