### ISSUE TITLE
VNET peering Permissions: Contributor or Network Contributor?

### ISSUE THREAD

**Issue by aluty** [MicrosoftDocs/azure-stack-docs#1898]
Please clarify VNET peering Permissions: Azure Stack Hub requires **Contributor** (superset)?  However, https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-manage-peering#permissions for Azure requires **Network Contributor** (least privilege).

--
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74cfae8-296b-d69c-75a0-9c756b1de30e
* Version Independent ID: cbfa8998-3b0d-a914-2250-ec84159f479e
* Content: [Virtual network peering in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/virtual-network-peering?view=azs-2108)
* Content Source: [azure-stack/user/virtual-network-peering.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/virtual-network-peering.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@aluty 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@aluty It sounds like the manage peering article just describes the different types of contributor roles, so I would add a link from the peering article back to that section of the manage peering article. I don't see anything mentioning "least privilege".

**Comment by raluca256** [comment]
@sethmanheim I was checking this out with @CristianEdwards today. @aluty is right, the minimum permission needed is "Network Contributor" role on the VNET, not even the subscription. I think we usually recommend the minimum permissions needed to set something up. The Contributor role gives too many permissions vs what is needed.
Even more that phrase has to be changed also to exclude the "Azure AD tenants" part, which is not currently supported on Hub.

This phrase: "Please ensure that when creating peerings with VNETs in different subscriptions and Azure AD tenants, the accounts have the Contributor role assigned." 
Should be changed into: "Please ensure that when creating peerings with VNETs in different subscriptions, the accounts have the Network Contributor role assigned at the VNETs level (Example: User1 has the Network Contributor role on VNET2 and User2 has the Network Contributor role on VNET1, where User1 owns the Subscription1 where VNET1 is created and User2 owns the Subscription2 where VNET2 is created)."

**Comment by sethmanheim** [comment]
I have made these updates and it should be live after 3 PM today PST. #please-close
