### ISSUE TITLE
Managed User Identitites

### ISSUE THREAD

**Issue by jamesorlando** [MicrosoftDocs/azure-stack-docs#1899]
This page covers Managed System Identities and Azure Stack (not supported), but makes no mention of Managed User Identities. I did some testing and it does appear Managed User Identities are supported in Stack, but it would be super helpful to have that spelled out in this doc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9696bc60-b1f8-a0bc-0936-82a46750aa74
* Version Independent ID: cb5673ae-2a4b-513f-fb26-5ccd58d8d0d2
* Content: [Identity architecture for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-identity-architecture?view=azs-2108#capabilities-and-limitations)
* Content Source: [azure-stack/operator/azure-stack-identity-architecture.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-identity-architecture.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by VikasPullagura-MSFT** [comment]
@jamesorlando 
Thanks for the feedback! I will check with document author on this.

**Comment by VikasPullagura-MSFT** [comment]
@BryanLa 
Can you please check and add your comments on this doc update request as applicable.

**Comment by BryanLa** [comment]
Article has been revised to clarify.

#please-close
