### ISSUE TITLE
Get-AzureStackLog script does not work as posted

### ISSUE THREAD

**Issue by mjuza** [MicrosoftDocs/azure-stack-docs#19]
The script on this page for collecting AzureStack logs after a failure of Test-AzureStack does not work as written.  I suggest you add the commands that are needed to make it work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eacef4e6-6608-bfab-ceea-d081b9c48e3a
* Version Independent ID: e260c6a1-7cec-2c32-76b6-a80ce0ac00fe
* Content: [Use the Azure Stack validation tool](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-diagnostic-test)
* Content Source: [articles/azure-stack/azure-stack-diagnostic-test.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-diagnostic-test.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by mattbriggs** [comment]
@TravisCragg-MSFT. I'm reviewing some of the older GitHub issues. In regard to the PEP session, you can import the PEP session into a regular PowerShell session and then you can have access to your other cmdlets. https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-privileged-endpoint#tips-for-using-the-privileged-endpoint .

In any case, I've pointed to the instructions and removed the cmdlet that isn't working. #please-close

**Comment by mattbriggs** [comment]
#please-close
