### ISSUE TITLE
Steps to prepare the client VM does not list required software packages

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1903]
The client VM for aks-engine created under #prepare-the-client-vm has some additional software prereqs that are not mentioned here-

* Linux requirements- https://github.com/Azure/aks-engine/blob/master/docs/topics/windows.md#linux
Specifically "jq - helpful JSON processor" which is required but not available by default on all distros, can be installed using package manager, e.g. "sudo apt install jq".

* Windows- https://github.com/Azure/aks-engine/blob/master/docs/topics/windows.md#windows

* Mac- https://github.com/Azure/aks-engine/blob/master/docs/topics/windows.md#mac

Suggest adding a link, or a list of required software packages on the client VM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d8c6cbd-54d8-9746-a1f8-a618b98e011e
* Version Independent ID: 479c631e-b7a4-c5cf-160d-141d336ad50a
* Content: [Install the AKS engine on Linux in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux?view=azs-2108#prepare-the-client-vm)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by PriyankaRudramaina** [comment]
Hi @alexsmithMSFT,

Thank you for your feedback. We will investigate and update the thread further.

**Comment by mattbriggs** [comment]
@alexsmithMSFT Thanks for the update Alex.

#in-progress

**Comment by mattbriggs** [comment]
updated.

#please-close
