### ISSUE TITLE
Logical Networks || Public VIP description

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-stack-docs#1904]
The description below in the table is confusing,  It might be better to be stated as

Azure Stack uses a total of 31 addresses from this network and the rest are used by tenant VMs. From the 31 addresses, 8 public IP addresses are used for a small set of Azure Stack services. If you plan to use App Service and the SQL resource providers, 7 more addresses are used. The remaining **16** IPs are reserved for future Azure services.

<html>
<body>

Logical Network | Description | Size
-- | -- | --
Public VIP | Azure Stack uses a total of 31 addresses from this network. Eight public IP addresses are used for a small set of Azure Stack services and the rest are used by tenant VMs. If you plan to use App Service and the SQL resource providers, 7 more addresses are used. The remaining 15 IPs are reserved for future Azure services. | /26 (62 hosts) - /22 (1022 hosts)Recommended = /24 (254 hosts)

</body>
</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49f52a1b-0bfa-a51f-dfa3-4422502d0e82
* Version Independent ID: 95213ed3-d96f-8ad9-e442-7c7f29164ebb
* Content: [Network integration planning for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-network?view=azs-2108#public-vip-network)
* Content Source: [azure-stack/operator/azure-stack-network.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-network.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by PriyankaRudramaina** [comment]
Hi @HassanAlmanasrah,

Thank you for your feedback. We will investigate and update the thread further.

**Comment by BryanLa** [comment]
Thanks again, @HassanAlmanasrah . Changes are complete and will publish around 3pm pacific today.

#please-close
