### ISSUE TITLE
Include az cli install in that document:

### ISSUE THREAD

**Issue by Mihaly7** [MicrosoftDocs/azure-stack-docs#1906]
Please include the following, because az cli is not included in the HCI OS by default.:

#install az powershell onprem
$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
rm .\AzureCLI.msi

Set environment path also for az cli commands:

$env:Path += "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b82e60f9-ebed-4011-41b7-3e11a60322ff
* Version Independent ID: 61535b85-bea3-f0b5-f562-fdd08293ed65
* Content: [VM provisioning through Azure portal on Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-enabled-virtual-machines)
* Content Source: [azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ksurjan
* Microsoft Alias: **ksurjan**

**Comment by VikasPullagura-MSFT** [comment]
@Mihaly7 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@ksurjan 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@ksurjan Can you please address this issue? Thank you!

**Comment by sethmanheim** [comment]
@Mihaly7 Very sorry for the slow response. If this is still an issue, please re-open. #please-close
