### ISSUE TITLE
Docker command not found

### ISSUE THREAD

**Issue by OEI-Cgray** [MicrosoftDocs/azure-stack-docs#1907]
Doesn't this use containerd now?

ssh -i (Get-AksHciConfig).Moc.sshPrivateKey clouduser@clusterip "sudo docker container ls | grep 'kms'"
sudo: docker: command not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42fa409d-1f42-4f1e-840b-d281dd17f3ee
* Version Independent ID: c9682e4a-02e6-9910-1a44-076a9c6b2d06
* Content: [Troubleshoot Kubernetes management and workload clusters issues in Azure Kubernetes Service on Azure Stack HCI - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues-workload-clusters#the-api-server-isnt-responsive-after-several-days)
* Content Source: [azure-stack/aks-hci/known-issues-workload-clusters.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/known-issues-workload-clusters.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by CHEEKATLAPRADEEP-MSFT** [comment]
@OEI-Cgray  Thanks for the question! We are investigating and will update you shortly.

**Comment by mkostersitz** [comment]
@EkeleAsonye FYI

**Comment by mattbriggs** [comment]
Update:

ssh -i (Get-AksHciConfig).Moc.sshPrivateKey clouduser@clusterip "sudo ctr container ls | grep 'kms'"

**Comment by OEI-Cgray** [comment]
Thanks!

Just to also note, the linked github issue on the page did have the commands (although I figured it out with some basic searches for containerd commands, and then found the github link...).

But thanks for updating the page!

Chris

**Comment by mattbriggs** [comment]
Still working on the doc update to address containerd and the best CLIs to work in the context of AKS on HCI, but this issue specific seems closed for now.

#please-close
