### ISSUE TITLE
Incorrect cell formula in DefineByWorkload worksheet impacts calculations

### ISSUE THREAD

**Issue by dfencegit** [MicrosoftDocs/azure-stack-docs#1910]
On the DefineByWorkload worksheet the cells used to calculate figures for the Standard_A2_v2 sku are incorrectly copied from the Standard_A1_v2 row.

Effected cells:

F:190
N:190

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0361b690-092e-77c1-fccb-1c2aeba5e259
* Version Independent ID: ac57d31d-4356-2d99-9f1c-976513f353ec
* Content: [Azure Stack Hub Capacity Planner - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-capacity-planner?view=azs-2108)
* Content Source: [azure-stack/operator/azure-stack-capacity-planner.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-capacity-planner.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by PriyankaRudramaina** [comment]
Hello @dfencegit,

Thank you for your feedback. We will investigate and update the thread further.
