### ISSUE TITLE
AKS Base Ubuntu image version number is outdated

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1911]
With 2108 updated re-released, this public doc still lists the older base image- 
https://docs.microsoft.com/en-us/azure-stack/operator/aks-add-on?view=azs-2108#download-aks-base-image

> Using the administrator portal, go the Marketplace management blade and select "Add from Azure", type "AKS" in the search box, locate, and download Linux "AKS Base Ubuntu 18.04-LTS Image Distro, 2021 Q3" version "2021.02.17

This should be updated with 2021 Q4 release (microsoft-aks.aksaks-ubuntu-1804-2021-q4-2021.12.08) and any subsequent base image versions, ideally with version information converted to a compatibility table, or specific version references removed entirely.

Also customers need to be able to differentiate the AKS versus aks-engine base images, because they are given similar names. For example, these images are both named "AKS Base Ubuntu 18.04-LTS Image Distro, 2021 Q3" but one is for AKS and the other for aks-engine:

```
microsoft-aks.aksaks-ubuntu-1804-2021-q3-2021.02.17
microsoft-aks.aks-engine-ubuntu-1804-202007-2021.09.27
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4871e496-b684-ea5f-b579-50774bb9ffb4
* Version Independent ID: b683dc6a-864d-9932-11da-3335d2597cb7
* Content: [Install and offer the Azure Kubernetes Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/aks-add-on?view=azs-2108)
* Content Source: [azure-stack/operator/aks-add-on.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/aks-add-on.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@[alexsmithMSFT](https://github.com/alexsmithMSFT) Thanks for the update. 

#in-progress

**Comment by mattbriggs** [comment]
Passed along the suggestion and updated the topic with the most recent Linux version. Thanks! Matt

#please-close
