### ISSUE TITLE
Need more clarification about total number of VMs

### ISSUE THREAD

**Issue by kongou-ae** [MicrosoftDocs/azure-stack-docs#1914]
Hi,

Does the limitation of the total number of VMs contain infrastructure role VMs? This document doesn't mention this topic. I'm confused that "TotalVMMaximum" which is used in Azure Stack Hub capacity planner is 670, not 700.

Best

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b6179e-9c7b-4c9e-6c26-c5edfc4bedae
* Version Independent ID: ada578d3-3b7f-dffc-a0f3-3e6938a8f75f
* Content: [Azure Stack Hub compute capacity - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-capacity-planning-compute?WT.mc_id=AZ-MVP-5003408&view=azs-2108#consideration-for-total-number-of-vms)
* Content Source: [azure-stack/operator/azure-stack-capacity-planning-compute.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-capacity-planning-compute.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by SreejaBhattacharya-MSFT** [comment]
Hi @kongou-ae , thanks for reaching out. We will investigate this further and get back to you.

**Comment by SreejaBhattacharya-MSFT** [comment]
Hi @kongou-ae , do you have any further questions on this?

**Comment by kongou-ae** [comment]
@SreejaBhattacharya-MSFT 

Thank you for your reply. I know that the document mentioned the number of infrastructure VMs. My question is whether these VMs are included in 700 per scale unit and 60 per scale unit node. And I suggest that the document needs to clarify whether these VMs are included in these limitations.

Best

**Comment by BryanLa** [comment]
Hi @kongou-ae - thanks very much for your feedback. I agree that the doc should be a little clearer. And yes, the infrastructure VMs are included in the limits. We'll be updating the doc to reflect this (which is also mentioned in the capacity planner spreadsheet). We'll drop another comment once the doc has been updated..

**Comment by ronmiab** [comment]
@kongou-ae - Updates have been made to clarify the VMs capacity and reference to the Azure Stack Hub capacity planner. The article will be published around 3PM/PST.

#please-close

**Comment by kongou-ae** [comment]
@ronmiab 
I confirmed this commit. Thank you for your quick improvement. 
https://github.com/MicrosoftDocs/azure-stack-docs/commit/aa51435b15a8a944899c2fc99427394f1a17ffd1
