### ISSUE TITLE
 Convert-WindowsImage bad link or bogus cmdlet?

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#1915]
Please test the link for Convert-WindowsImage (https://gallery.technet.microsoft.com/scriptcenter/Convert-WindowsImageps1-0fe23a8f).  Is this a bad link or a non-existent script/cmdlet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eeb152f-1c40-2222-c2d4-199371710080
* Version Independent ID: 09741470-9f27-a683-d042-12b22f3e4105
* Content: [System requirements for Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/system-requirements)
* Content Source: [azure-stack/hci/concepts/system-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/system-requirements.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by VikasPullagura-MSFT** [comment]
@aricbernard 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@JasonGerend 
Can you please check and add your comments on this doc update request as applicable.
