### ISSUE TITLE
Disconnected containers

### ISSUE THREAD

**Issue by Deepfat** [MicrosoftDocs/azure-stack-docs#1918]
[Enter feedback here]
There is nothing on this page about how I get a container in ACR to a disconnected Azure Stack Hub running K8s, in my case running on a ship which only comes into port every three to six months.  We are trying to help the customer swap out vmware and move to microservices at sea, however there must be other scenarios where this is needed.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3914390-367c-471b-b653-7672f967f472
* Version Independent ID: 08ecfe0f-a12d-9d24-8d25-a23b1aa1401a
* Content: [Azure disconnected deployment decisions for Azure Stack Hub integrated systems - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-disconnected-deployment?view=azs-2108)
* Content Source: [azure-stack/operator/azure-stack-disconnected-deployment.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-disconnected-deployment.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by SreejaBhattacharya-MSFT** [comment]
Hi @Deepfat , thanks for reaching out. We'll review this and update the document as appropriate

**Comment by BryanLa** [comment]
@Deepfat - thanks very much for your feedback on this. We've added your suggestion to the "Features that are impaired or unavailable" table, which points to a new entry in the ACR FAQ that provides additional how-to details.

#please-close
