### ISSUE TITLE
This document is missing the powershellgallery.com which is required to install the AzureAD module during deployment.

### ISSUE THREAD

**Issue by Lacosta74** [MicrosoftDocs/azure-stack-docs#1919]
Part of the deployment ls to install the Nuget package provider and the AzureAD module.
Deployment fails when trying to install both of these modules.

This is the first line that is called:
Install-PackageProvider -Name NuGet -verbose
Which connects to: https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag"
Initially it tries to connect to **https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409** to get the onegetcdn.azureedge.net list which fails if it is not white listed. 

Then it tries to install the azuread powershell module:
Install-Module AzureAD -verbose.
This tries to download the package from the default package provider PSGallery
**http://www.psgallery.com/api/v2**

Can we add these two websites to this list?

Thanks,
Luis A
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d02f93-1ae9-eb2d-9c0f-0af012653885
* Version Independent ID: 18f15ad2-ef9b-f883-c49b-09289a2e6fb8
* Content: [Publish Azure Stack Hub services in your datacenter - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-endpoints?view=azs-2108)
* Content Source: [azure-stack/operator/azure-stack-integrate-endpoints.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-integrate-endpoints.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by kobulloc-MSFT** [comment]
@Lacosta74 Thank you for the feedback!  We are reviewing the deployment instructions and will get back to you shortly.

**Comment by BryanLa** [comment]
@Lacosta74 - my apologies for the delay on this. 

I'm discussing with engineering, and they mentioned that those installations are typically done from the Operator's workstation (for example, see [Install PowerShell Az module for Azure Stack Hub](https://docs.microsoft.com/azure-stack/operator/powershell-install-az-module), and that the Azure Stack Hub infrastructure deployment does not require access to those endpoints for deployment. 

Regarding "Deployment fails when trying to install both of these modules", can you confirm where you're doing the installation from?

**Comment by lcacosta** [comment]
That is correct, this is specific to DellEMC deployments where it is building the MGMT-VM and DVM to start the baremeal deployment.  ".\MGMTVMPreReqInstall.ps1 -InstallAzureAD" is the code that calls for those modules.

**Comment by BryanLa** [comment]
Great, thanks @Lacosta74. Let me circle back w/engineering and I'll post a follow up...

**Comment by BryanLa** [comment]
@Lacosta74 - just a quick update... it sounds like this is something we'll need to relay to DellEMC, as engineering prefers to not add the additional endpoints for deployment of the ASH stamp itself. Deployment HLH image and module/script requirements varies by OEM. As soon as I get confirmation I will post another reply..

**Comment by BryanLa** [comment]
@Lacosta74  - apologies for the delays on this, but I have confirmed that this is something we are going to need to share with the DellEMC engineers. We'll likely recommend that they download the modules in advance and build them into the DVM image. 

We'll post any updates to this issue going forward, and thank you again for your feedback on this.

#please-close
