### ISSUE TITLE
Logic Apps

### ISSUE THREAD

**Issue by PatTelford** [MicrosoftDocs/azure-stack-docs#192]
I see that Logic Apps in the App Service Resource Provider do not work in a disconnected Azure Stack. This is definitely worth noting here (along with any other disconnected limitations in the App Service and SQL/MySQL RPs), since it can affect planning decisions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3914390-367c-471b-b653-7672f967f472
* Version Independent ID: 08ecfe0f-a12d-9d24-8d25-a23b1aa1401a
* Content: [Azure disconnected deployment decisions for Azure Stack integrated systems](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-disconnected-deployment#feedback)
* Content Source: [azure-stack/operator/azure-stack-disconnected-deployment.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-disconnected-deployment.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by PatTelford** [comment]
Let me break this up into two questions, since it doesn't make perfect sense what I mention above:
1. Should we mention common hybrid capabilities that will not work when disconnected (Logic Apps, Azure automation, App Insights etc.)?
2. Are there RP capabilities that are unavailable/impaired when disconnected? I only see core Azure Stack capabilities above - but maybe all RP capabilities are okay disconnected...

**Comment by TravisCragg-MSFT** [comment]
@PatTelford Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

I believe this doc outlines most of the Disconnected capabilities, is there anything in particular that you are not clear on for me to follow up with?

**Comment by mattbriggs** [comment]
@PatTelford I have sent your questions out to get some answers. I'll be back in touch when I have an answer, and update the docs to make them clearer about the disconnected limitations. #in-progress

**Comment by apwestgarth** [comment]
@PatTelford, @MattBriggs Logic Apps are not available as part of the App Service Resource Provider.  They are a separate RP entirely which is not available on Azure Stack at all.

**Comment by mattbriggs** [comment]
@apwestgarth Thanks Andrew! @PatTelford I will close this thread for now. But if you have additional questions, please contact me. Thanks! Matt

**Comment by mattbriggs** [comment]
#sign-off

**Comment by mattbriggs** [comment]
#please-close
