### ISSUE TITLE
BMC credentials to be configured on the new node before addition

### ISSUE THREAD

**Issue by JohnBMSFT** [MicrosoftDocs/azure-stack-docs#1921]
I recently assisted a customer who reported an issue during node addition which failed with below error when attempted from both portal and PowerShell. Turns out the issue was with invalid BMC credentials configured on the node being added.

_Failed to add node **'BMC IP xx.xx.xx.xx'**. Error message: The BMC IP address '**BMC IP xx.xx.xx.xx**' did not respond to a general query in the expected time. Verify that the BMC with this IP address has been connected to the network and configured with the correct credentials and try the operation again._

The new node should be configured with BMC credentials that are already configured within Azure Stack. Failing to do so will throw the above exception as Azure Stack cannot connect to the node using these credentials.

However, I don't see this included in the pre-requisite section of the document. Suggestion is to add a "Note" or include a point in the below section of the document that outlines the need for configuring BMC credentials on new node before proceeding with node addition so as to prevent other customers from running into the same issue.

https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-add-scale-node?view=azs-2108&tabs=portal#add-scale-unit-nodes

Tagging @alexsmithMSFT for visibility

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64db3541-1bfb-2e60-8e72-9ab367c921ea
* Version Independent ID: 61f792a6-9fef-f79e-ae35-6f58a6a625db
* Content: [Add scale unit nodes in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-add-scale-node?view=azs-2108&tabs=portal#add-scale-unit-nodes)
* Content Source: [azure-stack/operator/azure-stack-add-scale-node.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-add-scale-node.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by BryanLa** [comment]
@JohnBMSFT - thanks much for your feedback on this. The article has been revised to include a reminder that the new node should be configured with BMC credentials that are already configured within Azure Stack (at the beginning of the instructions). We also reformatted and improved the flow a bit in general. This will republish again around 10am PDT tomorrow, 5/18. 

#please-close
