### ISSUE TITLE
Language Issue -- possibly a Typo

### ISSUE THREAD

**Issue by pgoyal01** [MicrosoftDocs/azure-stack-docs#1925]
In the section Update the container operating system version without updating the Kubernetes version (https://docs.microsoft.com/en-us/azure-stack/aks-hci/upgrade#update-the-container-operating-system-version-without-updating-the-kubernetes-version), the first sentence states,

> Keep in mind that if you decide to upload a workload cluster to a newer version of the operating system without changing the Kubernetes version, it will not work unless the new operating system version requires a different Kubernetes version.

I think what it is supposed to say is that, "... it will not work unless the new operating system version does not require a different Kubernetes version"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d9faa89-0531-22d5-1c62-bb2e877b59e6
* Version Independent ID: 77691344-d8b8-0a93-2890-e466b565144d
* Content: [Upgrade the Kubernetes version of AKS workload clusters using PowerShell - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/upgrade)
* Content Source: [azure-stack/aks-hci/upgrade.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/upgrade.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by kobulloc-MSFT** [comment]
@pgoyal01 Thank you for pointing this out!  We're reviewing this and will get back to you shortly.

**Comment by mattbriggs** [comment]
@[pgoyal01](https://github.com/pgoyal01) Thanks for catching this! #in-progress

**Comment by mattbriggs** [comment]
updated

#please-close
