### ISSUE TITLE
zip file download link typo. 

### ISSUE THREAD

**Issue by jianfeng-jia** [MicrosoftDocs/azure-stack-docs#1927]
[Download the zip file now](https://azurestackhub.azureedge.net/PR/download/MAS_ProdHotfix_1.2102.30.1323/HotFix/AzS_Update_1.2102.30.132.zip).
should be: 
https://azurestackhub.azureedge.net/PR/download/MAS_ProdHotfix_1.2102.30.132/HotFix/AzS_Update_1.2102.30.132.zip

there is an extra number "3" in the URI.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f374ffcc-a29c-d614-1647-d0c5e899d6b3
* Version Independent ID: 7f8dd36f-4bae-809a-86d6-289beceff900
* Content: [Azure Stack Hub hotfix 1.2102.30.132 - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/hotfix-1-2102-30-132?view=azs-2108)
* Content Source: [azure-stack/operator/hotfix-1-2102-30-132.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/hotfix-1-2102-30-132.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@jianfeng-jia Thanks for pointing this out.

The document is updated and changes will go live soon.
