### ISSUE TITLE
Could we add guidance on how to upgrade AKS cluster on portal please?

### ISSUE THREAD

**Issue by Lihailian** [MicrosoftDocs/azure-stack-docs#1928]
Could we add guidance on how to upgrade AKS cluster on portal please? 

I know if we go to AKS cluster on portal, you will see upgrade related information but it will be hard for customers to find it out. We'd better have it in document.
![image](https://user-images.githubusercontent.com/45778009/164432230-162cf947-9569-4117-b4b8-c263f95a5735.png)
![image](https://user-images.githubusercontent.com/45778009/164432256-d3e5b51a-7cb1-44d0-ae07-11a8284a90aa.png)

Thank you.

Regards,
Hailian Li

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0fe7832-83ca-28bb-3b06-684a09da21d0
* Version Independent ID: 7552766c-b48c-ceef-335d-e22bca1d8583
* Content: [Use Azure Kubernetes Service on Azure Stack Hub in the portal - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/aks-how-to-use-portal?view=azs-2108)
* Content Source: [azure-stack/user/aks-how-to-use-portal.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/aks-how-to-use-portal.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by VikasPullagura-MSFT** [comment]
@Lihailian 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@mattbriggs 
Can you please check and add your comments on this doc update request as applicable.

**Comment by mattbriggs** [comment]
@Lihailian AKS on Azure Stack Hub doesn't yet have a version of Kubernetes to upgrade to. This is a public preview, and if you have feedback or requests, please send your insight and notes to: https://docs.microsoft.com/en-us/azure-stack/user/aks-support. Thanks again for trying AKS on Azure Stack Hub.

**Comment by mattbriggs** [comment]
#please-close
