### ISSUE TITLE
Add clarity to SPN role-based permissions

### ISSUE THREAD

**Issue by easyveazie** [MicrosoftDocs/azure-stack-docs#1930]
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-aks-engine?view=azs-2108

The following line should clarify which role-based permissions are required. Do I need owner, contributor, something else? Consider adding details on how to assign the permissions in the portal as well.
_The Kubernetes cluster will need service principal (SPN) and role-based permissions in Azure Stack Hub._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfb60cd-c79d-e4c3-9015-bb3b49e1dc06
* Version Independent ID: 9a48b797-af3b-462d-94a0-07693651a488
* Content: [Add Azure Kubernetes Services (AKS) engine prerequisites to Azure Stack Hub Marketplace - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-aks-engine?view=azs-2108&source=docs)
* Content Source: [azure-stack/operator/azure-stack-aks-engine.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-aks-engine.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@[easyveazie](https://github.com/easyveazie) Thanks Mike. #in-progress

**Comment by mattbriggs** [comment]
updated the Operator topic.

#please-close
