### ISSUE TITLE
Pre-requisites update

### ISSUE THREAD

**Issue by lanicolas** [MicrosoftDocs/azure-stack-docs#1933]
On the pre-requisites  section, I think it would be nice to add the AKSHCI module requirements, some people may not have them: 
  Install-Module -Name Az.Accounts -Repository PSGallery 
  Install-Module -Name Az.Resources -Repository PSGallery 
  Install-Module -Name AzureAD -Repository PSGallery 

Also, before the Get-Command, for it to work you would need to run: 

   Import-Module Az.Accounts
  Import-Module Az.Resources
  Import-Module AzureAD
  Import-Module AksHci

Minor changes for fresh installations
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9753c970-5a86-1862-4bb9-6b5ecdec550d
* Version Independent ID: b6ed170c-8c63-2020-2474-15c787c1c1b5
* Content: [Quickstart to set up an Azure Kubernetes Service host and create AKS on Azure Stack HCI clusters using Windows PowerShell - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/kubernetes-walkthrough-powershell)
* Content Source: [azure-stack/aks-hci/kubernetes-walkthrough-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/kubernetes-walkthrough-powershell.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by PriyankaRudramaina** [comment]
Hello @lanicolas,

Thank you for your feedback. We will investigate and update the thread further.

**Comment by mattbriggs** [comment]
@[lanicolas](https://github.com/lanicolas) Thanks for this feedback. That sounds good. I'll update shortly.

#in-progress

**Comment by mattbriggs** [comment]
Sent an email with the preview item. Will appear in the next build, once it passes PR review.

Thanks! Matt

#please-close
