### ISSUE TITLE
Add kubeconfig info to the "Verify your cluster" introduction section

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1938]
to that section we should add more to the introduction to say something like this:
"if you already have kubectl installed, you can get the kubeconfig file for the newly create cluster in this directory path: 

<output directory>/kubeconfig/kubeconfig.<location>.json

You can use it to add it to the .kube directory to access your new cluster. If you have not installed kubectl, visit: https://kubernetes.io/docs/tasks/tools/ to install it. Otherwise, follow the the instructions below to access the cluster from one of the control plane nodes."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d8c6cbd-54d8-9746-a1f8-a618b98e011e
* Version Independent ID: 479c631e-b7a4-c5cf-160d-141d336ad50a
* Content: [Install the AKS engine on Linux in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux?view=azs-2108)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by mattbriggs** [comment]
@[walterov](https://github.com/walterov) #in-progress

**Comment by sethmanheim** [comment]
@walterov It's not clear to me where your suggested content would belong -- I don't see a "Verify your cluster" section in this article, or anything that mentions the kubeconfig file.
