### ISSUE TITLE
Considerations for Node count and Physical Space

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/azure-stack-docs#1939]
Consider adding the following site readiness factors:
* Requirements such as Power, based on node count (4 vs 16 nodes as an example)
* Physical space requirements (LxWxH) based on stacking the units.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70d0adb4-9c95-e00d-bf5d-40751896e1e2
* Version Independent ID: cfa2aa27-8355-2cdf-13fe-4f2aca93e13a
* Content: [Azure Stack Hub ruggedized site readiness for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/ruggedized/site-readiness?view=azs-2108)
* Content Source: [azure-stack/ruggedized/site-readiness.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/ruggedized/site-readiness.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **wamota**

**Comment by kobulloc-MSFT** [comment]
@CHDAFNI-MSFT Thank you for the feedback!  We've assigned this to the document author for further review.

**Comment by sethmanheim** [comment]
Please reopen if you can obtain this information, and I will add it to the docs.
