### ISSUE TITLE
CreateAADIdentityApp.ps1

### ISSUE THREAD

**Issue by JamieRalphSmithMS** [MicrosoftDocs/azure-stack-docs#1940]
Script no longer works as the Reference in Get-AzureRMUserRefreshToken fails in line 27 and catches to 32 on a failure with no readitems method.  This may be to AzureStack Powershell being updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Prerequisites to deploy Azure App Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started?view=azs-2108&pivots=state-connected)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by kobulloc-MSFT** [comment]
@JamieRalphSmithMS Thank you for the feedback!  We have assigned this to the document author for further review.

**Comment by JamieRalphSmithMS** [comment]
Thanks for responding @V-GSOLER 
1.  ASH version is 2108
2.  2021Q3

**Comment by sethmanheim** [comment]
@JamieRalphSmithMS Sorry for the slow response. If you still need assistance, please open a new feedback request. #please-close
