### ISSUE TITLE
missing information/detail

### ISSUE THREAD

**Issue by nairsrijith** [MicrosoftDocs/azure-stack-docs#1941]
There are some error and missing information in the link provided below:
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-2108#rotate-external-secrets

Rotate External secret > Rotation > Step#1

`$CertSharePath = "<Network_Path_Of_CertShare>"`
It would be helpful to define what "<Network_Path_Of_CertShare>" should be like "`\\<IPAddress>\<ShareName>\Certificates`"

The information provided in the previous section makes this confusing as section 
Rotate External secret > Preparation > Step#6 defines 

    File share = \\<IPAddress>\<ShareName>
    Certificate root folder for Azure AD provider = \Certificates\AAD
    Full path = \\<IPAddress>\<ShareName>\Certificates\AAD

None of these match with the value that <Network_Path_Of_CertShare> accepts.

Only when you run the Start-SecretRotation it gives the error that path should end with Certificates.

Additionally the variable assignment use Capital Camel case whereas -ArgumentList contains the variables in Camel case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4feaa2a-4850-478d-8122-7eb751ba0777
* Version Independent ID: f5cd7372-0443-3f2e-c403-ed7ba1a56146
* Content: [Rotate secrets - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-2108)
* Content Source: [azure-stack/operator/azure-stack-rotate-secrets.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-rotate-secrets.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by BryanLa** [comment]
@nairsrijith - thanks very much for your feedback. I've made several changes to the article to improve clarity on the directory/folder structure, as well as the casing issue you pointed out. The revised version will republish around 3pm PDT today.

#please-close
