### ISSUE TITLE
Need to correct K8s version numbers for AKS Engine 0.70.0 

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1947]
The correct K8s version numbers  for AKS Engine 0.70.0 are 1.21.10, 1.22.7, see https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#aks-engine-versions

Please correct all instances throughout the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2108#aks-engine-and-corresponding-image-mapping)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@[walterov](https://github.com/walterov) #in-progress

**Comment by mattbriggs** [comment]
Updated: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/10047

**Comment by mattbriggs** [comment]
#please-close
