### ISSUE TITLE
Remove ATA References under Protect identities

### ISSUE THREAD

**Issue by TrentShoun** [MicrosoftDocs/azure-stack-docs#1948]
Under "Protect identities" we need to remove references to ATA (Advanced Threat Analytics" as it's no longer a supported product. I believe the section should be replaced with Endpoint protection. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a0c2cfb-d58d-04c3-c4f7-0aa1accc7c9f
* Version Independent ID: f16ff48f-c6a2-c1eb-9600-7a7431ebcf34
* Content: [Azure Stack HCI security considerations - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/security#protect-identities-1)
* Content Source: [azure-stack/hci/concepts/security.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/security.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by kobulloc-MSFT** [comment]
@TrentShoun Thank you for the feedback!  We've assigned this to the document author for further review.

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by alkohli** [comment]
Since there is no request to keep this issue open, closing this issue. #please-close

**Comment by TrentShoun** [comment]
The docs need to be updated. I am not sure why this was closed?

**Comment by alkohli** [comment]
@TrentShoun You can open the same issue using the https://aka.ms/ContentUserFeedback. Please note that Git issues are being phased out and will be replaced very soon by the feedback tool.

**Comment by TrentShoun** [comment]
I was just trying to help improve the docs, I submitted this a long time ago an di have no idea why it wasn't addressed. I am not going to open another request.

**Comment by alkohli** [comment]
@TrentShoun I can certainly keep it open so it gets addressed here instead of user feedback. Thank you!

**Comment by alkohli** [comment]
#hold-off
