### ISSUE TITLE
Minimum Stack Version is Unclear

### ISSUE THREAD

**Issue by jamesorlando** [MicrosoftDocs/azure-stack-docs#1951]
The doc for ALL 2102 Hotfixes state the minimum version the Hotfix applies to is 1.2102.28.82 This includes the 1.2102.28.87 update. First, I get the feeling this is not accurate for 1.2102.28.82 to be the minimum for 1.2102.28.87. Second, if it is accurate there is no hotfix available in the public facing docs that can get a 1.2102.0.10 build patched. 

Example: 
Dell deployed 1.2102.0.10

Lowest 2102 Hotfix Available is 1.2102.28.87, but it states you must be on 1.2102.28.82 or later to apply it. 

Again, all hotfixes available are dependent on the same minimum version, but that version is not available. 

Thanks for clarifying! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6619aa86-98cd-a037-be5b-5058d992422b
* Version Independent ID: be9ef7c3-30db-dbfd-19ef-d9302d0cb963
* Content: [Azure Stack Hub hotfix 1.2102.30.102 - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/hotfix-1-2102-30-102?view=azs-2102)
* Content Source: [azure-stack/operator/hotfix-1-2102-30-102.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/hotfix-1-2102-30-102.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@jamesorlando 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.
