### ISSUE TITLE
getkuberneteslogs.sh is used to collect k8s cluster logs which deployed by aks engine not apply to AKS n azure stack hub.

### ISSUE THREAD

**Issue by Lihailian** [MicrosoftDocs/azure-stack-docs#1954]
Hi Team,

In this guide, it is for AKS on azure stack hub issue troubleshoot. Commands was given to collect k8s cluster logs. 
But seems "getkuberneteslogs.sh" collects diagnostics from Kubernetes clusters provisioned by AKS Engine. Furthermore, it asks to provide "-i, --identity-file" while aks on azure stack hub deployment don;t provide keys. Could you update with correct log collection steps for AKS instead of aks engine please?

###
vmadmin@ubuntuv20:~$  ./getkuberneteslogs.sh -h
./getkuberneteslogs.sh collects diagnostics from Kubernetes clusters provisioned by AKS Engine

Usage:
  ./getkuberneteslogs.sh [flags]

Flags:
  -u, --user                        The administrator username for the cluster VMs
  -i, --identity-file               RSA private key tied to the public key used to create the Kubernetes cluster (usually named 'id_rsa')
  -g, --resource-group              Kubernetes cluster resource group
      --api-model                   AKS Engine Kubernetes cluster definition json file
      --upload-logs                 Persists retrieved logs in an Azure Stack storage account
      --disable-host-key-checking   Sets SSH's StrictHostKeyChecking option to "no" while the script executes. Only use in a safe environment.
  -h, --help                        Print script usage

Examples:
  ./getkuberneteslogs.sh -u azureuser -i ~/.ssh/id_rsa -g k8s-rg --disable-host-key-checking
  ./getkuberneteslogs.sh -u azureuser -i ~/.ssh/id_rsa -g k8s-rg -n default -n monitoring
  ./getkuberneteslogs.sh -u azureuser -i ~/.ssh/id_rsa -g k8s-rg --upload-logs --api-model clusterDefinition.json
  ./getkuberneteslogs.sh -u azureuser -i ~/.ssh/id_rsa -g k8s-rg --upload-logs
vmadmin@ubuntuv20:~$
###

Regards,
Hailian LI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56eab102-1391-3548-8ea7-6939d6cc0571
* Version Independent ID: 75d5a414-c2db-eee5-2e16-fe07da02aed7
* Content: [Troubleshoot the Azure Kubernetes Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/aks-troubleshoot?view=azs-2108)
* Content Source: [azure-stack/user/aks-troubleshoot.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/aks-troubleshoot.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by shwetamathur7** [comment]
@Lihailian Thanks for your feedback. I have assigned the issue to author to update further.

**Comment by sethmanheim** [comment]
@Lihailian Very sorry for the slow response, and thank you for reaching out. As the docs have been extensively updated, we are closing older GitHub issues. If you still need assistance, please open a new feedback request. #please-close
