### ISSUE TITLE
Pool quorum is not working like this since Windows Server 2019

### ISSUE THREAD

**Issue by jaromirk** [MicrosoftDocs/azure-stack-docs#1956]
[Enter feedback here]

Hey all,

pool quorum behavior changed in Windows Server 2019. No longer every disk has vote, but only selected amount of disks... 

Here is proof:
https://github.com/microsoft/MSLab/blob/master/Scenarios/S2D%20and%20Metadata%20deep%20dive/readme.md#exploring-pool-metadata

metadata=vote ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8ae0877-f926-fdd3-9ea7-274dd5c592f3
* Version Independent ID: 9b310a25-9c2c-ca6d-5622-08389d850a51
* Content: [Understand cluster and pool quorum on Azure Stack HCI and Windows Server clusters - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/quorum?source=docs#how-pool-quorum-works)
* Content Source: [azure-stack/hci/concepts/quorum.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/quorum.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by SreejaBhattacharya-MSFT** [comment]
@jaromirk 
Thanks for reaching out. Could you please mention how would you like us to help here as this issue has been opened in the Documentation channel. Do you want us to make any documentation changes for this ?

**Comment by jaromirk** [comment]
I think Cosmos Darwin created graphics while Jason Gerend documented it. I cannot recall the dev name now, who was responsible modifying pool quorum logic. I think failover clustering is now owned by Rob Hindman, but not sure :).

**Comment by SreejaBhattacharya-MSFT** [comment]
Thanks @jaromirk 
@JasonGerend could you please look into this?

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by alkohli** [comment]
Since there is no request to keep this open, closing this one. #please-close
