### ISSUE TITLE
Link broken, powershell

### ISSUE THREAD

**Issue by fe77** [MicrosoftDocs/azure-stack-docs#1961]
Hi Team
On the page we have this text : "If you’ve already set up AKS-HCI on your Azure Stack HCI cluster, you cannot currently deploy Arc Resource Bridge through Windows Admin Center. Use the command line instructions for Arc Resource Bridge deployment instead. For information about the command line deployment, see [Deploy Arc Resource Bridge using command line](https://docs.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-wac)."
But as you can see, the "deploy using command line" seem to point on ".. deploy using WAC".
What would be the link and could we update it ?
Thanks
fred

**Comment by sethmanheim** [comment]
@fe77 Please specify which article you're referring to, thank you.

**Comment by fe77** [comment]
Hi,
If you click the link on the previous post you will land on it. Locate then the text I mentioned, and you will see that it points to "itself", not the part related to "command line".
regards
fred

**Comment by sethmanheim** [comment]
@fe77 Got it, thanks for catching. This will be updated today. #please-close
