### ISSUE TITLE
Find the "edit" button

### ISSUE THREAD

**Issue by fe77** [MicrosoftDocs/azure-stack-docs#1962]
Team
On this text "To check all the prerequisites that should be met to deploy Arc Resource Bridge on an Azure Stack HCI Cluster, select Settings when connected to a cluster and navigate to Azure Arc VM setup for Azure Stack HCI.".. it took some time to locate the right place to go. Just as a feedback, I went on the EDIT logo at the top right of the screen, and had to select the bottom left, which in my lab is partially hidden. 
I wanted to share that with you in case you think you need to add more details.
Regards
fred

**Comment by sethmanheim** [comment]
@fe77 Not sure what the documentation issue is here? Please clarify.

**Comment by sethmanheim** [comment]
OK, per our discussion, thank you @fe77 for catching this, and I will update it on the livesite today. #please-close
