### ISSUE TITLE
Wrong example used

### ISSUE THREAD

**Issue by TheOnlyWei** [MicrosoftDocs/azure-stack-docs#1964]
Wrong example used in the example section:
https://docs.microsoft.com/en-us/azure-stack/reference/pep/set-graphapplication#example-1

The example uses "new-graphapplication", when the article is about "set-graphapplication".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbc64dc6-6940-75d9-c2d1-fd179852719e
* Version Independent ID: fe233957-64b8-b790-11a4-6981753ad70f
* Content: [Set-GraphApplication privileged endpoint for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/reference/pep/set-graphapplication)
* Content Source: [azure-stack/reference/pep/Set-GraphApplication.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/reference/pep/Set-GraphApplication.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
Thanks @TheOnlyWei. We'll get this fixed..

**Comment by V-GSOLER** [comment]
@BryanLa 
Task updated in ADO: https://dev.azure.com/mseng/TechnicalContent/_queries/edit/1961186/?queryId=90a6e983-15c6-4225-b0f8-7fd8237428cb
Preview: [Set-GraphApplication privileged endpoint for Azure Stack Hub - Azure Stack Hub | Microsoft Docs](https://review.docs.microsoft.com/en-us/azure-stack/reference/pep/set-graphapplication?branch=pr-en-us-10360)
Pull Request: [User Story 1961186 Wrong example PEP Set-GraphApp by V-GSOLER · Pull Request #10360 · MicrosoftDocs/azure-stack-docs-pr (github.com)](https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/10360)

**Comment by sethmanheim** [comment]
This appears to be fixed although the issue was never closed. Closing now...
