### ISSUE TITLE
SDN on HCI Single Node cluster

### ISSUE THREAD

**Issue by xzrian** [MicrosoftDocs/azure-stack-docs#1966]
Hi,
Do you have any supporting case scenario of running SDN on HCI Cluster single node?
i did encounter issue based on screenshot below.
![image](https://user-images.githubusercontent.com/47202302/176083912-41bd1b60-6897-4e01-9461-b761a876fa9a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6db0c266-9042-4171-77fe-666d43eeba15
* Version Independent ID: fbce33cb-7178-5933-e35d-1f5b40af00f5
* Content: [Software defined networking (SDN) in Azure Stack HCI and Windows Server - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/software-defined-networking)
* Content Source: [azure-stack/hci/concepts/software-defined-networking.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/software-defined-networking.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @AnirbanPaul
* Microsoft Alias: **anpaul**

**Comment by AshokPeddakotla-MSFT** [comment]
@xzrian Please help with the link of document on which above document feedback request is created. 
Under this repository we want to make sure any issue is linked to a doc so we can help others that may be having the same issue.

**Comment by xzrian** [comment]
hi @AshokPeddakotla-MSFT 

sorry didnt notice the email.
below are the docs as per requested.
https://docs.microsoft.com/en-us/azure-stack/hci/concepts/software-defined-networking

**Comment by AnirbanPaul** [comment]
Hi, can you remove the regkey on the HCI host as referenced in the below article and try again: https://docs.microsoft.com/en-us/azure-stack/hci/deploy/sdn-wizard#redeploy-sdn-network-controller

**Comment by VikasPullagura-MSFT** [comment]
@AnirbanPaul Thanks for sharing the details.

**Comment by VikasPullagura-MSFT** [comment]
@xzrian Can you please try the suggestion and see if that helps.

**Comment by VikasPullagura-MSFT** [comment]
@xzrian 
Hope the provided information is helpful.

We will now close this issue. If there are further questions regarding this, please tag me in a comment. I will reopen it and we will continue the discussion.

**Comment by xzrian** [comment]
Hi Anirban

I believe we met on SDN support email.
Yes i did run the command to remove and try to add again.
did not work


Just to add on that currently I’m running azure stack hci on top of unsupported hardware( no RDMA, no 10G, unmanaged switch with no DCBX)

Do let me know if you have case scenario where the SDN running on Single node cluster.
