### ISSUE TITLE
Outdated WAC Screen shots.

### ISSUE THREAD

**Issue by rjstephan** [MicrosoftDocs/azure-stack-docs#1969]
[Enter feedback here]

I am using WAC 2110.2 with my Azure Stack HCI cluster and all of the screenshots appear to be incorrect.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0343338-2574-7945-e13d-dd000ba634bb
* Version Independent ID: 9b0e602d-151e-7502-e389-c3bb56794841
* Content: [Get started with Azure Stack HCI and Windows Admin Center - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/get-started)
* Content Source: [azure-stack/hci/get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/get-started.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by kobulloc-MSFT** [comment]
@rjstephan Thank you for your feedback!  We've assigned this to the document author for further review.

**Comment by ronmiab** [comment]
@kobulloc-MSFT - this issue is now resolved. Images from the Get Started article have been updated and content revised as needed.

**Comment by ronmiab** [comment]
#close

**Comment by sethmanheim** [comment]
#please-close
