### ISSUE TITLE
VSCode Azure Accounts extension config value for azure.cloud should always be "AzureCustomCloud"

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#1970]
From **Set up the Azure Account extension -> Step 7 -> Values:**

azure.cloud | The name of your environment.
-- | --

However, I don't think this parameter should be changed to the name of the environment, it appears to required the literal string ["AzureCustomCloud"](https://github.com/microsoft/vscode-azure-account/blob/6fa3cab0b8f1784a3183fe38ad89055ed190bea7/package.json#L148).

I tried in a lab environment with the environment name already used by Get-AzEnvironment and Get-AzContext, and it didn't work. 

I needed to change my settings.json back to the default ```    "azure.cloud": "AzureCustomCloud",``` before it would sign in and load the subscriptions.

Unrelated but the code snippit in the same step is also missing a closed-caret symbol: ``` "azure.tenant": "<your-tenant-ID",``` .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d8803f5-7736-6a29-98df-69c121d43c95
* Version Independent ID: d88f693f-cade-48ee-df03-d2363298ef0d
* Content: [Connect to Azure Stack Hub using Azure Account Extension in Visual Studio Code - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-dev-start-vscode-azure?view=azs-2108#set-up-the-azure-account-extension)
* Content Source: [azure-stack/user/azure-stack-dev-start-vscode-azure.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-dev-start-vscode-azure.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by alexsmithMSFT** [comment]
@BryanLa you summed up the two issues perfectly.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/26260056/177846089-09b26453-1d5a-438f-a99d-495512285af3.png">

**Comment by sethmanheim** [comment]
This has been fixed, but I guess this issue wasn't closed.
