### ISSUE TITLE
msk8s.api.cdp.microsoft.com is not available 

### ISSUE THREAD

**Issue by munir94** [MicrosoftDocs/azure-stack-docs#1973]
While trying to install akshci mgmt node, i stumble on this error , 

![image](https://user-images.githubusercontent.com/39366930/179702915-13e92425-02f4-4dc4-a9b8-d5d7b33c7c1b.png)

while trying to resolve the issue , and try to test the connectivity , it seems like the url is not available, tried from multiple device and multiple internet connection

![image](https://user-images.githubusercontent.com/39366930/179702634-82cfb35d-df87-4f7f-a7d2-18679f844ff8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2058b8-318d-da2b-6dc7-04d4b3dffc9e
* Version Independent ID: 0e997ca9-22fa-19c3-a5d3-71fe840843fc
* Content: [Troubleshoot known issues and errors when installing Azure Kubernetes Service on Azure Stack HCI and Windows Server](https://docs.microsoft.com/en-us/azure-stack/aks-hci/known-issues-installation)
* Content Source: [azure-stack/aks-hci/known-issues-installation.yml](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/known-issues-installation.yml)
* Service: **azure-stack**
* GitHub Login: @mattbriggs

**Comment by munir94** [comment]
Hi @dineshgovindasamy , as per my checking , the issue is still there

**Comment by dineshgovindasamy** [comment]
@madhanrm FYI

**Comment by dineshgovindasamy** [comment]
Sorry @munir94 one more thing. Could you please update the PS Module and then try again? the fix was in the updated PS module.

Update-Module -Name AksHci -Force -AcceptLicense

**Comment by munir94** [comment]
Hi @dineshgovindasamy , 
here is the result on running the update module command 
![image](https://user-images.githubusercontent.com/39366930/180107161-3cfa29f5-ea8b-4e7d-8cb8-95fcd5db91be.png)

**Comment by AjayBathini-MSFT** [comment]
#please-close
