### ISSUE TITLE
Azure AD Graph API Tools for ADFS Identity users

### ISSUE THREAD

**Issue by TheBlackMini** [MicrosoftDocs/azure-stack-docs#1974]
This page was last edited on the 11/11/2021 and goes on to say that the article will be updated in the future with a list of supported tools for ADFS users.

"This article will be updated in the future and list supported tooling versions for Azure Stack Hub for AD FS."

Just wondering, now that the API has now been retired and ADFS hasn't been updated to support the new API. Has anyone compiled the list of supported tools? Are there plans to update the ADFS Identity platform to support the new API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 764b6c42-4350-84e5-7140-f8a986a5cf0c
* Version Independent ID: 0cbe20d5-9151-9209-1b75-6fba1c688040
* Content: [Overview of identity providers for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-identity-overview?view=azs-2206#azure-ad-graph)
* Content Source: [azure-stack/operator/azure-stack-identity-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-identity-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by keystroke** [comment]
Hi @TheBlackMini, there is no update yet for different Azure Stack tooling for AAD versus ADFS environments. When such a time comes, we'll update that documentation and mention it in release notes, etc.

**Comment by sethmanheim** [comment]
#please-close
