### ISSUE TITLE
Link to Sandbox Guide

### ISSUE THREAD

**Issue by jkingdon-ms** [MicrosoftDocs/azure-stack-docs#1975]
Need a link to this guide https://github.com/microsoft/AzStackHCISandbox on this page at the end, as it is currently the best one out there, with minimal issues. Tried the Private Forest guide and the HCI Eval guide, both of those guides have blocking issues right now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58cb678-2c81-b3c2-cfce-9ff96c0e18cc
* Version Independent ID: b34bb724-ea12-7063-8d9c-0ff0ae6db190
* Content: [Nested virtualization in Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/nested-virtualization)
* Content Source: [azure-stack/hci/concepts/nested-virtualization.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/nested-virtualization.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by MarileeTurscak-MSFT** [comment]
@jkingdon-ms 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by MarileeTurscak-MSFT** [comment]
Thanks! I had made a pull request to add this, but looks like you beat me to it. :) https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/10439

**Comment by jkingdon-ms** [comment]
Thanks Marilee!

**Comment by jkingdon-ms** [comment]
Looks like I don't have access to re-open the issue though @MarileeTurscak-MSFT
