### ISSUE TITLE
sequence for dynamic ip address not working

### ISSUE THREAD

**Issue by nicolgit** [MicrosoftDocs/azure-stack-docs#1978]
I am following this step-by-step procedure for dynamic ip address

at the step "If AKS on Azure Stack HCI and Windows Server is not installed. Run the following cmdlets to provide an IP address to your Azure Arc Resource Bridge VM:"

when I execute

`Set-MocConfig -workingDir $csv_path\ResourceBridge  -vnet $vnet -imageDir $csv_path\imageStore -skipHostLimitChecks -cloudConfigLocation $csv_path\cloudStore -catalog aks-hci-stable-catalogs-ext -ring stable`

i receive the following error:

`Cloud Service IP CIDR is required when using static IP assignment.`

but I am following the procedure for DYNAMIC ip address!

any advice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2b89ce1-6af9-aaa1-48f2-da8d2f5c8b75
* Version Independent ID: db6c5f7c-77b2-7a97-dc2c-d904db88edf5
* Content: [Deploy Azure Arc Resource Bridge using command line - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-dynamic-ip-address)
* Content Source: [azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by ManikaDhiman** [comment]
@nicolgit: Thanks for reaching out.
@ZmanKyle: Could you please look into this? Thanks!

**Comment by ZmanKyle** [comment]
@nicolgit I cleaned up my environment and re-tried dynamic IP configuration. It did not give me any error for the same steps. Could you try to upgrade/reinstall moc module and other related modules and try again? Let me know if you see the same error.
@ksurjan any thought on this?

**Comment by ksurjan** [comment]
@nicolgit  - If the hosts are configured to have static IP configuration, then you would need cloudServiceIP.
If the hosts are dynamic, then you don't need it.
