### ISSUE TITLE
BootStrapper version

### ISSUE THREAD

**Issue by lucidqdreams** [MicrosoftDocs/azure-stack-docs#198]
Install-Module -Name AzureRm.BootStrapper -Force should probably include a version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dabc86bd-3770-5832-7fa5-d28856998ae6
* Version Independent ID: cbdb8c6f-ad4d-9e3d-a490-f1348b5ccdfa
* Content: [Using SQL databases on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-deploy)
* Content Source: [azure-stack/operator/azure-stack-sql-resource-provider-deploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-sql-resource-provider-deploy.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by msrini-MSFT** [comment]
@lucidqdreams , Thank you for your feedback, We will investigate and get back to you.

**Comment by mattbriggs** [comment]
#lucidqdreams I've added the current version of Bootstrapper and the requiredversion flag. Thanks for your feedback. The update will be posted with the next doc build. Thanks!

**Comment by mattbriggs** [comment]
#please-close
