### ISSUE TITLE
Inconsistent 2206 upgrade instructions

### ISSUE THREAD

**Issue by aserfass-msft** [MicrosoftDocs/azure-stack-docs#1981]
There appear to be inconsistent requirements in the documentation.

This says to update from 1.2108.2.111 to 2206 
"Hotfix prerequisites: before applying the 2206 update
The 2206 release of Azure Stack Hub must be applied on the 2108 release with the following hotfixes:

[Azure Stack Hub hotfix 1.2108.2.111](https://docs.microsoft.com/en-us/azure-stack/operator/hotfix-1-2108-2-111?view=azs-2206)"
Source: https://docs.microsoft.com/en-us/azure-stack/operator/release-notes?view=azs-2206

But the 1.2206.1.24 hotfix docs say this:
"Hotfix information
To apply this hotfix, you must have version 1.2206.0.6 or later."
Source: https://docs.microsoft.com/en-us/azure-stack/operator/hotfix-1-2206-1-24?view=azs-2206

However, 1.2206.0.6 doesn't appear to exist.

Can you confirm that going from 1.2108.2.111 to 1.2206.1.24 is the correct sequence?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e05517-6ffa-ad32-ec69-d3299492d880
* Version Independent ID: 2d6ffb4c-9134-a390-3f90-2322c9182e76
* Content: [Azure Stack Hub release notes - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/release-notes?view=azs-2206)
* Content Source: [azure-stack/operator/release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/release-notes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by sethmanheim** [comment]
Please contact Microsoft Support, as on the documentation side, I have no visibility into versioning schemes. Thanks for reaching out! #please-close
