### ISSUE TITLE
SDN re-deployment wizard cannot be displayed if Customer want to deploy again

### ISSUE THREAD

**Issue by JasonMei11** [MicrosoftDocs/azure-stack-docs#1982]
[Enter feedback here]

HI Team,

we have a customer deployed SDN via WAC, but for some reason, customer want to redeploy it agian. We follow the doc that remove NC and NC host agent resgistry settings, but the SDN deployment wizard cannot be displayed, then casuse customer cannot deploy the SDN again. Finally, we just remove the cluster from WAC and then add the cluster to WAC for management, the we can see the SDN deploy wizard. So  i just want to let you know if we can add this steps to make the steps more accurate and save customer time and efforts, thanks !

BR,
Jason Mei

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842bf434-fd3f-5a56-4dee-794858175bed
* Version Independent ID: 779df781-d6a7-0a43-1f1a-2fc66eb9e82f
* Content: [Deploy SDN using Windows Admin Center - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/sdn-wizard)
* Content Source: [azure-stack/hci/deploy/sdn-wizard.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/sdn-wizard.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by VikasPullagura-MSFT** [comment]
@JasonMei11 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@ManikaDhiman 
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManikaDhiman** [comment]
Hi @VikasPullagura-MSFT, I started an internal thread to review this issue and update the article as needed. Thanks!

**Comment by ManikaDhiman** [comment]
Hi @JasonMei11: Thanks for your feedback! The [Redeploy SDN Network Controller](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/sdn-wizard#redeploy-sdn-network-controller) section is now updated with an additional step as described in your feedback. Thanks again for helping us improve our docs!

@VikasPullagura-MSFT: Please review the changes and close this issue. Thanks!

#please-close
