### ISSUE TITLE
Az Connect missing details 

### ISSUE THREAD

**Issue by BrunoStack** [MicrosoftDocs/azure-stack-docs#1985]
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-create-and-publish-marketplace-item?view=azs-2206&tabs=az#publish-a-marketplace-item
Connect to Azure Stack Hub using Az module misses the tenant information which is causing confusion when customer follows this article to create and publish marketplace.

Refer this link for missing tenant information. 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/98544255/181864745-efbb604f-d485-48d2-a095-dd33357f1c63.png)
 https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-configure-admin?view=azs-2206&tabs=az1%2Caz2%2Caz3#connect-with-azure-ad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e401ae26-588f-124f-09a8-f1f6dc75da4e
* Version Independent ID: 6a9509a1-f16c-f527-5df1-9dae2d8eeaed
* Content: [Create and publish a Marketplace item in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-create-and-publish-marketplace-item?view=azs-2206&tabs=az#publish-a-marketplace-item)
* Content Source: [azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by sethmanheim** [comment]
@BrunoStack Thank you for the feedback. Can you please be more specific about what the documentation issue is here? Setting the tenant name is part of the script.
