### ISSUE TITLE
Wrong documentation.

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/azure-stack-docs#1988]
The documentation is wrong regarding not using keys when using Windows Server Subscription.

![image](https://user-images.githubusercontent.com/31531703/182470553-27450234-137b-4a5e-a715-57bc9be34a1c.png)

Need to use AVMA key activation.

https://docs.microsoft.com/en-us/windows-server/get-started/automatic-vm-activation

Open a support ticket.  I was instructed to use the AVMA key.

Support request number:	2207220040000250

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/gabri/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/gabri/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/gabri/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=PT-BR style='tab-interval:35.4pt;word-wrap:break-word'>

Support request   number: | 2207220040000250
-- | --

</body>

</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c086461c-e2e8-e77a-012d-5279421b3aa6
* Version Independent ID: 821170a9-9de2-418f-7f05-baf06d915d64
* Content: [Activate Windows Server VMs using Automatic Virtual Machine Activation - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/vm-activate?WT.mc_id=WDIT-MVP-5003815)
* Content Source: [azure-stack/hci/manage/vm-activate.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/vm-activate.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
Hi @gabrielluizbh -- thank you for pointing this out, we are aware of the issue and I have a PR already filed to fix it. I am changing that table entry to "No host-side keys – AVMA is automatically enabled. After it's enabled, you can then apply the generic AVMA keys on the client side." Thanks again for the feedback.
