### ISSUE TITLE
Storage Tiers monitoring and reporting

### ISSUE THREAD

**Issue by i3laze** [MicrosoftDocs/azure-stack-docs#1989]
There's no documentation on monitoring and reporting of Storage Tiers performance and cache hit ratio.
One for Server 2012 and defrag.exe is currently obsolete:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn789160(v=ws.11)

Previous issue was auto closed without resolution:
https://github.com/MicrosoftDocs/azure-stack-docs/issues/1510

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73197027-3340-4b3a-ea69-87737dd7152a
* Version Independent ID: c28e92b8-46d5-31b1-44ce-abec49cfcf3a
* Content: [Create volumes on Azure Stack HCI and Windows Server clusters - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/create-volumes)
* Content Source: [azure-stack/hci/manage/create-volumes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/manage/create-volumes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by KranthiPakala-MSFT** [comment]
Thanks for the feedback! We have assigned the issue to the content author to further review this and update the document as appropriate.

**Comment by khdownie** [comment]
@i3laze @KranthiPakala-MSFT I am no longer on the HCI team so I'm asking @JasonGerend to recommend someone else to assign this to. Thanks!

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by alkohli** [comment]
Since there is no request to keep this open, will be closing this. #please-close
