### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by jonjunell** [MicrosoftDocs/azure-stack-docs#1991]
My team and I are deploying Azure Arc Resource Bridge and we'd like to know if we run the scripts from a HCI cluster member, or from an external server.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2b89ce1-6af9-aaa1-48f2-da8d2f5c8b75
* Version Independent ID: db6c5f7c-77b2-7a97-dc2c-d904db88edf5
* Content: [Deploy Azure Arc Resource Bridge using command line - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address)
* Content Source: [azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by ZmanKyle** [comment]
@jonjunell You need to run the scripts from an HCI node.

**Comment by kobulloc-MSFT** [comment]
@jonjunell We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
