### ISSUE TITLE
Schema is incorrect

### ISSUE THREAD

**Issue by jbpaux** [MicrosoftDocs/azure-stack-docs#20]
Hello, the schema https://docs.microsoft.com/en-us/azure/azure-stack/media/azure-stack-integrate-dns/integrate-dns-01.png is incorrect :
* Name servers are azs-ns01/ns02 and not azs-Dns01/Dns02 (the D should be removed)
* forwarded zone should be the same as in the text (east.cloud.fabrikam.com and not sea.azurestack.external)
* another zone should be included in the ns01/ns02 servers : east.cloudapp.cloud.fabrikam.com)

Please update it to match the rest of the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cf7c779-041d-a232-b441-b769be1aaa67
* Version Independent ID: 2b4f5bc1-66f6-4c7f-c06e-bc32f2acd383
* Content: [Azure Stack datacenter integration - DNS](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-integrate-dns)
* Content Source: [articles/azure-stack/azure-stack-integrate-dns.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-dns.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by mattbriggs** [comment]
@jbpaux Thanks for your feedback. I have a note out and will update as soon as I have an updated diagram. #in-progress

**Comment by TravisCragg-MSFT** [comment]
@PatAltimore @mattbriggs This is still not fixed, bumping this issue up.

**Comment by PatAltimore** [comment]
Updated diagram based on feedback.

#please-close

**Comment by jbpaux** [comment]
@PatAltimore I don't see updates :( 
https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/media/azure-stack-integrate-dns/integrate-dns-01.svg
There are sill mention of azs-Dns01 instead of ns01, the sea.azurestackhub.external, the missing zone for cloudapp.
