### ISSUE TITLE
Do we have RS5 (Build 17763) based ASDK 

### ISSUE THREAD

**Issue by agvardha** [MicrosoftDocs/azure-stack-docs#200]
Hello,

I have ASDK running on Windows Server 2016 with OS Version 10.0.14393. Do we have ASDK for OS Version 17763? Any time line on its availability? Thanks

**Comment by femsulu** [comment]
Thanks for your comment. We are actively investigating and will get back to you shortly. Thanks for your patience.

**Comment by agvardha** [comment]
@TravisCragg-MSFT please note I work for company which has close ties with MSFT. I do have the xxxx@azureadminyyyy.onmicrosoft.com account. If that gives me some special access where ordinary public do not get access give that info to. So please do not restrict your answer to general public. Thanks

**Comment by TravisCragg-MSFT** [comment]
@agvardha The ASDK should come with its own 2016 server operating system. Are you looking for when the OS version for the ASDK will be increased to 17763 or greater?

**Comment by agvardha** [comment]
Exactly I am looking for when the OS version of the ASDK will be increased to 17763 05 greater. Thanks

**Comment by TravisCragg-MSFT** [comment]
@agvardha We do plan on updating the OS version in the future, but I cannot give a time range at this time.

**Comment by agvardha** [comment]
@TravisCragg-MSFT ok thanks :(
