### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/azure-stack-docs#2004]
I tested several times to enable the benefit of azure in the VM with it running.
Did not work.

Finally I turned off the VM and enabling the azure benefit enabled the VM.

Documentation should inform that for activation the VM must be in a shutdown status.

![image](https://user-images.githubusercontent.com/31531703/185006230-f5024300-4424-47fe-a379-93f5c8f3647c.png)
![image](https://user-images.githubusercontent.com/31531703/185006269-ee0f8cd1-d442-4edd-860f-fde877787849.png)

Or am I wrong, try activating on a gen 1 vm with windows server 2008 r2.

At the time of the error the vm was running, after shutting down it worked.

![image](https://user-images.githubusercontent.com/31531703/185006720-9e00bddb-8bfc-4f47-87de-e6aaebd58091.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c98d186-ef81-48f0-7e70-301b3ad92f09
* Version Independent ID: 8552ac82-b862-f27d-e8df-5e4a8612d9ea
* Content: [Azure Benefits on Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-benefits?WT.mc_id=WDIT-MVP-5003815#azure-benefits-available-on-azure-stack-hci)
* Content Source: [azure-stack/hci/manage/azure-benefits.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/azure-benefits.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by PriyankaRudramaina** [comment]
@gabrielluizbh,

Thank you for your feedback. We will investigate and update the thread further.

**Comment by PriyankaRudramaina** [comment]
@gabrielluizbh,

Thanks again for surfacing this feedback. So here is the update, if it is a Gen 1 VM then yes, you need a shutdown. Gen 2 VMs do not need to be shutdown.

We will add this as a note in the document https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-benefits?WT.mc_id=WDIT-MVP-5003815#azure-benefits-available-on-azure-stack-hci

For any further queries or concerns, please feel free to tag me in your comments and I will be happy to help.
