### ISSUE TITLE
Confusing documentation.

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/azure-stack-docs#2005]
Confusing documentation.

Documentation for using Azure Stack HCI to make use of ESUs, very confusing.

And the link that says it is necessary to read is from 2020.
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/obtaining-extended-security-updates-for-eligible-windows-devices/ba-p/1167091

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1090bd3e-257f-603d-9f80-cb609c9376a5
* Version Independent ID: 70ddb1d7-854f-b1e9-6428-0f2d4982018c
* Content: [Extended Security Updates (ESU) on Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-benefits-esu)
* Content Source: [azure-stack/hci/manage/azure-benefits-esu.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/azure-benefits-esu.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by PriyankaRudramaina** [comment]
@gabrielluizbh,

Thank you for your feedback. We will investigate and update the thread further.

**Comment by PriyankaRudramaina** [comment]
@gabrielluizbh,

The blog post that is added for reference is to know what the installation prerequisites for ESUs are. Even though it is dated back to 2020, it is still applicable. The document is getting updated as and when there are more updates.(3 updates in the top from 2021)
[blog post](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-benefits-esu#prerequisites)

It is an important information post for users who were unable to complete the transition from Windows 7 Pro or Enterprise to Windows 10—or from Windows Server 2008 and 2008 R2 Datacenter, Enterprise, or Standard to the latest version of Windows Server—prior to the end of support on January 14, 2020

To clear your confusion, for the Azure Stack customers there are 2 things to know as per this [document](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-benefits-esu#tutorial-get-free-esus-through-azure-stack-hci):

1. Benefits of getting ESU for VMs on Azure Stack HCI
Free of charge: You can get ESUs through Azure Stack HCI for free.
Get an additional year of ESUs for Windows Server and SQL Server 2008 and 2008 R2: On Azure and Azure Stack HCI only, ESUs for Windows Server and SQL Server 2008 and 2008 R2 will end on January 14, 2024 and July 12, 2023 respectively; a year longer than the usual three-year ESU programs.

2. **[How to Enable Azure Benefits](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-benefits#enable-azure-benefits)**
Before enabling azure benefits you can read about the prerequisites from the [blog post](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-benefits-esu#prerequisites).

This document has all the required details will not be making any changes at the moment. 

Note: This channel is for driving improvements towards MS Docs.  If you need any further information in understanding the process described in the document, please feel to tag me in the comments or create a Q&A thread on the microsoft Q&A [platform](https://docs.microsoft.com/en-us/answers/questions/ask.html).
