### ISSUE TITLE
Secrets Store CSI Driver still pointing to old URL

### ISSUE THREAD

**Issue by cgatjens** [MicrosoftDocs/azure-stack-docs#2006]
Microsoft Documentation is still pointing to the old GitHub URL for Secrets Store CSI Driver:

Install the Secrets Store CSI Driver

helm repo add **csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts**

GitHub page describes that a new URL should be used - https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure

Note: The helm chart repository URL has changed from https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts to https://azure.github.io/secrets-store-csi-driver-provider-azure/charts.

Run the following commands to update your Helm chart repositories if using the old URL:

helm repo add csi-secrets-store-provider-azure https://azure.github.io/secrets-store-csi-driver-provider-azure/charts --force-update
helm repo update

Can we please update Microsoft document to reflect the new URL?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48500978-a4c7-4fd8-2c5a-3fca53607600
* Version Independent ID: d87865b6-266a-a2fb-631a-d7f66b62e304
* Content: [Kubernetes Secrets Store CSI Driver integration with  Azure Kubernetes Service on Azure Stack HCI and Windows Server - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/secrets-store-csi-driver#install-the-secrets-store-csi-driver)
* Content Source: [azure-stack/aks-hci/secrets-store-csi-driver.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/secrets-store-csi-driver.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@cgatjens Thank you for reaching out. Actually this was updated a few days ago and the URL was updated to https://azure.github.io/secrets-store-csi-driver-provider-azure/charts.

#please-close
