### ISSUE TITLE
Question: Secrets Store CSI Driver with AKS on Azure Stack HCI is GA or not?

### ISSUE THREAD

**Issue by tksh164** [MicrosoftDocs/azure-stack-docs#2007]
The document has the following note. Is this note meaning Secrets Store CSI Driver with AKS on Azure Stack HCI still preview feature?

> AKS on Azure Stack HCI and Windows Server preview features are available on a self-service, opt-in basis. Previews are provided "as is" and "as available," and it's recommended that you do not use these features in production scenarios. AKS on Azure Stack HCI and Windows Server preview features are partially covered by customer support on a best-effort basis.

![image](https://user-images.githubusercontent.com/1618784/185308262-a5d21cfb-9f8f-4d5d-9e2a-dfd5dedb9e5a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48500978-a4c7-4fd8-2c5a-3fca53607600
* Version Independent ID: d87865b6-266a-a2fb-631a-d7f66b62e304
* Content: [Kubernetes Secrets Store CSI Driver integration with  Azure Kubernetes Service on Azure Stack HCI and Windows Server - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/secrets-store-csi-driver#feedback)
* Content Source: [azure-stack/aks-hci/secrets-store-csi-driver.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/secrets-store-csi-driver.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SreejaBhattacharya-MSFT** [comment]
@tksh164 Thanks for reaching out. We will investigate and update the thread further.

**Comment by SreejaBhattacharya-MSFT** [comment]
> Azure Key Vault Provider for Secrets Store CSI Driver is an open source project that is [not covered by the Microsoft Azure support policy](https://support.microsoft.com/en-us/help/2941892/support-for-linux-and-open-source-technology-in-azure). [Please search open issues here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues), and if your issue isn't already represented please [open a new one](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/new/choose). The project maintainers will respond to the best of their abilities.

Have you referred to this? - [https://github.com/Azure/secrets-store-csi-driver-provider-azure](https://github.com/Azure/secrets-store-csi-driver-provider-azure)

**Comment by tksh164** [comment]
@SreejaBhattacharya-MSFT Thank you for the information. I had not checked that yet. So, the note in the document represents the Azure Key Vault Provider for Secrets Store CSI Driver is not covered by the Microsoft Azure support policy, right?

**Comment by SreejaBhattacharya-MSFT** [comment]
Yes correct. It is open source.

**Comment by tksh164** [comment]
@SreejaBhattacharya-MSFT Thanks!

**Comment by tksh164** [comment]
[GA: Azure Key Vault secrets provider extension for Arc enabled Kubernetes clusters](https://techcommunity.microsoft.com/t5/azure-arc-blog/ga-azure-key-vault-secrets-provider-extension-for-arc-enabled/ba-p/3389231)
