### ISSUE TITLE
Az module vs AzureRM 

### ISSUE THREAD

**Issue by CarlosGon** [MicrosoftDocs/azure-stack-docs#2009]
On the step
Create an Azure AD App
3.[Install PowerShell for Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2206).

it should point to AzureRM module instead
3.[Install PowerShell for Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-install?view=azs-2206).

More robust and permanent fix:
Another option, is to update the helper scripts to an AZ module version. 
Installer and helper scripts
1. Download the [App Service on Azure Stack Hub deployment helper scripts](https://aka.ms/appsvconmashelpers).

Updating the scripts is the option more aligned with the Azure Stack Hub recommended Az versions.
Az modules are supported on Azure Stack Hub with Update 2002 that is already a version out of support.
Right now, all the versions inside the support policy (2206, 2108, 2102), recommend the usage of Az modules.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Prerequisites to deploy Azure App Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started?view=azs-2206)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **anwestg**

**Comment by SreejaBhattacharya-MSFT** [comment]
@CarlosGon thanks for the feedback, we will update the docs with necessary changes. Thanks

**Comment by SreejaBhattacharya-MSFT** [comment]
@CarlosGon , I have updated the doc for now and pointing it to the AzureRM module link. Regarding updating of the helper scripts, @sethmanheim could you please look into this and check if converting the helper scripts to az module version would be possible? Thanks

**Comment by sethmanheim** [comment]
I will pass this information on to the product team, thank you for pointing this out.
