### ISSUE TITLE
Missing step to start bitnami after apply changes to my.cnf

### ISSUE THREAD

**Issue by CarlosGon** [MicrosoftDocs/azure-stack-docs#2010]
Topic Configure external access to the MySQL hosting server
3. If the MySQL hosting server is version 8.0 or above, you need to change the authentication method to mysql_native_password. If the MySQL version is below 8.0, this step can be skipped.

After add the change on my.cnf file
[mysqld]
default_authentication_plugin=mysql_native_password

We need to delete ib_logfile0 file before start the bitnami service
Execute:
sudo service bitnami stop
 **sudo rm /bitnami/mysql/data/ib_logfile0**
sudo service bitnami start

Without this step, bitnami service will not start successfully.
some reference links:
https://manage.accuwebhosting.com/knowledgebase/2318/How-to-Fix-MySQL-Error-Plugin-andsharp039InnoDBandsharp039-registration-as-a-STORAGE-ENGINE-failed.html
https://stackoverflow.com/questions/55820850/mysql-fail-on-upgrade-from-v5-1-to-v8-how-to-recover-data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9da7c95f-1749-8818-f96f-c4ae02aa28a6
* Version Independent ID: db6e924d-d8c0-72bc-b0e3-382373ee7588
* Content: [Add MySQL hosting servers in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers?view=azs-2206)
* Content Source: [azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SreejaBhattacharya-MSFT** [comment]
Thanks for reaching out. We will look into this and update the thread. Thanks
