### ISSUE TITLE
Installing remote support agent failed

### ISSUE THREAD

**Issue by lckho3693** [MicrosoftDocs/azure-stack-docs#2011]
Install remote support agent failed with following message in log file:
2022/08/22 09:42:40 : INFO : RetryCount: 3
2022/08/22 09:42:40 : INFO : TimeIntervalInSeconds: 60
2022/08/22 09:42:55 : INFO : Importing Remote Support Dep module
2022/08/22 09:42:56 : INFO : Started Remote Support JEA installation.
2022/08/22 09:43:34 : ERROR : Exception during JEA installation. Count 3 Cannot find an object with identity: 'hciremotesa' under: 'DC=MYIAN,DC=LOCAL'.
2022/08/22 09:44:49 : INFO : Importing Remote Support Dep module
2022/08/22 09:44:49 : INFO : Started Remote Support JEA installation.
2022/08/22 09:44:54 : ERROR : Exception during JEA installation. Count 2 Cannot find an object with identity: 'hciremotesa' under: 'DC=MYIAN,DC=LOCAL'.
2022/08/22 09:46:09 : INFO : Importing Remote Support Dep module
2022/08/22 09:46:10 : INFO : Started Remote Support JEA installation.
2022/08/22 09:46:15 : ERROR : Exception during JEA installation. Count 1 Cannot find an object with identity: 'hciremotesa' under: 'DC=MYIAN,DC=LOCAL'.

how should I create hciremotesa object ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c883e2-f417-5fe6-0d87-7375d3df94b6
* Version Independent ID: 207837bf-b82b-2b51-fa54-b77744981594
* Content: [Azure Stack HCI, version 22H2 OS post installation (preview) - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/preview-post-installation)
* Content Source: [azure-stack/hci/manage/preview-post-installation.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/preview-post-installation.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ronmiab
* Microsoft Alias: **robess**

**Comment by VikasPullagura-MSFT** [comment]
@lckho3693 
Thanks for your Question! We are currently investigating and will get back on this.

**Comment by VikasPullagura-MSFT** [comment]
@ronmiab Can you please help on this.

**Comment by sethmanheim** [comment]
@VikasPullagura-MSFT This isn't a documentation issue, it needs to go to the product team or support team.

**Comment by ronmiab** [comment]
Hi @VikasPullagura-MSFT - as mentioned in my emails back to you. I have reached out via email and sent a follow-up email to the PMs supports that provided information for the post installation article that you have referred to in this customer feedback issue. Unfortunately, since this is not a documentation issue, the PMs or Support team will need to provide more insight into the error and how to resolve that.

**Comment by VikasPullagura-MSFT** [comment]
@ronmiab Thanks for the update.

**Comment by ronmiab** [comment]
@VikasPullagura-MSFT - You're welcome. 

Do you know which command in the post-installation steps they were trying to run when they encountered the error?

**Comment by lckho3693** [comment]
Hi, I'm actually getting that error when installing remote support agent into ASHCI 22H2
- Install-AzStackHCIRemoteSuppor
![JEA PS Script Error1](https://user-images.githubusercontent.com/111038119/186914933-0f2323b4-4330-4216-950d-a81e243dbab1.jpg)
t

**Comment by lckho3693** [comment]
If I go directly to JEA folder and run the SupportServiceJEA.ps1 I will get the following erro
![JEA PS Script Error2](https://user-images.githubusercontent.com/111038119/186915537-1ea68c50-f7e7-461b-b3b0-d334fc60c946.jpg)
r

**Comment by lckho3693** [comment]
I tried installing the agent via Windows Admin Center -  remote support extension also failed.

**Comment by ronmiab** [comment]
Are you following this document for getting remote support for Azure Stack HCI: https://docs.microsoft.com/en-us/azure-stack/hci/manage/get-remote-support#before-you-begin

This seems to have a step-by-step speaking to the Install JEA configuration and granting support access in Windows Admin Center, once the prior steps are complete.

This is a product issue and not a documentation issue, so this will require the PMs/Support team for further insight.

**Comment by lckho3693** [comment]
Yes, you are right, I following the step to prepare the node for Remote Support grant. 
however, get error when installing the agent.

**Comment by ronmiab** [comment]
Thank you for verifying. I don't yet have a PM/Support team from that side, but I am working to identify someone. As soon as I have a contact, they may respond via this thread or possibly message you separately.

**Comment by easyveazie** [comment]
Hi @lckho3693, the Remote Support preview requires domain admin permissions to provision the `hciremotesa` gMSA, and then then Install-AzStackHCIRemoteSupport script will configure that account to be used for the remote support agent. I understand this elevated access will not be feasible in most production environments and we are reviewing alternatives. Are you able to try the running Install-AzStackHCIRemoteSUpport with a domain admin?

https://docs.microsoft.com/en-us/azure-stack/hci/manage/get-remote-support#install-jea-configurations-before-azure-registration

**Comment by lckho3693** [comment]
Hi @easyveazie, I'm running the script using domain admin (Domain\administrator) and received that error.

**Comment by easyveazie** [comment]
@lckho3693 the gMSA appears to be failing to create. What is the functional level of the AD forest and domain?

`Get-ADForest | Select ForestMode`
`Get-ADDomain | Select DomainMode`

Are you able to manually create the gMSA?

```powershell
$gmsaAccountName = "hciremotesa"
$wmiSystem = Get-WmiObject win32_computersystem
$nodeName = $wmiSystem.Name
$fqdn = $wmiSystem.Domain

New-ADServiceAccount -Name $gmsaAccountName -DNSHostName "$gmsaAccountName.$fqdn" -KerberosEncryptionType AES256 -PrincipalsAllowedToRetrieveManagedPassword "$nodeName$" -ServicePrincipalNames "$gmsaAccountName/$fqdn" -SamAccountName $gmsaAccountName
```

**Comment by lckho3693** [comment]
@easyveazie, below is my forest and domain mode detail 

       ForestMode
       ----------
Windows2016Forest

       DomainMode
       ----------
Windows2016Domain

Will run the script and get back to you later

**Comment by lckho3693** [comment]
service account created.
![image](https://user-images.githubusercontent.com/111038119/188040141-fd8c0182-0d97-4292-abb9-b22c44cb5e9a.png)

will try the RemoteSupportAgent installation later

**Comment by lckho3693** [comment]
In progress 
![image](https://user-images.githubusercontent.com/111038119/188040393-79d2fa19-7d16-452b-8422-811e618ba494.png)

**Comment by lckho3693** [comment]
Great, it works. 
![image](https://user-images.githubusercontent.com/111038119/188040878-dc2730a1-36d5-4ba5-90a1-cd8a956a5047.png)

**Comment by lckho3693** [comment]
The agent installed, however, still having issue one enabling Remote support using Windows Admin Center
![image](https://user-images.githubusercontent.com/111038119/188043401-23b1db09-699b-4850-8760-5d3561c990e4.png)

**Comment by lckho3693** [comment]
Agent status screen updated correctly 
![image](https://user-images.githubusercontent.com/111038119/188043695-c021d4e9-fba6-40ee-b9a0-db1d28cb5894.png)

**Comment by lckho3693** [comment]
Get error as per below if I run the enabling remote support via PowerShell

Enable-AzStackHCIRemoteSupport -AccessLevel Diagnostics -ExpireInMinutes 61

![image](https://user-images.githubusercontent.com/111038119/188044020-d5b0db9b-def4-474b-80f6-a892fc101bc3.png)

**Comment by easyveazie** [comment]
Interesting, I don't know why Netwonsoft would be missing. I'll DM you my contact and we can take a closer look together.

**Comment by lckho3693** [comment]
Hi @easyveazie, I sent you some information about my lab environment via email last week, take a look and we can communicate over it

**Comment by lckho3693** [comment]
Thanks to @easyveazie and Eleanor for the information shared.
Will continue to test the feature one it's become GA.

**Comment by lckho3693** [comment]
Hi, below is the screen capture where the script error message shown during installation.
