### ISSUE TITLE
Missing Azure Kubernetes Mapping and Failed to resolve the extension version from the given values.

### ISSUE THREAD

**Issue by Remigijus-D** [MicrosoftDocs/azure-stack-docs#2014]
Hello,

This is a few errors I get when I try to follow this manual:

az k8s-extension create --cluster-type appliances --cluster-name $resource_name --resource-group $resource_group --name hci-vmoperator --extension-type Microsoft.AZStackHCI.Operator --scope cluster --release-namespace helm-operator2 --configuration-settings Microsoft.CustomLocation.ServiceAccount=hci-vmoperator --configuration-protected-settings-file $csv_path\ResourceBridge\hci-config.json --configuration-settings HCIClusterID=$hciClusterId --auto-upgrade true

(ExtensionOperationFailed) The extension operation failed with the following error:  Failed to resolve the extension version from the given values.
Code: ExtensionOperationFailed
Message: The extension operation failed with the following error:  Failed to resolve the extension version from the given values.

For the above I used workaround to provide --version '1.2.3' and it worked.

---

az azurestackhci virtualnetwork create --subscription $subscription --resource-group $resource_group --extended-location name="/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.ExtendedLocation/customLocations/$customloc_name" type="CustomLocation" --location $Location --network-type "Transparent" --name $vnetName

Command group 'azurestackhci' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus

MissingAzureKubernetesMapping: The custom location '/subscriptions/sub-id/resourceGroups/AzureStackHCI/providers/Microsoft.ExtendedLocation/customLocations/cl-name' does not support resource type 'Microsoft.AzureStackHCI/virtualnetworks' with api-version '2021-09-01-preview'. The currently enabled api-versions for the resource type 'Microsoft.AzureStackHCI/virtualnetworks' are [2020-11-01-preview,2021-07-01-preview]. Please select one of the enabled api-versions for this version of the 'Microsoft.AzureStackHCI' cluster extension.

Please help :/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2b89ce1-6af9-aaa1-48f2-da8d2f5c8b75
* Version Independent ID: db6c5f7c-77b2-7a97-dc2c-d904db88edf5
* Content: [Deploy Azure Arc Resource Bridge using command line - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address)
* Content Source: [azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by YashikaTyagi-MSFT** [comment]
@Remigijus-D 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by ManikaDhiman** [comment]
Hi @ZmanKyle, could you look into this issue and let me know if any doc update is needed? Thanks!

**Comment by sethmanheim** [comment]
@ManikaDhiman Did you ever get a response on this? Just trying to close out old issues as we transition to the new feedback system.

**Comment by ManikaDhiman** [comment]
> @ManikaDhiman Did you ever get a response on this? Just trying to close out old issues as we transition to the new feedback system.

Hi @sethmanheim : I suppose not. Given the substantial overhaul of the Arc VM docs, I'd expect this issue to have already been resolved.

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by alkohli** [comment]
Logical network creation is through a newer module now: stack-hci-vm (and not azurestackhci module). The older docs are also deprecated. 
Moreover there is no request to keep this issue open, hence closing it. #please-close
