### ISSUE TITLE
No "Azure" option in WAC Settings page

### ISSUE THREAD

**Issue by johnliu55-msft** [MicrosoftDocs/azure-stack-docs#2016]
In [Validate Azure integration](https://docs.microsoft.com/en-us/azure-stack/aks-hci/aks-hci-evaluation-guide-2a#validate-azure-integration), step 2 mentioned "Under Gateway, click Azure.":
![image](https://user-images.githubusercontent.com/107901166/188858781-41e12ca4-6291-4cd7-92ce-c9010bcbd9f6.png)

But in WAC version 2110.2, there's no "Azure" option to select in WAC Settings page:
![image](https://user-images.githubusercontent.com/107901166/188858993-8d33e2d8-d9a7-4b59-ae67-45bf0f2fb25f.png)

I think it became "Register".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a8d8957-6fc1-d963-efd3-f180c92afe8e
* Version Independent ID: 80da2a5b-e373-9c47-aa15-cbb3091e7c8a
* Content: [Deploy your AKS-HCI infrastructure with Windows Admin Center - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/aks-hci-evaluation-guide-2a)
* Content Source: [azure-stack/aks-hci/aks-hci-evaluation-guide-2a.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/aks-hci-evaluation-guide-2a.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by YashikaTyagi-MSFT** [comment]
@johnliu55-msft 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by sethmanheim** [comment]
@johnliu55-msft Sorry for the delayed response here, this was actually updated recently. #please-close
