### ISSUE TITLE
Any disk addition 

### ISSUE THREAD

**Issue by YeJianXin** [MicrosoftDocs/azure-stack-docs#2018]
Dear There，
I just got two questions for this page,
1. Do you have any disk addition procedures? can we disable the auto claim for disk addition
2. Is this disk replacement procedure just published in year 2022. just curious this because seems it is not there before.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5205c067-de4e-c9ff-ece6-db1ab176c3e8
* Version Independent ID: 956a1232-e27a-902b-f38e-7670ceb53fd7
* Content: [Replace failed drives on Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/replace-drives)
* Content Source: [azure-stack/hci/manage/replace-drives.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/replace-drives.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by AjayBathini-MSFT** [comment]
@YeJianXin 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by sethmanheim** [comment]
@YeJianXin As we are moving to a new feedback system, we have opened corresponding work items and are tracking all open issues in our internal database.  We are closing all public issues, but as mentioned above, there are other ways to provide feedback. Thank you again for reaching out! #please-close
