### ISSUE TITLE
VLANID Syntax is wrong

### ISSUE THREAD

**Issue by TroyMiller** [MicrosoftDocs/azure-stack-docs#2020]
`New-ArcHciConfigFiles -subscriptionID $subscription -location $location -resourceGroup $resource_group -resourceName $resource_name -workDirectory $csv_path\ResourceBridge -controlPlaneIP $controlPlaneIP  -k8snodeippoolstart $VMIP -k8snodeippoolend $VMIP -gateway $Gateway -dnsservers $DNSServers -ipaddressprefix $IPAddressPrefix [-vLanID=$vlanID] `

Please remove the brackets around VLANID.  If used in current syntax, the VLANID is passed into the hci-config.json and breaks deployments further in the process.  I'd suggest removing the variable entirely for anyone who has deployed AKS prior as it appears to pull the VLAN configuration from the MOC configuration by default.

This step will be the first spot it breaks:

`az k8s-extension create --cluster-type appliances --cluster-name $resource_name --resource-group $resource_group --name hci-vmoperator --extension-type Microsoft.AZStackHCI.Operator --scope cluster --release-namespace helm-operator2 --configuration-settings Microsoft.CustomLocation.ServiceAccount=hci-vmoperator --configuration-protected-settings-file $csv_path\ResourceBridge\hci-config.json --configuration-settings HCIClusterID=$hciClusterId --auto-upgrade true
`
It fails with a generic timeout error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2b89ce1-6af9-aaa1-48f2-da8d2f5c8b75
* Version Independent ID: db6c5f7c-77b2-7a97-dc2c-d904db88edf5
* Content: [Deploy Azure Arc Resource Bridge using command line - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address)
* Content Source: [azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by AjayBathini-MSFT** [comment]
@TroyMiller 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

@ManikaDhiman 
please review it

**Comment by ZmanKyle** [comment]
The following command has been updated about 2 weeks ago and we have changed it from [vLanID=$vlanID] to [vLanID $vlanID]. The command currently in the doc is shown below:
New-ArcHciConfigFiles -subscriptionID $subscription -location $location -resourceGroup $resource_group -resourceName $resource_name -workDirectory $csv_path\ResourceBridge -controlPlaneIP $controlPlaneIP  -k8snodeippoolstart $VMIP -k8snodeippoolend $VMIP -gateway $Gateway -dnsservers $DNSServers -ipaddressprefix $IPAddressPrefix [-vLanID $vlanID]

Could you confirm if you are still running into the same issue with this updated command?

**Comment by TroyMiller** [comment]
New-ArcHciConfigFiles -subscriptionID $subscription -location $location -resourceGroup $resource_group -resourceName $resource_name -workDirectory $csv_path\ResourceBridge -controlPlaneIP $controlPlaneIP -k8snodeippoolstart $VMIP -k8snodeippoolend $VMIP -gateway $Gateway -dnsservers $DNSServers -ipaddressprefix $IPAddressPrefix[-vLanID $vlanID]
At line:1 char:331                                                                                                                                                                                               + ... ay -dnsservers $DNSServers -ipaddressprefix $IPAddressPrefix[-vLanID  ...                                                                                                                                  +                                                                  ~                                                                                                                                             Array index expression is missing or not valid.                                                                                                                                                                      + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException                                                                                                                                + FullyQualifiedErrorId : MissingArrayIndexExpression     


Adding a space after $IPAddressPrefix breaks the JSON again with this info:
{
    "azstackhciOperator.image":  "[-vLanID",

**Comment by TroyMiller** [comment]
I just tested this again today and it looks like it might have been fixed with an update.  The JSON is coming out correct using -vlanid $vlanid now.

**Comment by ZmanKyle** [comment]
Yes we have fixed the issue.

**Comment by ManikaDhiman** [comment]
The issue has been fixed.
#please-close
