### ISSUE TITLE
URL broken in Step 4, Option 2

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/azure-stack-docs#2021]
The link to register AKS-HCI using a Service Principal is broken/incorrect:

![image](https://user-images.githubusercontent.com/503974/189764942-37e7fc91-cfdf-4dd2-b147-167255b04368.png)

The link should probably be:
https://docs.microsoft.com/en-us/azure-stack/aks-hci/reference/ps/set-akshciregistration#register-aks-on-azure-stack-hci-and-windows-server-using-a-service-principal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9753c970-5a86-1862-4bb9-6b5ecdec550d
* Version Independent ID: b6ed170c-8c63-2020-2474-15c787c1c1b5
* Content: [Use PowerShell to set up Kubernetes on Azure Stack HCI and Windows Server clusters - AKS-HCI](https://docs.microsoft.com/en-us/azure-stack/aks-hci/kubernetes-walkthrough-powershell)
* Content Source: [azure-stack/aks-hci/kubernetes-walkthrough-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/kubernetes-walkthrough-powershell.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by AjayBathini-MSFT** [comment]
@eponerine 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

@sethmanheim 
Please review it

**Comment by sethmanheim** [comment]
@eponerine Thank you for catching this, it will be fixed by 3 PM today PDT.
