### ISSUE TITLE
Pulling Image from URL not listed in Firewall exceptions

### ISSUE THREAD

**Issue by TroyMiller** [MicrosoftDocs/azure-stack-docs#2022]
Azure HCI Resource Bridge - Extension for hci-vmoperator pulls images from gcr.io.  This needs to be included in firewall rules and/or Microsoft might consider hosting their own image.

Found in command:
`az k8s-extension create --cluster-type appliances --cluster-name $resource_name --resource-group $resource_group --name hci-vmoperator --extension-type Microsoft.AZStackHCI.Operator --scope cluster --release-namespace helm-operator2 --configuration-settings Microsoft.CustomLocation.ServiceAccount=hci-vmoperator --configuration-protected-settings-file $csv_path\ResourceBridge\hci-config.json --configuration-settings HCIClusterID=$hciClusterId --auto-upgrade true`

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  67s                default-scheduler  Successfully assigned azstackhci-operator-system/azstackhci-operator-controller-manager-7c59c9857c-fl2sr to moc-lzv7k4far4v
  Normal   Pulled     66s                kubelet            Container image "hybridaks.azurecr.io/azstackhci-operator:2.0.6" already present on machine
  Normal   Created    66s                kubelet            Created container manager
  Normal   Started    65s                kubelet            Started container manager
  Warning  Failed     65s                kubelet            Failed to pull image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0": rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0": failed to resolve reference "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0": failed to do request: Head "https://gcr.io/v2/kubebuilder/kube-rbac-proxy/manifests/v0.5.0": read tcp 172.16.200.91:59642->173.194.193.82:443: read: connection reset by peer
  Warning  Failed     52s                kubelet            Failed to pull image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0": rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0": failed to resolve reference "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0": failed to do request: Head "https://gcr.io/v2/kubebuilder/kube-rbac-proxy/manifests/v0.5.0": read tcp 172.16.200.91:55786->173.194.193.82:443: read: connection reset by peer
  Normal   Pulling    27s (x3 over 65s)  kubelet            Pulling image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0"
  Warning  Failed     27s (x3 over 65s)  kubelet            Error: ErrImagePull
  Warning  Failed     27s                kubelet            Failed to pull image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0": rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0": failed to resolve reference "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0": failed to do request: Head "https://gcr.io/v2/kubebuilder/kube-rbac-proxy/manifests/v0.5.0": read tcp 172.16.200.91:55864->173.194.193.82:443: read: connection reset by peer
  Normal   BackOff    2s (x5 over 65s)   kubelet            Back-off pulling image "gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0"
  Warning  Failed     2s (x5 over 65s)   kubelet            Error: ImagePullBackOff
PS C:\temp>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b82e60f9-ebed-4011-41b7-3e11a60322ff
* Version Independent ID: 61535b85-bea3-f0b5-f562-fdd08293ed65
* Content: [VM provisioning through Azure portal on Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-enabled-virtual-machines)
* Content Source: [azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/azure-arc-enabled-virtual-machines.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ksurjan
* Microsoft Alias: **ksurjan**

**Comment by AjayBathini-MSFT** [comment]
@TroyMiller 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SreejaBhattacharya-MSFT** [comment]
Hi @ksurjan could you please take a look at this. Thanks

**Comment by ksurjan** [comment]
@ZmanKyle - is gcr.io now in the updated firewall requirements?

**Comment by ZmanKyle** [comment]
gcr.io has been added to the doc under firewall requirements section. The change will be reflected soon.

**Comment by ZmanKyle** [comment]
gcr.io was replaced by hybridaks.azurecr.io.

**Comment by sethmanheim** [comment]
Thanks @ZmanKyle, #please-close
