### ISSUE TITLE
Issue registering cluster via Windows Admin Center with Azure

### ISSUE THREAD

**Issue by LucaOtto** [MicrosoftDocs/azure-stack-docs#2025]
I'm getting an error while trying to register the cluster with Azure ( https://learn.microsoft.com/en-gb/azure-stack/hci/guided-quick-deploy-eval?tabs=global-admin&tutorial-step=6 ).

I ran the tutorial twice and I keep getting the same issue even though I wait more than 60 seconds as mentioned in the Warning box 

![image](https://user-images.githubusercontent.com/42404744/191789126-06cac012-595c-4fb4-8405-618a675887c5.png)

Can I talk to someone that in relation to this?

Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd049ac2-b820-f3d4-9e65-57863a0f26ad
* Version Independent ID: e57d71ab-061f-03e4-c360-7d4687872916
* Content: [Evaluate Azure Stack HCI](https://learn.microsoft.com/en-gb/azure-stack/hci/guided-quick-deploy-eval?tutorial-step=9&tabs=global-admin)
* Content Source: [azure-stack/hci/guided-quick-deploy-eval.yml](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/guided-quick-deploy-eval.yml)
* Service: **azure-stack**
* GitHub Login: @BryanLa

**Comment by RamanathanChinnappan-MSFT** [comment]
@LucaOtto

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@LucaOtto 

Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by ercohen19** [comment]
Hi @LucaOtto can you share a screenshot of the error you are receiving please?  Also, what permissions do you have to the Azure tenant and subscription where you are trying to register the cluster?
