### ISSUE TITLE
There is typo in kubectl command

### ISSUE THREAD

**Issue by wotd** [MicrosoftDocs/azure-stack-docs#2029]
There is typo in kubectl command in Error: 'Secrets "sh.helm.release.v1.azure-arc.v1" not found':

```
You can also run kubectl get ns -a to confirm that the namespace, azure-arc, does not exist on your cluster.
```
it should be:
```
You can also run kubectl get ns -A to confirm that the namespace, azure-arc, does not exist on your cluster.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbd83c8b-58db-8675-91ee-0bab820828cf
* Version Independent ID: 237eeeb1-fa14-dfb2-618b-73b5b9f9a21b
* Content: [Resolve errors when enabling and disabling Azure Arc on Azure Kubernetes Service on Azure Stack HCI and Windows Server workload clusters](https://learn.microsoft.com/en-us/azure-stack/aks-hci/known-issues-arc)
* Content Source: [azure-stack/aks-hci/known-issues-arc.yml](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/known-issues-arc.yml)
* Service: **azure-stack**
* GitHub Login: @mattbriggs

**Comment by VikasPullagura-MSFT** [comment]
@wotd Thanks for the feedback. The document is updated and changes will go live once it is approved by the document author.
