### ISSUE TITLE
Remove the clientID (appid) from samples

### ISSUE THREAD

**Issue by madansr7** [MicrosoftDocs/azure-stack-docs#2033]
The use of your client id of your public client application in sample code of your documentation leads devs to just copy paste the code and run it. It would look seem as if they are using your application instead of their own app.
**Action:** Please remove your applications client id (1950a258-227b-4e31-a9cf-717495945fc2) from your doc samples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2f49e9-8b48-9023-11ea-db3bc03da21b
* Version Independent ID: 9dab4ae8-692e-5d63-e6fc-7d173cf98084
* Content: [Make API requests to Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-rest-api-use?view=azs-2206)
* Content Source: [azure-stack/user/azure-stack-rest-api-use.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-rest-api-use.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SaibabaBalapur-MSFT** [comment]
@madansr7 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
Hi @madansr7 -- very sorry for the delayed response here. The article appears to be correct as written, as this is the ID for PowerShell clients (see the example here: https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-rest-api-use?view=azs-2206#example-1).
