### ISSUE TITLE
AKS Deployment in Azure Stack Hub - From Marketplace - K8s Latest Versions not available

### ISSUE THREAD

**Issue by zohebs341** [MicrosoftDocs/azure-stack-docs#2034]
Hi Team,

When I tried deploying AKS in Azure Stack Hub using the marketplace option. It doesn't have Kubernetes latest versions, not even 1.21/1.22/1.23 versions. As in the drop-down list, I can see only 1.13 & 1.14.

We cannot use k8s 1.22 or 1.23 k8s versions if I use Azure stack hub marketplace.

Appreciate your inputs/suggestions. As I am a new user of Azure Stack Hub.
<img width="661" alt="image" src="https://user-images.githubusercontent.com/62261716/193392281-9c935474-187c-4016-a226-e613d4d2746f.png">

**Comment by ManoharLakkoju-MSFT** [comment]
@zohebs341 
Thanks for your feedback! We will investigate and update as appropriate.

It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by SaibabaBalapur-MSFT** [comment]
@zohebs341 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
