### ISSUE TITLE
Failure to install hci-vmoperator extension

### ISSUE THREAD

**Issue by ewingcorey** [MicrosoftDocs/azure-stack-docs#2036]
When running the following command from the documentation [here](https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line):
az k8s-extension create --cluster-type appliances --cluster-name $resource_name --resource-group $resource_group --name hci-vmoperator --extension-type Microsoft.AZStackHCI.Operator --scope cluster --release-namespace helm-operator2 --configuration-settings Microsoft.CustomLocation.ServiceAccount=hci-vmoperator --configuration-protected-settings-file $csv_path\ResourceBridge\hci-config.json --configuration-settings HCIClusterID=$hciClusterId --auto-upgrade true

I get the following error:

> (ExtensionOperationFailed) The extension operation failed with the following error:  Error: {Helm from path [] for release [hci-vmoperator] failed with the following error: err [release hci-vmoperator failed, and has been uninstalled due to atomic being set: failed to create resource: secrets "controllerconfig" is forbidden: unable to create new content in namespace moc-operator-system because it is being terminated]} occurred while doing the operation : {Installing the extension} on the config.
> Code: ExtensionOperationFailed
> Message: The extension operation failed with the following error:  Error: {Helm from path [] for release [hci-vmoperator] failed with the following error: err [release hci-vmoperator failed, and has been uninstalled due to atomic being set: failed to create resource: secrets "controllerconfig" is forbidden: unable to create new content in namespace moc-operator-system because it is being terminated]} occurred while doing the operation : {Installing the extension} on the config.

All commands prior to this have completed successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2b89ce1-6af9-aaa1-48f2-da8d2f5c8b75
* Version Independent ID: db6c5f7c-77b2-7a97-dc2c-d904db88edf5
* Content: [Deploy Azure Arc Resource Bridge using command line - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address)
* Content Source: [azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by Naveenommi-MSFT** [comment]
@ewingcorey 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by rbaret** [comment]
Hello,
I'm also encountering the same error.
Removing/reinstalling the whole ARC Bridge stuff  did not change anything.
Like OP, any command prior to that has run successfully

**Comment by ZmanKyle** [comment]
This is a known issue that occurred recently and is currently being investigated. Will provide an update once root cause is found. This is not a documentation issue.

**Comment by VikasPullagura-MSFT** [comment]
@ZmanKyle Thanks for confirming on the issue. Requesting you to share the update here for the benefit of community.

**Comment by ZmanKyle** [comment]
The IcM is still active and this is still under investigation. I will give an update here once the issue is resolved.

**Comment by storey-dev** [comment]
I have encountered the same issue - it would be great to understand the root cause/status of this and if a workaround exists for right now?

**Comment by mergljoe** [comment]
After updating Windows Server OS and Powershell modules on the machine, it started to work, I was able to install arc and setup connection. So I guess MS fixed something.

**Comment by ManikaDhiman** [comment]
As noted by @ZmanKyle, this is not a doc issue.
#please-close
