### ISSUE TITLE
Unable to enable Azure Site Recovery via Windows Admin Center

### ISSUE THREAD

**Issue by lckho3693** [MicrosoftDocs/azure-stack-docs#2038]
Unable to enable Azure Site Recovery via Windows Admin Center

Having error when enabling Azure Backup and Azure Site Recovery using Windows Admin Center

Setting up host with Azure Site Recovery

1:41:43 PM
Source
Go to Virtual machines.
Type
Error

Message
Azure Site Recovery software set up and registration to the recovery services vault 'HybridT10RSV' failed for the following hosts: node1.lab.net, node2.lab.net. Manually install the Azure Site Recovery software on the hosts and register them to the vault 'HybridT10RSV'. Get more information about Azure Site Recovery troubleshooting here https://go.microsoft.com/fwlink/?linkid=857208. Error message: Agent registration failed on machine node1.lab.net. Log: .NET Framework 4.6.2 or higher is avaialble. Proceeding with Microsoft Azure Site Recovery Provider installation. Microsoft Azure Site Recovery Provider installation has succeeded. Checking if Credentials file exists. Processing credentials file Installing management cert Initializing registration process. Stopping DR service Getting resource details The ASR cannot be registered due to an internal error. Run Setup again to register the server. The ASR cannot be registered due to an internal error. Run Setup again to register the server. Installing management cert Installing management cert Installing management cert Installing management cert Installing management cert Installing management cert Installing management cert Agent registration failed on machine node2.lab.net. Log: .NET Framework 4.6.2 or higher is avaialble. Proceeding with Microsoft Azure Site Recovery Provider installation. Microsoft Azure Site Recovery Provider installation has succeeded. Checking if Credentials file exists. Processing credentials file Installing management cert Initializing registration process. Stopping DR service Getting resource details The ASR cannot be registered due to an internal error. Run Setup again to register the server. The ASR cannot be registered due to an internal error. Run Setup again to register the server. Installing management cert Installing management cert Installing management cert Installing management cert Installing management cert Installing management cert Installing management cert

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fb2fe7d-660f-67fd-6461-8e6d76a21eca
* Version Independent ID: 8111c7d5-122f-a915-e57f-19db550a7468
* Content: [Protect your Hyper-V Virtual Machines with Azure Site Recovery and Windows Admin Center](https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/azure-site-recovery)
* Content Source: [WindowsServerDocs/manage/windows-admin-center/azure/azure-site-recovery.md](https://github.com/MicrosoftDocs/windowsserverdocs/blob/main/WindowsServerDocs/manage/windows-admin-center/azure/azure-site-recovery.md)
* Product: **windows-server**
* Technology: **windows-admin-center**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **wscontent**

**Comment by ManoharLakkoju-MSFT** [comment]
@lckho3693 
Thanks for your feedback! We will investigate and update as appropriate.

It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by lckho3693** [comment]
Hi, just to update that this happened to enabling Azure Backup using Windows Admin Center as well

**Comment by lckho3693** [comment]
this is the guide that I'm following 
https://learn.microsoft.com/en-us/windows-server/manage/windows-admin-center/azure/azure-site-recovery

Step 1-7 (Select Setup ASR)

**Comment by ManoharLakkoju-MSFT** [comment]
@lckho3693 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly

@IngridAtMicrosoft 
Could you Please review this and update as appropriate.

**Comment by lckho3693** [comment]
The step seems to be correct, as I manage to get it running few weeks ago. 
It may due to some Azure Recovery Service Vault updates causing the features failed.

**Comment by lckho3693** [comment]
Hi, any update for the issue?

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by alkohli** [comment]
Couple of notes here:
A new Azure Site Recovery procedure was published that applies to v22H2 and later. This does not include Windows Admin Center. Please give this procedure a try. 
Azure Back up articles are also updated for Azure Stack HCI, v23H2. Please take a look at those as well.

Since we have not received a request to keep this open, we will go ahead and close this issue. #sign-off

**Comment by lckho3693** [comment]
Thank you for the update. 
I will try it out next week on the new updates.
