### ISSUE TITLE
Unable to enable Azure via Windows Admin Center

### ISSUE THREAD

**Issue by lckho3693** [MicrosoftDocs/azure-stack-docs#2039]
Unable to enable Azure Backup via Windows Admin Center

Error:

3:18:25 PM
Source
Go to Azure Backup.
Type
Error

Message
Microsoft Azure Backup encountered an internal error. Wait for a few minutes and then try the operation again. If the issue persists, please contact Microsoft support.

**Comment by ManoharLakkoju-MSFT** [comment]
@lckho3693 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@lckho3693 
Duplicate of #2038

We are going to close this thread as Duplicate.
