### ISSUE TITLE
Indicate App Svc supportability & version for ASH 2206

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/azure-stack-docs#2040]
Last version listed is for ASH 2108 with App Svc RP version 2021.Q3

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14cde69a-5ed9-566f-4046-8cdd1d78493c
* Version Independent ID: b0bfbf03-907d-bd97-9a05-0102d9780a3f
* Content: [Deploy App Service in Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-deploy?view=azs-2206&pivots=state-disconnected)
* Content Source: [azure-stack/operator/azure-stack-app-service-deploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-app-service-deploy.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@CHDAFNI-MSFT 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@CHDAFNI-MSFT Sorry for the delayed response here, as this was updated shortly after you filed this issue. Thanks for reaching out! #please-close
