### ISSUE TITLE
"Select-Object -First 1" >>"Select-Object -Last 1"

### ISSUE THREAD

**Issue by cptzz** [MicrosoftDocs/azure-stack-docs#2041]
[Enter feedback here]
In the section of "Rotate Azure Stack Hub root certificate", the script uses "Select-Object -First 1" which would display the Oldest certificate. Instead, using "Select-Object -Last 1" displays the Latest root certificate installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4feaa2a-4850-478d-8122-7eb751ba0777
* Version Independent ID: f5cd7372-0443-3f2e-c403-ed7ba1a56146
* Content: [Rotate secrets - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-2108)
* Content Source: [azure-stack/operator/azure-stack-rotate-secrets.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-rotate-secrets.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@cptzz 
Thanks for the feedback! We will check and update the document as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@cptzz 
Close
