### ISSUE TITLE
Remove incorrect whitespace characters

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/azure-stack-docs#2042]
This whitespace:

![image](https://user-images.githubusercontent.com/503974/195259855-bfb61841-0883-43ed-832c-8c8d11a45e81.png)

Is actually not whitespace if you copy/paste it directly into PowerShell / Notepad / etc:

![image](https://user-images.githubusercontent.com/503974/195259986-4fb5e12b-f077-4dcd-8065-fd7c4a4c2103.png)

It appears that is `U+202F` instead of `U+0020`:

![image](https://user-images.githubusercontent.com/503974/195260165-686289d6-d2d9-4b29-9ced-6c5918d46dd6.png)

Please go thru and spot-check this entire document for incorrect whitespace characters, as copy/pasting them does NOT work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2b89ce1-6af9-aaa1-48f2-da8d2f5c8b75
* Version Independent ID: db6c5f7c-77b2-7a97-dc2c-d904db88edf5
* Content: [Deploy Azure Arc Resource Bridge using command line - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address#feedback)
* Content Source: [azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by Naveenommi-MSFT** [comment]
@eponerine 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@eponerine 
I am not facing any issue in Notepad 

<img width="711" alt="image" src="https://user-images.githubusercontent.com/111563669/195332106-7870f9a4-5f9b-4dd5-9a51-15454422140b.png">

Facing similar issue in Notepad++

<img width="937" alt="image" src="https://user-images.githubusercontent.com/111563669/195332816-ff9af98d-cbb4-4996-a097-ec7c45cff510.png">

Please check with your Notepad Version/Powershell Version.

If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by eponerine** [comment]
I’m confused - why do you need me to check any versions if you are experiencing the same problem? I literally sent the exact Unicode character that is on the Docs page. It’s wrong. The app (notepad, npp, etc) doesn’t matter. I’m copying it FROM your page. 

If you copy that exact command into PowerShell, it fails because PowerShell doesn’t actually separate the parameters. Again, because it’s WRONG on the Docs page. 

Did anyone actually test what they copy/pasted here? Was it sourced from a Word doc by accident?

**Comment by eponerine** [comment]
Here is an additional screenshot showing PowerShell 5.1 interpreting that character not as whitespace (as expected):

![image](https://user-images.githubusercontent.com/503974/195366638-dad73137-b65e-4e65-8f8b-7c7f7c9b92ea.png)

I also pulled the entire `deploy-arc-resource-bridge-using-command-line.md` and found that character is only used incorrectly _twice_ ... lines 181 and 217.

I'll be sending this issue to the Resource Bridge PG for visibility.

**Comment by ManikaDhiman** [comment]
Hi @eponerine, I am the assigned author of this article. Thanks for pointing out the whitespace issue! I will look into this and fix it as soon as possible. Thanks again!

**Comment by ManikaDhiman** [comment]
Hi @eponerine, I was able to reproduce the issues you pointed out. I fixed them and merged the PR. Updates should be live after the PM publishing pass today. Thank you so much again for your feedback!

**Comment by SaibabaBalapur-MSFT** [comment]
@eponerine 
Closed
