### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by hfu949** [MicrosoftDocs/azure-stack-docs#2045]
This link doesn't work.

> "For more information about Azure Hybrid Benefit, see [Azure Hybrid Benefit for Azure Stack HCI](https://learn.microsoft.com/en-us/concepts/azure-hybrid-benefit.md)."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6f92859f-7987-76ae-6f0d-8b048298158d
* Version Independent ID: 519ebc92-176d-7d46-a0ac-476cc241f45d
* Content: [Azure Stack HCI billing and payment - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/billing)
* Content Source: [azure-stack/hci/concepts/billing.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/billing.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by sethmanheim** [comment]
@hfu949 Thank you for pointing this out -- the fix has been merged and should be live after 3:30 PM PDT.

**Comment by sethmanheim** [comment]
#please-close

**Comment by Naveenommi-MSFT** [comment]
Hi @sethmanheim 
Thanks for your response.
