### ISSUE TITLE
Update to include 22H2 build info

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/azure-stack-docs#2049]
AS HCI 22H2 went GA the other day at Ignite. Can this page please be updated to include build numbers and release info?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22ce0662-cc07-34bc-1d9c-de7fd075bdee
* Version Independent ID: fc01822a-5d78-b4e0-eb1a-ccd8d9c7bdf0
* Content: [Azure Stack HCI release information - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/release-information)
* Content Source: [azure-stack/hci/release-information.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/release-information.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Naveenommi-MSFT** [comment]
@eponerine 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@eponerine 

Thank you for your time and patience!
Unfortunately, we don't provide product release updates through our GitHub channels. For this, I'd recommend referring to our [Azure Updates](https://azure.microsoft.com/en-us/updates/) or [Microsoft 365 Roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Azure%20Active%20Directory) pages for this info.

**Comment by eponerine** [comment]
@AjayBathini-MSFT I'm sorry, but did you even bother checking the link I sent?

The Azure Stack HCI official docs literally link here for release notes. Ever build is included here.

**Comment by AjayBathini-MSFT** [comment]
@eponerine 
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by ManikaDhiman** [comment]
@eponerine: Thanks for your feedback. The release info article is updated to include Azure Stack HCI, version 22H2 details. Thanks!

#please-close
