### ISSUE TITLE
AKS Host Windows Server requirements

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/azure-stack-docs#2053]
It is not clear to me what the requirements are for AKS host running on Windows Server:
* Does the AKS host need to run on the hypervisor, or is it fine to run it inside a virtual machine
* Is Windows Server 2022 Datacenter required for the host? Or is Windows Server 2022 Standard sufficient
* Can the AKS host run on VMWare vSphere? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 425ddc25-2a4b-c529-9d8c-b9e6975cfd1c
* Version Independent ID: 818658d6-3f73-7a88-93af-81018f971676
* Content: [Azure Kubernetes Service on Azure Stack HCI and Windows Server requirements - AKS-HCI](https://learn.microsoft.com/en-us/azure-stack/aks-hci/system-requirements?tabs=allow-table)
* Content Source: [azure-stack/aks-hci/system-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/aks-hci/system-requirements.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by abhilashaagarwala** [comment]
Hello!

**Comment by sethmanheim** [comment]
Closing this issue as the question was answered. #please-close
