### ISSUE TITLE
The EVA failed to enable if customer get  $TenantSubscriptionId via  $TenantSubscriptionId = read-host but not $TenantSubscriptionId = "SubID"

### ISSUE THREAD

**Issue by jianfeng-jia** [MicrosoftDocs/azure-stack-docs#2056]
Some users write script to leverage this feature and find that if they get $TenantSubscriptionId  via $TenantSubscriptionId = Read-Host
Then Invoke-AzureRmResourceAction can run **successfully** but EVA was not enabled. Such behavior can be replicated in 2108 and 2206.
From debug log I can see if users read-host to get $TenantSubscriptionId
The POST body looks as following: 
Absolute Uri:
https://adminmanagement.xxx/subscriptions/xxx/providers/Microsoft.Compute.Admin/locations/xxx/features/Microsoft.Compute.EmergencyVMAccess/enableTenantSubscriptionFeature?api-version=2020-11-01

Headers:
User-Agent                    : AzurePowershell/v0.0.0,PSVersion/v5.1.17763.2931
ParameterSetName              : BySubscriptionLevel
CommandName                   : Invoke-AzResourceAction

Body:
{
  "tenantSubscriptionId": _**{
    "CliXml": "<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\">\r\n  \<S>XXXTenantSubIDXXX\</S>\r\n</Objs>"
  }**_
}

Specify parameter $tenantSubscriptionId type to [String] can avoid such issue. 

Which means
$tenantSubscriptionSettings = @{
    TenantSubscriptionId = $tenantSubscriptionId
}
need to be 
$tenantSubscriptionSettings = @{
    TenantSubscriptionId = **[String]**$tenantSubscriptionId
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 221ace5c-e2df-f784-d570-a39563c13a8d
* Version Independent ID: 38a14acb-21f5-5378-6ece-50e89e437025
* Content: [Emergency VM access in Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/emergency-vm-access?view=azs-2206&tabs=azurerm1)
* Content Source: [azure-stack/user/emergency-vm-access.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/emergency-vm-access.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by YashikaTyagi-MSFT** [comment]
@jianfeng-jia 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by sethmanheim** [comment]
Thank you for bringing this up, it looks like it was addressed and fixed in a separate PR.
