### ISSUE TITLE
Wrong Powershell commands

### ISSUE THREAD

**Issue by alexor-ms** [MicrosoftDocs/azure-stack-docs#2058]
In the Option 2: turn on Azure Benefits using PowerShell part there are a mismatch of the used PowerShell cmdlets. 
Some commands are start with Enable-AzStack.... or Get-AzStack... both are wrong in my opinion. It should be always start with Get-AzureStackHCI....

Pls check and change it. 

Thanks
Alexander

GBB Hybrid Specialist @ Microsoft 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c98d186-ef81-48f0-7e70-301b3ad92f09
* Version Independent ID: 8552ac82-b862-f27d-e8df-5e4a8612d9ea
* Content: [Azure Benefits on Azure Stack HCI - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/azure-benefits?source=recommendations)
* Content Source: [azure-stack/hci/manage/azure-benefits.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/azure-benefits.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by YashikaTyagi-MSFT** [comment]
@alexor-ms 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
@alexor-ms Sorry for the delayed response. These cmdlets are correct. Azure Stack HCI has two ways that we name cmdlets – Get-azurestackhci and Get-AzStackHCI. The former is for out of the box OS cmdlets; the latter is for cmdlets that are part of the Az.StackHCI module
