### ISSUE TITLE
Addition & Deletion of NodePool using aks-engine - 0.67.0 & AKS Version 1.20.11 (Azure Stack Hub 2102)

### ISSUE THREAD

**Issue by zohebs341** [MicrosoftDocs/azure-stack-docs#2061]
Hi Team,

I've deployed the AKS cluster using aks-engine on Azure Stack Hub and it's up and running. However, I need to perform some modifications in the cluster. Like I need to delete one node pool and add a new node pool.

my "apimodel.json" file looks like the below:

cat apimodel.json | grep -i profile

"orchestratorProfile": {
"masterProfile": {
  "storageProfile": "ManagedDisks",
  "availabilityProfile": "AvailabilitySet",
"agentPoolProfiles": [
    "availabilityProfile": "AvailabilitySet",
    "storageProfile": "ManagedDisks",
    "availabilityProfile": "AvailabilitySet",
    "storageProfile": "ManagedDisks",
In the portal, I don't see any VMs in the Virtual machine scale sets tab. How can I add a node pool & delete a node pool?

**Comment by zohebs341** [comment]
As I've used the availability set, I need commands/process to add a new node pool & delete the node pool.

**Comment by AjayBathini-MSFT** [comment]
@zohebs341 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!
