### ISSUE TITLE
Update doc to state expected outcome for 'Set-DataResidencyLocation -Europe:$false'

### ISSUE THREAD

**Issue by Trace1337** [MicrosoftDocs/azure-stack-docs#2062]
Currently the doc only states and shows a screenshot of the expected outcome if the flag 'Europe=$true' is set. I recommend updating the doc to state the outcome of 'Europe=$false' which would show the Geographical region field as 'Other' and provide a screenshot example for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0094b74f-e85b-6983-5f58-ce24f825b63c
* Version Independent ID: a90feafe-0401-3da0-bb95-4dbc8868ea0f
* Content: [Azure Stack Hub known issues - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-2206)
* Content Source: [azure-stack/operator/known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/known-issues.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@Trace1337 Do you have the screenshot?

**Comment by Trace1337** [comment]
> @Trace1337 Do you have the screenshot? The current doc does not have a screenshot in it, although you state that it does, so I'm a bit unclear what you're asking. Btw, we don't generally include screenshots in the known issues article.

My apologies, this request should have been for [this page], which does have a screenshot.(https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-security-foundations?view=azs-2206#eu-schrems-ii-initiative-for-azure-stack-hub).

I'll work to get a screenshot showing 'Other'. Additionally, maybe for this page we just make a note saying it will show "Europe" for $true and "Other" for $false.

**Comment by AjayBathini-MSFT** [comment]
@Trace1337 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Trace1337** [comment]
![Screenshot showing "Other"](https://user-images.githubusercontent.com/111000263/236935529-1edd1f89-f95f-4e3d-bf7f-174535270950.png)

**Comment by sethmanheim** [comment]
@Trace1337 Very sorry for the slow response. Is this still an issue? If so, we can add the screenshot.

**Comment by sethmanheim** [comment]
@Trace1337 I have added this to the article, sorry again for the slow response. #please-close
