### ISSUE TITLE
NetworkATC not automatically installed

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#2068]
"When running the 22H2 Azure Stack HCI OS, each node will come with Network ATC pre-installed, along with all it's required modules. So you do not need to run an installation command."

Based on what I am seeing after downloading the ISO and installing the OS from the ISO, this is not the case.  The neither the NetworkATC or NetworkHUD Windows Features appear to be automatically installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a35e98c6-afb5-8598-db6a-638eedf11bba
* Version Independent ID: b1b4c5c8-52e0-a0c2-9c39-49cfa3c3f321
* Content: [Deploy host networking with Network ATC - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/network-atc?tabs=22H2)
* Content Source: [azure-stack/hci/deploy/network-atc.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/network-atc.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @dcuomo
* Microsoft Alias: **dacuo**

**Comment by RamanathanChinnappan-MSFT** [comment]
@aricbernard 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
@aricbernard Thank you for reaching out. The documentation has already been corrected to address this issue. #please-close
