### ISSUE TITLE
Release note gives incorrect hotfix build as pre-req for 2206 update

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#2069]
This generic release-note page still says 1.2108.2.113 is required to go to 2206 update:

> Hotfix prerequisites: before applying the 2206 update, The 2206 release of Azure Stack Hub must be applied on the 2108 release with the following hotfixes: [Azure Stack Hub hotfix 1.2108.2.113](https://learn.microsoft.com/en-us/azure-stack/operator/hotfix-1-2108-2-113?view=azs-2206)

However, since the release of newer 1.2108.2.127 hotfix, customers must go to that first before 2206.

```
Version      ApplicableUpdate
-------      ----------------
1.2108.2.113 1.2108.2.127
1.2108.2.127 1.2206.2.52
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6e05517-6ffa-ad32-ec69-d3299492d880
* Version Independent ID: 2d6ffb4c-9134-a390-3f90-2322c9182e76
* Content: [Azure Stack Hub release notes - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/release-notes?view=azs-2206)
* Content Source: [azure-stack/operator/release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/release-notes.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
Thanks for catching that @alexsmithMSFT -- I'll fix it immediately.

**Comment by Naveenommi-MSFT** [comment]
@alexsmithMSFT 
It looks like your issue is resolved since you closed this thread.
If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
