### ISSUE TITLE
Informative, but misleading

### ISSUE THREAD

**Issue by cforbin1** [MicrosoftDocs/azure-stack-docs#207]
I followed the directions on this page because the page mod date is 5 months later than another similar page.  This page, however, concerns a package called "AzureRM" which is apparently older than the current "Az" package.

The page could use a better (but still brief) explanation as to who should be using this procedure, and who should NOT, and why.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d14a302-9b02-8eb4-1b49-b52580a67472
* Version Independent ID: 10c55050-5b52-a48d-bfb2-eba0a4494900
* Content: [Install PowerShell for Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-install#feedback)
* Content Source: [azure-stack/operator/azure-stack-powershell-install.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-powershell-install.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@cforbin1 Thanks for the feedback! In case you are unsure, I can confirm that the specified "AzureRM" package should be used.

I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@cforbin1 Thanks for your note and perspective. I can see how that it would be confusing and I have added a note about the AzureRM and Az modules. I've updated the topic. Thanks, Matt

**Comment by mattbriggs** [comment]
#please-close
