### ISSUE TITLE
Probe behavior missing 

### ISSUE THREAD

**Issue by dafutsi** [MicrosoftDocs/azure-stack-docs#2071]
There is a difference in between the probe behavior of AzS load balancers and public Azure load balancers: 
- for public azure , probe originates from 168.63.129.16
- for AzS , probe originates from the default gateway of the subnet. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd5972fd-29f4-2643-56d4-98f845a132e6
* Version Independent ID: 900d8d64-db85-6db9-3a38-22d84d0c55df
* Content: [Azure Stack Hub networking differences - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-network-differences?view=azs-2206&source=docs#cheat-sheet-networking-differences)
* Content Source: [azure-stack/user/azure-stack-network-differences.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-network-differences.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Naveenommi-MSFT** [comment]
@dafutsi 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@dafutsi 
Thanks ! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@sethmanheim 
Can you please add your comments on above query.

**Comment by dafutsi** [comment]
Thanks Ajay,
I see the public docs have already been updated.

Many thanks

David
