### ISSUE TITLE
Clearing up Azure registration & configuration section

### ISSUE THREAD

**Issue by kimlam-ms** [MicrosoftDocs/azure-stack-docs#2077]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Under "Run deployment tool", step 6, it is a bit misleading to put the screen grab of the WAC before the subsequent steps (a-d) is done. 
I would recommend moving the screen shot to the bottom of the steps to show what a finished page should look like. I was concerned that I didn't have those options available when I should have copied the code and clicked on the "enter the code" link. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae91113-8c41-fdef-a6e4-95899bbaa36f
* Version Independent ID: 1135a6e1-7933-a7ef-5674-7f80aca310b5
* Content: [Deploy Azure Stack HCI interactively via a new configuration file (preview) - Azure Stack HCI](https://review.learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-tool-new-file?branch=release-asz-aug)
* Content Source: [azure-stack/hci/deploy/deployment-tool-new-file.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-tool-new-file.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @dansisson
* Microsoft Alias: **v-dansisson**

**Comment by VikasPullagura-MSFT** [comment]
@kimlam-ms 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@dansisson 
Can you please check and add your comments on this doc update request as applicable.

**Comment by dansisson** [comment]
This article has since been reorganized and issue resolved.
