### ISSUE TITLE
Azure Account Center links to retired page at https://account.windowsazure.com/subscriptions

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#2078]
The "View usage - other subscriptions" section, has a link for the Azure Account Center link to https://account.windowsazure.com/subscriptions

But the linked page refers customers to the Azure portal-

> **Account management has moved to Azure portal**
> This portal has been retired. We have migrated all the functionality including managing payment methods, downloading invoices, usage & costs and viewing your subscriptions to the Azure portal.
> Azure portal offers a richer unified experience for [cost management & billing](https://portal.azure.com/#blade/Microsoft_Azure_Billing/BillingMenuBlade/Overview) and resource management.

I suggest that we update this doc with a similar link directly to Azure Cost Management blade.

Also the [View usage - Enterprise Agreement subscriptions](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-usage-reporting?view=azs-2206#view-usage---enterprise-agreement-subscriptions) section has a link to an EA portal at https://ea.azure.com, but I'm not able to confirm if that site is still valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0137a710-b369-d41a-4bf1-8b2c92abd04e
* Version Independent ID: 18d89d67-fcee-bd46-98eb-6db35fcf35d1
* Content: [Report Azure Stack Hub usage data to Azure - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-usage-reporting?view=azs-2206)
* Content Source: [azure-stack/operator/azure-stack-usage-reporting.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-usage-reporting.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@alexsmithMSFT Thank you for catching that -- I updated to the link to point to the Azure Cost Management blade. Will be live after 3 PM PT today.

**Comment by Naveenommi-MSFT** [comment]
@alexsmithMSFT 

It looks like your issue is resolved since you closed this thread.
If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
