### ISSUE TITLE
Specifying the interface to run the command Set-DataResidencyLocation -Europe:$true or $false

### ISSUE THREAD

**Issue by NikhilBhoga** [MicrosoftDocs/azure-stack-docs#2079]
Regarding the KI "Geographical region not provided" 
I really appreciate for writing down the known issues and the mitigation steps. This was quick to identify what the alert is for and what should be done further. Thanks for your efforts.

Just one feedback, I thought may be specifying where to run this command *Set-DataResidencyLocation -Europe:$true or $false* will really help customers to follow the procedure easily. Whether it should be run connecting to Admin ARM or by connecting to PEP and if it is PEP, it is required to unlock the session.

I tried running this command connecting to locked PEP session and it worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0094b74f-e85b-6983-5f58-ce24f825b63c
* Version Independent ID: a90feafe-0401-3da0-bb95-4dbc8868ea0f
* Content: [Azure Stack Hub known issues - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-2206#geographical-region-not-provided)
* Content Source: [azure-stack/operator/known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/known-issues.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@NikhilBhoga Thank you for the feedback! We will update this information ASAP. #please-close

**Comment by NikhilBhoga** [comment]
Hi @sethmanheim, thank you for acknowledging. May I know how many days you usually take to update a document.
