### ISSUE TITLE
AKS Deployment in Azure Stack Hub - Service principal identity (SPN) (Secret expiry - two years)

### ISSUE THREAD

**Issue by zohebs341** [MicrosoftDocs/azure-stack-docs#2080]
Hi Team,

I am planning to deploy the k8s cluster using the AKS engine in Azure Stack Hub. In order to deploy the cluster, we need Service Principal details.

Question is, can we create SPN first from the portal and we can create a secret with two years expiry???

If I use the below command, it will create a secret with one-year expiry. Instead of this, I want to create SPN from the portal and create a two-year expiry secret. Will it work?

az ad sp create-for-rbac --name azurestack-aks-sp --query password -o tsv

**Comment by ManoharLakkoju-MSFT** [comment]
@zohebs341 
Thanks for your feedback! We will investigate and update as appropriate.

It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by ManoharLakkoju-MSFT** [comment]
@zohebs341 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
