### ISSUE TITLE
Required Azure AD Rights are not mentioned anywhere in the document

### ISSUE THREAD

**Issue by AndreasMWalter** [MicrosoftDocs/azure-stack-docs#2081]
Azure AD Rights are not mentioned anywhere in the document.
When registering using the Windows Admin Center and not using Powershell Azure AD rights are needed to set up the Service Principal.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a936999c-1c8d-e967-6571-4c73796b0721
* Version Independent ID: 6823f75b-1687-2829-d6db-a0bfbe52623d
* Content: [Connect Azure Stack HCI to Azure - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/register-with-azure)
* Content Source: [azure-stack/hci/deploy/register-with-azure.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/register-with-azure.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by ManoharLakkoju-MSFT** [comment]
@AndreasMWalter 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @AndreasMWalter please follow up below steps provided in link for register windows admin center.

https://learn.microsoft.com/en-us/azure-stack/hci/manage/register-windows-admin-center

**Comment by AndreasMWalter** [comment]
> 

We are not trying to register the Windows Admin Center, we are trying to register the Azure Stack HCI **using** the Windows Admin Center. However the required AAD permissions are not given in the document. Most importantly it is interesting to know what the "least privilege" rights are. For example the Role Application Developer may be enough?

**Comment by SaibabaBalapur-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

@AndreasMWalter 
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by sethmanheim** [comment]
@AndreasMWalter Very sorry for the slow response. This article has been updated extensively, so please take another look to see if it addresses your issues. If you still need assistance, please open a new feedback request. Thank you for reaching out! #please-close
