### ISSUE TITLE
k8s-extention create exits with http error 400

### ISSUE THREAD

**Issue by lnnrtkln** [MicrosoftDocs/azure-stack-docs#2083]
When deploying the Azure Arc VM management I can't set the requiered extentions using Azure CLI. 
The following command exits with a https error 400 "Bad Request" :
$hciClusterId= (Get-AzureStackHci).AzureResourceUri
az k8s-extension create --cluster-type appliances --cluster-name $resource_name --resource-group $resource_group --name hci-vmoperator --extension-type Microsoft.AZStackHCI.Operator --scope cluster --release-namespace helm-operator2 --configuration-settings Microsoft.CustomLocation.ServiceAccount=hci-vmoperator --configuration-protected-settings-file $csv_path\ResourceBridge\hci-config.json --configuration-settings HCIClusterID=$hciClusterId --auto-upgrade true --Debug

Here the Debug output:

`cli.azure.cli.core.auth.credential_adaptor: CredentialAdaptor.get_token: scopes=('https://management.core.windows.net//.default',), kwargs={}
cli.azure.cli.core.auth.msal_authentication: UserCredential.get_token: scopes=('https://management.core.windows.net//.default',), claims=None, kwargs={}
msal.application: Cache hit an AT
msal.telemetry: Generate or reuse correlation_id: 567bf7a0-72eb-425f-b001-dc967a8763a5
cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/d83386be-00ae-433e-81e5-6f15947791cb/resourceGroups/azcl-rg/providers/Microsoft.ResourceConnector/appliances/azcl-arcbridge/providers/Microsoft.KubernetesConfiguration/extensions/hci-vmoperator?api-version=2022-03-01'
cli.azure.cli.core.sdk.policies: Request method: 'PUT'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies:     'Content-Type': 'application/json'
cli.azure.cli.core.sdk.policies:     'Content-Length': '3985'
cli.azure.cli.core.sdk.policies:     'Accept': 'application/json'
cli.azure.cli.core.sdk.policies:     'x-ms-client-request-id': '69dc7176-668a-11ed-ab21-000af73e678f'
cli.azure.cli.core.sdk.policies:     'CommandName': 'k8s-extension create'
cli.azure.cli.core.sdk.policies:     'ParameterSetName': '--cluster-type --cluster-name --resource-group --name --extension-type --scope --release-namespace --configuration-settings --configuration-protected-settings-file --configuration-settings --auto-upgrade --debug'
cli.azure.cli.core.sdk.policies:     'User-Agent': 'AZURECLI/2.42.0 (MSI) azsdk-python-azure-mgmt-kubernetesconfiguration/2.0.0 Python/3.10.8 (Windows-10-10.0.20349-SP0)'
cli.azure.cli.core.sdk.policies:     'Authorization': '*****'
cli.azure.cli.core.sdk.policies: {"identity": {"type": "SystemAssigned"}, "properties": {"extensionType": "microsoft.azstackhci.operator", "autoUpgradeMinorVersion": true, "scope": {"cluster": {"releaseNamespace": "helm-operator2"}}, "configurationSettings": {"Microsoft.CustomLocation.ServiceAccount": "hci-vmoperator", "HCIClusterID": "/Subscriptions/d83386be-00ae-433e-81e5-6f15947791cb/resourceGroups/azcl-rg/providers/Microsoft.AzureStackHCI/clusters/azcl"}, "configurationProtectedSettings": {"secret.cloudFQDN": "xxx", "secret.loginString": "xxx="}}}
cli.azure.cli.core.sdk.policies: Request body:
urllib3.connectionpool: Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool: https://management.azure.com:443 "PUT /subscriptions/d83386be-00ae-433e-81e5-6f15947791cb/resourceGroups/azcl-rg/providers/Microsoft.ResourceConnector/appliances/azcl-arcbridge/providers/Microsoft.KubernetesConfiguration/extensions/hci-vmoperator?api-version=2022-03-01 HTTP/1.1" 400 226
cli.azure.cli.core.sdk.policies: Response status: 400
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies:     'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies:     'Content-Length': '226'
cli.azure.cli.core.sdk.policies:     'Content-Type': 'text/html'
cli.azure.cli.core.sdk.policies:     'Expires': '-1'
cli.azure.cli.core.sdk.policies:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.sdk.policies:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies:     'x-ms-request-id': '03f5eb04-eb40-4e11-810f-65dfd2fdd76a'
cli.azure.cli.core.sdk.policies:     'x-ms-correlation-request-id': '03f5eb04-eb40-4e11-810f-65dfd2fdd76a'
cli.azure.cli.core.sdk.policies:     'x-ms-routing-request-id': 'GERMANYWESTCENTRAL:20221117T151343Z:03f5eb04-eb40-4e11-810f-65dfd2fdd76a'
cli.azure.cli.core.sdk.policies:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies:     'Date': 'Thu, 17 Nov 2022 15:13:42 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: <html>
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>Request Header Or Cookie Too Large</center>
<hr><center>nginx</center>
</body>
</html>

cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "C:\Users\Administrator.HCILAB\.azure\cliextensions\k8s-extension\azext_k8s_extension\custom.py", line 209, in create_k8s_extension
    return sdk_no_wait(
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 722, in sdk_no_wait
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 73, in wrapper_use_tracer
  File "C:\Users\Administrator.HCILAB\.azure\cliextensions\k8s-extension\azext_k8s_extension\vendored_sdks\v2022_03_01\operations\_extensions_operations.py", line 382, in begin_create
    raw_result = self._create_initial(
  File "C:\Users\Administrator.HCILAB\.azure\cliextensions\k8s-extension\azext_k8s_extension\vendored_sdks\v2022_03_01\operations\_extensions_operations.py", line 317, in _create_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
Content: <html>
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>Request Header Or Cookie Too Large</center>
<hr><center>nginx</center>
</body>
</html>`

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2b89ce1-6af9-aaa1-48f2-da8d2f5c8b75
* Version Independent ID: db6c5f7c-77b2-7a97-dc2c-d904db88edf5
* Content: [Set up Azure Arc VM management using command line - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address)
* Content Source: [azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by ManoharLakkoju-MSFT** [comment]
@lnnrtkln 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@lnnrtkln 
I'm going to assign this to the document author so they can take a look at it accordingly.

@ManikaDhiman 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@SaibabaBalapur-MSFT This appears to be a request for technical support rather than an issue with the documentation. Please redirect as appropriate. Thanks!

**Comment by SaibabaBalapur-MSFT** [comment]
@lnnrtkln 
Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.
