### ISSUE TITLE
Configure custom quorum

### ISSUE THREAD

**Issue by kimlam-ms** [MicrosoftDocs/azure-stack-docs#2085]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Under the [validate custom quorum settings](https://review.learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-tool-validate?branch=release-asz-aug#validate-cluster-quorum-settings), the link is broken to "configure the cluster quorum".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4fd1a7d-54c9-45c2-b615-3ce9c2970eff
* Version Independent ID: 81205ef5-b0f7-17d7-0dc4-5f8a8ca7120c
* Content: [Validate deployment for Azure Stack HCI (preview) - Azure Stack HCI](https://review.learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-tool-validate?branch=release-asz-aug)
* Content Source: [azure-stack/hci/deploy/deployment-tool-validate.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-tool-validate.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @dansisson
* Microsoft Alias: **v-dansisson**

**Comment by ManoharLakkoju-MSFT** [comment]
@kimlam-ms 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@kimlam-ms 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by SaibabaBalapur-MSFT** [comment]
@dansisson 
Can you please check and updated broken link shared below screenshot and request as applicable.

<img width="758" alt="image" src="https://user-images.githubusercontent.com/111563669/202979198-12937867-16a8-4316-b7e2-0d9efbc6c9ef.png">

**Comment by sethmanheim** [comment]
Deleted screenshot as it contained an internal URL.
