### ISSUE TITLE
Az Module Code Snippet needed for Manage Keys and Secrets section

### ISSUE THREAD

**Issue by jamesorlando** [MicrosoftDocs/azure-stack-docs#2091]
This page has tabs for code snippets between the Az Modules and the AzureRM modules. However, the section "Manage Keys and Secrets" only has the AzureRM code snippets. Having trouble getting the Get-AzKeyVaultSecret cmdlet to work with ASH and it would be helpful here if there were examples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e5e5371-725a-54da-7991-064915718ebb
* Version Independent ID: fe13c7cd-7d10-a7fb-9fd4-b81989f4febc
* Content: [Manage Key Vault in Azure Stack Hub using PowerShell - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-key-vault-manage-powershell?view=azs-2206&tabs=az1%2Caz2%2Caz3%2Caz4%2Caz5%2Caz6%2Caz7)
* Content Source: [azure-stack/user/azure-stack-key-vault-manage-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-key-vault-manage-powershell.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@jamesorlando 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@jamesorlando I don't have access to any other examples, but if you have some, please send them to me and we'll include them.

**Comment by jamesorlando** [comment]
I do not. I could not get anything to work, so I was looking for some examples myself. To keep me moving forward I opted to just go with invoke-restmethod to get what I needed

**Comment by sethmanheim** [comment]
OK, thanks. I'll see what I can find. Let's leave this open for now and I will investigate.

**Comment by jamesorlando** [comment]
My caffeine levels were too low when I responded. I am confusing two things I am working on. I did not use invoke-restmethod to access a key vault. I am trying to access the keyvault using the AzModules, but am not having any luck. Still no examples... if I come up with something I will post it here.
