### ISSUE TITLE
Where is the Azure Stack Edge differences?

### ISSUE THREAD

**Issue by mkleef** [MicrosoftDocs/azure-stack-docs#2093]
Would be great to amend this article with Azure Stack Edge differences also. Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afda862d-5084-45c0-43d6-fa1cf6723e2a
* Version Independent ID: 12cb954d-fd9d-0877-6437-31bdd292abb2
* Content: [Differences between global Azure, Azure Stack Hub, Azure Stack HCI - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/compare-azure-azure-stack?view=azs-2206)
* Content Source: [azure-stack/operator/compare-azure-azure-stack.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/compare-azure-azure-stack.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@mkleef 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@mkleef Thank you for reaching out and for the suggestion, we will put this on our backlog list of updates. If you still need assistance, please open a new feedback request. #please-close
