### ISSUE TITLE
Static IP addresses

### ISSUE THREAD

**Issue by lucidqdreams** [MicrosoftDocs/azure-stack-docs#2099]
the recommended is static IP configuration.  yet your image shows DHCP.  the Cli install has more parameters than make sense, is VMIP_1 and VMIP_2 meant to be the same, is this an IP address that is meant to be inside the AKS mgmt node pool or VIP pool or outside of that pool?

$VMIP_1=
$VMIP_2=
$cloudServiceIP=
$controlPlaneIP=

guidance with how to use static IP configuration would be helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67515443-2fd6-f5a0-fa18-49c24deffde0
* Version Independent ID: f92341fc-4006-322c-80df-9698b45757df
* Content: [Set up Azure Arc VM management using Windows Admin Center (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-wac)
* Content Source: [azure-stack/hci/manage/deploy-arc-resource-bridge-using-wac.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/deploy-arc-resource-bridge-using-wac.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by ManikaDhiman** [comment]
@ZmanKyle: Could you look into this issue please? Thanks!

**Comment by ZmanKyle** [comment]
Since this is an old comment, I wanted to make sure we all know that we added this doc last year around the same time also explaining these IPs https://learn.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-vm-management-networking. Let me know if anything in that doc doesn't make sense and we will make changes accordingly. Thanks.

**Comment by ZmanKyle** [comment]
if we have not more questions on this one can we close it? @ManikaDhiman

**Comment by sethmanheim** [comment]
Will do, thank you @ZmanKyle. #please-close
