### ISSUE TITLE
Static routing and P2P references

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#21]
In the static routing section, all of the P2P references used are singular in nature. e.g.:
In the text: "static routes pointing to the TOR devices P2P"
In the image: "Customer border assign static route to TOR P2P"

In a static routing scenario, the TOR device (or devices) should always have multiple uplinks (as shown in the image) and therefore should always have multiple P2P connections.  If a customer took the singular reference literally and only configured a route to one of the P2P connections, in the cases where the Azure Stack TORs chose one of the other available paths, network communication would fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa29c6e-0845-f9e9-1f79-af2dea1081c4
* Version Independent ID: b0e0e929-6ccc-f0bb-7814-8962efed9e98
* Content: [Border connectivity network integration considerations for Azure Stack integrated systems](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-border-connectivity#feedback)
* Content Source: [articles/azure-stack/azure-stack-border-connectivity.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-border-connectivity.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by mattbriggs** [comment]
@aricbernard, @wamota updated the content. Thanks for your feedback. #please-close

**Comment by mattbriggs** [comment]
#please-close
