### ISSUE TITLE
No Azure DevOps in Disconnected ASH ?

### ISSUE THREAD

**Issue by rboro-home** [MicrosoftDocs/azure-stack-docs#2100]
Not quite sure if there is no Azure DevOps in Disconnected ASH.

'No Azure DevOps. Since this service is not available for a disconnected Azure Stack Hub, there is no integrated support for it.'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1162d2cd-89ae-c709-9b50-2e38eb464c58
* Version Independent ID: d7f7a574-2c5c-1333-57a1-767ffaafb365
* Content: [Azure Kubernetes Service on Azure Stack Hub overview for users - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/aks-overview?view=azs-2206)
* Content Source: [azure-stack/user/aks-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/aks-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by RamanathanChinnappan-MSFT** [comment]
@rboro-home 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju** [comment]
@rboro-home 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by ManoharLakkoju** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@rboro-home Very sorry for the slow response. As we have noted on the page, this service is being discontinued, so I am closing this issue. If you still need assistance, please open a new feedback request. #please-close
