### ISSUE TITLE
the convert image command fails to build a vhdx.  WINPE issue even after install ADK and winpe

### ISSUE THREAD

**Issue by lucidqdreams** [MicrosoftDocs/azure-stack-docs#2107]
the convert image command fails to build a vhdx.  I received errors that seem to have been raised already as an issue from mar 3 2020 https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1340

my experience and this commend on the issue suggest a more detail guide could be created or even better the module error handling and documentation improved.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01571ef6-1345-ed10-4033-6d031b769dac
* Version Independent ID: 7943811e-8822-7e0d-ba9a-172daf986312
* Content: [Deploy an SDN infrastructure using SDN Express - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/sdn-express)
* Content Source: [azure-stack/hci/manage/sdn-express.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/sdn-express.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SaibabaBalapur-MSFT** [comment]
@lucidqdreams 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@lucidqdreams 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by AjayBathini-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@lucidqdreams Very sorry for the slow response here -- if this is still an issue can you please submit a new feedback request. @please-close
