### ISSUE TITLE
Error in command line to remove k8s-extension

### ISSUE THREAD

**Issue by squasta** [MicrosoftDocs/azure-stack-docs#2111]
In documentation command given to delete k8s extension on Azure Arc Resource Bridge is :  
```shell
az k8s-extension delete --cluster-type appliances --cluster-name $resource_name --resource-group $resource_group --name hci-vmoperator --yes
``` 

_--name hci-vmoperator_ is incorrect.

Correct name operator is :  --name __vmss-hci__

![image](https://user-images.githubusercontent.com/13031988/211491793-0da498b3-057e-4749-ac77-4f2bb6efb09a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e049430-9bb9-ab66-b8bc-5fa0cc7b37e5
* Version Independent ID: 387e8235-0668-18b5-fc98-e3af2e464636
* Content: [Uninstall Azure Arc VM management (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/uninstall-arc-resource-bridge)
* Content Source: [azure-stack/hci/manage/uninstall-arc-resource-bridge.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/uninstall-arc-resource-bridge.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ksurjan
* Microsoft Alias: **ksurjan**

**Comment by VikasPullagura-MSFT** [comment]
@squasta 
Thanks for the feedback! We will check and update the document as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@squasta 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.

https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/11716

**Comment by SaibabaBalapur-MSFT** [comment]
@ksurjan 
Please can you review PR https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/11716

**Comment by SaibabaBalapur-MSFT** [comment]
@squasta 
We have made modifications in the private repository; once the author has authorized it, the document will become alive shortly. This thread is being closed right now. We monitor these change thread. https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/11716

https://review.learn.microsoft.com/en-us/azure-stack/hci/manage/uninstall-arc-resource-bridge?branch=pr-en-us-11716

**Comment by ZmanKyle** [comment]
Hi folks, 
--name is the name of the HCI VM operator extension that is provided when creating the extension.
This should match --name in this command during creation:
az k8s-extension create --cluster-type appliances --cluster-name $resource_name --resource-group $resource_group --name **hci-vmoperator** --extension-type Microsoft.AZStackHCI.Operator --scope cluster --release-namespace helm-operator2 --configuration-settings Microsoft.CustomLocation.ServiceAccount=hci-vmoperator --configuration-protected-settings-file $csv_path\ResourceBridge\hci-config.json --configuration-settings HCIClusterID=$hciClusterId --auto-upgrade true

If you set --name SSVM-operator in the above command, the --name in the delete command should be SSVM-operator as well. 

We use many pre-specified names throughout the documentation and user inputs may not be necessary. I suggest that we do not make this change.

**Comment by SaibabaBalapur-MSFT** [comment]
@squasta 
Thank you, the clarification, I'm going to assign this to the document author so they can take a look at it accordingly.

@ksurjan 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@SaibabaBalapur-MSFT @ksurjan already made his comment and closed the issue. #please-close
