### ISSUE TITLE
Typo in the table of parameters

### ISSUE THREAD

**Issue by squasta** [MicrosoftDocs/azure-stack-docs#2112]
_vanID_ is incorrect, it is __VlanID__

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2b89ce1-6af9-aaa1-48f2-da8d2f5c8b75
* Version Independent ID: db6c5f7c-77b2-7a97-dc2c-d904db88edf5
* Content: [Set up Azure Arc VM management using command line (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address-1%2Cfor-static-ip-address-2)
* Content Source: [azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by VikasPullagura-MSFT** [comment]
@squasta 
Thanks for the feedback! We will check and update the document as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@squasta 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
