### ISSUE TITLE
How do we provide credentials to Invoke-CloudDeployment.ps1 -Rerun ?

### ISSUE THREAD

**Issue by evan-morris** [MicrosoftDocs/azure-stack-docs#2119]
.\Invoke-CloudDeployment.ps1 -Rerun 

How do we provide credentials? Script fails on error otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b46a5f4c-309d-ce63-2b75-521e45f07b1a
* Version Independent ID: 266b7c05-ea64-5e95-4574-7cb023ef59c9
* Content: [Troubleshoot Azure Stack HCI deployment (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-tool-troubleshoot)
* Content Source: [azure-stack/hci/deploy/deployment-tool-troubleshoot.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-tool-troubleshoot.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @dansisson
* Microsoft Alias: **v-dansisson**

**Comment by YashikaTyagii** [comment]
@evan-morris 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by dansisson** [comment]
please reassign this to [alkohli](https://github.com/alkohli), who has a handle on the script's author in dev.

**Comment by alkohli** [comment]
Hello @evan-morris, This cmdlet should not require any credentials as you already provide these credentials when the deployment was started. Please let us know if any further clarification is needed.

#please-close

**Comment by ubergeek24** [comment]
What is not clear is that you have to use the "deployment account" that was created by the New-HciAdObjectsPreCreation script.
