### ISSUE TITLE
The way to get expiry of a REST Certificate is confusing.

### ISSUE THREAD

**Issue by luyaof** [MicrosoftDocs/azure-stack-docs#2136]
>To get the expiry of a REST certificate, replace "Certificate-subject-name" with the IP address of the Network Controller REST endpoint. You can get this value from the Get-NetworkController cmdlet.

The REST Cert Subject can be RestName or RestIPAddress. 

Suggest to:
>To get the expiry of a REST certificate, replace "Certificate-subject-name" with the RestIPAddress or RestName of NetworkController. You can get this value from the Get-NetworkController cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0a8e77-a838-e2b0-6169-1c3c7786e0b8
* Version Independent ID: a5b03b42-1340-db14-0f0c-695a083390cd
* Content: [Renew Network Controller certificates before they expire - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/update-network-controller-certificates#view-certificate-expiry)
* Content Source: [azure-stack/hci/manage/update-network-controller-certificates.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/update-network-controller-certificates.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by VikasPullagura-MSFT** [comment]
@luyaof 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@ManikaDhiman 
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManikaDhiman** [comment]
@luyaof: Thanks for the feedback! I verified the suggested edits with the SME and updated the article accordingly--updates will be live shortly. Thanks again for helping us improve our docs!

**Comment by ManikaDhiman** [comment]
@VikasPullagura-MSFT: Could you close this issue after the changes are live? Thanks!

**Comment by ManikaDhiman** [comment]
The updates are now live.
#please-close
