### ISSUE TITLE
Are API profiles still being published?

### ISSUE THREAD

**Issue by maxwolffe** [MicrosoftDocs/azure-stack-docs#2150]
Hey friends, 

Perhaps a silly question, but I was reading the documentation on profiles here - https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-version-profiles.md and see that new API profiles are meant to be published every 6 months in September and March. 

But the latest profile according to my cli and the docs here - https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-profiles-azure-resource-manager-versions?view=azs-2206 - is `2020-09-01-hybrid`. 

I also see the same when I attempt to set a newer profile:
```
❯ az cloud set --name AzureCloud --profile 2022_09_01_hybrid

az cloud set: '2022_09_01_hybrid' is not a valid value for '--profile'. Allowed values: latest, 2017-03-09-profile, 2018-03-01-hybrid, 2019-03-01-hybrid, 2020-09-01-hybrid.
Did you mean '2020-09-01-hybrid' ?
```

I'm checking because on AzureChinaCloud we're seeing the following error newly pop up this afternoon on jobs which were working fine earlier in the day: 
```
ERROR: Invalid profile is used for cloud 'AzureChinaCloud'. To configure the cloud profile, run `az cloud set --name AzureChinaCloud --profile <profile>(e.g. 2019-03-01-hybrid)`. For more information about using Azure CLI with Azure Stack, see https://docs.microsoft.com/azure-stack/user/azure-stack-version-profiles-azurecli2
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5eeeb82f-110e-e6f6-0c08-d1394c2cc043
* Version Independent ID: fed904fd-c5d3-ad20-860b-8b3161f4c418
* Content: [Resource provider API versions supported by profiles in Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-profiles-azure-resource-manager-versions?view=azs-2206)
* Content Source: [azure-stack/user/azure-stack-profiles-azure-resource-manager-versions.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-profiles-azure-resource-manager-versions.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by RamanathanChinnappan-MSFT** [comment]
@maxwolffe 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@maxwolffe 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
> @maxwolffe Can you please check and add your comments on this doc update request as applicable.

@SaibabaBalapur-MSFT Can you please assign this to the correct person? @maxwolffe is the original submitter...

**Comment by SaibabaBalapur-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
This should all be updated now, please let us know if that is not the case.
