### ISSUE TITLE
Doc error, dead link

### ISSUE THREAD

**Issue by HotCakeX** [MicrosoftDocs/azure-stack-docs#2152]
Hi,

in here:

https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/asdk/asdk-telemetry.md

Azure Stack telemetry is based on the Windows Server 2016 Connected User Experience and Telemetry component, which uses the [Event Tracing for Windows (ETW)](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/windows/win32/tracelogging/trace-logging-about) trace logging technology to...

![image](https://user-images.githubusercontent.com/118815227/215283033-5595346f-ff65-4d59-8326-7b459afd5cdd.png)

the link leads to a page not found error.

![image](https://user-images.githubusercontent.com/118815227/215283096-e58a3662-20fa-490d-a9e5-e78dcf306208.png)

--
title: Azure Stack telemetry 
description: Learn how to configure Azure Stack telemetry settings using PowerShell.
author: sethmanheim

ms.topic: article
ms.date: 02/12/2019
ms.author: sethm
ms.reviewer: misainat

**Comment by RamanathanChinnappan-MSFT** [comment]
@HotCakeX 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
@HotCakeX That is the correct behavior -- you are incorrectly viewing the docs in the public GitHub repo, and it's trying to link to an article in a different repo. The docs on learn.microsoft.com all have working links: https://learn.microsoft.com/en-us/azure-stack/asdk/asdk-telemetry?view=azs-2206. #please-close
