### ISSUE TITLE
correction in code.

### ISSUE THREAD

**Issue by virenderrawatgit** [MicrosoftDocs/azure-stack-docs#2154]
az azurestackhci galleryimage create --subscription $subscription --resource-group $resource_group --extended-location name=$customLocationID type="CustomLocation" --location $Location --image-path $galleryImageSourcePath --name $galleryImageName --os-type $osType

This code needs to fix. Fix the Variable which used earlier in above code.

$Subscription = "<Subscription ID>"
$Resource_Group = "<Resource group>"
$Location = "<Location for your Azure Stack HCI cluster>"
$ImageName = <VM image name>
$ImageSourcePath = <path to the source image>
$OsType = "<OS of source image>"

az azurestackhci galleryimage create --subscription $subscription --resource-group $resource_group --extended-location name=$customLocationID type="CustomLocation" --location $Location --image-path $galleryImageSourcePath --name $galleryImageName --os-type $osType

$galleryImageSourcePath = use $ImageSourcePath 
$galleryImageName = use $imageName

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cdb4b608-50ee-eb3d-6077-182db09e0655
* Version Independent ID: f9d524d3-e47d-e9c8-a626-619876e3295a
* Content: [Create Azure Stack HCI VM from local share images via Azure CLI (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/virtual-machine-image-local-share?tabs=azurecli)
* Content Source: [azure-stack/hci/manage/virtual-machine-image-local-share.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/virtual-machine-image-local-share.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by SaibabaBalapur-MSFT** [comment]
@virenderrawatgit 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@virenderrawatgit 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by virenderrawatgit** [comment]
hi sir,
if you look into the query so the variable used is not the same so the output will send the error.



$Subscription = "<Subscription ID>"
$Resource_Group = "<Resource group>"
$Location = "<Location for your Azure Stack HCI cluster>"
$ImageName = <VM image name>
$ImageSourcePath = <path to the source image>
$OsType = "<OS of source image>"

please check the Variable $ImageName, $ImageSourcePath


Create the VM image starting with a specified image in a local share on your Azure Stack HCI cluster.

az azurestackhci galleryimage create --subscription $subscription --resource-group $resource_group --extended-location name=$customLocationID type="CustomLocation" --location $Location --image-path $galleryImageSourcePath --name $galleryImageName --os-type $osType


I tested and it's working only when I use below script

az azurestackhci galleryimage create --subscription $subscription --resource-group $resource_group --extended-location name=$customLocationID type="CustomLocation" --location $Location --image-path $ImageSourcePath --name $ImageName --os-type $osType




________________________________
