### ISSUE TITLE
set-akshcinodepool -vmsize not documented

### ISSUE THREAD

**Issue by azvise** [MicrosoftDocs/azure-stack-docs#2155]
Hello, 
when reviewing the powershell doc for the "set-akshcinodepool" command, the -vmsize parameter is not documented. 
The parameter is only mentioned in the upscaling doc: 
https://learn.microsoft.com/en-us/azure/aks/hybrid/concepts-vertical-node-pool-scaling

Can the parameter be added to the command documentation? the command mentioned in the article about upscaling is working fine:

Set-AksHciNodePool -ClusterName mycluster -name mycluster-linux -vmsize Standard_A4_v2

Link: https://learn.microsoft.com/en-us/azure/aks/hybrid/reference/ps/set-akshcinodepool 
or https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/reference/ps/set-akshcinodepool.md

Thanks

**Comment by SaibabaBalapur-MSFT** [comment]
@azvise 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@azvise 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
#assign:sethmanheim

**Comment by sethmanheim** [comment]
Hi @azvise, thank you for pointing this out. I have a PR filed to fix this and am just waiting for some further information from the product team. Should be updated in a day or two. #please-close
