### ISSUE TITLE
Missing manual installation for Bootstrapping - Disconnectec scenario

### ISSUE THREAD

**Issue by taeheenator** [MicrosoftDocs/azure-stack-docs#216]
The following needs to be done, otherwise Registration will fail
https://docs.microsoft.com/en-us/powershell/gallery/how-to/getting-support/bootstrapping-nuget#manually-bootstrapping-the-nuget-provider-on-a-machine-that-is-not-connected-to-the-internet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d14a302-9b02-8eb4-1b49-b52580a67472
* Version Independent ID: 10c55050-5b52-a48d-bfb2-eba0a4494900
* Content: [Install PowerShell for Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-install#feedback)
* Content Source: [azure-stack/operator/azure-stack-powershell-install.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-powershell-install.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by msrini-MSFT** [comment]
@taeheenator , Thank you for your feedback, We will investigate and get back to you.

**Comment by TravisCragg-MSFT** [comment]
@taeheenator Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@taeheenator Thanks for pointing this out. I've added the step and it should show up with our next build. Thanks!

**Comment by mattbriggs** [comment]
#please-close
