### ISSUE TITLE
cluster name note missing in eval guide

### ISSUE THREAD

**Issue by phwecker** [MicrosoftDocs/azure-stack-docs#2164]
the manual instructions at https://learn.microsoft.com/en-us/azure/aks/hybrid/reference/ps/new-akshcicluster state, that : 
Note
Do not include hyphens in cluster names, or the cluster creation may fail.

however the eval guide has no such note, neither in 2a nor 2b ... 

in 2a (create via windows admin center) however, the UI has a default value for the cluster name of "my-workload-cluster" which violates the above note. 

if indeed it is a technical limitation for the cluster name to have NO hyphans, then (a) the note should be added to the eval guide, and (b) the product UI should be corrected to use a valid name (and even better, the field validation should act accordingly) 

if this is no longer a limitation, then the note should be removed. 

title: New-AksHciCluster for AKS hybrid
author: sethmanheim
description: The New-AksHciCluster PowerShell command creates a new managed Kubernetes cluster.
ms.topic: reference
ms.date: 11/30/2022
ms.author: sethm
ms.lastreviewed: 
ms.reviewer: mikek

**Comment by SaibabaBalapur-MSFT** [comment]
@phwecker 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@phwecker 
I'm going to assign this to the document author so they can take a look at it accordingly.

@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
Hi @phwecker -- thank you for reaching out and very sorry for the delay in responding. The evaluation guide has been retired, so this should no longer be an issue. #please-close
