### ISSUE TITLE
Typo in the PowerShell setup script for installing required features/roles

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/azure-stack-docs#2165]
This should be `FS-SMBBW`

![image](https://user-images.githubusercontent.com/503974/216085467-350a0fca-a712-4103-90d0-ea95f9bd7fab.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df3012c4-22e5-004d-da6f-60744f2cfb4f
* Version Independent ID: 57e21edd-9a2b-f1ca-2ff7-48e3da5dc260
* Content: [Create an Azure Stack HCI cluster using Windows PowerShell - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell)
* Content Source: [azure-stack/hci/deploy/create-cluster-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/create-cluster-powershell.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ronmiab
* Microsoft Alias: **robess**

**Comment by SaibabaBalapur-MSFT** [comment]
@eponerine 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@eponerine 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
