### ISSUE TITLE
Update from AzureRM to Az

### ISSUE THREAD

**Issue by Agazoth** [MicrosoftDocs/azure-stack-docs#217]
Modules need to be updated to use Az in stead of AzureRM

**Comment by DixitArora-MSFT** [comment]
@Agazoth Thank you for your feedback! Since this channel is for driving improvements towards MS Docs, could you provide the URL of the specific documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by DixitArora-MSFT** [comment]
@Agazoth  Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
