### ISSUE TITLE
"Important" note at top of document is ambiguous about Linux VM support

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#2183]
In the Important note at the top, it says-

> The EVA feature is limited to Windows Server computers running with a GUI...

This wording is confusing some people into thinking that EVA is not available for Linux VMs. 
Please make it clearer that this limitation applies only to Windows Server Core versus normal Windows Server with GUI, e.g.

> For VMs running Windows Server, the EVA feature is limited to computers running with a version with a GUI. For Windows Server Core...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 221ace5c-e2df-f784-d570-a39563c13a8d
* Version Independent ID: 38a14acb-21f5-5378-6ece-50e89e437025
* Content: [Emergency VM access in Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/emergency-vm-access?view=azs-2206&tabs=azurerm1)
* Content Source: [azure-stack/user/emergency-vm-access.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/emergency-vm-access.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@alexsmithMSFT 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@alexsmithMSFT I have a PR filed to update this. Changing the note to:

"The EVA feature is limited to computers running with a graphical user interface (GUI). For Windows Server, the core operating system doesn't support on-screen keyboard functionality. Since you cannot send the **Ctrl+Alt+Del** key combination..." etc.

**Comment by alexsmithMSFT** [comment]
@sethmanheim thanks for the update, however, this first sentence is still not true-
> The EVA feature is limited to computers running with a graphical user interface (GUI).

For EVA on a Linux VM a GUI is not required, and EVA should work on a Linux text-based terminal because Ctrl+Alt+Del key combination is not required to log in.
