### ISSUE TITLE
Command syntax error - Register-CustomAdfs -CustomAdfsName Contoso -CustomADFSFederationMetadataFileContent $using:federationMetadataFileContent

### ISSUE THREAD

**Issue by Lihailian** [MicrosoftDocs/azure-stack-docs#2188]
Hi Team,
In the document, it is suggested to connect to PEP and then register-CustomAdfs :
+++
$federationMetadataFileContent = get-content c:\metadata.xml
$creds=Get-Credential
Enter-PSSession -ComputerName <IP Address of ERCS> -ConfigurationName PrivilegedEndpoint -Credential $creds

Register-CustomAdfs -CustomAdfsName Contoso -CustomADFSFederationMetadataFileContent $using:federationMetadataFileContent
+++

However, using variable can be used only with invoke-command, so we will get error:
![image](https://user-images.githubusercontent.com/45778009/217743139-5968223c-c122-4d6a-b61f-87581a2e2a9a.png)

Could you update the command as "Register-CustomAdfs -CustomAdfsName Contoso -CustomADFSFederationMetadataFileContent $federationMetadataFileContent" or not enter-pssession, juct invoke the session to run the command please? Thanks!

Regards,
Hailian Li

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d295c322-0813-e159-e6f8-86f04b759c48
* Version Independent ID: 02b87d3f-125b-d674-b750-79dbaee5e497
* Content: [Integrate AD FS identity with your Azure Stack Hub datacenter - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-identity?view=azs-2206#create-federation-metadata-file)
* Content Source: [azure-stack/operator/azure-stack-integrate-identity.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-integrate-identity.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by ManoharLakkoju-MSFT** [comment]
@Lihailian 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@Lihailian 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
