### ISSUE TITLE
Instructions for creating a Windows Image don't work.  You need to install the ADK first to be able to do this.

### ISSUE THREAD

**Issue by grahamcarter** [MicrosoftDocs/azure-stack-docs#2189]
Instructions for creating a Windows Image don't work. You need to install the ADK first to be able to do this

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 842bf434-fd3f-5a56-4dee-794858175bed
* Version Independent ID: 779df781-d6a7-0a43-1f1a-2fc66eb9e82f
* Content: [Deploy SDN using Windows Admin Center - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/sdn-wizard)
* Content Source: [azure-stack/hci/deploy/sdn-wizard.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/sdn-wizard.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by ManoharLakkoju-MSFT** [comment]
@grahamcarter 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@grahamcarter 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@ManikaDhiman 
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManikaDhiman** [comment]
@grahamcarter: Could you let us know which OS version are you running? Thanks!

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by alkohli** [comment]
A couple of notes here. The procedure to deploy SDN using Windows Admin Center has now 2 versions. The procedure in this article against which the git issue is opened is now applicable only to v22H2 cluster. For new Azure Stack HCI, v23H2 clusters, use this procedure: https://learn.microsoft.com/en-us/azure-stack/hci/deploy/sdn-wizard-23h2. This doc was completely reviewed and updated based on PM review. Please take a look. 

Since there was no ask to keep this issue open, we will go ahead and close it. #please-close
