### ISSUE TITLE
specify a more clear hint for Dockerfile

### ISSUE THREAD

**Issue by bottkars** [MicrosoftDocs/azure-stack-docs#219]
the example dockerfile will not work for (default) docker desktop.
also, a default latest tag does not exist.

for 2019 one may use `FROM mcr.microsoft.com/windows/servercore:1903-KB4505057`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55e2558f-e434-e5cc-acd4-0d3bd2dd979f
* Version Independent ID: be6bfe5f-bfdd-6550-588d-6d627c16c3f8
* Content: [Use Docker to run PowerShell in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-powershell-user-docker)
* Content Source: [azure-stack/user/azure-stack-powershell-user-docker.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-powershell-user-docker.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by DixitArora-MSFT** [comment]
Hi @bottkars Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by jakaruna-MSFT** [comment]
@bottkars Thanks for reporting. Dockerfiles base image has to be changed.
Better to change that to `mcr.microsoft.com/windows/servercore:ltsc2019`

I will assign this issue to the author to investigate and update the document.

CC: @TravisCragg-MSFT

**Comment by mattbriggs** [comment]
@bottkars, @jakaruna-MSFT 

Thanks for providing feedback about this. It looks like latest was deprecated, and it looks like there have been some updates that may also cause some issues. Here is a thread that discusses it.

https://github.com/docker/for-win/issues/3761

I will update shortly when I work out the kinks. #in-progress

**Comment by bottkars** [comment]
Yes, we are facing some issues as well. When pullend from docker, we have eben able to Extract Digest, Headers etc from Go. Since pulling the new ones from mcr, the Go-libraries Face Various issues...

**Comment by mattbriggs** [comment]
@bottkars Thanks for the note. Pulling the image using the tag `ltsc2019` I am able to use the dockerfile. Iv'e updated the dockerfile to `mcr.microsoft.com/windows/servercore:ltsc2019`. I am running this is on Windows 10 Enterprise 1809. I will close this thread for now, but please me know if you have additional feedback or questions. Thanks again! Matt

**Comment by mattbriggs** [comment]
#please-close
