### ISSUE TITLE
More info would be appreciated on the network changes on ASDK 1901

### ISSUE THREAD

**Issue by BjornAnd** [MicrosoftDocs/azure-stack-docs#22]
In the release notes it is stated "BGP and NAT components are now deployed on the physical host. This eliminates the need to have two public or corporate IP addresses for deploying the ASDK, and also simplifies deployment."
Since networking is absolute key to get a cloud working it would be appreciated if there were some more info about how this change has been implemented. 
We normally set up our ASDKs as routed installations (no VPN and such) so the new 1901 installation is proving to quite the handful to get to work.. :)
(yeah, i know that our way of installation isn't the normal, or probably even supported way. But the end customers LOVE it and it makes the barrier to get them to try it SO much lower)
//Bjorn Andersson, Visolit Sweden (previously known as "TeleComputing sweden")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8368a3-49e9-5216-f7cb-f91f6f1122c1
* Version Independent ID: 12092beb-efeb-974f-f9fe-5428435b228b
* Content: [Microsoft Azure Stack Development Kit release notes](https://docs.microsoft.com/en-us/azure/azure-stack/asdk/asdk-release-notes)
* Content Source: [articles/azure-stack/asdk/asdk-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-release-notes.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@BjornAnd Sorry for leaving this open for so long. Is this still an issue? The ASDK has undergone some changes recently. If so, can you please open a new issue and @ mention me? Thanks again for your feedback. #please-close
