### ISSUE TITLE
Undocumented required port 30301

### ISSUE THREAD

**Issue by peterLeathMSFT** [MicrosoftDocs/azure-stack-docs#2209]
Discovered that hcisvc licensing binds and listens on port 30301
This port is not listed under the required internal rules and ports

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22d4fc82-62b9-6924-c0c5-605b63e09372
* Version Independent ID: 4abb02f9-e9a3-0e82-0f12-c31bcc77cb06
* Content: [Firewall requirements for Azure Stack HCI - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/firewall-requirements)
* Content Source: [azure-stack/hci/concepts/firewall-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/firewall-requirements.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by Naveenommi-MSFT** [comment]
@peterLeathMSFT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@peterLeathMSFT 
I'm going to assign this to the document author so they can take a look at it accordingly.

@ManikaDhiman 
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManikaDhiman** [comment]
@tiaramathur: Could you please look into this issue and let me know if any doc changes are required? Thanks!

**Comment by danielleemsft** [comment]
@ManikaDhiman Yes, I've confirmed that we need to add a new port to this doc. It should be a new section/table under this section: "Firewall requirements for internal rules and ports". It's just one row, but I think it doesn't fit in any of the other sections, so a separate, new section seems to make sense, but let me know if you have other ideas. Here's the content for the section:

Section title: Azure Stack HCI OS management
Description: Ensure that the following firewall rules are configured in your on-premises firewall for HCI OS management, including licensing and billing
Rule description: Allow inbound/outbound traffic to and from the Azure Stack HCI service on cluster servers
Action: Allow
Source: Cluster servers
Destination: Cluster servers
Service: TCP
Ports: 30301

**Comment by ManikaDhiman** [comment]
@peterLeathMSFT: Thanks for your feedback! We've added a new section for [Azure Stack HCI OS management](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/firewall-requirements#azure-stack-hci-os-management) under the required internal rules and ports section. I am closing this issue now as the required updates are done. Thanks again!

#please-close
