### ISSUE TITLE
Start the WindowsAzureGuestAgent

### ISSUE THREAD

**Issue by lucidqdreams** [MicrosoftDocs/azure-stack-docs#221]
I had been having the installation fail on stack 1905 to 1906 (with hotfixes) using 1.9.1 and 1.9.3 custom script extension.  the deployment would fail during the custom script extension to the SQLRP vm.  After looking through the logs and chasing a few dead ends it appears that the WindowsAzureGuestAgent service simply wasn't started.  The service startup type was set to automatic but 'Microsoft Azure VM Health Report' showed

      {  
         "errorControl":"Normal",
         "exitCode":1067,
         "name":"WindowsAzureGuestAgent",
         "processId":0,
         "serviceType":"Own Process",
         "startMode":"Auto",
         "startName":"LocalSystem",
         "state":"Stopped",
         "status":"OK"
      },

After changing the NSG to allow RDP access, so I could manually start the WindowsAzureGuestAgent service during the first two extension deployments SQLAdapterDeployment and IaaSDiagnostics allowed these to extensions to complete successfully.  After the next reboot,  I'm guessing RDP was disabled.  I had to gain access through HyperV and the VM console and again start the WindowsAzureGuestAgent service manually for the DbAdapterSecurityConfiguration extension to complete.  

The final ARM templates against the subscription ran just fine.  I had logged a case and been working through it with the engineer 119062724002737 but in the end, this is what I had to do for the deployment to complete.  I had tried this deployment from Powershell and the ISE several times through the different versions of Stack and two versions of the custom script extension.  

This was not a one-off deployment issue for me, it was 'consistent' 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dabc86bd-3770-5832-7fa5-d28856998ae6
* Version Independent ID: cbdb8c6f-ad4d-9e3d-a490-f1348b5ccdfa
* Content: [Using SQL databases on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-deploy)
* Content Source: [azure-stack/operator/azure-stack-sql-resource-provider-deploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-sql-resource-provider-deploy.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by DixitArora-MSFT** [comment]
Hi @lucidqdreams Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by TravisCragg-MSFT** [comment]
@lucidqdreams Thanks for sharing, and I am glad you were able to resolve the issue with support. I will follow up with the doc author & others to make sure that no updates are needed.

**Comment by mattbriggs** [comment]
@lucidqdreams, thanks as well for sharing your experience and resolution. I'll see what we need to do get this documented. #in-progress

**Comment by lucidqdreams** [comment]
This was an all NVMe stamp, so machines boot very quickly.  We had some other issues with the OS starting too quickly and other services not being ready.  I'm not sure what the retry options are for the guest agent service but maybe worth looking at.

**Comment by mattbriggs** [comment]
@lucidqdreams HI ... I sent a note to engineering, and they are trying to replicate your experience. I let them know the originating support ticket. For now there isn't an update to the docs. Thanks again for your information!

**Comment by TravisCragg-MSFT** [comment]
@lucidqdreams We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
