### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by phangwt** [MicrosoftDocs/azure-stack-docs#2220]
The two following command lines are identical.  How do we know whether the command line is running on local node or non-local node as there is only one result from a single command line?

    Running on local node: .\DiskSpd-2.0.21a\amd64\diskspd.exe -t4 -o32 -b4k -r4k -w0 -Sh -D -L C:\ClusterStorage\test01\targetfile\IO.dat
    Running on nonlocal node: .\DiskSpd-2.0.21a\amd64\diskspd.exe -t4 -o32 -b4k -r4k -w0 -Sh -D -L C:\ClusterStorage\test01\targetfile\IO.dat

![image](https://user-images.githubusercontent.com/73534096/220812340-18229b5f-0757-496a-8bfb-b67dcb071702.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dcbfe3b-52e3-7cc4-0727-3055383db649
* Version Independent ID: c894cd31-5738-8a11-78ec-5ecb4b8ad341
* Content: [Use DISKSPD to test workload storage performance - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/diskspd-overview)
* Content Source: [azure-stack/hci/manage/diskspd-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/diskspd-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @jasonnyi
* Microsoft Alias: **jasonyi**

**Comment by YashikaTyagii** [comment]
@phangwt 
Thanks for your feedback! We have assigned the issue to author and will provide further updates.

**Comment by sethmanheim** [comment]
@phangwt Thank you for reaching out and sorry for the slow response. If you still need assistance, please open a new feedback request. #please-close
