### ISSUE TITLE
This page has ambiguous language about which version of Stack HCI is required for GPU-P. 

### ISSUE THREAD

**Issue by dkirby-ms** [MicrosoftDocs/azure-stack-docs#2228]
This page has ambiguous language about which version of Stack HCI is required for GPU-P. 

This is the specific language: 

`To get started, you’ll need an Azure Stack HCI cluster of at least two servers, running Azure Stack HCI, version 21H2. You’ll also need GPUs that are physically installed in every server of the cluster.`

I dont believe we are version constrained to only 21H2. This text should more explicitly indicate that 22H2 works with the feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c08dae85-343a-8053-316f-fa321a0c46dc
* Version Independent ID: e91c7aa1-e79b-752b-f9ae-7f29d9629ae2
* Content: [Use GPUs with clustered VMs - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/use-gpu-with-clustered-vm)
* Content Source: [azure-stack/hci/manage/use-gpu-with-clustered-vm.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/use-gpu-with-clustered-vm.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @rick-man
* Microsoft Alias: **rickman**

**Comment by VikasPullagura-MSFT** [comment]
@dkirby-ms 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@rick-man 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@dkirby-ms Sorry for the slow response here. Please contact us (the doc team) directly if a documentation update is needed. Thanks! #please-close
