### ISSUE TITLE
page could be improved

### ISSUE THREAD

**Issue by Bae-ver** [MicrosoftDocs/azure-stack-docs#2231]
Our Dell assisted install just failed and has set us back at least a day, hopefully this info will help others.

Option 2 creates a the certificates but gives them all the same subject name, you even state this on the page "The first DNS name of the Azure Stack Hub service will be configured as the CN field on the certificate request." - the trouble is, 12 hour azure stack installation process then fails during a disconnected setup because dns1 (Subject Alt Name) doesn't match the Subject Name / CN,and the adfs and graph service certificates both fail.  We were 70% through and the whole thing has to be started again, gah!

Option 3 info details are incorrect and fails to create: # Azure Container Registry
New-AzsHubAzureContainerRegistryCertificateSigningRequest -RegionName $regionName -FQDN $externalFQDN -subject $subject -OutputRequestPath $OutputDirectory 

The last command fails it can be fixed by adding a CN/Subject, but its in a section for no CN :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6faad96b-2671-fa69-2897-eb33eaaa7a71
* Version Independent ID: 0d02649c-e207-069d-c062-dc4b824fdd26
* Content: [Generate certificate signing requests for Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-get-pki-certs?view=azs-2206&tabs=omit-cn&pivots=csr-type-new-deployment)
* Content Source: [azure-stack/operator/azure-stack-get-pki-certs.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-get-pki-certs.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by AjayBathini-MSFT** [comment]
@Bae-ver 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@Bae-ver 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by AjayBathini-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by erskinejohn** [comment]
Hi @Bae-ver, I'm the tool owner and document contributor.  Apologies you've had this experience, the tool and documentation are there to avoid exactly this issue., I'm sorry its let you down.

To help me better understand your scenario, would you be able to provide clarity on "option 2" and "option 3" nomenclature, I'm not familiar with this.  It would also be really useful if you could provide the PowerShell commands you issued which lead to the problem and the commands you issued to remediate the problem.  Something like cmdlet name(s) and parameters used, I don't need variable values.

Thanks

**Comment by Bae-ver** [comment]
Hi John, 

Option 3:  the last step  (the command in bold) will fail.

$outputDirectory = "C:\AzureFiles\AzureStackCSR\SubOnlyCN-IncludeContainerRegistry-ALL" # An existing output directory
$IdentitySystem = "ADFS"                     # Use "AAD" for Azure Active Director, "ADFS" for Active Directory Federation Services
$regionName = 'xch'                        # The region name for your Azure Stack Hub deployment
$externalFQDN = 'mgmt.mdn.local'    # The external FQDN for your Azure Stack Hub deployment

New-AzsCertificateSigningRequest -CertificateType Deployment -RegionName $regionName -FQDN $externalFQDN -OutputRequestPath $OutputDirectory -IdentitySystem $IdentitySystem -IncludeContainerRegistry

# App Services
New-AzsCertificateSigningRequest -CertificateType AppServices -RegionName $regionName -FQDN $externalFQDN -OutputRequestPath $OutputDirectory

# DBAdapter (SQL/MySQL)
New-AzsCertificateSigningRequest -CertificateType DbAdapter -RegionName $regionName -FQDN $externalFQDN -OutputRequestPath $OutputDirectory

# EventHubs
New-AzsCertificateSigningRequest -CertificateType EventHubs -RegionName $regionName -FQDN $externalFQDN -OutputRequestPath $OutputDirectory

**# Azure Container Registry
New-AzsHubAzureContainerRegistryCertificateSigningRequest -RegionName $regionName -FQDN $externalFQDN -subject $subject -OutputRequestPath $OutputDirectory**

Option 2 - this seems more aimed at a wild card certificate situation, as why else would you ever want the subject name to be the same for everything?  If you are in a disconnected environment (as we were) then you need ADFS, and it would never be good security practice to use a wild card here.  We learned all this the hard way because the adfs and related graph service fell over 70% of the way through a 12 hour installation and meant we had to start the whole thing over again.

My advice would be to just have option 1 up there really, or at least to recommend it.   As there was no recommendation I actually made all 3 sets of certs ready for our installation in case one was preferred over the other by Dell.  Because option 3 didn't work, I just flipped a coin. option 2 won the toss and ended up being a bad call.

Option 1 was used in the end and got the job done. 

Hope this helps.

**Comment by sethmanheim** [comment]
@Bae-ver Please open a new issue if you still require assistance here. Thank you for reaching out! #please-close
