### ISSUE TITLE
HCI 22H2 build 20349.1194 shows the wrong Availability date

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#2232]
From the release summary table in https://learn.microsoft.com/en-us/azure-stack/hci/release-information#azure-stack-hci-release-summary, the latest 22H2 build 20349.1194 shows an Availability date of **2022-10-12**...

Version | Availability date | OS build | Apply update by
-- | -- | -- | --
22H2 | **2022-10-12** | 20349.1194 | 2023-04-12

But the actual release was [October 25, 2022 Non-security update (KB5018485)](https://support.microsoft.com/en-us/topic/october-25-2022-non-security-update-kb5018485-513988dc-4a9f-40ca-b089-e4c7703ad06e). Which is correctly listed in the second table- https://learn.microsoft.com/en-us/azure-stack/hci/release-information#azure-stack-hci-version-22h2-os-build-20349.

I recommend confirming and then updating 20349.1194 to "Availability date" of 2022-10-25 and "Apply update by" 2023-04-25 (6 months later).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22ce0662-cc07-34bc-1d9c-de7fd075bdee
* Version Independent ID: fc01822a-5d78-b4e0-eb1a-ccd8d9c7bdf0
* Content: [Azure Stack HCI release information - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/release-information#azure-stack-hci-release-summary)
* Content Source: [azure-stack/hci/release-information.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/release-information.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by AjayBathini-MSFT** [comment]
@alexsmithMSFT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@alexsmithMSFT 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.

https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/12172
