### ISSUE TITLE
New-NetIntentProxyOverride does not exist

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#2234]
This document references a PowerShell cmdlet "New-NetIntentProxyOverride".  Since it does not state what module it is part of, one should expect that it is an export of the NetworkATC module (since that is where all other NetIntent* cmdlets are) on Azure Stack HCI 22H2.  However, this cmdlet does not appear to be in ANY PowerShell module.

Proxy configuration for Azure Stack HCI is a HIGHLY DESIRED FEATURE.  Remove this erroneous information form the document or fix the document to reflect what ever the current realty is.
![image](https://user-images.githubusercontent.com/15333804/222229562-51c050f3-4ab1-4080-8e62-fb58be1e2c7a.png)
![image](https://user-images.githubusercontent.com/15333804/222229871-e1087670-c8e5-4e9c-9061-04c1b3d25cd7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1cea280-89dd-b421-0ca9-da8fc972610d
* Version Independent ID: 746905a4-0549-449c-6842-d365fb7da05d
* Content: [Manage Network ATC - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/manage-network-atc?tabs=21H2)
* Content Source: [azure-stack/hci/manage/manage-network-atc.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/manage-network-atc.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by VikasPullagura-MSFT** [comment]
@aricbernard 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@JasonGerend 
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManikaDhiman** [comment]
Hi @aricbernard: Thanks for your feedback! The article has been updated to reflect the correct cmdlet name: https://learn.microsoft.com/en-us/azure-stack/hci/manage/manage-network-atc?tabs=21H2

Thanks again for your input that helped improve this article!

#please-close
