### ISSUE TITLE
Include "Data wipe" in Shutdown title 

### ISSUE THREAD

**Issue by BrunoStack** [MicrosoftDocs/azure-stack-docs#2244]
It would be easier for customer to know that the data will/can be wiped in the Step "Shutdown" including in the title, I see the second option " Start-AzsCryptoWipe" does mention as non-recoverable but its more highlighted if its mentioned in the "Shutdown" title. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70fe15ac-3fa4-9acd-2392-6286cec0ed09
* Version Independent ID: 50e81103-ac2b-73c7-8d87-f78d5156bd87
* Content: [Decommission an Azure Stack Hub system - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-hub-decommission?view=azs-2206)
* Content Source: [azure-stack/operator/azure-stack-hub-decommission.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-hub-decommission.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
Thanks for the feedback @BrunoStack. So are you saying that the blue highlighted "Important" note is not sufficient to convey the idea that shutting down is non-recoverable?

**Comment by BrunoStack** [comment]
It is sufficient that it is mentioned in the blue highlighted, what I was trying to say is to include the "Data Wipe" mentioned in the title, since the title reads as "Shut Down Azure Stack Hub" - if it makes sense

**Comment by sethmanheim** [comment]
I apologize, I am actually not sure what you're asking. The section describes the two options for shutting down -- recoverable and non-recoverable. Each is clearly described. Please be more specific with what documentation changes you're requesting.

**Comment by sethmanheim** [comment]
@BrunoStack Yes however only one of the options in that section is non-recoverable, so the data wipe only applies to option 1, correct?

**Comment by BrunoStack** [comment]
This looks good, thanks for updating.
