### ISSUE TITLE
Why no AD in disconnected ASH ?

### ISSUE THREAD

**Issue by rboro-home** [MicrosoftDocs/azure-stack-docs#2248]
It would be worth explaining why there can be no AD in a disconnected Azure stack hub ? Surely AD can be deployed within a subscription in the ASH ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3914390-367c-471b-b653-7672f967f472
* Version Independent ID: 08ecfe0f-a12d-9d24-8d25-a23b1aa1401a
* Content: [Azure disconnected deployment decisions for Azure Stack Hub integrated systems - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-disconnected-deployment?view=azs-2206)
* Content Source: [azure-stack/operator/azure-stack-disconnected-deployment.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-disconnected-deployment.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SaibabaBalapur-MSFT** [comment]
@rboro-home 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@rboro-home 
I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds.

[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1
