### ISSUE TITLE
Loadbalancer limitation/quota missing in Doku

### ISSUE THREAD

**Issue by weyCC81** [MicrosoftDocs/azure-stack-docs#228]
Hi Microsoft

The Basic LB limits are not the same as in Azure:
https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#load-balancer
     Resource | Default/maximum limit
     Front-end IP configurations, Basic | 200

Powershell Error: `
> $slb | Set-AzureRmLoadBalancer
Set-AzureRmLoadBalancer : Basic sku load balancer /path/ cannot have more than 5 FrontendIPConfigurations.
StatusCode: 400
ReasonPhrase: Bad Request
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd5972fd-29f4-2643-56d4-98f845a132e6
* Version Independent ID: 900d8d64-db85-6db9-3a38-22d84d0c55df
* Content: [Azure Stack networking Differences and considerations](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-differences#feedback)
* Content Source: [azure-stack/user/azure-stack-network-differences.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-network-differences.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@weyCC81 Thanks for your feedback. I am double-checking an update and will post it shortly. Thanks! Matt

#please-close

**Comment by weyCC81** [comment]
There hasn't been made any changes in the Documentation.
Is this still ongoing? (Case has been closed)

**Comment by mattbriggs** [comment]
@weyCC81 The update is pending review. Thanks for checking.

**Comment by weyCC81** [comment]
The default System-Quota (from Microsoft) is set to 5. It can be changed, in our case it has been changed to 10.
(Maybe possible to increasing this until limit from Azure Basic LB which has a limit of 200).

**Comment by weyCC81** [comment]
What has this commit to do with this issue?
(still not Documented)

**Comment by mattbriggs** [comment]
@weyCC81 thanks for reopening this issue. Not sure what happened to my update.

#in-progress

**Comment by mattbriggs** [comment]
This has been updated: https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-differences?view=azs-1910

**Comment by mattbriggs** [comment]
#please-close
