### ISSUE TITLE
Ports/Protocols: Missing PEP and Backup 

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [MicrosoftDocs/azure-stack-docs#2281]
Please validate if the listed incoming and outgoing services are up-to-date.

It is missing information relating to:
incoming: Privilege Endpoint
outgoing: Infrastructure backup to SMB share

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34d02f93-1ae9-eb2d-9c0f-0af012653885
* Version Independent ID: 18f15ad2-ef9b-f883-c49b-09289a2e6fb8
* Content: [Publish Azure Stack Hub services in your datacenter - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-endpoints?view=azs-2206)
* Content Source: [azure-stack/operator/azure-stack-integrate-endpoints.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-integrate-endpoints.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@CHDAFNI-MSFT 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@CHDAFNI-MSFT Sorry for the delayed response -- can you please clarify what information you're looking for?
