### ISSUE TITLE
vxvxz

### ISSUE THREAD

**Issue by bacmodung** [MicrosoftDocs/azure-stack-docs#2284]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3aec5557-132f-784f-9518-f697be85988f
* Version Independent ID: 934c5dea-d126-a5b1-0cfe-875ec6191b51
* Content: [Storage Spaces Direct overview - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/storage-spaces-direct-overview)
* Content Source: [azure-stack/hci/concepts/storage-spaces-direct-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/storage-spaces-direct-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @cosmosdarwin
* Microsoft Alias: **cosdar**

**Comment by ManoharLakkoju-MSFT** [comment]
@bacmodung 
Could you please elaborate the query for better understanding. So, we can assist you further.

**Comment by ManoharLakkoju-MSFT** [comment]
@bacmodung 
Since we have not heard back from you, we will now proceed to close this thread.
If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
