### ISSUE TITLE
Certificate validation process for resource providers contains reference to -CertificateType parameter which is no longer required since we now have specific RP commands

### ISSUE THREAD

**Issue by arturoliveira** [MicrosoftDocs/azure-stack-docs#2285]
Certificate validation process for resource providers contains reference to -CertificateType parameter which is no longer required since we now have specific RP commands

![image](https://user-images.githubusercontent.com/1878109/229460455-21bd900a-afd2-4eb2-88a1-a1be5a9997f1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78ca84a2-7dba-dab4-b591-976eb360baed
* Version Independent ID: 198d7378-7246-7b4b-bd73-564a1a593140
* Content: [Validate Azure Stack Hub PKI certificates - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-validate-pki-certs?view=azs-2206)
* Content Source: [azure-stack/operator/azure-stack-validate-pki-certs.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-validate-pki-certs.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Naveenommi-MSFT** [comment]
@arturoliveira 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
Update will be made in the private repo. #please-close
