### ISSUE TITLE
Need more clarification about the cost of preview channel

### ISSUE THREAD

**Issue by kongou-ae** [MicrosoftDocs/azure-stack-docs#2300]
Hi,

Based on the following blog, I understand that host service fee($10/physical core/month) doesn't apply to the cluster which preview channel is enabled.

https://techcommunity.microsoft.com/t5/azure-stack-blog/announcing-azure-stack-hci-dev-build-25217-23h2-for-preview/ba-p/3650906

> All Preview channel participants should install build 25217. If you instead continue applying quality updates to version 22H2, your cluster will become billable when version 22H2 reaches GA soon. To avoid billing, the next time you update your Preview channel cluster, be sure to choose dev build 25217.

I can't find this information in the pricing page and this doc. I would appreciate if you could add this information in this page and the pricing page.

Best regards.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa88abef-3a20-35ac-1a47-ddf35470bc1a
* Version Independent ID: f09fe7ce-0ae4-3e2b-d3c2-2fb20a9abf58
* Content: [Join the Azure Stack HCI preview channel - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/preview-channel)
* Content Source: [azure-stack/hci/manage/preview-channel.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/preview-channel.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by AjayBathini-MSFT** [comment]
@kongou-ae 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@JasonGerend
Can you please check and add your comments on this doc update request as applicable.

**Comment by SaibabaBalapur-MSFT** [comment]
@kongou-ae 
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by sethmanheim** [comment]
@kongou-ae As we are moving to a new feedback system, we have opened corresponding work items and are tracking all open issues in our internal database.  We are closing all public issues, but as mentioned above, there are other ways to provide feedback. Thank you again for reaching out! #please-close
