### ISSUE TITLE
The create vhd for a VM section example code seems wrong.

### ISSUE THREAD

**Issue by dkirby-ms** [MicrosoftDocs/azure-stack-docs#2301]
Under the example code for using New-VHD shows a code snippet that seems unrelated to the steps required to add a VHD to a VM. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9596fb64-7f7e-de3f-e21a-7df3416ece18
* Version Independent ID: 680ad894-3dd4-334b-5f61-367e3ef498e4
* Content: [Manage VMs using Windows PowerShell - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/vm-powershell)
* Content Source: [azure-stack/hci/manage/vm-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/vm-powershell.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by AjayBathini-MSFT** [comment]
@dkirby-ms 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@dkirby-ms 
I'm going to assign this to the document author so they can take a look at it accordingly.

@JasonGerend 
Can you please check and add your comments on this doc update request as applicable.

**Comment by alkohli** [comment]
@JasonGerend  Can you please update this article? The create VHD for a VM has this cmdlet: Get-ClusterGroup which definitely seems to be unrelated. Given this article will apply to v23H2, we should update this.

**Comment by Karl-WE** [comment]
@alkohli

Please replace
Get-ClusterGroup with

`New-VHD -Path "C:\Path\To\Your\VHD.vhdx" -SizeBytes 10GB`

This would resolve this issue and ready for #sign-off

**Comment by sethmanheim** [comment]
@dkirby-ms The doc has been updated, thank you for reaching out! #please-close
