### ISSUE TITLE
Article assumes install method was powershell

### ISSUE THREAD

**Issue by peterLeathMSFT** [MicrosoftDocs/azure-stack-docs#2304]
The "clean up" or uninstall document jumps straight into uninstall steps. If the user did the install with WAC, this document needs to have a section advising how to setup the variables used in the commands
$subscription, $resource_group, $vnetName, $customloc_name, $csv_path

the command line install document has these defined and how to set them
https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address-1%2Cfor-static-ip-address-2

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e049430-9bb9-ab66-b8bc-5fa0cc7b37e5
* Version Independent ID: 387e8235-0668-18b5-fc98-e3af2e464636
* Content: [Uninstall Azure Arc VM management (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/uninstall-arc-resource-bridge)
* Content Source: [azure-stack/hci/manage/uninstall-arc-resource-bridge.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/uninstall-arc-resource-bridge.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ksurjan
* Microsoft Alias: **ksurjan**

**Comment by RamanathanChinnappan-MSFT** [comment]
@peterLeathMSFT

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@ksurjan 
Can you please check and add your comments on this doc update request as applicable.

**Comment by ZmanKyle** [comment]
@ManikaDhiman on the Troubleshooting page, let's add a few lines to remind customers who deployed via WAC. We can direct them to the "Setup using command line" doc, specifically the input param section, for the input.

**Comment by SaibabaBalapur-MSFT** [comment]
@ZmanKyle Thank you for quick response.

@peterLeathMSFT We will update the document, as of now we are closing this case, further questions please feel reach out me.

**Comment by ManikaDhiman** [comment]
A blurb has been added for clarification with a link to the command-line setup article: https://learn.microsoft.com/en-us/azure-stack/hci/manage/uninstall-arc-resource-bridge#how-to-uninstall-azure-arc-vm-management

Thanks!
