### ISSUE TITLE
ARC Appliance Status Value Incorrect

### ISSUE THREAD

**Issue by mbrat2005** [MicrosoftDocs/azure-stack-docs#2305]
Verify that the Arc appliance is running. Keep running the following cmdlets until the appliance provisioning state is Succeeded and the status is **Running**. This operation can take up to five minutes.

Running should be **Connected**

PS C:\Users\adminb> az arcappliance show --resource-group $resource_group --name $resource_name --query '[provisioningState, status]'
Command group 'arcappliance' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
[
  "Succeeded",
  "Connected"
]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2b89ce1-6af9-aaa1-48f2-da8d2f5c8b75
* Version Independent ID: db6c5f7c-77b2-7a97-dc2c-d904db88edf5
* Content: [Set up Azure Arc VM management using command line (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address-1%2Cfor-static-ip-address-2)
* Content Source: [azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ManikaDhiman
* Microsoft Alias: **v-mandhiman**

**Comment by mbrat2005** [comment]
My bad!

**Comment by RamanathanChinnappan-MSFT** [comment]
@mbrat2005 

It looks like your issue is resolved since you closed this thread.
If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
