### ISSUE TITLE
Offerring App Service to multiple ISVs

### ISSUE THREAD

**Issue by easonlauys** [MicrosoftDocs/azure-stack-docs#231]
As an Azure Stack operator, can we offer App Service to different ISVs which develops different application on the same Azure Stack platform once we provisioned when offering this App Service as PaaS? Based on my understanding, it seems the database are being shared regardless of which ISVs. Any pointers or FAQ, please assist. 
Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee9022e-5af6-93f0-8910-2200485917d1
* Version Independent ID: 25cea13d-78f7-e51b-acb0-582e71c14684
* Content: [App Service on Azure Stack overview](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-overview)
* Content Source: [azure-stack/operator/azure-stack-app-service-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-overview.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **mabrigg**

**Comment by KrishnaG-MSFT** [comment]
@easonlauys Thanks for your comment. We are actively investigating and will get back to you shortly.

**Comment by TravisCragg-MSFT** [comment]
@easonlauys There are no technical limits to offering App Service to others on your Azure Stack. The Database that is deployed is used for the operation of the Resource Provider. 

You can [create Subscriptions to offer the app services](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-plan-offer-quota-overview#subscriptions) to the ISVs. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
