### ISSUE TITLE
move delete app registrations step to after the remove-registration step

### ISSUE THREAD

**Issue by leehau** [MicrosoftDocs/azure-stack-docs#2319]
We need to move the step to actually remove the app registrations in step 4.b to after they unregister the stamp. If they delete app registrations beforehand, the unregister step will fail.

There is a vague warning after step 4b to "Proceed with app registration cleanup with caution," but it's not very helpful.

Current steps:

1. Disable multi-tenancy
2. Verify any additional guest directories
3. Remove any tenant registrations
4. Remove Azure AD app registrations for Azure Stack Hub:
5. Remove AzSH Registration
6. Shutdown AzSH
7. Crypto Wipe

Suggestion is to change step 3 to "List AAD app registrations" and add step after step 5 to remove them.

1. Disable multi-tenancy
2. Verify any additional guest directories
3. Remove any tenant registrations
4. _List_ Azure AD app registrations for Azure Stack Hub
5. Remove AzSH Registration
6. _Remove Azure AD app registrations from step 4_
7. Shutdown AzSH
8. Crypto Wipe

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70fe15ac-3fa4-9acd-2392-6286cec0ed09
* Version Independent ID: 50e81103-ac2b-73c7-8d87-f78d5156bd87
* Content: [Decommission an Azure Stack Hub system - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-hub-decommission?view=azs-2108)
* Content Source: [azure-stack/operator/azure-stack-hub-decommission.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-hub-decommission.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Naveenommi-MSFT** [comment]
@leehau 
Thanks for your feedback! We will investigate and update as appropriate.
