### ISSUE TITLE
Need to remove VM agent in Azure VM before generalize 

### ISSUE THREAD

**Issue by xizhuang** [MicrosoftDocs/azure-stack-docs#2320]
If we generalize an Azure VM and use this captured VM image in Azure stack hub, we need to remove the extensions and VM agent in Azure VM. Since Azure VM support higher version of VM agent then azure stack hub, if we don't remove VM agent in Azure VM before generalize, the VM agent will show not ready in Azure stack VM. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cb89c681-689b-a8df-38e4-671313a36774
* Version Independent ID: 67f9a8d4-4de8-0ce9-5ecd-40d7b68269c7
* Content: [Move a VM to Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/vm-move-overview?view=azs-2206)
* Content Source: [azure-stack/user/vm-move-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/vm-move-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Naveenommi-MSFT** [comment]
@xizhuang 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YashikaTyagii** [comment]
@xizhuang 
You are correct. When you generalize an Azure VM and use the captured VM image in Azure Stack Hub, you need to remove the extensions and VM agent in Azure VM. If you don't remove the VM agent in Azure VM before generalizing, the VM agent will show not ready in Azure Stack VM

**Comment by xizhuang** [comment]
Hi, YashikaTyagi,

Thanks for investigating on this.

May I know when this article will be updated?

Regards,
Xiaoyu

**Comment by YashikaTyagii** [comment]
@xizhuang 
I have assigned to content author who will update accordingly.

**Comment by sethmanheim** [comment]
@YashikaTyagii Very sorry for the delay. The article has been updated and should be live later today. Thank you for reaching out. #please-close
