### ISSUE TITLE
Broken link to akshcihost.json

### ISSUE THREAD

**Issue by nekdima** [MicrosoftDocs/azure-stack-docs#2321]
Hey Team, 

The hyperlink to the ARM template on GH seems to be broken which results in failing deployment via PowerShell (Option 2) described in this article: https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-hci-evaluation-guide-1#deploy-the-vm-with-powershell

Broken hyperlink: https://raw.githubusercontent.com/Azure/aks-hci/october_eval/eval/json/akshcihost.json

![image](https://user-images.githubusercontent.com/38444705/234276995-3e4cc570-d659-4846-92bf-c1321ac3e6f8.png)

**Comment by Naveenommi-MSFT** [comment]
@nekdima 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
Thanks for catching that @nekdima. The correct URL is https://github.com/Azure/aks-hybrid/blob/main/eval/json/akshcihost.json. I will make sure the code in the article is updated. Closing this issue...
