### ISSUE TITLE
PowerShell command should perhaps be rather Get-AzsSubscriberUsage

### ISSUE THREAD

**Issue by tkubica12** [MicrosoftDocs/azure-stack-docs#233]
It seems this page correctly points to provider usage API, but uses PowerShell command for tenant API that does not return correct data when used in AzureStackAdmin context. I guess actual command is Get-AzsSubscriberUsage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35cd7f7c-54fa-f242-bee3-860e5378b135
* Version Independent ID: 1f878748-b633-f194-e27b-43c9f7f43924
* Content: [Provider resource usage API](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-provider-resource-api#feedback)
* Content Source: [azure-stack/operator/azure-stack-provider-resource-api.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-provider-resource-api.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@tkubica12 Thanks for the feedback! [Get-AzureUsageAggregates](https://docs.microsoft.com/en-us/powershell/module/azurerm.usageaggregates/get-usageaggregates?view=azurermps-6.13.0) does correlate to the Tenant Resource Provider API call. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@tkubica12 @TravisCragg-MSFT I'm really not sure what " Get-AzureUsageAggregates does correlate to the Tenant Resource Provider API call" means, but it looks like you're saying this is not the correct cmdlet. I just submitted a PR to change the doc to use Get-AzsSubscriberUsage instead. Thank you for catching that!

**Comment by sethmanheim** [comment]
This is live now, please let us know if there are any other issues. #please-close
