### ISSUE TITLE
Azure Portal HCI drilldown screenshots are outdate here.

### ISSUE THREAD

**Issue by anoobbacker** [MicrosoftDocs/azure-stack-docs#2336]
[Enter feedback here]
The screenshots needs updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2adbb622-ebc1-dfc3-74fd-24347d437f2f
* Version Independent ID: efd42319-570f-b72f-689c-2cb41ca5e8d2
* Content: [Use the Azure portal with Azure Stack HCI - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/azure-portal?source=docs)
* Content Source: [azure-stack/hci/manage/azure-portal.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/azure-portal.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @arduppal
* Microsoft Alias: **arduppal**

**Comment by VikasPullagura-MSFT** [comment]
@anoobbacker 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@arduppal 
Can you please check and add your comments on this doc update request as applicable.

**Comment by arduppal** [comment]
@VikasPullagura-MSFT and @anoobbacker : Please feel free to get this updated if it has changed. There is some mistake I don't own this doc. Also feel free to take the ownership if you are the right person.

**Comment by alkohli** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. We are currently closing this issue, however if you feel the problem persists, please re-open the issue no later than May 20, 2024 with additional information.
We appreciate your contribution and encourage you to propose changes using public PRs, or submit feedback through our updated control at the top of the page, as we phase out Git Issues for this repo. For more information on our feedback systems, see https://aka.ms/ContentUserFeedback.

**Comment by alkohli** [comment]
A couple of notes here: 
The doc in question applies to only 22H2 clusters. A decision was made to leave this older version article as-is. A new version of Azure Stack HCI, v23H2 is now available. Please use the mainstream TOC to use the relevant articles for 23H2. 

Moreover, no ask was made to keep this Git issue open. Closing this. #please-close.
