### ISSUE TITLE
Source code issue on page "System requirements for Azure Kubernetes Service on Azure Stack HCI and Windows Server/Optional: Create a new service principal"

### ISSUE THREAD

**Issue by frkim** [MicrosoftDocs/azure-stack-docs#2340]
Error on page : 
System requirements for Azure Kubernetes Service on Azure Stack HCI and Windows Server
Optional: Create a new service principal
https://learn.microsoft.com/en-us/azure/aks/hybrid/system-requirements?tabs=allow-table#optional-create-a-new-service-principal

$secret = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sp.Secret))
Write-Host "Application ID: $($sp.ApplicationId)"
Write-Host "App Secret: $secret"

Write-Host "Application ID: $($sp.AppId)"
Write-Host "secret: $($sp.passwordCredentials.secretText)"

**Comment by Naveenommi-MSFT** [comment]
@frkim
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@sethmanheim 
Can you review the query and add your comments.

**Comment by AjayBathini-MSFT** [comment]
@frkim 

It looks like there are two different sets of commands being used to retrieve the application ID and secret for a service principal. The first set of commands is:


$secret = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sp.Secret))
Write-Host "Application ID: $($sp.ApplicationId)"
Write-Host "App Secret: $secret"

The second set of commands is:


Write-Host "Application ID: $($sp.AppId)"
Write-Host "secret: $($sp.passwordCredentials.secretText)"

It's possible that the first set of commands is being used for an older version of the Azure PowerShell module, while the second set of commands is being used for a newer version. In any case, both sets of commands should retrieve the application ID and secret for the service principal.
