### ISSUE TITLE
Issue in https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/aks-edge-how-to-akri-onvif.md

### ISSUE THREAD

**Issue by SeryioGonzalez** [MicrosoftDocs/azure-stack-docs#2352]
The YAML template is wrong. 
app is not properly tabbed under matchLabels in the deployment

**Comment by sethmanheim** [comment]
@SeryioGonzalez Please do not view the technical documentation on GitHub, and please do not share this URL with customers. The correct URL to view this article is https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-how-to-akri-onvif. Thank you.

Also, this is valid YAML according to 2 separate validators I checked with.

**Comment by SaibabaBalapur-MSFT** [comment]
@SeryioGonzalez 
Glad to know you have self-resolved the issue.
