### ISSUE TITLE
issue with ADFS example

### ISSUE THREAD

**Issue by nimeader** [MicrosoftDocs/azure-stack-docs#2355]
https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-identity?view=azs-2206#trigger-automation-to-configure-claims-provider-trust-in-azure-stack-hub

For this section, step 2 should be using 

-CustomADFSFederationMetadataEndpointUri "https://ad01.contoso.com/federationmetadata/2007-06/federationmetadata.xml"

rather than 

-CustomADFSFederationMetadataFileContent $federationMetadataFileContent

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d295c322-0813-e159-e6f8-86f04b759c48
* Version Independent ID: 02b87d3f-125b-d674-b750-79dbaee5e497
* Content: [Integrate AD FS identity with your Azure Stack Hub datacenter - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-identity?view=azs-2206#setting-up-ad-fs-integration-by-downloading-federation-metadata)
* Content Source: [azure-stack/operator/azure-stack-integrate-identity.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-integrate-identity.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by nimeader** [comment]
issue raised by leyasa

**Comment by sethmanheim** [comment]
Thanks @nimeader, I will make sure this gets updated today.

**Comment by sethmanheim** [comment]
@nimeader Does this change apply to both instances in the article? The same command appears twice.

**Comment by nimeader** [comment]
No, only the first mention after the anchor I mentioned in the request. The second instance is accurate (and it actually defines the variable before that instance)

-Nick

**Comment by sethmanheim** [comment]
Right, the same anchor appears twice in the article (it probably shouldn't), hence my question. Thanks!

**Comment by nimeader** [comment]
Yeah, the second is a ###-1 I think? We want the one without the -1

-Nick
