### ISSUE TITLE
Wrong tool name in the Failover cluster maintenance procedures section

### ISSUE THREAD

**Issue by ignis-silver** [MicrosoftDocs/azure-stack-docs#2365]
[Enter feedback here]

Hello, there is an error in point no 1 in the **Pause and drain the server** section. There is no **Compute -> Servers** but it's a **Cluster resources -> Servers** in the left panel menu (tools) in the Windows Admin Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84da7560-2046-72af-cc0b-8922d47f23a0
* Version Independent ID: 3c23a71d-724d-06ef-6472-10cdb1a63e7d
* Content: [Failover cluster maintenance procedures for Azure Stack HCI and Windows Server - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/maintain-servers)
* Content Source: [azure-stack/hci/manage/maintain-servers.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/maintain-servers.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by YashikaTyagii** [comment]
@ignis-silver 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@ignis-silver 
I'm going to assign this to the document author so they can take a look at it accordingly.

@JasonGerend 
Please review it.
