### ISSUE TITLE
Overlapping subnet error while deploying

### ISSUE THREAD

**Issue by nekdima** [MicrosoftDocs/azure-stack-docs#2369]
Team,

While deploying AKS EE I've encountered a network error (see screenshot below).
Deployment is being done on an Azure VM using nested virtualisation: Azure VM with Windows Server runs Hyper-V which runs Windows 11 VM which again runs Hyper-V to leverage AKS EE.

 - All potential subnets '192.168.0.0' to '192.168.255.0' overlap with existing subnets of the local interfaces. (AksEdge.psm1:4121)

![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/38444705/80a61d69-e30b-4957-99d8-7944a45c0877)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59f9fa6b-d817-7c4a-d13e-a3ce79ea6796
* Version Independent ID: fe06a4d5-5bd1-bb2e-4f8b-fefcfca7a07d
* Content: [Quickstart for AKS Edge Essentials - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-quickstart)
* Content Source: [AKS-Hybrid/aks-edge-quickstart.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/aks-edge-quickstart.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @rcheeran
* Microsoft Alias: **rcheeran**

**Comment by AjayBathini-MSFT** [comment]
Fixed
