### ISSUE TITLE
new feature note uses wrong build version since the build was renamed

### ISSUE THREAD

**Issue by nimeader** [MicrosoftDocs/azure-stack-docs#2371]
[virtual-machine-view](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-compute-overview?view=azs-2206#virtual-machine-view)

this entry should read:

Virtual machine view
Starting with the 2301 release of Azure Stack Hub, a new view was added for operators in the Azure Stack Hub admin portal that shows virtual machines across all user subscriptions. This view displays the following information:

rather than 2210 (the original planned version of 2301)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84e5da33-ad7e-ff89-afb6-36d2774da19f
* Version Independent ID: 4197c1d7-0674-66da-8bd0-3db55c4d99f1
* Content: [Introduction to Azure Stack Hub VMs - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-compute-overview?view=azs-2206)
* Content Source: [azure-stack/user/azure-stack-compute-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-compute-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by AjayBathini-MSFT** [comment]
@nimeader 
Thanks for your feedback! We will investigate and update as appropriate.
