### ISSUE TITLE
"Note" for $adminpass is not correct. It should be local Local Administrator password of ASDK host, not the CloudAdmin default password. 

### ISSUE THREAD

**Issue by xizhuang** [MicrosoftDocs/azure-stack-docs#2374]
In this article, it says below in the "Note"

"The $adminpass on the script below must be the password of the default "CloudAdmin" user from the production environment when the backup was taken."

The $adminpass should be the Local Administrator password of ASDK host, not the CloudAdmin default password. 

If we use cloud admin password, it will report error "The Administrator password provided must match the Administrator password of the host"

The reason is that, in DeploySingleNoddeCommon.ps1 line 533 , there is below command
 
$credentialSuccess = Invoke-Command -ComputerName 'LocalHost' -Credential $builtInAdminCredential -ErrorAction 'SilentlyContinue' { $true } 
 
This command is to test that the Administrator password matches host administrator password. $builtInAdminCredential comes from below command 
 
$builtInAdminCredential = (New-Object PSCredential -ArgumentList 'Administrator', $AdminPassword) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 880d3c99-62f9-e909-e2dc-dfa2ff0cb723
* Version Independent ID: d9adc6a8-912e-f789-2833-8610a63c6a4c
* Content: [Use the ASDK to validate an Azure Stack backup - Azure Stack Development Kit (ASDK)](https://learn.microsoft.com/en-us/azure-stack/asdk/asdk-validate-backup?view=azs-2206)
* Content Source: [azure-stack/asdk/asdk-validate-backup.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/asdk/asdk-validate-backup.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub-asdk**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@xizhuang 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by xizhuang** [comment]
Hi, @sethmanheim , can I have an update on this please? Thank you!

**Comment by sethmanheim** [comment]
#please-close

**Comment by xizhuang** [comment]
Hi @Seth ***@***.***>, Thanks for your update!

Regards,
Xiaoyu
