### ISSUE TITLE
Missing variable definition

### ISSUE THREAD

**Issue by Trace1337** [MicrosoftDocs/azure-stack-docs#2375]
The variable $YourPrivilegedEndpoint is used 4 different times on the page in various code snippets but never defined for the customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19119cef-de12-31e5-d0b6-b95f2985f57e
* Version Independent ID: 5a7921c1-ac2e-6de8-0e8d-de9f04e457a6
* Content: [Register Azure Stack Hub with Azure - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-registration?view=azs-2301&tabs=az1%2Caz2%2Caz3%2Caz4&pivots=state-disconnected#verify-azure-stack-hub-registration)
* Content Source: [azure-stack/operator/azure-stack-registration.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-registration.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@Trace1337 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@Trace1337 Thank you for reaching out and very sorry for the delay. I have added a declaration of this variable in the appropriate spots: `$YourPrivilegedEndpoint = "<privileged_endpoint_computer_name>"' Thank you again! #please-close
