### ISSUE TITLE
HCI Arc VM ARM/Bicep Template

### ISSUE THREAD

**Issue by mbrat2005** [MicrosoftDocs/azure-stack-docs#2385]
Hi, I have customers looking for ARM and Bicep templates for VMs, so I started on a couple quickstart templates which might be good to include here or in a related doc. 

**Create Windows VM from existing Image**: https://github.com/mbrat2005/azure-quickstart-templates/tree/hci-vm/quickstarts/microsoft.azurestackhci/vm-simple-windows
**Create Image from Marketplace**: https://github.com/mbrat2005/azure-quickstart-templates/tree/hci-image/quickstarts/microsoft.azurestackhci/image-from-azure-marketplace
**Create a VM at a specific storage container**: https://github.com/mbrat2005/azure-quickstart-templates/tree/hci-vm-custom-path2/quickstarts/microsoft.azurestackhci/vm-windows-storage-container

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae893d86-6ef4-e879-430c-651b39e5f36c
* Version Independent ID: 5bc4688e-f540-3de7-fd20-81732129aa6d
* Content: [Create Arc virtual machines on Azure Stack HCI (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/manage-virtual-machines-in-azure-portal?tabs=azurecli)
* Content Source: [azure-stack/hci/manage/manage-virtual-machines-in-azure-portal.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/manage-virtual-machines-in-azure-portal.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ksurjan
* Microsoft Alias: **ksurjan**

**Comment by AjayBathini-MSFT** [comment]
@mbrat2005
Thanks for your contribution. Please add your ideas in below link, so our production team can review it and update the same.
[Ideas · Community (azure.com)](https://feedback.azure.com/d365community)
