### ISSUE TITLE
Reset the password expiration policy

### ISSUE THREAD

**Issue by Werner-MOC** [MicrosoftDocs/azure-stack-docs#24]
The whole topic is not necessary anymore, it defaults now (1901) to 679 days

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be299a6e-e10b-ae65-a59d-e5730e33a54d
* Version Independent ID: 9dc0a609-b728-7198-a2c0-8408c6ec91c6
* Content: [Post deployment configurations for the Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure/azure-stack/asdk/asdk-post-deploy)
* Content Source: [articles/azure-stack/asdk/asdk-post-deploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-post-deploy.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by mattbriggs** [comment]
@Werner-MOC  Thanks for your input. I've removed the section from the topic. #please-close

**Comment by mattbriggs** [comment]
#please-close
