### ISSUE TITLE
Need to export and trust Azure Stack root cert with the integrated systems

### ISSUE THREAD

**Issue by Lihailian** [MicrosoftDocs/azure-stack-docs#240]
In our document(https://docs.microsoft.com/en-gb/azure-stack/user/azure-stack-version-profiles-azurecli2#trust-the-azure-stack-ca-root-certificate-2), it states:
If you are using the ASDK, you will need to trust the CA root certificate on your remote machine. You will not need to do this with the integrated systems.
 
However, based on my test, we still need to export and trust Azure Stack certificate, otherwise, you will get error like below when trying to register the az cli.
PS C:\&gt; az cloud register -n AzureStackUser --endpoint-resource-manager "https://adminmanagement.azss01.cloud.wipro.com/" --suffix-storage-endpoint "azss01.cloud.wipro.com" --suffix-keyvault-dns ".vault.azss01.cloud.wipro.com" --endpoint-vm-image-alias-doc "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/arm-compute/quickstart-templates/aliases.json"
az : ERROR: Unable to get endpoints from the cloud.
At line:1 char:1
+ az cloud register -n AzureStackUser --endpoint-resource-manager "http ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Unable t...from the cloud.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='adminmanagement.azss01.cloud.wipro.com', port=443): Max retries exceeded with url: 
//metadata/endpoints?api-version=2015-01-01 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
 
PS C:\&gt; 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583c4bab-c16a-a723-04ac-b3265d9e8269
* Version Independent ID: e6ecb0ee-2303-a7ed-9fca-767e3d3bfe86
* Content: [Connect to Azure Stack with CLI](https://docs.microsoft.com/en-gb/azure-stack/user/azure-stack-version-profiles-azurecli2#trust-the-azure-stack-ca-root-certificate-2)
* Content Source: [azure-stack/user/azure-stack-version-profiles-azurecli2.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-version-profiles-azurecli2.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@Lihailian Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@mattbriggs Sorry this is so old, but I'm not sure if this is a doc update that's needed.
