### ISSUE TITLE
Some details missing

### ISSUE THREAD

**Issue by timmmayyy** [MicrosoftDocs/azure-stack-docs#2406]
Some of the steps in this document show the command to use and others do not. Example - step 10 of the offline update section.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64880e71-5de3-4b72-bcbf-1eb6d9dbfced
* Version Independent ID: db618f0c-c803-7fc0-91e9-2b77a6543ebf
* Content: [Update Azure Stack HCI clusters - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/update-cluster#perform-a-fast-offline-update-of-all-servers-in-a-cluster)
* Content Source: [azure-stack/hci/manage/update-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/update-cluster.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Naveenommi-MSFT** [comment]
@timmmayyy 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@JasonGerend
Can you please check and add your comments on this doc update request as applicable.

**Comment by SaibabaBalapur-MSFT** [comment]
@timmmayyy 
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by sethmanheim** [comment]
@timmmayyy As we are moving to a new feedback system, we have opened corresponding work items and are tracking all open issues in our internal database.  We are closing all public issues, but as mentioned above, there are other ways to provide feedback. Thank you again for reaching out! #please-close
