### ISSUE TITLE
Accessing Linux VM to check interfaces

### ISSUE THREAD

**Issue by kvietmeier** [MicrosoftDocs/azure-stack-docs#2410]
[Enter feedback here]

In the check interfaces section you just give a standard ifconfig command - but no instructions on how to get access to the Linux VM to run the commands.

Also - "ifconfig" is deprecated - "ip addr" is preferred.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f685932-3c65-9b92-566d-dfbe2eac49f6
* Version Independent ID: cc978763-2359-334f-a4dd-1c8c210ed67f
* Content: [Configure multiple NICs for AKS Edge Essentials - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-multi-nic)
* Content Source: [AKS-Hybrid/aks-edge-howto-multi-nic.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/aks-edge-howto-multi-nic.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @fcabrera
* Microsoft Alias: **fcabrera**

**Comment by SaibabaBalapur-MSFT** [comment]
@kvietmeier 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@kvietmeier 
To access a Linux virtual machine (VM) and run commands, you can typically use a secure shell (SSH) client. Here's a general overview of the steps to access a Linux VM in Azure:

Obtain the public IP address or DNS name of the Linux VM you want to connect to.
Ensure that your local machine has an SSH client installed. If you're using Windows, you can install an SSH client like PuTTY or use the built-in Windows Subsystem for Linux (WSL) to access the VM.
Open the SSH client and provide the IP address or DNS name of the Linux VM.
If necessary, provide the credentials (username and password or SSH key) to authenticate yourself and establish an SSH session with the Linux VM.
Once connected, you can run commands in the terminal of the SSH client to interact with the Linux VM.
Please note that the specific steps may vary depending on your operating system and SSH client. The Azure documentation you referenced provides guidance on creating and configuring an Azure Kubernetes Service (AKS) cluster with multiple network interfaces, but it assumes a basic understanding of how to access a Linux VM.

If you need more specific instructions or encounter any issues, please let me know, and I'll be happy to assist you further.

**Comment by AjayBathini-MSFT** [comment]
@kvietmeier 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/12803

**Comment by kvietmeier** [comment]
@AjayBathini-MSFT

Your comment above is correct - accessing a VM via SSH is well documented. But that assumes sshd is configured and port 22 open.  In the context of AKS-EE in particular, direct access to the Azure Linux instance is restricted to using the AKS-EE PowerShell commands (or not well documented).

When using AKS-EE the documented way to run commands in the Linux VM is:
```
Invoke-AksEdgeNodeCommand -NodeType "Linux" -command "sudo ip addr"
```

If there are other ways to access the VM they should be documented.

Also - the VMs don't show up in HyperV manager so you can't access them via the console.

Note that this does make troubleshooting/fixing possibly simple issues difficult to the point of it usually being easier to just blow everything away and restart.

**Comment by AjayBathini-MSFT** [comment]
@kvietmeier 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by AjayBathini-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@AjayBathini-MSFT It looks like you opened a PR to address this issue? Not sure what's expected to happen here...

**Comment by AjayBathini-MSFT** [comment]
@kvietmeier 
Thanks for your contribution. Please add your ideas in below link, so our production team can review it and update the same.
[Ideas · Community (azure.com)](https://feedback.azure.com/d365community)

**Comment by kvietmeier** [comment]
Assuming the VM ids actually running you can us hcsdiag to SSH to the VM for an interactive console. I had to do some digging to find this.
https://www.thomasmaurer.ch/2020/06/hcsdiag-exe-hyper-v-host-compute-service-diagnostics-tool/

```
	PS C:\Users\karlv\OneDrive\Documents> hcsdiag list
	aa817488-eb7f-11ed-9738-54b2030b89d9
	    VM,                         Running, AA817488-EB7F-11ED-9738-54B2030B89D9, wssdagent

```

Now connect for an interactive console session - well not exactly a console but better than one off commands using he PowerShell commandlets.
```
	PS C:\Users\karlv\OneDrive\Documents> hcsdiag console AA817488-EB7F-11ED-9738-54B2030B89D9
	sh-5.1# 
	sh-5.1# uname -a
	Linux skullcanyon-ledge 5.15.102.1-1.cm2 #1 SMP Tue Mar 21 04:10:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
	sh-5.1# cat /etc/os-release
	NAME="Common Base Linux Mariner"
	VERSION="2.0.20230321"
	ID=mariner
	VERSION_ID="2.0"
	PRETTY_NAME="CBL-Mariner/Linux"
	ANSI_COLOR="1;34"
	HOME_URL="https://aka.ms/cbl-mariner"
	BUG_REPORT_URL="https://aka.ms/cbl-mariner"
	SUPPORT_URL="https://aka.ms/cbl-mariner"
```

If the VM isn't running you can use "Start-AksEdgeNode -NodeType Linux" to start it first.

Still doesn't provide a serial console which I understand is a problem for some 3rd party utilities.

The problem with "Invoke-AksEdgeNodeCommand" is that if the Kubernetes cluster isn't running you will get a bunch exceptions and complaints about the cluster not being available before the Linux command is finally run.  Why check for the K8S cluster if you are just running a Linux command?
