### ISSUE TITLE
Please define "HUD" acronym.

### ISSUE THREAD

**Issue by dbuchho** [MicrosoftDocs/azure-stack-docs#2419]
An "overview" page should make defining acronyms a priority.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1a48fd4-dee8-97c4-7069-ae2f003046bb
* Version Independent ID: 86c89fa8-9178-dca1-2646-d41e96bae3ee
* Content: [Network HUD overview - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/network-hud-overview)
* Content Source: [azure-stack/hci/concepts/network-hud-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/network-hud-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @dcuomo
* Microsoft Alias: **dacuo**

**Comment by dbuchho** [comment]
An "overview" page should make defining acronyms a priority.

**Comment by VikasPullagura-MSFT** [comment]
@dbuchho 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@dcuomo 
Can you please check and add your comments on this doc update request as applicable.
