### ISSUE TITLE
Monitor Agent support for Azure Stack HCI virtual machines

### ISSUE THREAD

**Issue by jvta** [MicrosoftDocs/azure-stack-docs#2423]
Azure Stack HCI virtual machines need to be monitored same as Azure VMs or Arc based Hybrid Compute VMs - how can Azure Monitor Agent or Microsoft Monitor Agent currently be managed on HCI VMs whilst documentation states that only the Custom Script Extension is supported as an Extension to this resource type? 
Will there be support for Azure based monitoring agents added to HCI VMs forthcoming? Installing and managing them within the OS layer is not best practice nor manageable at scale.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac3a4a66-22c9-91d2-909c-800d422785cc
* Version Independent ID: 5193eb71-8d71-229f-1ebf-c70f1c5c0075
* Content: [Azure Arc VM management FAQs (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/faqs-arc-enabled-vms)
* Content Source: [azure-stack/hci/manage/faqs-arc-enabled-vms.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/faqs-arc-enabled-vms.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by RamanathanChinnappan-MSFT** [comment]
@jvta 

Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @
Currently, Azure Monitor Agent or Microsoft Monitor Agent is not supported as an extension on Azure Stack HCI virtual machines. As you mentioned, only the Custom Script Extension is supported as an extension to this resource type. However, you can still monitor your Azure Stack HCI virtual machines using Azure Monitor by installing the Azure Monitor Agent or Microsoft Monitor Agent within the OS layer of the virtual machine.

While this is not the recommended approach, it is still possible to install and manage the agents at scale using tools such as PowerShell Desired State Configuration (DSC) or Configuration Manager.

As for future support for Azure-based monitoring agents on HCI VMs, I do not have any information on that at this time. However, I recommend keeping an eye on the Azure Stack HCI documentation and Azure Monitor documentation for any updates or announcements regarding this.

**Comment by ManoharLakkoju-MSFT** [comment]
@jvta 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
