### ISSUE TITLE
It is not correct, I have the last version of Visual Studio 2022, and I cannot find any of your options

### ISSUE THREAD

**Issue by itsoftwaretsl** [MicrosoftDocs/azure-stack-docs#2446]
It is not correct, I have the last version of Visual Studio 2022, and I cannot find any of your options

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc1af34-ba5b-5aed-4270-7734c4bf3960
* Version Independent ID: 49b45f6c-5c71-af49-3e6a-1bc88b8947bc
* Content: [Install Visual Studio and connect to Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-install-visual-studio?view=azs-2301)
* Content Source: [azure-stack/user/azure-stack-install-visual-studio.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-install-visual-studio.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by ManoharLakkoju-MSFT** [comment]
@itsoftwaretsl 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
Hi @itsoftwaretsl 
The link you provided is about installing Visual Studio for Azure Stack, which is a different product than Visual Studio 2022. If you are looking for information on how to use Azure services with Visual Studio 2022, you can refer to the Azure OpenAI Service documentation.
https://learn.microsoft.com/en-us/azure/stream-analytics/vs-code-intellisense

**Comment by sethmanheim** [comment]
@itsoftwaretsl Thank you for reporting this. The article is written for Visual Studio 2019, and I am looking into whether Visual Studio 2022 is supported by Azure Stack in this scenario. If so I will be sure to update the article with new screen shots. I'll get back with updated information ASAP.

**Comment by sethmanheim** [comment]
Sorry for the delay on this. I am adding the following note to the article:

Note that while Azure Stack Hub supports both Visual Studio 2019 and 2022, Cloud Explorer has been deprecated from Visual Studio 2022. Although both Visual Studio 2019 and 2022 work if you're using Azure AD, if you are using AD FS with Azure Stack Hub (as described in the next section), you must use Visual Studio 2019 or earlier.
