### ISSUE TITLE
Parameter -AsHciAzureStackLCMUserCredential has been renamed to -AsHciDeploymentUserCredential

### ISSUE THREAD

**Issue by davyhoyle** [MicrosoftDocs/azure-stack-docs#2453]
The documented parameter -AsHciAzureStackLCMUserCredential has been renamed to -AsHciDeploymentUserCredential and this document needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd5a83a8-3d61-090c-68f9-002b03048ef9
* Version Independent ID: 5eb2d3d1-d12e-9f7f-fa2f-4c2d54869388
* Content: [Prepare Active Directory for new Azure Stack HCI deployments (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-tool-active-directory)
* Content Source: [azure-stack/hci/deploy/deployment-tool-active-directory.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-tool-active-directory.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @dansisson
* Microsoft Alias: **v-dansisson**

**Comment by Naveenommi-MSFT** [comment]
@davyhoyle 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@davyhoyle 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
