### ISSUE TITLE
The Signin Form or Download link Seems Broken- Azure Stack HCI OS 22H2- https://azure.microsoft.com/products/azure-stack/hci/hci-download/

### ISSUE THREAD

**Issue by Bhaskarg4455** [MicrosoftDocs/azure-stack-docs#2461]
The Signin Form or Download link Seems Broken- Azure Stack HCI OS 22H2- https://azure.microsoft.com/products/azure-stack/hci/hci-download/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15e6eafc-3472-f575-c388-95e05ec34f3c
* Version Independent ID: 23708372-a062-e458-e3c5-dc8922ee489c
* Content: [Install Azure Stack HCI, version 22H2 operating system (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-tool-install-os)
* Content Source: [azure-stack/hci/deploy/deployment-tool-install-os.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-tool-install-os.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @dansisson
* Microsoft Alias: **v-dansisson**

**Comment by YashikaTyagii** [comment]
@Bhaskarg4455 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@Bhaskarg4455 
Can you provide the screenshot where exactly the link seems broken in the doc. So we can be able to work on it
