### ISSUE TITLE
VLAN ID for Static IP only

### ISSUE THREAD

**Issue by DarrylvanderPeijl** [MicrosoftDocs/azure-stack-docs#2470]
The documentation states:

"For static IP only, you can specify the following optional parameters: **VLAN ID**"

We also need the ability to specify the VLAN ID for Dynamic / DHCP scenarios. VLAN IDs are not received from the DHCP server, the VM needs to be in the right VLAN to get an IP address from the DHCP server.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4801619b-bc5d-1091-0f03-128acbd7e792
* Version Independent ID: ec4d09c1-3d99-7077-90c9-6e6352877183
* Content: [Create virtual networks for Azure Stack HCI cluster (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/create-virtual-networks)
* Content Source: [azure-stack/hci/manage/create-virtual-networks.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/create-virtual-networks.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by YashikaTyagii** [comment]
@DarrylvanderPeijl 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@DarrylvanderPeijl 
According to the documentation you provided, the option to specify a VLAN ID is mentioned specifically for static IP scenarios. It doesn't mention the ability to specify a VLAN ID for dynamic/DHCP scenarios. In dynamic/DHCP scenarios, the VLAN ID is typically assigned by the network infrastructure or DHCP server.

If you require the ability to assign a specific VLAN ID for dynamic/DHCP scenarios in Azure Stack HCI, you may need to explore alternative configurations or customizations outside the scope of the provided documentation. It's possible that additional configuration steps or modifications to the network infrastructure might be required to achieve your desired VLAN configuration. In such cases, it's recommended to consult with the Azure Stack HCI documentation.

I'd recommend working closer with our [Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.

**Comment by DarrylvanderPeijl** [comment]
@AjayBathini-MSFT 

The VLAN ID is never assigned by the network infrastructure or DHCP server, that's the point.
VLANs are configured on virtual machine/virtual NIC level inside Hyper-V, that's not something the DHCP server can influence. I expect this to be a documentation issue and also expect that setting the VLAN for Dynamic / DHCP scenarios works as expected from the az cli. Please take this up internally.

**Comment by AjayBathini-MSFT** [comment]
@DarrylvanderPeijl 
I've assigned this issue to the author who will investigate and update as appropriate.

@alkohli 
Can you please check and add your comments on this doc update request as applicable.

**Comment by alkohli** [comment]
@DarrylvanderPeijl The original issue was filed for 22H2 Arc VM management docs. Those docs have been deprecated since. New docs have been created in support of v23H2. The current logical network doc here: https://learn.microsoft.com/en-us/azure-stack/hci/manage/create-logical-networks?tabs=azurecli#create-a-dhcp-logical-network-via-cli talks about VLAN ID for both static as well as DHCP. Hopefully that answers your query. 

Thanks again for your question. I will close this issue.

#please-close
