### ISSUE TITLE
Videos that are linked in the page are not working

### ISSUE THREAD

**Issue by mailhatt** [MicrosoftDocs/azure-stack-docs#2491]
As this is relatively "new" videos are helpful to ensure setup is the way it should be 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1a48fd4-dee8-97c4-7069-ae2f003046bb
* Version Independent ID: 86c89fa8-9178-dca1-2646-d41e96bae3ee
* Content: [Network HUD overview - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/network-hud-overview)
* Content Source: [azure-stack/hci/concepts/network-hud-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/network-hud-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @dcuomo
* Microsoft Alias: **dacuo**

**Comment by VikasPullagura-MSFT** [comment]
@mailhatt 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@dcuomo 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@mailhatt Thank you for reporting this -- I've changed the embedded videos to links, so you should now be able to access the videos. #pleasae-close

**Comment by mailhatt** [comment]
@sethmanheim - Just had a look and its not working. Screenshot attached. 

![Network HUD overview - Azure Stack HCI](https://github.com/MicrosoftDocs/azure-stack-docs/assets/103308133/7114bee6-b0d3-477f-b082-620fb6eac34e)

**Comment by sethmanheim** [comment]
Please try again after 10 AM Pacific time today.

**Comment by mailhatt** [comment]
Just looked and it working - thanks!
