### ISSUE TITLE
Is the core ratio in table correct?

### ISSUE THREAD

**Issue by Mahesh-MSFT** [MicrosoftDocs/azure-stack-docs#25]
Core ratio column in the table above displays the virtual to physical core ratio. It displays ratio as 4.3 for 1st row, 4:1 for 2nd row and 3:1 for 3rd row.

When I calculate the ratio between virtual to physical ratio, it comes about 27:28 for 1st row and 18:7 for 2nd and 3rd row.

My calculation is based on following table.

  | Memory | CPU Cores | Number of servers | Total Physical   Cores | D2 Tenant VMs1 | Tenant VM Virtual   Cores | Core ratio (   Virtual: Physical)
-- | -- | -- | -- | -- | -- | -- | --
Example 1 | 256 GB | 28 | 4 | 112 | 54 | 108 | 27:28
Example 2 | 512 GB | 28 | 4 | 112 | 144 | 288 | 18:7
Example 3 | 384 GB | 28 | 12 | 336 | 432 | 864 | 18:7

Can you please take a look and correct it accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a892fa3c-5403-6cbe-d9dc-23839807ec5b
* Version Independent ID: e2eb938a-1a20-d94b-63d6-c8b66f1a8dad
* Content: [Capacity planning for Azure Stack](https://docs.microsoft.com/en-us/azure/azure-stack/capacity-planning)
* Content Source: [articles/azure-stack/capacity-planning.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/capacity-planning.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by niheinba** [comment]
Is there any update on this question? I too am curious.

**Comment by jeffgilb** [comment]
I thought this was already fixed? I'm also no longer on the docs team so this will need to be reassigned if not.

**Comment by jeffgilb** [comment]
#please-close

**Comment by mattbriggs** [comment]
@Mahesh-MSFT Looks like this content has changed. Ratio guidance has been changed to:

Azure Stack doesn't over-commit memory. However, an over-commit of the number of physical cores is allowed. Since placement algorithms don't look at the existing virtual to physical core over-provisioning ratio as a factor, each host could have a different ratio. As Microsoft, we do not provide guidance on the physical-to-virtual core ratio because of the variation in workloads and service level requirements.

#please-close

**Comment by Mahesh-MSFT** [comment]
Closing the issue as the table shown earlier is no longer available in updated documentation.

**Comment by Mahesh-MSFT** [comment]
@mattbriggs @jeffgilb Closing the issue as the table shown earlier is no longer available in updated documentation.
