### ISSUE TITLE
The link to download ASDK seems wrong 

### ISSUE THREAD

**Issue by xizhuang** [MicrosoftDocs/azure-stack-docs#2501]
The link to download ASDK which mentioned in the article doesn't work. In that page, we can't find anywhere to download ASDK or provide our details. 

2. [Go to the Get Started page](https://azure.microsoft.com/overview/azure-stack/try/?v=try) where you can download the ASDK, provide your details, and then click Submit.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 289cb46f-b173-0ec0-ace1-6e038f82c553
* Version Independent ID: 8f72a4e5-fba9-6631-1924-3b649446bf18
* Content: [Download and extract the ASDK - Azure Stack Development Kit (ASDK)](https://learn.microsoft.com/en-us/azure-stack/asdk/asdk-download?view=azs-2301)
* Content Source: [azure-stack/asdk/asdk-download.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/asdk/asdk-download.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub-asdk**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@xizhuang We apologize for the inconvenience, we are investigating this problem. In the meantime, you can download the ASDK from here: https://azure.microsoft.com/contact/azure-stack-dev-kit/thank-you/

**Comment by sethmanheim** [comment]
#please-close

**Comment by AjayBathini-MSFT** [comment]
Resolved
