### ISSUE TITLE
Image Download failing with error "Could not convert the returned interface to MOCGalleryImage: Invalid Input

### ISSUE THREAD

**Issue by philipp-mair-acp** [MicrosoftDocs/azure-stack-docs#2507]
Hello,

we followed the guide and tried do download a VHDX file using the CLI method. No matter what VHD we select, we always get the error "Could not convert the returned interface to MOCGalleryImage: Invalid Input".
The image download starts and stops at about 30 percent.

We tried the same on two different HCI deployments and get the same result. Do you have any idea to resove this issue?

Regards,
Philipp

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84c81c1a-ea0a-16ff-fda5-0063aa4e5398
* Version Independent ID: 02b7c8a5-f187-c5ef-2ecc-c0d2e9cf2fc9
* Content: [Create Azure Stack HCI VM from images in Azure Storage account (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/virtual-machine-image-storage-account?tabs=azurecli)
* Content Source: [azure-stack/hci/manage/virtual-machine-image-storage-account.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/virtual-machine-image-storage-account.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by SaibabaBalapur-MSFT** [comment]
@philipp-mair-acp 
Since this issue isn't directly related to improving our docs, and to gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).
