### ISSUE TITLE
No key file got generated - convert to pfx fails

### ISSUE THREAD

**Issue by habeebth7** [MicrosoftDocs/azure-stack-docs#2510]
[Enter feedback here]

https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-get-pki-certs?view=azs-2301&tabs=add-cn&pivots=csr-type-renewal 

The CSR generation script does not create the key file. At the convert-to-pfx stage, it fails saying no key file found.

PS C:\Windows\system32> $pfxPassword = Read-Host -AsSecureString -Prompt "PFX Password"
PFX Password: *************
PS C:\Windows\system32> $ExportPath = "C:\Users\h.thekkar\Documents\AzureStackCSR\pfx"
PS C:\Windows\system32> ConvertTo-AzsPFX -Path $Path -pfxPassword $pfxPassword -ExportPath $ExportPath
ConvertTo-AzsPFX v1.2100.2308.133 started.

Stage 1: Scanning Certificates
        Path: C:\Users\h.thekkar\Documents\AzureStackCSR\CER Filter: CER Certificate count: 11
        adminmanagement_central01_azurestack_itc_sa.cer
        adminportal_central01_azurestack_itc_sa.cer
        management_central01_azurestack_itc_sa.cer
        portal_central01_azurestack_itc_sa.cer
        star_adminhosting_central01_azurestack_itc_sa.cer
        star_adminvault_central01_azurestack_itc_sa.cer
        star_blob_central01_azurestack_itc_sa.cer
        star_hosting_central01_azurestack_itc_sa.cer
        star_queue_central01_azurestack_itc_sa.cer
        star_table_central01_azurestack_itc_sa.cer
        star_vault_central01_azurestack_itc_sa.cer

Detected ExternalFQDN: central01.azurestack.itc.sa

Stage 2: Exporting Certificates

WARNING: Following certificates will be discarded:

FileName                                          ErrorMessage
--------                                          ------------
adminmanagement_central01_azurestack_itc_sa.cer   No Private Key
adminportal_central01_azurestack_itc_sa.cer       No Private Key
management_central01_azurestack_itc_sa.cer        No Private Key
portal_central01_azurestack_itc_sa.cer            No Private Key
star_adminhosting_central01_azurestack_itc_sa.cer No Private Key
star_adminvault_central01_azurestack_itc_sa.cer   No Private Key
star_blob_central01_azurestack_itc_sa.cer         No Private Key
star_hosting_central01_azurestack_itc_sa.cer      No Private Key
star_queue_central01_azurestack_itc_sa.cer        No Private Key
star_table_central01_azurestack_itc_sa.cer        No Private Key
star_vault_central01_azurestack_itc_sa.cer        No Private Key

Certificate validation was skipped.

Log location (contains PII): C:\Users\SAH~1.THE\AppData\Local\Temp\AzsReadinessChecker\AzsReadinessChecker.log
ConvertTo-AzsPFX Completed
PS C:\Windows\system32>

Log file:

[7/27/2023 10:33:08 AM] [Error] [PartialValidation] Certificate [CN=*.vault.central01.azurestack.itc.sa] has a problem with its private key. Error: The certificate does not contain a private key.
[7/27/2023 10:33:08 AM] [Error] [ConvertTo-AzsPFX] Unable to export certificate . Error: No Private Key
[7/27/2023 10:33:08 AM] [Warning] [ConvertTo-AzsPFX] WARNING: Following certificates will be discarded:
---

where should we generate the key file in this script? 
Should we generate CSR with normal method and ignore this procedure? 

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6faad96b-2671-fa69-2897-eb33eaaa7a71
* Version Independent ID: 0d02649c-e207-069d-c062-dc4b824fdd26
* Content: [Generate certificate signing requests for Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-get-pki-certs?pivots=csr-type-new-deployment&view=azs-2301&tabs=omit-cn)
* Content Source: [azure-stack/operator/azure-stack-get-pki-certs.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-get-pki-certs.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@habeebth7 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by habeebth7** [comment]
my SSL is expiring today? Shall i recreate new CSR with manual steps including key file?

**Comment by habeebth7** [comment]
I could fix this by regenerating the csr... Do not know what was the issue earlier. 
Thanks anyway..

**Comment by sethmanheim** [comment]
@habeebth7 Very sorry for the delay here. #please-close
