### ISSUE TITLE
No "AzureStack" endpoint available

### ISSUE THREAD

**Issue by robinmanuelthiel** [MicrosoftDocs/azure-stack-docs#252]
The "Add Azure Resource Manager service connection" does not seem to offer "AzureStack" as an environment anymore. I am pretty sure to remember that I have seen it there once. Did the process change?

![image](https://user-images.githubusercontent.com/5874465/61667868-ff989000-ac8f-11e9-8681-a314db855e12.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e54ed0-e139-1569-adc8-1833de468eb9
* Version Independent ID: 0b03d258-e1ee-e59b-997f-e9096c6f53e2
* Content: [Deploy apps to Azure and Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-pipeline#create-an-azure-stack-endpoint)
* Content Source: [azure-stack/user/azure-stack-solution-pipeline.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-solution-pipeline.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by TravisCragg-MSFT** [comment]
@robinmanuelthiel Thanks for the feedback. We are actively investigating and will get back to you soon.

**Comment by TravisCragg-MSFT** [comment]
@robinmanuelthiel I am not sure what the process used to be, but this doc has been changed several times In the past few months. I would follow the outlined process to see if you have any issues.

**Comment by TravisCragg-MSFT** [comment]
@robinmanuelthiel We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
