### ISSUE TITLE
Mistakes in documentation

### ISSUE THREAD

**Issue by Dionisas** [MicrosoftDocs/azure-stack-docs#2522]
[Enter feedback here]
Documentation has couple writing mistakes. 
In script last } is missing. 
Incorrect port number. Instead of 3389 in one place it is written 2289 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eae3b395-faa5-a31f-6442-75fcf8439da3
* Version Independent ID: 34ea4455-36ad-6f22-5813-17b7eafb6024
* Content: [App Service on Azure Stack Hub 2302 release notes - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/app-service-release-notes-2302?view=azs-2301)
* Content Source: [azure-stack/operator/app-service-release-notes-2302.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/app-service-release-notes-2302.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @apwestgarth
* Microsoft Alias: **anwestg**

**Comment by Naveenommi-MSFT** [comment]
@Dionisas 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@Dionisas 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.

**Comment by Dionisas** [comment]
I still see same issue in the documentation.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @Dionisas Thanks for taking your time, we have already raised change request to author, Once Document author approval, the document changes will be gone alive soon.
