### ISSUE TITLE
Ambiguous language regarding CIS/DISA/STIG requirements

### ISSUE THREAD

**Issue by dkirby-ms** [MicrosoftDocs/azure-stack-docs#2531]
What exactly is meant by "closely meet" in this sentence from the page?

`"Enables you to closely meet Center for Internet Security (CIS) benchmark and Defense Information System Agency (DISA) Security Technical Implementation Guide (STIG) requirements for the operating system (OS) and the Microsoft recommended security baseline."`

What is the delta here between almost meeting the standard and actually meeting it? We should be explicit with what the baseline cannot meet here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4898389f-c8f6-a8f4-b386-d2491051eedd
* Version Independent ID: 1c0e9e8c-4292-1e48-5e20-ba559afee3fe
* Content: [Security baseline settings on Azure Stack HCI (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/secure-baseline)
* Content Source: [azure-stack/hci/concepts/secure-baseline.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/secure-baseline.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by AjayBathini-MSFT** [comment]
@dkirby-ms 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@dkirby-ms 

"Closely meet" in this context means that the secure baseline provides a set of security configurations that are aligned with the Center for Internet Security (CIS) benchmark and Defense Information System Agency (DISA) Security Technical Implementation Guide (STIG) requirements for the operating system (OS) and the Microsoft recommended security baseline. However, it is important to note that the secure baseline may not meet all of the requirements of these standards. The secure baseline is designed to provide a strong starting point for securing your environment, but it is not a guarantee that your environment will be fully compliant with these standards. It is always recommended to review the specific requirements of the standards and adjust the secure baseline configurations as needed to meet your specific compliance needs.

The delta between "almost meeting" the standard and "actually meeting" it is the specific requirements of the standard that are not met by the secure baseline. While the secure baseline is designed to closely meet the requirements of the Center for Internet Security (CIS) benchmark and Defense Information System Agency (DISA) Security Technical Implementation Guide (STIG) for the operating system (OS) and the Microsoft recommended security baseline, it may not meet all of the requirements of these standards. For example, there may be specific controls or settings that are required by the standard that are not included in the secure baseline. It is important to review the specific requirements of the standards and adjust the secure baseline configurations as needed to meet your specific compliance needs.

if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by dkirby-ms** [comment]
Thanks, that helps and gets me what I need. A "nice to have" would be including this in our docs but of course I'll leave that up to the docs team to decide if you want to do that or not.

**Comment by AjayBathini-MSFT** [comment]
@dkirby-ms 
We're thrilled to hear that the suggestion we provided has been helpful and has met your needs. Your feedback is incredibly valuable to us, and we always aim to improve our services based on your input. Once again, thank you for contribution.

We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
