### ISSUE TITLE
Incorrect heading in Remove-AksHciNode

### ISSUE THREAD

**Issue by divyeshg94** [MicrosoftDocs/azure-stack-docs#2536]
[Enter feedback here]

Instead of remove a physical node, its marked as Add a physical node 
https://learn.microsoft.com/en-us/azure/aks/hybrid/reference/ps/remove-akshcinode

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 401fc8c6-697b-58fa-730c-3fb45ce58d27
* Version Independent ID: 783cd1fe-1a87-01df-f870-c816e0b09058
* Content: [Remove-AksHciNode for AKS hybrid - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/reference/ps/remove-akshcinode)
* Content Source: [AKS-Hybrid/reference/ps/remove-akshcinode.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/reference/ps/remove-akshcinode.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@divyeshg94 Thank you for reporting this, it's been updated and fixed in the documentation. #please-close
