### ISSUE TITLE
AKSHCI SDN Log using old module

### ISSUE THREAD

**Issue by xzrians** [MicrosoftDocs/azure-stack-docs#2542]
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/47202302/797906b1-0acd-437f-8ffc-d023afc7acd8)

AksHciSdnLogCollector not exist on PSGallery.
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/47202302/530c155f-210f-4351-be92-ee1564712928)

please update to use this module instead.
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/47202302/266b90c6-9e3b-44f1-9544-d5c189f3aa3f)

https://www.powershellgallery.com/packages/AksHciNcCompanion/0.8

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22f2042d-f0db-c61c-a4f0-9f50d28b30d6
* Version Independent ID: b89a6518-2f6c-94dc-fb23-8b4f7d809aa1
* Content: [How to use AKS hybrid with SDN and virtual networking infrastructure - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/software-defined-networking)
* Content Source: [AKS-Hybrid/software-defined-networking.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/software-defined-networking.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by AjayBathini-MSFT** [comment]
@xzrians 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@xzrians 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.

**Comment by SaibabaBalapur-MSFT** [comment]
#https://github.com/SaibabaBalapur-MSFT/azure-stack-docs-pr/pull/2
