### ISSUE TITLE
Two typos under post-install known issues for Tenant Applications are unable to bind certificates to applications

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#2543]
Two minor typos to technical details that could potentially impact customer environments in this section-
**Known issues (post-installation) -> Tenant Applications are unable to bind certificates to applications after upgrade**

- Step 2 incorrectly identifies port 2289 instead of 3389 (correctly mentioned in step 7)

> By default, remote desktop is disabled to all App Service infrastructure roles. Modify the **Inbound_Rdp_2289** rule action to Allow access.

- Step 5, the script in this section is missing an end-curly-brace "}"

Open braces are used for ForEach-Object, Invoke-Command, and If statement, but only two are closed at the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eae3b395-faa5-a31f-6442-75fcf8439da3
* Version Independent ID: 34ea4455-36ad-6f22-5813-17b7eafb6024
* Content: [App Service on Azure Stack Hub 2302 release notes - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/app-service-release-notes-2302?view=azs-2206#known-issues-post-installation)
* Content Source: [azure-stack/operator/app-service-release-notes-2302.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/app-service-release-notes-2302.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @apwestgarth
* Microsoft Alias: **anwestg**

**Comment by AjayBathini-MSFT** [comment]
@alexsmithMSFT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
@alexsmithMSFT I am not seeing the curly brace issue.

Step 5 seems to include the correct number of curly braces (2 open, 2 closed):

$c = Get-AppServiceConfig -Type Credential -CredentialName FrontEndCredential
$spwd = ConvertTo-SecureString -String $c.Password -AsPlainText -Force
$cred = New-Object System.Management.Automation.PsCredential ($c.UserName, $spwd)

Get-AppServiceServer -ServerType LoadBalancer | ForEach-Object {
    $lb = $_
    $session = New-PSSession -ComputerName $lb.Name -Credential $cred

    Invoke-Command -Session $session {
      $f = Get-WindowsFeature -Name Web-CertProvider
      if (-not $f.Installed) {
          Write-Host Install feature on $env:COMPUTERNAME
          Install-WindowsFeature -Name Web-CertProvider

          Shutdown /t 5 /r /f 
      }
}

Remove-PSSession -Session $session

Read-Host -Prompt "If installing the feature, the machine will reboot, wait till there are enough frontend availability and press ENTER to continue"

**Comment by sethmanheim** [comment]
Fixed in private repo. #please-close
