### ISSUE TITLE
"Hotfix 1.22301.2.60" not added to [Azure Stack Hub Hotfixes] RSS feed.

### ISSUE THREAD

**Issue by aluty** [MicrosoftDocs/azure-stack-docs#2556]
Observed:
1. Found [Azure Stack Hub hotfix 1.2301.2.60 - Azure Stack Hub | Microsoft Learn](https://learn.microsoft.com/en-us/azure-stack/operator/hotfix-1-2301-2-60?view=azs-2301)
2. **Not found** "Hotfix 1.22301.2.60" in Browse [Azure Stack Hub Hotfixes](https://azurestackhubdocs.azurewebsites.net/xml/hotfixes.rss) RSS feed.

**Comment by sethmanheim** [comment]
Correct, 2301.2.60 has not yet been added to the RSS feed. We'll try and get that added when the owner returns from vacation. #please-close
