### ISSUE TITLE
Arc VM management - controlplaneIP ?? 

### ISSUE THREAD

**Issue by lucidqdreams** [MicrosoftDocs/azure-stack-docs#2558]
Has anyone tried to follow these instructions recently?

A couple points – we do not recommend running AKS-HCI (GA product, managed using WAC and PS) and Arc Resource Bridge on the same Azure Stack HCI cluster. TSG - [Known issues with AKS hybrid clusters provisioned from Azure - AKS hybrid | Microsoft Learn](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Faks%2Fhybrid%2Ftroubleshoot-aks-hybrid-preview%23issues-with-using-aks-hci-and-azure-arc-resource-bridge&data=05%7C01%7Cmatt.quickenden%40avanade.com%7C6a4a241f072d42f7b58a08db94493f28%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C638266814551418015%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OberkWc9YPEC7BDGJBk9qGvPSoo1eFCMpuGaSVAa7%2BY%3D&reserved=0). This is a recent change in guidance and we’re working with the Arc VM team to get this added to their documentation.

This was a comment I got from HCI team.  However, when I try to deploy Arc VM management, without AKS, it keeps asking for controlplaneIP which "This is the IP address of the Kubernetes API server hosting the VM management application that is running inside the Resource Bridge VM. The IP address must be in the same subnet as the DHCP scope and must be excluded from the DHCP scope to avoid IP address conflicts. If DHCP is used to assign the control plane IP, then the IP address needs to be reserved."

I'm pretty confused how to get to the end of this installation an would appreciate this documentation being updated in line with no AKS deployment.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2b89ce1-6af9-aaa1-48f2-da8d2f5c8b75
* Version Independent ID: db6c5f7c-77b2-7a97-dc2c-d904db88edf5
* Content: [Set up Azure Arc VM management using command line (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address-1%2Cfor-static-ip-address-2#install-powershell-modules-azure-cli-extensions-and-host-agent-service)
* Content Source: [azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by RamanathanChinnappan-MSFT** [comment]
@lucidqdreams 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @alkohli 
Could you please look into this request, thanks.

**Comment by alkohli** [comment]
@SaibabaBalapur-MSFT  Can you please assign this to Kyle Zhang? He is the PM for this feature. The docs are being updated but how they align to the AKS is something he will be able to help with.

**Comment by ZmanKyle** [comment]
@lucidqdreams the doc does not install AKS HCI. Arc VM and AKS share the same infra components (Moc, Resource Bridge) and the resource bridge requires controlPlaneIP. The resource bridge contains an arc appliance VM which is located in a Kubernetes cluster, this is not AKS. Also, the AKS and Arc VM co-existence will not be an issue in HCI 23H2 with the introduction of Hybrid AKS.

**Comment by lucidqdreams** [comment]
I know it doesnt install it, but when I try to follow the instructions without AKS I am asked for a controlplaneIP parameter.  Which as the documentation explains that's the AKS endpoint... ?

**Comment by SaibabaBalapur-MSFT** [comment]
@ZmanKyle 
Please review.

**Comment by alkohli** [comment]
After conferring with the Engg team, we wanted to let you know that this issue is no longer relevant as the new 23H2 deployment installs the Arc resource bridge during the deployment itself. We will be happy to help if there are questions regarding the new process. Thank you again for filing this. Will close it now.

Cc: @ZmanKyle 

#please-close
