### ISSUE TITLE
missing domain whitelisting for k8s.io / cdn.dl.k8s.io

### ISSUE THREAD

**Issue by phwecker** [MicrosoftDocs/azure-stack-docs#2559]
customer alerted me that they spent weeks trying to get AKS hybrid up and running and now -finally- got pointed out by support  that the section about the allow list is missing an etnry for 

k8s.io / cdn.dl.k8s.io

pls verify with PG and add to prevent further customer deadlocks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 425ddc25-2a4b-c529-9d8c-b9e6975cfd1c
* Version Independent ID: 818658d6-3f73-7a88-93af-81018f971676
* Content: [Azure Kubernetes Service on Azure Stack HCI and Windows Server requirements - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/system-requirements?tabs=allow-table)
* Content Source: [AKS-Hybrid/system-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/system-requirements.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by RamanathanChinnappan-MSFT** [comment]
@phwecker 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@phwecker 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
@phwecker As you've seen from the ongoing thread, we have made updates to the documentation to address this issue. Closing for now, thank you for reporting this! #please-close
