### ISSUE TITLE
The Title and the Command are not matching

### ISSUE THREAD

**Issue by jaypaddy** [MicrosoftDocs/azure-stack-docs#2560]
The title says Get-AksHciContainerStorage, while the cmdlet is Get-AksHciStorageContainer

The cmdlet that works is Get-AksHciStorageContainer
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 76441d3e-7523-e1de-97ad-ce50f1ac786f
* Version Independent ID: b3f8f717-5696-6fa6-e5e9-3829ca907e89
* Content: [Get-AksHciStorageContainer for AKS hybrid - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/reference/ps/get-akshcistoragecontainer)
* Content Source: [AKS-Hybrid/reference/ps/get-akshcistoragecontainer.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/reference/ps/get-akshcistoragecontainer.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by RamanathanChinnappan-MSFT** [comment]
@jaypaddy 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
@jaypaddy Thank you very much for catching this. We will fix this ASAP and it should be live later today. Thanks again for the contribution! #please-close
