### ISSUE TITLE
Additional step required for Linux to use imported CA certificates

### ISSUE THREAD

**Issue by dmc-tech** [MicrosoftDocs/azure-stack-docs#2563]
[Enter feedback here]
I've found that with the later version of az cli, for Linux, the following command is also required after importing the CA certs :
```
export REQUESTS_CA_BUNDLE=~/.local/lib/python3.9/site-packages/certifi/cacert.pem
# RECOMMENDED: set the env var automatically for your subsequent sessions
echo 'export REQUESTS_CA_BUNDLE=~/.local/lib/python3.9/site-packages/certifi/cacert.pem' >> ~/.bash_profile
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a42ff21d-4d03-75c8-7ac7-7b03119b1e55
* Version Independent ID: 74536d0e-29ae-ecee-b1b2-17dfd3576b80
* Content: [Setting up certificates for Azure CLI on the Azure Stack Development Kit (ASDK)? - Azure Stack Development Kit (ASDK)](https://learn.microsoft.com/en-us/azure-stack/asdk/asdk-cli?tabs=lin&view=azs-2301#export-the-azure-stack-hub-ca-root-certificate)
* Content Source: [azure-stack/asdk/asdk-cli.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/asdk/asdk-cli.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub-asdk**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by dmc-tech** [comment]
Blog post here with further information: https://www.cryingcloud.com/blog/2023/8/25/azure-cli-determining-location-where-certificates-are-stored

**Comment by RamanathanChinnappan-MSFT** [comment]
@dmc-tech 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@sethmanheim
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@dmc-tech Thank you for reaching out, and very sorry for the delay. I have updated the article to include your command. Note that the ASDK is still functional but no longer officially supported. #please-close
