### ISSUE TITLE
Get-AzsVirtualNetworkGatewayConnection examples

### ISSUE THREAD

**Issue by Dionisas** [MicrosoftDocs/azure-stack-docs#2570]
Can't find such Get-AzsVirtualNetworkGatewayConnection command. Please list more detailed explanation on how to use this. Would be nice to see working example too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: befd912b-36b3-467a-602d-0de1c358e670
* Version Independent ID: 58114a6b-0508-c875-381c-de0aa434739c
* Content: [Azure Stack Hub VPN Fast Path for operators - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-vpn-fast-path-operators?view=azs-2301)
* Content Source: [azure-stack/operator/azure-stack-vpn-fast-path-operators.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-vpn-fast-path-operators.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @cedward
* Microsoft Alias: **cedward**

**Comment by sethmanheim** [comment]
@Dionisas Thank you for reaching out. The VPN Fast Path article does contain a link to the documentation for the Get-AzVirtualNetworkGatewayConnection cmdlet: https://learn.microsoft.com/en-us/powershell/module/az.network/get-azvirtualnetworkgatewayconnection?view=azps-10.2.0, including examples. 

Hope that helps, thanks again for the feedback. #please-close

**Comment by Dionisas** [comment]
Hi,

So you want to say that Get-AzsVirtualNetworkGatewayConnection and
Get-AzVirtualNetworkGatewayConnection is the same cmdlet and works fine on
Azure Stack Hub? If yes, which resource group Stack Operator should use in
order to see all tenant VPN connections?

**Comment by sethmanheim** [comment]
@Dionisas Sorry no, this is the wrong cmdlet. I am working with the product team to get the correct cmdlet documented. Thank you for pointing this out.

**Comment by Dionisas** [comment]
Simpy place ref, that in order this to work azs modules require updating to
newest version.  And link to correct cmdlet documentation.
