### ISSUE TITLE
Disabling IPv6 vs. Microsoft Recommendation on IPv6

### ISSUE THREAD

**Issue by MatheusPPfitscher** [MicrosoftDocs/azure-stack-docs#2571]
[Enter feedback here]
This documentation says to disable IPv6 on all clusters hosts to configure AKS Hybrid,
The official Microsoft documentation says that disabling IPv6 is not a recommended, which one should be followed?

https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 425ddc25-2a4b-c529-9d8c-b9e6975cfd1c
* Version Independent ID: 818658d6-3f73-7a88-93af-81018f971676
* Content: [Azure Kubernetes Service on Azure Stack HCI and Windows Server requirements - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/system-requirements?tabs=allow-table)
* Content Source: [AKS-Hybrid/system-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/system-requirements.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SaibabaBalapur-MSFT** [comment]
@MatheusPPfitscher 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@MatheusPPfitscher 
I apologize for any confusion this may have caused. You are correct that the official Microsoft documentation for AKS Hybrid does not recommend disabling IPv6. The documentation you mentioned that suggests disabling IPv6 on all cluster hosts is not specific to AKS Hybrid and may not be applicable to all scenarios. In general, it is recommended to leave IPv6 enabled unless there is a specific reason to disable it. In the case of AKS Hybrid, IPv6 is required for certain features such as dual-stack networking. Therefore, it is recommended to leave IPv6 enabled on all cluster hosts when configuring AKS Hybrid. I hope this helps clarify the issue.

**Comment by ManoharLakkoju-MSFT** [comment]
@MatheusPPfitscher 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
