### ISSUE TITLE
Get-AzsVirtualNetworkGatewayConnection is not publicly documented and this doc links to the wrong cmdlet

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#2574]
This doc links Get-AzsVirtualNetworkGatewayConnection cmdlet to public Azure's Get-AzVirtualNetworkGatewayConnection:

> For more information, see [Get-AzsVirtualNetworkGatewayConnection](https://learn.microsoft.com/en-us/powershell/module/az.network/get-azvirtualnetworkgatewayconnection).

But this is actually a different cmdlet, that is available in https://www.powershellgallery.com/packages/Azs.Network.Admin/1.1.0, which includes a markdown file-
> docs\Get-AzsVirtualNetworkGatewayConnection.md

That says it should be hosted at https://docs.microsoft.com/en-us/powershell/module/azs.network.admin/get-azsvirtualnetworkgatewayconnection but that link doesn't work.

My suggestion is to publish Get-AzsVirtualNetworkGatewayConnection.md under https://learn.microsoft.com/en-us/powershell/module/azs.network.admin/, and then update the link in this doc to point to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: befd912b-36b3-467a-602d-0de1c358e670
* Version Independent ID: 58114a6b-0508-c875-381c-de0aa434739c
* Content: [Azure Stack Hub VPN Fast Path for operators - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-vpn-fast-path-operators?view=azs-2301)
* Content Source: [azure-stack/operator/azure-stack-vpn-fast-path-operators.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-vpn-fast-path-operators.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @cedward
* Microsoft Alias: **cedward**

**Comment by sethmanheim** [comment]
@alexsmithMSFT This is something the engineering team would need to publish, as https://learn.microsoft.com/en-us/powershell/module/azs.network.admin/?view=azurestackps-2.2.0 contains the auto-generated PS cmdlet content that comes from the product team. @CristianEdwards is that something you can help with?

**Comment by SaibabaBalapur-MSFT** [comment]
@alexsmithMSFT 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by iancaragol** [comment]
Get-AzSVirtualNetworkGatewayConnection cmdlet is available in Azure Stack Powershell v2.4.0. It looks like the v2.4.0 docs have not been published to https://learn.microsoft.com/en-us/powershell/module/azs.network.admin

So we need to:

1. Publish the v2.4.0 Azure Stack Powershell documentation. @TheOnlyWei, is this something you can help with?
https://github.com/Azure/azurestack-powershell/commit/fbcd9713a1fd6e0dc532c4da079b1a283fe2635a

2. Update this doc to link to the Get-AzSVirtualNetworkGatewayConnection cmdlet published in v2.4.0

**Comment by AjayBathini-MSFT** [comment]
@alexsmithMSFT 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by AjayBathini-MSFT** [comment]
@alexsmithMSFT 
Still the document has not been updated. Can you please check and add your comments on this doc update request as applicable.

**Comment by alexsmithMSFT** [comment]
> So we need to:
> 1. Publish the v2.4.0 Azure Stack Powershell documentation. @TheOnlyWei, is this something you can help with?
>    [Azure/azurestack-powershell@fbcd971](https://github.com/Azure/azurestack-powershell/commit/fbcd9713a1fd6e0dc532c4da079b1a283fe2635a)
> 2. Update this doc to link to the Get-AzSVirtualNetworkGatewayConnection cmdlet published in v2.4.0

@AjayBathini-MSFT I'm not sure what you are asking me to do.... @iancaragol correctly identified the next steps above, but they are not done, so this issue is not resolved yet.

**Comment by AjayBathini-MSFT** [comment]
@alexsmithMSFT 
I have assigned to author. He will take care of it.

**Comment by alexsmithMSFT** [comment]
Hello @AjayBathini-MSFT, could you check on this again please?

[Get-AzsVirtualNetworkGatewayConnection.md](https://github.com/Azure/azurestack-powershell/blob/dev/src/Azs.Network.Admin/docs/Get-AzsVirtualNetworkGatewayConnection.md) is still not published at listed location- https://docs.microsoft.com/en-us/powershell/module/azs.network.admin/get-azsvirtualnetworkgatewayconnection (404 error)

And today I noticed [Get-AzsComputeScaleUnit.md](https://github.com/Azure/azurestack-powershell/blob/dev/src/Azs.Compute.Admin/docs/Get-AzsComputeScaleUnit.md) is also missing from https://learn.microsoft.com/en-us/powershell/module/azs.compute.admin/get-azscomputescaleunit

**Comment by alexsmithMSFT** [comment]
> Get-AzSVirtualNetworkGatewayConnection cmdlet is available in Azure Stack Powershell v2.4.0. It looks like the v2.4.0 docs have not been published to https://learn.microsoft.com/en-us/powershell/module/azs.network.admin
> 
> So we need to:
> 
> 1. Publish the v2.4.0 Azure Stack Powershell documentation. @TheOnlyWei, is this something you can help with?
>    [Azure/azurestack-powershell@fbcd971](https://github.com/Azure/azurestack-powershell/commit/fbcd9713a1fd6e0dc532c4da079b1a283fe2635a)
> 2. Update this doc to link to the Get-AzSVirtualNetworkGatewayConnection cmdlet published in v2.4.0

@TheOnlyWei is the action still on PG to push the 2.4.0 docs from the git repo? I saw that https://github.com/Azure/azurestack-powershell/commit/4b756404a96ccca4e2e39071862775ea86d463b3 was the one that released v.2.4.0 a few months ago, but I don't know how the .md files are meant to be pushed over to https://learn.microsoft.com/en-us/powershell/azurestackhub/

**Comment by sethmanheim** [comment]
@alexsmithMSFT Note that all your comments here are posted in the public repo, so they are visible to the world. There is a separate email conversation going on with Wei where I've pointed him to the tools and processes we have used to update the PS documentation. Let me know if you want to be added to that thread.

**Comment by alexsmithMSFT** [comment]
> @alexsmithMSFT Note that all your comments here are posted in the public repo, so they are visible to the world. There is a separate email conversation going on with Wei where I've pointed him to the tools and processes we have used to update the PS documentation. Let me know if you want to be added to that thread.

Thanks Seth. These are both public repos, so I don't see a problem with tracking it here, but happy to switch to the e-mail thread if you prefer.

**Comment by TheOnlyWei** [comment]
> > Get-AzSVirtualNetworkGatewayConnection cmdlet is available in Azure Stack Powershell v2.4.0. It looks like the v2.4.0 docs have not been published to https://learn.microsoft.com/en-us/powershell/module/azs.network.admin
> > So we need to:
> > 
> > 1. Publish the v2.4.0 Azure Stack Powershell documentation. @TheOnlyWei, is this something you can help with?
> >    [Azure/azurestack-powershell@fbcd971](https://github.com/Azure/azurestack-powershell/commit/fbcd9713a1fd6e0dc532c4da079b1a283fe2635a)
> > 2. Update this doc to link to the Get-AzSVirtualNetworkGatewayConnection cmdlet published in v2.4.0
> 
> @TheOnlyWei is the action still on PG to push the 2.4.0 docs from the git repo? I saw that [Azure/azurestack-powershell@4b75640](https://github.com/Azure/azurestack-powershell/commit/4b756404a96ccca4e2e39071862775ea86d463b3) was the one that released v.2.4.0 a few months ago, but I don't know how the .md files are meant to be pushed over to https://learn.microsoft.com/en-us/powershell/azurestackhub/

I am also not familiar with what files need to be generated and "pushed over". I inherited the release process, but there is no process documentation for the process of updating the MS docs. If you guys need docs for Get-AzsVirtualNetworkGatewayConnection, it is here:
https://github.com/Azure/azurestack-powershell/blob/dev/src/Azs.Network.Admin/docs/Get-AzsVirtualNetworkGatewayConnection.md

@sethmanheim is asking me for PlatyPS files, but I don't know what PlatyPS files he needs. The PlatyPS command generates multiple different files.
