### ISSUE TITLE
errors in getting SP secret and id

### ISSUE THREAD

**Issue by jeffbearer** [MicrosoftDocs/azure-stack-docs#2581]
Seems like the $sp has AppId and not ApplicationId.

also the snippit for getting the secret doesn't work for me seems like sp.Secret is empty.

 $secret = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($sp.Secret))
Exception calling "SecureStringToBSTR" with "1" argument(s): "Value cannot be null.
Parameter name: s"
At line:1 char:1
+ $secret = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 425ddc25-2a4b-c529-9d8c-b9e6975cfd1c
* Version Independent ID: 818658d6-3f73-7a88-93af-81018f971676
* Content: [Azure Kubernetes Service on Azure Stack HCI and Windows Server requirements - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/system-requirements?tabs=allow-table)
* Content Source: [AKS-Hybrid/system-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/system-requirements.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@jeffbearer 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by abhilashaagarwala** [comment]
@jeffbearer  - We state in the documentation that "Retrieve the password for the service principal by running the following command. Note that the below command only works for Az.Accounts 2.6.0 or lesser. We automatically download Az.Accounts 2.6.0 module when you install the AksHci PowerShell module." Can you please retry by deleting all versions of Az.Accounts > 2.6.0, installing 2.6.0 and see if it works for you?

**Comment by sethmanheim** [comment]
Closing for now, please send any follow-up questions. #please-close
