### ISSUE TITLE
Incorrect parameter name given in code examples

### ISSUE THREAD

**Issue by MrCNeale** [MicrosoftDocs/azure-stack-docs#2584]
The parameter list correctly lists the parameter as AzureStackLCMUserCredential
But the example code uses a wrong parameter AsHciDeploymentUserCredential 

This should be updated

![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/7669921/920becd5-9f29-4071-bd53-8e0f2dedb18d)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd5a83a8-3d61-090c-68f9-002b03048ef9
* Version Independent ID: 5eb2d3d1-d12e-9f7f-fa2f-4c2d54869388
* Content: [Prepare Active Directory for new Azure Stack HCI deployments (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-tool-active-directory)
* Content Source: [azure-stack/hci/deploy/deployment-tool-active-directory.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-tool-active-directory.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by Naveenommi-MSFT** [comment]
@MrCNeale 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@MrCNeale 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/13229
