### ISSUE TITLE
new-akshciclusternetwork and new-akshcinetworksetting issue for creating new akshci cluster network config

### ISSUE THREAD

**Issue by xzrians** [MicrosoftDocs/azure-stack-docs#2586]
new-akshcinetworksetting  -name parameter only allow lower case and no special character.

![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/47202302/00ebcf33-b29e-4f30-a83e-85870157a8dc)

on top of this. found out that the command to create new cluster network is incorrect. using new-akshcinetworksetting will not create new config for akshciclusternetwork

new-akshcinetworksetting
![RDCMan_xo1t3lDJAu](https://github.com/MicrosoftDocs/azure-stack-docs/assets/47202302/fb8dfa68-3a1c-411b-9e64-d8015d5e65a0)

new-akshciclusternetwork
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/47202302/3fb7fca9-3dc4-4ac2-9063-9408f3998c82)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2523f88c-8542-9cc7-3f48-86edf578e67a
* Version Independent ID: 900f28b4-8001-8eb4-bc22-db536fbee8af
* Content: [How to deploy AKS hybrid target clusters on different SDN virtual networks - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/deploy-target-clusters-virtual-networks)
* Content Source: [AKS-Hybrid/deploy-target-clusters-virtual-networks.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/deploy-target-clusters-virtual-networks.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by ManoharLakkoju-MSFT** [comment]
@xzrians 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@xzrians 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly

@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.
