### ISSUE TITLE
FQDN support for Time Server not working in AzS.Deployment.Worksheet PowerShell module

### ISSUE THREAD

**Issue by jgallucci32** [MicrosoftDocs/azure-stack-docs#26]
Using the latest AzS.Deployment.Worksheet PowerShell module, the field description says the following for the **Time Server:** field
> Enter a single IPv4 address or a single FQDN to be used as a reliable time source.
> NOTE: If a FQDN is specified, all of the network devices must support the use of a FQDN, otherwise validation will fail.

I attemped to use an FQDN for all 8 Vendor switches available in the list and all of them failed with the following error
> (ntp.domain.local) is not valid as a Time Server. If entering a FQDN, all switches must support FQDN for switch NTP. Contact OEM for support information.

I was working with my OEM rep and they were unsure how to proceed. Since all vendor switches throw an error this option should be removed until FQDN is actually supported.

**UPDATE**
I am using version v1.1811.1214.1 of the PowerShell module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147eee4f-8b0f-927a-14ff-5642accb3610
* Version Independent ID: 95213ed3-d96f-8ad9-e442-7c7f29164ebb
* Content: [Network integration considerations for Azure Stack integrated systems](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-network)
* Content Source: [articles/azure-stack/azure-stack-network.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-network.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by mattbriggs** [comment]
@jgallucci32 Thanks for providing feedback. The engineering team has opened items to resolve this issue. #please-close

**Comment by mattbriggs** [comment]
#please-close
