### ISSUE TITLE
Need to remove all Azure Stack HCI tabs, commands, mention. Change document to just for server 2019 & 2022 only

### ISSUE THREAD

**Issue by XavierCross** [MicrosoftDocs/azure-stack-docs#2611]
Need to remove all mention and tabs for Azure Stack HCI. The commands for installing resource bridge in this document are inconsistent with the Azure Stack HCI document. Also doesn't mention Resource Bridge is in preview for Azure Stack HCI.

The following document is out currently for customers wanting to install Resource Bridge on Azure Stack HCI

https://learn.microsoft.com/en-us/azure-stack/hci/manage/deploy-arc-resource-bridge-using-command-line?tabs=for-static-ip-address-1%2Cfor-static-ip-address-2

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b629133e-8471-d440-e8d4-c20b7162ebf9
* Version Independent ID: e3ea66bb-897c-c2ad-cd39-9723e79e0323
* Content: [How to deploy Azure Arc Resource Bridge on Windows Server - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/deploy-arc-resource-bridge-windows-server?tabs=shell)
* Content Source: [AKS-Hybrid/deploy-arc-resource-bridge-windows-server.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/deploy-arc-resource-bridge-windows-server.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @abha
* Microsoft Alias: **abha**

**Comment by SaibabaBalapur-MSFT** [comment]
@XavierCross 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@XavierCross 
Thank you for your suggestion. It would be helpful to provide your ideas in the below link so our product team will work on it.
https://feedback.azure.com/d365community
