### ISSUE TITLE
missing comma

### ISSUE THREAD

**Issue by laurentiupetre1** [MicrosoftDocs/azure-stack-docs#2631]
missing comman in point 4 "Install the required roles and features using the following command, then reboot before continuing." after "storage replica"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab3539e-5334-d406-7078-1bab3a66215d
* Version Independent ID: c1486a71-19a8-e347-d456-6714529306e6
* Content: [Deploy Azure Stack HCI on a single server - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/single-server)
* Content Source: [azure-stack/hci/deploy/single-server.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/single-server.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ronmiab
* Microsoft Alias: **robess**

**Comment by Naveenommi-MSFT** [comment]
@laurentiupetre1 
Thanks for your feedback! We will investigate and update as appropriate.
