### ISSUE TITLE
Clarify which version of .NET Azure Storage library depends on Jackson and is vulnerable

### ISSUE THREAD

**Issue by scharnyw** [MicrosoftDocs/azure-stack-docs#2635]
It's mentioned in the [Azure Stack Hub storage docs](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-storage-dev?view=azs-2306) that:

> There is a high severity vulnerability in old version of .NET and Java client library, because of the dependencies on a vulnerable version of Jackson package. It is strongly suggested to use the latest supported version of .NET and Java client library to avoid security issue.

Is it possible to clarify which version of .NET Azure Storage client library has this vulnerability? I looked through the dependencies of [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs) which is the latest SDK, and legacy [Microsoft.Azure.Storage.Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob) and [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage) going back several versions and did not find any dependency on "Jackson". I therefore suspect that the quote above only applied to Java libraries and not .NET.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b295ed4f-98c5-9fe1-4d6f-e35102467109
* Version Independent ID: 4a6ca293-f302-a0e1-eb01-f9e26d03beb6
* Content: [Learn Azure Stack Hub storage development tools - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-storage-dev?view=azs-2306)
* Content Source: [azure-stack/user/azure-stack-storage-dev.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-storage-dev.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Naveenommi-MSFT** [comment]
@scharnyw 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@scharnyw 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by scharnyw** [comment]
@sethmanheim Any news on this?

**Comment by sethmanheim** [comment]
@scharnyw Sorry for the delay here. I have a question pending with the product team to try and get this information. I'll follow up ASAP...

**Comment by sethmanheim** [comment]
@scharnyw Sorry for the delay here. I am removing this note as I believe it's incorrect at this point. Please open a new issue if this is still an issue for you. #please-close
