### ISSUE TITLE
Bugs in page

### ISSUE THREAD

**Issue by bsniderpa** [MicrosoftDocs/azure-stack-docs#2638]
The Az.StackHCI module also requires AzureRM.

The Register-AzStackHCI command section specified --credentials but it is just --credential

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a936999c-1c8d-e967-6571-4c73796b0721
* Version Independent ID: 6823f75b-1687-2829-d6db-a0bfbe52623d
* Content: [Register Azure Stack HCI with Azure - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/register-with-azure?tab=power-shell&tabs=windows-admin-center#register-a-cluster)
* Content Source: [azure-stack/hci/deploy/register-with-azure.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/register-with-azure.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
Thanks for reaching out @bsniderpa. AzureRM is being deprecated very soon, as we've announced.

**Comment by Naveenommi-MSFT** [comment]
@bsniderpa 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by bsniderpa** [comment]
Sorry, I am not a Windows or PowerShell user. I went back and looked at my history and saw that I had to install the Az module. I had installed Az.StackHCI as instructed but the HCI command still failed because I was missing Az.Resources so I found that I needed to install Az to make progress.

**Comment by ManoharLakkoju-MSFT** [comment]
@bsniderpa 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation
