### ISSUE TITLE
Error in example command

### ISSUE THREAD

**Issue by bsniderpa** [MicrosoftDocs/azure-stack-docs#2640]
This command fails:

Install-WindowsFeature -Name "BitLocker", "Data-Center-Bridging", "Failover-Clustering", "FS-FileServer", "FS-Data-Deduplication", "Hyper-V", "Hyper-V-PowerShell", "RSAT-AD-Powershell", "RSAT-Clustering-PowerShell", "NetworkATC", "Storage-Replica" "NetworkHUD" -IncludeAllSubFeature -IncludeManagementTools

The example command is missing a comma between Storage-Replica and NetworkHUD
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab3539e-5334-d406-7078-1bab3a66215d
* Version Independent ID: c1486a71-19a8-e347-d456-6714529306e6
* Content: [Deploy Azure Stack HCI on a single server - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/single-server)
* Content Source: [azure-stack/hci/deploy/single-server.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/single-server.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ronmiab
* Microsoft Alias: **robess**

**Comment by ronmiab** [comment]
@bsniderpa - the issue has been corrected in another PR. Changes should be published today.

**Comment by ronmiab** [comment]
please #close
