### ISSUE TITLE
Bad grammar in a note

### ISSUE THREAD

**Issue by bsniderpa** [MicrosoftDocs/azure-stack-docs#2641]
This note needs to be updated:

This procedure applies only if you an Azure AD admin

This procedure applies only if you are an Azure AD admin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0b133de-ea80-3860-b8d2-00f1b109fef9
* Version Independent ID: cea18011-66a6-521c-1517-312a1508f1ab
* Content: [Register Windows Admin Center with Azure - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/register-windows-admin-center)
* Content Source: [azure-stack/hci/manage/register-windows-admin-center.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/register-windows-admin-center.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@bsniderpa Thank you for catching that -- we will get it fixed right away. #please-close
