### ISSUE TITLE
Some mistakes and improvements on the page 

### ISSUE THREAD

**Issue by BrandonSardi** [MicrosoftDocs/azure-stack-docs#2644]
Hello Team, 

Found some issues while running this with a client these are my suggestions 

- Step 2 Command 4: Variable SubscriptionID instead of Subscription
Variable set above this is SubscriptionID but the script variable is Subscription recommend changing the command to use SubscriptionID.

- $Location: Variable not present
One of the commands require a $location variable that is not specified on the Variable setting step. 

- Step 3 Command 2: 3 --- instead of 2 (--)
Self explanatory the command begins with --- instead of --

- Step 4 Command 2: output has some header that is getting mixed with the required output
When testing this out with a customer before the output of the subscription was shared there was a notification that also was included in the variable causing problems when running the command, we fix it by copying only the valid part, but a clarification or a script that only sets the correct value will be appreciated 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe2b6d67-7a78-5e62-16cb-af88719c2a27
* Version Independent ID: 20e7ac2f-f88d-64ed-ebaa-18005aeb4d62
* Content: [How to deploy AKS on Azure Stack HCI with Arc VMs - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/deploy-aks-service-hci?tabs=powershell)
* Content Source: [AKS-Hybrid/deploy-aks-service-hci.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/deploy-aks-service-hci.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @abha
* Microsoft Alias: **abha**

**Comment by Naveenommi-MSFT** [comment]
@BrandonSardi 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@BrandonSardi 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.
