### ISSUE TITLE
AzStackHCI deployment results in error

### ISSUE THREAD

**Issue by kprpg** [MicrosoftDocs/azure-stack-docs#2654]
This STEP is causing the below error (shown in the pic)
![AzStackHCIError](https://github.com/MicrosoftDocs/azure-stack-docs/assets/11221387/5a6c40fd-86f9-4956-b69c-3b497256fc3c)
:- 
https://learn.microsoft.com/en-us/azure-stack/hci/guided-quick-deploy-eval?tabs=global-admin&tutorial-step=3
Script is: C:\AzHCI_Sandbox\AzSHCISandbox-main\New-AzSHCISandbox.ps1

![AzStackHCIError](https://github.com/MicrosoftDocs/azure-stack-docs/assets/11221387/5d17306f-b2e6-475a-b807-1bb4c7f26f02)

There is no way to Install chocolatey manually and restart as it breaks the Original deployment script within which multiple things happens one of which is installing the .NET Framework.
Rebooting does not restart anything and the Deployment script does not pick from where it left. Restarting the Deployment Script after reboot just ends in error saying VHDX file is locked by the process. 
So this needs to be fixed in the Original Deployment Script C:\AzHCI_Sandbox\AzSHCISandbox-main\New-AzSHCISandbox.ps1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd049ac2-b820-f3d4-9e65-57863a0f26ad
* Version Independent ID: e57d71ab-061f-03e4-c360-7d4687872916
* Content: [Evaluate Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/guided-quick-deploy-eval?tabs=global-admin&tutorial-step=3)
* Content Source: [azure-stack/hci/guided-quick-deploy-eval.yml](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/guided-quick-deploy-eval.yml)
* Service: **azure-stack**
* GitHub Login: @ronmiab
* Microsoft Alias: **robess**

**Comment by ManoharLakkoju-MSFT** [comment]
@kprpg 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@kprpg 
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by ronmiab** [comment]
@kprpg and @ManoharLakkoju-MSFT - Hello! This is a known issue that the product team and developers are working through. Unfortunately, there is currently no ETA. I am happy to update you at a later date when more detail is available.

**Comment by ronmiab** [comment]
@kprpg and @ManoharLakkoju-MSFT - In my communications with PMs/Devs, there have been some newer options introduced in the last month in terms of evaluating Azure Stack HCI. 
 
Here are the latest offerings: 
[Deploy a virtual Azure Stack HCI, version 23H2 system - Azure Stack HCI | Microsoft Learn](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-virtual)
[Azure Arc Jumpstart](https://arcjumpstart.com/azure_jumpstart_hcibox/getting_started)

**Comment by SaibabaBalapur-MSFT** [comment]
@kprpg 
It looks like your issue is resolved since you closed this thread.
If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
