### ISSUE TITLE
NAT stops working sometime after MS Online login and Step 60.120

### ISSUE THREAD

**Issue by amanjee** [MicrosoftDocs/azure-stack-docs#266]
I cannot resolve DNS at some point and my stack configuration fails, tried both static IP and DHCP as well as automatic DNS and manual DNS configurations. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e46293a4-00e4-46d5-d052-09f49c99d3c9
* Version Independent ID: 5df13a3e-3b6e-a90f-968e-72a5b5dc4447
* Content: [Install the Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-install)
* Content Source: [azure-stack/asdk/asdk-install.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-install.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TravisCragg-MSFT** [comment]
@amanjee the BGPNAT VM is no longer a part of the ASDK. What version of the ASDK are you using?

**Comment by amanjee** [comment]
Sorry, I was attempting a build downloaded on June 25, the NAT issue is on the host. Partially through setup, Nat seems to stop working. Retrying on latest build tonight

**Comment by amanjee** [comment]
Okay downloaded the latest build, same result. For some reason i seem to lose connectivity once the host netnat is built. I am using an Asus 10g nic, all other nics on the PC are disabled during the prep phase. I thought maybe my issue was related to static assignments on my gateway for the host, so I disabled that and have the static assignment using the ASDK setup.

**Comment by amanjee** [comment]
[Logs.zip](https://github.com/MicrosoftDocs/azure-stack-docs/files/3442441/Logs.zip)
Adding my log files

After trying to rebake this a few times over the weekend, the problem appears when teh Hostnic, Management, Deployment, and Storage NICs are deployed. it seems the nic that is supposed to NAT is not routing traffic and the Deployment NIC is also not routing any traffic.

**Comment by TravisCragg-MSFT** [comment]
@amanjee If you are deploying an AAD installation of the ASDK you will need internet connectivity for the physical machine. You can [review more about the network requirements here](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-deploy-considerations#network). 

Do you have a proxy or anything else that might be interrupting internet connectivity from the physical machine?

**Comment by amanjee** [comment]
Correct, Machine has internet connectivity prior to rollout and initially as I am able to sign into AAD when kicking it off. Once the Deployment and other NICs are built, connectivity drops. I still ahve everything plugged in, but the way the installler configures NICs and NATs, i can no longer connect once those are provisioned.. 

No proxies, no special VLans

**Comment by TravisCragg-MSFT** [comment]
@amanjee I am seeing a lot of networking resources not found errors throughout your log, and they seem to start early in the deployment. Have you run the [deployment checker for the Azure Stack Development Kit](https://gallery.technet.microsoft.com/Deployment-Checker-for-50e0f51b) to make sure that your environment is ready for the ASDK?

**Comment by amanjee** [comment]
Absolutely, only requirement not met is a lack of dual processor sockets, but there are enough total threads (32). Last night I watched it for the very moment that it drops off the network. It is after the NICs are created. Here is where networking stops functioning in the transcript.
[Network-starts-failing-here.txt](https://github.com/MicrosoftDocs/azure-stack-docs/files/3444582/Network-starts-failing-here.txt)

**Comment by TravisCragg-MSFT** [comment]
This was taken offline, and we are still troubleshooting. 

Closing for now.

**Comment by AzureAzim** [comment]
For any of those who are interested, the issue was related to my hardware NIC not liking the NetNat.
