### ISSUE TITLE
expired-secret-for-service-principal-spn-causes-cluster-to-fail

### ISSUE THREAD

**Issue by zohebk8s** [MicrosoftDocs/azure-stack-docs#2668]
Hi Team,

It’s related to updating expired SPN for cluster.

This week I’ve updated SPN for our cluster and followed this page which highlighted only two steps:

1. Update SPN 
2. Restart kubelet

However these two steps didn’t fixed the issue. Along with that, I’ve to restart master nodes as well.

I’ve already highlighted this to Microsoft and request you to please add that 3rd step.

ie Restart Master Nodes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bddc138b-1b2e-4be5-d38b-91818ccf1922
* Version Independent ID: fb4f2341-8ca1-f849-05f5-5b4ce22b9462
* Content: [Known issues with AKS engine on Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues?view=azs-2301#expired-secret-for-service-principal-spn-causes-cluster-to-fail)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by ManoharLakkoju-MSFT** [comment]
@zohebk8s 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@sethmanheim
Can you please check and add your comments on this doc update request as applicable.

**Comment by ManoharLakkoju-MSFT** [comment]
@zohebk8s 
I'm going to assign this to the document author so they can take a look at it accordingly

**Comment by zohebk8s** [comment]
@ManoharLakkoju-MSFT Thank you.

Hope it will be helpful for users.

**Comment by zohebk8s** [comment]
@sethmanheim Please let me know if any further information required from my side.

**Comment by sethmanheim** [comment]
@zohebk8s Thank you for reporting this -- I've sent a request for confirmation from the product team and am just waiting to hear back from them. Sorry for the delay...

**Comment by sethmanheim** [comment]
Hi @zohebk8s The answer from the engineering team is that we can replace `restart kubelet` with `reboot node`. I will update that section of the documentation.

Hope that helps. Thank you!

**Comment by zohebk8s** [comment]
@sethmanheim I would like to thank you and the team for acknowledging.

Once you update the documentation, just let me know. I will share this info with our team internally to follow this going forward. As we are using a couple of Azure Stack AKS Clusters.

**Comment by sethmanheim** [comment]
@zohebk8s Very sorry for the delay here. The documentation is updated and should be live later today. #please-close
