### ISSUE TITLE
example uses an undefined variable

### ISSUE THREAD

**Issue by bsniderpa** [MicrosoftDocs/azure-stack-docs#2679]
When setting up the storage and checking on the storage pool, the example is:

Get-StoragePool -CimSession $session

But $session is never defined anywhere

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df3012c4-22e5-004d-da6f-60744f2cfb4f
* Version Independent ID: 57e21edd-9a2b-f1ca-2ff7-48e3da5dc260
* Content: [Create an Azure Stack HCI cluster using Windows PowerShell - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell)
* Content Source: [azure-stack/hci/deploy/create-cluster-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/create-cluster-powershell.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ronmiab
* Microsoft Alias: **robess**

**Comment by RamanathanChinnappan-MSFT** [comment]
@bsniderpa 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@bsniderpa 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@ronmiab 
Can you please check and add your comments on this doc update request as applicable.

**Comment by ronmiab** [comment]
@bsniderpa - we have the doc updates in another PR and will update and close this one once that content is published.

**Comment by ronmiab** [comment]
The update has been published. #please-close
