### ISSUE TITLE
Update prerequisite documentation - SQL RP and PowerShell

### ISSUE THREAD

**Issue by rfsonders** [MicrosoftDocs/azure-stack-docs#268]
Team.
The SQL RP PowerShell requirements are still very much mismatched. Please add this workaround to the PowerShell documentation.
Work-around for SQL RP PowerShell mismatch.
1. Install the current AzS build.
2. Run this script to remove all Azure* modules.
3. Install the SQL RP.
4. Rerun the current AzS Powershell build.

Get-Module -Name Azs.* -ListAvailable | Uninstall-Module -Force
Get-Module -Name Azure* -ListAvailable | Uninstall-Module -Force
Remove-Item 'C:\Program Files (x86)\WindowsPowerShell\Modules\Azure*' -Force 
Remove-Item 'C:\Program Files (x86)\WindowsPowerShell\Modules\Azs*' -Force 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dabc86bd-3770-5832-7fa5-d28856998ae6
* Version Independent ID: cbdb8c6f-ad4d-9e3d-a490-f1348b5ccdfa
* Content: [Using SQL databases on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-deploy#feedback)
* Content Source: [azure-stack/operator/azure-stack-sql-resource-provider-deploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-sql-resource-provider-deploy.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@rfsonders Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
# rfsonders I believe you need the older version of the AzureRM module to install this RP. I have a question out to the engineers. In any case, this should be called and we should have instructions on uninstall current modules. Thanks for your feedback. #in-progress

**Comment by MatthewAt3Sharp** [comment]
why are the RPs still running on a much older version of PS? it is a huge pain to constantly have to uninstall, reinstall various levels of PS. this is a bad user exp.

**Comment by mattbriggs** [comment]
@MatthewAt3Sharp I've passed the this feedback back to the product team. I agree it is painful, especially given that to use Azure Stack you already need to manage older RP endpoints and use a specific Azure modules. #product-feedback

**Comment by mattbriggs** [comment]
#please-close
