### ISSUE TITLE
JSON for Azure Role

### ISSUE THREAD

**Issue by eszych** [MicrosoftDocs/azure-stack-docs#2683]
[Enter feedback here]

in this section: https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-tool-set-up-first-server#assign-azure-permissions-using-powershell
)the JSON seems to be wrong and running the command 
`New-AzRoleDefinition -InputFile "C:\CustomRoles\customHciRole.json"`
leads to an error.

The sample on the URL https://learn.microsoft.com/en-us/azure/role-based-access-control/tutorial-custom-role-powershell
is different and is misssing the line `  "id": "/subscriptions/<Azure subscription ID>",`

`{
  "Name": "Reader Support Tickets",
  "IsCustom": true,
  "Description": "View everything in the subscription and also open support tickets.",
  "Actions": [
    "*/read",
    "Microsoft.Support/*"
  ],
  "NotActions": [],
  "DataActions": [],
  "NotDataActions": [],
  "AssignableScopes": [
    "/subscriptions/00000000-0000-0000-0000-000000000000"
  ]
}`

creating a JSON similar to the one above but with the needed Actions / permissions works.

`{
    "Name": "Azure Stack HCI 23H2 validator and registration role",
    "Description": "Custom Azure role to allow subscription-level access to register Azure Stack HCI",
    "IsCustom": true,
    "Actions": [
        "Microsoft.Resources/subscriptions/resourceGroups/read",
        "Microsoft.Resources/subscriptions/resourceGroups/write",
        "Microsoft.Resources/subscriptions/resourceGroups/delete",
        "Microsoft.AzureStackHCI/register/action",
        "Microsoft.AzureStackHCI/Unregister/Action",
        "Microsoft.AzureStackHCI/clusters/*",
        "Microsoft.Authorization/roleAssignments/write",
        "Microsoft.Authorization/roleAssignments/read",
        "Microsoft.HybridCompute/register/action",
        "Microsoft.GuestConfiguration/register/action",
        "Microsoft.HybridConnectivity/register/action",
        "Microsoft.HybridCompute/machines/extensions/write",
        "Microsoft.HybridCompute/machines/extensions/read",
        "Microsoft.HybridCompute/machines/extensions/delete",
        "Microsoft.HybridCompute/machines/read",
        "Microsoft.HybridCompute/machines/write",
        "Microsoft.HybridCompute/machines/delete",
        "Microsoft.HybridCompute/privateLinkScopes/read",
        "Microsoft.GuestConfiguration/guestConfigurationAssignments/read",
        "Microsoft.ResourceConnector/register/action",
        "Microsoft.ResourceConnector/appliances/read",
        "Microsoft.ResourceConnector/appliances/write",
        "Microsoft.ResourceConnector/appliances/delete",
        "Microsoft.ResourceConnector/locations/operationresults/read",
        "Microsoft.ResourceConnector/locations/operationsstatus/read",
        "Microsoft.ResourceConnector/appliances/listClusterUserCredential/action",
        "Microsoft.ResourceConnector/operations/read",
        "Microsoft.Kubernetes/register/action",
        "Microsoft.KubernetesConfiguration/register/action",
        "Microsoft.ExtendedLocation/register/action",
        "Microsoft.HybridContainerService/register/action",
        "Microsoft.KubernetesConfiguration/extensions/write",
        "Microsoft.KubernetesConfiguration/extensions/read",
        "Microsoft.KubernetesConfiguration/extensions/delete",
        "Microsoft.KubernetesConfiguration/extensions/operations/read",
        "Microsoft.KubernetesConfiguration/namespaces/read",
        "Microsoft.KubernetesConfiguration/operations/read",
        "Microsoft.ExtendedLocation/customLocations/deploy/action",
        "Microsoft.ExtendedLocation/customLocations/read",
        "Microsoft.ExtendedLocation/customLocations/write",
        "Microsoft.ExtendedLocation/customLocations/delete"
    ],
    "notActions": [],
    "dataActions": [],
    "notDataActions": [],
    "assignableScopes": [
        "/subscriptions/e350e4c9-wxyz-abcd-1234-60692dba1d20"
    ]
}`

Please update the documentation accordingly.

An while you are at it, please change the titel of the box from "jason" to "JSON" :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f348f5a9-0a14-e5f6-1539-8c3b8d41a75e
* Version Independent ID: 6dfec0ea-f662-9ff4-5803-6a60b6e6172c
* Content: [Set up the first server for new Azure Stack HCI deployments (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-tool-set-up-first-server)
* Content Source: [azure-stack/hci/deploy/deployment-tool-set-up-first-server.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-tool-set-up-first-server.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by RamanathanChinnappan-MSFT** [comment]
@eszych 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@eszych 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@alkohli 
Can you please check and add your comments on this doc update request as applicable.

**Comment by eszych** [comment]
still not changed on the original learn website...???

**Comment by eszych** [comment]
@alkohli @SaibabaBalapur-MSFT 
Another week has gone by and the page has not been updated...

**Comment by alkohli** [comment]
@eszych  Just wanted to let you know that 22H2SP pages (the ones that you are referring to are not being updated). These qualify as earlier versions and the only pages in 22H2SP that we are updating or creating are the release notes for updates. The deploy and manage for these articles was moved to a pdf. The latest generally available version is Azure Stack HCI, version 23H2 if you want to give that a try. This version went public preview in mid November and GA last week.

**Comment by alkohli** [comment]
@SaibabaBalapur-MSFT  I will be closing this issue. #please-close

**Comment by alkohli** [comment]
#close-off

**Comment by alkohli** [comment]
#please-close
