### ISSUE TITLE
Steps incorrect

### ISSUE THREAD

**Issue by mzbowe** [MicrosoftDocs/azure-stack-docs#27]
If you follow this step by step, in will not work.  You Should create the VNets, Subnets and Virtual Network GWs first on each side.  If you do that THEN you ca do this step "type the public IP address for your Azure Stack Virtual Network Gateway that is listed previously in the network configuration table." - which is listed in the Azure section, but before anything had been done in Azure Stack.  Therefore, you will not have the IP Address for the Azure Stack VNet GW, because it has not been created yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fec5666f-c9b6-2ae6-3a46-3b390d252d19
* Version Independent ID: cbdfbfc9-a835-2015-ce60-a6e0578c4d4a
* Content: [Connect Azure Stack to Azure using VPN](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-connect-vpn)
* Content Source: [articles/azure-stack/azure-stack-connect-vpn.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-connect-vpn.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@mzbowe Please feel free to open another GitHub issue if you still require help with this issue. Thanks again for reaching out! #please-close
