### ISSUE TITLE
New-AksHciVipPoolSetting needs lowercase Name

### ISSUE THREAD

**Issue by eszych** [MicrosoftDocs/azure-stack-docs#2701]
[Enter feedback here]

The example Code for the $VipPool definition is as follows:
`$VipPool = New-AksHciVipPoolSetting -name "PublicVIP" -vipPoolStart $VIPPoolStart -vipPoolEnd $VIPPoolEnd`

running this command leads to the following error:
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/33837465/461271f8-92f9-4b4d-b862-4594e9d7a61f)

The Name Parameter needs to be all lower-case!

Please correct the Documentaion!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22f2042d-f0db-c61c-a4f0-9f50d28b30d6
* Version Independent ID: b89a6518-2f6c-94dc-fb23-8b4f7d809aa1
* Content: [How to use AKS hybrid with SDN and virtual networking infrastructure - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/software-defined-networking#install-and-prepare-sdn-for-aks-hybrid)
* Content Source: [AKS-Hybrid/software-defined-networking.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/software-defined-networking.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by ManoharLakkoju-MSFT** [comment]
@eszych 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@sethmanheim
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@eszych Thank you, I will update this information in a separate PR.
