### ISSUE TITLE
Code Sample - missing "

### ISSUE THREAD

**Issue by eszych** [MicrosoftDocs/azure-stack-docs#2702]
in the sample:
`New-AksHciNetworkSetting -name "SDNVNet1" -vswitchName "ConvergedSwitch(hci) 
-ipAddressPrefix "13.20.0.0/8" -gateway "13.20.0.1" -dnsServers "10.195.95.223" 
-k8sNodeIpPoolStart "13.20.0.2" -k8sNodeIpPoolEnd "13.20.100.255"`

There is a missing `"`  on the first line just behind `"ConvergedSwitch(hci) `

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2523f88c-8542-9cc7-3f48-86edf578e67a
* Version Independent ID: 900f28b4-8001-8eb4-bc22-db536fbee8af
* Content: [How to deploy AKS hybrid target clusters on different SDN virtual networks - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/deploy-target-clusters-virtual-networks)
* Content Source: [AKS-Hybrid/deploy-target-clusters-virtual-networks.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/deploy-target-clusters-virtual-networks.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@eszych Thank you for catching that! We will get it updated ASAP.

**Comment by sethmanheim** [comment]
Working in another PR.
