### ISSUE TITLE
Code Samples not working!

### ISSUE THREAD

**Issue by eszych** [MicrosoftDocs/azure-stack-docs#2703]
I followed the code samples to create a new VNET and that succeeded, but when I tried to retrieve the new VNET using the `Get-AksHciClusterNetwork` Command it failed - see below
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/33837465/60a65ca5-b90e-4794-b3db-e73a1d2abf30)

it would be better to create the VNET and directly put it into a variable like this: 
`$vnet = New-AksHciNetworkSetting -name "aksvnet1" -vSwitchName $vSwitchName -ipAddressPrefix $ipAddressPrefix -gateway $gateway -dnsServers "192.168.60.10" -k8sNodeIpPoolStart $k8sNodeIpPoolStart -k8sNodeIpPoolEnd $k8sNodeIpPoolEnd `

The Variable `$vent` then contains the necessary information for the next step...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2523f88c-8542-9cc7-3f48-86edf578e67a
* Version Independent ID: 900f28b4-8001-8eb4-bc22-db536fbee8af
* Content: [How to deploy AKS hybrid target clusters on different SDN virtual networks - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/deploy-target-clusters-virtual-networks)
* Content Source: [AKS-Hybrid/deploy-target-clusters-virtual-networks.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/deploy-target-clusters-virtual-networks.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@eszych Thank you for the suggestion. I've changed it to this, please confirm:

```powershell
$vnet = New-AksHciNetworkSetting -name "SDNVNet1" -vSwitchName $vSwitchName -ipAddressPrefix $ipAddressPrefix -gateway $gateway -dnsServers "192.168.60.10" -k8sNodeIpPoolStart $k8sNodeIpPoolStart -k8sNodeIpPoolEnd $k8sNodeIpPoolEnd 
$vnet = Get-AksHciClusterNetwork
```

**Comment by sethmanheim** [comment]
Working in another PR.

**Comment by eszych** [comment]
> @eszych Thank you for the suggestion. I've changed it to this, please confirm:
> 
> ```powershell
> $vnet = New-AksHciNetworkSetting -name "SDNVNet1" -vSwitchName $vSwitchName -ipAddressPrefix $ipAddressPrefix -gateway $gateway -dnsServers "192.168.60.10" -k8sNodeIpPoolStart $k8sNodeIpPoolStart -k8sNodeIpPoolEnd $k8sNodeIpPoolEnd 
> $vnet = Get-AksHciClusterNetwork
> ```

The second line (`$vnet = Get-AksHciClusterNetwork`) is not needed, the variable `$vnet` already contains the object.

**Comment by ManoharLakkoju-MSFT** [comment]
@sethmanheim 
Could you Please review this.

**Comment by sethmanheim** [comment]
@eszych Thank you. Fixes will be live by end of day today!
