### ISSUE TITLE
The whole documentation is not working!

### ISSUE THREAD

**Issue by eszych** [MicrosoftDocs/azure-stack-docs#2704]
In the last code sample on the page the variable for the VNET is in double quotes like - but this is not working:

![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/33837465/c7af791f-7965-467b-b213-9649ab88ad66)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2523f88c-8542-9cc7-3f48-86edf578e67a
* Version Independent ID: 900f28b4-8001-8eb4-bc22-db536fbee8af
* Content: [How to deploy AKS hybrid target clusters on different SDN virtual networks - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/deploy-target-clusters-virtual-networks)
* Content Source: [AKS-Hybrid/deploy-target-clusters-virtual-networks.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/deploy-target-clusters-virtual-networks.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by ManoharLakkoju-MSFT** [comment]
@eszych 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@eszych 
I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
@eszych Thank you for reaching out and sorry for the delay. This article has been completely updated; in particular the name of the cmdlet has been updated to `New-AksHciClusterNetwork`. Hope that's helpful. #please-close
