### ISSUE TITLE
Duplicate -RepairRegistration on commad

### ISSUE THREAD

**Issue by xzrians** [MicrosoftDocs/azure-stack-docs#2710]
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/47202302/39186975-6240-4bca-a5f1-8441318f2d15)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 250faed6-284d-dc39-538e-9da2e19f8449
* Version Independent ID: f8b31b2e-d7d5-90c0-0736-7b242e8b1388
* Content: [Monitor a single Azure Stack HCI cluster with Insights - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/monitor-hci-single?tabs=22h2-and-later)
* Content Source: [azure-stack/hci/manage/monitor-hci-single.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/monitor-hci-single.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @dansisson
* Microsoft Alias: **v-dansisson**

**Comment by VikasPullagura-MSFT** [comment]
@xzrians Thanks for reporting this, we will check and update the document.

**Comment by SaibabaBalapur-MSFT** [comment]
@xzrians 
Thank you for reporting this. Our document team has updated this page. You can review the changes made and updates in this document.
https://learn.microsoft.com/en-us/azure-stack/hci/manage/monitor-hci-single?tabs=22h2-and-later#repair-cluster-registration:~:text=rely%20on%20AMA.-,Repair%20cluster%20registration,TenantID%7D%20%2DSubscriptionId%20%7BsubscriptionID%7D%20%2DComputerName%20%7BNodeName%7D%20%2DRepairRegistration,-Repair%20AMA%20for


We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
