### ISSUE TITLE
The article refers to an external video that is unavailable

### ISSUE THREAD

**Issue by VitalKoshalew** [MicrosoftDocs/azure-stack-docs#2713]
The article links to a video that is not available (made private):
`For example, the demo at the 37-minute mark of this presentation shows [various mixes achieving 46 percent, 54 percent, and 65 percent efficiency](https://www.youtube.com/watch?v=-LK2ViRGbWs&t=36m55s) with 12 servers.`

Generally, it doesn't seem to be a good idea to use external sources in documentation. Furthermore, referring to a different type of media (a video from a text documentation) may be undesirable, i.e. for accessibility reasons.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6daf71fc-aa1a-9e6e-c939-23edeceec1f2
* Version Independent ID: 8a69b399-3682-6767-4794-3cb81fcae479
* Content: [Fault tolerance and storage efficiency on Azure Stack HCI and Windows Server clusters - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/fault-tolerance)
* Content Source: [azure-stack/hci/concepts/fault-tolerance.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/fault-tolerance.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Naveenommi-MSFT** [comment]
@VitalKoshalew 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@JasonGerend
Can you please check and add your comments on this doc update request as applicable.

@VitalKoshalew 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by sethmanheim** [comment]
@VitalKoshalew Checking the article, this seems to be resolved now. #please-close
