### ISSUE TITLE
AZURE STACK AZURE ACTIVE DIRECTORY APPLICATION CREATION

### ISSUE THREAD

**Issue by jonathan-vella** [MicrosoftDocs/azure-stack-docs#272]
Team, as per https://azurestack.blog/2019/01/lesson-learned-azure-stack-azure-active-directory-application-creation/ you need to add the required parameter “-AzureStackAdminCredential" when executing "Create-AADIdentityApp.ps1"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Before you deploy App Service on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started#feedback)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by TravisCragg-MSFT** [comment]
@jonathan-vella Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by BryanLa** [comment]
Thanks @jonathan-vella. 

This particular parameter (`$AzureStackAdminCredential`) is showing as `Mandatory=$false` in the Create-AADIdentityApp.ps1 script, with a help message of `Scripts will prompt for credentials if not provided.` I'd like to bring @apwestgarth into the conversation to comment before making any doc changes, as he owns the install script.

I was able to test the script far enough that it worked for me. Ie: to the point where `Get-AzureRmUserRefreshToken()` was called with an empty `$AutomationCredential` parameter, which calls the `Add-AzureRmAccount()` cmdlet cited as failing in the post. The comment for that call also says `Prompts the user for interactive login flow if automation credential is not specified`. When I ran it, it successfully prompted me for admin creds, and returned the refresh token.

**Comment by BryanLa** [comment]
I've discussed this with engineering as well, and they've confirmed my analysis. Please let me know though, if you feel there is something that needs to be updated in the article, or feel free to submit a PR against the article and I can review for merge. Thanks!

CXP #please-close.
