### ISSUE TITLE
PSH Cmdlet incorrect (?)

### ISSUE THREAD

**Issue by tobyjrreu** [MicrosoftDocs/azure-stack-docs#2724]
[Enter feedback here]
Hi, 

Just checking in the examples it's showing the cmdlet 

New-AKSHCINetworkSettings , however, that appears to fail to create the actual network shouldn't the command be
New-AKSHCIClusterNetwork ?

As seen in Kyle video here: https://techcommunity.microsoft.com/t5/networking-blog/sdn-aks-3-15-23-updates-and-features/ba-p/3769859

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2523f88c-8542-9cc7-3f48-86edf578e67a
* Version Independent ID: 900f28b4-8001-8eb4-bc22-db536fbee8af
* Content: [How to deploy AKS hybrid target clusters on different SDN virtual networks - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/deploy-target-clusters-virtual-networks)
* Content Source: [AKS-Hybrid/deploy-target-clusters-virtual-networks.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/deploy-target-clusters-virtual-networks.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SaibabaBalapur-MSFT** [comment]
@sethmanheim
Can you please check and add your comments on this doc update request as applicable.

@sethmanheim 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by sethmanheim** [comment]
Hi @tobyjrreu -- thanks for pointing this out. I'm just double checking with Kyle, so I'll get back to you ASAP.

**Comment by sethmanheim** [comment]
@tobyjrreu Sorry for the delay here -- yes this is correct, and it should be `New-AksHciClusterNetwork` instead of `New-AksHciNetworkSetting` that's in the doc today. I will get this updated today, and many thanks again for reporting it.

**Comment by sethmanheim** [comment]
#please-close
