### ISSUE TITLE
How to perform an Role assignment to ASH using Powershell. 

### ISSUE THREAD

**Issue by Chirag1233** [MicrosoftDocs/azure-stack-docs#2728]
Hi There, 
I have an Azure Stack Hub running in disconnected mode and currently, it is integrated with the ADFS. I am trying to use the

New-AzRoleAssignment -ObjectId $($GroupDetails.SID.Value) -Scope "/subscriptions/$($LandingZone.SubscriptionId)" -RoleDefinitionId $($roleDefDetails.id) -Verbose

However I am getting the error that principal ID is not valid it's to do with the SID as this command is only expecting the ObjectID Guid. Do you know if I need to specify anything special to get this working with the SIDs? 

Thanks and REgards, 
Chirag Dave

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b12c58c5-d502-b45e-9cb8-699be1856deb
* Version Independent ID: aae468e2-40d7-007a-e47f-cf30a1238bae
* Content: [Connect to Azure Stack Hub with PowerShell - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-configure-admin?view=azs-2306&tabs=az1%2Caz2%2Caz3)
* Content Source: [azure-stack/operator/azure-stack-powershell-configure-admin.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-powershell-configure-admin.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Chirag1233** [comment]
This is the Error I am getting

New-AzRoleAssignment : The content of your request was not valid, and the original object could not be deserialized. Exception message: 'Required property 'principalId' not found in JSON. Path 
'properties', line 4, position 3.'
At line:1 char:1
+ New-AzRoleAssignment -ObjectId "S-1-5-21-291718924-XXXXXXX-3639566 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand

**Comment by AjayBathini-MSFT** [comment]
@Chirag1233 
could you provide the URL of the specific Microsoft documentation that your feedback is applicable to? That way, we are able to make sure your feedback is addressed by the right team.

**Comment by AjayBathini-MSFT** [comment]
@Chirag1233 
Thank you for your feedback! 

I'd recommend working closer with our support team via an [Azure support request] (https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. 
[Teams Q&A forum] (https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum] (https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
Thank you for your time and patience throughout this issue.
