### ISSUE TITLE
Clarification on below statement on the document

### ISSUE THREAD

**Issue by phosatti** [MicrosoftDocs/azure-stack-docs#273]
"Marketplace images are available for pay-as-you-use or BYOL (EA/SPLA) licensing. Use of both on a single Azure Stack instance is not supported."

Is this limitation true? What level is the limitation at? Tenant level or Stack level? 
Can two seperate tenants run pay-as-you-use and BYOL respectively on the same stack? Customers would want to run both. Please confirm if this limitation is true and if there is a work around here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf72767c-5772-1398-dfbc-2f736aeb3e2a
* Version Independent ID: c8f3ce87-baa9-5a4f-6b2e-f0dd6614c6a3
* Content: [Supported guest operating systems for Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-supported-os)
* Content Source: [azure-stack/operator/azure-stack-supported-os.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-supported-os.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Mike-Ubezzi-MSFT** [comment]
@phosatti Thank you very much for your interest in Azure cloud services. I am redirecting your question to the service area specializing in Azure Stack but, I did want to request from you the specific document your question arises from. Thank you.

**Comment by TravisCragg-MSFT** [comment]
@phosatti You can find more information [Here about the different versions of Windows Server that are available on the Azure Stack Marketplace](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-windows-server-faq#what-are-the-licensing-options-for-windows-server-marketplace-images-on-azure-stack). This limit is at the Azure Stack level, and it is unfortunately enforced by the Windows Server team, so there is not a workaround. Both can be downloaded, but only one can be deployed at a time. 

If you would like to run both, you will need 2 separate Azure Stack deployments.

**Comment by TravisCragg-MSFT** [comment]
@phosatti We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
