### ISSUE TITLE
Missing reference or link to : 23H2_ClusterDeploy_Template.json

### ISSUE THREAD

**Issue by jbthefish** [MicrosoftDocs/azure-stack-docs#2735]
Dear Team,

i am missing reference or link to : 23H2_ClusterDeploy_Template.json. Can not find it!
Please update the webpage with an easy to find link or paste the content.

Thanks,
JB

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19e287e0-c90a-15ba-0d7b-15e8f8f2cc84
* Version Independent ID: 573de587-4673-4ad4-0042-b23d8c732b08
* Content: [Azure Resource Manager template deployment for Azure Stack HCI, version 23H2 (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-azure-resource-manager-template)
* Content Source: [azure-stack/hci/deploy/deployment-azure-resource-manager-template.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-azure-resource-manager-template.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by RamanathanChinnappan-MSFT** [comment]
@jbthefish 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by alkohli** [comment]
@jbthefish The 23H2 deployment via ARM template article is now updated and it links to a sample json file that can be used with the quickstart template. The whole article has had major changes including what you are asking. Please take a look. Thanks again for your question!

I will be closing off this issue.

@ManoharLakkoju-MSFT 

#please-close
