### ISSUE TITLE
Add strong recommendation that VMs should be created under a CSV volume for them to be HAVMs

### ISSUE THREAD

**Issue by kerimhanif** [MicrosoftDocs/azure-stack-docs#2740]
In https://learn.microsoft.com/en-us/azure-stack/hci/manage/vm#create-a-new-vm we have a screenshot. Even though this is a screenshot to be used as an example, it shows a local path for the VM. If customers do this, they will NOT get an HAVM! 

Also in the article we say:

In number 7 of Azure Portal flow, under Path, we say "_select a preassigned file path from the dropdown list or click Browse to choose the folder to save the VM configuration and virtual hard disk (VHD) files to. You can browse to any available SMB share on the network by entering the path as \server\share._"

So, it doesn't also say there that they should place this VM on a ClusterStorage so that this is an HAVM.

We should at a minimum say in number 7 that "**we strongly recommend that you select a cluster shared volume in order for this VM to be highly available**."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 63b7027b-560c-777c-9c33-0ae3d9aca43b
* Version Independent ID: 13e9e402-e89e-974d-1e63-aa567e29bdca
* Content: [Manage VMs with Windows Admin Center - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/vm#create-a-new-vm)
* Content Source: [azure-stack/hci/manage/vm.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/vm.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by RamanathanChinnappan-MSFT** [comment]
@kerimhanif
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by alkohli** [comment]
@AjayBathini-MSFT Please assign this to me. I will take care of this issue.

**Comment by alkohli** [comment]
@kerimhanif This change seems to be done in this doc. Also, this Git issue channel is primarily meant for customers. MSFT can actually file a content workitem or reach out to the content team to get this change made :-). Thank you. Closing this issue now.

#please-close
