### ISSUE TITLE
The year and release ID is missing from this docs page

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/azure-stack-docs#2747]
This page says the following:

![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/503974/1fe5fae2-c8e2-4c43-a6dc-d63ea0b60c8b)

What September? What year? 2021? 2023? 2099? 20xx?

Can we please update this page to have something more descriptive to know what year this feature was actually released?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4b51ac2d-86d8-1c65-3fb9-c2e00b465d23
* Version Independent ID: 9bb65dbb-3202-c774-8afb-8cdb916243b7
* Content: [Set up multiple administrators on AKS hybrid - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/set-multiple-administrators)
* Content Source: [AKS-Hybrid/set-multiple-administrators.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/set-multiple-administrators.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by RamanathanChinnappan-MSFT** [comment]
@eponerine 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by sethmanheim** [comment]
@eponerine Sorry for the confusion there. I've updated the article to indicate this is referring to the September 2022 release (and later).

**Comment by sethmanheim** [comment]
#please-close
