### ISSUE TITLE
-Scope is not an option for AzSSecurity

### ISSUE THREAD

**Issue by hfu949** [MicrosoftDocs/azure-stack-docs#2748]
The doc instructs users to use **-Scope <Local | Cluster>** parameter but that's not an option. It's just -Local, -Cluster or -PerNode.

![AzsSecurity](https://github.com/MicrosoftDocs/azure-stack-docs/assets/22666204/3753f73e-437e-4066-9c0d-0eac4f84eae9)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4898389f-c8f6-a8f4-b386-d2491051eedd
* Version Independent ID: 1c0e9e8c-4292-1e48-5e20-ba559afee3fe
* Content: [Security baseline settings on Azure Stack HCI, version 23H2 (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/secure-baseline)
* Content Source: [azure-stack/hci/concepts/secure-baseline.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/secure-baseline.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by SaibabaBalapur-MSFT** [comment]
@hfu949 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@hfu949

According to the document you supplied, it appears that the appropriate parameters for the **-Scope option** are **-Local, -Cluster, or -PerNode**. The **-Scope option** is employed to indicate the extent of the security baseline application.

For instance, to apply the security baseline to a particular node, you can utilize the **-Scope PerNode** option. To extend the security baseline to all nodes in a cluster, choose the **-Scope Cluster** option. If you wish to apply the security baseline to the local machine, use the **-Scope Local** option.
If there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by hfu949** [comment]
Hi @RamanathanChinnappan-MSFT,

Perhaps I wasn't clear, -Scope is not a valid parameter. Readers will encounter an error if they try to use -Scope with any of the three options. See the output

<img width="813" alt="image" src="https://github.com/MicrosoftDocs/azure-stack-docs/assets/22666204/bb330f81-1410-4435-9505-99ab8a79315e">

**Comment by RamanathanChinnappan-MSFT** [comment]
@hfu948
I apologize for the confusion. You are correct that the "-Scope" parameter is not valid for the three options mentioned in the article. If you try to use "-Scope" with any of these options, you will encounter an error.
Thank you for bringing this to our attention. I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by RamanathanChinnappan-MSFT** [comment]
@alkohli
could you please review this and update as appropriate.

**Comment by alkohli** [comment]
@hfu949 Thank you for bringing this to our attention. We will be removing this parameter. I will be creating a PR.
#in-progress

**Comment by alkohli** [comment]
@hfu949  The PR is merged: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/14707 and should go live tomorrow morning (3/13) after 10 AM. I will close this issue now. Thanks!

#please-close

**Comment by hfu949** [comment]
Hi @alkohli, it looks like manage bitlocker was updated but manage-secure-baseline.md needs to be updated as well with the same type of change..
