### ISSUE TITLE
Confusing gMSA deployment steps

### ISSUE THREAD

**Issue by arp-mbender** [MicrosoftDocs/azure-stack-docs#2762]
The article is really confusing in two aspects:
- namespace usage
- deployment usage

## Confusing namespace usage
Specifically, section 2. of `Configure gMSA for Windows pods and containers in the cluster` specifies the following with no details:  
`<secret under namespace other than the default>`

It is unclear if this secret MUST be created in a different namespace other than default or not and how this will be used later on.

## Confusing deployment
- Service account is listed in an improper YML format in section 1. under `Deploy the application` (nested `securityContext` is invalid):
```
serviceAccountName: default
   securityContext:  <- this is nested; the entire section seems to contain parts of section 2. instead?
     windowsOptions: 
       gmsaCredentialSpecName:
```
- In addition to the improper format `default` is probably an invalid value and likely depends on the account created in section 3. of `Configure gMSA for Windows pods and containers in the cluster`.
- Section 3. describes a volume mount; gMSA examples on Kubernetes own sites don't list such a requirement. In addition the secret created in a prior step doesn't have the paths listed here, so it makes no sense.

The whole thing could use a clean-up pass + an actual example deployment YML, akin to the sample from section 3. of `Configure gMSA for Windows pods and containers in the cluster`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a4455cc-ac26-428f-596c-45ea6f42179e
* Version Independent ID: a0a8b873-17c6-2856-278a-d02982502334
* Content: [Configure group Managed Service Accounts (gMSA) for Windows containers with Azure Kubernetes Service on Azure Stack HCI and Windows Server - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/prepare-windows-nodes-gmsa)
* Content Source: [AKS-Hybrid/prepare-windows-nodes-gmsa.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/prepare-windows-nodes-gmsa.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by ManoharLakkoju-MSFT** [comment]
@arp-mbender 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@sethmanheim
Can you please check and add your comments on this doc update request as applicable.

**Comment by SaibabaBalapur-MSFT** [comment]
@arp-mbender 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by sethmanheim** [comment]
@arp-mbender As we are moving to a new feedback system, we have opened corresponding work items and are tracking all open issues in our internal database.  We are closing all public issues, but as mentioned above, there are other ways to provide feedback. Thank you again for reaching out! #please-close
