### ISSUE TITLE
What does network ATC mean?

### ISSUE THREAD

**Issue by byguo2018** [MicrosoftDocs/azure-stack-docs#2779]
Dear Sir/Madam,

I almost read all the linked documents you mentioned in the page, but there seems no clear explanation for ATC. What does ATC mean please? Is it an abbreviation for 3 words?

Thanks.
Bruce Guo

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e1cea280-89dd-b421-0ca9-da8fc972610d
* Version Independent ID: 746905a4-0549-449c-6842-d365fb7da05d
* Content: [Manage Network ATC - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/manage-network-atc?source=recommendations&tabs=21H2)
* Content Source: [azure-stack/hci/manage/manage-network-atc.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/manage-network-atc.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by Naveenommi-MSFT** [comment]
@byguo2018 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
Hi @byguo2018 **ATC** stands for Azure Traffic Controller. It is a software-defined networking (SDN) solution that provides network virtualization and security for Azure Stack HCI. ATC is built on top of the Windows Server Software Defined (WSSD) networking stack and provides a distributed network controller that runs on each node in the cluster. It enables you to create and manage virtual networks, network security groups, and user-defined routes. You can use ATC to create and manage virtual networks, network security groups, and user-defined routes. It also provides a distributed firewall that can be used to filter traffic between virtual networks and between virtual networks and the physical network.

**Comment by byguo2018** [comment]
Thank you very much.

Bruce Guo

发件人: Saibaba Balapur Hireka ***@***.***>
发送时间: Tuesday, January 2, 2024 2:48 PM
收件人: MicrosoftDocs/azure-stack-docs ***@***.***>
抄送: Bruce Guo ***@***.***>; Mention ***@***.***>
主题: Re: [MicrosoftDocs/azure-stack-docs] What does network ATC mean? (Issue #2779)


Hi @byguo2018<https://github.com/byguo2018> ATC stands for Azure Traffic Controller. It is a software-defined networking (SDN) solution that provides network virtualization and security for Azure Stack HCI. ATC is built on top of the Windows Server Software Defined (WSSD) networking stack and provides a distributed network controller that runs on each node in the cluster. It enables you to create and manage virtual networks, network security groups, and user-defined routes. You can use ATC to create and manage virtual networks, network security groups, and user-defined routes. It also provides a distributed firewall that can be used to filter traffic between virtual networks and between virtual networks and the physical network.

―

**Comment by SaibabaBalapur-MSFT** [comment]
@byguo2018 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

**Comment by sethmanheim** [comment]
@byguo2018 @SaibabaBalapur-MSFT Actually "Network ATC" does not stand for anything -- it's a proper noun, similar to Network HUD.

**Comment by SaibabaBalapur-MSFT** [comment]
@sethmanheim Thanks for clarification on this.
