### ISSUE TITLE
Mis Spell for north-south traffic under Scenario heading

### ISSUE THREAD

**Issue by Ravivarman13** [MicrosoftDocs/azure-stack-docs#2782]
[ East-West storage traffic replication won't interfere or compete with north-**sound** traffic dedicated for management and compute
I believe there is spelling mistake on north-sound traffic rather it should be **north-south** traffic]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1adb8c8-0a51-0695-bf37-1c2d94efd7eb
* Version Independent ID: e42734c4-1987-4f1c-0cd1-dbdb25691e46
* Content: [Azure Stack HCI two-node storage switched, non-converged deployment network reference pattern - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/plan/two-node-switched-non-converged)
* Content Source: [azure-stack/hci/plan/two-node-switched-non-converged.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/plan/two-node-switched-non-converged.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @dansisson
* Microsoft Alias: **v-dansisson**

**Comment by VikasPullagura-MSFT** [comment]
@Ravivarman13 
Thanks for the feedback! We will check and update the document as appropriate.

**Comment by SaibabaBalapur-MSFT** [comment]
@Ravivarman13 
Thanks for reporting this! We have created a PR for this issue and the changes should go live soon.

https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/14067
