### ISSUE TITLE
Documentation suggests using an out-of-support Ubuntu 16.04 image

### ISSUE THREAD

**Issue by phealy** [MicrosoftDocs/azure-stack-docs#2783]
Ubuntu 16.04 LTS has been EOL since April 2021; we probably shouldn't be recommending customers build with that image almost 3 years later.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 824169a1-5250-d9e0-9f47-509e03ef4aad
* Version Independent ID: 48de76d6-2fb1-df25-5ebb-7853eed6ee62
* Content: [Create Linux VM with Azure CLI in Azure Stack Hub - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/user/azure-stack-quick-create-vm-linux-cli?view=azs-2206)
* Content Source: [azure-stack/user/azure-stack-quick-create-vm-linux-cli.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/user/azure-stack-quick-create-vm-linux-cli.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by VikasPullagura-MSFT** [comment]
@phealy 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@sethmanheim 
Can you please check and add your comments on this doc update request as applicable.

**Comment by sethmanheim** [comment]
@phealy Thank you for the feedback and sorry for the delay. I have updated this article to include the most recent supported LTS version, which is 20.04. I also updated the PowerShell article. Thanks again for reaching out. #please-close
