### ISSUE TITLE
ESU for Azure Stack HCI dates appear to be incorrect

### ISSUE THREAD

**Issue by deanbostedor** [MicrosoftDocs/azure-stack-docs#2794]
This isn't right. Not sure who can fix it.
 
Windows Server version isn't specified, and I think the intent was to call out SQL and Server 2008 RS ESU expiration dates. I suspect this was written prior to 2012 ESUs being available and so the language doesn't reflect the updates.

_"There are several advantages to getting ESU through Azure, which extend to Azure Stack HCI:

Free of charge: You can get ESUs through Azure Stack HCI for free.
**Get an additional year of ESUs for Windows Server: On Azure and Azure Stack HCI only, ESUs for Windows Server will end on January 14, 2024 and July 12, 2023 respectively**; a year longer than the usual three-year ESU programs."_

Customer asked if they only have until next week to get ESUs before their Azure Stack HCI benefit expires.
https://learn.microsoft.com/en-us/azure-stack/hci/manage/azure-benefits-esu?tabs=windows-server-2012#benefits-of-getting-esu-for-vms-on-azure-stack-hci

**Comment by sethmanheim** [comment]
@deanbostedor Thanks for reaching out -- I've just forwarded this to the PM to verify. I'll get back to you here, ASAP.

**Comment by deanbostedor** [comment]
Thanks Seth.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sethmanheim** [comment]
@deanbostedor Good catch. Yes, this statement applies to Windows Server 2008 ESUs only. There is no extra year announced yet for WS 2012 ESUs. Since this additional benefit is no longer that relevant at this point, I will remove it. There are still redirect links elsewhere in the article to see the ESU lifecycle. Thanks again for bringing this up.

**Comment by sethmanheim** [comment]
#please-close
