### ISSUE TITLE
Test-AzureStack -Include list incomplete.

### ISSUE THREAD

**Issue by aluty** [MicrosoftDocs/azure-stack-docs#2798]
List for -Include parameter is incomplete.
**Test-AzureStack -List**
```
AzsAcsSummary
AzsActionPlanStatus
AzsAdSummary
AzsAgentHealth
AzsAksAcrPreviewSummary
AzsAlertSummary
AzsApplicationCrashSummary
AzsBackupShareAccessibility
AzsControlPlane
AzsDCBValidation
AzsDefenderSummary
AzsEceProvisioningStatus
AzsExternalCertificates
AzsGpuConfigurationSummary
AzsHardwareMonitorEnable
AzsHostingInfraFWSummary
AzsHostingInfraSummary
AzsHostingInfraUtilization
AzsIdentityProviderConnectivity
AzsIdentityProviderStatus
AzsInfraCapacity
AzsInfraFileValidation
AzsInfraPerformance
AzsInfraRoleSummary
AzsInfraUpdateMemory
AzsInfraUpdateSummary
AzsNCImosValidation
AzsNetworkInfra
AzsOemHardware
AzsOemUpdatePrereqs
AzsPortalAPISummary
AzSRdmaOperationalStatus
AzsResourceProviderAuthStatus
AzsScaleUnitEvents
AzsScaleUnitResources
AzsScenarios
AzsSFRoleSummary
AzsSQLDiagnostics
AzsSQLSummary
AzsStampBMCSummary
AzsStorageDataPlane
AzsStorageSvcsSummary
AzsStoreSummary
AzsUsage
AzsUsageBridgeSummary
AzsVmPlacement
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7062722e-8cab-c8ba-6f77-6fba03be0ccd
* Version Independent ID: e260c6a1-7cec-2c32-76b6-a80ce0ac00fe
* Content: [Validate system state with the Azure Stack Hub validation tool - Azure Stack Hub](https://learn.microsoft.com/en-us/azure-stack/operator/azure-stack-diagnostic-test?view=azs-2306)
* Content Source: [azure-stack/operator/azure-stack-diagnostic-test.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/operator/azure-stack-diagnostic-test.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by AjayBathini-MSFT** [comment]
@aluty 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by sethmanheim** [comment]
@aluty Thank you, I will get this added to the release branch. Note that you filed this in the public repo, so all discussions and version numbers are visible publicly.

**Comment by sethmanheim** [comment]
@aluty Is it safe to assume that anything that's in the doc but NOT on the above list, should be removed (for example, Azure Stack Hub Cloud Hosting Infrastructure Summary)?

**Comment by sethmanheim** [comment]
Done, thank you. Will be live with 2311. #please-close

**Comment by aluty** [comment]
> @aluty Is it safe to assume that anything that's in the doc but NOT on the above list, should be removed (for example, Azure Stack Hub Cloud Hosting Infrastructure Summary)?
It depends since the documentation may need to cover N, N-1, N-2 releases.

**Comment by sethmanheim** [comment]
> > @aluty Is it safe to assume that anything that's in the doc but NOT on the above list, should be removed (for example, Azure Stack Hub Cloud Hosting Infrastructure Summary)?
> > It depends since the documentation may need to cover N, N-1, N-2 releases.

There's no indication in this GitHub issue as to what version(s) this applies to. I've made the change per your original submission, feel free to file a PR if anything is wrong. Also note that any discussion here is visible publicly to anyone with a GitHub account.
