### ISSUE TITLE
Virtual Networking naming and topology consistency

### ISSUE THREAD

**Issue by carlbuchmann** [MicrosoftDocs/azure-stack-docs#28]
- [x] The relevant Azure service or technology: Azure Stack virtual networking concepts
- [x] A link to the published documentation article that you have feedback about.:
  https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-network.md
https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-connect-expressroute.md

- [x] Clear, specific feedback that the author can act on.
The documentations/diagrams related to virtual network devices do not use consistent naming or topology which leads to confusion. What is the correct traffic flow and terminology for traffic routing to device on public networks (Public VIPs). For example this is the various naming and topology referred to across various documents and diagram:
- SDN | Software BGP ASN : https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/media/azure-stack-network/NetworkDiagram.png
- Load Balancer : https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/media/azure-stack-connect-expressroute/Conceptual.png
- NAT | Multitenant Gateway: https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/media/azure-stack-connect-expressroute/Architecture.png
- NAT/FW | SLB | Multitenant Gateway: https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/media/azure-stack-connect-expressroute/EndToEnd.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 147eee4f-8b0f-927a-14ff-5642accb3610
* Version Independent ID: 95213ed3-d96f-8ad9-e442-7c7f29164ebb
* Content: [Network integration considerations for Azure Stack integrated systems](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-network)
* Content Source: [articles/azure-stack/azure-stack-network.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-network.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by mattbriggs** [comment]
@carlbuchmann Thanks for your detailed feedback. I've passed it along to our engineering team. I'll update as soon I get an update. #please-close

**Comment by mattbriggs** [comment]
#please-close
