### ISSUE TITLE
Time out error after 2 hours deploying

### ISSUE THREAD

**Issue by eversonamancio** [MicrosoftDocs/azure-stack-docs#2819]
I tried to deploy Azure Stack HCI 23H2 using portal three times.

In all tentatives i received a time-out error message after 2 hours deploying the resources for a two-node cluster.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80cd7a2c-6a28-973c-6def-6a5be0132e44
* Version Independent ID: 695bc1f5-5d3f-b667-9ea9-76cffef475a6
* Content: [Deploy an Azure Stack HCI system using the Azure portal - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deploy-via-portal)
* Content Source: [azure-stack/hci/deploy/deploy-via-portal.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deploy-via-portal.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by SaibabaBalapur-MSFT** [comment]
@eversonamancio 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment]
@eversonamancio 
I'm going to assign this to the document author so they can take a look at it accordingly

@JasonGerend 
Can you please check and add your comments on this doc update request as applicable.

**Comment by alkohli** [comment]
@eversonamancio This was a known issue documented here:
