### ISSUE TITLE
Avoiding test files full of zeros

### ISSUE THREAD

**Issue by DougBernhardt** [MicrosoftDocs/azure-stack-docs#2828]
When using diskspd to validate storage, by default is writes test files filled with zeros. The examples in this article use those default settings. Some storage appliances recognize this and do not read/write pages of zeros to and from disk. Therefore, if you're testing with the default settings, you may not be actually hitting the disk. When using diskspd to validate storage performance a better way would be to use the flags to populate the file with random data.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dcbfe3b-52e3-7cc4-0727-3055383db649
* Version Independent ID: c894cd31-5738-8a11-78ec-5ecb4b8ad341
* Content: [Use DISKSPD to test workload storage performance - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/diskspd-overview)
* Content Source: [azure-stack/hci/manage/diskspd-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/diskspd-overview.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by AjayBathini-MSFT** [comment]
@DougBernhardt 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by sethmanheim** [comment]
@DougBernhardt As we are moving to a new feedback system, we have opened corresponding work items and are tracking all open issues in our internal database.  We are closing all public issues, but as mentioned above, there are other ways to provide feedback. Thank you again for reaching out! #please-close
