### ISSUE TITLE
ASDK - Quickstart template for File Server dep fails

### ISSUE THREAD

**Issue by juajac** [MicrosoftDocs/azure-stack-docs#283]
Hi, when I try to download the file server vm from quickstart, it fails. "The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest' is not available. ". I´m new to ASDK, can you help me? thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Before you deploy App Service on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started#feedback)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by TravisCragg-MSFT** [comment]
@juajac You will need to [download the Marketplace Image for Windows Server 2016](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-download-azure-marketplace-item#connected-scenario). Also, make sure you are using the template designed for the ASDK. 

I have assigned the issue to the content author to evaluate and update as appropriate.

@BryanLa It seems we do not state in this doc that the 2016 Datacenter image is required, can you add it?

**Comment by juajac** [comment]
Answer: just download a Windows 2016 Datacenter machine from marketplace first.

**Comment by BryanLa** [comment]
Yes. This is included in the HA template, and soon the stand-alone template, but I'll add to the article as well..

**Comment by BryanLa** [comment]
Done. The revised article will be republished around 3:30 PDT on 9/5. 

#please-close
