### ISSUE TITLE
Request more information about what the onprem preparation of Active Directory does

### ISSUE THREAD

**Issue by degrootea** [MicrosoftDocs/azure-stack-docs#2841]
Thank you so much for outlining how to prepare the onprem Active Directory.
It would be nice to get an explanation why this needs to be done or a link to a resource that explains why

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ebc97e0d-11b1-df69-173e-90016800fd89
* Version Independent ID: 3b9245c0-7047-ccc2-915a-7f9c6d310d05
* Content: [Prepare Active Directory for new Azure Stack HCI, version 23H2 deployment (preview) - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-prep-active-directory)
* Content Source: [azure-stack/hci/deploy/deployment-prep-active-directory.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-prep-active-directory.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by AjayBathini-MSFT** [comment]
@degrootea 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by alkohli** [comment]
@degrootea We have made major changes to the AD prep article here: https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-prep-active-directory. You can now use your own procedure to create an OU that will be used for Azure Stack HCI, version 23H2 deployment.  Please take a look at the article and let me know if any questions you have are answered. 

@AjayBathini-MSFT

**Comment by alkohli** [comment]
Am going to close this issue. Thank you. #please-close
