### ISSUE TITLE
buy option grayed

### ISSUE THREAD

**Issue by juajac** [MicrosoftDocs/azure-stack-docs#287]
Hi, in ASDK, when create a virtual machine, everything goes OK, the summary page shows validation passed, but option 5 "buy" is grayed, can´t create the virtual machine. No error message, just option 5 grayed. Any ideas? Thanks for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a36e4c-e20e-e8fa-2944-f004ef046e09
* Version Independent ID: 0aec3f91-5789-7ffc-55ed-50bdab79d7eb
* Content: [Make virtual machines available to your Azure Stack users](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-tutorial-tenant-vm)
* Content Source: [azure-stack/operator/azure-stack-tutorial-tenant-vm.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-tutorial-tenant-vm.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Mike-Ubezzi-MSFT** [comment]
@juajac Thank you for bringing this to our attention. We are currently investigating and will update you when we have greater clarity surrounding the issue.

**Comment by TravisCragg-MSFT** [comment]
@juajac First, I would make sure that everything in your ASDK deployment is working as expected. You can do this by [validating your installation using test-azurestack](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-post-deploy#validate-the-asdk-installation).  If that shows everything as green, make sure that the subscription has adequate quotas for the deployment.

**Comment by TravisCragg-MSFT** [comment]
@juajac Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
