### ISSUE TITLE
--proxy

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#2875]
> If you're accessing the internet via a proxy server, you need to pass the --proxy parameter and provide the proxy server as http://<Proxy server FQDN or IP address>:Port when running the script.

The parameter only has one hyphen (-).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00d02e07-0813-47ed-69d3-b4d777d07b53
* Version Independent ID: 9a403bb0-bd87-78ea-f987-12b1fe354eb0
* Content: [Register your Azure Stack HCI servers with Azure Arc and assign permissions for deployment - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-arc-register-server-permissions)
* Content Source: [azure-stack/hci/deploy/deployment-arc-register-server-permissions.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-arc-register-server-permissions.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by VikasPullagura-MSFT** [comment]
@aricbernard 
Thanks for the feedback! We will check and update the document as appropriate.

**Comment by aricbernard** [comment]
After additional testing, I can confirm that User Access Administrator is only required at the Resource Group level (not the Subscription level).

**Comment by AjayBathini-MSFT** [comment]
@aricbernard 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

@alkohli 
Can you please check and add your comments on this doc update request as applicable.

**Comment by alkohli** [comment]
@aricbernard Thanks for bringing this to our notice. Based on the title of this issue, it seems that the change required was for the proxy article. I do want to confirm that the proxy article was updated. See the updated version here: https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-arc-register-server-permissions#register-servers-with-azure-arc

Also regarding the permissions and roles, the article had major updates with the 2311.2 GA release and with 2402 release. The roles and permissions were updated. User Access Admin is now not needed at the sub level. 

I will be closing this issue. 

#please-close
