### ISSUE TITLE
Roles required for 23H2 server registration with Arc

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#2876]
> If you're registering the servers as Arc resources, make sure that you have the following permissions on the resource group where the servers were provisioned:

The two listed roles, Azure Connected Machine Onboarding and Azure Connected Machine Resource Administrator, are insufficient in this context.  The user who registers the servers with Azure Arc will also need the User Access Administrator role assigned at the subscription level otherwise role assignment attempts that occurs during the new Arc registration process in 23H2 will fail.  Note that the Arc registration itself will appear to succeed, and the errors which are not particularly highlighted will occur.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00d02e07-0813-47ed-69d3-b4d777d07b53
* Version Independent ID: 9a403bb0-bd87-78ea-f987-12b1fe354eb0
* Content: [Register your Azure Stack HCI servers with Azure Arc and assign permissions for deployment - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-arc-register-server-permissions)
* Content Source: [azure-stack/hci/deploy/deployment-arc-register-server-permissions.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-arc-register-server-permissions.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by VikasPullagura-MSFT** [comment]
@aricbernard 
Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate.

**Comment by VikasPullagura-MSFT** [comment]
@alkohli 
Can you please check and add your comments on this doc update request as applicable.

**Comment by alkohli** [comment]
#in-progress Started a thread w/ Engg team to verify if the roles are sufficient or the user needs User Access Admin role at the sub level. Thanks for bringing this to my notice!

**Comment by alkohli** [comment]
@aricbernard Changes were made to the above doc. We have added an extra prereq that requires the registration to the RPs at the sub level. For that action, owner or contributor perms are required. Once that is done, the currently documented perms (that do not require owner perms at sub level) will work. Closing this issue.

**Comment by alkohli** [comment]
#please-close
