### ISSUE TITLE
Partner Future Requirements

### ISSUE THREAD

**Issue by ld0614** [MicrosoftDocs/azure-stack-docs#289]
Is there any information as to what requirements partners need to go through to become certified?  Specifically I have a customer who wants to understand if there are commitments to long term certification / re-certification as driver and software updates are updated.

Are there any plans for upgrades once Windows Server vNext is released?  Or are these solutions envisaged to remain on Windows Server 2019 for the entire hardware lifecycle?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3f2787b-e9cb-0580-78c5-ffbdc7c36be6
* Version Independent ID: c326847f-f62a-2916-819e-b2a1b15564cc
* Content: [Azure Stack HCI overview](https://docs.microsoft.com/en-gb/azure-stack/operator/azure-stack-hci-overview)
* Content Source: [azure-stack/operator/azure-stack-hci-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-hci-overview.md)
* Product: **windows-server-threshold**
* Technology: **storage**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by YutongTie-MSFT** [comment]
@ld0614 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@ld0614 An Azure Stack HCI solution is considered valid by Microsoft, as-is, for the full 10 years that the base OS is supported. The Azure Stack HCI solution validation program does not require hardware vendors to re-run and re-submit validation for every monthly OS patch.  However, it does require re-validation for every major OS version, and for major platform changes. Also, most of the major OEMs do regular testing with monthly updates and configurations in their own labs above-and-beyond the requirements of the program for the benefit of their customers. 
 
Also, solutions validated for Windows Server 2016 are not automatically validated for Windows Server 2019: the hardware vendor must run and submit validation with the new OS if they decide it makes business sense to support it (which many did, in this case). Individual OEMs decide if they will validate older or existing platforms for new OS releases as part of the program. As an example, virtually every platform that was listed for 2016 solutions was also validated for 2019 solutions, with the exception of legacy platforms that were no longer being sold. Changes to key parts of the hardware bill of materials also require additional validations. These are critical items like motherboards, HBAs, and NICs.

**Comment by TravisCragg-MSFT** [comment]
@ld0614 We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by fbifido** [comment]
DO you have Validating App for said hardware?
