### ISSUE TITLE
Document removing app service worker tiers, including Remove-AppServiceWorkerTier  cmdlet

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#29]
This doc addresses creating custom worker tiers, but not how to remove them. Recomment adding a section on removing them, including this cmdlet, which does not appear to be documented anywhere...

**Remove-AppServiceWorkerTier -WorkerSize <worker size> -ComputeMode <Compute mode>**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba102ce6-c79f-33fe-fadb-a77a4c5cdd8f
* Version Independent ID: c38cb661-e97f-8bf1-4c48-1b5c1359b856
* Content: [Scale out worker roles in App Services - Azure Stack](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-app-service-add-worker-roles)
* Content Source: [articles/azure-stack/azure-stack-app-service-add-worker-roles.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-add-worker-roles.md)
* Service: **azure-stack**
* GitHub Login: @apwestgarth
* Microsoft Alias: **anwestg**

**Comment by sethmanheim** [comment]
@alexsmithMSFT Sorry for the delay here -- cleaning out old issues as we're moving to a new feedback system. Please contact us directly if changes are needed. #please-close
