### ISSUE TITLE
Include Important note from Uninstall Azure Arc VM management on 22H2 here.

### ISSUE THREAD

**Issue by RodriCoto** [MicrosoftDocs/azure-stack-docs#2902]
Article "Uninstall Azure Arc VM management (preview)" for 22H2 is gone from documentation.

This article had an important note which said:
"Back up any running VMs before you uninstall Arc VM management. Uninstallation also removes these VMs."

Although this is not the case for 23H2, make note for 22H2 can avoid confusion and severe impact of data loss to users that are still in process to uninstall Azure Arc VM management on 22H2.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc3a83f-58e7-b968-b205-e4bb7c1ff0a4
* Version Independent ID: b5b32e37-2d3d-654f-8b36-76192f5a3c68
* Content: [Azure Arc VM management FAQ](https://learn.microsoft.com/en-us/azure-stack/hci/manage/azure-arc-vms-faq#if-i-delete-arc-resource-bridge--are-the-vms-also-deleted-)
* Content Source: [azure-stack/hci/manage/azure-arc-vms-faq.yml](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/azure-arc-vms-faq.yml)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by AjayBathini-MSFT** [comment]
@RodriCoto 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by alkohli** [comment]
#please-close
