### ISSUE TITLE
Best way , syncing the Data between the Azure Stack and Azure Public cloud

### ISSUE THREAD

**Issue by kuttikrishnan** [MicrosoftDocs/azure-stack-docs#2923]
Hi ,

We are having a use case/scenario where we are thinking to use the Azure Stack hub. It will be great if you are able to help us with your comments and suggestions.
Currently we are having an IoT Based system/application running completely in the Azure Public cloud. We also have a couple of App Functions and Azure App services which is used to process and expose the messages and insights, respectively. There are multiple customers for this application and in one of the new customers which we need to onboard have use cases to process the messages from their on-premises environment and they would like to process and view their data with in their on-premises intranet . Also, the same data needs to be the updated in the Azure Public.

Below is the Architectural diagram of the Services and components which we have currently. It will be great if you are able to help us to proceed further on this.

 
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/4919614/7ea01453-61f7-4c0b-82aa-2a20bb410ede)

Thanks and Regards,
Kuttikrishnan.P

**Comment by RamanathanChinnappan-MSFT** [comment]
@kuttikrishnan 
Thanks for sharing the feedback. Since this channel is for driving improvements towards Docs, could you please provide the URL of the specific documentation that your feedback is applicable to? That way, we can make sure your feedback is addressed by the right team.

**Comment by RamanathanChinnappan-MSFT** [comment]
@kuttikrishnan
We are going to close this thread. if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.
