### ISSUE TITLE
*kv.vault.azure.net should be in the allowed public endpoints documentation.

### ISSUE THREAD

**Issue by AgentAnguz** [MicrosoftDocs/azure-stack-docs#2945]
Prior to deploying Azure Stack 23H2 there is a validation process.
If *kv.vault.azure.net is not allowed in outbound ruleset on prem, the validation fails.
*kv.vault.azure.net is not in the list of needed public endpoints in any documentation I've read.

Regards,
Anders.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22d4fc82-62b9-6924-c0c5-605b63e09372
* Version Independent ID: 4abb02f9-e9a3-0e82-0f12-c31bcc77cb06
* Content: [Firewall requirements for Azure Stack HCI - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/firewall-requirements?tabs=allow-json#recommended-firewall-urls)
* Content Source: [azure-stack/hci/concepts/firewall-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/firewall-requirements.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by RamanathanChinnappan-MSFT** [comment]
@AgentAnguz
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by AjayBathini-MSFT** [comment]
@AgentAnguz 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by sethmanheim** [comment]
@AgentAnguz As we are moving to a new feedback system, we have opened corresponding work items and are tracking all open issues in our internal database.  We are closing all public issues, but as mentioned above, there are other ways to provide feedback. Thank you again for reaching out! #please-close
