### ISSUE TITLE
az stack-hci-vm galleryimage create: not a valid command

### ISSUE THREAD

**Issue by matthansen0** [MicrosoftDocs/azure-stack-docs#2946]
The command: ``az stack-hci-vm galleryimage create --subscription $subscription -g $resource_group --extended-location name=$customLocationID type="CustomLocation" --location $location --image-path $galleryImagePath --name $galleryImageName --debug --os-type 'Linux' 
`` does not exist. 

AzCLI docs show you can only use ``galleryimage`` with ``az azurestackhci galleryimage`` or you can use ``az azurestackhci image`` or ``az stack-hci-vm image`` but the command listed in this documentation does not exist. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 650dbefd-7c24-62f7-2810-4b2ec5728db2
* Version Independent ID: 55366ba7-8e6d-6976-065c-3007fe0d61ca
* Content: [Prepare Linux image for Azure Stack HCI VM via Azure CLI - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/manage/virtual-machine-image-linux-sysprep)
* Content Source: [azure-stack/hci/manage/virtual-machine-image-linux-sysprep.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/manage/virtual-machine-image-linux-sysprep.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by RamanathanChinnappan-MSFT** [comment]
@matthansen0 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by alkohli** [comment]
#in-progress Started a thread with engg to confirm the changes. I believe what you are saying is correct @matthansen0. But need to confirm. Thanks!

**Comment by alkohli** [comment]
@matthansen0 PR with changes is merged. The changes will go live at 10 AM publish today. Closing this issue. #please-close
