### ISSUE TITLE
fix screenshot for view public IP address info

### ISSUE THREAD

**Issue by shriramnat** [MicrosoftDocs/azure-stack-docs#295]
the screenshot for viewing public IP info has a raining cloud in it..we should fix this to a better screenshot https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-viewing-public-ip-address-consumption#view-the-public-ip-address-usage-information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5538433-26ef-444d-aed9-7a2676b96f3c
* Version Independent ID: 429ee86d-52a9-0c4b-0756-1473fc59a6a2
* Content: [View public IP address consumption in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-viewing-public-ip-address-consumption#view-the-public-ip-address-usage-information)
* Content Source: [azure-stack/operator/azure-stack-viewing-public-ip-address-consumption.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-viewing-public-ip-address-consumption.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@shriramnat Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@shriramnat Do you happen to have a better screen shot? I can try to generate one from our internal environment, but if you have one handy that'd help. Btw, as an internal MS person you should really be using the private repo, or contacting me internally.

**Comment by mattbriggs** [comment]
@shriramnat Updated with current images from the portal. https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/1291

**Comment by mattbriggs** [comment]
#please-close
