### ISSUE TITLE
Incorrect resource provider commands

### ISSUE THREAD

**Issue by integyjc** [MicrosoftDocs/azure-stack-docs#2951]
Under the pre-req's it states to register several resource providers at the subscription level with the following command:

Register-ResourceProviderIfRequired

I cant see that this command exists and should be register-azresourceprovider

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00d02e07-0813-47ed-69d3-b4d777d07b53
* Version Independent ID: 9a403bb0-bd87-78ea-f987-12b1fe354eb0
* Content: [Register your Azure Stack HCI servers with Azure Arc and assign permissions for deployment - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-arc-register-server-permissions)
* Content Source: [azure-stack/hci/deploy/deployment-arc-register-server-permissions.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-arc-register-server-permissions.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by Naveenommi-MSFT** [comment]
@integyjc 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Naveenommi-MSFT** [comment]
Hi @integyjc

I couldn't locate any mention of the **Register-ResourceProviderIfRequired** command on this page. It seems the document has been updated to include the **Register-AzResourceProvider** command instead. Perhaps this is what you were referring to.

**Comment by alkohli** [comment]
@integyjc These commands were updated. Closing this issue. 
#please-close
