### ISSUE TITLE
directions order needs to be reviewed

### ISSUE THREAD

**Issue by mailOSommer** [MicrosoftDocs/azure-stack-docs#2956]
https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-install-os

Configure networking as per your environment. You can configure the following optional settings:
	• Configure VLAN IDs for the management network. For more information, see [Management VLAN ID](https://learn.microsoft.com/en-us/azure-stack/hci/plan/cloud-deployment-network-considerations#management-vlan-id) and [Management VLAN ID with a virtual switch](https://learn.microsoft.com/en-us/azure-stack/hci/plan/cloud-deployment-network-considerations#management-vlan-id-with-a-virtual-switch).

Aus <https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-install-os> 

Verlinkt auf:
https://learn.microsoft.com/en-us/azure-stack/hci/plan/cloud-deployment-network-considerations#management-vlan-id

u.a.
$IntentName = "MgmtCompute"
New-VMSwitch -Name "ConvergedSwitch($IntentName)" -SwitchType External -NetAdapterName "NIC1","NIC2" -EnableEmbeddedTeaming $true -AllowManagementOS $false

Aber ohne das Hyper-V installiert ist (später im Dokument) 

Also müsste folgende Zeile vorher ausgeführt werden.
Install required Windows roles
	1. Install the Hyper-V role. Run the following command on each server of the cluster:
PowerShellCopy

Enable-WindowsOptionalFeature -Online -FeatureNameMicrosoft-Hyper-V -All
Your servers will restart; this takes a few minutes.

Aus <https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-install-os> 

kann man z.B. noch keine New-VMSwitch ausführen.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4a08887-7331-143b-0c16-95a30680f78e
* Version Independent ID: 31dda2a9-97be-0353-7abd-785d885b1c39
* Content: [Install Azure Stack HCI, version 23H2 operating system - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-install-os)
* Content Source: [azure-stack/hci/deploy/deployment-install-os.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deployment-install-os.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by RamanathanChinnappan-MSFT** [comment]
@mailOSommer
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by alkohli** [comment]
@RamanathanChinnappan-MSFT please assign this issue to me. I have started the work on this one. Thanks!

**Comment by alkohli** [comment]
@mailOSommer We got the issue translated inhouse. We made the change to network considerations for cloud deployment doc and added a link to Install required Windows role (Hyper-V). The change is in this PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/14617 and will be merged soon.

**Comment by alkohli** [comment]
@Naveenommi-MSFT PLease assign this issue to me. So I can merge the PR and mark it as complete.

**Comment by alkohli** [comment]
@mailOSommer The PR is merged and the content will go live today at 10AM publish. Thank you again!

I am closing this issue now. #please-close
