### ISSUE TITLE
Doc out of date 

### ISSUE THREAD

**Issue by GTMer** [MicrosoftDocs/azure-stack-docs#296]
Screenshot in manifest.json is mandatory and its dimensions are '324','533'.
Add-AzsGalleryItem v0.2.0 do not have parameter SubscriptionID.
By the way, we should note customers the path of manifest should also be absolute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e401ae26-588f-124f-09a8-f1f6dc75da4e
* Version Independent ID: 6a9509a1-f16c-f527-5df1-9dae2d8eeaed
* Content: [Create and publish a Marketplace item in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-create-and-publish-marketplace-item#feedback)
* Content Source: [azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by msrini-MSFT** [comment]
@GTMer , Thank you for your feedback. We will take a look and get back to you.

**Comment by TravisCragg-MSFT** [comment]
@GTMer Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@GTMer Thank you for the feedback and sorry for the delay! We will make this change today, and thanks again for catching it. #in-progress

**Comment by sethmanheim** [comment]
@GTMer The changes have been made and should appear live after 10 AM PT. Thank you again for the contribution! #please-close
