### ISSUE TITLE
Indicate which instructions that Windows Server OS should use for SMB/NFS

### ISSUE THREAD

**Issue by eponerine** [MicrosoftDocs/azure-stack-docs#2963]
Despite the fact that these instructions are listed under Azure Stack HCI, they overlap with AKS on Windows Server.

This tab should probably indicate 22H2 and Windows Server (same for the NFS and uninstall tabs below this):

![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/503974/0a98b92b-fe88-405e-b8f1-765a708733fa)

Alternatively, update the Windows Server docs with matching information:
https://learn.microsoft.com/en-us/azure/aks/hybrid/persistent-volume

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 687119fa-7670-bddc-8e08-171bf89b1fc1
* Version Independent ID: 284f2797-f3ec-fa8c-3a23-188988c77d66
* Content: [Use Container Storage Interface (CSI) file drivers in AKS enabled by Azure Arc - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/container-storage-interface-files?tabs=23H2)
* Content Source: [AKS-Hybrid/container-storage-interface-files.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/container-storage-interface-files.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
Hi @eponerine, thanks for reaching out. We added an "applies to" banner at the top of the article that indicates it's supported on 22H2, AKS on Windows Server, and AKS on Azure Stack HCI 23H2.

**Comment by eponerine** [comment]
@sethmanheim - yes, I saw that:

![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/503974/ba8b5d7a-9135-4499-822b-b80cd26d634d)

The problem is that Azure Stack HCI and Windows Server are two completely different operating systems with vastly different methods to install and configure AKS Hybrid, let alone the CSI drivers.

The top **APPLIES TO** stuff is a good start, but the PowerShell code example tabs also need to reflect what OS they are applicable for.
