### ISSUE TITLE
Confirm AKS with Stack HCI on a Single Node for version 23H2 

### ISSUE THREAD

**Issue by sudharsonan** [MicrosoftDocs/azure-stack-docs#2969]
[Enter feedback here]

Hi Team,

Curious to understand the support for 23H2 version for AKS hosted on a single node Stack HCI server. Appreciate if you can confirm and update documentation related to this?

Regards
Sudharson AN
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 620c4a18-9d41-f927-0637-617b23386e31
* Version Independent ID: 05feff69-0405-611c-572b-d3c0cd2f136f
* Content: [Using Azure Stack HCI on a single server - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/concepts/single-server-clusters)
* Content Source: [azure-stack/hci/concepts/single-server-clusters.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/single-server-clusters.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @ronmiab
* Microsoft Alias: **robess**

**Comment by AjayBathini-MSFT** [comment]
@sudharsonan 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by ronmiab** [comment]
@sudharsonan / @AjayBathini-MSFT - I have reviewed the inquiry and will need to get with PMs to verify support for 23H2 version for AKS hosted on a single node Stack HCI server. As soon as I have more information, I will share.

**Comment by sudharsonan** [comment]
any inputs on this?

**Comment by ronmiab** [comment]
Per PM, single node is supported, doc reference: [Scale requirements for AKS on Azure Stack HCI - AKS hybrid | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Faks%2Fhybrid%2Fscale-requirements%23support-count-for-aks-on-hci&data=05%7C02%7CRonmia.Bess%40microsoft.com%7C8a4a1d03b2894d599d3b08dc3e1bf144%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638453536948074121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Y0R%2Fw17vswWk94xwpij8leaJqUYA1b%2BAajqQumuoVBY%3D&reserved=0). However, there hasn't been any determination in terms of updating the doc the customer is referencing to reflect 23H2. I am waiting to hear back on whether or not that doc will change or if there is a better direction to point the customer. As soon as I have more information, I will provide an update.

**Comment by ronmiab** [comment]
@sudharsonan - with the latest response and information, are we able to resolve this issue?

**Comment by ronmiab** [comment]
@sudharsonan - this is a follow-up to the message a couple of months back. I shared content back based on the PMs response. Can I close this PR?

**Comment by ronmiab** [comment]
#please-close
