### ISSUE TITLE
Add more emphasis on adding to availability group

### ISSUE THREAD

**Issue by easyveazie** [MicrosoftDocs/azure-stack-docs#298]
We mention adding to the AG briefly at the bottom of this article but it's easy to overlook. Can we add a couple of steps/screenshots highlighting how to:
- Connect to SQL
- Add the DBs to the availability group
- Perform failover to test

https://docs.microsoft.com/en-us/azure-stack/operator/app-service-deploy-ha

**Comment by YutongTie-MSFT** [comment]
@easyveazie Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by YutongTie-MSFT** [comment]
@BryanLa Hi Bryan, could you please take a look of this issue and update the document as necessary? Thank you.

**Comment by BryanLa** [comment]
@easyveazie - thanks for your feedback. 

I believe the 2nd item (Add the DBs to the availability group) is covered in detail, in the linked SQL article, which provides 3 different ways of adding them along with steps/examples. 

I'm wondering if the 3rd item (Perform failover to test) is covered in the adjacent [Perform a Forced Manual Failover of an Always On Availability Group](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/perform-a-forced-manual-failover-of-an-availability-group-sql-server?view=sql-server-2017) article in the same SQL doc set?

In terms of making this more visible, I could pull that portion of text out of the "Next steps" section, and turn it into it's own section, if that would help? 

I'd also like to get thoughts from @apwestgarth on this request as well.

**Comment by BryanLa** [comment]
@easyveazie - I'll close this for now, but please let me know if you want us to reconsider any of the above. The article you cited was also modified recently FWIW, to add a script link to the 2nd item (to sync login accounts between replica members). 

#please-close
