### ISSUE TITLE
Inconsistent support info for 3-node switchless on 23H2 AS HCI

### ISSUE THREAD

**Issue by wruss** [MicrosoftDocs/azure-stack-docs#2981]
The documentation seems to be inconsistent on support of 3-node switchless running AS HCI 23H2.

The following page within the 'Plan' section mostly states that 3 node switchless deployments are supported using 23H2, so long as they are deployed using ARM Templates -

https://learn.microsoft.com/en-us/azure-stack/hci/plan/cloud-deployment-network-considerations

Example 1 -
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/162985966/14250c93-9b38-4da0-96f5-8aaa55708cf7)

Example 2 -
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/162985966/1a24bbe8-904e-473c-9df4-fb8b0775fb45)

Example 3 -
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/162985966/875712af-4b0e-4eef-b88d-90912c29645d)

But then there is a single image on the same page which contradicts this information -

Example 4 -
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/162985966/bcaef87b-57c4-4634-b8f7-51ab7258e38c)

The following page suggests 3-node switchless is supported, and even provides a diagram to confirm this -

https://learn.microsoft.com/en-us/azure-stack/hci/concepts/physical-network-requirements

Example 5 -
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/162985966/95f0de69-228b-4a37-be42-c81c3337ce84)

And there is another page in the 'Deploy' section which says a 3-node switchless deployment is supported as 'Test only'.

https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deployment-introduction

Example 6 -
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/162985966/30e987c5-c440-4177-ac61-94094a4ce0eb)

This is the only place in the docs I can find 'Test only | No Update or repair support' for 3-node switchless. If it turns out this is correct, then the information needs to be expanded to explain specifically what 'No update or repair support' means, and also needs to be propagated to the 'Plan' section.

In summary - I'm not sure which information is correct with 3-node switchless support on 23H2, but it needs an overhaul to be made both correct and consistent on all the above pages.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a40a2be7-a860-d3c2-8f35-00a7a5adcd54
* Version Independent ID: 6ff69f8c-f227-25cd-d401-6abb0e0ddc9d
* Content: [Network considerations for cloud deployment for Azure Stack HCI, version 23H2 - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/plan/cloud-deployment-network-considerations)
* Content Source: [azure-stack/hci/plan/cloud-deployment-network-considerations.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/plan/cloud-deployment-network-considerations.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @alkohli
* Microsoft Alias: **alkohli**

**Comment by ManoharLakkoju-MSFT** [comment]
@wruss 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ChrisPVella** [comment]
I really need this clarified. 3-node switchless is quite popular and I've been unable to advise clients for several very considerable ASHCI tenders whether it is even supported or not.

**Comment by wruss** [comment]
@alkohli Just wondering if there's a status update on this?

**Comment by alkohli** [comment]
@ChrisPVella  and @wruss Taking a look at this. The 3-node support documentation is already in progress and is coming in soon. We will update all the docs very soon (in next couple weeks). Thanks for your patience!

**Comment by alkohli** [comment]
#in-progress

**Comment by alkohli** [comment]
The changes for this git issue are in this PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/15078

**Comment by alkohli** [comment]
Changes are merged and the docs are live! @wruss @ChrisPVella 
Closing this issue. #please-close

**Comment by Karl-WE** [comment]
Hello @alkohli thank you for resolving these issues with #15078. Can you open the link to the PR mentioned? It fails for me, so I cannot double check them.
