### ISSUE TITLE
certificate creation error

### ISSUE THREAD

**Issue by Stech01** [MicrosoftDocs/azure-stack-docs#30]
hi, I ´ve following the steps to create certificates in my Azure Stack (integrated systems no SDK!!!) however the Get-AzureStackRootCert.ps1 command can´t find the Endpoint I fix it adding the IP and hostname to my hosts file. 
Then I go forward to run the Create-AppServiceCerts.ps1 script  but It fails with errors as follows:

New-SelfSignedCertificate : Cannot bind parameter 'Signer' to the target. Exception setting "Signer": "Value cannot be null.
Parameter name: Signer"
At C:\appservice\Create-AppServiceCerts.ps1:38 char:140
+ ... ocation Cert:\LocalMachine\My -DnsName $DnsName -Signer $root -Provid ...
+                                                             ~~~~~
    + CategoryInfo          : WriteError: (:) [New-SelfSignedCertificate], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.CertificateServices.Commands.NewSelfSignedCertificateCommand
 
So there is another way to create certificates to enable App Services on my Azure Stack?  or there is something that I missed?

regards

S_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b745d67-f3a8-3a4a-5b89-c0e5851ef5e0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Before you deploy App Service on Azure Stack](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-app-service-before-you-get-started#get-certificates)
* Content Source: [articles/azure-stack/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* GitHub Login: @apwestgarth
* Microsoft Alias: **anwestg**

**Comment by apwestgarth** [comment]
Documentation has been significantly update in the last 18 months to restructure based on a number of feedback items. #please-close
