### ISSUE TITLE
Azure Stack HCI Cluster portal deployment Domain error

### ISSUE THREAD

**Issue by f1mosidi** [MicrosoftDocs/azure-stack-docs#3003]
When deploying a cluster from the portal, the domain fails if it has a number in it, see below:
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/163894884/085bf167-bde2-4c3b-97db-921765b2cb8e)

Without a number its succeeds:
![image](https://github.com/MicrosoftDocs/azure-stack-docs/assets/163894884/69057559-7dae-4f0d-8eea-298d729d36ec)

Is this expected behaviour? Active directory domains can have a variety of non routable domain names.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80cd7a2c-6a28-973c-6def-6a5be0132e44
* Version Independent ID: 695bc1f5-5d3f-b667-9ea9-76cffef475a6
* Content: [Deploy an Azure Stack HCI system using the Azure portal - Azure Stack HCI](https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deploy-via-portal)
* Content Source: [azure-stack/hci/deploy/deploy-via-portal.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/deploy/deploy-via-portal.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by ManoharLakkoju-MSFT** [comment]
@f1mosidi 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!

**Comment by Naveenommi-MSFT** [comment]
Hello @f1mosidi 
Actually "Dot" is not considered while deployment. You can use hyphens and alphanumeric characters for that.


<img width="422" alt="image" src="https://github.com/MicrosoftDocs/azure-stack-docs/assets/113576472/36c51b1f-cd40-49c1-a88c-c0191d387d16">


**After adding hyphen and number it will be considered.**

<img width="450" alt="image" src="https://github.com/MicrosoftDocs/azure-stack-docs/assets/113576472/26c2c0e9-ab2d-4c76-9720-fa1cf73b33ba">

**Comment by Naveenommi-MSFT** [comment]
@f1mosidi 
We are going to close this thread as resolved but if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close

**Comment by f1mosidi** [comment]
@ManoharLakkoju-MSFT The deployment process followed is shown here:
https://learn.microsoft.com/en-us/azure-stack/hci/deploy/deploy-via-portal

The actual issue is explained above and in my humble opinion is a bug with the portal

**Comment by f1mosidi** [comment]
@Naveenommi-MSFT Any updates on this ?

**Comment by Naveenommi-MSFT** [comment]
@f1mosidi 
To gain a better understanding of your issue, I'd recommend working closer with our support team via an [Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request). Or you can leverage our Q&A forum by posting your issue there so our community, and MVPs can further assist you in troubleshooting this issue or finding potential workarounds. [Teams Q&A forum](https://docs.microsoft.com/en-us/answers/topics/46488/office-teams-windows-itpro.html) for technical questions about the configuration and administration of Microsoft Teams on Windows.
[Microsoft Teams Community forum](https://answers.microsoft.com/en-us/msteams/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)

**Comment by Naveenommi-MSFT** [comment]
@f1mosidi 
We are going to close this thread, if there are any further questions regarding the documentation, please tag me in your reply and we will be happy to continue the conversation.

#Please-close
