### ISSUE TITLE
Gateway SKU is set to Basic in the script which does not support IKE/IPSec policy

### ISSUE THREAD

**Issue by raluca256** [MicrosoftDocs/azure-stack-docs#301]
Hello,
On the consideration part it is stated: The IPsec/IKE policy only works on the Standard and HighPerformance (route-based) gateway SKUs. 
But the script creates a GWY using Basic SKU: 
New-AzureRmVirtualNetworkGateway -Name $GWName1 -ResourceGroupName $RG1 `
-Location $Location1 -IpConfigurations $gw1ipconf1 -GatewayType Vpn `
-VpnType RouteBased -GatewaySku VpnGw1 &gt;&gt;&gt;&gt;&gt;. Basic SKU! 
Correct command:
New-AzureRmVirtualNetworkGateway -Name $GWName1 -ResourceGroupName $RG1 `
-Location $Location1 -IpConfigurations $gw1ipconf1 -GatewayType Vpn `
-VpnType RouteBased -GatewaySku VpnGw2
Running the command in the article will generate an explicit error.
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d6ea47-e076-e8ca-04b8-caf60a394879
* Version Independent ID: 55f706e5-2200-ec76-9703-f507f029a5bd
* Content: [Configure IPsec/IKE site-to-site VPN connections](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-s2s#feedback)
* Content Source: [azure-stack/user/azure-stack-vpn-s2s.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-vpn-s2s.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by raluca256** [comment]
Please close - I made a confusion between the new and the old SKUs. Looking at the Doc from Azure I see that IKE/IPSec is supported for VpnGw1.

**Comment by TravisCragg-MSFT** [comment]
@raluca256 Thanks for following up! I am glad you were able to resolve your issue.
