### ISSUE TITLE
This Walkthrough doesn't work!

### ISSUE THREAD

**Issue by GammaFour** [MicrosoftDocs/azure-stack-docs#303]
Followed the steps religiously.  Go to the part where you select the Virtual Machine in the publish wizard.  Hit "Browse..."  Selected my new VM from the list.  The wizard spun for a few seconds then said "Could not reach the Web Deploy endpoint on the specified virtual machine".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86a4e4e-a87b-376f-c2c8-dc208f65af24
* Version Independent ID: 3af8893e-2822-1859-de57-6c129ddfeebe
* Content: [Deploy a C# ASP.NET web app to a virtual machine in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-dev-start-howto-vm-dotnet#feedback)
* Content Source: [azure-stack/user/azure-stack-dev-start-howto-vm-dotnet.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-dev-start-howto-vm-dotnet.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@GammaFour I'll double check my instructions as soon as I get a chance. But thanks for leaving this feedback, and I'm glad you tried it out! But sorry it didn't work. I have a few questions about your environments. Are you using an ASDK or Integrated System. And which version are you using? Also, in terms of you dev machine, are able to connect to your Azure Stack, and can you connect to your VM via RDP or SSH? Also, which version of Visual Studio are using? The example is using Visual Studio 2017 template Web app, and it is possible something has changed between 2017 and 2019. Thanks again for leaving your feedback. #in-progress

**Comment by GammaFour** [comment]
I think you left out the Inbound port rule for WebDeploy: 8172.

**Comment by mattbriggs** [comment]
@GammaFour Yes reading my instructions, and I see I have a cut and paste from my Tomcat instructions. You need the inbound port 8172 open in the VM for Web Deploy, as you point out. Not the port that is listed. I'm double-checking, and then when I get it working I'll update. Did you get a deployment in your Azure Stack?

**Comment by GammaFour** [comment]
Yes, the Web Deploy port was the biggest obstacle.  Other than that, it is a very useful reference.  Thanks.

**Comment by mattbriggs** [comment]
Thanks!

#please-close
