### ISSUE TITLE
Data drives: At least 2 disks with a minimum capacity of 500 GB (SSD or HDD).

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#3031]
At https://learn.microsoft.com/en-us/azure-stack/hci/concepts/system-requirements-23h2#server-and-storage-requirements the following statement is made about Data drives: "At least 2 disks with a minimum capacity of 500 GB (SSD or HDD)."  This statement is not accurate, and more detail is required.

- If only 2 disks will be used, they MUST be SSDs.
- If HDDs will be used, a minimum of 4 drives are required - but also additional caching SSDs are required.

**Comment by AjayBathini-MSFT** [comment]
@aricbernard 
Thanks for your feedback! I've assigned this issue to the author who will investigate and update as appropriate.

**Comment by alkohli** [comment]
@aricbernard thank you for your patience! Taking a look at this issue. 
#in-progress
