### ISSUE TITLE
Offline marketplace download tool

### ISSUE THREAD

**Issue by jah29m** [MicrosoftDocs/azure-stack-docs#309]
The disconnected/offline marketplace download tool seems to fail often when downloading the large (130GB) windows images. I've tried downloading from multiple locations, multiple machines and types of images, and they all have failed at one time or another. I have managed to pull down 3 images in the past week...while trying about 40 times.

**Comment by YutongTie-MSFT** [comment]
@jah29m Hi John, could you please share more details about which document you are referring to? Thank you.

**Comment by YutongTie-MSFT** [comment]
@jah29m 
We will now proceed to close this thread. If there are further questions regarding this matter, please respond here and @YutongTie-MSFT and we will gladly continue the discussion.
