### ISSUE TITLE
Why does Set-AksHCIRegistration remove tags from the resource group?

### ISSUE THREAD

**Issue by anwather** [MicrosoftDocs/azure-stack-docs#3097]
Noticed when running this is removed the tags from the resource group? Is there any reason to do this as we have policies in place to deny creation of a resource group without tags attached, 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37e3139e-399b-be0f-d80e-d78b094b214a
* Version Independent ID: f18262fc-0401-68d0-964a-ee4e19be10e0
* Content: [Use PowerShell to set up Kubernetes on Azure Stack HCI and Windows Server clusters - AKS hybrid](https://learn.microsoft.com/en-us/azure/aks/hybrid/kubernetes-walkthrough-powershell#step-4-sign-in-to-azure-and-configure-registration-settings)
* Content Source: [AKS-Hybrid/kubernetes-walkthrough-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/AKS-Hybrid/kubernetes-walkthrough-powershell.md)
* Service: **azure-stack**
* Sub-service: **aks-hci**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by PesalaPavan** [comment]
@anwather 
It would be great if you could add a link to the documentation you are following for these steps? This would help us redirect the issue to the appropriate team. Thanks!!

**Comment by anwather** [comment]
https://learn.microsoft.com/en-us/azure/aks/hybrid/kubernetes-walkthrough-powershell#step-4-sign-in-to-azure-and-configure-registration-settings

**Comment by Naveenommi-MSFT** [comment]
@anwather 
Thank you for bringing this to our attention.
I've delegated this to content author @sethmanheim, who will review it and offer their insightful opinions.

**Comment by Naveenommi-MSFT** [comment]
@sethmanheim
Could you please review add comments on this, update as appropriate.

**Comment by sethmanheim** [comment]
@anwather Thank you for reaching out. I am not seeing the issue you mention. However, as we are moving to a new content feedback system, we have opened corresponding work items and are tracking all open issues in our internal database.  We are closing all public issues, but as mentioned above, there are other ways to provide feedback. #please-close
