### ISSUE TITLE
Outbound DNS

### ISSUE THREAD

**Issue by AzureStacker** [MicrosoftDocs/azure-stack-docs#31]
Hi,

My understanding is that OUTBOUND DNS is required for initial deployment only, and not for day-to-day operation.  It states as much in the DNS integration section earlier in this document.  Could this be clarified as some customers want to keep their public ports as locked down as possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bf65509-158a-6ae7-60f0-586170fab6af
* Version Independent ID: 18f15ad2-ef9b-f883-c49b-09289a2e6fb8
* Content: [Azure Stack datacenter integration - Publish endpoints](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-integrate-endpoints)
* Content Source: [articles/azure-stack/azure-stack-integrate-endpoints.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-endpoints.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by mattbriggs** [comment]
@AzureStacker clarification has been added. I've updated the doc as well. Thanks! #please-close

**Comment by mattbriggs** [comment]
#please-close
