### ISSUE TITLE
Add important details about accounts used for update deployments

### ISSUE THREAD

**Issue by christophkarner** [MicrosoftDocs/azure-stack-docs#312]
Hi, in my opinion information falls short regarding account prerequisites. I found the following with some trial & error:

1. **The account used for running the updatesqlprovider.ps1 script does need local administrative rights**. It does not suffice to use an regular non-administrative user, then elevate the powershell using a different (now local administrative) user. The BITS transfer invoked by the subroutine script "Download-File.ps1" will fail (a BITS quirk).
2. **No details about the Azure Stack Service User** (i.e. an AAD tenant user if using AAD identity management for Azure Stack). It appears to require **owner** rights on the Azure subscription (and Azure Stack Default Provider Subscription). It looks like Contributor rights are not enough?

Please validate my findings or correct them if I'm mislead. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7036dfa7-b02a-2a1f-5f25-7d1b9f5bd548
* Version Independent ID: d138b9d0-0717-28f2-71a9-ec2380ddeece
* Content: [Updating the Azure Stack SQL resource provider](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-update)
* Content Source: [azure-stack/operator/azure-stack-sql-resource-provider-update.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-sql-resource-provider-update.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@christophkarner Thanks for providing these notes. We are in the process of updating the Azure Stack update notes (at least of Azure Stack itself rather than the RPs.) I will touch base with the technical owner for this content, and update. I think with number #1, we probably assumed you would run the PowerShell command line with Admin rights. I agree we should make this explicit. #2 Yes this is correct; Contributor rights tend to be for a user, and only an operator would be installing the RP. I'll follow up to find out the correct/lowest permission service account with the necessary permissions to use. #in-progress

**Comment by christophkarner** [comment]
@mattbriggs Thanks for your quick response. The powershell is elevated and run with administrative rights of a user different from the logged on Windows account. I think the salient point is we must not use **_different_** accounts, because BITS transfer will fail. See also [BITS job suspended when started under elevated PS instance](https://social.technet.microsoft.com/Forums/windowsserver/en-US/1464860b-db04-4e2e-8788-b789c6649e5b/bits-job-suspended-when-started-under-elevated-ps-instance?forum=winserverpowershell). Maybe we could drop BITS and use azcopy instead?

**Comment by mattbriggs** [comment]
@christophkarner I'm passing our feedback to the product team. Thanks, Matt #in-progress

**Comment by mattbriggs** [comment]
Updated topic with clarifying permissions for the account running the script.

#please-close
