### ISSUE TITLE
Dual Link / NIC redundancy in network considerations

### ISSUE THREAD

**Issue by Karl-WE** [MicrosoftDocs/azure-stack-docs#3134]
Dear @alkohli @dansisson @dansisson @AArnott @krukow 

in reference to the new updated pictures of #3120 
may I kindly request an update on this? 

It would be most helpful to outline in the 23H2 docs that customers
- when fully converged (Compute+Storage+Mgmt) AND EVERY other supported scenario where and customers using 2 TOR switches, we should also consequently lookout for NIC link redundancy. 
This should be clear recommendation in the docs.

It is not that we must have this principle but mark it as recommended and shown in pictures. people doing networking are rarely the same team that understand the requirements of Azure Stack HCI / Hardware at the other end of the switch.

Currently the pictures are often misinterpreted as if one NIC has just one NIC port, where in reality we are often using Dual Port NICs and using 
- Link 1 SMB 1 on NIC 1 P1, NetATC VLAN 711*
- Link 2 SMB 1 on NIC 2 P1 NetATC VLAN 711**
- Link 3 SMB 2 on NIC 1 P2 NetATC VLAN 712**
- Link 4 SMB 2 on NIC 2 P2 NetATC VLAN 712**

Thank you for your follow-up on this. NIC Link redundancy help to prevent SPOF on NIC level, which can easily happen. If one NIC has issues with 2 Ports (e.g. FW or Driver) both ports go down the same time!
This is also a consent within the community. So, I kindly request to modify the text and graphics, despite higher complexity to show these scenarios and not assume that a single link could also represent a dual link. Thank you very much

**Comment by PesalaPavan** [comment]
@Karl-WE 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by Karl-WE** [comment]
added NetATC VLAN for better understanding.

**Comment by AjayBathini-MSFT** [comment]
@alkohli 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by alkohli** [comment]
@Karl-WE Thank you for your contribution! Taking a look at this issue. #in-progress

**Comment by sethmanheim** [comment]
@Karl-WE As we are moving to a new content feedback system, we have opened corresponding work items and are tracking all open issues in our internal database.  We are closing all public issues, but as mentioned above, there are other ways to provide feedback. Thank you again for reaching out! #please-close
