### ISSUE TITLE
Setting enforce TLS 1.2 to True has failed

### ISSUE THREAD

**Issue by LinoRS** [MicrosoftDocs/azure-stack-docs#316]
VERBOSE: Setting enforce TLS 1.2 to True has failed with exception Method invocation failed because [System.Xml.XPathNodeList] does not contain a method named 'SetAttribute'.
VERBOSE: Enforcing TLS 1.2 has raised an exception: Method invocation failed because [System.Xml.XPathNodeList] does not contain a method named 'SetAttribute'.
VERBOSE: Verifying TLS policy
VERBOSE: Get GPO TLS protocols registry 'enabled' values
VERBOSE: GPO TLS applied with the following preferences:
VERBOSE:     TLS protocol SSL 2.0 enabled value: 0
VERBOSE:     TLS protocol SSL 3.0 enabled value: 0
VERBOSE:     TLS protocol TLS 1.0 enabled value: 1
VERBOSE:     TLS protocol TLS 1.1 enabled value: 1
VERBOSE:     TLS protocol TLS 1.2 enabled value: 1
VERBOSE: TLS 1.2 is not enforced
VERBOSE: Restoring TLS policy ECE info. Setting TLS policy back to TLS_All
VERBOSE: Setting enforce TLS 1.2 to False has failed with exception Method invocation failed because [System.Xml.XPathNodeList] does not contain a method named 'SetAttribute'.

Any ideas... or raise a support request with MS ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a6c4029-7e45-9b19-db5c-76311d37ae76
* Version Independent ID: 831086f5-f1ad-7fb8-fdc4-de9929c8b6fa
* Content: [Configure Azure Stack security controls](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-security-configuration#feedback)
* Content Source: [azure-stack/operator/azure-stack-security-configuration.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-security-configuration.md)
* Service: **azure-stack**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by TravisCragg-MSFT** [comment]
@LinoRS Make sure that your Azure PowerShell and Azure Stack are up to date with the latest patch and try again. If that does not work and you are doing this on an Azure Stack Integrated System (Not the ASDK), your best bet is to go through support.

**Comment by LinoRS** [comment]
@TravisCragg-MSFT, thank you.... i have used HLH and connected to PEP from my local PC, Same error occurs, 
Azure Stack is on version 1906, which is supported in doing this in this version.
Powershell is using  version "Script     2.5.0      AzureRM" / "Script     1.7.2      AzureStack"  thanks.... so might then log a call to support to see whats going on.

**Comment by TravisCragg-MSFT** [comment]
@LinoRS We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

If you get the chance, please update this thread with the resolution.

**Comment by LinoRS** [comment]
MS has identified this as a bug and they now also know the cause. Seem PG is currently working on the mitigation.

**Comment by LinoRS** [comment]
So Steps from MS
If you an early adopter and have upgraded Stack the issue came from other builds, however if you just installed stack and on build 1904 and upgrade to 1906 you will be fine. In my case not. So you need to break glass with MS, then Run the following mitigation:
Import-Module -Name ECEClient -Verbose:$false -DisableNameChecking
$eceClient = Create-ECEClientWithServiceResolver
$eceXml = [XML]($eceClient.GetCloudParameters().getAwaiter().GetResult().CloudDefinitionAsXmlString)
$tls12EnforcedNode = $eceXml.SelectNodes("//Parameter[@Name='TLS12Enforced']")
if (($null -eq $tls12EnforcedNode) -or ($tls12EnforcedNode.Count -eq 0))
{
    Write-Verbose -Verbose "Persistent reference TLS12Enforced is not present, creating it"
    $domainCategory = $eceXml.SelectSingleNode("//Category[@Name='Domain']")
    $tls12ParamNode = $eceXml.CreateElement("Parameter")
    $tls12ParamNode.SetAttribute("Name", "TLS12Enforced")
    $tls12ParamNode.SetAttribute("Type", "bool")
    $tls12ParamNode.SetAttribute("Value", $false)
    $tls12ParamNode.SetAttribute("AllowedValues", "")
    $tls12ParamNode.SetAttribute("Reference", "[{TLS12Enforced}]")
    $domainCategory.AppendChild($tls12ParamNode) | Out-Null

    $eceCloudParametersDefinition = New-Object Microsoft.AzureStack.Solution.Deploy.EnterpriseCloudEngine.Controllers.Models.CloudDefinitionDescription
    $eceCloudParametersDefinition.ConfigurationName = 'AzureStack'
    $eceCloudParametersDefinition.CloudDefinitionAsXmlString = $eceXml.OuterXml
    $null = $eceClient.ImportCloudParameters($eceCloudParametersDefinition).GetAwaiter().GetResult()
    Write-Verbose -Verbose "Persistent reference TLS12Enforced is now created"
} 

Then once done, close your Admin session.
and you should now be able to run the Set-TLSPolicy -Version TLS_1.2... has worked for me.

So anyone that is having the same issue, hope this helps you.

thanks
