### ISSUE TITLE
incomplete listing for allowing incoming connections for tenant VPN Gateways

### ISSUE THREAD

**Issue by jecarlsen** [MicrosoftDocs/azure-stack-docs#32]
Assuming you follow this page (important goto-place) for configuring FW you won't be able to connect a Azure VPN to the Azure Stack VPN. 
It is listed in the FAQ for VPN though, but I strongly belive this page should include such important information when we use this page for planning.

Ref:
•	https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-vpn-faq 
o	IKEv2 VPN. IKEv2 VPN is a standards-based IPsec VPN solution that uses UDP port 500 and 4500 and IP protocol no. 50. Firewalls do not always open these ports, so there is a possibility of IKEv2 VPN not being able to traverse proxies and firewalls.

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 4bf65509-158a-6ae7-60f0-586170fab6af
* Version Independent ID: 18f15ad2-ef9b-f883-c49b-09289a2e6fb8
* Content: [Azure Stack datacenter integration - Publish endpoints](https://docs.microsoft.com/nb-no/azure/azure-stack/azure-stack-integrate-endpoints#ports-and-protocols-inbound)
* Content Source: [articles/azure-stack/azure-stack-integrate-endpoints.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-endpoints.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by mattbriggs** [comment]
@jecarlsen  I've added the VPN note to the page. #please-close

**Comment by mattbriggs** [comment]
#please-close
