### ISSUE TITLE
No Hyperlink in Volumes section

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-stack-docs#330]
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-storage-infrastructure-overview#volumes

There is paragraph : "Mirroring provides fault tolerance by keeping multiple copies of all data. How that data is striped and placed is non-trivial (see this blog to learn more)", but there is no hyperlink leads to this blog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 005ba5b3-3e9b-363a-5bfd-e0d94091e23f
* Version Independent ID: 5c37bc70-106f-792a-f682-4c4fd714830e
* Content: [Manage storage infrastructure for Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-storage-infrastructure-overview#feedback)
* Content Source: [azure-stack/operator/azure-stack-storage-infrastructure-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-storage-infrastructure-overview.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SubhashVasarapu-MSFT** [comment]
@HassanAlmanasrah , We have assigned this issue to the content author for updating the document accordingly. @mattbriggs , Could you please provide your insights on this ?

**Comment by TravisCragg-MSFT** [comment]
@HassanAlmanasrah We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
