### ISSUE TITLE
Improve documentation for FQDN in cluster certificate section

### ISSUE THREAD

**Issue by easyveazie** [MicrosoftDocs/azure-stack-docs#338]
It would be helpful to describe what the FQDN for the SF cluster will look like prior to requesting certificates. 

Here's a good example:
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started#default-domain-certificate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80a333ac-8208-4146-2d99-6b6258b64a3f
* Version Independent ID: 30341430-ba3a-ae9e-5599-5ed618e9213a
* Content: [Deploy a secured Service Fabric cluster in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-template-service-fabric-cluster)
* Content Source: [azure-stack/user/azure-stack-solution-template-service-fabric-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-solution-template-service-fabric-cluster.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by DiegoRamirez-MSFT** [comment]
Hello @easyveazie 

thanks for reaching out and sharing your feedback, will take a look an update you as soon as possible

best

**Comment by DiegoRamirez-MSFT** [comment]
@mattbriggs can you please take a look and let us know your thoughts?

**Comment by mattbriggs** [comment]
@easyveazie We reference the Azure docs where we can in the Azure Stack docs. In this case, we point to the cert reqs in Azure which spells out the format for the FDQN. Thanks for your feedback.

#please-close
