### ISSUE TITLE
Outdated Screenshot for Secrets

### ISSUE THREAD

**Issue by easyveazie** [MicrosoftDocs/azure-stack-docs#344]
The Security screenshot on this article does not match what the ARM template is asking for. 

The template is also asking for:
Server Certificate Url
Server Certificate Thumbprint
Admin Client Certificate Thumbprint
Non-Admin Client Certificate Thumbprint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80a333ac-8208-4146-2d99-6b6258b64a3f
* Version Independent ID: 30341430-ba3a-ae9e-5599-5ed618e9213a
* Content: [Deploy a secured Service Fabric cluster in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-template-service-fabric-cluster)
* Content Source: [azure-stack/user/azure-stack-solution-template-service-fabric-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-solution-template-service-fabric-cluster.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by BryanTrach-MSFT** [comment]
@easyveazie Thanks for the feedback! I have assigned the issue to the content author to investigate further and update the document as appropriate.

**Comment by mattbriggs** [comment]
@easyveazie  Thanks for your feedback. I've updated the security screen shot.

#please-close
