### ISSUE TITLE
SERVICEFABRICURL does not work in disconnected environments

### ISSUE THREAD

**Issue by easyveazie** [MicrosoftDocs/azure-stack-docs#346]
The default url for the runtime download is here:
http://go.microsoft.com/fwlink/?LinkId=730690

If a customer is in a disconnected environment, how can they install this? Are they able to put the runtime on a storage account on their disconnected Azure Stack instance and point to it somehow? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80a333ac-8208-4146-2d99-6b6258b64a3f
* Version Independent ID: 30341430-ba3a-ae9e-5599-5ed618e9213a
* Content: [Deploy a secured Service Fabric cluster in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-template-service-fabric-cluster)
* Content Source: [azure-stack/user/azure-stack-solution-template-service-fabric-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-solution-template-service-fabric-cluster.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by BryanTrach-MSFT** [comment]
@easyveazie Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by msrini-MSFT** [comment]
@mattbriggs , can you take a look at this issue?

**Comment by mattbriggs** [comment]
@easyveazie Thanks for your question. The Azure Stack Operator would download the RP to make it available in the disconnected Azure Stack. Here is the topic about this: https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-download-azure-marketplace-item

However, in this topic are pointing to instructions for the Azure Stack user who would not have the permissions to add an RP to Azure Stack. We have two main classes of users who use Azure Stack. The user, who typically develops solutions, and the Azure Stack operator, who maintains Azure Stack and sets up services and offerings. The operator role is different than any role you would find Azure. The two users interact with Azure Stack in different portals: The Azure Stack administrative portal for operators, and the Azure Stack user portal for users. I hope this helps.

**Comment by mattbriggs** [comment]
#please-close

**Comment by TravisCragg-MSFT** [comment]
@alexsmithMSFT @mattbriggs I reopened the issue.

**Comment by mattbriggs** [comment]
@alexsmithMSFT Thanks! #please-close
