### ISSUE TITLE
FIPS 140-2 clarification

### ISSUE THREAD

**Issue by jgallucci32** [MicrosoftDocs/azure-stack-docs#357]
The update states "All components of Azure Stack infrastructure now operate in FIPS 140-2 mode". Does this mean Bitlocker is now configured to use AES 256-bit encryption for data at rest? Previous releases of Azure Stack only used 128-bit encryption for data at rest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53773d84-b521-0441-3393-4fe6156c5951
* Version Independent ID: de7bbe31-85c5-37a5-1bf8-1664bf56e5f9
* Content: [Azure Stack 1908 release notes](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-release-notes-1908?view=azs-1908#feedback)
* Content Source: [azure-stack/operator/azure-stack-release-notes-1908.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-release-notes-1908.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@jgallucci32 Thanks for the feedback. We are actively investigating and will get back to you soon.

**Comment by TravisCragg-MSFT** [comment]
@jgallucci32 Bitlocker on Azure Stack still uses an AES 128 key to encrypt disk volumes. 

FIPS mode forces the OS to use approved crypto modules/algorithm for communication. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
