### ISSUE TITLE
Cannot connect to https://management.local.azurestack/external

### ISSUE THREAD

**Issue by duncanspeidel** [MicrosoftDocs/azure-stack-docs#364]
Hi,

The page shows https://management.local.azurestack/external as a valid URL but neither Visual Studio nor the browser can find it.   When the page shows https://management.[Region}.[External FQDN], how do I determine which region to use?

Thank you,
Duncan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dc1af34-ba5b-5aed-4270-7734c4bf3960
* Version Independent ID: 49b45f6c-5c71-af49-3e6a-1bc88b8947bc
* Content: [Install Visual Studio and connect to Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-install-visual-studio?view=azs-1908)
* Content Source: [azure-stack/user/azure-stack-install-visual-studio.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-install-visual-studio.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@duncanspeidel Are you using the ASDK or a full Azure Stack multi-node deployment? for the ASDK, the ARM Endpoint is management.local.azurestack/external, [but you will need to either be on the ASDK machine, or connected to it via a VPN](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-connect?view=azs-1908).

**Comment by duncanspeidel** [comment]
I see the connection now, you can close the issue.

**Comment by TravisCragg-MSFT** [comment]
@duncanspeidel We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
