### ISSUE TITLE
AppService Resource Provider with the latest ASDK 1908

### ISSUE THREAD

**Issue by rfsonders** [MicrosoftDocs/azure-stack-docs#369]
Hello.
Is the latest App Service Installer compatible with the latest ASDK 1908.0.20 build?
I have downloaded the latest App Service installer from here
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-update?view=azs-1908
When I run appservice.exe as admin, the app never starts. No logs are provided.
Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05a15b1c-daa5-6d35-35a5-7c40b8ba89e8
* Version Independent ID: 7565c3cb-e379-14f5-ccf3-5bd3bbbcb3df
* Content: [Update Azure App Service on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-update?view=azs-1908#feedback)
* Content Source: [azure-stack/operator/azure-stack-app-service-update.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-update.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by AjayKumar-MSFT** [comment]
@rfsonders, Thanks for posting the question! As mentioned in the document note "deploy the latest Azure Stack Development Kit (ASDK) before deploying Azure App Service 1.7.", so, it should typically work on the latest ASDK version. I was able to start the installation process locally (as a test), so, you may try re-downloading the App Service Installer again and then re-try while we check on this further. 
![image](https://user-images.githubusercontent.com/44606227/64912722-bd9c3f80-d750-11e9-9a83-c0820bf21b59.png)

**Comment by TravisCragg-MSFT** [comment]
@rfsonders I verified that 1908 is compatible with the current version of the App Service RP. If you are having issues installing, try running appservice.exe programatically with the following parameters:

`appservice.exe /log log.txt`

If this fails to run or produce any logs, go ahead and [stop the ASDK, reboot the host computer, and then start the ASDK](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-start-stop?view=azs-1908) and try to install the app service again.

**Comment by rfsonders** [comment]
Hello @TravisCragg-MSFT 
Starting the app programmatically was successful. Thank you.
