### ISSUE TITLE
How to request access token using enterprise SSO

### ISSUE THREAD

**Issue by jfnu** [MicrosoftDocs/azure-stack-docs#376]
Hi 
My company is using enterprise SSO with pin and token to login to the azure stack tenant portal. How to request access token this way? I'm aware of using service principal to access it. However, tenant will still need to give the permission to the service principal first. Is there any other way? Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2f49e9-8b48-9023-11ea-db3bc03da21b
* Version Independent ID: 9dab4ae8-692e-5d63-e6fc-7d173cf98084
* Content: [Make API requests to Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-rest-api-use?view=azs-1908)
* Content Source: [azure-stack/user/azure-stack-rest-api-use.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-rest-api-use.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for your question. Please provide us with the link to the documentation you are referring to so we can better assist.

**Comment by jfnu** [comment]
Hi Karishma,

 here is the doc if you want to request access token to azure stack api using AAD account
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-rest-api-use?view=azs-1908

here is the doc if you want to request access token to azure stack api using service principal
https://blogs.msdn.microsoft.com/wushuai/2018/10/02/how-to-call-azure-stack-api-via-client-credential-grant/

what's missing is (if possible) how to request access token to azure stack api using enterprise SSO

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for sharing the documents. I have updated the issue with doc details. 
Our team is currently investigating and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@jfnu If you are doing an AAD installation, you should be able to use a typical AAD Auth flow to get the token for API access. [Here is AAD documentation describing the process](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code). 

If this is about a full Azure Stack multi-node installation and not the ASDK, your best bet is to create a support request if you need further assistance.

**Comment by jfnu** [comment]
Hi Travis,

   That's not the ask though. The documentation seems to be missing "How-To" on getting access token on azure stack API via Enterprise SSO. If it's not possible, that's fine. I wanted to know if there's a way and if  it's not, what would be the recommendation. 

    Thank you
