### ISSUE TITLE
Storage Explorer not available in Azure Government

### ISSUE THREAD

**Issue by jgallucci32** [MicrosoftDocs/azure-stack-docs#387]
Storage explorer is not available in Azure Government so you cannot obtain a SAS URI using the method described in the instructions. As far as I can tell, you can only get a SAS URI from the portal at the Storage Account level, and not at the specific container. In order to get a proper SAS URI we had to get it from the portal and then append the specific container to the URI.

Wanted to point this out to see if there is a better way to do this or to have this at least noted somewhere in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 018f9564-f0cc-bc8b-7e22-b02243f3ca5f
* Version Independent ID: a5b8f334-717a-6237-44d2-f94bf84c654c
* Content: [Configure automatic Azure Stack log collection](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-configure-automatic-diagnostic-log-collection?view=azs-1908)
* Content Source: [azure-stack/operator/azure-stack-configure-automatic-diagnostic-log-collection.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-configure-automatic-diagnostic-log-collection.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by Justinha** [comment]
@jgallucci32 Thanks for the feedback. I'm sharing with our engineering partners and will follow up.

**Comment by Justinha** [comment]
@jgallucci32 @TravisCragg-MSFT with the 2002 release, we no longer require using Storage Explorer. I think we can close this as a result.

**Comment by jgallucci32** [comment]
@Justinha In the context of Azure Stack yes this may be closed. The underlying issue still exists where Azure Government users cannot easily get the SAS URI of a container and must manually construct it based on the storage account info. That is a minor problem though.

**Comment by mattbriggs** [comment]
@sethmanheim

**Comment by sethmanheim** [comment]
#please-close
