### ISSUE TITLE
The Build pipeline screens are completely differemt.

### ISSUE THREAD

**Issue by kprpg** [MicrosoftDocs/azure-stack-docs#391]
The Pipeline section screenshots don't match with the new default YAML based build. Please show the default YAML screen shots. Also how does one change the Agent pool to the one running on the AzureStack host. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e54ed0-e139-1569-adc8-1833de468eb9
* Version Independent ID: 0b03d258-e1ee-e59b-997f-e9096c6f53e2
* Content: [Deploy apps to Azure and Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-pipeline?view=azs-1908#prerequisites)
* Content Source: [azure-stack/user/azure-stack-solution-pipeline.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-solution-pipeline.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by TravisCragg-MSFT** [comment]
@kprpg Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by BryanLa** [comment]
Thanks for your feedback, @kprpg. I'm looking into this. I'll add another comment as soon as we resolve..

**Comment by v-thepet** [comment]
@kprpg - Can you access and review these proposed changes: https://review.docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-pipeline?view=azs-1802&branch=pr-en-us-1446#create-a-build-pipeline-and-run-a-build, and see whether it fits with your experience and expectations?
You can also select "Show assistant" to the right of the YAML, which opens a form that helps you add tasks and steps. Do you think it would be more useful to show that process, or just give the code as now? 
Note that if you have the Preview "multi-stage pipeline" experience turned on, things will look and act different. We won't document that until it becomes the default.
Currently, it's also possible to write Release pipelines in YAML, but that isn't the default experience, so I've left that section mostly as is with a few small updates. 
Thanks very much for providing your opinion on these changes if you can. @BryanLa FYI.

**Comment by v-thepet** [comment]
@kprpg - The build pipeline changes are in PR https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/1446. Please take a look and let us know if anything more is needed. Thanks. @BryanLa FYI.

**Comment by BryanLa** [comment]
Thanks @v-thepet.
@kprpg - when you get a chance, please let us know if this resolves the doc issue you cited.
@TravisCragg-MSFT - I believe this one can be closed now, unless the "how does one change the Agent pool to the one running on the AzureStack host" question is still outstanding.

**Comment by BryanLa** [comment]
#please-close
