### ISSUE TITLE
Your screenshot doesn't match your sample

### ISSUE THREAD

**Issue by nateforsyth** [MicrosoftDocs/azure-stack-docs#397]
Your screenshot doesn't match your sample, should probably update this article.

```xml
  <appSettings>
    <!-- Update these settings for your test environment -->
    <add key="VaultUrl" value="URL to your Vault" />
    <add key="AuthClientId" value="Client Id of your Service Principal" />
    <add key="AuthCertThumbprint" value="Thumbprint of the certificate used for authentication" />
    <add key="TracingEnabled" value="false" />
  </appSettings>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19456c4d-d3ad-7490-16d9-be2662fb13a1
* Version Independent ID: e2314a70-1614-9d79-95a5-d4e303cc8424
* Content: [Allow apps to access Azure Stack Key Vault secrets](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-key-vault-sample-app?view=azs-1908#feedback)
* Content Source: [azure-stack/user/azure-stack-key-vault-sample-app.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-key-vault-sample-app.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@nateforsyth Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@nateforsyth Thank you for the feedback and sorry for the delay. I have just submitted a PR to update the sample code in the article. #please-close
