### ISSUE TITLE
"for example Update-1811" should be lower case.

### ISSUE THREAD

**Issue by mattu0119** [MicrosoftDocs/azure-stack-docs#40]
Container name does not accept upper case, so that example should be lower case on step 4.

 "Under Blob service, select + Container to create a container. Enter a name (for example Update-1811), and then select OK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1fb775-13ec-28b6-060d-af8f601d18c0
* Version Independent ID: 6225e89d-4bc4-8232-34ae-b479ded1a1b0
* Content: [Apply updates in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-apply-updates)
* Content Source: [azure-stack/operator/azure-stack-apply-updates.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-apply-updates.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
fixed (https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/100) #please-close

**Comment by TravisCragg-MSFT** [comment]
@mattu0119 Thanks for catching this!

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
