### ISSUE TITLE
AdminRsourceManagerEdpoint is not clearly given

### ISSUE THREAD

**Issue by kprpg** [MicrosoftDocs/azure-stack-docs#411]
What is the value for AdminRsourceManagerEdpoint? This is a basic thing - Please give a sample for running the PowerShell commands with the "sample" values for the parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d8803f5-7736-6a29-98df-69c121d43c95
* Version Independent ID: d88f693f-cade-48ee-df03-d2363298ef0d
* Content: [Connect to Azure Stack using Azure Account Extension in Visual Studio Code](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-dev-start-vscode-azure?view=azs-1908)
* Content Source: [azure-stack/user/azure-stack-dev-start-vscode-azure.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-dev-start-vscode-azure.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@kprpg Thanks for the feedback! You can [find more information about Azure Stack Endpoints Here](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-endpoints?view=azs-1908#ports-and-protocols-inbound). This endpoint is also talked about in step 7 below. 

I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@ kprpg I just wanted to make sure I understand your question. The topic you are referencing is for developers on Azure Stack interacting with the Azure Stack Resource Manager working with resource providers such as computer, storage, and so on.

However, you are looking to use the Azure Account Extension in Visual Studio Code to work with the Admin endpoints and perform operations such as Scale Unit Nodes, Alerts, Updates, Backup, Marketplace, Subscriptions, Offers?

For the ASDK this endpoint is: adminmanagement.local.azurestack.external. 

- Are you working with a multinode? Do you need to know how to create the URL?
- Can you let me know about the tasks you would like to perform using Azure Account Extension in Visual Studio Code as an operator?

I am not sure how applicable this topic is to use case, and can forward your information to engineering to get more information when I have it.

#in-progress

**Comment by mattbriggs** [comment]
#please-close
