### ISSUE TITLE
How to configure Azcopy to point to Azure stack endpoint

### ISSUE THREAD

**Issue by ooteniya** [MicrosoftDocs/azure-stack-docs#423]
There is no documentations on how to setup the azcopy (v10) to authenticate with Azurestack Endpoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3a78588-520c-9787-dadc-7ae66cfa2ed4
* Version Independent ID: 5f2c2e9d-84f8-82d2-b20e-608679c3c7bd
* Content: [Use data transfer tools in Azure Stack Storage](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-storage-transfer?view=azs-1908#feedback)
* Content Source: [azure-stack/user/azure-stack-storage-transfer.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-storage-transfer.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@ooteniya Thanks for your feedback. I see that we have general instructions for using azcopy with storage: https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-storage-transfer?view=azs-1908#download-all-blobs-to-a-local-disk. By Azure stack endpoint, do you mean the storage URL for a container?

#in-progress

**Comment by ooteniya** [comment]
@mattbriggs  I mean to use the azcopy login command https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#choose-how-youll-provide-authorization-credentials  

How do i make it work for Azure stack? Is there a place to specify the azurestack endpoint to login with?

**Comment by TravisCragg-MSFT** [comment]
@ooteniya There are 2 ways to authenticate to a storage account using AzCopy - SAS or AAD. AAD Authentication is fairly new for AzCopy, and I am not sure if that is supported by Azure Stack at this time. Your best bet will be to use SAS using the instructions provided by @mattbriggs .

**Comment by TravisCragg-MSFT** [comment]
@ooteniya Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
