### ISSUE TITLE
The command to unregister needs updating

### ISSUE THREAD

**Issue by frehnejc** [MicrosoftDocs/azure-stack-docs#427]
the command to de-register needs an extra parameter:
Remove-AzsRegistration `
   -PrivilegedEndpointCredential $CloudAdminCred `
   -PrivilegedEndpoint AzS-ERCS01
  -RegistrationName $RegistrationName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3bed670-b412-74b4-f2ea-48023250a718
* Version Independent ID: 109c728d-522d-71d1-04cf-146624e5e4e2
* Content: [Redeploy the ASDK](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-redeploy?view=azs-1908)
* Content Source: [azure-stack/asdk/asdk-redeploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-redeploy.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by himanshusinha-msft** [comment]
@frehnejc .Thanks for the feedback . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by TravisCragg-MSFT** [comment]
@frehnejc Thanks for the feedback! I confirmed that the -RegistrationName parameter is required. 

I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by myoungerman** [comment]
@TravisCragg-MSFT I have fixed this, thanks!

**Comment by TravisCragg-MSFT** [comment]
@frehnejc We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
