### ISSUE TITLE
Can't import VM extension with "marketplace syndication tool"

### ISSUE THREAD

**Issue by kongou-ae** [MicrosoftDocs/azure-stack-docs#435]
When I imported VM extension with "marketplace syndication tool" according to [Disconnected or a partially connected scenario](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-download-azure-marketplace-item?view=azs-1908#disconnected-or-a-partially-connected-scenario), the following error raised. I tried importing acronis.acronis-backup-win-arm-1.0.51 and microsoft.customscriptextension-arm-1.9.3, but same error raised.

```powershell
PS C:\Users\AzureStackAdmin\AzureStack-Tools> Import-AzSOfflineMarketplaceItem -origin "E:\DisconnectedMarketPlace" -Verbose
VERBOSE: displayName = Custom Script Extension
VERBOSE: publisherDisplayName = Microsoft Corp.
VERBOSE: publisherIdentifier = Microsoft.Compute
VERBOSE: galleryPackageBlobSasUri = https://azstmktprodwcu001.blob.core.windows.net/packages/3d1da3405381461ebfeca24537b5dcc5/GalleryPackage/package.azpkg?sv=2018-03-28&sr=b&sig=9EKI1jr
pAsVpX3dFUvA%2BU6T1voJy8vxWo9Gvrc0SUuU%3D&se=2019-10-18T13%3A20%3A22Z&sp=r
PreCheck : 
Property value for offer is null. Please check JSON contents, then retry import
JSON file contains null values for required properties: billingPartNumber description displayName galleryItemIdentity galleryPackageBlobSasUri iconUris legalTerms links offer 
offerVersion payloadLength productDetailsProperties productKind productProperties publisherDisplayName publisherIdentifier sku vmExtensionType
At C:\Users\AzureStackAdmin\AzureStack-Tools\Syndication\AzureStack.MarketplaceSyndication.psm1:655 char:5
+     PreCheck -contentFolder $origin
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,PreCheck
 ```
Importing a virtual machine with "marketplace syndication tool" works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5a0e40a-4042-9935-0f59-37eb87ec478e
* Version Independent ID: 81e5de2b-da67-e875-405d-65628be05adc
* Content: [Download marketplace items from Azure and publish to Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-download-azure-marketplace-item?view=azs-1908#disconnected-or-a-partially-connected-scenario)
* Content Source: [azure-stack/operator/azure-stack-download-azure-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-download-azure-marketplace-item.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@kongou-ae Are you trying to import these items into an Azure Stack Integrated System (multi-node deployment) or an Azure Stack Development Kit (ASDK)?

Also, what version of Azure Stack are you using?

**Comment by kongou-ae** [comment]
@TravisCragg-MSFT 
Thank you for your quick reply. I'm trying an integrated systems(1.1908.4.33) and an ASDK(1.1908.0.20). Each systems raised same error.

**Comment by TravisCragg-MSFT** [comment]
@kongou-ae I am following up with more information, but you can bypass the error for now by adding a non-null value by going to the "microsoft.customscriptextension-arm-1.9.3.json" (or other .json names for other extensions) and adding a space for the "offer", "offerVersion", and "SKU" properties.

**Comment by TravisCragg-MSFT** [comment]
@kongou-ae This was a validation issue on our end, and it will be fixed in the near future. For now, adding a non-null value to the "offer", "offerVersion", and "SKU" properties will allow you to import the marketplace extension items. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by kongou-ae** [comment]
@TravisCragg-MSFT 
Thanks. I confirmed the following PR which may related to this issue. After being merged this PR, I will try importing an VM extension manually.

https://github.com/Azure/AzureStack-Tools/pull/532
