### ISSUE TITLE
Share permissions

### ISSUE THREAD

**Issue by sspinetti** [MicrosoftDocs/azure-stack-docs#454]
I can see that shared folder's credentials are included as parameter of Start-SecretRotation cmdlet so, is CloudAdmin's access to shared folder is really required, as stated in step 7 of "Pre-steps for secret rotation" section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4feaa2a-4850-478d-8122-7eb751ba0777
* Version Independent ID: f5cd7372-0443-3f2e-c403-ed7ba1a56146
* Content: [Rotate secrets in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-1908#feedback)
* Content Source: [azure-stack/operator/azure-stack-rotate-secrets.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-rotate-secrets.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@sspinetti typically you would give the CloudAdmin's Credentials to access the share, but any valid credential will do.

**Comment by TravisCragg-MSFT** [comment]
@sspinetti We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
