### ISSUE TITLE
Need to change the choco command for intalling

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#456]
Should not be "choco install aks-engine --version v0.41.2 -y". It should be "choco install aks-engine --version 0.41.2 -y", remove the "v"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 374a2d3f-fc08-7479-678e-cc1b28fa09c3
* Version Independent ID: 56139164-d119-c4e5-de98-3bf7cb0702bc
* Content: [Deploy the AKS Engine on Windows in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-windows?view=azs-1908#verify-the-installation)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-windows.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-windows.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@walterov Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@walterov The change has been made and should show up in the next build. Thanks, Matt

**Comment by mattbriggs** [comment]
#please-close
