### ISSUE TITLE
A bit confusing regarding TLS 1.2

### ISSUE THREAD

**Issue by azscloudpro** [MicrosoftDocs/azure-stack-docs#457]
Hello!

Been troubleshooting the better part of today on why TLS 1.2 is not working when forcing only TLS 1.2 in the my.cnf file, we have followed the guide you have "Deploy highly available MySQL Databases" which uses Bitnami and their templates which is using Mysql Server version: 5.7.22-log MySQL Community Server. When enabling TLS 1.2 and only  TLS 1.2 you get the warning message in the mysql log: Failed to set up SSL because of the following SSL library error: TLS version is invalid

I found someone who had a similar problem here: https://github.com/docker-library/mysql/issues/567 which states:
This is a limitation in yaSSL (which is what the community edition of 5.7 uses currently); It only supports 1.1... So if following the "Deploy highly available MySQL databases" guide that you have the: Ensure that all hosting servers are configured for communication using TLS 1.2.  part is not applicable. Maybe needs some clarification :)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9da7c95f-1749-8818-f96f-c4ae02aa28a6
* Version Independent ID: db6e924d-d8c0-72bc-b0e3-382373ee7588
* Content: [Add MySQL hosting servers in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers?view=azs-1908)
* Content Source: [azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@azscloudpro Thanks for the feedback. I am following up now to get more information.

**Comment by TravisCragg-MSFT** [comment]
@azscloudpro We are looking further into this. TLS 1.1 will work in this scenario.

**Comment by azscloudpro** [comment]
Thank you for following up!

**Comment by mattbriggs** [comment]
@azscloudpro I am updating the doc. Thanks! Matt

#please-close
