### ISSUE TITLE
Omitted words in the following sentence...

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#460]
"If the installation steps in failed, you try to install using the GoFish package manager. GoFish describes itself as a cross-platform Homebrew."

Needs to be: "If the installation steps described in the sections above failed, you can install the AKS Engine using the GoFish package manager. GoFish describes itself as a cross-platform Homebrew."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143ccfc6-64a1-f7d9-e9ec-7e0b313f1f15
* Version Independent ID: e59d1050-1d82-0792-dd64-7f0fa9816605
* Content: [Troubleshoot the AKS Engine on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot?view=azs-1908)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by ChiragMishra-MSFT** [comment]
@walterov Thanks for bringing this to our notice. We are investigating into the issue and will update you shortly.

**Comment by mattbriggs** [comment]
https://review.docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot?view=azs-1802&branch=pr-en-us-1656
