### ISSUE TITLE
Change download instructions for the tar file 

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#461]
Need to update instructions, the following box of code should change:
mkdir -p $HOME/kuberneteslogs
cd $HOME/kuberneteslogs
wget https://github.com/msazurestackworkloads/azurestack-gallery/releases/download/diagnosis-v0.1.0/diagnosis.tar.gz
tar xvzf diagnosis.tar.gz -C ./

To:

mkdir -p $HOME/kuberneteslogs
cd $HOME/kuberneteslogs
wget https://github.com/msazurestackworkloads/azurestack-gallery/releases/download/diagnosis-v0.1.1/diagnosis-v0.1.1.tar.gz 
tar xvf diagnosis-v0.1.1.tar.gz -C ./

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143ccfc6-64a1-f7d9-e9ec-7e0b313f1f15
* Version Independent ID: e59d1050-1d82-0792-dd64-7f0fa9816605
* Content: [Troubleshoot the AKS Engine on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot?view=azs-1908)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by ChiragMishra-MSFT** [comment]
@walterov Thanks for bringing this to our notice. We are investigating into the issue and will update you shortly.

**Comment by mattbriggs** [comment]
https://review.docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-troubleshoot?view=azs-1802&branch=pr-en-us-1656

**Comment by mattbriggs** [comment]
#please-close
