### ISSUE TITLE
User Portal links are broken

### ISSUE THREAD

**Issue by luisvw** [MicrosoftDocs/azure-stack-docs#463]
The "user portal" links are broken. They currently point to https://portal.local.azurestack.external/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cca516b-9d83-3975-39b2-329f23e2b31c
* Version Independent ID: 14f0d110-3bad-3076-9432-518b9b13296a
* Content: [Manage Key Vault in Azure Stack using the portal](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-key-vault-manage-portal?view=azs-1908#feedback)
* Content Source: [azure-stack/user/azure-stack-key-vault-manage-portal.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-key-vault-manage-portal.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@luisvw that link is correct for the ASDK. For a full Azure Stack Integrated System, [you can find more information Here](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-use-portal?view=azs-1908#access-the-portal) abou the correct URL. 

Please let me know if you need any additional information.

**Comment by luisvw** [comment]
That is not a valid link, it can't be reached in any browser, on or off Microsoft corpnet.

**Comment by TravisCragg-MSFT** [comment]
@luisvw This doc is for [Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-overview?view=azs-1908) not Azure. The correct Azure doc for [managing secrets in Key Vault is found Here](https://docs.microsoft.com/en-us/azure/key-vault/about-keys-secrets-and-certificates).

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
