### ISSUE TITLE
Azure subscription replicator (v3) tool download location or github project repository is missing

### ISSUE THREAD

**Issue by eric-jenouvrier** [MicrosoftDocs/azure-stack-docs#472]
Azure subscription replicator (v3) tool download location or github project repository is missing. This page seem promissing :) but it is impossible to test, or use it or provide additional feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae86f077-cc54-1e9a-24b6-b132b2afdeb3
* Version Independent ID: 379e8fa2-11cb-301b-86be-3a7ece2bc111
* Content: [How to replicate resources across multiple Azure Stack subscriptions](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-howto-backup-replicator?view=azs-1908#feedback)
* Content Source: [azure-stack/user/azure-stack-network-howto-backup-replicator.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-network-howto-backup-replicator.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@eric-jenouvrier 

Thanks for messaging me. I’ve cc:ed the principal author. Sorry for frustration … I know it can be confounding to try to find a repo that isn’t there. I should have the pointer shortly and will post the update, and hopefully get you the link directly.

#in-progress

**Comment by eric-jenouvrier** [comment]
Hi Matt,

Thanks for feedback, I believe I finally found it (after numerous research within different microsoft repo on Github), so it is may be that one : https://github.com/Azure-Samples/azure-intelligent-edge-patterns/tree/master/subscription%20replicator

And btw the author rtibi on github is not far away from tibir on screenshoot within the doc

But beyond myself, if some other people would like to test or find the place, they will face the same problem I believe

Warm regards,

Eric JENOUVRIER
DSI – Cloud Architect Microsoft
[cid:image001.png@01D59596.105756D0]
Sopra Steria
11 avenue du Maréchal Juin
92366 Meudon la Forêt - France
Phone: +33 1 85 32 59 85 - Mobile: +33 6 49 88 81 05
eric.jenouvrier@soprasteria.com<mailto:eric.jenouvrier@soprasteria.com> - www.soprasteria.com<http://www.soprasteria.com/>

De : Matt Briggs <notifications@github.com>
Envoyé : 07 November 2019 18:03
À : MicrosoftDocs/azure-stack-docs <azure-stack-docs@noreply.github.com>
Cc : JENOUVRIER Eric <eric.jenouvrier@soprasteria.com>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/azure-stack-docs] Azure subscription replicator (v3) tool download location or github project repository is missing (#472)


@eric-jenouvrier<https://github.com/eric-jenouvrier>

Thanks for messaging me. I’ve cc:ed the principal author. Sorry for frustration … I know it can be confounding to try to find a repo that isn’t there. I should have the pointer shortly and will post the update, and hopefully get you the link directly.

#in-progress

**Comment by mattbriggs** [comment]
@eric-jenouvrier That should be it. I've updated the doc. Thanks and will correct when I get additional info if there should be a different repo. But those look like the scripts. Thanks again for your feedback and update.

**Comment by mattbriggs** [comment]
#please-close

**Comment by mattbriggs** [comment]
Doc updated. 

#please-close
