### ISSUE TITLE
AKS engine in preview or GA ? 

### ISSUE THREAD

**Issue by eric-jenouvrier** [MicrosoftDocs/azure-stack-docs#474]
Link to ingnite announcement : https://techcommunity.microsoft.com/t5/Azure-Stack-Blog/Azure-Stack-Hub-extends-capabilities-on-the-Edge/ba-p/984483 it is said "...We are announcing the general availability of AKS engine on Azure Stack Hub...."

If it is the case, then, that bloc " Important

The AKS engine is currently in public preview. This preview version is provided without a service level agreement, and it's not recommended for production workloads. Certain features might not be supported or might have constrained capabilities. For more information, see Supplemental Terms of Use for Microsoft Azure Previews." is no more relevant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4810154-9f19-3f67-8c54-c2bb08edc2b4
* Version Independent ID: e99088a6-f7b1-cefd-4cad-3554423d4900
* Content: [What is the AKS engine on Azure Stack?](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-overview?view=azs-1908)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-overview.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@eric-jenouvrier Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@eric-jenouvrier I haven't yet received the instruction to remove this notice. I will verify. Thanks, Matt

#in-progress

**Comment by mattbriggs** [comment]
@eric-jenouvrier The AKS Engine on Azure Stack Hub will be at GA with the 1910 release.

#please-close
