### ISSUE TITLE
Add example for connecting when the winrm client PC is not using en-US

### ISSUE THREAD

**Issue by easyveazie** [MicrosoftDocs/azure-stack-docs#483]
If a customer connects to the privileged endpoint when the value of [System.Globalization.CultureInfo]::CurrentCulture is not en-US on the client OS, we need to force the culture to be en-US when creating the session. Without setting this to en-US, utilities such as Test-AzureStack or Get-AzureStackLog do not work properly.

```powershell
$cred = Get-Credential
$pep = New-PSSession -ComputerName <IP_address_of_ERCS> -ConfigurationName PrivilegedEndpoint -Credential $cred -SessionOption (New-PSSessionOption -Culture en-US -UICulture en-US) 
Enter-PSSession $pep
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae3d8bb-b86b-aba5-f1ae-784434442810
* Version Independent ID: 09851c8f-bd84-b23b-dda8-48f3d3b9e843
* Content: [Using the privileged endpoint in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-privileged-endpoint?view=azs-1908)
* Content Source: [azure-stack/operator/azure-stack-privileged-endpoint.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-privileged-endpoint.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@easyveazie Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by easyveazie** [comment]
@TravisCragg-MSFT thank you facilitating this update. I see it is live now so go ahead and close this issue out :)

**Comment by TravisCragg-MSFT** [comment]
@easyveazie We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
