### ISSUE TITLE
Account used for AzCredential can't use MFA

### ISSUE THREAD

**Issue by Cyr-Az** [MicrosoftDocs/azure-stack-docs#484]
The script fails with the error "Unable to acquire token for tenant" if the account used as AzCredential requires MFA (and if its password is expired as well). It took me a few hours to realize it, so it may be worth mentioning it somewhere 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f7e3b4a-30fb-4068-32b1-943cd483f531
* Version Independent ID: fc78fd4f-2626-e0b9-8ac0-7ea1938ff419
* Content: [Deploy MySQL resource provider on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-mysql-resource-provider-deploy?view=azs-1908#feedback)
* Content Source: [azure-stack/operator/azure-stack-mysql-resource-provider-deploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-mysql-resource-provider-deploy.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@Cyr-Az Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@Cyr-Az Thanks for your feedback. I've added a note in the topic. Thanks! Matt

#please-close
