### ISSUE TITLE
Deploy a Service Fabric cluster to Azure Stack with ARM

### ISSUE THREAD

**Issue by pisees** [MicrosoftDocs/azure-stack-docs#490]
Can you deploy Service Fabric cluster to Azure Stack with ARM templates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80a333ac-8208-4146-2d99-6b6258b64a3f
* Version Independent ID: 30341430-ba3a-ae9e-5599-5ed618e9213a
* Content: [Deploy a secured Service Fabric cluster in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-template-service-fabric-cluster?view=azs-1908#feedback)
* Content Source: [azure-stack/user/azure-stack-solution-template-service-fabric-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-solution-template-service-fabric-cluster.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by pisees** [comment]
Reading the doc again I see it says "The Service Fabric cluster in Azure Stack doesn't use the resource provider Microsoft.ServiceFabric. Instead, in Azure Stack, the Service Fabric cluster is a virtual machine scale set with preinstalled software using Desired State Configuration (DSC)." so I assume that answer to my question is no.

Given that, is the source for DSC deployment available?

**Comment by mike-urnun-msft** [comment]
Hi @pisees - Thank you for your feedback! We will review and get back to you with relative info.

**Comment by TravisCragg-MSFT** [comment]
@pisees I do not believe that this is available via template at this time, but I am following up to confirm. 

It is my understanding that the DSC configuration is behind the scenes, you should not need to configure it yourself. 

As the first sentence of this article states, you can use the marketplace item for a Service Fabric Cluster in Azure Stack Hub. 

Please let me know if you need any additional clarification.

**Comment by TravisCragg-MSFT** [comment]
@pisees After following up, it is possible to deploy a Service Fabric cluster to Azure Stack via ARM template. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
