### ISSUE TITLE
Add a note under the "what's new" section for the release of the AKS engine on Azure Stack

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#503]
Update 1910 enables the deployment of Kubernetes clusters in Azure Stack Edge. AKS Engine will allow Azure Stack Hub customers to:
1.	Manage the life-cycle of their Kubernetes clusters. That is, they will be able to create, update, and scale clusters with ease.
2.	Maintain their clusters using managed images produced by the AKS team and prep by the Azure Stack team.
3.	Take advantage of an ARM integrated Kubernetes cloud provider that builds clusters using Azure native resources.
4.	Deploy and manage their clusters in connected or disconnected Azure Stack stamps.
5.	Utilize Azure hybrid features:
a.	Integration with Azure Arc (private preview coming soon)
b.	Integration with Azure Monitor for Containers (in public preview)
6.	Use Windows Containers with AKS engine (in private preview)
7.	Receive CSS and PG support for their deployments

For more information see: https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e05517-6ffa-ad32-ec69-d3299492d880
* Version Independent ID: 2d6ffb4c-9134-a390-3f90-2322c9182e76
* Content: [Azure Stack release notes](https://docs.microsoft.com/en-us/azure-stack/operator/release-notes?view=azs-1910#whats-new)
* Content Source: [azure-stack/operator/release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/release-notes.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@walterov Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
#please-close
