### ISSUE TITLE
- Force parameter is not available for Register-AzureRmResourceProvider

### ISSUE THREAD

**Issue by bottkars** [MicrosoftDocs/azure-stack-docs#51]
[Enter feedback here]
in

foreach($s in (Get-AzureRmSubscription)) {
        Select-AzureRmSubscription -SubscriptionId $s.SubscriptionId | Out-Null
        Write-Progress $($s.SubscriptionId + " : " + $s.SubscriptionName)
Get-AzureRmResourceProvider -ListAvailable | Register-AzureRmResourceProvider -Force
    }

-Force is not a Parameter
Register-AzureRmResourceProvider : A parameter cannot be found that matches parameter name 'Force'.
At line:4 char:79
+ ... urceProvider -ListAvailable | Register-AzureRmResourceProvider -Force
+                                                                    ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Register-AzureRmResourceProvider], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.RegisterAzureProviderCmdlet
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1427fb3-7704-d83a-45df-a68e76fcb2b9
* Version Independent ID: d995f898-b0e3-1cdc-4d19-db5145f46896
* Content: [Connect to Azure Stack with PowerShell as a user](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-powershell-configure-user#feedback)
* Content Source: [azure-stack/user/azure-stack-powershell-configure-user.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-powershell-configure-user.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@bottkars Thanks for sending this update. I've updated the topic. Thanks, Matt #please-close

**Comment by TravisCragg-MSFT** [comment]
@bottkars We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
