### ISSUE TITLE
Text in article is ambiguous or not compliant with legal agreement

### ISSUE THREAD

**Issue by eric-jenouvrier** [MicrosoftDocs/azure-stack-docs#511]
Within the page, there is this sentence "You can follow this example to upload a VHD to a storage account in the Azure Stack Administrator portal."

It could be ambiguous or not compliant with legal agreement for the following reason : 

1/ it could make think to Azure Stack Admin he have to create a storage account within the "Default Provider Subscription" of Azure Stack  to upload VHD (custom product), then publish it within Azure Stack Marketplace.

2/ but if you read legal agreement signed between Microsoft and MS Partner (Microsoft Partner Agreement, new version starting ~Sep 2019), it is clearly explained (legal) such thing (ie. create a storage account to make something else that "regular" admin activities) is forbidden (I will not provide more details and/or in private conversation because agreement material is under NDA). Let me know if you need exact references.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6a61eee-2c60-1a86-3e06-fa7689705d18
* Version Independent ID: 28759edc-2b94-e42e-3353-6ebe13b2a90f
* Content: [Add a custom VM image to Azure Stack](https://docs.microsoft.com/en-gb/azure-stack/operator/azure-stack-add-vm-image?view=azs-1910#add-a-vm-image-as-an-azure-stack-operator-using-the-portal)
* Content Source: [azure-stack/operator/azure-stack-add-vm-image.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-add-vm-image.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **Justinha**

**Comment by mike-urnun-msft** [comment]
@eric-jenouvrier Thank you for your feedback! We will review and update as appropriate.

**Comment by mattbriggs** [comment]
@eric-jenouvrier Thanks for yoiur comment. #-in-progress

**Comment by mattbriggs** [comment]
@eric-jenouvrier We have a question to our legal team and I've brought this to the attention of the product group. Thanks for raising this issue. I will update when legal and the product group provide guidance.

**Comment by mattbriggs** [comment]
#please-close
