### ISSUE TITLE
Deployment requirements incorrectly links to creation of free Azure subscription

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#523]
The list under the deployment requirements header has a link to create a free Azure subscription -&gt; https://azure.microsoft.com/free/?b=17.06

But Azure Stack customers must use a CSP or EA subscription, not a free one, so think link doesn't seem relevant to Azure Stack customers. I think they should be linked to the AzsReadinessChecker tool instead, to validate their existing subscription- https://docs.microsoft.com/azure-stack/operator/azure-stack-validate-registration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6facccd9-e7e3-4d83-6797-79a8e6381a37
* Version Independent ID: 32429d7e-d806-e9cb-0a28-de2d6ae51113
* Content: [Azure Stack deployment network traffic](https://docs.microsoft.com/en-us/azure-stack/operator/deployment-networking?view=azs-1910#deployment-requirements)
* Content Source: [azure-stack/operator/deployment-networking.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/deployment-networking.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
Thanks for your feedback, @alexsmithMSFT. This makes sense to me. I've updated the topic. https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/1911

**Comment by mattbriggs** [comment]
#please-close
