### ISSUE TITLE
Need links for SQL RP and AKS-Engine

### ISSUE THREAD

**Issue by cenkersoy** [MicrosoftDocs/azure-stack-docs#525]
On this page, https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-considerations  it would make sense to add links to the "Next Steps" section about differences between Azure SQL and Azure Stack SQL RP as well as AKS versus AKS-Engine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d376758-4743-cfa3-814d-b032aa6fb778
* Version Independent ID: 75d86a26-aa15-b5a9-5f23-51250f52d890
* Content: [Differences between Azure Stack and Azure when using services and building apps](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-considerations?view=azs-1910)
* Content Source: [azure-stack/user/azure-stack-considerations.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-considerations.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by ManojReddy-MSFT** [comment]
@cenkersoy  Thanks for the feedback. We are looking into this and will get back to you shortly.

**Comment by TravisCragg-MSFT** [comment]
@cenkersoy Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@cenkersoy Very sorry for the slow response. I will add some relevant links to the Next Steps section ASAP. Thank you for your feedback! #please-close
