### ISSUE TITLE
Why I need  "Connect to Azure Stack" to add tenant? 

### ISSUE THREAD

**Issue by fengatms** [MicrosoftDocs/azure-stack-docs#526]
I suppose I need connect to Azure to add tenant. same as document 
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-csp-howto-register-tenants?view=azs-1910#update-the-registration-with-the-end-customer-subscription

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b9c1529-af2a-1be0-4b24-910ec0d2d4ec
* Version Independent ID: 743ed0e9-478c-9d69-fa04-07a314b8ef07
* Content: [Register tenants for usage tracking in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-csp-ref-operations?view=azs-1910#feedback)
* Content Source: [azure-stack/operator/azure-stack-csp-ref-operations.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-csp-ref-operations.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@fengatms You need to connect to both Azure and Azure Stack to register a tenant for usage in Azure Stack. 

If you are looking for instructions for creating an Azure Tenant not related to Azure Stack, you can [find instructions Here](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-create-new-tenant).

**Comment by TravisCragg-MSFT** [comment]
@fengatms Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
