### ISSUE TITLE
URLs Missing

### ISSUE THREAD

**Issue by QFiaux** [MicrosoftDocs/azure-stack-docs#529]
Hi,

There are two URLs missing for the identity role. Based on your Microsoft AzureStack Readiness script it needs to also connect to the two endpoints below during deployments (from the Public Infrastructure Network):

ManagementServiceUri = "https://management.core.windows.net/"
ARMUri                          = "https://management.azure.com/"

I've encountered this issue when deploying the solution for a customer blocking the outgoing traffic allowing only the list above.

Thanks,

Q

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d02f93-1ae9-eb2d-9c0f-0af012653885
* Version Independent ID: 18f15ad2-ef9b-f883-c49b-09289a2e6fb8
* Content: [Publish Azure Stack services in your datacenter](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-endpoints?view=azs-1910#feedback)
* Content Source: [azure-stack/operator/azure-stack-integrate-endpoints.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-endpoints.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **justinha**

**Comment by ManojReddy-MSFT** [comment]
@justinha Thanks for bringing this to our attention. We are looking into this and will get back to you shortly.

**Comment by TravisCragg-MSFT** [comment]
@QFiaux Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@QFiaux Thanks for your feedback. I have a question out and will update shortly.

#in-progress

**Comment by mattbriggs** [comment]
@QFiaux The topic has been updated. Thanks again for your feedback.

#please-close
