### ISSUE TITLE
The cloud-init is supported now

### ISSUE THREAD

**Issue by yuxisun1217** [MicrosoftDocs/azure-stack-docs#531]
Could you please update this page? If add a guide to cloud-init configuration will be better. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc31e147-b01d-ab0d-f97a-14ace2d658a8
* Version Independent ID: 351862a1-a03f-61dd-e619-3af6562870ac
* Content: [Prepare a Red Hat-based virtual machine for Azure Stack - Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-redhat-create-upload-vhd?view=azs-1910&source=docs#feedback)
* Content Source: [azure-stack/operator/azure-stack-redhat-create-upload-vhd.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-redhat-create-upload-vhd.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@yuxisun1217 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@yuxisun1217 Thanks for pointing that out. I've updated the topic, and I have a question out engineering about adding the cloud-init to Red Hat to add more information.

#please-close
