### ISSUE TITLE
Better formulation needed for the Access Control (IAM) known issue

### ISSUE THREAD

**Issue by raluca256** [MicrosoftDocs/azure-stack-docs#537]
Hello,
The current note states:
Access Control (IAM)
Applicable: This issue applies to releases 1903 and later
Cause: IAM Extension is out of date. Ibiza shipped with Azure Stack introducing a new behavior that causes RBAC extension to break if user is opening RBAC extension from a subscription which is not selected in the global subscription picker.
Remediation: Ensure the subscription is checked in the global subscription picker.

This does not mean too much for an azure stack operator or user. The name of that blade in the portal is "Access Control IAM", not "RBAC extension" as mentioned on the note. The blade does not "break", it displays "Loading" in a loop. The Remediation mentions the "global subscription picker" name that is no where to be found in the User portal. The blade that the remediation refers too is called "Directory + Subscription" and it has a shortcut on the "All resources" blade called: "Don't see a subscription?Open Directory + Subscription settings" and a button on the top right line of the portal on the left side of the "Notification" bell button.
The proper text should be:
Access Control (IAM)

Applicable: This issue applies to stamps that were deployed with a base image 1903 or earlier.
Cause: The IAM Extension is out of date. Ibiza shipped with Azure Stack introducing a new behavior that causes RBAC extension to fail if the user is opening the "Access Control (IAM)" blade for a subscription which is not selected in the global subscription picker, called "Directory + Subscription" in the User Portal. The blade will display "Loading" in a loop and the user cannot add new roles to the subscription, the "Add" blade will also display "Loading" in a loop.
Remediation: Ensure the subscription is checked in the "Directory + Subscription" menu. The menu can be accessed from the top right part of the portal, near the "Notifications" button, or via the shortcut added on the "All resources" blade using the phrases "Don't see a subscription?Open Directory + Subscription settings". The subscription has to be selected in this menu.

Thanks! 
Raluca

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0094b74f-e85b-6983-5f58-ce24f825b63c
* Version Independent ID: a90feafe-0401-3da0-bb95-4dbc8868ea0f
* Content: [Azure Stack known issues](https://docs.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-1910)
* Content Source: [azure-stack/operator/known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/known-issues.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@raluca256 No problem, I will make the change ASAP.

**Comment by sethmanheim** [comment]
Done, and should be live by 3 PM PST today: https://docs.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-1910#access-control-iam.

**Comment by sethmanheim** [comment]
#please-close
