### ISSUE TITLE
Can't connect to PEP anymore from non-english windows OS

### ISSUE THREAD

**Issue by Cyr-Az** [MicrosoftDocs/azure-stack-docs#539]
Following the update, it is not possible anymore to connect to the Privileged Endpoint (ERC VMs) from a computer running a non-english version of Windows : 
![image](https://user-images.githubusercontent.com/48621794/70821070-74549e00-1dda-11ea-80a6-42a7bb47cf66.png)

A quick workaround is to run the new-pssession/enter-pssession using en-US Culture in powershell settings, for example using this script : https://resources.oreilly.com/examples/9780596528492/blob/master/Use-Culture.ps1 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0094b74f-e85b-6983-5f58-ce24f825b63c
* Version Independent ID: a90feafe-0401-3da0-bb95-4dbc8868ea0f
* Content: [Azure Stack known issues](https://docs.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-1910)
* Content Source: [azure-stack/operator/known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/known-issues.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@Cyr-Az Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
I can't just add known issues without getting confirmation from the engineering team, so I need to check with them.

**Comment by sethmanheim** [comment]
@Cyr-Az Confirmed. I will add this ASAP, thank you!

**Comment by sethmanheim** [comment]
Done, thank you for the feedback. #please-close
