### ISSUE TITLE
Facing issue in Azure Stack deployment with 1910.58

### ISSUE THREAD

**Issue by akn9050** [MicrosoftDocs/azure-stack-docs#543]
I tried to run the script multiple times with Re-Run Flag. With Same configuration if I am deploying the 1907 then it is working.

Can you please check on this with high priority. As we are trying it from long and multiple times but it looks like not working.

[Deployment.2019-12-17.14-02-56.0.log](https://github.com/MicrosoftDocs/azure-stack-docs/files/3973946/Deployment.2019-12-17.14-02-56.0.log)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 858effe3-8bc2-f070-8679-2b8ff2ed3f73
* Version Independent ID: bdf45685-a816-50c1-e41b-c3233b82249d
* Content: [Deploy ASDK from the command line using Powershell](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-deploy-powershell?view=azs-1910)
* Content Source: [azure-stack/asdk/asdk-deploy-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-deploy-powershell.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by MarileeTurscak-MSFT** [comment]
@akn9050 please provide a link to the document you are referencing so that we can better assist you.

**Comment by akn9050** [comment]
@MarileeTurscak-MSFT Please find the document which i am referring https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-deploy-powershell?view=azs-1910

**Comment by sethmanheim** [comment]
@akn9050 This is not a documentation issue. Please contact Microsoft Support for help with this problem. Thank you! #please-close
