### ISSUE TITLE
Update section for "Default provider subscription" for multi-node Azure Stack

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#546]
Doc still mentions ASDK- "The default provider subscription is automatically created when you deploy the ASDK."
Default provider subscription is available in multi-node Azure Stack, not just ASDK. 
Can leave mention of ASDK but probably best to just remove it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34b4d158-a0bd-47ce-4a29-60111ef9f515
* Version Independent ID: 4a8f336e-cbb4-f35a-429c-048ada1c6df6
* Content: [Azure Stack services, plans, offers, subscriptions overview](https://docs.microsoft.com/en-us/azure-stack/operator/service-plan-offer-subscription-overview?view=azs-1910)
* Content Source: [azure-stack/operator/service-plan-offer-subscription-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/service-plan-offer-subscription-overview.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
Thanks @alexsmithMSFT. I've reworded and removed ASDK.
