### ISSUE TITLE
Confusion from Creating Linux Server

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-stack-docs#556]
In "Quickstart: Create a Linux server VM by using the Azure Stack portal."
The link guides to deploy Ubuntu VM from market place. But in the real scenario, specific linux Ubuntu VM should be deployed for the AKS Engine which is "AKS Base Ubuntu 16.04-LTS Image Distro, October 2019"
If I follow the guides exactly, I will be deploying normal Ubuntu VM instead of AKS Base image. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d8c6cbd-54d8-9746-a1f8-a618b98e011e
* Version Independent ID: 479c631e-b7a4-c5cf-160d-141d336ad50a
* Content: [Install the AKS engine on Linux in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux?view=azs-1910)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by MarileeTurscak-MSFT** [comment]
@HassanAlmanasrah 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by msrini-MSFT** [comment]
@HassanAlmanasrah , In the doc where you see the link to deploy Ubuntu VM should be fine as you are not deploying the ASK VM at this step. It is a client VM on which you install AKS engine and other necessary tools to connect to AKS VM. In the next doc, you can see steps to deploy the AKS VM which will have the base OS as "AKS Base Ubuntu 16.04-LTS Image Distro, October 2019"

Let me know if you have any further questions.

**Comment by HassanAlmanasrah** [comment]
Thanks Karthik

I had the impression that it is mandatory to use AKS Base for the AKS Engine, while from the below, AKS Base is used for the nodes not the engine.

Best Regards
Hassan
