### ISSUE TITLE
Can this also applied to CSP 

### ISSUE THREAD

**Issue by HannahHsiao** [MicrosoftDocs/azure-stack-docs#557]
What if I have an older image and my user forgot to check the "I have a license" box, or we use our own images and we do have Enterprise Agreement entitlement?
You can change the license model attribute to the bring your own license model, by running the following commands:

PowerShell

Copy
$vm= Get-Azurermvm -ResourceGroup "&lt;your RG&gt;" -Name "&lt;your VM&gt;"
$vm.LicenseType = "Windows_Server"
Update-AzureRmVM -ResourceGroupName "&lt;your RG&gt;" -VM $vm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 610b3550-693c-c08f-929a-23d7afb96268
* Version Independent ID: 43cf2d3c-69af-24fc-2f13-949a381061f5
* Content: [Azure Stack Windows Server related FAQs](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-windows-server-faq?view=azs-1908)
* Content Source: [azure-stack/operator/azure-stack-windows-server-faq.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-windows-server-faq.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by MarileeTurscak-MSFT** [comment]
@HannahHsiao 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by msrini-MSFT** [comment]
@HannahHsiao , Did you get any error message while trying those commands via CSP subscription ?

If yes, please share the error message.

**Comment by HannahHsiao** [comment]
Hi msrini, thank you for your reply, I'll try

**Comment by HannahHsiao** [comment]
if it can also be used for CSP subscription, could you please adjust the description to "What if I have an older image and my user forgot to check the "I have a license" box, or we use our own images and we do have Enterprise Agreement entitlement or we use our own images and we are CSPs who use SPLA licensing." ?

**Comment by msrini-MSFT** [comment]
@HannahHsiao , Did you get this worked when you tried the command?

**Comment by msrini-MSFT** [comment]
@HannahHsiao , Do you have any update on this issue?

**Comment by msrini-MSFT** [comment]
@HannahHsiao , The doc can be updated only when there are exceptions to the subscriptions. If that command works for you, we don't explicitly need to update that it works for CSP subscription. 

Please test and update me and I will close this issue for now, feel free to tag me if you need any help.
