### ISSUE TITLE
Unable to deploy item downloaded from Azure

### ISSUE THREAD

**Issue by aSmallByte** [MicrosoftDocs/azure-stack-docs#56]
Hi, 

I have two versions of an item that I added from Azure into Azure Stack ADFS marketplace management. In Marketplace Management, I can see both items and the corresponding version. When I go to Marketplace, I only see one item. Since there is no version info, I don't know which item it corresponds to. 

In the connected scenario, step 5 mentions: "To deploy the downloaded item, select + Create a resource, and then search among the categories for the new marketplace item. ".
Does it mean that when we are in Marketplace management page and select the item, we should see "Create a resource" somewhere? In my case, I don't have that option. 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5a0e40a-4042-9935-0f59-37eb87ec478e
* Version Independent ID: 81e5de2b-da67-e875-405d-65628be05adc
* Content: [Download marketplace items from Azure](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-download-azure-marketplace-item)
* Content Source: [azure-stack/operator/azure-stack-download-azure-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-download-azure-marketplace-item.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@aSmallByte Thanks for the feedback. We are actively investigating and will get back to you soon.

**Comment by TravisCragg-MSFT** [comment]
@aSmallByte Are you doing this with the ASDK or with an Azure Stack Multi-Node deployment?

When you download items from Azure, they will appear in the Marketplace Management. You will be able to deploy them from your Azure Stack Marketplace, which is a different area from the Marketplace Management. for example, if you downloaded a VM image, you will be able to select that image from the marketplace when deploying a VM

Most marketplace deployments automatically select the most recent version when you deploy. If the version is not listed, assume it is the highest version number. You can also use Azure Stack PowerShell to view the marketplace items in your Azure Stack for more info.

**Comment by pomme1608** [comment]
Hi, 

That's what I wasn't sure of, if the item I saw in the Marketplace would be the latest version (and yes I'm using the ASDK).

Thank you for your quick reply.

**Comment by aSmallByte** [comment]
Hi,

That's what I wasn't sure of, if the item I saw in the Marketplace would be the latest version (and yes I'm using the ASDK).

Thank you for your quick reply.
