### ISSUE TITLE
Please confirm the code

### ISSUE THREAD

**Issue by HannahHsiao** [MicrosoftDocs/azure-stack-docs#560]
Dear team,
Could you please confirm if the first line for "What if my user incorrectly checked the "I have a license" box in previous Windows builds, and they don't have a license?" is right?

"vm=" Get-Azurermvm -ResourceGroup "&lt;your RG&gt;" -Name "&lt;your VM&gt;"
should it be "$vm=" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 610b3550-693c-c08f-929a-23d7afb96268
* Version Independent ID: 43cf2d3c-69af-24fc-2f13-949a381061f5
* Content: [Azure Stack Windows Server related FAQs](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-windows-server-faq?view=azs-1908)
* Content Source: [azure-stack/operator/azure-stack-windows-server-faq.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-windows-server-faq.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SnehaAgrawal-MSFT** [comment]
@HannahHsiao Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by msrini-MSFT** [comment]
PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/2193
