### ISSUE TITLE
Missing \ in --azure-env AzureStackCloud 

### ISSUE THREAD

**Issue by jayfam91** [MicrosoftDocs/azure-stack-docs#562]
aks-engine upgrade \
--azure-env AzureStackCloud   
--location &lt;for an ASDK is local&gt; \
--resource-group kube-rg \
--subscription-id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx \
--api-model kube-rg/apimodel.json \
--upgrade-version 1.13.5 \
--client-id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx \
--client-secret xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx \
--identity-system adfs # required if using AD FS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f23e9819-30aa-02a8-08af-49b92c61316b
* Version Independent ID: a0b1770c-1ddc-17b6-2461-b4d77f474ca4
* Content: [Upgrade a Kubernetes cluster on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-upgrade?view=azs-1910#feedback)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-upgrade.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-upgrade.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SnehaAgrawal-MSFT** [comment]
@jayfam91 Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by mattbriggs** [comment]
@SnehaAgrawal-MSFT Thanks for reviewing and noting the missing line escape. I've updated. Thanks!

**Comment by mattbriggs** [comment]
#please-close
