### ISSUE TITLE
SQL RP - ASDK - Unable to install

### ISSUE THREAD

**Issue by rfsonders** [MicrosoftDocs/azure-stack-docs#572]
Team.
The systemic PowerShell version problem still exists. See all my previous tickets.
Current SDK version: 1910
SQL RP version: 1.1.47.0

Steps to reproduce:
1. Uninstall all PowerShell modules
Get-Module -Name Azs.* -ListAvailable | Uninstall-Module -Force -Verbose
Get-Module -Name Azure* -ListAvailable | Uninstall-Module -Force -Verbose
Remove-Item 'C:\Program Files (x86)\WindowsPowerShell\Modules\Azure*' -Force 
Remove-Item 'C:\Program Files (x86)\WindowsPowerShell\Modules\Azs*' -Force 

2. Install the SQL RP

Logging attached which contains the PS failure.

[DeploySQLProvider.ps1_20200104-144026.txt](https://github.com/MicrosoftDocs/azure-stack-docs/files/4022031/DeploySQLProvider.ps1_20200104-144026.txt)

**Comment by mike-urnun-msft** [comment]
@rfsonders Thank you for your feedback. Could you provide us with a URL of the documentation that your feedback is most applicable to? That way, we're able to locate the right team that's better suited to address your feedback.

**Comment by sethmanheim** [comment]
If this is still an issue, please reopen with more details. Thank you! #please-close
