### ISSUE TITLE
IPSec negotiation fails with 1910 default settings

### ISSUE THREAD

**Issue by comnam90** [MicrosoftDocs/azure-stack-docs#577]
The new IPSec negotiation settings in 1910 fail to negotiate with Azure.
Azure uses DH Group 2, while Azure Stack is using Dh Group ECP384 (among other incorrect settings.)

Azure Settings:
```
Policy1:Cipher=AES-CBC-256 Integrity=SHA1 DhGroup=DhGroup2 
Policy2:Cipher=AES-CBC-256 Integrity=SHA256 DhGroup=DhGroup2 
Policy3:Cipher=AES-CBC-128 Integrity=SHA1 DhGroup=DhGroup2 
Policy4:Cipher=AES-CBC-128 Integrity=SHA256 DhGroup=DhGroup2 
Policy5:Cipher=3DES Integrity=SHA1 DhGroup=DhGroup2 
Policy6:Cipher=3DES Integrity=SHA256 DhGroup=DhGroup2 
```

Azure Stack Settings:
```
Policy1:Cipher=AES-CBC-256 Integrity=SHA384 DhGroup=DhGroupECP384 
```

The fix is to use powershell to update the IPSec policies for the Azure Virtual Network Gateway Connection to match Azure Stack Hub.
```
# Create IPSec Policy
$IPSecPolicy = New-AzIpsecPolicy -DhGroup ECP384 -IkeIntegrity SHA384 -PfsGroup ECP384 `
    -IpsecEncryption GCMAES256 -IpsecIntegrity GCMAES256 -SALifeTimeSeconds 27000 `
    -SADataSizeKilobytes 33553408 -IkeEncryption AES256
		​
# Apply the policy to the connection
Get-AzResourceGroup "<Name of RG Containing VPN Connection>" |  `
Get-AzVirtualNetworkGatewayConnection |  `
Set-AzVirtualNetworkGatewayConnection -IpsecPolicies $IPSecPolicy -Verbose
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 914f9ca2-addd-fca2-4562-f8e748f188b6
* Version Independent ID: cbdfbfc9-a835-2015-ce60-a6e0578c4d4a
* Content: [Connect Azure Stack to Azure using VPN](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-connect-vpn?view=azs-1910&source=docs#feedback)
* Content Source: [azure-stack/user/azure-stack-connect-vpn.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-connect-vpn.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by DixitArora-MSFT** [comment]
Hi @comnam90 Thanks for your feedback. We will review and update as appropriate.

**Comment by msrini-MSFT** [comment]
@comnam90 , Does Azure Stack has only one policy configured? i.e ECP384 ?

Doesn't it have multiple policies ?

**Comment by comnam90** [comment]
> @comnam90 , Does Azure Stack has only one policy configured? i.e ECP384 ?
> 
> Doesn't it have multiple policies ?

If it does, it didn't negotiate them. 
The release notes suggest there is only 1 default policy with 1910
https://docs.microsoft.com/en-us/azure-stack/operator/release-notes?view=azs-1910#improvements

**Comment by msrini-MSFT** [comment]
@sethmanheim, Can you update the doc with the Azure VPN IPSec Parameters that needs to be configured in the Public cloud to establish the connectivity ?

**Comment by comnam90** [comment]
@sethmanheim Any progress on this?

**Comment by sethmanheim** [comment]
@comnam90 I am trying to verify the issue with the engineering team. It isn't clear what the documentation issue is here. I'll get back with more info ASAP.

**Comment by sethmanheim** [comment]
@comnam90 @msrini-MSFT Very sorry for the slow responses. Those parameters are documented here: https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-gateway-settings?view=azs-2002#ipsecike-parameters. I hope that's helpful.

**Comment by sethmanheim** [comment]
Going to close this issue for now, but please re-open or let us know if this doesn't help with your questions. #please-close
