### ISSUE TITLE
set-azsdnsforwarder doesn't work without unlocking the privileged endpoint

### ISSUE THREAD

**Issue by yyakushev** [MicrosoftDocs/azure-stack-docs#578]
Hello,

We have tried to change the DNS settings using set-azsdnsforwarder command but got the following error:

The term 'Test-NetConnection' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

It looks like that the command doesn't work without unlocking the privileged endpoint.

Regards,
Yaroslav

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fac9473c-1508-2b4f-0af1-2ee8f4afb385
* Version Independent ID: 166932ad-d9ae-51ec-408d-596a2ce03ca6
* Content: [Update the DNS forwarder in Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-configure-dns?view=azs-1910#feedback)
* Content Source: [azure-stack/operator/azure-stack-configure-dns.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-configure-dns.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by himanshusinha-msft** [comment]
Thanks for the feedback and bringing this to our notice . At this time we are reviewing the feedback and will update the document as appropriate .

**Comment by msrini-MSFT** [comment]
@yyakushev , can you paste the output of the command with -Debug ?

**Comment by yyakushev** [comment]
Thanks for the quick response @msrini-MSFT. 
Please find below the output of the command:

`Set-AzsDnsForwarder -IPAddress "<IP1>", "<IP2>" -Debug`
`The term 'Test-NetConnection' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`
`    + CategoryInfo          : ObjectNotFound: (Test-NetConnection:String) [Test-DnsForwarder], CommandNotFoundException`
`    + FullyQualifiedErrorId : CommandNotFoundException,Test-DnsForwarder`

**Comment by msrini-MSFT** [comment]
@yyakushev , Can you try installing the below module in your PowerShell and restart the PS and try again?

https://docs.microsoft.com/en-us/powershell/module/nettcpip/?view=win10-ps

**Comment by AzureStackNinja** [comment]
@msrini-MSFT you cannot install anything on the PEP server. When running the command from the native machine it will work. I think JEA is the problem.

**Comment by yyakushev** [comment]
@AzureStackNinja thanks for the clarification, 
I've just tried to find the command Set-AzsDnsForwarder in azurestack module on my local PS and run it remotely, but I have not able to find it. Is it only available on the PEP server?

**Comment by kongou-ae** [comment]
@yyakushev 

I tried the following command in 1910 integrated system. 

```
$PEPCreds = Get-Credential -UserName "<Azure Sack Local domain>\CloudAdmin -Message password
$PEPSession = New-PSSession -ComputerName <The ip address of ERCS> -Credential $PEPCreds -ConfigurationName "PrivilegedEndpoint"

Invoke-Command -Session $PEPSession {
    Set-AzsDnsForwarder
}
```

I can't change the setting of dns forwarder, so the option of `Set-AzsDnsForwarder` was empty. But the following result looks fine. Did you execute `Set-AzsDnsForwarder` by using PEP? 

```
cmdlet Set-AzSDnsForwarder at command pipeline position 1
Supply values for the following parameters:
IPAddress[0]: 
```

**Comment by yyakushev** [comment]
@kongou-ae
I ran the command in 1910 integrated system (1.1910.9.78) using PEP and without parameters, it asked for the IP addresses but could not set them with the same error:

`[<PEP_IP>]: PS> Set-AzsDnsForwarder
cmdlet Set-AzSDnsForwarder at command pipeline position 1
Supply values for the following parameters:
IPAddress[0]: <IP1>
IPAddress[1]: <IP2>
IPAddress[2]: 
The term 'Test-NetConnection' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Test-NetConnection:String) [Test-DnsForwarder], CommandNotFoundException
    + FullyQualifiedErrorId :  [CommandNotFoundException,Test-DnsForwarder]
`

**Comment by kongou-ae** [comment]
@yyakushev Thank you for more clarification. I tried to configure dns forwarders which are as same as current dns forwarders with `Set-AzSDnsForwarder` and encountered same error. I believe that your operation are correct and ERCS has a issue of `Set-AzSDnsForwarder`. You need to open SR to MIcrosoft support to mitigate this issue.

**Comment by yyakushev** [comment]
Thank you all for your help. 
I will open the support ticket to mitigate this issue.
