### ISSUE TITLE
support question

### ISSUE THREAD

**Issue by marcus1258** [MicrosoftDocs/azure-stack-docs#591]
So does this page indicate that Microsoft will officially support iSCSI storage on Azure Stack if a support question or concern arises?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbda96b7-f21d-f350-b887-e13b9125d4d1
* Version Independent ID: cc717953-6370-7f6d-56f3-88b4934d5f99
* Content: [How to connect to iSCSI storage with Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-howto-iscsi-storage?view=azs-1910#feedback)
* Content Source: [azure-stack/user/azure-stack-network-howto-iscsi-storage.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-network-howto-iscsi-storage.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@marcus1258 Azure Stack can connect to iSCSI storage; however your OEM would support your hardware. I have a question to support in case to find out more detail. Thanks! Matt #in-progress

**Comment by KrishnaG-MSFT** [comment]
@mattbriggs Thanks for the quick response. :+1:

**Comment by mattbriggs** [comment]
#please-close
