### ISSUE TITLE
The page seems to have singled out

### ISSUE THREAD

**Issue by rammalkani** [MicrosoftDocs/azure-stack-docs#594]
This page appears to have singled out from the Table of Contents on the left.
This should fall under Manage Updates -&gt; Monitor Update Status

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c3ea68c-8ec6-57e7-d12b-25ee757d8e39
* Version Independent ID: ca7e2ace-eb8a-de4f-39a8-b8d9c72562e6
* Content: [Monitor updates in Azure Stack Hub using the privileged endpoint - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-monitor-update?view=azs-1910#feedback)
* Content Source: [azure-stack/operator/azure-stack-monitor-update.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-monitor-update.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by KrishnaG-MSFT** [comment]
@rammalkani Thanks for the feedback.
Assigning @mattbriggs for visibility, review and document enhancement consideration.

**Comment by mattbriggs** [comment]
@rammalkani Thanks for your feedback. I"m able to replicate the issue by clicking your link.

However in looking at the table-of-contents and topic, I see that the topic is already in the table-of-contents and linked.
     
![image](https://user-images.githubusercontent.com/1634646/72550632-01f73380-3848-11ea-930c-404bea7575b4.png)

I am not able to replicate this issue with other topics. I"m following up with our doc build engineers to see if I can figure out what is causing this issue. In the meantime, I'm going to close this item.

If you see find other pages that are not opening to the entry in the table-of-contents, please let me know. Thanks for providing this info.

#please-close

**Comment by mattbriggs** [comment]
Issue was two topics with slightly different management tools (PEP vs PowerShell via Admin endpoints). Clarified in the TOC and added the missing topic. Thanks again.
