### ISSUE TITLE
Built-in role

### ISSUE THREAD

**Issue by Makovec** [MicrosoftDocs/azure-stack-docs#599]
There already exists built-in role called "Azure Stack Registration Owner" but has lower rights than the one described in this article. Which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aacc015e-fe7c-e95a-f8e4-def1a4fb91e2
* Version Independent ID: 35d53d5c-0f68-69fa-7b6c-1bae8d3b9b8e
* Content: [Create a custom role for Azure Stack Hub registration - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-registration-role?view=azs-1910#feedback)
* Content Source: [azure-stack/operator/azure-stack-registration-role.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-registration-role.md)
* Service: **azure-stack**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by MohitVerma-MSFT** [comment]
Hello @Makovec ,

Thank you for your feedback! We will review and provide an update as appropriate.

**Comment by TravisCragg-MSFT** [comment]
@Makovec Use the one described in this document. The [Azure Stack Registration Owner](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#azure-stack-registration-owner) role does not contain the correct permissions to register Azure Stack Hub, only to read & manage existing registrations. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
