### ISSUE TITLE
Azure Infrastructure Backup

### ISSUE THREAD

**Issue by joseq-terawe** [MicrosoftDocs/azure-stack-docs#6]
Under the section Enable backup on 1901 and beyond using certificate, it seems like there is a mismatch on the path location and the name of the cert file. after creating the cert, it is then exported to the directory called "certs" on the C: drive. Then when running the final line of code the encryptioncertpath is set to c:\temp\cert.cer
this is confusing as in the earlier portion of code the cert was exported and saved as "AzSIBCCert.cer". I then changed path to c:\certs\AzSIBCCert.cer and the final line of code worked but now I get a failed backup warning when trying the "BackUp Now" through the admin portal. am I missing something or overlooking a step?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25dd0267-d611-f945-3008-a036315185d8
* Version Independent ID: e17c0e82-09d3-21ff-acaf-b08fa2691890
* Content: [Enable Backup for Azure Stack with PowerShell](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-backup-enable-backup-powershell)
* Content Source: [articles/azure-stack/azure-stack-backup-enable-backup-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-backup-enable-backup-powershell.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by TravisCragg-MSFT** [comment]
@joseq-terawe Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
