### ISSUE TITLE
Jenkins ?

### ISSUE THREAD

**Issue by vmaruthi** [MicrosoftDocs/azure-stack-docs#61]
Do you have a sample implementation using Jenkins ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e54ed0-e139-1569-adc8-1833de468eb9
* Version Independent ID: 0b03d258-e1ee-e59b-997f-e9096c6f53e2
* Content: [Deploy your app to Azure and Azure Stack](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-pipeline#feedback)
* Content Source: [azure-stack/user/azure-stack-solution-pipeline.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-solution-pipeline.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@vmaruthi I do not believe that there is a current example using Jenkins at this time. 

It is possible to get Azure Stack working with Jenkins, but it will require some custom networking configuration. You can refer to [This Post](https://social.msdn.microsoft.com/Forums/en-US/ee5d86ba-1594-45cf-a410-41be97d7178c/azure-stack-service-principal-authentication-from-jenkins-server-using-proxyserver-not-working) for more info. Also the [Azure Jenkins Plugin does not suppport Azure Stack at this time](https://issues.jenkins-ci.org/browse/JENKINS-52489). 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
