### ISSUE TITLE
Change word "Engine" for "Image"

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#610]
in sentence "The AKS Base Engine must be available in your Azure Stack Hub Marketplace" replace word "Engine" for "Image". It should read "The AKS Base Image must be available in your Azure Stack Hub Marketplace"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d8c6cbd-54d8-9746-a1f8-a618b98e011e
* Version Independent ID: 479c631e-b7a4-c5cf-160d-141d336ad50a
* Content: [Install the AKS engine on Linux in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux?view=azs-1910#feedback)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov updating...

**Comment by mattbriggs** [comment]
Updated. Here is the PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/2589

Thanks, Matt

**Comment by mattbriggs** [comment]
#sign-off
