### ISSUE TITLE
Ambiguous location given for On Demand log collection

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#613]
In Section: Use Help and Support to collect diagnostic logs on demand
Step 1: Open Help and Support Overview and click Collect logs now.

Actual location: Help + Support -&gt; Log Collection -&gt; Collect Logs Now

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b13cf4d7-5d49-3f3a-3fae-3d12f40a695f
* Version Independent ID: 2a5b7922-ff52-4923-4d7e-ded60075394b
* Content: [Collect Azure Stack Hub diagnostic logs on demand - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-configure-on-demand-diagnostic-log-collection?view=azs-1910)
* Content Source: [azure-stack/operator/azure-stack-configure-on-demand-diagnostic-log-collection.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-configure-on-demand-diagnostic-log-collection.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by alexsmithMSFT** [comment]
![image](https://user-images.githubusercontent.com/26260056/73391756-8b761f00-42a6-11ea-9180-5f518e12fb15.png)

**Comment by TravisCragg-MSFT** [comment]
@alexsmithMSFT Thanks for the feedback! I updated this issue to the correct page, and assigned the issue to the content author to evaluate and update as appropriate.

**Comment by myoungerman** [comment]
@alexsmithMSFT @TravisCragg-MSFT Fixed this. Thanks!

**Comment by TravisCragg-MSFT** [comment]
@alexsmithMSFT We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
