### ISSUE TITLE
Is it possible to get an authentication token from other identity providers or principals?

### ISSUE THREAD

**Issue by easyveazie** [MicrosoftDocs/azure-stack-docs#616]
If it's supported, can we clarify how to get an auth token from:
- AzureAD with a service principal

- AD FS with user account
- AD FS with Graph application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2f49e9-8b48-9023-11ea-db3bc03da21b
* Version Independent ID: 9dab4ae8-692e-5d63-e6fc-7d173cf98084
* Content: [Make API requests to Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-rest-api-use?view=azs-1910)
* Content Source: [azure-stack/user/azure-stack-rest-api-use.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-rest-api-use.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Mike-Ubezzi-MSFT** [comment]
@easyveazie Thank you for your inquiry. I have assigned this to an engineer supporting this service area who will be able to help with this issue.

**Comment by TravisCragg-MSFT** [comment]
@easyveazie Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
Sorry, this is an old issue. If it's still relevant, please re-open. #please-close
