### ISSUE TITLE
Custom Image Windows Server 2016 with Microsoft .NET 3.5.1 SP1. Can't selected in App Service Wizard

### ISSUE THREAD

**Issue by DenBir** [MicrosoftDocs/azure-stack-docs#620]
In Docs "**Complete the offline installation of Azure App Service on Azure Stack Hub**" is a information for:  Azure App Service on Azure Stack Hub requires that Microsoft .NET 3.5.1 SP1 be activated on the image used for deployment. Marketplace-syndicated Windows Server 2016 images don't have this feature enabled. Therefore, you must create and use a Windows Server 2016 image with this feature pre-enabled.

We've also upload a custom Windows Server 2016 image with .net 3.5 installed.
The image can we successful deploy over the marketplace.

But we can't select the custom image in App Service 1.8 Wizard > Select Platform Image.
![2020-02-03 16_04_37-Clipboard](https://user-images.githubusercontent.com/42352926/73664185-4899ba00-469f-11ea-9dcf-5134414f7f36.png)

**How does the wizard filter the correct images?**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d3eb0a6-9a55-cbbe-c4d2-fa8ed7a610c7
* Version Independent ID: bbdaa561-13cf-d852-36db-b1845495e9ab
* Content: [Deploy Azure App Service in an offline environment in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-deploy-offline?view=azs-1910)
* Content Source: [azure-stack/operator/azure-stack-app-service-deploy-offline.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-deploy-offline.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by TravisCragg-MSFT** [comment]
@DenBir you can add a custom image to the marketplace [using these instructions](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-add-vm-image?view=azs-1910#step-3-option-1-add-the-vm-image-as-an-azure-stack-hub-operator-using-the-portal). 

Make sure that the following values are correct:

Publisher = MicrosoftWindowsServer
Offer = WindowsServer
SKU = 2016-Datacenter

Once it is successfully in the marketplace, check to see if it can be found. You might need to re-start the installer.

**Comment by DenBir** [comment]
Thanks @TravisCragg-MSFT for your quick response and feedback.

I've deploy a new Image with the following values:
Publisher = MicrosoftWindowsServer
Offer = WindowsServer
SKU = 2016-Datacenter
Version = 2016.127.20191231 (LATEST)

The App Service Wizard show the same Image type: latest

With version 2016.127.20191231 is this the "latest" 2016-Datacenter Image and we can successful deploy AppService!

Please add this information to the docs:

Make sure that the following values are correct:
Publisher = MicrosoftWindowsServer
Offer = WindowsServer
SKU = 2016-Datacenter
version: "latest"

**Comment by BryanLa** [comment]
@DenBir - thanks very much for your contribution. I've updated the NOTE block in the doc, with a pointer to the article and the Publisher/Offer/SKU/version values. The changes will go public around 3pm PST today/Tuesday.

Adding @apwestgarth for awareness.

#please-close
