### ISSUE TITLE
Page deletion

### ISSUE THREAD

**Issue by jbpaux** [MicrosoftDocs/azure-stack-docs#625]
Wouldn't it be great to delete this page in new release as this configuration is now established for more than 1 year and a half ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8364a423-33bd-08ae-73a2-6076a833d7be
* Version Independent ID: 5429035c-a7d9-61d4-068d-e3784a7f4839
* Content: [Prepare for extension host in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-extension-host-prepare?view=azs-1910)
* Content Source: [azure-stack/operator/azure-stack-extension-host-prepare.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-extension-host-prepare.md)
* Service: **azure-stack**
* GitHub Login: @IHenkel
* Microsoft Alias: **inhenkel**

**Comment by TravisCragg-MSFT** [comment]
@jbpaux Those who are running older versions and want to add a new node will still need this document. If that changes this doc will be removed. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by jbpaux** [comment]
@TravisCragg-MSFT nobody is running older versions as Microsoft only supports N-2 max version. So currently the latest supported version is 1907 which is one year ahead of this change so litterally nobody is still using versions where hosting extension is not used
