### ISSUE TITLE
Comparison Should include Azure Stack Edge

### ISSUE THREAD

**Issue by SumeshP** [MicrosoftDocs/azure-stack-docs#639]
this Comparison Should include Azure Stack Edge for completeness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afda862d-5084-45c0-43d6-fa1cf6723e2a
* Version Independent ID: 12cb954d-fd9d-0877-6437-31bdd292abb2
* Content: [Differences between global Azure, Azure Stack Hub, Azure Stack HCI - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/compare-azure-azure-stack?view=azs-1910)
* Content Source: [azure-stack/operator/compare-azure-azure-stack.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/compare-azure-azure-stack.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by KrishnaG-MSFT** [comment]
@SumeshP Thanks for the feedback.
Assigning content owner @Justinha for visibility, review and document enhancement consideration as appropriate.

**Comment by SychevIgor** [comment]
All 3 Edge options. Edge zones, private edge zones, carrier edge zone
https://azure.microsoft.com/en-us/blog/microsoft-partners-with-the-industry-to-unlock-new-5g-scenarios-with-azure-edge-zones/

**Comment by SychevIgor** [comment]
@KrishnaG-MSFT @Justinha any news/plans?

**Comment by mattbriggs** [comment]
@sethmanheim

**Comment by sethmanheim** [comment]
Hi @KrishnaG-MSFT, can you please assign this issue to me? Thanks!

**Comment by sethmanheim** [comment]
@SumeshP Thank you for reaching out and sorry for the slow response. We do have this on our list to update. If you still need assistance, please open a new feedback request. #please-close
