### ISSUE TITLE
AzureRm? Really?

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/azure-stack-docs#643]
Please update to no-longer-new 'Az' cmdlets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a3d35c1-9e1b-c3ae-06f1-af0402ac24e2
* Version Independent ID: a3006cac-6a67-c14e-125f-c816d38df6ed
* Content: [Create a Windows Server VM by using PowerShell in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-quick-create-vm-windows-powershell?view=azs-1910)
* Content Source: [azure-stack/user/azure-stack-quick-create-vm-windows-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-quick-create-vm-windows-powershell.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@jtuliani Azure Stack Hub hasn't release the Az cmdlets yet.

#please-close
