### ISSUE TITLE
Export and then import the Azure Stack Hub certificate

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-stack-docs#648]
Where the AzureStackSelfSignedRootCert can be found, what is the "Azure Stack Hub host machine" ?
It is not clear for me, from where we should export the certificate. Thanks!

https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-storage-connect-se?view=azs-1910#export-and-then-import-the-azure-stack-hub-certificate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aa954f6-471e-fb07-ad81-d3c389b8d1ea
* Version Independent ID: c80b0c02-9292-c5e1-d7df-c37db7aa2c42
* Content: [Connect Storage Explorer to an Azure Stack Hub subscription or a storage account - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-storage-connect-se?view=azs-1910#export-and-then-import-the-azure-stack-hub-certificate)
* Content Source: [azure-stack/user/azure-stack-storage-connect-se.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-storage-connect-se.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@HassanAlmanasrah Thanks for your feedback. I provide some instructions directly, but need to validate with the product team to check their accuracy and to get an update to make the disconnected scenario clearer. Thanks, Matt #in-progress

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
@HassanAlmanasrah The product team updated the page, whcih is in progress. You can,. "Open mmc.exe on an Azure Stack Hub host machine, or a local machine with a VPN connection to Azure Stack Hub." Note this means _any_ machine in the environment. The instructions are using mmc.exe, so to use these instructions you would want to use a Windows machine. Thanks again for your feedback.

**Comment by mattbriggs** [comment]
#please-close
