### ISSUE TITLE
Is this page still up to date ? 

### ISSUE THREAD

**Issue by Ilkoboy** [MicrosoftDocs/azure-stack-docs#650]
Is this page still up to date ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afda862d-5084-45c0-43d6-fa1cf6723e2a
* Version Independent ID: 12cb954d-fd9d-0877-6437-31bdd292abb2
* Content: [Differences between global Azure, Azure Stack Hub, Azure Stack HCI - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/compare-azure-azure-stack?view=azs-1910#feedback)
* Content Source: [azure-stack/operator/compare-azure-azure-stack.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/compare-azure-azure-stack.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by TravisCragg-MSFT** [comment]
@Ilkoboy This describes the high level differences between the 3 products, and it is still up to date. 

Even though the date lists as last May, there have been 10 updates to this page in the past month. 

Did you have a specific question about what is discussed in this doc?

**Comment by TravisCragg-MSFT** [comment]
@Ilkoboy We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
