### ISSUE TITLE
TLS 1.1 on MYSQL RP and Azure Stack ? 

### ISSUE THREAD

**Issue by eric-jenouvrier** [MicrosoftDocs/azure-stack-docs#655]
TLS 1.1 on Mysql ? https://docs.microsoft.com/en-gb/azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers?view=azs-1910#security-considerations-for-mysql

Is it relevant ? MYSQL support TLS 1.2 : https://dev.mysql.com/doc/refman/5.7/en/encrypted-connection-protocols-ciphers.html

SQL Database PaaS Service on Azure Stack in on TLS 1.2 : https://docs.microsoft.com/en-gb/azure-stack/operator/azure-stack-sql-resource-provider-hosting-servers?view=azs-1910#additional-security-information

Azure Stack is providing feature to allow Azure STack Hub Cloud Operator to schedule and enforce TLS 1.2 : https://docs.microsoft.com/en-gb/azure-stack/operator/azure-stack-security-configuration?view=azs-1910#tls-version-policy

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9da7c95f-1749-8818-f96f-c4ae02aa28a6
* Version Independent ID: db6e924d-d8c0-72bc-b0e3-382373ee7588
* Content: [Add MySQL hosting servers in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-gb/azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers?view=azs-1910#security-considerations-for-mysql)
* Content Source: [azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-mysql-resource-provider-hosting-servers.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BharathNimmala-MSFT** [comment]
@eric-jenouvrier  Thank you for your query, our team will further look into it and get back to you at the earliest.

**Comment by TravisCragg-MSFT** [comment]
@eric-jenouvrier It is recommended to use TLS 1.1 for MySQL RP on Azure Stack. See #457 for more info.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
