### ISSUE TITLE
Known issue missing

### ISSUE THREAD

**Issue by raluca256** [MicrosoftDocs/azure-stack-docs#66]
Hello, we have a known issue on this release and previous ones that was never published: Unable to remove Scale Sets via the "Virtual Machine Scale Sets" blade in the portal. The Scale set's blade or PowerShell can be used as workaround. Can this be added to the known issues list? Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfeb25b3-a85d-ac1f-1b2f-d7f95d8b196c
* Version Independent ID: 381939cb-8180-c365-6271-91522b6821b9
* Content: [Azure Stack release notes - known issues in 1904](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-release-notes-known-issues-1904)
* Content Source: [azure-stack/operator/azure-stack-release-notes-known-issues-1904.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-release-notes-known-issues-1904.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by YutongTie-MSFT** [comment]
@raluca256 
Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@raluca256 Can you reference a Support Request # or any other context where this was worked on?

Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
This is being dealt with through the proper channels and not in GitHub issues in the public repo. #please-close

**Comment by TravisCragg-MSFT** [comment]
@raluca256 We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
