### ISSUE TITLE
an error in Register tenants for usage tracking in Azure Stack Hub

### ISSUE THREAD

**Issue by Donnie-Zhang** [MicrosoftDocs/azure-stack-docs#663]
https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-csp-ref-operations.md#powershell

Use the New-AzureRmResource cmdlet to add a tenant. **Connect to Azure Stack Hub**, and then from an elevated prompt use the following cmdlet:

We should connect to **public Azure** instead of **Azure Stack Hub** before running the command New-AzureRmResource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b9c1529-af2a-1be0-4b24-910ec0d2d4ec
* Version Independent ID: 743ed0e9-478c-9d69-fa04-07a314b8ef07
* Content: [Register tenants for usage tracking in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-csp-ref-operations?view=azs-1910)
* Content Source: [azure-stack/operator/azure-stack-csp-ref-operations.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-csp-ref-operations.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SaurabhSharma-MSFT** [comment]
@Donnie-Zhang Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by sethmanheim** [comment]
Hi @Donnie-Zhang and sorry for the long delay in processing this. We will add this to the referenced article, specifying that you must connect to public Azure instead of Azure Stack Hub before running the command New-AzureRmResource. Thanks again for the feedback! #please-close
