### ISSUE TITLE
Connection name

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-stack-docs#666]
I would love to know why connection ends with 6 & 16 in the PS script, I was asked many times from the customers. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d6ea47-e076-e8ca-04b8-caf60a394879
* Version Independent ID: 55f706e5-2200-ec76-9703-f507f029a5bd
* Content: [Configure IPsec/IKE site-to-site VPN connections - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-s2s?view=azs-1910)
* Content Source: [azure-stack/user/azure-stack-vpn-s2s.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-vpn-s2s.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@HassanAlmanasrah Are you referring to the number after the forward slash in IP addresses, or the variable names? The number after the forward slash is the subnet mask.

**Comment by TravisCragg-MSFT** [comment]
@HassanAlmanasrah the variable "$Connection16" and the string value "VNet1toSite6" are just names, and you can change them to be any valid string. 

@sethmanheim these values do seem strange, as they imply the existence of 15 other connections, and 5 other sites.

**Comment by TravisCragg-MSFT** [comment]
@HassanAlmanasrah Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@HassanAlmanasrah As these are the subnet masks, please let us know if you have further questions. If so, please open a new issue and we will assign it to the engineering team. Thanks again for the feedback! #please-close
