### ISSUE TITLE
Subnet size

### ISSUE THREAD

**Issue by Rygorazd** [MicrosoftDocs/azure-stack-docs#674]
is this correct size for subnet? 
WorkersSubnet /21

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Prerequisites for deploying Azure App Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started?view=azs-1910)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by TravisCragg-MSFT** [comment]
@Rygorazd That does seem quite large. Let me follow up with this.

**Comment by TravisCragg-MSFT** [comment]
@Rygorazd This size is correct. It is for all workers that could be potentially deployed to the azure stack RP. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
