### ISSUE TITLE
Worth mentioning contentType

### ISSUE THREAD

**Issue by AndreasFrangopoulos** [MicrosoftDocs/azure-stack-docs#678]
Worth mentioning on this page that the contentType of the secret cannot be set as anything except PFX. Setting it arbitrarily cost me two days of troubleshooting as ARM gives a misleading error about not being able to decode the data property or that the password is incorrect.  The about_Secrets doc page gives the impression that the secret contentType field is for us as consumers and mostly ignored by Azure APIs but in this case that isn't true.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8e492f7-56f4-6838-f498-35fdb47530de
* Version Independent ID: 9fa5f288-f002-af8f-9601-201f1d34c36d
* Content: [Deploy a VM with a securely stored certificate on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-key-vault-push-secret-into-vm?view=azs-1910#feedback)
* Content Source: [azure-stack/user/azure-stack-key-vault-push-secret-into-vm.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-key-vault-push-secret-into-vm.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by MarileeTurscak-MSFT** [comment]
@AndreasFrangopoulos 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TravisCragg-MSFT** [comment]
@AndreasFrangopoulos Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
Hi @AndreasFrangopoulos and sorry for the long delay in responding. As you can see we have added some notes, and I will also make sure to add this information to the doc page you referenced. Again, thanks for your feedback! #please-close
