### ISSUE TITLE
Support for AD FS on Server 2019

### ISSUE THREAD

**Issue by jgallucci32** [MicrosoftDocs/azure-stack-docs#694]
Will the deployment work with AD FS deployed using Server 2019 or will that require official support/documentation for it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d295c322-0813-e159-e6f8-86f04b759c48
* Version Independent ID: 02b87d3f-125b-d674-b750-79dbaee5e497
* Content: [Integrate AD FS identity with your Azure Stack Hub datacenter - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-identity?view=azs-2002)
* Content Source: [azure-stack/operator/azure-stack-integrate-identity.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-identity.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by TravisCragg-MSFT** [comment]
@jgallucci32 Let me follow up to make sure that 2019 is not supported. It might be possible to get this working for 2019 even if it is not supported.

**Comment by jbpaux** [comment]
It's working fine and we got support after asking, just doc is outdated

**Comment by mattbriggs** [comment]
@jgallucci32 Thanks for your comment. I'm updating and it will go live after being reviewed. Thanks! Matt #in-progress

**Comment by jbpaux** [comment]
I think you can close this issue as latest version of the doc has 2019 https://github.com/MicrosoftDocs/azure-stack-docs/commit/7b40e04737a754d4c0591905660db9d45c588f41#diff-7ae253ef63b63fbcbc40f0550123cac1

**Comment by TravisCragg-MSFT** [comment]
@jbpaux Thanks for the update! 

@jgallucci32 We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
