### ISSUE TITLE
Which resouces are included in /27 outbound

### ISSUE THREAD

**Issue by stevenzhou2006** [MicrosoftDocs/azure-stack-docs#695]
Does the fixed /27 having the same list of end points which are allowed inbound? Please provide a list of VMs/endpoints need outbound Azure accessing, but not a simple /27.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d02f93-1ae9-eb2d-9c0f-0af012653885
* Version Independent ID: 18f15ad2-ef9b-f883-c49b-09289a2e6fb8
* Content: [Publish Azure Stack Hub services in your datacenter - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-endpoints?view=azs-1910)
* Content Source: [azure-stack/operator/azure-stack-integrate-endpoints.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-endpoints.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by TravisCragg-MSFT** [comment]
@stevenzhou2006 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by IngridAtMicrosoft** [comment]
In review

**Comment by IngridAtMicrosoft** [comment]
#please-close
