### ISSUE TITLE
premium block blob support?

### ISSUE THREAD

**Issue by Chai-NED** [MicrosoftDocs/azure-stack-docs#698]
Does Azure Stack HUB support premium block blob? It is not clear from this quote from above "Can be provisioned, but no performance limit or guarantee. Would not block using block blobs, append blobs, tables and queues in premium storage accounts." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ef3d725-6a5b-9799-8fe9-b9c6f0e56a6e
* Version Independent ID: c2ba5b5e-1582-953b-cc5f-07b382d94a54
* Content: [Azure Stack Hub storage differences and considerations - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-acs-differences?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-acs-differences.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-acs-differences.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@Chai-NED Thanks again for your question. This indicates that Azure Stack Hub allows you to use Premium block blobs. However, the performance is not guaranteed. This likely depends on your instance of Azure Stack Hub and how your cloud operator has configured your system. You can find out more information about managing the storage infrastructure on Azure Stack Hub in the operator content: https://docs.microsoft.com/azure-stack/operator/azure-stack-storage-infrastructure-overview?view=azs-2002

**Comment by mattbriggs** [comment]
#please-close
