### ISSUE TITLE
Missing permissions that need to be included in the JSON config for the registration role

### ISSUE THREAD

**Issue by dilutedspine** [MicrosoftDocs/azure-stack-docs#702]
"Microsoft.Authorization/locks/write" needs to be included in the permissions otherwise you get an AuthorizationFailed error when trying to perform the AzRegistration with the created service account due to missing the "Microsoft.Authorization/locks/write" permissions with the service user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aacc015e-fe7c-e95a-f8e4-def1a4fb91e2
* Version Independent ID: 35d53d5c-0f68-69fa-7b6c-1bae8d3b9b8e
* Content: [Create a custom role for Azure Stack Hub registration - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-registration-role?view=azs-2002#feedback)
* Content Source: [azure-stack/operator/azure-stack-registration-role.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-registration-role.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by femsulu** [comment]
Thanks for your comment. The feedback has been shared with the content owner for further review. Thanks for your patience.

**Comment by IngridAtMicrosoft** [comment]
In-review

**Comment by IngridAtMicrosoft** [comment]
This change has been completed.

**Comment by femsulu** [comment]
thanks @IngridAtMicrosoft . Closing this thread based on the above.
