### ISSUE TITLE
Standard_F64s_v2 failed to be deployed

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-stack-docs#703]
It seems that VM vCPU depends on the number of Cores per node, as for systems with Cores or logical processor less than 64 do not support VM size Standard_F64s_v2. 
If this is correct, I think it might be good to have this stated in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab1df1a4-dba7-3a66-dce4-88028f9b663d
* Version Independent ID: 3f33cd0e-cb7f-87e8-f201-872148031f4d
* Content: [VM sizes supported in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vm-sizes?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-vm-sizes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-vm-sizes.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by femsulu** [comment]
Thanks for your comment. The feedback has been shared with the content owner for further review. Thanks for your patience.

**Comment by mattbriggs** [comment]
@HassanAlmanasrah Thanks for your note. I have a question to the technical team and will update based on their guidance. #in-progress

**Comment by mattbriggs** [comment]
@HassanAlmanasrah Yes it is correct. I'll update Thanks! Matt

#please-close
