### ISSUE TITLE
If an AAD Service Principal is used, Internet access is required from the cluster VMs

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#704]
Add the following to the "Service Principal" requirement description: "If an Azure Active Directory (AAD) Service Principal identity is used, Internet access is required from the Virtual Machines in the Kubernetes cluster so that the Service Principal can be authenticated with AAD. If there is no internet access, the Kubernetes cluster will not be functional"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a537721-93a2-202f-abf5-6d0fe560fef0
* Version Independent ID: 676263bc-6c11-4fd4-0318-5d2504c1b014
* Content: [Set up the prerequisites for the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-set-up?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-set-up.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-set-up.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by femsulu** [comment]
Thanks for your comment. We are actively investigating and will get back to you shortly. Thanks for your patience.

**Comment by mattbriggs** [comment]
@walterov I've added the text to the SPN row in the prereq. It should appear in the next build.

**Comment by mattbriggs** [comment]
#please-close
