### ISSUE TITLE
Add maximum agent VM count to 50 nodes per subscription

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#708]
In step 8 "In agentPoolProfiles update", add to the description the following text "... The maximum count of nodes to use per subscription is 50. If you are deploying more than one cluster per subscription ensure that the total agent count does not go beyond 50"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9652b7b-09b9-ace9-4ef7-abc413b9d52c
* Version Independent ID: 53c19bb0-3f77-d15c-87e2-33e1d442d73b
* Content: [Deploy a Kubernetes cluster with the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by walterov** [comment]
UPDATE to the text: "... The maximum count of nodes to use per subscription is 50. If you are deploying more than one cluster per subscription ensure that the total agent count does not go beyond 50. Make sure to use the configuration items specified in this sample api model json file <https://github.com/Azure/aks-engine/blob/master/examples/azure-stack/kubernetes-azurestack.json>"

**Comment by mattbriggs** [comment]
@walterov Update in progress. Thanks! Matt

https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/3115

#sign-off

**Comment by mattbriggs** [comment]
@TravisCragg-MSFT The topic has been updated. Thanks!

#please-close
