### ISSUE TITLE
Azure Stack Powershell versions are incompatible while you are deploying Azure Stack SQLaaS (Integrated Systems)

### ISSUE THREAD

**Issue by bsezgin** [MicrosoftDocs/azure-stack-docs#71]
Because Azure RM powershell 2.4.0 version doesn't allow to use hybrid profile, Azure RM powershell 2.3.0 should be used with custom script deployment. Additionaly, since Azure Stack powershell 1.7.0 is incompatible with Azure RM 2.3.0, Azure Stack powershell 1.5.0 or 1.6.0 must be used in conjunction with Azure RM 2.3.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Before you deploy App Service on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started#feedback)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **anwestg**

**Comment by TravisCragg-MSFT** [comment]
@bsezgin this looks like a duplicate of your other issues, so we will continue the discussion on those issues.
