### ISSUE TITLE
Need to change this AKS icon with "preview" label to one without "preview" label

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#710]
The icon in this section https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-solution-template-kubernetes-cluster-add?view=azs-2002#add-kubernetes-to-the-marketplace
needs to be change to one without the preview label

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22917ba3-bfff-619c-901e-579fa3fb18a8
* Version Independent ID: eef7b5b0-80af-2686-e507-4ac98a48760b
* Content: [Add Kubernetes to Azure Stack Hub Marketplace - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-solution-template-kubernetes-cluster-add?view=azs-2002#add-kubernetes-to-the-marketplace)
* Content Source: [azure-stack/operator/azure-stack-solution-template-kubernetes-cluster-add.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-solution-template-kubernetes-cluster-add.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks. I've updated the screenshot. Thanks, Matt

**Comment by mattbriggs** [comment]
#please-close
