### ISSUE TITLE
Add-ADFSRelyingPartyTrust requires TLS1.2 enforcement with 2002 and later

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#715]
If using Azure Stack Hub version 2002 or greater, when executing Add-ADFSRelyingPartyTrust on the ADFS host/farm, you must first ensure that TLS1.2 is enforced on the ADFS host/farm else the attempt will result in the following error message:

Add-ADFSRelyingPartyTrust : The underlying connection was closed: An unexpected error occurred on a send.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d295c322-0813-e159-e6f8-86f04b759c48
* Version Independent ID: 02b87d3f-125b-d674-b750-79dbaee5e497
* Content: [Integrate AD FS identity with your Azure Stack Hub datacenter - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-identity?view=azs-2002#feedback)
* Content Source: [azure-stack/operator/azure-stack-integrate-identity.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-identity.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by TravisCragg-MSFT** [comment]
@aricbernard Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by IngridAtMicrosoft** [comment]
This change has been reviewed and the content has been changed.

**Comment by IngridAtMicrosoft** [comment]
#please-close
