### ISSUE TITLE
Registering Azure Stack Hub with the guest directory

### ISSUE THREAD

**Issue by LinoRS** [MicrosoftDocs/azure-stack-docs#718]
Hi MS,

is there a way to run this for all our tenants we have... like as a group or can one group all tenants ?, or does it need to be run individually for each guest on stack.
Reason why im asking i have allot of tenants that i need to run this for after each OS update etc, and to minimise any impact and save time i do this on their behalf.

thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cea6b2d3-c2a7-a7f1-2473-34c76e32c835
* Version Independent ID: b3cd3369-fdab-225e-2cc9-d90f9b5bffff
* Content: [Configure multi-tenancy in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-gb/azure-stack/operator/azure-stack-enable-multitenancy?view=azs-2002#configure-guest-directory)
* Content Source: [azure-stack/operator/azure-stack-enable-multitenancy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-enable-multitenancy.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by PramodValavala-MSFT** [comment]
@LinoRS Thanks for the question! We will review and get back to you!

**Comment by TravisCragg-MSFT** [comment]
@LinoRS This script will need to be run for each tenant individually. It should not be too difficult to script it for multiple tenants. 

Please let me know if you need any additional information.

**Comment by LinoRS** [comment]
thanks guys for the feedback, ill give it a go and see.

**Comment by TravisCragg-MSFT** [comment]
@LinoRS Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
