### ISSUE TITLE
Comparison of resource providers

### ISSUE THREAD

**Issue by ddobric** [MicrosoftDocs/azure-stack-docs#719]
It would be great and helpful to provide on this page a comparison between Azure Stack available resour ce providers vs. Azure Resource Providers. For example: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-services-resource-providers 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7365a8d-a66f-b338-117a-abbb49bb4db0
* Version Independent ID: 0e32791c-3fee-636f-27f6-37b08dfcd5b4
* Content: [Azure Stack Hub overview - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-overview?view=azs-2002)
* Content Source: [azure-stack/operator/azure-stack-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-overview.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by PramodValavala-MSFT** [comment]
@ddobric Thanks for the question! We will review and get back to you!

**Comment by TravisCragg-MSFT** [comment]
@ddobric Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@sethmanheim

**Comment by sethmanheim** [comment]
Hi @TravisCragg-MSFT, can you please assign this issue to me? Thanks!

**Comment by sethmanheim** [comment]
@PatAltimore Not sure if you want to add this to your backlog for the article, so assigning to you. #reassign:@pataltimore

**Comment by PatAltimore** [comment]
#reassign @BryanLa

**Comment by sethmanheim** [comment]
@ddobric Very sorry for the slow response. As we are moving to a new feedback system, we need to close older issues. If you still need assistance, please open a new feedback request. #please-close
