### ISSUE TITLE
Azure Stack Hub Capacity Planner (Feature Enhancement)

### ISSUE THREAD

**Issue by Marauder1568** [MicrosoftDocs/azure-stack-docs#720]
Would it be possible to include the GPU specs as a part of the Solution Partner Values? Depending on the application these calculations would be just as important. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 091e58ac-42db-d8ba-8bd9-31635f4af131
* Version Independent ID: e61fe9a3-e6d3-134e-40fe-b038240452a6
* Content: [Capacity planning overview - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-capacity-planning-overview?view=azs-2002#feedback)
* Content Source: [azure-stack/operator/azure-stack-capacity-planning-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-capacity-planning-overview.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by PramodValavala-MSFT** [comment]
@Marauder1568 Thanks for the question! We will review and get back to you!

**Comment by TravisCragg-MSFT** [comment]
@Marauder1568 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by IngridAtMicrosoft** [comment]
#in-progress

**Comment by IngridAtMicrosoft** [comment]
Program management has registered the feature enhancement.
#please-close
