### ISSUE TITLE
Custom script deployment

### ISSUE THREAD

**Issue by bsezgin** [MicrosoftDocs/azure-stack-docs#73]
Because Azure RM powershell 2.4.0 version doesn't allow to use hybrid profile, Azure RM powershell 2.3.0 should be used with custom script deployment. Additionaly, since Azure Stack powershell 1.7.0 is incompatible with Azure RM 2.3.0, Azure Stack powershell 1.5.0 or 1.6.0 must be used in conjunction with Azure RM 2.3.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f7e3b4a-30fb-4068-32b1-943cd483f531
* Version Independent ID: fc78fd4f-2626-e0b9-8ac0-7ea1938ff419
* Content: [Using MySQL databases on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-mysql-resource-provider-deploy)
* Content Source: [azure-stack/operator/azure-stack-mysql-resource-provider-deploy.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-mysql-resource-provider-deploy.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **jeffgilb**

**Comment by TravisCragg-MSFT** [comment]
@bsezgin Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate. This seems very similar to #18

**Comment by mattbriggs** [comment]
You will need to follow the instruction for installing Azure Stack PowerShell, which means you we suggest that you remove previous versions of PowerShell. https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-install. For an article about API profiles, I can point you to: https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles #please-close

**Comment by TravisCragg-MSFT** [comment]
@bsezgin We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
