### ISSUE TITLE
Dedicated vNIC for iSCSI

### ISSUE THREAD

**Issue by imamadi** [MicrosoftDocs/azure-stack-docs#730]
Can we use dedicated vNIC(s) for iSCSI rather than the default vNIC to separate storage traffic and data traffic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbda96b7-f21d-f350-b887-e13b9125d4d1
* Version Independent ID: cc717953-6370-7f6d-56f3-88b4934d5f99
* Content: [How to connect to iSCSI storage with Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-howto-iscsi-storage?view=azs-1910#feedback)
* Content Source: [azure-stack/user/azure-stack-network-howto-iscsi-storage.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-network-howto-iscsi-storage.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by BharathNimmala-MSFT** [comment]
@imamadi Thank you for your query, our team will further look into it and get back to you at the earliest.

**Comment by TravisCragg-MSFT** [comment]
@imamadi I am reaching out for an answer on this one, I will update you as soon as I am able.

**Comment by TravisCragg-MSFT** [comment]
@imamadi This is possible, and you can [find steps to add them here](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-howto-extend-datacenter?view=azs-2002#connect-to-a-windows-server-iscsi-target). 

Please let me know if you need any additional information

**Comment by mattbriggs** [comment]
@TravisCragg-MSFT  Thanks!

**Comment by TravisCragg-MSFT** [comment]
@imamadi We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
