### ISSUE TITLE
brokent link https://adminportal.local.azurestack.external/

### ISSUE THREAD

**Issue by fleisherdev** [MicrosoftDocs/azure-stack-docs#738]
https://adminportal.local.azurestack.external/ goes nowhere

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c66522-b80a-ded9-aafc-05ba2fab1877
* Version Independent ID: bdf35cf3-4685-1e96-0095-b764a2772b7a
* Content: [Configure deployment sources for App Services on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-configure-deployment-sources?view=azs-2002#feedback)
* Content Source: [azure-stack/operator/azure-stack-app-service-configure-deployment-sources.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-configure-deployment-sources.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by AjayKumar-MSFT** [comment]
@fleisherdev, Thanks for posting the question. Just to clarify, you need to access the admin portal from ASDK host machine and not locally. You have to Sign in to the Azure Stack Hub admin portal (https://adminportal.local.azurestack.external) as the service admin.
Please let us know if the issue occurs on the ASDK host machine.

**Comment by fleisherdev** [comment]
Thanks for your response.  Issue seems to be DNS related:

This site can’t be reached

*adminportal.local.azurestack.external*’s server IP address could not be
found.


   - Try running Windows Network Diagnostics.

DNS_PROBE_FINISHED_NXDOMAIN

**Comment by fleisherdev** [comment]
How do I get to the host machine? The link is in the document. Perhaps you
could provide more explicit information. I am working with AppServices and
don't  have VM's. Can this be access through Bash or SSH?

**Comment by AjayKumar-MSFT** [comment]
Thanks for sharing more details. 

**Short Answer:**  
For accessing admin portal on integrated system deployment -the address is in the format - https://adminportal.[region].[FQDN].
For accessing admin portal on ASDK- the address format is - https://adminportal.local.azurestack.external.

We will be adding this info to bring more clarity in the documentation. 

**Long Answer:** 

Just to clarify, you have two options to leverage Azure Stack: **ASDK** and **Microsoft Azure Stack Hub integrated systems**.

The Azure Stack Development Kit (ASDK) is a single-node deployment of Azure Stack that you can download and use for free (intended for non-production/testing). Whereas, Microsoft Azure Stack Hub integrated systems range in size from 4-16 nodes, and are jointly supported by a hardware partner and Microsoft (for production workloads). 

Depending on your Stack environment, access the appropriate URLs (admin or user) as mentioned below: 

**Sign in to the administrator portal:**
- For an integrated system deployment, the portal address varies based on your solution's region and external domain name. The address is in this format: https://adminportal.[region].[FQDN].

- For the Azure Stack Development Kit (ASDK), the portal address is https://adminportal.local.azurestack.external.

 
**Sign in to the user portal:**

- For an integrated system, the URL varies based on your operator's region and external domain name, and will be in the format https://portal.[region].[FQDN].

- If you're using the Azure Stack Development Kit (ASDK), the portal address is https://portal.local.azurestack.external.

-----------------------------------------------

If you're using ASDK host, which I had mentioned in my previous post - you can RDP to the host, checkout the step-step instructions outlined in this document - [Connect to the ASDK](https://docs.microsoft.com/azure-stack/asdk/asdk-connect?view=azs-2002)

Also, please refer the doc- [ASDK and multi-node Azure Stack Hub differences ](https://docs.microsoft.com/azure-stack/asdk/asdk-what-is?view=azs-2002#asdk-and-multi-node-azure-stack-hub-differences) for more details on this topic.

**Comment by BryanLa** [comment]
Thanks very much for this feedback, @fleisherdev. The article has been updated accordingly, and will republish around 10am PDT today.

CXP #please-close
