### ISSUE TITLE
1903 app update issue

### ISSUE THREAD

**Issue by bsezgin** [MicrosoftDocs/azure-stack-docs#74]
Character "_" creates a problem with the 1903  update while deploying the "Quickstart template for Highly Available File Server and SQL Server" thru the Admin Portal. Template deployment fails to start. To deploy the template successfully, use Powershell instead of admin portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Before you deploy App Service on Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* GitHub Login: @jeffgilb
* Microsoft Alias: **anwestg**

**Comment by TravisCragg-MSFT** [comment]
@bsezgin Your best bet with this is to follow up with a support request. If you do not have a support plan, please let me know. 

Have you updated your Azure Stack to 1904? There were marketplace improvements that could have resolved this issue.

**Comment by bsezgin** [comment]
Not yet but I was able to deploy the template thru powershell.

**Comment by jeffgilb** [comment]
Hi all, I believe this is a known issue and a fix is actively being worked on. The template should work as expected very soon or at least within a few days. That said, that's pretty much all I know and this is a technical issue and not a docs issue so I cannot provide additional support here.

**Comment by jeffgilb** [comment]
#please-close

**Comment by TravisCragg-MSFT** [comment]
@bsezgin We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by 0925042781** [comment]
Ok
