### ISSUE TITLE
NATVM on adsk

### ISSUE THREAD

**Issue by devalian** [MicrosoftDocs/azure-stack-docs#749]
Asdk no longer have NATVM. Is there updated way for the mapping or simply map directly to the host ip? Or no longer require altogether? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8c6b8cb-6783-9ef0-4072-fee777e6c73a
* Version Independent ID: 5a5cf46f-d186-2c32-5223-67909a3df56d
* Content: [Create a site-to-site VPN connection between two virtual networks in different ASDK environments - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-create-vpn-connection-one-node?view=azs-2002#feedback)
* Content Source: [azure-stack/operator/azure-stack-create-vpn-connection-one-node.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-create-vpn-connection-one-node.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by himanshusinha-msft** [comment]
Thanks for the ask  . At this time we are reviewing it and we will reply back as soon as we can .

**Comment by TravisCragg-MSFT** [comment]
@devalian You can find [ASDK specific instructions for a S2S VPN Here](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-connect?view=azs-2002#connect-to-azure-stack-using-vpn).  Please let me know if you have any additional questions.

**Comment by TravisCragg-MSFT** [comment]
@devalian We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
