### ISSUE TITLE
Replace step 3 in "Update API model" with the following...

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#764]
"In the kubernetes-azurestack.json file, find orchestratorRelease and orchestratorVersion. Select one of the supported Kubernetes versions. For example, for orchestratorRelease use 1.14 or 1.15 and for orchestratorVersion use 1.14.7 or 1.15.10 respectively. Specify the orchestratorRelease as x.xx and orchestratorVersion as x.xx.x. For a list of current versions, see Supported AKS engine Versions &lt;https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#supported-aks-engine-versions&gt;. " REMOVE example with aks-engine get-versions command it is confusing to customers since it for Azure Stack it is a smaller set of supported versions. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9652b7b-09b9-ace9-4ef7-abc413b9d52c
* Version Independent ID: 53c19bb0-3f77-d15c-87e2-33e1d442d73b
* Content: [Deploy a Kubernetes cluster with the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster?view=azs-2002#update-the-api-model)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@walterov Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@walterov Updated. Please see the following PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/3444

**Comment by mattbriggs** [comment]
#please-close
