### ISSUE TITLE
Replace step 1 in "Steps to upgrade to a newer Kubernetes version" with the following...

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#765]
"The versions of Kubernetes supported in the latest update are 1.14.7 and 1.15.10. Follow this table for the upgrades available:
Current Version	Upgrade available
1.14.7	1.15.10
1.14.8	1.15.10
1.15.4	1.15.10
1.15.5	1.15.10
For a complete mapping of AKS engine, AKS Base Image and Kubernetes versions see Supported AKS Engine Versions &lt;https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#supported-aks-engine-versions&gt;"
REMOVE example with aks-engine get-versions command. Thanks!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f23e9819-30aa-02a8-08af-49b92c61316b
* Version Independent ID: a0b1770c-1ddc-17b6-2461-b4d77f474ca4
* Content: [Upgrade a Kubernetes cluster on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-upgrade?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-upgrade.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-upgrade.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@walterov Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@walterov Thanks walter. I've added to the following PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/3444

#please-close
