### ISSUE TITLE
In "Add the AKS Base Image", step 5, update version value to

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#766]
AKS Base Ubuntu 16.04-LTS Image Distro, March 2020 (Version: “2020.03.19”)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfb60cd-c79d-e4c3-9015-bb3b49e1dc06
* Version Independent ID: 9a48b797-af3b-462d-94a0-07693651a488
* Content: [Add the Azure Kubernetes Services (AKS) engine prerequisites to the Azure Stack Hub Marketplace - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-aks-engine?view=azs-2002#add-the-aks-base-image)
* Content Source: [azure-stack/operator/azure-stack-aks-engine.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-aks-engine.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@walterov Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@walterov Thanks Walter. I've added to the change to the following PR:
https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/3444

#please-close
