### ISSUE TITLE
Change version references in section "Matching engine to base image version" with the following

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#768]
Change this link "Supported Kubernetes Versions" to "Supported AKS Engine Versions" and point it to &lt;https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#supported-aks-engine-versions&gt;

for aks engine use "0.48.0"

In "AKS Base image version 2019.10.24" replace with "AKS Base image version 2020.03.19"

Replace bash example of aks-engine version with
"$ aks-engine version
Version: v0.48.0
GitCommit: 44a35c00c
GitTreeState: clean"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a537721-93a2-202f-abf5-6d0fe560fef0
* Version Independent ID: 676263bc-6c11-4fd4-0318-5d2504c1b014
* Content: [Set up the prerequisites for the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-set-up?view=azs-2002#matching-engine-to-base-image-version)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-set-up.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-set-up.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@walterov Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@walterov I've updated in this PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/3444

#please-close
