### ISSUE TITLE
On Windows systems, I get an error when installing on PSCore / Windows PowerShell 5.1

### ISSUE THREAD

**Issue by dmc-tech** [MicrosoftDocs/azure-stack-docs#769]
When running my PS Core 7 or Windows PowerShell 5.1 sessions as an administrator, I get an error:
'Administrator rights are required to install or update. Log on to the computer with an account that has administrator rights...'

This can be fixed with the following:
Install-Module -Name Az.BootStrapper -Force -AllowPrerelease
Install-AzProfile -Profile 2019-03-01-hybrid -Force
Install-Module -Name AzureStack -RequiredVersion 2.0.0-preview -AllowPrerelease

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c7ec8b-634f-6b95-7ce1-c38d55b12c23
* Version Independent ID: 8cc3a38e-0bbc-71b4-2c37-fc6231bb540d
* Content: [Install PowerShell Az module for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2002#feedback)
* Content Source: [azure-stack/operator/powershell-install-az-module.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/powershell-install-az-module.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@dmc-tech the script you gave is identical to what is in [step 4 Here](https://docs.microsoft.com/en-us/azure-stack/operator/powershell-install-az-module?view=azs-2002#4-connected-install-with-internet-connectivity). Can you clarify your issue / ask?

**Comment by dmc-tech** [comment]
The doc has been updated, so the issue can be closed.  The previous version of the doc was incorrect, per my issue.

**Comment by dmc-tech** [comment]
https://github.com/MicrosoftDocs/azure-stack-docs/commit/795cd5070f791edbe4c8d62bcb5b0153b4894d8e#diff-14f616907d6d91071c237acac57e25cb

**Comment by mattbriggs** [comment]
#please-close
