### ISSUE TITLE
Add an example for scheduling update deployment for Azure Stack VMs

### ISSUE THREAD

**Issue by assing** [MicrosoftDocs/azure-stack-docs#773]
I am from Azure Update Management Product Group. Please add an example for creating update deployment schedule. Currently the schedule deployment creation from the UX won't work. It will fail. The workaround is to use cmdlet or REST api and pass these machines as nonAzure machines similar to this article for the machines which belong to different tenant. https://docs.microsoft.com/azure/automation/troubleshoot/update-management#resolution-7  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5482339c-6e7c-ba76-ca3c-d303d862bbe3
* Version Independent ID: 07b2e417-beb7-eb9e-fcf6-de595c04e9f1
* Content: [VM update and management automation in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/vm-update-management?view=azs-2002#feedback)
* Content Source: [azure-stack/user/vm-update-management.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/vm-update-management.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@assing Thanks for your comment. I'll follow up with the product team and update the docs. I'll let you know when this is posted.

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
@assing: can you review this update:
https://review.docs.microsoft.com/en-us/azure-stack/user/vm-update-management?view=azs-1802&branch=pr-en-us-3472#create-an-update-deployment-schedule

Do you know if this cmdlet will work on Azure Stack Hub with the Azure Stack Hub resource manager?

**Comment by assing** [comment]
@mattbriggs Please change this line "pass the machines in the other tenant to the" to "pass the azure stack machines to the" . We need to pass the azure stack machines to the NonAzureComputer parameter. You need to remove this line "To run this script you will need to use the preview of the Azure Stack Az module." as well. These are not Azure Stack Az module. These are standard Az module. You also need to add link to these cmdlet. The link will be same as this documentation: https://docs.microsoft.com/azure/automation/troubleshoot/update-management#resolution-7

**Comment by assing** [comment]
> Do you know if this cmdlet will work on Azure Stack Hub with the Azure Stack Hub resource manager?

@mattbriggs  It won't work azure stack hub resource manager.

**Comment by mattbriggs** [comment]
@assing Thanks. I've updated and made clear they need to use the global Azure Az module. Thanks!

**Comment by mattbriggs** [comment]
#please-close

**Comment by assing** [comment]
@mattbriggs I don't see a link for New-AzAutomationSoftwareUpdateConfiguration and New-AzAutomationSchedule. Please add a link to the cmdlet documentation for corresponding cmdlet.

**Comment by mattbriggs** [comment]
@assing added to links to the ref content via the cmdlet names.

**Comment by assing** [comment]
@mattbriggs both links are pointing to same cmdlet. Please correct the link for New-AzAutomationSoftwareUpdateConfiguration

**Comment by mattbriggs** [comment]
@assing updated. Thanks.
