### ISSUE TITLE
Estimated aggregate throughput by SKU

### ISSUE THREAD

**Issue by CarlosGon** [MicrosoftDocs/azure-stack-docs#781]
This is the Estimated throughput for each tunnel by SKU, as stated on the first Note on top of this document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f780e2ad-c126-43e9-2596-848115d09fa7
* Version Independent ID: 7e6afc9e-2803-5831-14b5-44d6fdbdb952
* Content: [Create VPN gateways for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-gateway-about-vpn-gateways?view=azs-2002#estimated-aggregate-throughput-by-sku)
* Content Source: [azure-stack/user/azure-stack-vpn-gateway-about-vpn-gateways.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-vpn-gateway-about-vpn-gateways.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@CarlosGon Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@CarlosGon @TravisCragg-MSFT I'm sorry, I don't understand what the documentation issue is here. Can you clarify?

**Comment by CarlosGon** [comment]
The values on the table are not for the aggregate value of the gateway, instead they are the values for each tunnel created under each one of the gateways (SKU).
Using the Basic Sku as example:
100Mbps is not the aggregate throughput of the Basic SKU, it is the aggregate throughput of each IPsec tunnel created inside this gateway.

**Comment by CarlosGon** [comment]
@sethmanheim @TravisCragg-MSFT I submitted a pull request with my propose of changes on the documents. Let me know your feedback

**Comment by sethmanheim** [comment]
@CarlosGon @TravisCragg-MSFT Thank you and very sorry for the delay -- this issue was never assigned to anyone. I've asked for clarification in the other PR, so let's close this one. #please-close
