### ISSUE TITLE
Gateway SKUs

### ISSUE THREAD

**Issue by CarlosGon** [MicrosoftDocs/azure-stack-docs#782]
This is the Estimated throughput for each tunnel by SKU, as stated on the first Note on top of this document https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-gateway-about-vpn-gateways?view=azs-2002

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34ea6e48-1e3a-6fc0-04a7-89e4300eecc8
* Version Independent ID: 2eff51e4-ed22-2420-7d5a-241f754b5a4e
* Content: [Configure VPN gateway settings for Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-gateway-settings?view=azs-2002#gateway-skus)
* Content Source: [azure-stack/user/azure-stack-vpn-gateway-settings.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-vpn-gateway-settings.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@CarlosGon Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@CarlosGon @TravisCragg-MSFT I'm sorry, I don't understand what the documentation issue is here. Can you clarify?

**Comment by CarlosGon** [comment]
The values on the table are not for the aggregate value of the gateway, instead they are the values for each tunnel created under each one of the gateways (SKU).
Using the Basic Sku as example:
100Mbps is not the aggregate throughput of the Basic SKU, it is the aggregate throughput of each IPsec tunnel created inside this gateway.

**Comment by TravisCragg-MSFT** [comment]
@sethmanheim @CarlosGon has posted the reason for this issue - conflicting information. If you would like I can make adjustments to the table descriptions to match the note referred to [Here](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vpn-gateway-about-vpn-gateways?view=azs-2002).

**Comment by CarlosGon** [comment]
@sethmanheim @TravisCragg-MSFT I submitted a pull request with my propose of changes on the documents. Let me know your feedback

**Comment by sethmanheim** [comment]
@CarlosGon @TravisCragg-MSFT Thank you and very sorry for the delay -- I never saw this issue as it was never assigned to anyone. I've asked for clarification in the other PR, so let's close this one. #please-close
