### ISSUE TITLE
Please update the misleading code example

### ISSUE THREAD

**Issue by poetw** [MicrosoftDocs/azure-stack-docs#792]
[Enter feedback here]
Regarding this code example:
$decryptioncertpassword = Read-Host -AsSecureString -Prompt "Password for the decryption certificate"
Restore-AzsBackup -ResourceId "<BackupID>" `
 -DecryptionCertPath "<path to decryption certificate with file name (.pfx)>" `
 -DecryptionCertPassword $decryptioncertpassword

Please update -ResourceId to -Name. The Name parameter refers to Backup Id, e.g., 0456ff88-b159-4f1e-a12e-3999efa6475d, while the ResourceId parameter refers to the actual ARM resource Id of the backup, e.g., /subscriptions/b9703725-c3be-41c9-98da-60bb505025c9/resourceGroups/System.redmond/providers/Microsoft.Backup.Admin/backupLocations/redmond/backups/0456ff88-b159-4f1e-a12e-3999efa6475d

Please help update this page to avoid customer confusion.

Thanks!
Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 880d3c99-62f9-e909-e2dc-dfa2ff0cb723
* Version Independent ID: d9adc6a8-912e-f789-2833-8610a63c6a4c
* Content: [Use the ASDK to validate an Azure Stack backup - Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-validate-backup?view=azs-2002#feedback)
* Content Source: [azure-stack/asdk/asdk-validate-backup.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-validate-backup.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by SamaraSoucy-MSFT** [comment]
Thanks for the feedback! I have assigned the issue to the doc author to update appropriately.

**Comment by mattbriggs** [comment]
@mattbriggs

**Comment by mattbriggs** [comment]
@TravisCragg-MSFT the author has left. Can you re-assign this topic to me? @mattbriggs Thanks! Matt

**Comment by mattbriggs** [comment]
@poetw Thanks for your feedback. I've updated the topic.

#please-close
