### ISSUE TITLE
AD FS 2016/2019 PowerShell Snippet

### ISSUE THREAD

**Issue by eszych** [MicrosoftDocs/azure-stack-docs#795]
Hello! 
In the section "Configure relying party on existing AD FS deployment" you have a sample PowerShell snippet for the AD FS 2016/2019 Integration. You reference the .txt file as "C:\ClaimIssuanceRules.txt" - but above the sample file you propose to save the file as "c:\ClaimRules.txt"...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d295c322-0813-e159-e6f8-86f04b759c48
* Version Independent ID: 02b87d3f-125b-d674-b750-79dbaee5e497
* Content: [Integrate AD FS identity with your Azure Stack Hub datacenter - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-identity?view=azs-1910#feedback)
* Content Source: [azure-stack/operator/azure-stack-integrate-identity.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-identity.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
@eszych - thanks for catching this and taking time to provide feedback. I've made the correction. It should republish sometime today.

#please-close
