### ISSUE TITLE
The script doesn't seem to check "Global Admin" right

### ISSUE THREAD

**Issue by ksekimoto** [MicrosoftDocs/azure-stack-docs#8]
Created an installation user account with "User" right of their tenant directory (without Global Admin). Then executed the validation script on the following url.

https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-validate-identity

 The script output was OK.
 I think that this script doesn't check "Global Admin" right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 180ae274-132e-dd31-19cf-71eac378dc21
* Version Independent ID: de499123-09f5-e6f5-176c-f63994e8f758
* Content: [Validate Azure Identity for Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-validate-identity)
* Content Source: [azure-stack/operator/azure-stack-validate-identity.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-validate-identity.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
If this is still an issue, please re-open. #please-close
