### ISSUE TITLE
1906 archive is unavailable

### ISSUE THREAD

**Issue by rammalkani** [MicrosoftDocs/azure-stack-docs#807]
The archive for 1906 is not available. Could you make the archive available on the gallery link on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0094b74f-e85b-6983-5f58-ce24f825b63c
* Version Independent ID: a90feafe-0401-3da0-bb95-4dbc8868ea0f
* Content: [Azure Stack Hub known issues - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/known-issues?view=azs-1906&source=docs#feedback)
* Content Source: [azure-stack/operator/known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/known-issues.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SadiqhAhmed-MSFT** [comment]
@rammalkani Thank you for the feedback. This issue is being assigned to the content author to evaluate and update as appropriate.

@sethmanheim FYI

**Comment by sethmanheim** [comment]
@rammalkani Thank you for your feedback! We only publish release notes for the last 4 Azure Stack Hub releases on docs.microsoft.com. If you need access to earlier versions, they are on the TechNet Gallery (https://aka.ms/azsarchivedrelnotes), which is now up to date.

**Comment by sethmanheim** [comment]
Closing this for now, please let us know if you have further questions. #please-close
