### ISSUE TITLE
Proxy Setting Typo

### ISSUE THREAD

**Issue by jorlando82** [MicrosoftDocs/azure-stack-docs#815]
Under Proxy Settings there is a missing d on /etc/system**d**/system.... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b262dce-e5b1-b335-8222-38acaf2790ee
* Version Independent ID: 3d154b9f-0ec3-840f-d09a-411ab1887483
* Content: [Deploy Azure Cognitive Services to Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-solution-template-cognitive-services?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-solution-template-cognitive-services.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-solution-template-cognitive-services.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@jorlando82 Thanks for your update. I've submitted a PR to fix the topic. Thanks! Matt

#please-close
