### ISSUE TITLE
typo Get-AzureStackLogs

### ISSUE THREAD

**Issue by chenminhua** [MicrosoftDocs/azure-stack-docs#816]
[Enter feedback here]

Several place "Get-AzureStackLogs" in this doc. I guess it should be "Get-AzureStackLog"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9791d946-d79a-6929-4e48-56eb37021c6f
* Version Independent ID: 22b2c392-7cc5-c21a-fae5-2f717ce477c2
* Content: [Use the privileged endpoint (PEP) to collect diagnostic logs - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-get-azurestacklog?view=azs-2002)
* Content Source: [azure-stack/operator/azure-stack-get-azurestacklog.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-get-azurestacklog.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by AjayKumar-MSFT** [comment]
@chenminhua,  Thanks for the feedback! We are taking a look into this and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@chenminhua Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by TravisCragg-MSFT** [comment]
@Justinha this bug is still present, let me know if I can assist.

**Comment by Justinha** [comment]
@TravisCragg-MSFT sorry for delay and thanks raising this @chenminhua . This is fixed.
