### ISSUE TITLE
This page refers to general secret rotation for the core components, Not Event Hubs RP

### ISSUE THREAD

**Issue by dmc-tech** [MicrosoftDocs/azure-stack-docs#817]
To rotate internal secrets for Event Hubs RP:
1. Install Azure PowerShell for Azure Stack Hub
2. Connect the the Admin environment for the stamp 
3. Invoke-AzsProductRotateSecretsAction -ProductId microsoft.eventhub

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4feaa2a-4850-478d-8122-7eb751ba0777
* Version Independent ID: f5cd7372-0443-3f2e-c403-ed7ba1a56146
* Content: [Rotate secrets - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-2002)
* Content Source: [azure-stack/operator/azure-stack-rotate-secrets.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-rotate-secrets.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by TravisCragg-MSFT** [comment]
@dmc-tech Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by IngridAtMicrosoft** [comment]
#in-review

**Comment by IngridAtMicrosoft** [comment]
This is a TOC issue for another author.  @TravisCragg-MSFT please assign to @BryanLa.

**Comment by BryanLa** [comment]
Thanks @IngridAtMicrosoft 
@dmc-tech - thanks much for your feedback. This is work we have planned for our June sprint. I'll update this issue again when it's completed.
#please-close
