### ISSUE TITLE
Local Properties image no longer accurate

### ISSUE THREAD

**Issue by TheOnlyWei** [MicrosoftDocs/azure-stack-docs#828]
[Enter feedback here]

I was told the image for the Region Management > Local- Properties is out-dated in the linked tutorial. The fields that currently exist for Azure Stack environment don't exist in that screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19119cef-de12-31e5-d0b6-b95f2985f57e
* Version Independent ID: 5a7921c1-ac2e-6de8-0e8d-de9f04e457a6
* Content: [Register Azure Stack Hub with Azure - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-registration?view=azs-2002&pivots=state-disconnected#verify-azure-stack-hub-registration)
* Content Source: [azure-stack/operator/azure-stack-registration.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-registration.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by MarileeTurscak-MSFT** [comment]
@TheOnlyWei 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TravisCragg-MSFT** [comment]
@TheOnlyWei Are you referring to the ASDK or a full Azure Stack installation?

**Comment by TravisCragg-MSFT** [comment]
@TheOnlyWei Since we have not heard back from you we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
