### ISSUE TITLE
Regarding the AKS Base Image and Custom Script Extensions

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#835]
For those two items, in their respective "instructions" boxes, we need to tell the user that those items are only visible to the Administrator and they need to ask the admin to make sure they have been added to the stamp. We are now hiding them from the tenant to avoid the customer using them to create VMs directly 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a537721-93a2-202f-abf5-6d0fe560fef0
* Version Independent ID: 676263bc-6c11-4fd4-0318-5d2504c1b014
* Content: [Set up the prerequisites for the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-set-up?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-set-up.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-set-up.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by MarileeTurscak-MSFT** [comment]
@walterov 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TravisCragg-MSFT** [comment]
@walterov Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
#please-close
