### ISSUE TITLE
Restore AKS Base Ubuntu March 2020 version, and update support matrix link anchor

### ISSUE THREAD

**Issue by alexsmithMSFT** [MicrosoftDocs/azure-stack-docs#837]
Per @walterov : Could we address this as an URGENT issue? It will generate support calls. 
**Version: AKS Base Ubuntu 16.04-LTS Image Distro, March 2020 (2020.03.19)**
Latest AKS Engine 0.48.0 only matches the version above: https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2002#download-new-image-and-aks-engine 

Mapping of image and aks-engine versions: https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#supported-aks-engine-versions

(Currently used anchor #supported-kubernetes-versions is broken- https://github.com/Azure/aks-engine/blob/master/docs/topics/azure-stack.md#supported-kubernetes-versions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfb60cd-c79d-e4c3-9015-bb3b49e1dc06
* Version Independent ID: 9a48b797-af3b-462d-94a0-07693651a488
* Content: [Add the Azure Kubernetes Services (AKS) engine prerequisites to the Azure Stack Hub Marketplace - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-aks-engine?view=azs-2002#add-the-aks-base-image)
* Content Source: [azure-stack/operator/azure-stack-aks-engine.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-aks-engine.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by alexsmithMSFT** [comment]
For the March 2020 base image, looks like it was added on April 24- https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/3444/files#diff-562d1057d338ff57057c1ca099b43150R57

But then reverted on April 27, when the image was temporarily rolled back-
https://github.com/MicrosoftDocs/azure-stack-docs/commit/22a8091495898ca9701b9665a8e0c494f1a188d7#diff-562d1057d338ff57057c1ca099b43150L57

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
@alexsmithMSFT @walterov Thanks for passing along this info. I've updated the links that had the old anchor and the operator topic with the right version number: https://review.docs.microsoft.com/en-us/azure-stack/operator/azure-stack-aks-engine?view=azs-1802&branch=pr-en-us-3864 You can find the pr here: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/3864

**Comment by mattbriggs** [comment]
#please-close
