### ISSUE TITLE
AzureGallery.exe generate .azpkg example command issue

### ISSUE THREAD

**Issue by Lihailian** [MicrosoftDocs/azure-stack-docs#851]
In the document, generate .azpkg command example like below:
.\AzureGallery.exe package –m c:\<path>\<gallery package name>\manifest.json –o c:\Temp

There is tiny error in the command, the "-" before **m** and **o** was not input under Eng keyboard, due to which, when we copy the command and run it, we will get error:
_C:\hailian\Azure Stack Marketplace Item Generator and Sample Templates\AzureGalleryPackageGenerator> .\AzureGallery.exe package –m C:\hailian\TW\manifest.json –o C:\hailian
.\AzureGallery.exe : The argument 'manifestfile' is required
At line:1 char:1
+ .\AzureGallery.exe package –m C:\hailian\TW\manifest.json –o C:\haili ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The argument 'manifestfile' is required:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Usage: AzureGallery <action> options

EXAMPLE: AzureGallery package [-m <path to manifest xml> -o <output directory>]
Creates a gallery item package using the manifest file and saves it in the output directory

Actions:

package

   OPTION                  TYPE      DESCRIPTION                              
   -manifestfile (-m)      string*   Path to manifest xml file                
   -outputdirectory (-o)   string*   Directory where the package is written_   

**Corrected one:**
.\AzureGallery.exe package **–m** c:\<path>\<gallery package name>\manifest.json **–o** c:\Temp ##Before change
.\AzureGallery.exe package **-m** c:\<path>\<gallery package name>\manifest.json **-o** c:\Temp##After change

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e401ae26-588f-124f-09a8-f1f6dc75da4e
* Version Independent ID: 6a9509a1-f16c-f527-5df1-9dae2d8eeaed
* Content: [Create and publish a Marketplace item in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-create-and-publish-marketplace-item?view=azs-1910)
* Content Source: [azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by BryanTrach-MSFT** [comment]
@Lihailian Thanks for the feedback! We are currently investigating and will update you shortly.

**Comment by TravisCragg-MSFT** [comment]
@Lihailian Thanks for the feedback! I was able to find another instance of a script containing the improper character as well. I have corrected the '-' characters in this doc that are found in scripts, and the docs should reflect the change within 24 hours. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
