### ISSUE TITLE
Certificate copy step is duplicated in documentation

### ISSUE THREAD

**Issue by ewebster-neal** [MicrosoftDocs/azure-stack-docs#861]
Documentation is repeated for copying  and installing certificate on Linux. Documentation needs to only have it present in one area to avoid confusion.

**Reduntant code steps:**
```sh
sudo cp /var/lib/waagent/Certificates.pem /usr/local/share/ca-certificates/azurestackca.crt
sudo update-ca-certificates
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d8c6cbd-54d8-9746-a1f8-a618b98e011e
* Version Independent ID: 479c631e-b7a4-c5cf-160d-141d336ad50a
* Content: [Install the AKS engine on Linux in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-linux.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@ewebster-neal  Thanks for your feedabck. The repeated step is for two different SKUs of Azure Stack Hub, but thanks for drawing my attention to the potential for confusion. Thanks!

**Comment by mattbriggs** [comment]
An update is in progress.

**Comment by mattbriggs** [comment]
#please-close
