### ISSUE TITLE
Test URL for Marketplace items are outdated

### ISSUE THREAD

**Issue by caz3542** [MicrosoftDocs/azure-stack-docs#864]
The URL to validate the published custom marketplace items still references the port 30015 URL that is no longer valid. Needs to be updated to galleryartifacts URL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e401ae26-588f-124f-09a8-f1f6dc75da4e
* Version Independent ID: 6a9509a1-f16c-f527-5df1-9dae2d8eeaed
* Content: [Create and publish a Marketplace item in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-create-and-publish-marketplace-item?view=azs-2002)
* Content Source: [azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-create-and-publish-marketplace-item.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@caz3542 Thank you for the feedback -- can you please include the name and/or path to the article in question?

**Comment by caz3542** [comment]
https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-create-and-publish-marketplace-item?view=azs-2002 - Item (6)

**Comment by TravisCragg-MSFT** [comment]
@caz3542 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@caz3542 Thank you for the report, we are currently looking into this.

**Comment by sethmanheim** [comment]
#in-progress

**Comment by sethmanheim** [comment]
@caz3542 Hi again and sorry for the delay. I have obtained the new information, as follows are the corrected gallery artifacts URLs. I will be updating the article with this information today:

https://galleryartifacts.adminhosting.[Region].[externalFQDN]/artifact/20161101/[TemplateName]/DeploymentTemplates/Template.json

https://galleryartifacts.hosting.[Region].[externalFQDN]/artifact/20161101/[TemplateName]/DeploymentTemplates/Template.json

#please-close
