### ISSUE TITLE
Version mapping table is missing info and has a typo

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#868]
here is the correct table:

Azure Stack Hub version | AKS engine version
1910 | 0.43.0 , 0.43.1
2002 | 0.48.0, 0.51.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for the Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2002)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks for the update. Sending you a preview link.

#in-progress

**Comment by mattbriggs** [comment]
Done. #please-close
