### ISSUE TITLE
Remove references to K8s 1.17 and add note in known issues

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#871]
1. Remove reference to 1.17 in section "Kubernetes version upgrade path in AKS engine 0.51.0". See word doc for change in the section
2. Remove bullet point with reference to 1.17 in section "What's new", see word doc
3. Add this note to "Known Issue":
•	Kubernetes 1.17 is not supported in this release. Even though there are PRs alluding to it, 1.17 is in fact not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for the Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2002)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Thanks Walter. #in-progress

**Comment by mattbriggs** [comment]
@walterov  https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/4028/commits/8e57751c35e8d86e3bf345d9f4bd38223d007ecc

**Comment by mattbriggs** [comment]
PR signed off.

#please-close
