### ISSUE TITLE
New "known issue" to be added

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#876]
We need to add a new item to the "Known Issues" section

•	During upgrade (aks-engine upgrade) of a Kubernetes cluster from version 1.15.x to 1.16.x the kubernetes kube-proxy component is not upgraded:

o	In connected environments is not obvious to notice this issue since there are no signs in the cluster that kube-proxy was not upgraded. Everything appears to work as expected.
o	In disconnected environments you can see this problem when you run a query for the status of the system pods and see that kube-proxy pods are not in “Ready” state:
kubectl get pods -n kube-system
o	Workaround: to solve this issue, please delete the kube-proxy deamonset so that Kubernetes will restart it with the correct version. Run:
kubectl delete ds kube-proxy -n kube-system

Please let me know any questions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69382e4-c307-4dfe-9885-92d2436ef858
* Version Independent ID: 135ea653-550b-039d-121c-95f2e7c93f10
* Content: [Release notes for the Azure Kubernetes Service (AKS) engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-release-notes?view=azs-2002)
* Content Source: [azure-stack/user/kubernetes-aks-engine-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-release-notes.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by sethmanheim** [comment]
Moved to private repo PR 4053. #please-close
