### ISSUE TITLE
Add note explicitly saying that there is no support for the customer to provide his own certificates

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#878]
At the end of section "Define cluster specification", after step 9 add the following Note:

Currently AKS engine for Azure Stack Hub does not provide functionality to allow the user to provide his/her own certificates for the creation of the cluster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9652b7b-09b9-ace9-4ef7-abc413b9d52c
* Version Independent ID: 53c19bb0-3f77-d15c-87e2-33e1d442d73b
* Content: [Deploy a Kubernetes cluster with the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by SaurabhSharma-MSFT** [comment]
@walterov Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
@walterov https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/4124 messages you on Teams.

**Comment by mattbriggs** [comment]
#please-close
