### ISSUE TITLE
Issue with the Table

### ISSUE THREAD

**Issue by IAteUrPoptart** [MicrosoftDocs/azure-stack-docs#879]
On the System Requirements table the HW logo certification for recommended is on a new line in the table on mobile. 
![Screenshot_20200630-102141](https://user-images.githubusercontent.com/11493878/86137669-87e7fd80-babb-11ea-9f4d-f56427f0e318.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc787c65-8a49-6504-abde-3b6bbd6e0d58
* Version Independent ID: 051a3b4a-9b69-c4ff-74e2-e0d5a9ae70cc
* Content: [ASDK requirements and considerations - Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-deploy-considerations?view=azs-2002)
* Content Source: [azure-stack/asdk/asdk-deploy-considerations.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-deploy-considerations.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by SaurabhSharma-MSFT** [comment]
@IAteUrPoptart Thanks for your feedback! We will investigate and update as appropriate.

**Comment by TravisCragg-MSFT** [comment]
@IAteUrPoptart Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by myoungerman** [comment]
@TravisCragg-MSFT @SaurabhSharma-MSFT Fixed, thanks! 

[https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5062](https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5062)

**Comment by mattbriggs** [comment]
@mattbriggs

**Comment by mattbriggs** [comment]
#please-close
