### ISSUE TITLE
RSS feed link goes to '404 - Page not found'

### ISSUE THREAD

**Issue by Andy-Dawson** [MicrosoftDocs/azure-stack-docs#884]
The link on this page to the RSS feed when clicked gives '404 - Page not found'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8368a3-49e9-5216-f7cb-f91f6f1122c1
* Version Independent ID: 12092beb-efeb-974f-f9fe-5428435b228b
* Content: [ASDK Release Notes - Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-release-notes?view=azs-2002&viewFallbackFrom=azs-2006)
* Content Source: [azure-stack/asdk/asdk-release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-release-notes.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by SaurabhSharma-MSFT** [comment]
@Andy-Dawson Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by sethmanheim** [comment]
@Andy-Dawson Thank you for catching this -- the link in the Markdown source seems to be correct but I made a few formatting tweaks and the link in the article seems to be working. I'll close this for now but just add a comment if it isn't fixed by noon today PDT. #please-close

**Comment by sethmanheim** [comment]
@Andy-Dawson I've noticed this is still not working correctly and have escalated the issue. #in-progress
