### ISSUE TITLE
Correct BMC password credential limit

### ISSUE THREAD

**Issue by DiegoOrdonezHPE** [MicrosoftDocs/azure-stack-docs#888]
Should correct that the "BMC Password" character limit is 16 characters.
It is only stated for the "BMC Username"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4feaa2a-4850-478d-8122-7eb751ba0777
* Version Independent ID: f5cd7372-0443-3f2e-c403-ed7ba1a56146
* Content: [Rotate secrets - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-rotate-secrets?view=azs-2002#feedback)
* Content Source: [azure-stack/operator/azure-stack-rotate-secrets.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-rotate-secrets.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by SaurabhSharma-MSFT** [comment]
@DiegoOrdonezHPE Thanks for the feedback !  I have assigned this issue to content author to investigate and update the document as appropriate.

**Comment by IngridAtMicrosoft** [comment]
in review

**Comment by IngridAtMicrosoft** [comment]
Please assign @BryanLa

**Comment by BryanLa** [comment]
@DiegoOrdonezHPE - thanks very much for your feedback.

I'm in the process of making major revisions to this article, and have included your feedback.

#please-close
