### ISSUE TITLE
The table Capabilities and Limitations is outdated

### ISSUE THREAD

**Issue by calcobia** [MicrosoftDocs/azure-stack-docs#9]
The table [Capabilities and Limitations](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-identity-architecture#capabilities-and-limitations) is outdated.

[Azure Stack release 1811](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-update-1811#new-features) introduced this capability: 
- Added support for Service Principals using a client secret with Active Directory Federated Services (AD FS).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 013a0f43-0887-69dd-b02f-cb3cddaedd3f
* Version Independent ID: cb5673ae-2a4b-513f-fb26-5ccd58d8d0d2
* Content: [Identity architecture for Azure Stack](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-identity-architecture#capabilities-and-limitations)
* Content Source: [articles/azure-stack/azure-stack-identity-architecture.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-identity-architecture.md)
* Service: **azure-stack**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by PatAltimore** [comment]
Hi @calcobia, Thanks for catching this.  I'll fix the table.

Thanks,
Pat

#please-close
