### ISSUE TITLE
All products available?

### ISSUE THREAD

**Issue by niheinba** [MicrosoftDocs/azure-stack-docs#90]
Are all products available on azure stack? I feel like I might be missing something super obvious.

Cheers,
Nick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7365a8d-a66f-b338-117a-abbb49bb4db0
* Version Independent ID: 0e32791c-3fee-636f-27f6-37b08dfcd5b4
* Content: [What is Azure Stack?](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-overview#feedback)
* Content Source: [azure-stack/operator/azure-stack-overview.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-overview.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by niheinba** [comment]
Never mind. Sorry

**Comment by niheinba** [comment]
Yea, the answers are elsewhere. Thank you!

**Comment by mattbriggs** [comment]
@niheinba Thanks for asking your question. And no ... only a subset of Azure resources are available on Azure Stack. Glad you found your answer! #please-close

**Comment by TravisCragg-MSFT** [comment]
@niheinba We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by juajac** [comment]
Hi guys, a customer sent me a list of resource types he is using in Azure. He wants to know if all this resource types are also available in Azure Stack. Is there a public list, comparisson, whatever...? 
This is his list, thanks in advance! @traviscragg-msft 

Analysis Services
API Connection
App Service
App Service (Slot)
App Service plan
Application Insights
Automation Account
Container registry
Data factory (V2)
Data Lake Analytics
Data Lake Storage Gen1
Disk
Event Grid Topic
Event Hubs Namespace
IoT Hub
Key vault
Log Analytics workspace
Logic app
Network interface
Network security group
Notification Hub
Notification Hub Namespace
On-premises Data Gateway
Public IP address
Recovery Services vault
Runbook
Scheduler Job Collection
Service Bus Namespace
SignalR
Solution
SQL database
SQL server
Storage account
Stream Analytics job
Virtual machine
Virtual network

**Comment by mattbriggs** [comment]
@juajac @TravisCragg-MSFT This is on my list of things to provide in a clear way in our docs (which doesn't help your customer right this second!)

One way thing to point out is that some of Azure stack services are 'add ons' and are built on top of the Azure's IaaS infrastructure, such as Kubernetes and App Service.

 At the moment I think it is a bit cryptic even though much of the information is there. For example, you can review the API Profiles and list of available RPs:

https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-profiles-azure-resource-manager-versions?view=azs-1910

Or, you can use the an ARM template validation tool. There are two topics that address this:

https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-validate-templates?view=azs-1910. 
https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-resource-manager-deploy-template-vscode?view=azs-1910

Finally, you can review the RPs and services. Many of them have a considerations  page that explains who the Azure Stack Hub version varies from the global Azure. Here is one of thes topoic for 'Compute' (which provides VMS): https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-vm-considerations?view=azs-1910
