### ISSUE TITLE
Great stuff!

### ISSUE THREAD

**Issue by niheinba** [MicrosoftDocs/azure-stack-docs#91]
I really appreciate how well it is all laid out.  Feel free to close. Just a quick kudo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517b1814-7971-258a-1e6e-cfd0769d3fbc
* Version Independent ID: e2eb938a-1a20-d94b-63d6-c8b66f1a8dad
* Content: [Capacity planning for Azure Stack](https://docs.microsoft.com/en-us/azure-stack/operator/capacity-planning)
* Content Source: [azure-stack/operator/capacity-planning.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/capacity-planning.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by msrini-MSFT** [comment]
@niheinba , Thank you for sharing your feedback. 

@mattbriggs Great job.
