### ISSUE TITLE
Need more clarification about the license for guest windows server

### ISSUE THREAD

**Issue by kongou-ae** [MicrosoftDocs/azure-stack-docs#918]
Hello Team,

I believe that the following sentence needs more clarification.

> No traditional on-premises software license is required, although guest virtual machines (VMs) may require individual operating system licensing

My confusing point is as follows.

**1.The server license for guest windows server**

Can we run the infinite guest windows servers without an additional server license? Does the billing of Azure Stack HCI OS contain the right of running guest Windows Server?

**2.The CAL for guest windows server**

Do I need CAL for the guest windows server? the new Azure Stack HCI supports ESU of win 2008 so I think that Microsoft treats the new Azure Stack HCI as Azure. so I guess that Azure Stack HCI doesn't require the CAL for guest windows server as same as Azure Stack Hub.

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f92859f-7987-76ae-6f0d-8b048298158d
* Version Independent ID: 519ebc92-176d-7d46-a0ac-476cc241f45d
* Content: [Azure Stack HCI billing and payment - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/billing)
* Content Source: [azure-stack/hci/concepts/billing.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/concepts/billing.md)
* Service: **azure-stack**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by NavtejSaini-MSFT** [comment]
@kongou-ae We are checking this and we will get back to you.

**Comment by TravisCragg-MSFT** [comment]
@kongou-ae Let me double check on this.

**Comment by TravisCragg-MSFT** [comment]
@kongou-ae The billing for Azure Stack HCI only includes the core usage, and does not include guest OS licenses. There is no native licensing method within Azure Stack HCI, so you will need to provide licenses for the Operating Systems that you deploy.

**Comment by mattmcspirit** [comment]
@kongou-ae - to give an example, if you had 2 physical hosts, with 10 cores each:

1. You'd install Azure Stack HCI onto both pieces of hardware, build your cluster etc, and register it with Azure.  For a total of 20 physical cores, that would be charged at US $200 per month (List pricing).
2. For your guests, if you had only a few guests, and you wished those to be Windows Server, you could stack Windows Server 2019 Standard edition licenses, to cover the number of guests you needed.  Each license grants you 2 guests licenses to run Windows Server Standard in VMs on that host.
3. If you needed more guests on the cluster, you'd buy Windows Server Datacenter for your cluster, as this gives you unlimited virtualization rights.  The key point here is, regardless of choosing Standard or Datacenter for your guests, you only need to install Azure Stack HCI OS on the metal.
4. As for CALs, CALs are required for every user or device accessing a server, so this is irrelevant of the underlying Azure Stack HCI OS - if you have users accessing a Windows-based file server, or other application server, then you'd need CALs.

Ultimately, for #1, 2 and 3 above, it's no different than if your virtualization layer on the metal was VMware, or an open source hypervisor - you'd still have to license the Windows Server guests on top.

As for ESU - Azure Stack does give the rights to run 2008 with the security updates provided, however I don't believe that negates the need for CALs, and I believe that to be true for Azure Stack Hub also.  My understanding is if you have valid CALs, use those, but if not, you'd buy CALs for 2019, and I believe these would cover you for accessing the older OS's also.  I'll double check this CAL part and update when I have a firm answer.

**Comment by TravisCragg-MSFT** [comment]
@kongou-ae We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by kongou-ae** [comment]
@mattmcspirit @TravisCragg-MSFT 

Thank you for your advice. I understand and I don't have any additional questions.

I believe that the point about the license for guest VMs should be written on the price page of Azure Stack HCI when the new Azure Stack Hub will be GA. Because our friend is also confused by this.

Best.

**Comment by mattmcspirit** [comment]
Thanks for this - i've started a few discussions internally, and we'll start to put some guidance together.

Thanks!

**Comment by DellProSupportGse** [comment]
Would it be possible to add this Windows licensing information on the HCI OS pricing page?
https://azure.microsoft.com/en-us/pricing/details/azure-stack/hci/

**Comment by jlgandy2** [comment]
Would it be possible to add this Windows licensing information on the HCI OS pricing page?
https://azure.microsoft.com/en-us/pricing/details/azure-stack/hci/
