### ISSUE TITLE
VHD Path needs to be specified

### ISSUE THREAD

**Issue by nandak-msft** [MicrosoftDocs/azure-stack-docs#920]
Install-WindowsFeature -Vhd **<vhdPath>** -Name Hyper-V, RSAT-Hyper-V-Tools, Hyper-V-Powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a42847db-d724-8267-47bb-035ce4016d08
* Version Independent ID: f580b757-cefd-1765-c1ed-f6b572f849c2
* Content: [Known issues for Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/known-issues)
* Content Source: [azure-stack/hci/known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/known-issues.md)
* Service: **azure-stack**
* GitHub Login: @JohnCobb1
* Microsoft Alias: **v-johcob**

**Comment by nandak-msft** [comment]
Github markup keeps eating the commandline i specified.

Install-WindowsFeature -Vhd **{VHDPATH}** -Name Hyper-V, RSAT-Hyper-V-Tools, Hyper-V-Powershell

**Comment by TravisCragg-MSFT** [comment]
@nandak-msft Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by myoungerman** [comment]
@TravisCragg-MSFT I've updated the article, thanks!

https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/5211

**Comment by sethmanheim** [comment]
#please-close
