### ISSUE TITLE
Subscription Permissions

### ISSUE THREAD

**Issue by jamesorlando** [MicrosoftDocs/azure-stack-docs#933]
This page could use some information on permissions required to create a cluster. I just learned that users who are owners of a resource group in a subscription, but not an owner of the subscription will be unable to create a cluster. Do you need to be a subscription contributor or owner to create new clusters? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a71abd01-3dbf-a597-3866-c0ce27416693
* Version Independent ID: 7d9e5f95-9c31-e1a0-d336-81a891373f62
* Content: [Create an Event Hubs cluster using the portal - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/event-hubs-quickstart-cluster-portal?view=azs-2002)
* Content Source: [azure-stack/user/event-hubs-quickstart-cluster-portal.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/event-hubs-quickstart-cluster-portal.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by TravisCragg-MSFT** [comment]
@BryanLa Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by BryanLa** [comment]
Hi @jamesorlando - apologies for the delay on this. Engineering has confirmed that the user only needs to be a member of the Contributor role. I will also add a note to the article you cited, and thanks for your feedback.

#please-close
