### ISSUE TITLE
The term 'Get-AzureStackLogs' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by Donnie-Zhang** [MicrosoftDocs/azure-stack-docs#935]
It's 'Get-AzureStackLog', not 'Get-AzureStackLog**s**'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9791d946-d79a-6929-4e48-56eb37021c6f
* Version Independent ID: 22b2c392-7cc5-c21a-fae5-2f717ce477c2
* Content: [Use the privileged endpoint (PEP) to collect diagnostic logs - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-get-azurestacklog?view=azs-2002)
* Content Source: [azure-stack/operator/azure-stack-get-azurestacklog.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-get-azurestacklog.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by BharathNimmala-MSFT** [comment]
@Donnie-Zhang  Thank you for bringing this to our notice, we will review the document and update it accordingly.

**Comment by TravisCragg-MSFT** [comment]
@Donnie-Zhang This is already listed in #816, closing this a dupicate and following up with that issue.
