### ISSUE TITLE
Script parameter clarification needed

### ISSUE THREAD

**Issue by pappleby64** [MicrosoftDocs/azure-stack-docs#936]
Need more clarification on a couple of parameters
**VirtualMachineMemory** - deafult is 4GB but if I want 8GB what do pass as the parameter 8, 8G, 8000000 ?
**AzureStackCertificatePath** - need to explain why and when it's needed (using a non public CA) and be more specific about the certs that are needed and how to find them 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b96bdc7-32a2-b303-fa5f-c691edd5bd37
* Version Independent ID: 87467e92-a054-4436-e7e4-cf3c218fb00a
* Content: [Azure Stack Hub Operator Access Workstation - Azure Stack Hub](https://review.docs.microsoft.com/en-us/azure-stack/operator/operator-access-workstation?view=azs-1802&branch=pr-en-us-3857)
* Content Source: [azure-stack/operator/operator-access-workstation.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/operator-access-workstation.md)
* Service: **azure-stack**
* GitHub Login: @asganesh
* Microsoft Alias: **justinha**

**Comment by TravisCragg-MSFT** [comment]
@pappleby64 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@mattbriggs

**Comment by mattbriggs** [comment]
@TravisCragg-MSFT the author has left. Can you re-assign this topic to me? @mattbriggs Thanks! Matt

**Comment by mattbriggs** [comment]
@pappleby64 Thanks @pappleby64. I have a question out.

#in-progress

**Comment by mattbriggs** [comment]
@pappleby64 Updated topic and is in progress for publish. In review with the technical owner.

#please-close
