### ISSUE TITLE
No support for deploying a cluster in the Admin subscription

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#941]
Please add the following note to the description of "subscription-id": Only provide a tenant subscription, deploying to the admin subscription is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9652b7b-09b9-ace9-4ef7-abc413b9d52c
* Version Independent ID: 53c19bb0-3f77-d15c-87e2-33e1d442d73b
* Content: [Deploy a Kubernetes cluster with the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-cluster.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@walterov Thanks for the feedback. We shall evaluate and update the document as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@walterov Thank you for the feedback. I have submitted a PR to fix the issue that's in review.

**Comment by mattbriggs** [comment]
Needed to make a change to the wording. I've added the note to this PR: https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/4542. Line 127 of the topic.

**Comment by mattbriggs** [comment]
#please-close
