### ISSUE TITLE
Remove the Basic Load Balancer limitation from the doc, it is no longer a limitation

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#942]
Remove this from the doc:

Basic load balancer SKU limitations
Single agent pool limitation. Currently, Azure Stack Hub only supports the Basic load balancer SKU. This SKU limits the backend pool endpoints to virtual machines in a single availability set (or virtual machine scale set). This implies that all replicas of a LoadBalancer service should be deployed on the same agent pool and it also implies that each individual cluster can either have a Linux LoadBalancer service or a Windows LoadBalancer service.

You can force Kubernetes to create pods in a specific agent pool by adding node selector "agentpool: MY_POOL_NAME" in your pod template.

JSON

Copy
nodeSelector:

      agentpool: linuxpool
If a LoadBalancer service was already created in your cluster, you can find out which agent pool was selected as the backend pool of the load balancer by inspecting the load balancer backend pools blade in the Azure Stack Hub portal. Once you have that information, you can specify the target agent pool by updating your deployment/pod yaml (as explained in the previous paragraph).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bddc138b-1b2e-4be5-d38b-91818ccf1922
* Version Independent ID: fb4f2341-8ca1-f849-05f5-5b4ce22b9462
* Content: [Known issues with the AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues?view=azs-2002#basic-load-balancer-sku-limitations)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-known-issues.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@walterov Thank you for the feedback. I have submitted a PR to fix the issue that's in review.

**Comment by mattbriggs** [comment]
@BhargaviAnnadevara-MSFT I've fixed in another PR. Please CC me in the future so I can fix in a single PR. Thanks! Matt

#please-close
