### ISSUE TITLE
Changes needed to this doc were sent to Matt through internal mail

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#944]
Matt, please look at the changes I outlined in an internal mail to you. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc538db2-5b34-3668-1e8e-1914b4b18c43
* Version Independent ID: 4f4c7701-f73c-ca0b-f7e4-62652a7ae66b
* Content: [Deploy a Kubernetes cluster to a custom virtual network on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/kubernetes-aks-engine-custom-vnet?view=azs-2002)
* Content Source: [azure-stack/user/kubernetes-aks-engine-custom-vnet.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/kubernetes-aks-engine-custom-vnet.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@walterov Thanks for the feedback. I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/4542

**Comment by mattbriggs** [comment]
#in-progress

**Comment by mattbriggs** [comment]
Resolved. #please-close
