### ISSUE TITLE
registrationrole.json template Line 16 col 41 missing double quote leading to parsing error

### ISSUE THREAD

**Issue by prasks82** [MicrosoftDocs/azure-stack-docs#945]
Hello, 

In the registrationrole.json template Line 16 col 41     "Microsoft.Authorization/locks/write is missing double quote leading to parsing error:
New-AzureRmRoleDefinition : After parsing a value an unexpected character was encountered: N. Path 'Actions[9]', line
18, position 4.
At line:1 char:1
+ New-AzureRmRoleDefinition -InputFile "C:\CustomRoles\registrationrole ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRoleDefinition], JsonReaderException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleDefinitionCommand

Please update the template to resolve the parsing error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aacc015e-fe7c-e95a-f8e4-def1a4fb91e2
* Version Independent ID: 35d53d5c-0f68-69fa-7b6c-1bae8d3b9b8e
* Content: [Create a custom role for Azure Stack Hub registration - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-registration-role?view=azs-2002)
* Content Source: [azure-stack/operator/azure-stack-registration-role.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-registration-role.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@prasks82 Thank you very much for bringing this to our attention. We shall evaluate and update the document as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@prasks82 Thank you for catching that error in the docs! I have submitted a PR to fix the issue that's in review.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@prasks82 The change is merged internally and will go-live in the public docs shortly. Thanks again for the feedback.
