### ISSUE TITLE
Teaming Every "Up" Adapter

### ISSUE THREAD

**Issue by hfu949** [MicrosoftDocs/azure-stack-docs#947]
This command seems a bit broad in terms of teaming any adapter that is up especially with SET not being able to team heterogeneous adapters. 

Invoke-Command -ComputerName $Servers -ScriptBlock {New-VMSwitch -Name $using:vSwitchName -EnableEmbeddedTeaming $TRUE -EnableIov $true -NetAdapterName (Get-NetAdapter | Where-Object Status -eq Up ).InterfaceAlias}

https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell#create-virtual-switches

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df3012c4-22e5-004d-da6f-60744f2cfb4f
* Version Independent ID: 57e21edd-9a2b-f1ca-2ff7-48e3da5dc260
* Content: [Create an Azure Stack HCI cluster using Windows PowerShell - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell)
* Content Source: [azure-stack/hci/deploy/create-cluster-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/deploy/create-cluster-powershell.md)
* Service: **azure-stack**
* GitHub Login: @v-dasis
* Microsoft Alias: **v-dasis**

**Comment by NavtejSaini-MSFT** [comment]
@hfu949 We are checking this and we will get back to you.

**Comment by TravisCragg-MSFT** [comment]
@hfu949 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by v-dasis** [comment]
content updated in staging per below. Let me know if this is OK. Then will merge and publish live later today:

"All network adapters must be identical when teaming NICs."

**Comment by v-dasis** [comment]
push live on Monday as missed Fri window

**Comment by v-dasis** [comment]
#sign-off

**Comment by jamesaepp** [comment]
I was reviewing the documentation for powershell commands as I'm frustrated with WAC and I found the same thing. This seems like quite the oversight.

**Comment by v-dasis** [comment]
Hi, please clarify what is meant by "...and I found the same thing." Thanks.

**Comment by jamesaepp** [comment]
As in, I found the same issue in the documentation that OP reported.

**Comment by v-dasis** [comment]
This was closed last August with "All network adapters must be identical when teaming NICs." Not sure specifically what you are referring to in addition here.

**Comment by jamesaepp** [comment]
What if I don't want all network adapters on the system to be part of the same virtual switch? What purpose is accomplished by putting all adapters into the same vSwitch? Why do the powershell steps make this recommendation but the wizard in WAC does something different?

There is a lot of confusion in this document and product.

**Comment by v-dasis** [comment]
To address these specific questions, recommend going to product support at https://docs.microsoft.com/en-us/azure-stack/hci/manage/get-support. WAC wizard follows a specific preset implementation based on auto-discovery of your environment while the PowerShell article gives but one example of how things could be done, out of many possible permutations. For a deep-dive of PowerShell scripts used for HCI cluster creation, see the WSLabs examples in GitHub at https://github.com/jaromirk/WSLab.
