### ISSUE TITLE
Wrong Parameter for New-ClusterFaultDomain

### ISSUE THREAD

**Issue by hfu949** [MicrosoftDocs/azure-stack-docs#949]
Looks like the -Type should be -FaultDomainType as there is no -Type for that cmdlet.

New-ClusterFaultDomain -CimSession ClusterS1 -Type Site -Name Site1
New-ClusterFaultDomain -CimSession ClusterS1 -Type Site -Name Site2

https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell#step-51-create-sites

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df3012c4-22e5-004d-da6f-60744f2cfb4f
* Version Independent ID: 57e21edd-9a2b-f1ca-2ff7-48e3da5dc260
* Content: [Create an Azure Stack HCI cluster using Windows PowerShell - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell)
* Content Source: [azure-stack/hci/deploy/create-cluster-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/deploy/create-cluster-powershell.md)
* Service: **azure-stack**
* GitHub Login: @v-dasis
* Microsoft Alias: **v-dasis**

**Comment by TravisCragg-MSFT** [comment]
@hfu949 Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by v-dasis** [comment]
content updated in staging. Will merge and publish live later today.
