### ISSUE TITLE
AzureStack-Tools-az still make use of AzureRM PowerShell modules

### ISSUE THREAD

**Issue by jonathanrelf** [MicrosoftDocs/azure-stack-docs#951]
Whilst the instructions invite the use of the preview Az modules for Azure Stack, scripts like 'CloudCapabilities\AzureRM.CloudCapabilities.psm1' still make use of commands like 'Get-AzureRmResourceProvider'. After uninstalling all Azure modules from PowerShell 7.0.3 I was getting the error that 'The term 'Get-AzureRmResourceProvider' is not recognized as the name of a cmdlet, function, script file, or operable program'.

The only way I've got the CloudCapabilities tool to work is to issue 
`Enable-AzureRmAlias -Scope CurrentUser`

If the AzureStack-Tools-az cannot be updated to use only Az commands because of missing functionality still, then this guide needs to add the AzureRmAlias command in there somewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c26c4e-2806-66bd-a127-c23e45309403
* Version Independent ID: b9076003-9857-47ec-c2dc-64d3c8b65243
* Content: [Download Azure Stack Hub tools from GitHub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-download?view=azs-2002)
* Content Source: [azure-stack/operator/azure-stack-powershell-download.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-powershell-download.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@jonathanrelf Thanks for your comments and experimentation with the GitHub repo. I'm following with with with the owner of the scripts, and will update once I get their response or let you know if they are updating something. Thanks! Matt

#in-progress

**Comment by bganapa** [comment]
@mattbriggs it looks like the az branch CloudCapabilities script hasnt got converted to Az. Simply changing the -AzureRM prefix to -Az in the script should work I believe. Do you have time to make a PR to AzureStack tools repo?

**Comment by mattbriggs** [comment]
@bganapa I submitted a PR to the Tools repo and validated that it run locally. @jonathanrelf  The update is in progress and should be live shortly. Thanks for your feedback.

#please-close
