### ISSUE TITLE
Invalid Parameter for Get-Storagepool

### ISSUE THREAD

**Issue by hfu949** [MicrosoftDocs/azure-stack-docs#955]
There is no -Cluster parameter. Probably meant to use -Cimsession.

Get-StoragePool -Cluster Cluster1

https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell#step-6-enable-storage-spaces-direct

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df3012c4-22e5-004d-da6f-60744f2cfb4f
* Version Independent ID: 57e21edd-9a2b-f1ca-2ff7-48e3da5dc260
* Content: [Create an Azure Stack HCI cluster using Windows PowerShell - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/deploy/create-cluster-powershell)
* Content Source: [azure-stack/hci/deploy/create-cluster-powershell.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/deploy/create-cluster-powershell.md)
* Service: **azure-stack**
* GitHub Login: @v-dasis
* Microsoft Alias: **v-dasis**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@hfu949 Thanks for the question! We're investigating this and will get back to you shortly.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@hfu949 Thank you for catching that error in the docs! I have submitted a PR to fix the issue, the change is merged internally and will go-live in the public docs shortly.
