### ISSUE TITLE
Backup payload for connected deployments i.e. with Azure AD are not 1GB in size.

### ISSUE THREAD

**Issue by PatrickLownds** [MicrosoftDocs/azure-stack-docs#956]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34deefc4-caeb-f37d-a8c2-38425d5c8229
* Version Independent ID: ddb06ae4-dc73-543d-dc86-c28af82f98c6
* Content: [Infrastructure Backup Service reference - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-backup-reference?view=azs-2002)
* Content Source: [azure-stack/operator/azure-stack-backup-reference.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-backup-reference.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by PatrickLownds** [comment]
Document needs updating to reflect changes in the size of the backup payload for connected deployments.

**Comment by NavtejSaini-MSFT** [comment]
@PatrickLownds We are checking this and will get back to you.

**Comment by TravisCragg-MSFT** [comment]
@PatrickLownds Can you give a bit more context on what you are referring to, and what section of the doc needs to be changed?

Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by mattbriggs** [comment]
@mattbriggs

**Comment by mattbriggs** [comment]
@TravisCragg-MSFT the author has left. Can you re-assign this topic to me? @mattbriggs Thanks! Matt

**Comment by mattbriggs** [comment]
Sorry for the length of time to respond. Storage size is listed as 280 GB.

#please-close
