### ISSUE TITLE
Add one more item to "AKS engine areas not supported"

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#960]
Please add the following bullet at the end of the existing list under "AKS engine areas not supported":

"Production environments should only use highly available Kubernetes clusters, that is, clusters deployed with a minimum of 3 masters and 3 agent nodes. Anything less cannot be supported in production deployments" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95fd6a25-af7a-737d-24e4-f2c7947f0aba
* Version Independent ID: d1ef3fa8-733d-1802-59c9-5b54f7069d43
* Content: [Support policies for AKS engine on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-support?view=azs-2002)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-support.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-support.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@walterov Sent an update preview.

#in-progress

**Comment by mattbriggs** [comment]
#please-close
