### ISSUE TITLE
Spelling error - noice should be noise

### ISSUE THREAD

**Issue by SqlTechMike** [MicrosoftDocs/azure-stack-docs#962]
In the list of Fixes in the 2005 release the 8th bullet, related to code integrity policy, has a spelling error.  I believe "noice" should be corrected to "noise".  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e05517-6ffa-ad32-ec69-d3299492d880
* Version Independent ID: 2d6ffb4c-9134-a390-3f90-2322c9182e76
* Content: [Azure Stack Hub release notes - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/release-notes?view=azs-2005#2005-build-reference)
* Content Source: [azure-stack/operator/release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/release-notes.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@SqlTechMike Thank you so much for catching that! I just submitted a PR to fix it, should be live after 10:15 AM PDT. #please-close
