### ISSUE TITLE
1908 release notes should not be archived

### ISSUE THREAD

**Issue by Donnie-Zhang** [MicrosoftDocs/azure-stack-docs#965]
1908 is still supported (due to CoVid 19), so it should not be archived.
And it's not available at https://gallery.technet.microsoft.com/Azure-Stack-version-1811-13716073

Anywhere can I find it?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6e05517-6ffa-ad32-ec69-d3299492d880
* Version Independent ID: 2d6ffb4c-9134-a390-3f90-2322c9182e76
* Content: [Azure Stack Hub release notes - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/release-notes?view=azs-1908)
* Content Source: [azure-stack/operator/release-notes.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/release-notes.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by sethmanheim** [comment]
@Donnie-Zhang Sorry about that, we only found out very late about the 45-day grace period. I will add 1908 back, and it will be live by 10 AM PDT.

**Comment by sethmanheim** [comment]
@Donnie-Zhang Done, and published live. #please-close
