### ISSUE TITLE
interactive container and connecting to ARM

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-stack-docs#972]
1. the below command runs container and let us access it at the same time, so if this is used each time, multiple containers will be run.
**docker run -it azure-stack-powershell powershell**
It might worth mentioning that this command can be used to access the container, instead of creating one each time:
**docker exec -it "Container name" powershell**

2. Tried the below and it works, but figured that I connected to public Azure
**Connect-AzureRmAccount -ServicePrincipal -Credential $pscredential -TenantId <TenantID>**

Have used the below and it works fine with Azure Stack
   **Add-AzureRMEnvironment -Name "AzureStackUser" -ArmEndpoint "Arm Endpoint"
    Add-AzureRmAccount -EnvironmentName "AzureStackUser" -TenantId "tenant ID" -ServicePrincipal -Credential $pscredential**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55e2558f-e434-e5cc-acd4-0d3bd2dd979f
* Version Independent ID: be6bfe5f-bfdd-6550-588d-6d627c16c3f8
* Content: [Use Docker to run PowerShell in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-powershell-user-docker?view=azs-2005&tabs=rm)
* Content Source: [azure-stack/user/azure-stack-powershell-user-docker.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-powershell-user-docker.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@HassanAlmanasrah Thanks for this detailed feedback. I will update the article. 

#in-progress

**Comment by mattbriggs** [comment]
updated. #please-close
