### ISSUE TITLE
MySQL RP Update example script has extra spaces

### ISSUE THREAD

**Issue by leyasa** [MicrosoftDocs/azure-stack-docs#973]
The example update script has an extra space after each tick of each parameter that breaks the correct parsing of the parameters
# Then adjust the endpoints.
.$tempDir\UpdateMySQLProvider.ps1 -AzCredential $AdminCreds ` 
-VMLocalCredential $vmLocalAdminCreds ` 
-CloudAdminCredential $cloudAdminCreds ` 
-PrivilegedEndpoint $privilegedEndpoint ` 
-AzureEnvironment $AzureEnvironment ` 
-DefaultSSLCertificatePassword $PfxPass ` 
-DependencyFilesLocalPath $tempDir\cert ` 
-AcceptLicense

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b377dc6-ab2b-9f37-41a6-c0142bc0529a
* Version Independent ID: 71f3378d-6db4-6941-4514-7ff63a9c5adc
* Content: [Update the MySQL resource provider in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-mysql-resource-provider-update?view=azs-2005)
* Content Source: [azure-stack/operator/azure-stack-mysql-resource-provider-update.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-mysql-resource-provider-update.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@leyasa Thanks for bringing this to our attention. We shall evaluate and update the document as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@leyasa Thank you for catching that error in the docs! I have submitted a PR to fix the issue, the change is merged internally and will go-live in the public docs shortly.
