### ISSUE TITLE
SQL RP Update example script has extra spaces

### ISSUE THREAD

**Issue by leyasa** [MicrosoftDocs/azure-stack-docs#974]
The example update script has an extra space after the tick on the AzureEnvironment parameter that breaks the correct parsing of the last two parameters

# Then adjust the endpoints.
. $tempDir\UpdateSQLProvider.ps1 -AzCredential $AdminCreds `
  -VMLocalCredential $vmLocalAdminCreds `
  -CloudAdminCredential $cloudAdminCreds `
  -PrivilegedEndpoint $privilegedEndpoint `
  -AzureEnvironment $AzureEnvironment ` 
  -DefaultSSLCertificatePassword $PfxPass `
  -DependencyFilesLocalPath $tempDir\cert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7036dfa7-b02a-2a1f-5f25-7d1b9f5bd548
* Version Independent ID: d138b9d0-0717-28f2-71a9-ec2380ddeece
* Content: [Update the Azure Stack Hub SQL resource provider - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-sql-resource-provider-update?view=azs-2005)
* Content Source: [azure-stack/operator/azure-stack-sql-resource-provider-update.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-sql-resource-provider-update.md)
* Service: **azure-stack**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BhargaviAnnadevara-MSFT** [comment]
@leyasa Thanks for bringing this to our attention. We shall evaluate and update the document as appropriate.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@leyasa Thank you for catching that error in the docs! I have submitted a PR to fix the issue, the change is merged internally and will go-live in the public docs shortly.
