### ISSUE TITLE
vhdx disk size to small for ASDK 2005

### ISSUE THREAD

**Issue by Werner-MOC** [MicrosoftDocs/azure-stack-docs#976]
If you use default vhdx size of cloudbuilder.vhdx then you will have only 4GB left on C drive after setup.
This should be changed in next version, until then, before booting into this vhdx you can extend the size inside the vhdx to 200GB with cmdlet:
Resize-VHD -Path 'C:\Azure Stack Development Kit\CloudBuilder.vhdx' -SizeBytes 200GB
and then after booting into this vhdx extend C drive with computer management tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 289cb46f-b173-0ec0-ace1-6e038f82c553
* Version Independent ID: 8f72a4e5-fba9-6631-1924-3b649446bf18
* Content: [Download and extract the ASDK - Azure Stack Development Kit (ASDK)](https://docs.microsoft.com/en-us/azure-stack/asdk/asdk-download?view=azs-2005)
* Content Source: [azure-stack/asdk/asdk-download.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/asdk/asdk-download.md)
* Service: **azure-stack**
* GitHub Login: @Justinha
* Microsoft Alias: **justinha**

**Comment by KranthiPakala-MSFT** [comment]
@Werner-MOC Thanks for the feedback and bringing this to our notice. At this time we are reviewing the feedback and will provide an update as appropriate.

**Comment by SychevIgor** [comment]
It's super important problem. currently disk require 56GB! MSFT- please fix requirements and this document

**Comment by sethmanheim** [comment]
@Werner-MOC Very sorry for the slow response. At this time we have removed support for the ASDK. As this wasn't really a documentation issue, closing for now.
