### ISSUE TITLE
FAQ question and answer is a little misleading

### ISSUE THREAD

**Issue by Rkariyal** [MicrosoftDocs/azure-stack-docs#984]
[The FAQ section has this question and the answer is Yes - Do the the Azure portal cost management tools work for Azure Stack HCI? Yes

On discussion with a GBB colleague I was told that the " Azure Cost management tools don’t integrate with HCI or Hub or on premise resources" So I asked what does the question and answer refer to? his response is the 10$ per core per month charge.

Is this correct? if yes, it does sound misleading? cost when you say Azure Cost management tools, what comes to mind is that Azure Cost Management is talking to the HCI host and is now able to read utilization data of the on premise HCI instance and make recommendations like Azure around Snoozing VMs and right sizing VMs]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f92859f-7987-76ae-6f0d-8b048298158d
* Version Independent ID: 519ebc92-176d-7d46-a0ac-476cc241f45d
* Content: [Azure Stack HCI billing and payment - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/billing)
* Content Source: [azure-stack/hci/concepts/billing.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/concepts/billing.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by Grace-MacJones-MSFT** [comment]
Hi @Rkariyal, thanks for bringing this to our attention. I have assigned the issue to the content author to evaluate and update as appropriate

**Comment by khdownie** [comment]
Hi @Rkariyal - I've reached out to my boss about this issue. Azure Stack HCI is not in GA yet so it's possible that this integration is forthcoming. Nonetheless I agree that we should clarify if it's not yet available. Thanks for pointing this out.

**Comment by Rkariyal** [comment]
Thanks, my information could be wrong as well, in fact I hope it's wrong, :) cause that would be a great feature!

Look forward to hearing back from you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
