### ISSUE TITLE
Meter ID

### ISSUE THREAD

**Issue by LingYi-Wu** [MicrosoftDocs/azure-stack-docs#985]
Hello Team,

Azure Stack Meter ID is different with Azure Meter ID (Resource guid). 
It's really hard to check which Azure Stack Meter ID will bill our customers.
There is no document to compare with both IDs.

Please help mark each Azure Stack Meter ID which will generate cost, and add corresponding Azure Meter ID (Resource guid) to each ID. 
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e302294c-1c5d-4fe6-067f-0a23d631e64c
* Version Independent ID: 4978c005-a8df-6ed8-1613-aed749443c05
* Content: [Usage API FAQ - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-usage-related-faq?view=azs-2005)
* Content Source: [azure-stack/operator/azure-stack-usage-related-faq.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-usage-related-faq.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by Grace-MacJones-MSFT** [comment]
Hi @LingYi-Wu,  thanks for bringing this to our attention. Your feedback has been shared with the content owner for further review.

**Comment by sethmanheim** [comment]
@LingYi-Wu Thank you for reaching out and very sorry for the slow response. As we are moving to a new feedback system, we need to close older issues. If you still need assistance, please open a new feedback request. #please-close
