### ISSUE TITLE
Root Certificate not found on Stack VM

### ISSUE THREAD

**Issue by jgardner04** [MicrosoftDocs/azure-stack-docs#99]
Step 2 in the Prepare for the CLI does not seem to be accurate. After creating a VM on Stack (1.1903.2.39) there is no certificate with the label "AzureStackSelfSignedRootCert". 

Steps to reproduce:
Create a Windows Server 2016 Datacenter server on Azure Stack
Sign into the machine and open elevated PowerShell windows
Run the provided script to find the StackSelfSignedRootCert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 583c4bab-c16a-a723-04ac-b3265d9e8269
* Version Independent ID: e6ecb0ee-2303-a7ed-9fca-767e3d3bfe86
* Content: [Connect to Azure Stack with CLI](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-azurecli2#next-steps)
* Content Source: [azure-stack/user/azure-stack-version-profiles-azurecli2.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-version-profiles-azurecli2.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by TravisCragg-MSFT** [comment]
@jgardner04 As you are using 1903, I assume that this is a multi-node. 

The "AzureStackSelfSignedRootCert" is for the ASDK only, and this step is not needed for multi-node deployments. You should start [Here with the Set up the Virtual Machine Alias Endpoints](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-azurecli2#set-up-the-virtual-machine-aliases-endpoint).

The section titled [Trust the Azure Stack CA root certificate](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-version-profiles-azurecli2#trust-the-azure-stack-ca-root-certificate) is for the ASDK as well and can be skipped for multi-node deployments. 

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by jgardner04** [comment]
@TravisCragg-MSFT 👍 tie this up to RTM. Sorry about that!
