### ISSUE TITLE
VM overview blade does not show correct computer name

### ISSUE THREAD

**Issue by HassanAlmanasrah** [MicrosoftDocs/azure-stack-docs#992]
I would like to suggest the below modification, since it make confusion. In the below part:
**VM overview blade does not show correct computer name
Applicable: This issue applies to all releases.
Cause: When viewing details of a VM in the overview blade, the computer name shows as (not available). This is by design for VMs created from specialized disks/disk snapshots.
Remediation: View the Properties blade under Settings.**

- This known issue is not only for 2002, but also in 2005. maybe we need to add this to 2005 known issues
also, this doesn't apply only on Snapshot/Specialized disk images, but also market place images.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0094b74f-e85b-6983-5f58-ce24f825b63c
* Version Independent ID: a90feafe-0401-3da0-bb95-4dbc8868ea0f
* Content: [Azure Stack Hub known issues - Azure Stack Hub](https://docs.microsoft.com/en-gb/azure-stack/operator/known-issues?view=azs-2002#vm-overview-blade-does-not-show-correct-computer-name)
* Content Source: [azure-stack/operator/known-issues.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/known-issues.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by TravisCragg-MSFT** [comment]
@HassanAlmanasrah Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by sethmanheim** [comment]
@HassanAlmanasrah Thank you for catching that; we will add that known issue to 2005 as well as 2002. It should be live tomorrow after 10 AM PDT. Thanks again for the feedback! #please-close

**Comment by HassanAlmanasrah** [comment]
Hello Seth,

Thanks for the update. It has been mentioned under 2005. But still showing that this is applied on Specialized/Snapshot VMs, while in reality , this applies on Market place images as well.

﻿Best Regards
Hassan
