### ISSUE TITLE
CSV enabled by default or not

### ISSUE THREAD

**Issue by IbTornoe** [MicrosoftDocs/azure-stack-docs#993]
You may choose to use the CSV cache, or not – it's up to you. It is off by default in Storage Spaces Direct.
Thought that the CSV cache was enabled by default after 2012R2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f73eaa55-b596-53e5-bc97-d6730b70b721
* Version Independent ID: b940469f-9a0d-b119-e708-2c54f3e34e96
* Content: [Understanding the cache in Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/cache)
* Content Source: [azure-stack/hci/concepts/cache.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/hci/concepts/cache.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @khdownie
* Microsoft Alias: **v-kedow**

**Comment by khdownie** [comment]
@IbTornoe I am looking into this now. We definitely have some conflicting information in the docs. Thanks for this catch. I think that in Windows Server 2016, the CSV cache is off by default. In Windows Server 2019, it's on by default with 1 GB allocated. I will make this clarification and address the out of date Windows Server docs as well.

**Comment by khdownie** [comment]
This seems to change with every Windows Server release, so I'm not surprised we're pulling from outdated docs. This is the correct info, I think:

By default in Windows Server 2012, the CSV cache is disabled by default. 

In Windows Server 2012 R2, the CSV cache is enabled by default. However, you must still allocate the size of the block cache to reserve.

In Windows Server 2016, it's off by default.

In Windows Server 2019, it's on by default with 1 GB allocated.

**Comment by khdownie** [comment]
@IbTornoe @TravisCragg-MSFT this is now resolved in both the Windows Server and Azure Stack HCI repos, so this issue can be closed. Thanks again for the heads up.

**Comment by TravisCragg-MSFT** [comment]
@IbTornoe We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
