### ISSUE TITLE
master.zip should be changed to az.zip for az

### ISSUE THREAD

**Issue by bganapa** [MicrosoftDocs/azure-stack-docs#996]
# Change directory to the root directory.
here master.zip to az.zip

# Download the tools archive.
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 
invoke-webrequest `
  https://github.com/Azure/AzureStack-Tools/archive/az.zip `
  -OutFile master.zip

# Expand the downloaded files.
expand-archive master.zip `
  -DestinationPath . `
  -Force

# Change to the tools directory.
cd AzureStack-Tools-az

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52c26c4e-2806-66bd-a127-c23e45309403
* Version Independent ID: b9076003-9857-47ec-c2dc-64d3c8b65243
* Content: [Download Azure Stack Hub tools from GitHub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-download?view=azs-2005)
* Content Source: [azure-stack/operator/azure-stack-powershell-download.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-powershell-download.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by mattbriggs** [comment]
@bganapa Thanks! updating...

#in-progress

**Comment by mattbriggs** [comment]
article updated. https://github.com/MicrosoftDocs/azure-stack-docs-pr/pull/4831/commits/33367ed81e7d1a39990251d9e3689d0f8b3f98b3

#please-close
